import type { CasoDef } from '../types'

/**
 * agua — 10 dossiers, 10 of them with a live cross-reference.
 *
 * Every source URL was fetched and every query was resolved against the live
 * collection before this file was committed (scripts/verify-casos.ts re-checks
 * both). A caso with no `query` is not a gap in the research: its money does
 * not travel through the Compras Estatales feed at all, which `feedCoverage`
 * records and the page states outright.
 */
export const CASOS_AGUA: CasoDef[] = [
  {
    slug: 'proyecto-neptuno-arazati-contrato',
    emoji: '⚖️',
    theme: 'agua',
    period: '2023-2025',
    statusKind: 'judicial',
    status: 'denuncia',
    amountReported: 'US$ 890 millones de compromiso estatal a 20 años (Sudestada, diciembre de 2023; El Observador, julio de 2025); la inversión privada se publicó en US$ 210 millones según Brecha y en US$ 294 millones según El Observador',
    organisms: ['Administración de las Obras Sanitarias del Estado'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Administración de las Obras Sanitarias del Estado',
      ],
      search: 'planta potabilizadora',
      yearFrom: 2023,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'Sudestada', title: 'El Tribunal de Cuentas avala la inconstitucionalidad del proyecto Arazatí', url: 'https://www.sudestada.com.uy/articleId__2e44c806-d9f5-4992-b932-23d47ef797cd/10893/Detalle-de-Noticia', date: '2023-12-12' },
      { outlet: 'Brecha', title: 'Organizaciones sociales logran avance judicial en la lucha contra el Proyecto Neptuno: Un poco de aire', url: 'https://brecha.com.uy/un-poco-de-aire/', date: '2024-05-03' },
      { outlet: 'Subrayado', title: 'Juez impuso medida de "no innovar" y ordena a OSE no firmar contrato para construir planta en Arazatí', url: 'https://www.subrayado.com.uy/juez-impuso-medida-no-innovar-y-ordena-ose-no-firmar-contrato-construir-planta-arazati-n950016', date: '2024-06-24' },
      { outlet: 'la diaria', title: 'Presentaron acción judicial contra el proyecto Neptuno', url: 'https://ladiaria.com.uy/justicia/articulo/2024/8/presentaron-accion-judicial-contra-el-proyecto-neptuno/', date: '2024-08-12' },
      { outlet: 'Búsqueda', title: 'Proyecto Neptuno: organizaciones sociales apuntan a reclamar la nulidad del contrato en un nuevo juicio', url: 'https://www.busqueda.com.uy/informacion/proyecto-neptuno-organizaciones-sociales-apuntan-reclamar-la-nulidad-del-contrato-un-nuevo-juicio-n5397149', date: '2025-03-20' },
      { outlet: 'Montevideo Portal', title: 'Proyecto Neptuno: gobierno acordó con consorcio frenar ejecución del contrato por 90 días', url: 'https://www.montevideo.com.uy/Noticias/Proyecto-Neptuno-gobierno-acordo-con-consorcio-frenar-ejecucion-del-contrato-por-90-dias-uc920530', date: '2025-04-11' },
      { outlet: 'El Observador', title: 'Gobierno de Yamandú Orsi resolvió dejar sin efecto el proyecto Neptuno y ofreció al consorcio construir obras alternativas', url: 'https://www.elobservador.com.uy/nacional/gobierno-yamandu-orsi-resolvio-dejar-efecto-el-proyecto-neptuno-y-ofrecio-al-consorcio-construir-obras-alternativas-n6008821', date: '2025-07-16' },
    ],
    es: {
      title: 'Proyecto Neptuno: US$ 890 millones y una pelea judicial por Arazatí',
      dek: 'OSE adjudicó en 2023 una planta potabilizadora sobre el Río de la Plata con pago estatal a 20 años. Organizaciones sociales llevaron el contrato a la Justicia.',
      contexto: 'En 2023, durante el gobierno de Luis Lacalle Pou, OSE adjudicó al consorcio Aguas de Montevideo —integrado por Saceem, Berkes y Ciemsa— el llamado proyecto Neptuno: una planta potabilizadora en la playa de Arazatí, San José, que tomaría agua del Río de la Plata para abastecer al área metropolitana con 200.000 metros cúbicos diarios, según El Observador. El diseño, la construcción y el mantenimiento quedaban a cargo del consorcio privado y el Estado pagaría un canon anual durante casi dos décadas. Según Sudestada, el Tribunal de Cuentas resolvió el 23 de noviembre de 2023, por 4 votos a 3, no formular observaciones al gasto. Según Montevideo Portal, el contrato se firmó el 23 de enero de 2025, unas cinco semanas antes del cambio de gobierno.',
      hallazgo: 'Las cifras publicadas difieren según la fuente. Brecha informó en mayo de 2024 una inversión privada de unos US$ 210 millones y un canon estatal de unos US$ 50 millones anuales durante 17,5 años, cerca de US$ 800 millones en total. Sudestada detalló en diciembre de 2023 US$ 45,6 millones anuales por la obra durante 17,5 años más US$ 5 millones anuales por operación, y cifró el costo total en US$ 890 millones a 20 años; El Observador consignó en julio de 2025 una inversión estimada de US$ 294 millones y el mismo total de US$ 890 millones. La Comisión Nacional en Defensa del Agua y la Vida y la organización Tucu Tucu, patrocinadas por la Clínica de Litigio Estratégico de la Udelar, demandaron a OSE, al Ministerio de Ambiente y al Ministerio de Salud Pública sosteniendo, según la diaria, que el proyecto es inconstitucional porque habilita "la participación de privados en el suministro de agua potable". OSE respondió, según Sudestada, que "el abastecimiento de agua potable continúa a cargo, de manera exclusiva y directamente por OSE"; en esa misma nota la URSEA planteó que la prestación comprende desde la captación del agua cruda y su potabilización hasta el transporte a los usuarios. Según Búsqueda, el director de Saceem Alejandro Ruibal mencionó públicamente cifras de entre US$ 50 y US$ 60 millones como costo de una rescisión unilateral.',
      statusNote: 'El 24 de junio de 2024 el juez Alejandro Recarey dictó una medida de no innovar que impidió a OSE firmar el contrato, al entender que había "bases como para suponer que puede estarse ante un proceso de privatización parcial del suministro público de agua potable"; según Subrayado, el gobierno resolvió apelar esa sentencia. El contrato terminó firmándose el 23 de enero de 2025. Búsqueda informó que las organizaciones desistieron de ese juicio el 6 de febrero de 2025, que el juez Federico Tobía aceptó el desistimiento el 26 de febrero y que la Clínica de Litigio Estratégico preparaba un juicio ordinario para reclamar la nulidad del contrato. Al cierre de esta ficha (agosto de 2026) no constan en las fuentes consultadas novedades judiciales posteriores a marzo de 2025.',
      porQueImporta: 'El agua potable del área metropolitana la consumen más de un millón y medio de personas. El compromiso que se discute es un pago estatal a casi veinte años: lo que se firma hoy lo pagan los usuarios de OSE y los contribuyentes hasta mediados de la década de 2040, con independencia del gobierno de turno.',
      caveat: 'Los pagos por canon de un contrato de este tipo no se registran como compras corrientes en el portal de compras estatales, por lo que el cruce con datos abiertos puede mostrar sólo el llamado y contrataciones conexas, no el flujo anual comprometido. Las cifras de inversión y de compromiso total difieren entre medios y ninguna proviene de un documento contractual publicado.',
    },
    en: {
      title: 'Neptuno project: US$890 million and a court fight over Arazatí',
      dek: 'In 2023 OSE awarded a water treatment plant on the Río de la Plata with state payments over 20 years. Civil society groups took the contract to court.',
      contexto: 'In 2023, under Luis Lacalle Pou\'s government, OSE awarded the Aguas de Montevideo consortium — Saceem, Berkes and Ciemsa — the so-called Neptuno project: a drinking water plant at Arazatí beach, San José, drawing water from the Río de la Plata to supply the metropolitan area with 200,000 cubic metres a day, according to El Observador. Design, construction and maintenance fell to the private consortium, and the State would pay an annual fee for almost two decades. According to Sudestada, on 23 November 2023 the Court of Auditors decided by 4 votes to 3 not to raise objections to the spending. According to Montevideo Portal, the contract was signed on 23 January 2025, some five weeks before the change of government.',
      hallazgo: 'Published figures differ by source. In May 2024 Brecha reported private investment of around US$210 million and an annual state fee of some US$50 million over 17.5 years, close to US$800 million in total. In December 2023 Sudestada detailed US$45.6 million a year for the works over 17.5 years plus US$5 million a year for operation, putting the total cost at US$890 million over 20 years; in July 2025 El Observador cited an estimated investment of US$294 million and the same US$890 million total. The National Commission in Defence of Water and Life and the Tucu Tucu organisation, represented by the Udelar Strategic Litigation Clinic, sued OSE, the Environment Ministry and the Public Health Ministry, arguing — according to la diaria — that the project is unconstitutional because it allows "the participation of private actors in the supply of drinking water". OSE replied, according to Sudestada, that "the supply of drinking water remains the exclusive and direct responsibility of OSE"; in the same piece the regulator URSEA held that the service runs from the intake of raw water and its treatment through to delivery to users. According to Búsqueda, Saceem director Alejandro Ruibal publicly cited figures of US$50 to US$60 million as the cost of unilateral termination.',
      statusNote: 'On 24 June 2024 judge Alejandro Recarey issued an injunction barring OSE from signing the contract, holding there were "grounds to suppose this may be a process of partial privatisation of the public drinking water supply"; according to Subrayado, the government resolved to appeal that ruling. The contract was ultimately signed on 23 January 2025. Búsqueda reported that the organisations withdrew that case on 6 February 2025, that judge Federico Tobía accepted the withdrawal on 26 February, and that the Strategic Litigation Clinic was preparing an ordinary suit seeking annulment of the contract. As of this file\'s closing date (August 2026) the sources consulted record no judicial developments after March 2025.',
      porQueImporta: 'More than a million and a half people drink the metropolitan area\'s water. What is at stake is a state payment stretching almost twenty years: what is signed today will be paid by OSE\'s customers and by taxpayers into the mid-2040s, whichever government is in office.',
      caveat: 'Annual fee payments under this type of contract are not recorded as ordinary purchases on the state procurement portal, so cross-referencing open data may surface only the tender and related contracts, not the committed annual flow. The investment and total-commitment figures differ between outlets and none comes from a published contract document.',
    },
  },
  {
    slug: 'neptuno-renegociacion-observada-tribunal-cuentas',
    emoji: '🧾',
    theme: 'agua',
    period: '2025-2026',
    statusKind: 'auditoria',
    status: 'auditoria',
    amountReported: 'US$ 213 millones de inversión del consorcio y unos US$ 40 millones anuales de pagos por disponibilidad durante 18,5 años, unos US$ 740 millones en total (El Observador, marzo de 2026)',
    organisms: ['Administración de las Obras Sanitarias del Estado'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Administración de las Obras Sanitarias del Estado',
      ],
      search: 'planta potabilizadora',
      yearFrom: 2025,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'El Observador', title: 'Gobierno de Yamandú Orsi resolvió dejar sin efecto el proyecto Neptuno y ofreció al consorcio construir obras alternativas', url: 'https://www.elobservador.com.uy/nacional/gobierno-yamandu-orsi-resolvio-dejar-efecto-el-proyecto-neptuno-y-ofrecio-al-consorcio-construir-obras-alternativas-n6008821', date: '2025-07-16' },
      { outlet: 'Telenoche', title: 'Renegociación de Arazatí implica ahorro de 80 millones de dólares; obra Solís Chico se licitará aparte', url: 'https://www.telenoche.com.uy/nacionales/renegociacion-arazati-implica-ahorro-80-millones-dolares-obra-solis-chico-se-licitara-aparte-n5393664', date: '2025-12-19' },
      { outlet: 'El Observador', title: 'Tribunal de Cuentas observó reformulación del contrato del proyecto Neptuno impulsada por el gobierno de Orsi', url: 'https://www.elobservador.com.uy/nacional/tribunal-cuentas-observo-reformulacion-del-contrato-del-proyecto-neptuno-impulsada-el-gobierno-orsi-n6034988', date: '2026-02-19' },
      { outlet: 'UyPress', title: 'Proyecto Neptuno: Tribunal de Cuentas observó contrato de renegociación del actual gobierno por 4 votos a 3', url: 'https://www.uypress.net/Politica/Proyecto-Neptuno-Tribunal-de-Cuentas-observo-contrato-de-renegociacion-del-actual-gobierno-por-4-votos-a-3-uc150397', date: '2026-02-20' },
      { outlet: 'El Observador', title: 'Nueva potabilizadora en Aguas Corrientes: OSE y consorcio privado firman contrato pese a observación del Tribunal de Cuentas', url: 'https://www.elobservador.com.uy/nacional/nueva-potabilizadora-aguas-corrientes-ose-y-consorcio-privado-firman-contrato-observacion-del-tribunal-cuentas-n6036363', date: '2026-03-04' },
      { outlet: 'la diaria', title: 'OSE y el consorcio Aguas de Montevideo firmaron la modificación del contrato del proyecto Neptuno', url: 'https://ladiaria.com.uy/politica/articulo/2026/3/ose-y-el-consorcio-aguas-de-montevideo-firmaron-la-modificacion-del-contrato-del-proyecto-neptuno/', date: '2026-03-05' },
    ],
    es: {
      title: 'El Tribunal de Cuentas observó el nuevo contrato de Arazatí',
      dek: 'El gobierno de Orsi rehizo el contrato de Neptuno y mudó la planta a Aguas Corrientes. El Tribunal de Cuentas lo observó 4 a 3; el Ejecutivo reiteró el gasto.',
      contexto: 'El gobierno de Yamandú Orsi asumió en marzo de 2025 y en abril acordó con el consorcio Aguas de Montevideo congelar por 90 días la ejecución del contrato heredado. El 16 de julio de 2025, según El Observador, resolvió dejar sin efecto el proyecto Neptuno en su forma original y ofreció al consorcio construir obras alternativas, entre ellas una planta de tratamiento en Aguas Corrientes. La renegociación derivó en un contrato distinto: la planta potabilizadora ya no se construye en Arazatí sino en Aguas Corrientes, y la toma sigue siendo del río Santa Lucía. Según Telenoche, el gobierno sostuvo en diciembre de 2025 que el cambio implica un ahorro de más de US$ 80 millones, y que el embalse y la potabilizadora del Solís Chico quedan fuera del contrato y se licitarán por separado con financiamiento de organismos multilaterales.',
      hallazgo: 'El 19 de febrero de 2026 el Tribunal de Cuentas observó la modificación por 4 votos a 3. Según El Observador, su presidente Francisco Gallinal dijo que "se cambiaron muchas cosas como el lugar, el precio y hasta el mantenimiento" de la infraestructura y que la reformulación "lesiona la igualdad de los oferentes", porque con esas modificaciones el llamado original habría sido distinto y podrían haberse presentado otras empresas. UyPress citó el fallo de mayoría: los cambios "alteran sustancialmente el objeto del contrato, contraviniéndose así los principios de igualdad y concurrencia". Los tres ministros del Frente Amplio votaron en contra; Miguel Aumento sostuvo que se trata de una "reducción parcial de común acuerdo de las prestaciones objeto del contrato, respetando sus condiciones y modalidades". El Observador informó que el contrato se firmó igual: US$ 213 millones de inversión del consorcio y unos US$ 40 millones anuales de pagos por disponibilidad durante 18,5 años, unos US$ 740 millones, con un ahorro que el gobierno cifró en US$ 10 millones anuales respecto del contrato de Arazatí.',
      statusNote: 'El Poder Ejecutivo reiteró el gasto pese a la observación, mecanismo previsto en la normativa uruguaya, y OSE firmó la modificación con Saceem, Berkes y Ciemsa, según El Observador, el 4 de marzo de 2026; la diaria fechó la firma el 5 de marzo. Las obras estaban previstas para comenzar en mayo de 2026, sujetas a permisos ambientales, con un plazo de 30 meses y una capacidad de 200.000 metros cúbicos diarios. Al cierre de esta ficha (agosto de 2026) no constan en las fuentes consultadas novedades posteriores a marzo de 2026.',
      porQueImporta: 'Es uno de los contratos de agua potable más caros de la historia reciente del país y lo paga OSE con la factura de sus usuarios durante 18 años y medio. Que el órgano de control lo haya observado y el Ejecutivo lo haya reiterado no lo anula, pero deja registrado que el procedimiento fue cuestionado.',
      caveat: 'Los pagos por disponibilidad son un flujo contractual anual, no compras puntuales, por lo que difícilmente aparezcan como órdenes de compra en el portal estatal. El cruce puede alcanzar el llamado original y las contrataciones auxiliares.',
    },
    en: {
      title: 'The Court of Auditors flagged the new Arazatí contract',
      dek: 'Orsi\'s government rewrote the Neptuno contract and moved the plant to Aguas Corrientes. The Court of Auditors objected 4-3; the Executive reiterated the spending.',
      contexto: 'Yamandú Orsi\'s government took office in March 2025 and in April agreed with the Aguas de Montevideo consortium to freeze execution of the inherited contract for 90 days. On 16 July 2025, according to El Observador, it resolved to set aside the Neptuno project in its original form and offered the consortium alternative works, among them a treatment plant at Aguas Corrientes. The renegotiation produced a different contract: the plant is no longer built at Arazatí but at Aguas Corrientes, and the intake remains the Santa Lucía river. According to Telenoche, in December 2025 the government maintained the change means savings of more than US$80 million, and that the Solís Chico reservoir and treatment plant fall outside the contract and will be tendered separately with multilateral financing.',
      hallazgo: 'On 19 February 2026 the Court of Auditors objected to the amendment by 4 votes to 3. According to El Observador, its president Francisco Gallinal said "many things were changed, such as the location, the price and even the maintenance" of the infrastructure, and that the reformulation "harms equality among bidders", because with those changes the original tender would have been different and other firms could have bid. UyPress quoted the majority ruling: the changes "substantially alter the object of the contract, thereby contravening the principles of equality and open competition". The three Frente Amplio members voted against; Miguel Aumento held it is a "partial reduction by mutual agreement of the services covered by the contract, respecting its terms and arrangements". El Observador reported the contract was signed anyway: US$213 million of consortium investment and some US$40 million a year in availability payments over 18.5 years, around US$740 million, with savings the government put at US$10 million a year against the Arazatí contract.',
      statusNote: 'The Executive reiterated the spending despite the objection, a mechanism provided for in Uruguayan law, and OSE signed the amendment with Saceem, Berkes and Ciemsa on 4 March 2026, according to El Observador; la diaria dated the signing 5 March. Works were due to begin in May 2026, subject to environmental permits, with a 30-month schedule and capacity of 200,000 cubic metres a day. As of this file\'s closing date (August 2026) the sources consulted record no developments after March 2026.',
      porQueImporta: 'This is one of the most expensive drinking water contracts in the country\'s recent history, and OSE pays for it out of its customers\' bills for 18 and a half years. That the oversight body objected and the Executive reiterated the spending does not void it, but it puts on record that the procedure was questioned.',
      caveat: 'Availability payments are an annual contractual flow rather than discrete purchases, so they are unlikely to appear as purchase orders on the state portal. Cross-referencing can reach the original tender and ancillary contracts.',
    },
  },
  {
    slug: 'trasvase-rio-san-jose-santa-lucia',
    emoji: '🚧',
    theme: 'agua',
    period: '2023-2024',
    statusKind: 'gestion',
    status: 'inconcluso',
    amountReported: 'US$ 35 millones de costo total, de los cuales US$ 10,2 millones más IVA a las empresas constructoras (El Observador, julio de 2023); la obra se había anunciado en US$ 20 millones un mes antes',
    organisms: ['Administración de las Obras Sanitarias del Estado'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Administración de las Obras Sanitarias del Estado',
      ],
      search: 'tubería',
      yearFrom: 2023,
      yearTo: 2024,
    },
    sources: [
      { outlet: 'El Observador', title: 'Emergencia hídrica: calidad del agua de OSE seguirá empeorando y gobierno decidió exonerar de impuestos al agua embotellada', url: 'https://www.elobservador.com.uy/nota/calidad-del-agua-seguira-empeorando-y-gobierno-decidio-exonerar-de-impuestos-al-agua-embotellada-202361922500', date: '2023-06-20' },
      { outlet: 'El Observador', title: 'El trasvase del río San José se queda: así se aprovechará el millonario préstamo de OSE para las obras de emergencia por la crisis del agua', url: 'https://www.elobservador.com.uy/nota/el-millonario-prestamo-de-ose-para-las-obras-de-emergencia-y-la-utilidad-que-tendra-el-trasvase-del-rio-san-jose-en-el-futuro-202372720140', date: '2023-07-28' },
      { outlet: 'Brecha', title: 'Una obra de 35 millones de dólares: El costoso trasvase abandonado', url: 'https://brecha.com.uy/el-costoso-trasvase-abandonado/', date: '2024-04-26' },
      { outlet: 'UyPress', title: 'Se rompió parte de la obra de trasvase del río San José al Santa Lucía', url: 'https://www.uypress.net/Actualidad/Se-rompio-parte-de-la-obra-de-trasvase-del-rio-San-Jose-al-Santa-Lucia-uc136451', date: '2024-05-06' },
      { outlet: 'Brecha', title: 'La respuesta del gobierno sobre el costoso trasvase del río San José: Un provisorio permanente', url: 'https://brecha.com.uy/un-provisorio-permanente/', date: '2024-05-10' },
    ],
    es: {
      title: 'El trasvase de US$ 35 millones que funcionó pocos días',
      dek: 'OSE tendió unos 13 kilómetros de tubería del río San José al Santa Lucía en la sequía de 2023. Con las lluvias de marzo de 2024, el río rompió parte de la obra.',
      contexto: 'En junio de 2023, con la represa de Paso Severino cerca de su mínimo histórico, el gobierno de Luis Lacalle Pou anunció una obra de emergencia: trasvasar agua del río San José al Santa Lucía mediante una tubería entre Paso Valdéz y Paso Belastiquí. El Observador informó el 20 de junio de 2023 que la obra se anunciaba en US$ 20 millones y 13,5 kilómetros de tubería. Un mes después, el 28 de julio, el mismo medio consignó un costo total de US$ 35 millones, de los cuales US$ 10,2 millones más IVA se pagarían a las empresas constructoras —Espina, Cujó, Teyma, Stiler, Ciemsa y Saceem—, ubicó la tubería en 13,2 kilómetros, y detalló que OSE tomó un préstamo de US$ 25 millones a 12 meses y negociaba hasta US$ 60 millones con Fonplata. OSE la había planteado como temporal y terminó definiéndola como "definitiva y perdurable", con capacidad de sumar 2.500 kilómetros cuadrados de cuenca y 70 millones de metros cúbicos anuales.',
      hallazgo: 'Brecha publicó el 26 de abril de 2024 la nota "Una obra de 35 millones de dólares: el costoso trasvase abandonado". Citó al investigador Marcel Achkar, según quien el sistema "funcionó tres días" y, cuando empezó a llover, el desborde del San José "rompió la represa que hicieron". UyPress informó el 6 de mayo de 2024 que los contenedores usados en la obra nunca fueron retirados y terminaron arrastrados por el río en la zona de Puente Valdez, pese a que el Ministerio de Ambiente había anunciado un retiro paulatino. En una segunda nota, del 10 de mayo de 2024, Brecha señaló que las autoridades del Ministerio de Ambiente y de OSE respondieron que las obras serían permanentes, sin precisar plazos ni el costo de las modificaciones futuras en la toma y el represamiento; el diputado César Vega, del Partido Ecologista Radical Intransigente, cuestionó la demora, el costo final y la cantidad de días que la obra estuvo operativa.',
      statusNote: 'Al cierre de esta ficha (agosto de 2026) no constan en las fuentes consultadas novedades posteriores a las notas de Brecha y UyPress de mayo de 2024 sobre el destino final de la obra: no se publicó una rendición del costo definitivo, ni el resultado del retiro de los materiales que quedaron en el cauce, ni una evaluación oficial del volumen de agua efectivamente trasvasado durante la emergencia.',
      porQueImporta: 'Fue una de las obras más caras de la emergencia hídrica de 2023 y se pagó con endeudamiento de OSE. Saber cuántos metros cúbicos aportó realmente y en qué estado quedó no es un detalle contable: define si conviene reconstruirla o si el dinero debía ir a otra solución la próxima vez que falte agua.',
      caveat: 'El costo publicado es agregado y las cifras de longitud de la tubería difieren entre el anuncio de junio (13,5 km) y el relevamiento de julio (13,2 km). El portal de compras estatales puede mostrar órdenes de OSE por caños, bombeo y obra civil, pero repartidas en muchos expedientes de compra directa por urgencia, difíciles de sumar sin la lista oficial del expediente.',
    },
    en: {
      title: 'The US$35 million water transfer that ran for a few days',
      dek: 'OSE laid some 13 kilometres of pipe from the San José river to the Santa Lucía during the 2023 drought. With the March 2024 rains, the river broke part of the works.',
      contexto: 'In June 2023, with the Paso Severino reservoir near its historic low, Luis Lacalle Pou\'s government announced an emergency scheme: transferring water from the San José river to the Santa Lucía through a pipeline between Paso Valdéz and Paso Belastiquí. On 20 June 2023 El Observador reported the works were announced at US$20 million and 13.5 kilometres of pipe. A month later, on 28 July, the same outlet put the total cost at US$35 million, of which US$10.2 million plus VAT would go to the construction firms — Espina, Cujó, Teyma, Stiler, Ciemsa and Saceem — put the pipeline at 13.2 kilometres, and reported that OSE took a US$25 million 12-month loan and was negotiating up to US$60 million with Fonplata. OSE had framed it as temporary and ended up describing it as "definitive and lasting", capable of adding 2,500 square kilometres of catchment and 70 million cubic metres a year.',
      hallazgo: 'On 26 April 2024 Brecha published "A US$35 million project: the costly abandoned water transfer". It quoted researcher Marcel Achkar, according to whom the system "worked for three days" and, when it began to rain, the San José overflow "broke the dam they built". UyPress reported on 6 May 2024 that the containers used in the works were never removed and were swept away by the river near Puente Valdez, despite the Environment Ministry having announced a gradual removal. In a second article, on 10 May 2024, Brecha noted that Environment Ministry and OSE officials replied the works would be permanent, without specifying timelines or the cost of future changes to the intake and the dam; deputy César Vega, of the Radical Intransigent Ecologist Party, questioned the delay, the final cost and how many days the works were actually operating.',
      statusNote: 'As of this file\'s closing date (August 2026) the sources consulted record no developments after the Brecha and UyPress articles of May 2024 on the final fate of the works: no account of the definitive cost was published, nor the outcome of removing the materials left in the riverbed, nor an official assessment of how much water was actually transferred during the emergency.',
      porQueImporta: 'It was one of the most expensive projects of the 2023 water emergency and was paid for with OSE debt. Knowing how many cubic metres it actually delivered and what state it was left in is not an accounting detail: it determines whether rebuilding it is worthwhile or whether the money should go elsewhere the next time water runs short.',
      caveat: 'The published cost is an aggregate, and the pipeline length differs between the June announcement (13.5 km) and the July report (13.2 km). The state procurement portal may show OSE orders for pipes, pumping and civil works, but spread across many urgent direct-purchase files that are hard to add up without the official case listing.',
    },
  },
  {
    slug: 'trasvase-solis-chico-laguna-del-cisne',
    emoji: '🚱',
    theme: 'agua',
    period: '2021-2025',
    statusKind: 'gestion',
    status: 'inconcluso',
    amountReported: '$ 77 millones uruguayos (unos US$ 2 millones), tras haberse aprobado en $ 49 millones (El Observador, febrero de 2023)',
    organisms: ['Administración de las Obras Sanitarias del Estado'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Administración de las Obras Sanitarias del Estado',
      ],
      search: 'Laguna del Cisne',
      yearFrom: 2021,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'Búsqueda', title: 'OSE puede "sacrificar" la laguna del Cisne para resolver problema de abastecimiento, advierten Intendencia de Canelones y Udelar', url: 'https://www.busqueda.com.uy/Secciones/OSE-puede-sacrificar-la-laguna-del-Cisne-para-resolver-problema-de-abastecimiento-advierten-Intendencia-de-Canelones-y-Udelar-uc50473', date: '2021-12-08' },
      { outlet: 'El Observador', title: 'Trasvase del Solís Chico: la obra de US$ 2 millones para combatir la sequía que OSE no puede usar por fallas técnicas', url: 'https://www.elobservador.com.uy/nota/la-obra-de-us-2-millones-para-combatir-la-sequia-que-ose-no-puede-usar-por-fallas-tecnicas-202321717280', date: '2023-02-19' },
      { outlet: 'Telenoche', title: 'Renegociación de Arazatí implica ahorro de 80 millones de dólares; obra Solís Chico se licitará aparte', url: 'https://www.telenoche.com.uy/nacionales/renegociacion-arazati-implica-ahorro-80-millones-dolares-obra-solis-chico-se-licitara-aparte-n5393664', date: '2025-12-19' },
    ],
    es: {
      title: 'Trasvase al Cisne: una obra que OSE construyó y no pudo usar',
      dek: 'OSE llevó agua del arroyo Solís Chico a la Laguna del Cisne para abastecer la Costa de Oro. La salinidad y los permisos ambientales dejaron la obra sin uso.',
      contexto: 'OSE ejecutó un trasvase desde el arroyo Solís Chico hacia un afluente de la Laguna del Cisne, la fuente de agua de la Costa de Oro canaria, que abastece a unas 100.000 personas en verano y sufre cortes recurrentes. La obra se hizo mediante una ampliación de la adjudicación que la empresa Teyma tenía por el saneamiento de Ciudad de la Costa. Búsqueda informó el 8 de diciembre de 2021 que la Intendencia de Canelones y expertos de la Udelar advirtieron riesgos ambientales sobre el ecosistema de la laguna: el director Leonardo Herou dijo que no permitirían que "una solución de corto plazo nos hipoteque un recurso natural", y el biólogo Franco Teixeira (CURE) alertó por cambios en las comunidades bacterianas y por especies invasoras como carpas o mejillón dorado. Según esa nota, el trasvase ampliaría la cuenca captadora de 50 a 465 kilómetros cuadrados, con ingreso de nutrientes y plaguicidas desde un territorio mucho mayor. OSE describió entonces la operación como una "prueba temporal", iniciada en noviembre, que funcionó unos 15 días.',
      hallazgo: 'El Observador informó el 19 de febrero de 2023 que la obra había sido aprobada por $ 49 millones y terminó costando $ 77 millones —unos US$ 2 millones— tras detectarse que el agua llegaba con una salinidad siete veces mayor a la registrada en la laguna, lo que obligó a extender 1,4 kilómetros más de tubería. Según ese informe, en el trasvase realizado entre diciembre de 2022 y enero de 2023 el agua "se escurrió en el camino y no llegó", el bombeo resultó insuficiente y la instalación no completó las condiciones ambientales exigidas. En plena sequía, un directivo del organismo reconoció al medio: "Estamos haciendo los esfuerzos para poder usarla", pese a que técnicos y científicos entendían que no contaba con la autorización necesaria.',
      statusNote: 'En diciembre de 2025, según Telenoche, el gobierno anunció que la solución para la Costa de Oro se resolverá con obras nuevas: un embalse y una planta potabilizadora en el Solís Chico, que quedaron fuera del contrato renegociado de Arazatí y se licitarán por separado con financiamiento de organismos multilaterales. Al cierre de esta ficha (agosto de 2026) no constan en las fuentes consultadas novedades posteriores a diciembre de 2025 sobre el destino del trasvase ya construido.',
      porQueImporta: 'La Costa de Oro se queda sin agua todos los veranos. Se gastaron cerca de dos millones de dólares en una infraestructura que quedó sin uso y ahora se anuncia otra obra, mucho más cara, para el mismo problema. Es el costo de decidir antes de tener terminados los estudios ambientales.',
      caveat: 'Al haberse ejecutado como ampliación de un contrato de saneamiento ya adjudicado, el gasto puede no aparecer como un llamado propio en el portal de compras: conviene buscarlo dentro del expediente del saneamiento de Ciudad de la Costa.',
    },
    en: {
      title: 'Transfer to Laguna del Cisne: works OSE built and could not use',
      dek: 'OSE piped water from the Solís Chico stream to Laguna del Cisne to supply the Costa de Oro. Salinity and environmental permits left the works unused.',
      contexto: 'OSE carried out a transfer from the Solís Chico stream to a tributary of Laguna del Cisne, the water source for the Costa de Oro in Canelones, which supplies around 100,000 people in summer and suffers recurring cuts. The works were done through an extension of the contract the company Teyma already held for the Ciudad de la Costa sewerage scheme. On 8 December 2021 Búsqueda reported that the Canelones local government and Udelar experts warned of environmental risks to the lagoon\'s ecosystem: director Leonardo Herou said they would not allow "a short-term solution to mortgage a natural resource", and biologist Franco Teixeira (CURE) warned of changes to bacterial communities and of invasive species such as carp or golden mussel. According to that piece, the transfer would expand the catchment from 50 to 465 square kilometres, letting in nutrients and pesticides from a far larger territory. OSE described the operation at the time as a "temporary trial", begun in November, which ran for about 15 days.',
      hallazgo: 'On 19 February 2023 El Observador reported that the works had been approved at $49 million and ended up costing $77 million — around US$2 million — after it emerged that the incoming water was seven times saltier than the level recorded in the lagoon, forcing an extra 1.4 kilometres of pipe. According to that report, in the transfer carried out between December 2022 and January 2023 the water "drained away along the route and did not arrive", pumping proved insufficient, and the installation did not meet the required environmental conditions. In the middle of the drought, a board member told the outlet: "We are making efforts to be able to use it", even though technicians and scientists understood it lacked the necessary authorisation.',
      statusNote: 'In December 2025, according to Telenoche, the government announced that the solution for the Costa de Oro will come from new works: a reservoir and a treatment plant on the Solís Chico, which were left out of the renegotiated Arazatí contract and will be tendered separately with multilateral financing. As of this file\'s closing date (August 2026) the sources consulted record no developments after December 2025 on the fate of the transfer already built.',
      porQueImporta: 'The Costa de Oro runs short of water every summer. Close to two million dollars went into infrastructure that ended up unused, and now another, far more expensive scheme is announced for the same problem. That is the cost of deciding before the environmental studies are finished.',
      caveat: 'Because it was executed as an extension of an already awarded sewerage contract, the spending may not appear as a tender of its own on the procurement portal: it is best searched for inside the Ciudad de la Costa sewerage file.',
    },
  },
  {
    slug: 'saneamiento-interior-61-localidades',
    emoji: '🚽',
    theme: 'agua',
    period: '2024-2026',
    statusKind: 'auditoria',
    status: 'auditoria',
    amountReported: 'US$ 422.243.984 adjudicados con leyes sociales y sin IVA, unos US$ 73 millones por encima de los US$ 349 millones estimados en los estudios de factibilidad (El Observador, junio de 2024)',
    organisms: ['Administración de las Obras Sanitarias del Estado', 'Corporación Nacional para el Desarrollo'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Administración de las Obras Sanitarias del Estado',
      ],
      search: 'saneamiento',
      yearFrom: 2024,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'El Observador', title: 'Saneamiento, uno de los proyectos clave del gobierno de Lacalle Pou, costará US$ 70 millones más de lo anunciado', url: 'https://www.elobservador.com.uy/nacional/saneamiento-uno-los-proyectos-clave-del-gobierno-lacalle-pou-costara-us-70-millones-mas-lo-anunciado-n5944760', date: '2024-06-10' },
      { outlet: 'El Observador', title: '"Evasión a los procedimientos": la observación que el Tribunal de Cuentas le hizo a un proyecto de OSE', url: 'https://www.elobservador.com.uy/economia-y-empresas/evasion-los-procedimientos-la-observacion-que-el-tribunal-cuentas-le-hizo-un-proyecto-ose-n5989155', date: '2025-03-12' },
      { outlet: 'la diaria', title: 'OSE anunció en el Parlamento que se hará una "reformulación" del plan de saneamiento del gobierno anterior', url: 'https://ladiaria.com.uy/politica/articulo/2026/5/ose-anuncio-en-el-parlamento-que-se-hara-una-reformulacion-del-plan-de-saneamiento-del-gobierno-anterior/', date: '2026-05-06' },
      { outlet: 'Telenoche', title: 'OSE reformuló plan de saneamiento; según Pablo Ferreri, no tenía criterio técnico y excedía el presupuesto', url: 'https://www.telenoche.com.uy/nacionales/ose-reformulo-plan-saneamiento-segun-pablo-ferreri-no-tenia-criterio-tecnico-y-excedia-del-presupuesto-n5399235', date: '2026-05-06' },
    ],
    es: {
      title: 'Saneamiento en 61 localidades: US$ 73 millones más y un descalce',
      dek: 'OSE adjudicó en 2024 el mayor plan de saneamiento del interior por US$ 422 millones. El Tribunal de Cuentas observó su gestión y en 2026 el plan se rehizo.',
      contexto: 'Durante el gobierno de Luis Lacalle Pou, OSE adjudicó el proyecto de universalización del saneamiento en 61 localidades del interior al consorcio Saneamiento del Uruguay —integrado por Saceem, Ciemsa, Teyma y Fast— por US$ 422.243.984 con leyes sociales y sin IVA, según El Observador. Ese mismo medio informó el 10 de junio de 2024 que la cifra superaba en unos US$ 73 millones los US$ 349 millones estimados en los estudios de factibilidad aprobados a fines de 2022, y que el financiamiento combinaba un préstamo de Fonplata por US$ 325 millones con un subsidio parlamentario de hasta US$ 30 millones anuales durante 16 años. OSE atribuyó la diferencia a la variación del tipo de cambio (el dólar se había estimado a $ 44,7 y en marzo de 2024 estaba en $ 37,5), al aumento del IPC y a mejoras del proyecto, entre ellas más conexiones intradomiciliarias y cambios en operación y mantenimiento. En esa misma nota, el director frenteamplista Diego Pastorín advirtió que la participación de Fonplata había bajado del 92% al 66%, con una brecha de unos US$ 170 millones sin fuente clara.',
      hallazgo: 'El 12 de marzo de 2025 El Observador informó que el Tribunal de Cuentas observó el convenio de cooperación entre OSE y la Corporación Nacional para el Desarrollo para gestionar el proyecto, por entender que configuraba una "evasión a los procedimientos de contratación" y que no quedaba claro el objeto de las contrataciones. La contraprestación a la CND rondaba los $ 350 millones —más de US$ 8 millones— en cinco años, más un 4% e IVA mensual sobre lo ejecutado, honorarios de entre $ 120.000 y $ 140.000 más IVA por persona seleccionada y $ 6.200 más IVA por hora de asesoramiento técnico. El ministro del Tribunal Francisco Gallinal votó en contra de la observación: sostuvo que la CND tenía competencia legal para ejecutar el convenio y que su participación reducía costos para OSE. En mayo de 2026, ante la comisión parlamentaria, el presidente de OSE, Pablo Ferreri, anunció una reformulación: dijo que había un "descalce financiero" de US$ 260 millones, que el plan implicaba "una inversión de más de 500 millones de dólares, cuando el préstamo que se obtuvo con Fonplata era de 320 millones", y que las localidades se eligieron "sin ningún criterio técnico", con relevamientos hechos con drones y sin verificación en el terreno, al punto de incluir localidades que ya tenían redes.',
      statusNote: 'El plan está en reformulación. Según la diaria y Telenoche, Ferreri informó al Parlamento el 6 de mayo de 2026 que se revisará la lista de localidades y se incorporarán obras no previstas, como una planta de tratamiento en Mercedes por US$ 40 millones. El diputado nacionalista Juan Pablo Delgado cuestionó las demoras en ejecutar los contratos heredados de la administración anterior. Al cierre de esta ficha (agosto de 2026) no constan en las fuentes consultadas novedades posteriores a mayo de 2026.',
      porQueImporta: 'Uruguay tiene una cobertura de saneamiento muy despareja: en buena parte de las ciudades del interior las aguas servidas van a pozo negro. Que el plan cueste más de lo previsto y se rehaga a los dos años significa que localidades que estaban en la lista pueden quedar afuera o esperar varios años más.',
      caveat: 'Parte del dinero se ejecuta a través de un convenio con la Corporación Nacional para el Desarrollo y con préstamo de Fonplata, por lo que los pagos a las empresas pueden no figurar como compras directas de OSE en el portal estatal.',
    },
    en: {
      title: 'Sewerage in 61 towns: US$73 million more and a funding gap',
      dek: 'In 2024 OSE awarded the largest sewerage plan for the interior at US$422 million. The Court of Auditors flagged its management and in 2026 the plan was redrawn.',
      contexto: 'Under Luis Lacalle Pou\'s government, OSE awarded the project to universalise sewerage in 61 towns of the interior to the Saneamiento del Uruguay consortium — Saceem, Ciemsa, Teyma and Fast — for US$422,243,984 including social charges and excluding VAT, according to El Observador. The same outlet reported on 10 June 2024 that the figure exceeded by some US$73 million the US$349 million estimated in the feasibility studies approved in late 2022, and that financing combined a US$325 million Fonplata loan with a parliamentary subsidy of up to US$30 million a year for 16 years. OSE attributed the difference to the exchange rate (the dollar had been estimated at $44.7 and stood at $37.5 in March 2024), to inflation, and to project improvements including more in-home connections and changes to operation and maintenance. In the same piece, Frente Amplio board member Diego Pastorín warned that Fonplata\'s share had fallen from 92% to 66%, leaving a gap of about US$170 million with no clear source.',
      hallazgo: 'On 12 March 2025 El Observador reported that the Court of Auditors objected to the cooperation agreement between OSE and the National Development Corporation (CND) to manage the project, holding that it amounted to an "evasion of contracting procedures" and that the object of the contracts was not clear. The payment to CND was around $350 million — more than US$8 million — over five years, plus 4% and VAT monthly on funds executed, fees of $120,000 to $140,000 plus VAT per person recruited and $6,200 plus VAT per hour of technical advice. Court member Francisco Gallinal voted against the objection: he held that CND had the legal competence to execute the agreement and that its involvement reduced costs for OSE. In May 2026, before the parliamentary committee, OSE president Pablo Ferreri announced a reformulation: he said there was a US$260 million "funding mismatch", that the plan implied "an investment of more than 500 million dollars, when the loan obtained from Fonplata was 320 million", and that the towns were chosen "on no technical criterion", with surveys done by drone and without checks on the ground, to the point of including towns that already had networks.',
      statusNote: 'The plan is being reformulated. According to la diaria and Telenoche, Ferreri told Parliament on 6 May 2026 that the list of towns will be revised and unplanned works added, such as a treatment plant in Mercedes costing US$40 million. National Party deputy Juan Pablo Delgado questioned the delays in executing contracts inherited from the previous administration. As of this file\'s closing date (August 2026) the sources consulted record no developments after May 2026.',
      porQueImporta: 'Uruguay\'s sewerage coverage is very uneven: in much of the interior, wastewater still goes into cesspits. A plan that costs more than budgeted and is redrawn two years later means towns that were on the list may drop off it or wait several more years.',
      caveat: 'Part of the money flows through an agreement with the National Development Corporation and a Fonplata loan, so payments to the companies may not appear as direct OSE purchases on the state portal.',
    },
  },
  {
    slug: 'agua-no-contabilizada-ose',
    emoji: '💧',
    theme: 'agua',
    period: '2017-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'US$ 60 millones anunciados en medidores inteligentes y telemedición (Ámbito y Subrayado, agosto de 2025); alrededor del 50% del agua producida no se contabiliza ni se cobra',
    organisms: ['Administración de las Obras Sanitarias del Estado'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Administración de las Obras Sanitarias del Estado',
      ],
      search: 'medidores de agua',
      yearFrom: 2017,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Presidencia de la República', title: 'El 20 % de las pérdidas de agua no contabilizadas por OSE responde a conexiones clandestinas', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/20-perdidas-agua-contabilizadas-ose-responde-conexiones-clandestinas', date: '2017-05-15' },
      { outlet: 'la diaria', title: 'Presidente de OSE anunció un plan piloto de telemedición para reducir el 50% de agua que no se contabiliza', url: 'https://ladiaria.com.uy/politica/articulo/2025/8/presidente-de-ose-anuncio-un-plan-piloto-de-telemedicion-para-reducir-el-50-de-agua-que-no-se-contabiliza/', date: '2025-08-07' },
      { outlet: 'Ámbito', title: 'OSE invertirá u$s 60 millones en medidores inteligentes para reducir las pérdidas no facturadas', url: 'https://www.ambito.com/uruguay/ose-invertira-us-60-millones-medidores-inteligentes-reducir-las-perdidas-no-facturadas-n6175953', date: '2025-08-07' },
      { outlet: 'Subrayado', title: 'Presidente de OSE anunció plan piloto con medidores inteligentes y monitoreo en tiempo real del consumo de agua', url: 'https://www.subrayado.com.uy/presidente-ose-anuncio-plan-piloto-medidores-inteligentes-y-monitoreo-tiempo-real-del-consumo-agua-n984587', date: '2025-08-07' },
    ],
    es: {
      title: 'La mitad del agua que OSE produce no se cobra',
      dek: 'Desde 2017 el organismo reconoce que cerca del 50% del agua potabilizada se pierde o no se factura. En 2025 anunció US$ 60 millones en medidores inteligentes.',
      contexto: 'El indicador se llama agua no contabilizada: la diferencia entre el agua que OSE potabiliza y la que efectivamente factura. En mayo de 2017, el entonces presidente del organismo, Milton Machado, explicó en una comunicación de Presidencia que rondaba el 50% del agua entregada al sistema, con pérdidas físicas de entre 25% y 30% por fugas y pérdidas comerciales del orden del 20% —la mitad por fraude y la otra mitad por subsidios y situaciones irregulares—. Esa misma comunicación consignó que el 20% del total de las pérdidas se explicaba por conexiones clandestinas. OSE trabaja el problema con el Programa de Reducción de Agua No Contabilizada (RANC), que descentraliza decisiones e involucra a los operarios.',
      hallazgo: 'Ocho años después el porcentaje no bajó. El 7 de agosto de 2025, según la diaria, el presidente de OSE, Pablo Ferreri, afirmó que "el 50% del agua que se produce no se contabiliza o no se cobra" y desglosó unos 15 puntos por fraudes o mal funcionamiento de medidores y unos 35 puntos de pérdidas físicas. Ámbito y Subrayado informaron el mismo día que el organismo invertirá US$ 60 millones en medidores inteligentes y telemedición, con financiamiento de organismos internacionales, y que el plan piloto arrancaría a comienzos de 2027 en Salto y en algunas zonas de Montevideo antes de extenderse al resto del país. Ferreri dijo que "Salto será la prueba de la OSE del futuro, con aplicación de telemedición e internet de las cosas". OSE gestiona unas 1,12 millones de conexiones. Ninguna de las fuentes consultadas publicó cuánto dinero representa esa pérdida por año.',
      statusNote: 'El plan piloto de telemedición estaba anunciado para comenzar a principios de 2027 en Salto y zonas de Montevideo, financiado con un préstamo de un banco de desarrollo y con cerca de 20.000 medidores inteligentes previstos en la primera fase, según la diaria. Al cierre de esta ficha (agosto de 2026) no constan en las fuentes consultadas novedades posteriores al anuncio del 7 de agosto de 2025 sobre la adjudicación de los medidores ni sobre la evolución del indicador.',
      porQueImporta: 'Cada peso de la tarifa cubre el doble del agua que llega facturada: la mitad se va en caños rotos, medidores que no miden y conexiones irregulares. Es el mayor ahorro disponible sin construir una sola represa, y el que menos se discute cuando se anuncian obras de cientos de millones.',
      caveat: 'El porcentaje es un indicador de gestión, no un gasto, y las cifras de 2017 y 2025 provienen de declaraciones de los presidentes de OSE, no de una auditoría publicada. Lo rastreable en datos abiertos son las compras asociadas —medidores, macromedidores, equipos de detección de fugas y reposición de cañería—, dispersas en muchos llamados a lo largo de los años.',
    },
    en: {
      title: 'Half the water OSE produces is never billed',
      dek: 'Since 2017 the utility has acknowledged that about 50% of treated water is lost or unbilled. In 2025 it announced US$60 million for smart meters.',
      contexto: 'The indicator is called non-revenue water: the gap between what OSE treats and what it actually bills. In May 2017, then-president Milton Machado explained in a Presidency communication that it was around 50% of the water delivered into the system, with physical losses of 25% to 30% from leaks and commercial losses of about 20% — half from fraud and half from subsidies and irregular situations. The same communication stated that 20% of total losses was explained by clandestine connections. OSE addresses the problem through its Non-Revenue Water Reduction Programme (RANC), which decentralises decisions and involves field staff.',
      hallazgo: 'Eight years on, the percentage has not fallen. On 7 August 2025, according to la diaria, OSE president Pablo Ferreri stated that "50% of the water produced is not accounted for or not charged", breaking it down into some 15 points from fraud or faulty meters and some 35 points of physical losses. Ámbito and Subrayado reported the same day that the utility will invest US$60 million in smart meters and remote metering, financed by international bodies, with the pilot starting in early 2027 in Salto and parts of Montevideo before extending to the rest of the country. Ferreri said "Salto will be the test of the OSE of the future, applying remote metering and the internet of things". OSE manages some 1.12 million connections. None of the sources consulted published how much money that loss represents per year.',
      statusNote: 'The remote metering pilot was announced to start in early 2027 in Salto and parts of Montevideo, funded by a development bank loan and with close to 20,000 smart meters planned for the first phase, according to la diaria. As of this file\'s closing date (August 2026) the sources consulted record no developments after the 7 August 2025 announcement on the award of the meters or on the indicator\'s trajectory.',
      porQueImporta: 'Every peso of the tariff covers twice the water that gets billed: half goes to broken pipes, meters that do not measure and irregular connections. It is the largest saving available without building a single dam, and the one least discussed when hundred-million works are announced.',
      caveat: 'The percentage is a management indicator, not spending, and the 2017 and 2025 figures come from statements by OSE\'s presidents, not from a published audit. What is traceable in open data are the related purchases — meters, bulk meters, leak detection equipment and pipe replacement — scattered across many tenders over the years.',
    },
  },
  {
    slug: 'represa-casupa-licitacion-sin-aval-ambiental',
    emoji: '🏞️',
    theme: 'agua',
    period: '2025-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'US$ 130 millones de préstamo de la CAF: US$ 110 millones para la obra y US$ 20 millones para expropiaciones (Ámbito, mayo de 2026)',
    organisms: ['Administración de las Obras Sanitarias del Estado', 'Ministerio de Ambiente'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Administración de las Obras Sanitarias del Estado',
        'Dirección Nacional de Medio Ambiente',
      ],
      search: 'Casupá',
      yearFrom: 2025,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'En Perspectiva (Radiomundo)', title: 'Construcción de represa en Casupá pone en alerta a vecinos de la zona: reclaman más información del gobierno', url: 'https://enperspectiva.uy/en-perspectiva-programa/construccion-represa-casupa-alerta-vecinos-reclaman-informacion/', date: '2025-09-03' },
      { outlet: 'Ámbito', title: 'Edgardo Ortuño avanzará con la represa de Casupá, a pesar de no tener los estudios ambientales concluidos', url: 'https://www.ambito.com/uruguay/edgardo-ortuno-avanzara-la-represa-casupa-pesar-no-tener-los-estudios-ambientales-concluidos-n6283506', date: '2026-05-31' },
      { outlet: 'El Observador', title: 'Represa en Casupá: OSE adjudicará la licitación luego que la obra reciba la autorización ambiental', url: 'https://www.elobservador.com.uy/represa-casupa-ose-adjudicara-la-licitacion-luego-que-la-obra-reciba-la-autorizacion-ambiental-n6048851', date: '2026-06-27' },
    ],
    es: {
      title: 'Represa de Casupá: se licita antes de tener el aval ambiental',
      dek: 'OSE llamó a licitación la mayor reserva de agua del país con US$ 130 millones de la CAF, sin la autorización ambiental previa terminada.',
      contexto: 'La represa sobre el arroyo Casupá, en Florida, es la obra de reserva de agua para el área metropolitana que impulsa el gobierno de Yamandú Orsi. Según Ámbito, el embalse tendrá 118 millones de metros cúbicos y beneficiaría a 1.600.000 habitantes; el propio medio ubica la sequía de 2023 como el argumento de urgencia del proyecto. El financiamiento es un crédito de la CAF por US$ 130 millones: US$ 110 millones para la obra y US$ 20 millones para expropiaciones. Ámbito consignó que en diciembre de 2025 precalificaron ocho consorcios. El cronograma oficial prevé adjudicar a fines de 2026, empezar a construir en 2027 y terminar a mediados de 2029.',
      hallazgo: 'El cuestionamiento es de secuencia. El 31 de mayo de 2026, según Ámbito, el ministro de Ambiente Edgardo Ortuño afirmó: "No solo no vamos a detener el proyecto, sino que vamos a avanzar", y argumentó que licitar no es construir y que no habrá obra sin autorización ambiental. El senador nacionalista Martín Lema pidió suspender la licitación y calificó de "absolutamente improcedente e institucionalmente riesgoso" avanzar sin los estudios de impacto ambiental finalizados. En septiembre de 2025, En Perspectiva informó que unas 80 familias de la zona reclamaban más información, que se evaluaran los riesgos y un análisis técnico independiente: según ese informe, la obra inundaría casi 2.900 hectáreas, con 700 de zona de exclusión y 400 de monte nativo a talar, a diez kilómetros del pueblo de Casupá. En junio de 2026 El Observador publicó cifras oficiales distintas: 2.127 hectáreas de embalse, 3.467 de expropiación y unas 426 de bosque nativo a talar.',
      statusNote: 'El 27 de junio de 2026, según El Observador, el directorio de OSE aprobó el pliego de la licitación internacional y previó publicarlo la semana siguiente. El presidente del organismo, Pablo Ferreri, señaló que "la idea es adjudicar la obra después que reciba la autorización ambiental previa (AAP) por parte del Ministerio de Ambiente", trámite que seguía en revisión y que esperaban resolver antes de fin de año. El cronograma oficial ubica la finalización a mediados de 2029. Al cierre de esta ficha (agosto de 2026) no constan en las fuentes consultadas novedades posteriores a junio de 2026.',
      porQueImporta: 'Es la obra que debería evitar que se repita el verano de 2023, cuando el área metropolitana tomó agua salada. También inunda miles de hectáreas y se paga con un préstamo que devuelven los usuarios. Que la licitación corra antes que el aval ambiental condiciona la discusión: cuando llegue el informe, ya habrá ofertas sobre la mesa.',
      caveat: 'Las superficies afectadas difieren entre el relevamiento vecinal de 2025 (2.900 hectáreas inundadas) y las cifras oficiales de 2026 (2.127 de embalse y 3.467 de expropiación). Es una licitación internacional financiada por la CAF: el llamado debería ser rastreable, pero los pagos a la empresa adjudicataria pueden canalizarse por el préstamo y no aparecer como órdenes de compra corrientes de OSE.',
    },
    en: {
      title: 'Casupá dam: tendered before the environmental clearance',
      dek: 'OSE tendered the country\'s largest water reserve with US$130 million from CAF, without the prior environmental authorisation completed.',
      contexto: 'The dam on the Casupá stream, in Florida, is the water reserve project for the metropolitan area driven by Yamandú Orsi\'s government. According to Ámbito, the reservoir will hold 118 million cubic metres and would benefit 1,600,000 people; the same outlet points to the 2023 drought as the project\'s urgency argument. Financing is a CAF loan of US$130 million: US$110 million for the works and US$20 million for expropriations. Ámbito reported that eight consortia pre-qualified in December 2025. The official schedule foresees awarding the contract at the end of 2026, starting construction in 2027 and finishing in mid-2029.',
      hallazgo: 'The objection is about sequence. On 31 May 2026, according to Ámbito, Environment Minister Edgardo Ortuño said: "Not only will we not stop the project, we are going to move ahead", arguing that tendering is not building and that there will be no works without environmental authorisation. National Party senator Martín Lema asked for the tender to be suspended and called moving ahead without completed environmental impact studies "absolutely improper and institutionally risky". In September 2025, En Perspectiva reported that some 80 local families were demanding more information, an assessment of the risks and an independent technical analysis: according to that report, the works would flood almost 2,900 hectares, with 700 of exclusion zone and 400 of native forest to be felled, ten kilometres from the town of Casupá. In June 2026 El Observador published different official figures: 2,127 hectares of reservoir, 3,467 of expropriation and some 426 of native forest to be felled.',
      statusNote: 'On 27 June 2026, according to El Observador, OSE\'s board approved the international tender documents and planned to publish them the following week. The utility\'s president, Pablo Ferreri, said "the idea is to award the works after it receives the prior environmental authorisation (AAP) from the Environment Ministry", a process still under review that they expected to resolve before year\'s end. The official schedule places completion in mid-2029. As of this file\'s closing date (August 2026) the sources consulted record no developments after June 2026.',
      porQueImporta: 'This is the project meant to prevent a repeat of the summer of 2023, when the metropolitan area drank salty water. It also floods thousands of hectares and is paid for with a loan that customers repay. Running the tender ahead of the environmental clearance shapes the debate: by the time the report lands, bids will already be on the table.',
      caveat: 'The affected areas differ between the 2025 residents\' account (2,900 hectares flooded) and the 2026 official figures (2,127 of reservoir and 3,467 of expropriation). This is an international tender financed by CAF: the call should be traceable, but payments to the winning company may flow through the loan and not appear as ordinary OSE purchase orders.',
    },
  },
  {
    slug: 'crisis-hidrica-2023-gasto-emergencia',
    emoji: '🥤',
    theme: 'agua',
    period: '2023',
    statusKind: 'debate',
    status: 'debate',
    amountReported: 'más de US$ 70 millones informados por el Poder Ejecutivo en agosto de 2023; unos US$ 10 millones de renuncia fiscal estimada por la exoneración de IVA e IMESI al agua embotellada',
    organisms: ['Administración de las Obras Sanitarias del Estado'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Administración de las Obras Sanitarias del Estado',
      ],
      yearFrom: 2023,
      yearTo: 2023,
    },
    sources: [
      { outlet: 'El Observador', title: 'Emergencia hídrica: calidad del agua de OSE seguirá empeorando y gobierno decidió exonerar de impuestos al agua embotellada', url: 'https://www.elobservador.com.uy/nota/calidad-del-agua-seguira-empeorando-y-gobierno-decidio-exonerar-de-impuestos-al-agua-embotellada-202361922500', date: '2023-06-20' },
      { outlet: 'la diaria', title: 'Compras de OSE por la crisis hídrica fueron "tardías" y caras, denuncian la oposición y el sindicato', url: 'https://ladiaria.com.uy/politica/articulo/2023/7/compras-de-ose-por-la-crisis-hidrica-fueron-tardias-y-caras-denuncian-la-oposicion-y-el-sindicato/', date: '2023-07-22' },
      { outlet: 'Subrayado', title: 'Más de USD 70 millones invertidos en emergencia hídrica: se distribuyeron 66 millones de litros de agua embotellada', url: 'https://www.subrayado.com.uy/mas-usd-70-millones-invertidos-emergencia-hidrica-se-distribuyeron-66-millones-litros-agua-embotellada-n924035', date: '2023-08-23' },
      { outlet: 'Ámbito', title: 'Crisis del agua: el gobierno invirtió más de u$s 70 M en el marco de la emergencia hídrica', url: 'https://www.ambito.com/uruguay/crisis-del-agua-el-gobierno-invirtio-mas-us-70-m-el-marco-la-emergencia-hidrica-n5803360', date: '2023-08-24' },
    ],
    es: {
      title: 'Crisis hídrica de 2023: más de US$ 70 millones en emergencia',
      dek: 'El gobierno repartió 66 millones de litros de agua embotellada y exoneró impuestos. La oposición y el sindicato dijeron que las compras fueron tardías y caras.',
      contexto: 'Entre mayo y agosto de 2023, la peor sequía en décadas dejó al área metropolitana bebiendo agua del Río de la Plata mezclada con la del Santa Lucía, con la represa de Paso Severino cerca de su mínimo histórico de unos 3 millones de metros cúbicos. Para estirar las reservas, se elevaron los máximos de la norma: El Observador informó el 20 de junio de 2023 que se pasó de 280 a 720 miligramos por litro de cloruros y de 200 a 440 de sodio. Ese mismo día se anunció la exoneración de IVA (22%) e IMESI (10,5% por litro) al agua embotellada, con una renuncia fiscal estimada en US$ 10 millones, además de una barrera provisoria en Buschental para frenar el ingreso de agua salada al río San José y la tubería de trasvase del mismo río.',
      hallazgo: 'El 23 y 24 de agosto de 2023, al anunciar el fin de la emergencia, el presidente Luis Lacalle Pou informó que el Estado había invertido más de US$ 70 millones, según Subrayado y Ámbito: 66 millones de litros de agua embotellada distribuidos, apoyo económico a más de 500.000 personas —entre ellas jubilados y población vulnerable—, la obra de trasvase y las exoneraciones impositivas. El Ministerio de Economía se comprometió a dar a conocer cifras ajustadas. Un mes antes, el 22 de julio de 2023, la diaria había recogido las denuncias de la oposición y del sindicato FFOSE: sostenían que las compras de emergencia de OSE fueron tardías y por eso más caras, y que si se hubieran iniciado al declararse la emergencia agropecuaria en octubre de 2022, o al restringirse el uso del agua potable en febrero de 2023, habrían costado menos. El entonces director por el Frente Amplio en OSE, Edgardo Ortuño, habló de un "encarecimiento de estas obras de emergencia por haber sido planteadas en forma tardía" y advirtió que el organismo quedaría con presupuesto en rojo.',
      statusNote: 'La emergencia hídrica se levantó en agosto de 2023 tras las lluvias, y el apoyo económico para comprar agua embotellada se mantuvo hasta setiembre. Al cierre de esta ficha (agosto de 2026) no consta en las fuentes consultadas una rendición desagregada oficial del gasto total: la cifra de más de US$ 70 millones sigue siendo la comunicada por el Poder Ejecutivo en agosto de 2023, y las "cifras ajustadas" que el Ministerio de Economía prometió entonces no aparecen publicadas.',
      porQueImporta: 'Durante tres meses, tomar agua segura pasó a ser un gasto del bolsillo: las familias compraron botellas y el Estado repartió litros. Saber cuánto costó cada litro, a quién se le compró y si se pudo comprar antes es la única forma de que la próxima sequía —que va a llegar— no se pague dos veces.',
      caveat: 'Las compras se hicieron por vía de urgencia y el reparto de agua embotellada involucró a más de un organismo, no sólo a OSE. Además, la renuncia fiscal por la exoneración de impuestos no es una compra: es dinero público que se dejó de percibir y no figura en el portal estatal.',
    },
    en: {
      title: '2023 water crisis: over US$70 million in emergency spending',
      dek: 'The government handed out 66 million litres of bottled water and waived taxes. The opposition and the union said the purchases were late and expensive.',
      contexto: 'Between May and August 2023, the worst drought in decades left the metropolitan area drinking Río de la Plata water mixed with the Santa Lucía\'s, with the Paso Severino reservoir near its historic low of about 3 million cubic metres. To stretch reserves, the regulatory limits were raised: El Observador reported on 20 June 2023 that chlorides went from 280 to 720 milligrams per litre and sodium from 200 to 440. That same day the government announced waiving VAT (22%) and IMESI (10.5% per litre) on bottled water, with an estimated fiscal cost of US$10 million, plus a temporary barrier at Buschental to stop salt water entering the San José river and the transfer pipeline on that same river.',
      hallazgo: 'On 23 and 24 August 2023, announcing the end of the emergency, President Luis Lacalle Pou said the State had invested more than US$70 million, according to Subrayado and Ámbito: 66 million litres of bottled water distributed, financial support for more than 500,000 people — including pensioners and vulnerable households — the transfer works and the tax waivers. The Economy Ministry undertook to release adjusted figures. A month earlier, on 22 July 2023, la diaria had reported the claims of the opposition and the FFOSE union: they argued OSE\'s emergency purchases were late and therefore more expensive, and that had they started when the agricultural emergency was declared in October 2022, or when drinking water use was restricted in February 2023, they would have cost less. Edgardo Ortuño, then Frente Amplio board member at OSE, spoke of "a rise in the cost of these emergency works because they were raised late" and warned the utility would be left with its budget in the red.',
      statusNote: 'The water emergency was lifted in August 2023 after the rains, and the financial support for buying bottled water ran until September. As of this file\'s closing date (August 2026) the sources consulted contain no official itemised account of total emergency spending: the figure of more than US$70 million remains the one communicated by the Executive in August 2023, and the "adjusted figures" the Economy Ministry promised do not appear to have been published.',
      porQueImporta: 'For three months, drinking safe water became an out-of-pocket expense: families bought bottles and the State handed out litres. Knowing what each litre cost, who it was bought from and whether it could have been bought earlier is the only way the next drought — and there will be one — is not paid for twice.',
      caveat: 'The purchases were made under urgency procedures and the bottled water distribution involved more than one public body, not only OSE. The revenue forgone through the tax waiver is also not a purchase: it is public money not collected and does not appear on the state portal.',
    },
  },
  {
    slug: 'cuenca-santa-lucia-planes-sin-resultado',
    emoji: '🧪',
    theme: 'agua',
    period: '2013-2025',
    statusKind: 'gestion',
    status: 'sin-resolver',
    amountReported: 'US$ 72 millones anunciados por OSE en 2015 para filtros: US$ 60 millones en Aguas Corrientes y US$ 12 millones en Laguna del Sauce (Presidencia de la República)',
    organisms: ['Administración de las Obras Sanitarias del Estado', 'Ministerio de Ambiente'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Administración de las Obras Sanitarias del Estado',
        'Dirección Nacional de Medio Ambiente',
      ],
      search: 'activado',
      yearFrom: 2013,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'Presidencia de la República', title: 'OSE invertirá US$ 72 millones para optimizar calidad de agua potable', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/ose-invertira-us-72-millones-para-optimizar-calidad-agua-potable', date: '2015-06-05' },
      { outlet: 'Brecha', title: 'A pesar de los planes, la cuenca del Santa Lucía sigue en estado crítico: Como agua entre los dedos', url: 'https://brecha.com.uy/como-agua-entre-los-dedos/', date: '2024-04-26' },
      { outlet: 'la diaria', title: 'Ojo con el Plan de Riego: reportan que tajamares y embalses son la fuente de cianobacterias que afectan a OSE en Aguas Corrientes', url: 'https://ladiaria.com.uy/ciencia/articulo/2025/3/ojo-con-el-plan-de-riego-reportan-que-tajamares-y-embalses-son-la-fuente-de-cianobacterias-que-afectan-a-ose-en-aguas-corrientes/', date: '2025-03-22' },
      { outlet: 'la diaria', title: '"Nuestros cuerpos de agua están enfermos": reportan que cianobacterias ponen en peligro la red de distribución de agua potable', url: 'https://ladiaria.com.uy/ambiente/articulo/2025/6/nuestros-cuerpos-de-agua-estan-enfermos-reportan-que-cianobacterias-ponen-en-peligro-la-red-de-distribucion-de-agua-potable/', date: '2025-06-03' },
      { outlet: 'Ministerio de Ambiente', title: 'Plan de Acción para la Protección del Agua en la Cuenca del Santa Lucía', url: 'https://www.gub.uy/ministerio-ambiente/politicas-y-gestion/plan-accion-para-proteccion-del-agua-cuenca-del-santa-lucia' },
    ],
    es: {
      title: 'Trece años de planes y el Santa Lucía sigue igual',
      dek: 'El río que abastece al 60% del país tiene los mayores niveles de fósforo y nitrógeno. Hubo planes en 2013, 2017 y 2023; los académicos dicen que casi no se aplicaron.',
      contexto: 'Tras la crisis de sabor del agua de 2013, el Estado creó el Plan de Acción para la Protección del Agua en la Cuenca del Río Santa Lucía. Según el Ministerio de Ambiente, el plan reúne once medidas —mejora del cumplimiento ambiental de los vertimientos industriales y domésticos, tratamiento de efluentes en tambos, restricción de nuevos corrales de engorde a cielo abierto, zonas de amortiguación para restaurar la vegetación ribereña, planes de uso y manejo de suelos y la declaración de los arroyos Casupá y El Soldado como reservas de agua potable— y se apoya en la Comisión de Cuenca creada por el Decreto 106/13. En paralelo, en junio de 2015 Presidencia anunció una inversión de OSE de US$ 72 millones en filtros: US$ 60 millones en Aguas Corrientes y US$ 12 millones en Laguna del Sauce, con carbón activado granular y pruebas de ozonización para mitigar eventos de olor y sabor.',
      hallazgo: 'Brecha publicó el 26 de abril de 2024 que, pese a tres planes de acción sucesivos —2013, 2017 y 2023—, la cuenca sigue presentando los niveles más altos de fósforo y nitrógeno del país. Citó al investigador Ismael Díaz, de la Facultad de Ciencias de la Udelar, según quien "la lentitud en la aplicación de las medidas es alarmante porque prácticamente no se ha hecho" casi nada, y a Marcel Achkar, de REDES-Amigos de la Tierra, que resumió el problema del lado del gasto: "cualquier agua se puede potabilizar. El problema es el costo". La diaria informó el 22 de marzo de 2025 sobre un relevamiento que ubica en tajamares y embalses agropecuarios de la cuenca el origen de las cianobacterias que llegan a Aguas Corrientes —exportadas al río en los eventos de lluvia intensa—, la planta desde la que OSE potabiliza para el 60% de los habitantes del país.',
      statusNote: 'La diaria informó el 3 de junio de 2025 que el proyecto interdisciplinario "Agua y salud" reportó presencia generalizada de cianobacterias en los cuerpos de agua superficiales del país, con plantas potabilizadoras que dejaron de funcionar, a partir de datos de agua bruta recopilados por la propia OSE. Al cierre de esta ficha (agosto de 2026) no constan en las fuentes consultadas novedades posteriores a junio de 2025 sobre una evaluación oficial del grado de cumplimiento de las medidas del plan de cuenca.',
      porQueImporta: 'Cuanto peor está el río, más caro sale potabilizarlo: carbón activado, coagulantes, ozono y plantas nuevas los paga OSE con la factura del usuario. Prevenir la contaminación en la cuenca compite, dentro del mismo presupuesto, con tratar el agua ya contaminada aguas abajo.',
      caveat: 'El diagnóstico de incumplimiento proviene de investigadores académicos y de la prensa, no de una auditoría oficial. El cruce con datos abiertos alcanza a los insumos de potabilización y al monitoreo, no al cumplimiento del plan de cuenca, que depende de medidas regulatorias sobre actores privados y no genera compras del Estado.',
    },
    en: {
      title: 'Thirteen years of plans and the Santa Lucía is unchanged',
      dek: 'The river supplying 60% of the country has the highest phosphorus and nitrogen levels. Plans came in 2013, 2017 and 2023; academics say they were barely applied.',
      contexto: 'After the 2013 water taste crisis, the State created the Action Plan for the Protection of Water in the Santa Lucía River Basin. According to the Environment Ministry, the plan brings together eleven measures — improved environmental compliance for industrial and domestic discharges, effluent treatment on dairy farms, restrictions on new open-air feedlots, buffer zones to restore riparian vegetation, soil use and management plans, and the designation of the Casupá and El Soldado streams as drinking water reserves — and rests on the Basin Commission created by Decree 106/13. In parallel, in June 2015 the Presidency announced an OSE investment of US$72 million in filters: US$60 million at Aguas Corrientes and US$12 million at Laguna del Sauce, with granular activated carbon and ozonation trials to mitigate taste and odour events.',
      hallazgo: 'On 26 April 2024 Brecha reported that, despite three successive action plans — 2013, 2017 and 2023 — the basin still shows the highest phosphorus and nitrogen levels in the country. It quoted researcher Ismael Díaz, of the Udelar Faculty of Sciences, according to whom "the slowness in applying the measures is alarming because practically nothing has been done", and Marcel Achkar, of REDES-Friends of the Earth, who summed up the spending side: "any water can be made drinkable. The problem is the cost". On 22 March 2025 la diaria reported on a survey tracing the cyanobacteria reaching Aguas Corrientes to farm ponds and reservoirs in the basin — exported into the river during heavy rainfall events — the plant from which OSE supplies 60% of the country\'s inhabitants.',
      statusNote: 'On 3 June 2025 la diaria reported that the interdisciplinary project "Water and health" found cyanobacteria to be widespread in the country\'s surface water bodies, with some treatment plants having stopped operating, based on raw water data collected by OSE itself. As of this file\'s closing date (August 2026) the sources consulted record no developments after June 2025 regarding an official assessment of compliance with the basin plan\'s measures.',
      porQueImporta: 'The worse the river gets, the more expensive treatment becomes: activated carbon, coagulants, ozone and new plants are all paid for by OSE out of customers\' bills. Preventing pollution in the basin competes, within the same budget, with treating already contaminated water downstream.',
      caveat: 'The non-compliance diagnosis comes from academic researchers and the press, not from an official audit. Cross-referencing open data reaches treatment inputs and monitoring, not compliance with the basin plan, which depends on regulatory measures over private actors and generates no state purchases.',
    },
  },
  {
    slug: 'ose-deficit-tarifa-plan-inversiones',
    emoji: '💸',
    theme: 'agua',
    period: '2024-2026',
    statusKind: 'gestion',
    status: 'debate',
    amountReported: 'aumento tarifario de 7% desde enero de 2025 y una propuesta de 8,5% para enero de 2026, de la cual 3,7 puntos se destinan a corregir desequilibrios y financiar el plan de inversiones',
    organisms: ['Administración de las Obras Sanitarias del Estado'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Administración de las Obras Sanitarias del Estado',
      ],
      search: 'arrendamiento',
      yearFrom: 2024,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'la diaria', title: 'OPP instó a OSE a "reducir gastos" por aumento imprevisto de déficit y en el FA aseguran que la empresa estatal está totalmente desfinanciada', url: 'https://ladiaria.com.uy/politica/articulo/2024/8/opp-insto-a-ose-a-reducir-gastos-por-aumento-imprevisto-de-deficit-y-en-el-fa-aseguran-que-la-empresa-estatal-esta-totalmente-desfinanciada/', date: '2024-08-05' },
      { outlet: 'Ámbito', title: 'OSE empezará el año con aumento, ¿de cuánto será?', url: 'https://www.ambito.com/uruguay/ose-empezara-el-ano-aumento-de-cuanto-sera-n6097570', date: '2024-12-28' },
      { outlet: 'la diaria', title: 'OSE propuso al Poder Ejecutivo un aumento de tarifas de 8,5% desde el 1° de enero', url: 'https://ladiaria.com.uy/economia/articulo/2025/12/ose-propuso-al-poder-ejecutivo-un-aumento-de-tarifas-de-85-desde-el-1-de-enero/', date: '2025-12-26' },
    ],
    es: {
      title: 'Quién paga el plan de obras de OSE: la factura del usuario',
      dek: 'La OPP pidió a OSE reducir gastos por desvíos financieros en 2024. Un año después el organismo propuso subir la tarifa 8,5% para financiar sus inversiones.',
      contexto: 'OSE encara al mismo tiempo el mayor plan de inversiones de su historia —la nueva potabilizadora de Aguas Corrientes, la represa de Casupá, el saneamiento del interior y la renovación de redes— y arrastra las consecuencias financieras de la emergencia hídrica de 2023. La diaria informó el 5 de agosto de 2024 que el director de la Oficina de Planeamiento y Presupuesto, Fernando Blanco, notificó en junio al presidente de OSE por "importantes desvíos" respecto del programa financiero acordado en febrero de ese año, que preveía un superávit de 1.553.666 miles de pesos y que para abril mostraba un déficit global. La OPP le pidió reducir gastos y señaló, entre otros puntos, que el personal tercerizado tiene "un costo muy superior a lo que es un funcionario de OSE".',
      hallazgo: 'En esa misma nota, dirigentes del Frente Amplio —entonces en la oposición— sostuvieron que la empresa estatal estaba "totalmente desfinanciada" y que el sobrecosto se terminaría pagando "a través de la factura". La tarifa subió: Ámbito informó el 28 de diciembre de 2024 que el directorio aprobó un aumento de 7% desde el 1° de enero de 2025 —por encima de la inflación esperada, proyectada en 5,2% para ese año y muy por encima del 3% de UTE y el 5% de Antel—, con los votos del presidente Raúl Montero y la vicepresidenta Susana Montaner, y el voto en contra del director frenteamplista Diego Pastorín; el ajuste requería aval del Poder Ejecutivo. Un año después, ya con el Frente Amplio en el gobierno, la diaria informó el 26 de diciembre de 2025 que OSE propuso un aumento de 8,5% desde el 1° de enero de 2026 —4,8% para hogares vulnerables—, del cual 4,8 puntos corresponden a la evolución de costos y 3,7 puntos a "corregir desequilibrios estructurales" de la empresa y afrontar "el plan de inversiones más ambicioso de la historia del organismo".',
      statusNote: 'Al 26 de diciembre de 2025 la propuesta de 8,5% había sido enviada al Poder Ejecutivo para su estudio y la decisión seguía pendiente, según la diaria. Al cierre de esta ficha (agosto de 2026) no constan en las fuentes consultadas novedades posteriores a diciembre de 2025 sobre la resolución final del ajuste tarifario ni sobre el resultado financiero cerrado del organismo.',
      porQueImporta: 'Todas las obras de agua que se anuncian —la potabilizadora, la represa, el saneamiento— terminan en el mismo lugar: la factura mensual de OSE. Cuando 3,7 puntos de un aumento tarifario se destinan explícitamente a financiar inversiones, el usuario está adelantando plata para obras que va a usar recién dentro de varios años.',
      caveat: 'La tarifa y el resultado financiero no son compras y no aparecen en el portal de compras estatales. Lo que sí puede rastrearse son los gastos operativos de OSE —servicios tercerizados, mantenimiento de redes, arrendamientos— que la OPP señaló como desvío.',
    },
    en: {
      title: 'Who pays for OSE\'s works plan: the customer\'s bill',
      dek: 'The budget office told OSE to cut spending over financial deviations in 2024. A year later the utility proposed an 8.5% tariff rise to fund its investments.',
      contexto: 'OSE is simultaneously undertaking the largest investment plan in its history — the new Aguas Corrientes treatment plant, the Casupá dam, sewerage in the interior and network renewal — while carrying the financial aftermath of the 2023 water emergency. On 5 August 2024 la diaria reported that the head of the Planning and Budget Office, Fernando Blanco, notified OSE\'s president in June about "significant deviations" from the financial programme agreed in February that year, which projected a surplus of 1,553,666 thousand pesos and by April showed an overall deficit. The budget office asked OSE to cut spending and noted, among other points, that outsourced staff carry "a cost far higher than an OSE employee".',
      hallazgo: 'In the same article, Frente Amplio figures — then in opposition — argued the state utility was "completely defunded" and that the extra cost would end up being paid "through the bill". The tariff did rise: Ámbito reported on 28 December 2024 that the board approved a 7% increase from 1 January 2025 — above expected inflation, projected at 5.2% for that year and well above UTE\'s 3% and Antel\'s 5% — with votes from president Raúl Montero and vice-president Susana Montaner, and a vote against from Frente Amplio board member Diego Pastorín; the adjustment still required Executive approval. A year later, with the Frente Amplio now in government, la diaria reported on 26 December 2025 that OSE proposed an 8.5% rise from 1 January 2026 — 4.8% for vulnerable households — of which 4.8 points reflect cost movements and 3.7 points are to "correct structural imbalances" at the company and take on "the most ambitious investment plan in the organisation\'s history".',
      statusNote: 'As of 26 December 2025 the 8.5% proposal had been sent to the Executive for consideration and the decision remained pending, according to la diaria. As of this file\'s closing date (August 2026) the sources consulted record no developments after December 2025 on the final resolution of the tariff adjustment or on the utility\'s closed financial result.',
      porQueImporta: 'Every water project announced — the treatment plant, the dam, the sewerage scheme — ends up in the same place: OSE\'s monthly bill. When 3.7 points of a tariff rise are explicitly earmarked to finance investments, customers are paying up front for works they will only use several years from now.',
      caveat: 'Tariffs and financial results are not purchases and do not appear on the state procurement portal. What can be traced are OSE\'s operating costs — outsourced services, network maintenance, leases — which the budget office flagged as a deviation.',
    },
  },
]
