import type { CasoDef } from '../types'

/**
 * ambiente — 10 dossiers, 7 of them with a live cross-reference.
 *
 * Every source URL was fetched and every query was resolved against the live
 * collection before this file was committed (scripts/verify-casos.ts re-checks
 * both). A caso with no `query` is not a gap in the research: its money does
 * not travel through the Compras Estatales feed at all, which `feedCoverage`
 * records and the page states outright.
 */
export const CASOS_AMBIENTE: CasoDef[] = [
  {
    slug: 'neptuno-arazati-contrato-observado',
    emoji: '💧',
    theme: 'ambiente',
    period: '2025-2026',
    statusKind: 'auditoria',
    status: 'auditoria',
    amountReported: 'US$ 40 millones anuales durante 17,5 años tras la renegociación, unos US$ 10 millones menos por año que en el proyecto original (La Mañana, agosto de 2026)',
    organisms: ['Administración de las Obras Sanitarias del Estado (OSE)', 'Ministerio de Ambiente'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Administración de las Obras Sanitarias del Estado',
        'Dirección Nacional de Medio Ambiente',
      ],
      search: 'potabilizadora',
      yearFrom: 2025,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'El Observador', title: 'Tribunal de Cuentas observó reformulación del contrato del proyecto Neptuno impulsada por el gobierno de Orsi', url: 'https://www.elobservador.com.uy/nacional/tribunal-cuentas-observo-reformulacion-del-contrato-del-proyecto-neptuno-impulsada-el-gobierno-orsi-n6034988', date: '2026-02-19' },
      { outlet: 'la diaria', title: 'Tribunal de Cuentas observó el contrato de renegociación del proyecto Neptuno por 4 votos a 3', url: 'https://ladiaria.com.uy/politica/articulo/2026/2/tribunal-de-cuentas-observo-el-contrato-de-renegociacion-del-proyecto-neptuno-por-4-votos-a-3/', date: '2026-02-19' },
      { outlet: 'Subrayado', title: 'Tribunal de Cuentas observó contrato firmado por OSE para construir nueva potabilizadora en el río Santa Lucía', url: 'https://www.subrayado.com.uy/tribunal-cuentas-observo-contrato-firmado-ose-construir-nueva-potabilizadora-el-rio-santa-lucia-n1000452', date: '2026-02-19' },
      { outlet: 'Montevideo Portal', title: 'OSE firmó cambios al contrato de Proyecto Neptuno: qué cambia y cuánto costará', url: 'https://www.montevideo.com.uy/Noticias/OSE-firmo-cambios-al-contrato-de-Proyecto-Neptuno-que-cambia-y-cuanto-costara-uc954976', date: '2026-03-05' },
      { outlet: 'Teledoce', title: 'El gobierno cerró la renegociación del proyecto Neptuno: las obras acordadas comenzarán en abril de 2026 y se extenderán por 30 meses', url: 'https://www.teledoce.com/telemundo/nacionales/el-gobierno-cerro-la-renegociacion-del-proyecto-neptuno-las-obras-acordadas-comenzaran-en-abril-de-2026-y-se-extenderan-por-30-meses/', date: '2025-12-19' },
      { outlet: 'La Mañana', title: 'Ambiente autorizó el nuevo proyecto Neptuno pese a las observaciones del Tribunal de Cuentas', url: 'https://www.xn--lamaana-7za.uy/actualidad/ambiente-autorizo-el-nuevo-proyecto-neptuno-pese-a-las-observaciones-del-tribunal-de-cuentas/', date: '2026-08-11' },
    ],
    es: {
      title: 'Neptuno: el Tribunal de Cuentas observó el contrato renegociado',
      dek: 'OSE rediseñó la potabilizadora heredada del gobierno anterior y bajó el canon. El Tribunal de Cuentas observó el cambio por 4 votos a 3 y el organismo reiteró el gasto.',
      contexto: 'El Proyecto Neptuno nació como iniciativa privada para reforzar el abastecimiento de agua potable del área metropolitana, golpeado por la sequía de 2023. El diseño original, contratado bajo el gobierno de Luis Lacalle Pou con el consorcio Aguas de Montevideo, ubicaba la planta en Arazatí, San José, tomando agua del Río de la Plata. El gobierno de Yamandú Orsi renegoció ese contrato y cerró el acuerdo en diciembre de 2025, según Teledoce: la planta se mudó a Aguas Corrientes, sobre el río Santa Lucía, con una capacidad de 200.000 metros cúbicos diarios y un acueducto de 40 kilómetros hasta Cuchilla Pereira, según Subrayado. Montevideo Portal informó el 5 de marzo de 2026 que OSE firmó los cambios al contrato.',
      hallazgo: 'El 19 de febrero de 2026 el Tribunal de Cuentas observó la modificación por 4 votos a 3, según El Observador, la diaria y Subrayado. Según El Observador, su presidente, Francisco Gallinal, sostuvo que los cambios sustanciales alcanzaron la ubicación, el precio y el mantenimiento, y que con esas condiciones el llamado habría sido distinto y otras empresas podrían haberse presentado: «lesiona la igualdad de los oferentes», afirmó. La resolución mayoritaria, según la diaria, concluyó que la modificación proyectada altera sustancialmente el objeto contractual original, porque la toma de agua bruta pasa del contratista a OSE. Las cifras difieren según la fuente: La Mañana informó que OSE pagará US$ 40 millones anuales durante 17,5 años, unos US$ 10 millones menos por año que en el proyecto original; Montevideo Portal informó que el precio bajó de US$ 300 millones a unos US$ 200 millones, y Teledoce citó al presidente de OSE, Pablo Ferreri, diciendo que el nuevo diseño permitió bajar los costos de 360 a 212 millones de dólares.',
      statusNote: 'Ferreri respondió, según Subrayado, que la resolución no cuestiona los fundamentos sobre interés público ni la conveniencia económica, que «la renegociación que se hizo está dentro del marco de las normas y de la legalidad» y que el directorio de OSE resolvió reiterar el gasto, mecanismo que habilita a ejecutarlo pese a la observación. El 11 de agosto de 2026, según La Mañana, el ministro de Ambiente, Edgardo Ortuño, firmó la autorización ambiental previa, con la exigencia de que OSE presente un Plan de Gestión Ambiental de Construcción antes de iniciar las obras, previstas para setiembre. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores al 11 de agosto de 2026.',
      porQueImporta: 'El agua potable del área metropolitana depende en gran medida de la planta de Aguas Corrientes, y la sequía de 2023 dejó agua salinizada en las canillas de Montevideo. Lo que se resuelva acá lo paga cada hogar en la factura de OSE durante 17 años y medio, y define si el próximo verano seco vuelve a encontrar al país sin reserva.',
      caveat: 'Es un contrato surgido de una iniciativa privada bajo régimen de participación público-privada: no se tramita como una compra estatal común y puede no aparecer en el feed de compras públicas. Los pagos de OSE son un canon anual, no órdenes de compra. Las fuentes consultadas no detallan la integración empresarial del consorcio.',
    },
    en: {
      title: 'Neptuno: the Court of Accounts flagged the renegotiated contract',
      dek: 'OSE redesigned the water plant inherited from the previous government and cut the annual fee. The Court of Accounts objected 4-3 and OSE reaffirmed the spending anyway.',
      contexto: 'Project Neptuno began as a private initiative to reinforce drinking-water supply for the Montevideo metropolitan area, hit hard by the 2023 drought. The original design, contracted under Luis Lacalle Pou\'s government with the Aguas de Montevideo consortium, placed the plant at Arazatí, San José, drawing water from the Río de la Plata. Yamandú Orsi\'s government renegotiated that contract and closed the deal in December 2025, according to Teledoce: the plant moved to Aguas Corrientes on the Santa Lucía river, with a capacity of 200,000 cubic metres a day and a 40-kilometre aqueduct to Cuchilla Pereira, according to Subrayado. Montevideo Portal reported on 5 March 2026 that OSE had signed the contract changes.',
      hallazgo: 'On 19 February 2026 the Court of Accounts flagged the amendment by 4 votes to 3, according to El Observador, la diaria and Subrayado. According to El Observador, its president, Francisco Gallinal, held that the substantial changes reached the location, the price and the maintenance, and that under those conditions the tender would have been different and other firms could have entered: it "harms equality among bidders", he said. The majority ruling, according to la diaria, concluded that the proposed amendment substantially alters the original contractual object, because raw-water intake passes from the contractor to OSE. Figures differ by source: La Mañana reported OSE will pay US$40 million a year for 17.5 years, some US$10 million less per year than in the original project; Montevideo Portal reported the price fell from US$300 million to about US$200 million, and Teledoce quoted OSE president Pablo Ferreri saying the new design brought costs down from 360 to 212 million dollars.',
      statusNote: 'Ferreri replied, according to Subrayado, that the ruling does not question the grounds of public interest nor the economic case, that "the renegotiation carried out is within the framework of the rules and of legality", and that OSE\'s board resolved to reaffirm the spending — a mechanism that allows execution despite the objection. On 11 August 2026, according to La Mañana, Environment Minister Edgardo Ortuño signed the prior environmental authorisation, requiring OSE to submit a Construction Environmental Management Plan before starting the works, scheduled for September. As of this file\'s closing (August 2026) no developments after 11 August 2026 are on record.',
      porQueImporta: 'Drinking water for the metropolitan area depends largely on the Aguas Corrientes plant, and the 2023 drought left salinised water in Montevideo\'s taps. Whatever is settled here is paid by every household in its OSE bill for 17 and a half years, and determines whether the next dry summer again finds the country without reserves.',
      caveat: 'This is a contract born of a private initiative under a public-private partnership regime: it is not processed as an ordinary state purchase and may not appear in the public-procurement feed. OSE\'s payments are an annual fee, not purchase orders. The sources consulted do not detail which firms make up the consortium.',
    },
  },
  {
    slug: 'trasvase-rio-san-jose-paso-belastiqui',
    emoji: '🚰',
    theme: 'ambiente',
    period: '2023-2025',
    statusKind: 'gestion',
    status: 'inconcluso',
    amountReported: 'US$ 35 millones el costo total de la obra; US$ 10,2 millones más IVA repartidos entre las constructoras (El Observador, julio de 2023)',
    organisms: ['Administración de las Obras Sanitarias del Estado (OSE)'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Administración de las Obras Sanitarias del Estado',
      ],
      search: 'tubería',
      yearFrom: 2023,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'Brecha', title: 'El costoso trasvase abandonado', url: 'https://brecha.com.uy/el-costoso-trasvase-abandonado/', date: '2024-04-26' },
      { outlet: 'El Observador', title: 'El trasvase del río San José se queda: así se aprovechará el millonario préstamo de OSE para las obras de emergencia por la crisis del agua', url: 'https://www.elobservador.com.uy/nota/el-millonario-prestamo-de-ose-para-las-obras-de-emergencia-y-la-utilidad-que-tendra-el-trasvase-del-rio-san-jose-en-el-futuro-202372720140', date: '2023-07-28' },
      { outlet: 'El Observador', title: 'OSE se prepara para poner en marcha el trasvase del río San José y empezó a usar reservas de Paso Severino', url: 'https://www.elobservador.com.uy/nacional/ose-se-prepara-poner-marcha-el-trasvase-del-rio-san-jose-y-empezo-usar-reservas-paso-severino-n5980242', date: '2025-01-18' },
      { outlet: 'Presidencia de la República', title: 'Gobierno decretó emergencia hídrica en área metropolitana y anunció exoneración impositiva para agua embotellada', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/gobierno-decreto-emergencia-hidrica-area-metropolitana-anuncio-exoneracion', date: '2023-06-19' },
    ],
    es: {
      title: 'El trasvase del río San José: US$ 35 millones que funcionaron días',
      dek: 'OSE construyó en plena sequía una represa provisoria y unos 13 kilómetros de tubería. El investigador Marcel Achkar dijo a Brecha que funcionó tres días antes de que el desborde del río rompiera la represa.',
      contexto: 'En junio de 2023, con las reservas de Paso Severino casi agotadas y agua salinizada en las canillas de Montevideo, el gobierno decretó la emergencia hídrica. Entre las medidas anunciadas por Presidencia el 19 de junio figuraban la entrega de dos litros diarios de agua gratis a unos 21.000 beneficiarios del Mides y el inicio de trabajos para construir un embalse y un sistema de cañerías sobre el río San José, con una duración máxima estimada de unos 30 días. OSE ejecutó la obra hacia Paso Belastiquí, sobre el Santa Lucía. El Observador informó en julio de 2023 que el costo total era de US$ 35 millones, con US$ 10,2 millones más IVA repartidos entre Espina, Cujó, Teyma, Stiler, Ciemsa y Saceem, que la traza tenía 13,2 kilómetros de tuberías —Brecha consignó 13,5— y que operaba con cinco electrobombas y otras cinco motobombas, y que OSE se financió con un préstamo de emergencia de US$ 25 millones a 12 meses.',
      hallazgo: 'El gobierno presentó la obra como perdurable: El Observador tituló en julio de 2023 que «el trasvase del río San José se queda» y consignó que aportaría 70 millones de metros cúbicos al año, equivalentes a otro Paso Severino, y sumaría 2.500 kilómetros cuadrados de cuenca. Brecha publicó en abril de 2024 una nota titulada «El costoso trasvase abandonado», en la que el investigador de la Facultad de Ciencias de la Udelar Marcel Achkar afirmó que se trató de «algo que funcionó tres días» y que «el desborde del San José con la primera lluvia rompió la represa». Achkar sostuvo además que «los cuidados ambientales fueron mínimos», que la obra generó un frente de erosión importante en la ribera oeste y que tras las lluvias de marzo quedaron contenedores y restos flotando en la zona de Puente Valdez. En enero de 2025 El Observador informó que el trasvase todavía no había sido activado, que el proyecto ejecutivo estaba en etapa final y que quedaba pendiente una licitación pública para construir la toma permanente en Paso Valdez.',
      statusNote: 'En enero de 2025 el gerente general de OSE, Arturo Castagnino, dijo a El Observador: «Estamos en los actos preparatorios. Estimo que será necesario poner en marcha a la brevedad el trasvase». Según esa nota, OSE priorizaba las reservas de Canelón Grande y dejaba Paso Severino como último recurso, y la infraestructura puede llevar 200.000 metros cúbicos diarios desde el río San José hacia Aguas Corrientes. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a enero de 2025 verificadas para esta ficha.',
      porQueImporta: 'Son US$ 35 millones de OSE, financiados con deuda que se paga con la tarifa del agua, en una obra que según el investigador citado por Brecha operó unos tres días. El caso muestra el precio de comprar tarde y bajo emergencia: la oposición y el sindicato ya habían advertido que hacerlo con anticipación habría costado menos.',
      caveat: 'Las contrataciones de emergencia se procesan por vías excepcionales y pueden aparecer fragmentadas o con objeto genérico en el feed de compras. La cifra de US$ 35 millones es la reportada por la prensa, no un total oficial auditado por obra, y la duración de tres días de operación es la afirmación de un investigador citado por Brecha, no un dato oficial de OSE.',
    },
    en: {
      title: 'The San José river transfer: US$35 million that ran for days',
      dek: 'During the drought OSE built a temporary dam and some 13 kilometres of pipeline. Researcher Marcel Achkar told Brecha it ran three days before the river\'s overflow broke the dam.',
      contexto: 'In June 2023, with Paso Severino\'s reserves nearly exhausted and salinised water in Montevideo taps, the government declared a water emergency. Among the measures announced by the Presidency on 19 June were the delivery of two free litres of water a day to some 21,000 Mides beneficiaries and the start of works to build a reservoir and pipeline system on the San José river, estimated to take at most about 30 days. OSE executed the works towards Paso Belastiquí, on the Santa Lucía. El Observador reported in July 2023 that the total cost was US$35 million, with US$10.2 million plus VAT split among Espina, Cujó, Teyma, Stiler, Ciemsa and Saceem, that the route ran 13.2 kilometres of pipe — Brecha recorded 13.5 — operating with five electric pumps and five motor pumps, and that OSE financed it with a 12-month US$25 million emergency loan.',
      hallazgo: 'The government presented the works as lasting: El Observador headlined in July 2023 that "the San José river transfer is here to stay" and recorded that it would add 70 million cubic metres a year, equivalent to another Paso Severino, and 2,500 square kilometres of basin. In April 2024 Brecha published a piece titled "The costly abandoned transfer", in which Udelar Faculty of Sciences researcher Marcel Achkar said it was "something that ran three days" and that "the San José overflowing with the first rain broke the dam". Achkar also held that "environmental precautions were minimal", that the works produced a significant erosion front on the western bank, and that after March\'s rains containers and debris were left floating around Puente Valdez. In January 2025 El Observador reported the transfer had still not been activated, that the executive design was in its final stage, and that a public tender was still pending to build the permanent intake at Paso Valdez.',
      statusNote: 'In January 2025 OSE general manager Arturo Castagnino told El Observador: "We are in the preparatory steps. I estimate the transfer will need to be started up shortly." According to that report, OSE was prioritising Canelón Grande reserves and holding Paso Severino as a last resort, and the infrastructure can carry 200,000 cubic metres a day from the San José river towards Aguas Corrientes. As of this file\'s closing (August 2026) no developments after January 2025 have been verified for this file.',
      porQueImporta: 'This is US$35 million of OSE money, financed with debt repaid through the water tariff, on works that according to the researcher quoted by Brecha operated for about three days. The case shows the price of buying late and under emergency: the opposition and the union had already warned that acting earlier would have cost less.',
      caveat: 'Emergency contracting runs through exceptional channels and can appear fragmented or under a generic purchase description in the procurement feed. The US$35 million figure is the one reported by the press, not an audited official total per work, and the three-day operating span is a researcher\'s statement quoted by Brecha, not an official OSE figure.',
    },
  },
  {
    slug: 'ferrocarril-central-obras-comprometidas-upm',
    emoji: '🚂',
    theme: 'ambiente',
    period: '2019-2025',
    statusKind: 'gestion',
    status: 'sobrecosto',
    amountReported: 'Sobrecostos que pueden ascender a US$ 670 millones según la diaria (febrero de 2024); acuerdo de pago por US$ 144 millones anunciado en mayo de 2025 (El Observador)',
    organisms: ['Ministerio de Transporte y Obras Públicas'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'la diaria', title: 'Ferrocarril Central: sobrecostos pueden ascender a 670 millones de dólares y desde el FA critican cambios al contrato', url: 'https://ladiaria.com.uy/politica/articulo/2024/3/ferrocarril-central-sobrecostos-pueden-ascender-a-670-millones-de-dolares-y-desde-el-fa-critican-cambios-al-contrato/', date: '2024-02-29' },
      { outlet: 'Búsqueda', title: 'Asesores del MTOP sugirieron intimar al Grupo Vía Central por «incumplimiento grave» días antes de inaugurar el tren', url: 'https://www.busqueda.com.uy/economia/asesores-del-mtop-sugirieron-intimar-al-grupo-via-central-incumplimiento-grave-dias-antes-inaugurar-el-tren-n5393592', date: '2024-10-10' },
      { outlet: 'El Observador', title: 'Gobierno anunció acuerdo con consorcio que hizo vías de Ferrocarril Central: el Estado pagará US$ 144 millones', url: 'https://www.elobservador.com.uy/nacional/gobierno-anunciara-acuerdo-consorcio-via-central-deuda-obras-del-ferrocarril-central-n6000103', date: '2025-05-19' },
    ],
    es: {
      title: 'Ferrocarril Central: la obra del Estado para la planta de UPM',
      dek: 'El tren que conecta la planta de celulosa con el puerto acumuló adendas, un arbitraje internacional y un acuerdo final de US$ 144 millones que paga el Estado.',
      contexto: 'El Ferrocarril Central une el puerto de Montevideo con Paso de los Toros. Según la diaria, el Grupo Vía Central firmó con el gobierno el contrato original para construirlo, conectando la planta de celulosa de UPM con el puerto de Montevideo. Se contrató bajo el régimen de participación público-privada: el Estado no paga la obra de una vez, sino un canon por disponibilidad de la vía a lo largo de años. Búsqueda consignó que el tren se inauguró el 16 de abril de 2024 en Cardal, y El Observador que entró en operación el 8 de agosto de 2024, tras dos modificaciones del contrato.',
      hallazgo: 'la diaria informó el 29 de febrero de 2024 que los sobrecostos podían ascender a US$ 670 millones y que desde el Frente Amplio se criticaban los cambios al contrato: un director frenteamplista en la Corporación Nacional para el Desarrollo sostuvo que hay riesgos que debe asumir exclusivamente el contratista, cuestionando cómo se reasignaron al Estado. Según esa nota, una segunda adenda por US$ 331 millones estaba a estudio del Tribunal de Cuentas y se habría acordado después de que el consorcio amenazara con un arbitraje internacional. Búsqueda informó en octubre de 2024 que tres asesores del MTOP —los ingenieros Carlos González y Luis Ceiter y el abogado Diego Bianchi— enviaron el 5 de abril de 2024, once días antes de la inauguración, una carta al ministro José Luis Falero recomendando intimar al contratista bajo apercibimiento de rescisión por incumplimiento grave, ante defectos y observaciones que podían afectar la seguridad ferroviaria y la durabilidad de la infraestructura. La misma nota consignó que el Estado ya había acordado dos modificaciones del contrato, de US$ 145 millones la primera y US$ 140 millones la segunda.',
      statusNote: 'En mayo de 2025 El Observador informó que el gobierno de Yamandú Orsi anunció un acuerdo por el que el Estado pagará US$ 144 millones al consorcio, que en febrero de 2024 había comunicado el inicio de una demanda internacional contra el Estado uruguayo por incumplimientos y falta de pagos. El acuerdo, presentado por Orsi junto al ministro de Economía Gabriel Oddone, la ministra de Transporte Lucía Etcheverry y el secretario de Presidencia Alejandro Sánchez, cubre el período comprendido entre el 23 de diciembre de 2023 y el 31 de marzo de 2025. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a mayo de 2025 verificadas para esta ficha.',
      porQueImporta: 'Es infraestructura pagada con impuestos, asociada a una inversión privada. Cada adenda y cada acuerdo por atrasos se suma a lo que el Estado paga durante años por la disponibilidad de la vía, plata que no está disponible para otras rutas, escuelas u hospitales.',
      caveat: 'Al ser un contrato de participación público-privada, los pagos son cánones de disponibilidad y no compras con orden de compra: es probable que no figuren en el feed de compras estatales. Los montos citados son los reportados por la prensa. Las fuentes consultadas no recogen una respuesta del ministro Falero a la recomendación de sus asesores ni un descargo del Grupo Vía Central.',
    },
    en: {
      title: 'Ferrocarril Central: the state works built for the UPM mill',
      dek: 'The railway linking the pulp mill to the port piled up addenda, an international arbitration and a final US$144 million settlement paid by the State.',
      contexto: 'The Ferrocarril Central links the port of Montevideo with Paso de los Toros. According to la diaria, Grupo Vía Central signed the original contract with the government to build it, connecting UPM\'s pulp mill to the port of Montevideo. It was contracted as a public-private partnership: the State does not pay for the works up front, but an availability fee for the track over years. Búsqueda recorded that the train was inaugurated on 16 April 2024 at Cardal, and El Observador that it entered service on 8 August 2024, after two contract amendments.',
      hallazgo: 'la diaria reported on 29 February 2024 that cost overruns could reach US$670 million and that Frente Amplio figures criticised the contract changes: an FA director at the National Development Corporation held that there are risks the contractor alone must bear, questioning how they were reassigned to the State. According to that report, a second addendum worth US$331 million was under review by the Court of Accounts and had reportedly been agreed after the consortium threatened international arbitration. Búsqueda reported in October 2024 that three MTOP advisers — engineers Carlos González and Luis Ceiter and lawyer Diego Bianchi — sent a letter on 5 April 2024, eleven days before the inauguration, to Minister José Luis Falero recommending the contractor be formally summoned under warning of termination for serious breach, given defects and observations that could affect railway safety and the durability of the infrastructure. The same report recorded that the State had already agreed two contract amendments, US$145 million the first and US$140 million the second.',
      statusNote: 'In May 2025 El Observador reported that Yamandú Orsi\'s government announced a settlement under which the State will pay the consortium US$144 million, after the consortium had in February 2024 announced the start of an international claim against the Uruguayan State for breaches and unpaid amounts. The agreement, presented by Orsi alongside Economy Minister Gabriel Oddone, Transport Minister Lucía Etcheverry and Presidential Secretary Alejandro Sánchez, covers the period from 23 December 2023 to 31 March 2025. As of this file\'s closing (August 2026) no developments after May 2025 have been verified for this file.',
      porQueImporta: 'This is infrastructure paid for with taxes, tied to a private investment. Every addendum and every settlement for delays adds to what the State pays for years for the track\'s availability — money not available for other roads, schools or hospitals.',
      caveat: 'Being a public-private partnership, payments are availability fees rather than purchases with a purchase order: they are unlikely to appear in the state procurement feed. The amounts cited are those reported by the press. The sources consulted carry no response from Minister Falero to his advisers\' recommendation, nor any reply from Grupo Vía Central.',
    },
  },
  {
    slug: 'agua-embotellada-emergencia-hidrica-2023',
    emoji: '🚱',
    theme: 'ambiente',
    period: '2023',
    statusKind: 'gestion',
    status: 'terminado',
    amountReported: 'Más de 66 millones de litros de agua embotellada comprados por el Estado, por US$ 25 millones a través del Mides (El Observador, agosto de 2023)',
    organisms: ['Ministerio de Desarrollo Social', 'Administración de las Obras Sanitarias del Estado (OSE)', 'Presidencia de la República'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Ex-Adm.Gral- Dir. General Secret.',
        'Dirección de Desarrollo Social',
        'Instituto Nacional de Alimentación',
        'Direc. General de Secretaría.',
        'Dirección Nacional de Protección Social',
        'Instituto Nacional de la Juventud',
        'Administración de las Obras Sanitarias del Estado',
        'Presidencia de la República y Oficinas Dependientes',
        'Presidencia de la República',
        'Oficina Nacional del Servicio Civil',
        'Secretaría Nacional del Deporte',
        'Oficina de Planeamiento y Presupuesto',
        'Unidad Reguladora de Servic.de Comunicaciones-URSEC',
        'Casa Militar',
        'Instituto Nacional de Estadística',
        'AGESIC',
        'Unidad Reguladora de Serv. de Energía y Agua-URSEA',
        'Presidencia de la República y Unidades Dependientes',
        'NO VIGENTE - Dirección de Proyectos de Desarrollo',
        'Secretaría Nacional del Deporte',
        'Instituto Nacional de EstadÍstica',
        'Agen.p/Des.del Gob.de Gest.Electr.y Soc.Inform.y del Conoc.',
      ],
      search: 'agua mineral',
      yearFrom: 2023,
      yearTo: 2023,
    },
    sources: [
      { outlet: 'Presidencia de la República', title: 'Gobierno decretó emergencia hídrica en área metropolitana y anunció exoneración impositiva para agua embotellada', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/gobierno-decreto-emergencia-hidrica-area-metropolitana-anuncio-exoneracion', date: '2023-06-19' },
      { outlet: 'El Observador', title: 'Con el fin de la emergencia hídrica el agua embotellada vuelve a tener impuestos: cuáles pueden ser los nuevos precios', url: 'https://www.elobservador.com.uy/nota/el-agua-embotellada-vuelve-a-tener-impuestos-cuales-pueden-ser-los-nuevos-precios-2023823132315', date: '2023-08-23' },
      { outlet: 'la diaria', title: 'Compras de OSE por la crisis hídrica fueron «tardías» y caras, denuncian la oposición y el sindicato', url: 'https://ladiaria.com.uy/politica/articulo/2023/7/compras-de-ose-por-la-crisis-hidrica-fueron-tardias-y-caras-denuncian-la-oposicion-y-el-sindicato/', date: '2023-07-22' },
    ],
    es: {
      title: '66 millones de litros: lo que el Estado gastó en agua embotellada',
      dek: 'En la sequía de 2023 el Estado aseguró la compra de más de 66 millones de litros de agua por US$ 25 millones. La oposición y el sindicato dijeron que se compró tarde y caro.',
      contexto: 'El 19 de junio de 2023, con el agua de la canilla salinizada en el área metropolitana, el presidente Luis Lacalle Pou decretó la emergencia hídrica. Según el comunicado de Presidencia, se anunció la eliminación de impuestos al agua embotellada mediante decreto y proyecto de ley, la entrega de dos litros de agua gratis por día a unos 21.000 beneficiarios del Mides, el suministro asegurado a hospitales, residenciales, CAIF y dependencias del INAU, y el inicio de obras de urgencia, entre ellas un embalse sobre el río San José. Según El Observador, la exoneración de IVA (22%) e Imesi (10,5%) se dispuso a fines de junio de 2023, y la cobertura de compra de agua para población vulnerable se extendía hasta el 11 de setiembre de 2023.',
      hallazgo: 'El Observador informó el 23 de agosto de 2023 que el gobierno aseguró la compra de más de 66 millones de litros de agua embotellada para población vulnerable, lo que representó una inversión de US$ 25 millones. Antes, en julio, la diaria había recogido las críticas de la oposición y del sindicato de OSE: el director frenteamplista del organismo, Edgardo Ortuño, sostuvo que «hubo un encarecimiento de estas obras de emergencia por haber sido planteadas en forma tardía» y que en ese tiempo «hubiéramos podido procesar las compras a menores costos», citando como ejemplo una compra de caños de unos 20 millones. El planteo era que si las compras se hubieran hecho al declararse la emergencia agropecuaria, en octubre de 2022, o al empezar las restricciones en febrero de 2023, habrían costado bastante menos. El mismo artículo consignó que OSE enfrentaría los años siguientes con su presupuesto en rojo y que el sindicato FFOSE denunciaba estar por debajo de la dotación mínima necesaria de funcionarios.',
      statusNote: 'Según El Observador, con el fin de la emergencia hídrica el presidente firmó el decreto para levantarla y el agua embotellada volvió a tributar 22% de IVA y 10,5% de Imesi por litro. Edgardo Ortuño, entonces director opositor en OSE y crítico de las compras tardías, es hoy ministro de Ambiente del gobierno de Yamandú Orsi. Al cierre de esta ficha (agosto de 2026) no constan, para esta ficha, resoluciones de auditoría posteriores a agosto de 2023 sobre estas compras específicas.',
      porQueImporta: 'Fueron US$ 25 millones gastados en comprar el agua que el sistema público no pudo entregar, además de la recaudación resignada por la exoneración impositiva. El costo de no tener reserva no se paga sólo en obras: se paga también en botellas, y lo pagan todos los contribuyentes.',
      caveat: 'Las compras se hicieron bajo régimen de emergencia y por distintos organismos (Mides, OSE, Presidencia), por lo que en el feed pueden figurar dispersas, con objeto genérico o bajo excepciones al llamado público. El total de US$ 25 millones es el reportado por la prensa. Las críticas por compras «tardías y caras» son planteos de la oposición y del sindicato, no conclusiones de una auditoría.',
    },
    en: {
      title: '66 million litres: what the State spent on bottled water',
      dek: 'During the 2023 drought the State secured the purchase of over 66 million litres of water for US$25 million. The opposition and the union said it bought late and dear.',
      contexto: 'On 19 June 2023, with tap water salinised across the metropolitan area, President Luis Lacalle Pou declared a water emergency. According to the Presidency\'s statement, the government announced the removal of taxes on bottled water by decree and bill, the delivery of two free litres of water a day to some 21,000 Mides beneficiaries, guaranteed supply to hospitals, care homes, CAIF centres and INAU facilities, and the start of urgent works, among them a reservoir on the San José river. According to El Observador, the VAT (22%) and Imesi (10.5%) exemption was set in late June 2023, and the water-purchase coverage for vulnerable populations ran until 11 September 2023.',
      hallazgo: 'El Observador reported on 23 August 2023 that the government secured the purchase of more than 66 million litres of bottled water for vulnerable populations, an investment of US$25 million. Earlier, in July, la diaria had gathered criticism from the opposition and OSE\'s union: the utility\'s Frente Amplio director, Edgardo Ortuño, held that "these emergency works became more expensive because they were raised late" and that in that time "we could have processed the purchases at lower cost", citing as an example a pipe purchase of some 20 million. The argument was that had the purchases been made when the agricultural emergency was declared in October 2022, or when restrictions began in February 2023, they would have cost considerably less. The same article recorded that OSE would face the following years with its budget in the red and that the FFOSE union reported staffing below the necessary minimum.',
      statusNote: 'According to El Observador, with the end of the water emergency the president signed the decree to lift it and bottled water again paid 22% VAT and 10.5% Imesi per litre. Edgardo Ortuño, then the opposition director at OSE and a critic of the late purchasing, is today Environment Minister in Yamandú Orsi\'s government. As of this file\'s closing (August 2026) no audit rulings after August 2023 on these specific purchases are on record for this file.',
      porQueImporta: 'This was US$25 million spent buying the water the public system could not deliver, on top of the tax revenue forgone through the exemption. The cost of having no reserve is not paid only in works: it is also paid in bottles, and every taxpayer pays it.',
      caveat: 'The purchases were made under an emergency regime and by different bodies (Mides, OSE, the Presidency), so in the feed they may appear scattered, under a generic description, or through exceptions to open tendering. The US$25 million total is the figure reported by the press. The criticism of "late and expensive" purchasing comes from the opposition and the union, not from an audit finding.',
    },
  },
  {
    slug: 'aratiri-arbitraje-costo-defensa-estado',
    emoji: '⛏️',
    theme: 'ambiente',
    period: '2017-2025',
    statusKind: 'judicial',
    status: 'juicio',
    amountReported: 'US$ 5 millones costó la defensa del Estado; el tribunal ordenó a los demandantes reembolsar US$ 4.097.149 (Montevideo Portal, setiembre de 2020)',
    organisms: ['Presidencia de la República'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Presidencia de la República y Oficinas Dependientes',
        'Presidencia de la República',
        'Oficina Nacional del Servicio Civil',
        'Secretaría Nacional del Deporte',
        'Oficina de Planeamiento y Presupuesto',
        'Unidad Reguladora de Servic.de Comunicaciones-URSEC',
        'Casa Militar',
        'Instituto Nacional de Estadística',
        'AGESIC',
        'Unidad Reguladora de Serv. de Energía y Agua-URSEA',
        'Presidencia de la República y Unidades Dependientes',
        'NO VIGENTE - Dirección de Proyectos de Desarrollo',
        'Secretaría Nacional del Deporte',
        'Instituto Nacional de EstadÍstica',
        'Agen.p/Des.del Gob.de Gest.Electr.y Soc.Inform.y del Conoc.',
      ],
      search: 'asesoramiento',
      yearFrom: 2017,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'Montevideo Portal', title: 'Defensa de Uruguay contra Aratirí costó U$S 5 millones; el tribunal ordenó reembolsar 4', url: 'https://www.montevideo.com.uy/Noticias/Defensa-de-Uruguay-contra-Aratiri-costo-U-S-5-millones-el-tribunal-ordeno-reembolsar-4-uc764533', date: '2020-09-14' },
      { outlet: 'Subrayado', title: 'Uruguay ganó el juicio internacional que le inició la minera Aratirí', url: 'https://www.subrayado.com.uy/uruguay-gano-el-juicio-internacional-que-le-inicio-la-minera-aratiri-n654393', date: '2020-08-06' },
      { outlet: 'El Observador', title: 'El caso no terminó: cómo sigue el arbitraje de Aratirí tras el fallo favorable para Uruguay', url: 'https://www.elobservador.com.uy/nacional/el-caso-no-termino-como-sigue-el-arbitraje-aratiri-el-fallo-favorable-uruguay-n5992996', date: '2025-04-04' },
      { outlet: 'El Observador', title: 'Jorge Díaz celebró el fallo favorable en juicio por Aratirí y cuestionó que Uruguay sea visto como un Estado «débil»', url: 'https://www.elobservador.com.uy/nacional/jorge-diaz-celebro-el-fallo-favorable-juicio-aratiri-y-cuestiono-que-uruguay-sea-visto-como-un-estado-debil-n5992957', date: '2025-04-04' },
    ],
    es: {
      title: 'Aratirí: lo que le costó al Estado defenderse por la mina',
      dek: 'Uruguay ganó el arbitraje que le inició la minera, pero la defensa costó US$ 5 millones y el tribunal ordenó reembolsar US$ 4.097.149.',
      contexto: 'El proyecto de minería de hierro Aratirí se impulsó durante el gobierno de José Mujica y fue cancelado, según El Observador, lo que derivó en una disputa por inversiones de la familia Agarwal. En 2017 la empresa demandó al Estado uruguayo por 3.500 millones de dólares —US$ 3.536 millones según Montevideo Portal—, denunciando que Uruguay incumplió el acuerdo de Protección y Promoción de Inversiones con el Reino Unido. Según Subrayado, Aratirí invocó el tratado británico porque India no había aprobado un acuerdo similar con Uruguay. El Estado se defendió ante un tribunal arbitral internacional —la Corte Permanente de Arbitraje de La Haya, según Montevideo Portal— contratando al estudio estadounidense Foley Hoag LLP, con sede en Washington.',
      hallazgo: 'En agosto de 2020, según Subrayado, el tribunal no reconoció a los demandantes la legitimidad para reclamar una indemnización del Estado uruguayo, y Uruguay ganó el juicio. Montevideo Portal informó en setiembre de 2020 el detalle de la factura: la defensa costó US$ 5 millones, con US$ 1.398.537 en peritos subcontratados, US$ 72.106 en viajes internacionales y US$ 40.123 en viáticos. El tribunal ordenó a los tres demandantes —Ritika Mehta, Vinita Agarwal y Prenay Agarwal— reembolsar US$ 4.097.149, unos US$ 900.000 menos de lo que el país efectivamente gastó. El Observador informó en abril de 2025 que el monto reclamado alcanzaba los US$ 4.000 millones.',
      statusNote: 'El 2 de abril de 2025, según El Observador, la Corte de Casación francesa anuló una decisión de febrero de 2023 de la Corte de Apelaciones de París que había invalidado el laudo arbitral favorable a Uruguay, y condenó a los empresarios a pagar 5.000 euros. El caso vuelve a la Corte de Apelaciones con otra integración. El prosecretario de Presidencia, Jorge Díaz, celebró el fallo —«antes estábamos perdiendo 5 a 0 y ahora estamos ganando 5 a 0», ejemplificó— y advirtió que el partido no está terminado, porque la Corte de Apelaciones todavía debe resolver aspectos pendientes. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a abril de 2025.',
      porQueImporta: 'Defenderse de un arbitraje internacional cuesta plata pública aunque el país gane: acá quedaron sin cubrir unos US$ 900.000. Es el precio contable de decidir qué se autoriza y qué no en materia ambiental y minera, y explica por qué los tratados de inversión pesan en decisiones que parecen sólo técnicas.',
      caveat: 'Las fuentes no precisan qué organismo contrató y pagó al estudio jurídico, por lo que el cruce con compras estatales es tentativo. Los honorarios de defensa en arbitrajes internacionales suelen tramitarse por vías de excepción y pueden no figurar como una compra ordinaria.',
    },
    en: {
      title: 'Aratirí: what defending the State against the mine cost',
      dek: 'Uruguay won the arbitration the mining firm brought, but the defence cost US$5 million and the tribunal ordered US$4,097,149 reimbursed.',
      contexto: 'The Aratirí iron mining project was promoted under José Mujica\'s government and was cancelled, according to El Observador, triggering an investment dispute by the Agarwal family. In 2017 the company sued the Uruguayan State for 3.5 billion dollars — US$3.536 billion according to Montevideo Portal — alleging Uruguay had breached the Investment Protection and Promotion agreement with the United Kingdom. According to Subrayado, Aratirí invoked the British treaty because India had not approved a similar agreement with Uruguay. The State defended itself before an international arbitral tribunal — the Permanent Court of Arbitration in The Hague, according to Montevideo Portal — hiring the US firm Foley Hoag LLP, based in Washington.',
      hallazgo: 'In August 2020, according to Subrayado, the tribunal did not recognise the claimants\' standing to seek compensation from the Uruguayan State, and Uruguay won the case. Montevideo Portal reported in September 2020 the itemised bill: the defence cost US$5 million, including US$1,398,537 in subcontracted experts, US$72,106 in international travel and US$40,123 in per diems. The tribunal ordered the three claimants — Ritika Mehta, Vinita Agarwal and Prenay Agarwal — to reimburse US$4,097,149, some US$900,000 less than the country actually spent. El Observador reported in April 2025 that the amount claimed reached US$4 billion.',
      statusNote: 'On 2 April 2025, according to El Observador, France\'s Court of Cassation annulled a February 2023 Paris Court of Appeals decision that had invalidated the arbitral award favourable to Uruguay, and ordered the businessmen to pay €5,000. The case returns to the Court of Appeals with a differently composed panel. Presidential Deputy Secretary Jorge Díaz welcomed the ruling — "before we were losing 5-0 and now we are winning 5-0", he put it — and warned the match is not over, because the Court of Appeals still has pending aspects to resolve. As of this file\'s closing (August 2026) no developments after April 2025 are on record.',
      porQueImporta: 'Defending against an international arbitration costs public money even when the country wins: here some US$900,000 went uncovered. It is the accounting price of deciding what is and is not authorised in environmental and mining matters, and it explains why investment treaties weigh on decisions that look purely technical.',
      caveat: 'The sources do not specify which body contracted and paid the law firm, so the cross-reference with state procurement is tentative. Legal fees in international arbitration are usually processed through exceptional channels and may not appear as an ordinary purchase.',
    },
  },
  {
    slug: 'montevideo-fideicomiso-limpieza-residuos',
    emoji: '🗑️',
    theme: 'ambiente',
    period: '2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'US$ 260 millones en cuatro préstamos extrapresupuestales a 25 años, de los cuales US$ 50 millones para el plan de limpieza (El Observador y Subrayado, junio de 2026)',
    organisms: ['Intendencia de Montevideo'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Intendencia de Montevideo',
      ],
      yearFrom: 2026,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'El Observador', title: 'Préstamos millonarios de la IM para limpieza, calles y veredas en la cuerda floja: oposición reclama cambios y reducciones drásticas de los montos', url: 'https://www.elobservador.com.uy/nacional/prestamos-millonarios-la-im-limpieza-calles-y-veredas-la-cuerda-floja-oposicion-reclama-cambios-y-reducciones-drasticas-los-montos-n6045166', date: '2026-05-26' },
      { outlet: 'Subrayado', title: 'Junta votó fideicomiso extrapresupuestal: aumentó monto para saneamiento y se redujo el de veredas, calles y limpieza', url: 'https://www.subrayado.com.uy/junta-vot%C3%B3-fideicomiso-extrapresupuestal-aumento-monto-saneamiento-y-se-redujo-el-veredas-calles-y-limpieza-n1009511', date: '2026-06-04' },
      { outlet: 'El Observador', title: 'El «puñal» dentro de la coalición y la «Copa Libertadores» para la IM: la tensa sesión que le dio US$ 260 millones a Bergara para obras en Montevideo', url: 'https://www.elobservador.com.uy/nacional/el-punal-dentro-la-coalicion-y-la-copa-libertadores-la-im-la-tensa-sesion-que-le-dio-us-250-millones-bergara-obras-montevideo-n6046392', date: '2026-06-05' },
    ],
    es: {
      title: 'Montevideo: US$ 260 millones a crédito para basura y saneamiento',
      dek: 'La Junta Departamental aprobó cuatro préstamos por US$ 260 millones a 25 años. La oposición cuestionó financiar a ese plazo camiones y contenedores que durarán menos.',
      contexto: 'En 2026 la administración de Mario Bergara pidió a la Junta Departamental de Montevideo autorización para tomar financiamiento por fuera del presupuesto mediante fideicomisos. El pedido original, según Subrayado, era de US$ 318 millones a 25 años, repartidos en cinco líneas: saneamiento, limpieza, calles, veredas y un plan para la Ciudad Vieja de US$ 40 millones. El componente de limpieza contemplaba, según El Observador, la compra de 74 camiones, 254.000 contenedores intradomiciliarios y 19.000 contenedores intraprediales.',
      hallazgo: 'El Observador informó el 26 de mayo de 2026 que la oposición reclamaba bajar los montos —«tienen que bajar los montos ostensiblemente, drásticamente», dijo un edil— y que cuestionaba específicamente el paquete de limpieza, entonces de US$ 60 millones, junto con US$ 50 millones para calles y US$ 65 millones para veredas. El edil Guillermo Kruse calificó de «imposible» votar el mecanismo de fondo rotatorio para veredas, aunque dijo que consideraría financiar veredas en asentamientos. El 4 de junio la Junta aprobó un paquete recortado a US$ 260 millones a 25 años: se eliminó el plan de Ciudad Vieja y la línea de limpieza quedó en US$ 50 millones. El Observador desglosó el total en US$ 130 millones para saneamiento, US$ 50 millones para limpieza, US$ 40 millones para calles y US$ 40 millones para veredas; Subrayado consignó US$ 150 millones para saneamiento. El edil Gonzalo Gómez cuestionó el endeudamiento: «le estamos cargando a los montevideanos US$ 600 millones» sumando obligaciones previas de US$ 321 millones hasta 2046.',
      statusNote: 'Las cuatro líneas se votaron el 4 de junio de 2026. La de limpieza pasó con los 21 votos mínimos —los 17 del Frente Amplio más cuatro ediles de la coalición opositora que votaron con el oficialismo: el independiente Guillermo Kruse, el colorado Federico Paganini y los blancos Nicolás Hernández y Joaquín Campos—, y la de saneamiento se aprobó por unanimidad, con 31 votos según Subrayado. Se creó además una comisión de seguimiento con participación mayoritaria de la oposición. Al cierre de esta ficha (agosto de 2026) no constan llamados adjudicados posteriores verificados para esta ficha.',
      porQueImporta: 'Es plata que Montevideo va a pagar durante 25 años con tributos departamentales, para comprar camiones y contenedores que la oposición sostiene que habrá que reponer antes de terminar de pagarlos. Si el plan funciona, cambia la basura en la puerta de cada casa; si no, la deuda queda igual.',
      caveat: 'Los préstamos son la autorización de gasto, no la compra: las licitaciones de camiones y contenedores deberían aparecer después en el feed, a nombre de la Intendencia de Montevideo. El monto de saneamiento difiere entre fuentes (US$ 130 o US$ 150 millones). La afirmación sobre la vida útil de camiones y contenedores es un planteo de ediles opositores, no un dato técnico verificado.',
    },
    en: {
      title: 'Montevideo: US$260 million on credit for waste and sanitation',
      dek: 'The Departmental Board approved four 25-year loans worth US$260 million. The opposition questioned financing over that term trucks and bins that will last less.',
      contexto: 'In 2026 Mario Bergara\'s administration asked Montevideo\'s Departmental Board to authorise off-budget financing through trust funds. The original request, according to Subrayado, was US$318 million over 25 years, across five lines: sanitation, cleaning, streets, sidewalks and a US$40 million Old City plan. The cleaning component contemplated, according to El Observador, buying 74 trucks, 254,000 in-home containers and 19,000 on-premises containers.',
      hallazgo: 'El Observador reported on 26 May 2026 that the opposition demanded the amounts be cut — "the amounts have to come down markedly, drastically", one councillor said — and specifically questioned the cleaning package, then US$60 million, alongside US$50 million for streets and US$65 million for sidewalks. Councillor Guillermo Kruse called it "impossible" to vote the revolving-fund mechanism for sidewalks, though he said he would consider financing sidewalks in informal settlements. On 4 June the Board approved a package trimmed to US$260 million over 25 years: the Old City plan was dropped and the cleaning line settled at US$50 million. El Observador broke the total down as US$130 million for sanitation, US$50 million for cleaning, US$40 million for streets and US$40 million for sidewalks; Subrayado recorded US$150 million for sanitation. Councillor Gonzalo Gómez questioned the borrowing: "we are loading US$600 million onto Montevideans", counting prior obligations of US$321 million through 2046.',
      statusNote: 'The four lines were voted on 4 June 2026. Cleaning passed with the minimum 21 votes — the Frente Amplio\'s 17 plus four opposition councillors who voted with the governing bloc: independent Guillermo Kruse, Colorado Federico Paganini and National Party members Nicolás Hernández and Joaquín Campos — and sanitation was approved unanimously, with 31 votes according to Subrayado. An oversight commission with majority opposition participation was also created. As of this file\'s closing (August 2026) no subsequently awarded tenders have been verified for this file.',
      porQueImporta: 'This is money Montevideo will repay over 25 years through departmental taxes, to buy trucks and containers the opposition argues will need replacing before they are paid off. If the plan works, it changes the rubbish at every doorstep; if it does not, the debt remains all the same.',
      caveat: 'The loans are the spending authorisation, not the purchase: tenders for trucks and containers should appear later in the feed under the Intendencia de Montevideo. The sanitation amount differs between sources (US$130 million or US$150 million). The claim about the working life of trucks and containers is an argument made by opposition councillors, not a verified technical finding.',
    },
  },
  {
    slug: 'data-center-google-agua-canelones',
    emoji: '🖥️',
    theme: 'ambiente',
    period: '2023-2026',
    statusKind: 'debate',
    status: 'debate',
    amountReported: 'Hasta 7.600 metros cúbicos diarios de agua potable de OSE en el proyecto original, reducidos a 48 metros cúbicos tras el rediseño (la diaria y El Observador, 2023); inversión privada de unos US$ 850 millones (El Observador, 2026)',
    organisms: ['Ministerio de Ambiente', 'Administración de las Obras Sanitarias del Estado (OSE)'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Dirección Nacional de Medio Ambiente',
        'Administración de las Obras Sanitarias del Estado',
      ],
      search: 'evaluación',
      yearFrom: 2023,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'la diaria', title: 'Data center de Google podría utilizar un máximo de 7.600.000 litros de agua potable por día', url: 'https://ladiaria.com.uy/ambiente/articulo/2023/3/data-center-de-google-podria-utilizar-un-maximo-de-7600000-litros-de-agua-potable-por-dia/', date: '2023-03-30' },
      { outlet: 'El Observador', title: 'Proyecto de Google en Uruguay: más chico y con un edificio menos tras cambio en el sistema de enfriamiento', url: 'https://www.elobservador.com.uy/nota/sin-agua-con-enfriamiento-por-aire-y-un-edificio-en-lugar-de-dos-los-detalles-del-proyecto-de-google-en-uruguay-2023112116100/', date: '2023-11-22' },
      { outlet: 'Brecha', title: 'El Ministerio de Ambiente frente al data center de Google: una aprobación a ciegas', url: 'https://brecha.com.uy/una-aprobacion-a-ciegas/', date: '2024-08-02' },
      { outlet: 'El Observador', title: 'Vecinos del data center de Google en Canelones piden frenar avances: reclaman dejar sin efecto la autorización ambiental y denuncian molestias', url: 'https://www.elobservador.com.uy/nacional/vecinos-del-data-center-google-canelones-piden-frenar-avances-reclaman-dejar-efecto-autorizacion-ambiental-y-denuncian-molestias-n6053924', date: '2026-08-12' },
    ],
    es: {
      title: 'El data center de Google y el agua potable que iba a consumir',
      dek: 'El proyecto preveía usar hasta 7.600 metros cúbicos diarios de agua de OSE. Tras la polémica pasó a enfriarse por aire, pero la autorización sigue cuestionada.',
      contexto: 'Google proyectó un centro de datos en el Parque de las Ciencias, una zona franca del departamento de Canelones. En marzo de 2023, en plena sequía, la diaria informó que su filial Eleanor Applications SRL había declarado un consumo de hasta 7.600 metros cúbicos diarios de agua potable —7.600.000 litros— en su segunda fase, equivalente al consumo diario de 55.000 personas, provista por OSE; la primera fase preveía la mitad. El dato salió a la luz después de que el investigador de la Facultad de Ciencias Sociales de la Udelar, Daniel Peña, detectara que el proyecto de viabilidad ambiental había sido clasificado como «secreto industrial». La revelación coincidió con la peor crisis de agua potable en décadas.',
      hallazgo: 'En noviembre de 2023 El Observador informó que Google reformuló el proyecto: un edificio en lugar de dos, alrededor de un tercio de la capacidad prevista y enfriamiento por aire mediante chillers de circuito cerrado, con lo que el consumo de agua potable bajó a 48 metros cúbicos diarios, sólo para cocina y baños. El Ministerio de Ambiente pidió a la empresa precisar el consumo máximo de energía y confirmar que la demanda no comprometería la calidad del servicio de UTE a otros consumidores. En agosto de 2024 Brecha publicó una columna de opinión del investigador Daniel Peña que cuestionó la aprobación: sostuvo que el ministerio aprobó la construcción el 6 de junio de 2024 pero comunicó la decisión «un mes y medio después», y que aprobó «haciendo caso omiso» a los 421 formularios ciudadanos que pedían más estudios. Peña señaló además 25.000 toneladas anuales de CO₂ y 86 toneladas de basura tóxica por año.',
      statusNote: 'El Observador informó el 12 de agosto de 2026 que cuatro familias vecinas presentaron el 29 de julio de 2026 un recurso ante el Ministerio de Ambiente pidiendo dejar sin efecto la autorización ambiental de junio de 2024. Denuncian impacto visual, iluminación industrial que alteró sustancialmente las condiciones nocturnas y ruidos antes inexistentes —purgas de cañerías, pruebas de generadores y funcionamiento de equipos— y sostienen que, pese a haber sido identificados en el estudio de impacto como el vecino más vulnerable al impacto acústico, nunca fueron notificados ni consultados formalmente. La nota consigna que el emprendimiento, llamado Los Teros, involucra unos US$ 850 millones, y que si el ministerio rechaza el recurso las familias podrían ir a la vía contencioso-administrativa. El artículo no recoge respuesta de Google ni del ministerio. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores al 12 de agosto de 2026.',
      porQueImporta: 'El agua potable que una empresa consume sale de la misma red que abastece a los hogares, y en 2023 esa red no alcanzó. El caso muestra qué se puede declarar secreto industrial en un expediente ambiental y cuánto margen tiene un vecino para enterarse a tiempo de lo que se instala al lado de su casa.',
      caveat: 'No es una compra estatal: es una inversión privada en zona franca con autorización ambiental del Estado, por lo que casi con certeza no aparece en el feed de compras públicas. Lo que sí podría aparecer son contratos de monitoreo o consultoría ambiental del ministerio. La pieza de Brecha es una columna de opinión firmada, no una nota informativa, y ni ella ni el resto de las fuentes recogen la posición de Google.',
    },
    en: {
      title: 'Google\'s data centre and the drinking water it was to use',
      dek: 'The project foresaw using up to 7,600 cubic metres of OSE water a day. After the controversy it switched to air cooling, but the permit is still contested.',
      contexto: 'Google planned a data centre at Parque de las Ciencias, a free trade zone in Canelones department. In March 2023, at the height of the drought, la diaria reported that its subsidiary Eleanor Applications SRL had declared consumption of up to 7,600 cubic metres of drinking water a day — 7,600,000 litres — in its second phase, equivalent to the daily use of 55,000 people, supplied by OSE; the first phase foresaw half that. The figure came to light after Daniel Peña, a researcher at Udelar\'s Faculty of Social Sciences, found that the environmental viability filing had been classified as an "industrial secret". The revelation coincided with the worst drinking-water crisis in decades.',
      hallazgo: 'In November 2023 El Observador reported that Google reformulated the project: one building instead of two, around a third of the planned capacity and air cooling via closed-circuit chillers, cutting drinking-water use to 48 cubic metres a day, only for kitchen and bathrooms. The Ministry of Environment asked the company to specify maximum energy consumption and confirm that demand would not compromise UTE\'s service quality for other consumers. In August 2024 Brecha published an opinion column by researcher Daniel Peña questioning the approval: he held that the ministry approved construction on 6 June 2024 but announced the decision "a month and a half later", and that it approved "disregarding" the 421 citizen submissions requesting further studies. Peña also flagged 25,000 tonnes of CO₂ a year and 86 tonnes of toxic waste annually.',
      statusNote: 'El Observador reported on 12 August 2026 that four neighbouring families filed an appeal with the Ministry of Environment on 29 July 2026 seeking to annul the June 2024 environmental authorisation. They report visual impact, industrial lighting that substantially altered night-time conditions, and previously nonexistent noise — pipe flushing, generator testing and equipment operation — and hold that, despite having been identified in the impact study as the neighbour most vulnerable to acoustic impact, they were never formally notified or consulted. The report records that the development, named Los Teros, involves some US$850 million, and that if the ministry rejects the appeal the families could go to the administrative courts. The article carries no response from Google or the ministry. As of this file\'s closing (August 2026) no developments after 12 August 2026 are on record.',
      porQueImporta: 'The drinking water a company uses comes from the same network that supplies homes, and in 2023 that network fell short. The case shows what can be declared an industrial secret in an environmental file, and how much room a neighbour has to find out in time what is being built next door.',
      caveat: 'This is not a state purchase: it is a private investment in a free trade zone with a state environmental permit, so it almost certainly does not appear in the public procurement feed. What could appear are the ministry\'s environmental monitoring or consultancy contracts. The Brecha piece is a signed opinion column, not a news report, and neither it nor the other sources carry Google\'s position.',
    },
  },
  {
    slug: 'represa-casupa-licitacion-sin-estudios',
    emoji: '🏞️',
    theme: 'ambiente',
    period: '2025-2029',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'Préstamo de la CAF por US$ 130 millones: US$ 110 millones para la obra y US$ 20 millones para expropiaciones (Presidencia y Subrayado, 2025)',
    organisms: ['Administración de las Obras Sanitarias del Estado (OSE)', 'Ministerio de Ambiente'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Administración de las Obras Sanitarias del Estado',
        'Dirección Nacional de Medio Ambiente',
      ],
      yearFrom: 2025,
      yearTo: 2029,
    },
    sources: [
      { outlet: 'Presidencia de la República', title: 'CAF aprobó préstamo de 130 millones de dólares para represa en Casupá', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/caf-aprobo-prestamo-130-millones-dolares-para-represa-casupa', date: '2025-10-11' },
      { outlet: 'Subrayado', title: 'OSE firmó acuerdo con CAF para financiar construcción de represa de Casupá: préstamo de USD 130 millones', url: 'https://www.subrayado.com.uy/ose-firmo-acuerdo-caf-financiar-construccion-represa-casupa-prestamo-usd-130-millones-n987269', date: '2025-09-08' },
      { outlet: 'la diaria', title: 'Agua, residuos e impuesto a fitosanitarios: Ambiente defendió su presupuesto y ratificó la obra de Casupá', url: 'https://ladiaria.com.uy/politica/articulo/2025/9/agua-residuos-e-impuesto-a-fitosanitarios-ambiente-defendio-su-presupuesto-y-ratifico-la-obra-de-casupa/', date: '2025-09-17' },
      { outlet: 'Ámbito', title: 'Edgardo Ortuño avanzará con la represa de Casupá, a pesar de no tener los estudios ambientales concluidos', url: 'https://www.ambito.com/uruguay/edgardo-ortuno-avanzara-la-represa-casupa-pesar-no-tener-los-estudios-ambientales-concluidos-n6283506', date: '2026-05-31' },
    ],
    es: {
      title: 'Casupá: la represa más grande del país, con estudios sin cerrar',
      dek: 'OSE financió con US$ 130 millones de la CAF la mayor reserva de agua del país. El ministro de Ambiente confirmó que licitaría sin los estudios ambientales concluidos.',
      contexto: 'La represa de Casupá, en el departamento de Florida, es la apuesta del gobierno de Yamandú Orsi para asegurar el agua potable del área metropolitana después de la crisis de 2023. Según Presidencia, tendrá 118 millones de metros cúbicos de agua dulce, será la más grande del país y está comprendida entre los 63 compromisos asumidos por el Gobierno; Subrayado precisó que es casi el doble de la capacidad de Paso Severino (67 millones de metros cúbicos). La CAF aprobó el préstamo de US$ 130 millones el 10 de octubre de 2025: US$ 110 millones para la obra y US$ 20 millones para expropiaciones, según Subrayado, que consignó además unos US$ 63 millones para modernización tecnológica de OSE y una cooperación técnica no reembolsable de US$ 160.000 destinada a evaluaciones ambientales y pliegos.',
      hallazgo: 'En mayo de 2026, según Ámbito, el ministro de Ambiente Edgardo Ortuño confirmó que durante junio se realizaría el llamado a licitación pública internacional pese a que los estudios ambientales no estaban concluidos: «No solo no vamos a detener el proyecto, sino que vamos a avanzar», afirmó. El senador nacionalista Martín Lema pidió suspender la licitación, por considerar «absolutamente improcedente e institucionalmente riesgoso» avanzar sin los estudios de impacto terminados. Ortuño respondió que el ministerio está actualizando los estudios técnicos en coordinación con OSE, la Universidad de la República y equipos independientes, y aclaró que «no va a haber construcción de la obra sin autorización ambiental», citando como antecedente el proyecto Neptuno-Arazatí, donde la licitación (marzo de 2023) precedió a la autorización ambiental (diciembre de 2024). La misma nota consignó ocho consorcios precalificados y expropiaciones que alcanzan a 37 propietarios en 102 padrones. En setiembre de 2025 Ortuño ya había ratificado la obra ante la comisión de Presupuesto y anunciado que la Udelar participaría en la evaluación de impacto ambiental.',
      statusNote: 'El cronograma informado por Subrayado y Ámbito prevé el llamado público a comienzos de 2026, adjudicación a fines de 2026, inicio de obra a principios de 2027 y finalización a mediados de 2029, más un llenado del embalse de entre seis meses y un año según las lluvias. El presidente de OSE, Pablo Ferreri, definió la obra como la reserva de agua dulce bruta que el área metropolitana necesita para asegurar el abastecimiento hacia 2045. Al cierre de esta ficha (agosto de 2026) no constan adjudicaciones posteriores a mayo de 2026 verificadas para esta ficha.',
      porQueImporta: 'Es la obra de agua más grande del país y la paga OSE con deuda, es decir con la tarifa. Define si el área metropolitana vuelve a quedarse sin reserva en la próxima seca, y también cuánta tierra se inunda y qué se compensa a quienes viven ahí.',
      caveat: 'La licitación internacional y las expropiaciones deberían aparecer en el feed a nombre de OSE, pero el financiamiento externo de la CAF puede tramitarse por procedimientos propios del organismo multilateral y no reflejarse como una compra estatal común. El ministerio sostiene que la licitación puede preceder a la autorización ambiental y que sin ella no habrá construcción.',
    },
    en: {
      title: 'Casupá: the country\'s biggest dam, with studies unfinished',
      dek: 'OSE financed the country\'s largest water reserve with US$130 million from CAF. The environment minister confirmed he would tender without the environmental studies finished.',
      contexto: 'The Casupá dam, in Florida department, is Yamandú Orsi\'s government\'s bet to secure drinking water for the metropolitan area after the 2023 crisis. According to the Presidency, it will hold 118 million cubic metres of fresh water, will be the country\'s largest, and is among the 63 commitments the Government has taken on; Subrayado specified it is nearly double the capacity of Paso Severino (67 million cubic metres). CAF approved the US$130 million loan on 10 October 2025: US$110 million for construction and US$20 million for expropriations, according to Subrayado, which also recorded some US$63 million for OSE\'s technological modernisation and a US$160,000 non-reimbursable technical cooperation grant for environmental assessments and tender documents.',
      hallazgo: 'In May 2026, according to Ámbito, Environment Minister Edgardo Ortuño confirmed the international public tender would be called during June even though the environmental studies were not finished: "Not only are we not going to stop the project, we are going to move forward," he said. National Party senator Martín Lema asked for the tender to be suspended, calling it "absolutely improper and institutionally risky" to proceed without completed impact studies. Ortuño replied that the ministry is updating the technical studies in coordination with OSE, the Universidad de la República and independent teams, and clarified that "there will be no construction of the works without environmental authorisation", citing as precedent the Neptuno-Arazatí project, where the tender (March 2023) preceded the environmental authorisation (December 2024). The same report recorded eight pre-qualified consortia and expropriations reaching 37 owners across 102 parcels. In September 2025 Ortuño had already reaffirmed the works before the Budget committee and announced that Udelar would take part in the environmental impact assessment.',
      statusNote: 'The schedule reported by Subrayado and Ámbito foresees the public call in early 2026, award in late 2026, construction starting in early 2027 and completion by mid-2029, plus six months to a year to fill the reservoir depending on rainfall. OSE president Pablo Ferreri described the works as the raw freshwater reserve the metropolitan area needs to secure supply towards 2045. As of this file\'s closing (August 2026) no awards after May 2026 have been verified for this file.',
      porQueImporta: 'It is the country\'s largest water project and OSE pays for it with debt — that is, with the tariff. It determines whether the metropolitan area again runs out of reserves in the next drought, and also how much land is flooded and what is compensated to those who live there.',
      caveat: 'The international tender and the expropriations should appear in the feed under OSE, but CAF\'s external financing may be processed through the multilateral lender\'s own procedures and not show up as an ordinary state purchase. The ministry holds that the tender may precede the environmental authorisation and that without it there will be no construction.',
    },
  },
  {
    slug: 'upm-rio-negro-derrame-y-sanciones',
    emoji: '🏭',
    theme: 'ambiente',
    period: '2023-2025',
    statusKind: 'auditoria',
    status: 'investigacion',
    amountReported: 'Una de las multas aplicadas a la planta equivalió a unos 20.800 dólares en unidades reajustables (la diaria, octubre de 2023)',
    organisms: ['Ministerio de Ambiente'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'la diaria', title: 'Derrame de UPM deja en evidencia un sistema de control que «termina siendo un estímulo a la contaminación»', url: 'https://ladiaria.com.uy/ambiente/articulo/2023/10/derrame-de-upm-deja-en-evidencia-un-sistema-de-control-que-termina-siendo-un-estimulo-a-la-contaminacion/', date: '2023-10-09' },
      { outlet: 'El Observador', title: 'Estudios midieron la calidad de las aguas del río Negro tras el primer año de operaciones de UPM: los resultados', url: 'https://www.elobservador.com.uy/nacional/estudios-midieron-la-calidad-las-aguas-del-rio-negro-el-primer-ano-operaciones-upm-los-resultados-n5975821', date: '2024-12-19' },
      { outlet: 'El Observador', title: 'Calidad del Río Negro empeoró en verano; Ambiente no ve «patrón» que permita «vincular directamente» a UPM y apunta a influencia de «otros factores»', url: 'https://www.elobservador.com.uy/nacional/calidad-del-rio-negro-empeoro-verano-ambiente-no-ve-patron-que-permita-vincular-directamente-upm-y-apunta-influencia-otros-factores-n6011775', date: '2025-08-07' },
    ],
    es: {
      title: 'UPM en el río Negro: 14 sanciones y un monitoreo que no concluye',
      dek: 'La planta de Paso de los Toros acumuló 14 sanciones ambientales y un derrame de soda cáustica. El Ministerio dice no ver un patrón que la vincule al deterioro del río.',
      contexto: 'La segunda planta de celulosa de UPM, en Paso de los Toros, empezó a operar en 2023 y vierte sus efluentes al río Negro, entre las represas de Rincón del Bonete y Baygorria. El Ministerio de Ambiente es el organismo encargado de controlarla: define los parámetros de vertido, recibe los informes de monitoreo de la empresa y realiza su propio seguimiento de la calidad del agua, incluido el análisis satelital de floraciones de algas.',
      hallazgo: 'la diaria informó el 9 de octubre de 2023, a partir de un pedido de acceso a la información pública al Ministerio de Ambiente, que a comienzos de setiembre UPM vertió alrededor de un millón de litros de soda cáustica a un curso de agua en Durazno, y que la planta acumulaba 14 sanciones: 11 durante la construcción y tres desde el inicio de la operación. Una de las multas equivalió a unos 20.800 dólares en unidades reajustables. Entre los incumplimientos figuraban inconsistencias e imprecisiones en los informes de monitoreo, vertidos por encima de los parámetros permitidos con cloro libre y compuestos nitrogenados, y el inicio no autorizado de la construcción de la planta de tratamiento de efluentes. El título de la nota recoge la crítica de que el sistema de control «termina siendo un estímulo a la contaminación». En diciembre de 2024 El Observador informó que el equipo técnico del ministerio no halló diferencias significativas de clorofila-a al analizar el río en tres tramos amplios, aunque al dividirlo en 19 sectores identificó diferencias significativas en siete, que atribuyó a cambios en las condiciones hidrológicas y no al vertido de la planta.',
      statusNote: 'El monitoreo continúa. Según El Observador, entre enero y abril de 2025 se registraron las mayores concentraciones de clorofila-a desde que existen registros satelitales, en 2017, con diferencias significativas en la mayoría de los 19 sectores medidos entre Rincón del Bonete y Baygorria, tanto aguas arriba como aguas abajo de la planta. La Dinacea concluyó que no observa «un patrón espacial claro que permita vincular directamente esas diferencias con la presencia del vertido de UPM II» y señaló que otros factores —condiciones ecológicas, hidrológicas y/o climáticas particulares de 2025— pudieron tener influencia determinante. Un estudio consignado en diciembre de 2024 concluyó que los requerimientos legales de calidad del agua se cumplieron en general. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a agosto de 2025.',
      porQueImporta: 'El río Negro abastece de agua a ciudades del interior y es lugar de baño y pesca. Que el control funcione o no define si una empresa privada internaliza el costo de contaminar o lo traslada a los vecinos y al Estado, que después paga potabilización, monitoreo y remediación.',
      caveat: 'UPM no es proveedora del Estado en este caso, así que no hay contratos suyos que cruzar. Lo que sí puede aparecer en el feed son las compras del Ministerio de Ambiente para monitoreo, laboratorio y análisis de agua. Las notas citadas no recogen respuesta ni descargo de UPM, y el propio ministerio sostiene que no puede vincular directamente el deterioro del río al vertido de la planta.',
    },
    en: {
      title: 'UPM on the Río Negro: 14 sanctions and inconclusive monitoring',
      dek: 'The Paso de los Toros mill accumulated 14 environmental sanctions and a caustic soda spill. The Ministry says it sees no pattern linking it to the river\'s decline.',
      contexto: 'UPM\'s second pulp mill, at Paso de los Toros, began operating in 2023 and discharges its effluent into the Río Negro, between the Rincón del Bonete and Baygorria dams. The Ministry of Environment is the body that oversees it: it sets discharge parameters, receives the company\'s monitoring reports and runs its own water quality follow-up, including satellite analysis of algal blooms.',
      hallazgo: 'la diaria reported on 9 October 2023, based on a freedom-of-information request to the Ministry of Environment, that in early September UPM discharged around one million litres of caustic soda into a watercourse in Durazno, and that the mill had accumulated 14 sanctions: 11 during construction and three since operations began. One fine amounted to some US$20,800 in adjustable units. The breaches included inconsistencies and imprecisions in monitoring reports, discharges above permitted parameters containing free chlorine and nitrogen compounds, and the unauthorised start of construction of the effluent treatment plant. The article\'s headline carries the criticism that the control system "ends up being a stimulus to contamination". In December 2024 El Observador reported that the ministry\'s technical team found no significant chlorophyll-a differences when analysing the river in three broad stretches, though dividing it into 19 sectors it identified significant differences in seven, which it attributed to changes in hydrological conditions rather than the plant\'s discharge.',
      statusNote: 'Monitoring continues. According to El Observador, between January and April 2025 the highest chlorophyll-a concentrations since satellite records began in 2017 were recorded, with significant differences in most of the 19 sectors measured between Rincón del Bonete and Baygorria, both upstream and downstream of the plant. Dinacea concluded that it does not observe "a clear spatial pattern allowing those differences to be linked directly to the presence of UPM II\'s discharge" and noted that other factors — ecological, hydrological and/or climatic conditions particular to 2025 — could have had a determining influence. A study recorded in December 2024 concluded that legal water quality requirements were generally met. As of this file\'s closing (August 2026) no developments after August 2025 are on record.',
      porQueImporta: 'The Río Negro supplies water to inland cities and is used for swimming and fishing. Whether oversight works determines if a private company internalises the cost of polluting or passes it to neighbours and to the State, which then pays for treatment, monitoring and remediation.',
      caveat: 'UPM is not a state supplier in this case, so there are no contracts of its own to cross-reference. What can appear in the feed are the Ministry of Environment\'s purchases for monitoring, laboratory work and water analysis. The articles cited carry no response or rebuttal from UPM, and the ministry itself holds that it cannot directly link the river\'s decline to the plant\'s discharge.',
    },
  },
  {
    slug: 'vertederos-cielo-abierto-meta-2025',
    emoji: '♻️',
    theme: 'ambiente',
    period: '2021-2026',
    statusKind: 'gestion',
    status: 'inconcluso',
    amountReported: 'US$ 17 millones de apoyo financiero del gobierno central a doce intendencias para el cierre de vertederos a cielo abierto (Ministerio de Ambiente, diciembre de 2023)',
    organisms: ['Ministerio de Ambiente', 'Intendencia de Salto', 'Intendencia de Montevideo', 'Intendencia de Canelones'],
    feedCoverage: 'likely',
    sources: [
      { outlet: 'Búsqueda', title: 'Gobierno prevé cerrar todos los vertederos de basura para 2025: las condiciones ambientales son «graves» e «inadmisibles»', url: 'https://www.busqueda.com.uy/Secciones/Gobierno-preve-cerrar-todos-los-vertederos-de-basura-para-2025-las-condiciones-ambientales-son-graves-e-inadmisibles--uc51685', date: '2022-03-23' },
      { outlet: 'Ministerio de Ambiente', title: 'Doce intendencias se suman al cierre de vertederos a cielo abierto durante 2023', url: 'https://www.gub.uy/ministerio-ambiente/comunicacion/noticias/doce-intendencias-se-suman-cierre-vertederos-cielo-abierto-durante-2023', date: '2023-12-20' },
      { outlet: 'En Perspectiva', title: 'La mayoría de los vertederos de basura no cumple con las condiciones básicas para minimizar sus impactos ambientales', url: 'https://enperspectiva.uy/en-perspectiva-programa/la-mesa/la-mayoria-de-los-vertederos-de-basura-no-cumple-con-las-condiciones-basicas-para-minimizar-sus-impactos-ambientales-que-soluciones-tiene-este-problema/', date: '2023-02-28' },
      { outlet: 'la diaria', title: 'La Intendencia de Salto pasará a manos de privados el manejo del vertedero y sistema de recolección de residuos por hasta 12 años', url: 'https://ladiaria.com.uy/salto/articulo/2026/8/la-intendencia-de-salto-pasara-a-manos-de-privados-el-manejo-del-vertedero-y-sistema-de-recoleccion-de-residuos-por-hasta-12-anos/', date: '2026-08-12' },
      { outlet: 'Ministerio de Ambiente', title: 'Primer Plan Nacional de Gestión de Residuos de Uruguay ingresa en su etapa final y abre período de consulta pública', url: 'https://www.gub.uy/ministerio-ambiente/comunicacion/noticias/primer-plan-nacional-gestion-residuos-uruguay-ingresa-su-etapa-final-abre', date: '2021-10-07' },
    ],
    es: {
      title: 'Cerrar todos los basurales en 2025: la meta que venció sin cumplirse',
      dek: 'El Plan Nacional de Gestión de Residuos fijó «cero vertedero a cielo abierto para 2025». De 66 vertederos, sólo seis tenían autorización ambiental.',
      contexto: 'El primer Plan Nacional de Gestión de Residuos de Uruguay, elaborado en el marco de la ley 19.829 y sometido a consulta pública entre el 8 de octubre y el 15 de noviembre de 2021, fijó como objetivo «CERO vertedero a cielo abierto para 2025», con la instalación de rellenos sanitarios, eventualmente regionales. La disposición final de residuos es competencia de las intendencias, mientras que el Ministerio de Ambiente autoriza y controla. En diciembre de 2023 el ministerio informó que doce intendencias se sumaban al proceso con un apoyo financiero de US$ 17 millones del gobierno central, y que esos convenios implicaban «la clausura, al 2025, de todos estos sitios».',
      hallazgo: 'Búsqueda informó en marzo de 2022 que de los 66 vertederos que operaban en el país sólo seis contaban con autorización ambiental —Montevideo, Maldonado, Rocha, Florida, Fray Bentos y Paso de los Toros—, que concentraban alrededor del 65% de los residuos enterrados, y que los otros 60 funcionaban en condiciones inadecuadas o parcialmente adecuadas, con quema a cielo abierto sin controles y contaminación. El entonces ministro de Ambiente, Adrián Peña, describió la situación de la mayoría de los vertederos del interior como «grave» y en algunos casos «inadmisible», y la nota consignó incendios de verano en Rivera, Tacuarembó, Durazno, Lavalleja, Melo, Young y Trinidad. En febrero de 2023 En Perspectiva reunió a Jorge Alsina (Intendencia de Montevideo), Leonardo Herou (Intendencia de Canelones) y Marisol Mallo (Dirección Nacional de Medio Ambiente) en torno a la misma constatación: la mayoría de los sitios de disposición final son vertederos a cielo abierto que no cumplen las condiciones básicas para minimizar sus impactos ambientales, sanitarios y sociales.',
      statusNote: 'La meta de 2025 venció. Para esta ficha no se localizó un balance oficial que confirme cuántos vertederos se cerraron efectivamente. El 12 de agosto de 2026 la diaria informó que la Intendencia de Salto presentó a la Junta Departamental un plan departamental de residuos para pasar a manos privadas, por hasta 12 años, el manejo del vertedero y la recolección; el director Sergio Acuña lo definió como una transformación «histórica», financiada por un fideicomiso ya aprobado que cubrirá el cierre sanitario del vertedero actual y la modernización del reciclaje, y la nota consigna que aún resta concretar la solución definitiva para el vertedero. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores al 12 de agosto de 2026.',
      porQueImporta: 'Un vertedero a cielo abierto quema plástico al lado de casas, filtra líquidos a la napa y contamina el arroyo del que se saca agua. Cerrarlos cuesta obra y equipamiento que pagan las intendencias, y cada año de demora es un año más de humo y lixiviados para quienes viven cerca.',
      caveat: 'El cierre y la operación de vertederos se contratan por cada intendencia, con nombres de objeto muy variados (obra civil, celda, transporte, maquinaria), por lo que un solo término de búsqueda no captura el gasto completo. Los US$ 17 millones son apoyo del gobierno central, no el costo total. El relevamiento de 66 vertederos es de 2022 y puede haber variado.',
    },
    en: {
      title: 'Closing every dump by 2025: the deadline that passed unmet',
      dek: 'The National Waste Plan set "ZERO open-air dumps by 2025". Of 66 landfills, only six held an environmental permit.',
      contexto: 'Uruguay\'s first National Waste Management Plan, drawn up under law 19,829 and put to public consultation between 8 October and 15 November 2021, set as its goal "ZERO open-air dumps by 2025", with the installation of sanitary landfills, possibly regional ones. Final disposal is the departmental governments\' responsibility, while the Ministry of Environment authorises and oversees. In December 2023 the ministry reported that twelve departments were joining the process with US$17 million in financial support from central government, and that those agreements entailed "the closure, by 2025, of all these sites".',
      hallazgo: 'Búsqueda reported in March 2022 that of the 66 landfills operating in the country only six held an environmental permit — Montevideo, Maldonado, Rocha, Florida, Fray Bentos and Paso de los Toros — which took in around 65% of buried waste, and that the other 60 operated in inadequate or partially adequate conditions, with uncontrolled open-air burning and contamination. The then Environment Minister, Adrián Peña, described the situation of most inland landfills as "grave" and in some cases "inadmissible", and the report recorded summer fires in Rivera, Tacuarembó, Durazno, Lavalleja, Melo, Young and Trinidad. In February 2023 En Perspectiva brought together Jorge Alsina (Intendencia de Montevideo), Leonardo Herou (Intendencia de Canelones) and Marisol Mallo (National Environment Directorate) around the same finding: most final disposal sites are open-air dumps that do not meet the basic conditions to minimise their environmental, health and social impacts.',
      statusNote: 'The 2025 target has passed. For this file no official assessment confirming how many landfills were actually closed could be located. On 12 August 2026 la diaria reported that the Intendencia de Salto submitted a departmental waste plan to the Departmental Board to hand landfill management and collection to private operators for up to 12 years; director Sergio Acuña described it as a "historic" transformation, financed by an already approved trust fund that will cover the sanitary closure of the current landfill and the modernisation of recycling, and the article records that a definitive solution for the landfill still has to be settled. As of this file\'s closing (August 2026) no developments after 12 August 2026 are on record.',
      porQueImporta: 'An open-air dump burns plastic next to homes, leaks liquids into the water table and contaminates the stream water is drawn from. Closing them takes works and equipment paid for by the departments, and every year of delay is another year of smoke and leachate for those living nearby.',
      caveat: 'Landfill closure and operation are contracted by each department under widely varying purchase descriptions (civil works, cells, transport, machinery), so a single search term will not capture the full spend. The US$17 million is central government support, not the total cost. The count of 66 landfills dates from 2022 and may have changed.',
    },
  },
]
