import type { CasoDef } from '../types'

/**
 * cancer — 10 dossiers, 8 of them with a live cross-reference.
 *
 * Every source URL was fetched and every query was resolved against the live
 * collection before this file was committed (scripts/verify-casos.ts re-checks
 * both). A caso with no `query` is not a gap in the research: its money does
 * not travel through the Compras Estatales feed at all, which `feedCoverage`
 * records and the page states outright.
 */
export const CASOS_CANCER: CasoDef[] = [
  {
    slug: 'aceleradores-radioterapia-sin-software-asse',
    emoji: '☢️',
    theme: 'cancer',
    period: '2018-2023',
    statusKind: 'gestion',
    status: 'terminado',
    amountReported: 'US$ 3.975.000 por tres aceleradores lineales según El Observador (marzo de 2023); en su nota de diciembre de 2020 el mismo diario consignó US$ 3.750.000 «como surge de la página web de compras estatales»',
    organisms: ['Administración de los Servicios de Salud del Estado (ASSE)', 'Instituto Nacional del Cáncer', 'Hospital de Tacuarembó', 'Centro Hospitalario Pereira Rossell'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Hospital Maciel',
        'Centro Hospitalario Pereira Rossell',
        'Hospital Pasteur',
        'Centro Departamental de Rocha',
        'Centro Departamental de Salto',
        'Centro Auxiliar de Pando',
        'Hospital Español',
        'Centro Auxiliar de Bella Unión',
        'Servicio Nacional de Ortopedia y Traumatología',
        'Centro Departamental de Flores',
        'Centro Hospitalario Maldonado-San Carlos',
        'Centro de Rehabilitación Médico Ocupacional y Sicosocial',
        'Hospital de San Carlos',
        'Centro Departamental de Paysandú',
        'Red de Atención Primaria Area Metropolitana',
        'Laboratorio Químico Industrial Francisco Dorrego',
        'Centro Departamental de Canelones',
        'Administración de Servicios de Salud del Estado',
        'Hospital Dr. Gustavo Saint Bois',
        'Centro Auxiliar de las Piedras',
        'Hospital Vilardebó',
        'Direc.Sistema de Atenciòn Integral Personas Privad. Libertad',
        'Red de Atención Primaria de Rocha',
        'Centro Auxiliar de Río Branco',
        'Red de Atención Primaria de Rivera',
        'Instituto Nacional del Cáncer',
        'Centro Departamental de Maldonado',
        'Centro Departamental de Durazno',
        'Instituto Nal.de Reumatalogía Prof.Dr. Moisés Mizraji',
        'Centro Auxiliar de Young',
        'Red de Atención Primaria de San José',
        'Centro Departamental de Tacuarembó',
        'Centro Departamental de Treinta y Tres',
        'Colonia Siquiátrica Dr. Bernardo Etchepare',
        'Hospital del Cerro',
        'Red de Atención Primaria de Salto',
        'Centro Departamental de San José',
        'Centro Departamental de Lavalleja',
        'Hospital -Centro Geriátrico Dr. Luis Piñeiro del Campo',
        'Centro Departamental de Florida',
        'Hospital Especializado de Ojos',
        'Centro Departamental de Cerro Largo',
        'Centro Auxiliar de San Carlos',
        'Centro Departamental de Rivera',
        'Servicio Nacional de Sangre',
        'Centro Auxiliar Chuy',
        'Red de Atención Primaria de Paysandú',
        'Centro Departamental de Soriano',
        'Red de Atención Primaria de Canelones',
        'Ctro Inf.y Ref.Nal de Red Drogas',
        'Red de Atención Primaria de Cerro Largo',
        'Centro Auxiliar de Guichón',
        'Centro Departamental de Río Negro',
        'Centro Departamental de Salud Pública de Colonia',
        'Red de Atención Primaria de Maldonado',
        'Red de Atención Primaria de Río Negro',
        'Centro Auxiliar de Paso de los Toros',
        'Red de Atención Primaria de Colonia',
        'Red de Atención Primaria de Artigas',
        'Centro Auxiliar de Carmelo',
        'Colonia Dr.Santín Carlos Rossi',
        'NO VIGENTE Centro Auxiliar Ciudad de la Costa',
        'Centro Departamental de Artigas',
        'Red de Atención Primaria de Tacuarembó',
        'Centro Auxiliar de Rosario',
        'Centro Auxiliar de Juan Lacaze',
        'Asistencia Integral',
        'Red de Atención Primaria de Treinta y Tres',
        'Red de Atención Primaria de Florida',
        'Red de Atención Primaria de Soriano',
        'Atencion de Urgencia Emergencia Prehospitalaria y Traslado.',
        'Centro Auxiliar de Dolores',
        'Centro Aux. de Cardona y Florencio Sánchez',
        'Red de Atención Primaria de Lavalleja',
        'Centro Auxiliar de Castillos',
        'Red de Atención Primaria de Flores',
        'Red de Atención Primaria de Durazno',
        'Centro Auxiliar de Nueva Helvecia',
        'Inst.Nal.Don.yTransp.Cél.Tej.Or',
        'Centro Auxiliar de Nueva Palmira',
        'NO VIGENTE - Centro Auxiliar de Nueva Helvecia',
        'NO VIGENTE Centro Auxiliar de Tala',
        'NO VIGENTE Centro Auxiliar Ciudad del Plata',
        'NO VIGENTE Centro Auxiliar de Cerro Chato',
        'NO VIGENTE Centro Auxiliar de San Ramón',
        'NO VIGENTE Centro Auxiliar de Aiguá',
        'Centro Auxiliar de Sarandí del Yi',
        'NO VIGENTE Instituto Nacional del Cáncer',
        'NO VIGENTE Centro Hospitalario Pereira Rossell',
      ],
      search: 'acelerador lineal',
      yearFrom: 2018,
      yearTo: 2023,
    },
    sources: [
      { outlet: 'El Observador', title: 'Falla en licitación de equipos de radioterapia postergó recambio de viejos equipos', url: 'https://www.elobservador.com.uy/nota/falla-en-licitacion-de-equipos-de-radioterapia-postergo-recambio-de-viejos-equipos--202012417450', date: '2020-12-14' },
      { outlet: 'El Observador', title: 'Equipos de radioterapia de "última generación" incorporados por ASSE hace más de 4 años aún no están funcionando', url: 'https://www.elobservador.com.uy/nota/equipos-de-radioterapia-incorporados-por-asse-hace-mas-de-4-anos-aun-no-estan-funcionando-202331319270', date: '2023-03-14' },
      { outlet: 'El Observador', title: 'Dos equipos de radioterapia para cáncer estuvieron casi cinco años sin ser usados por ASSE: ¿qué pasó?', url: 'https://www.elobservador.com.uy/nota/dos-equipos-de-radioterapia-para-cancer-estuvieron-casi-cinco-anos-sin-ser-usados-por-asse-que-paso--202371118510', date: '2023-07-12' },
      { outlet: 'Presidencia de la República', title: 'ASSE incorporó equipamiento que incrementa calidad de tratamientos radioterapéuticos', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/asse-incorporo-equipamiento-incrementa-calidad-tratamientos-radioterapeuticos', date: '2023-11-23' },
      { outlet: 'Montevideo Portal', title: 'Hospital de Tacuarembó incorporó el equipo de radioterapia más moderno del país', url: 'https://www.montevideo.com.uy/Archivo/Hospital-de-Tacuarembo-incorporo-el-equipo-de-radioterapia-mas-moderno-del-pais-uc729108?plantilla=1385' },
    ],
    es: {
      title: 'ASSE compró tres aceleradores sin el software para usarlos',
      dek: 'El pliego de 2018 no incluyó los programas de planificación y dosimetría, informó El Observador. Dos de los tres equipos estuvieron casi cinco años sin ser usados.',
      contexto: 'En 2018 ASSE adjudicó a Tera Ingenieros SRL, que representa en Uruguay al fabricante Varian, la compra de tres aceleradores lineales de radioterapia, según El Observador. Los equipos estaban destinados al Instituto Nacional del Cáncer (INCA), al Hospital de Tacuarembó y al Centro Hospitalario Pereira Rossell. Sobre el precio, las propias notas del diario no coinciden: en diciembre de 2020 consignó US$ 3.750.000 «como surge de la página web de compras estatales» y en marzo de 2023 US$ 3.975.000. En ese momento el sector público trataba con aparatos muy antiguos: el de Tacuarembó tenía 23 años y el INCA usaba un acelerador arrendado desde 2014 que tenía 15 años. Sobre el del Pereira Rossell, la misma nota de 2020 dice en un pasaje que tenía 17 años y cita un correo de la directora del centro, Victoria Lafluf, según el cual el equipo en funcionamiento «tiene 26 años de vida útil y presenta fallas técnicas habituales».',
      hallazgo: 'El Observador informó el 14 de diciembre de 2020 que el pliego no había incluido el sistema de planificación de tratamientos (TPS), los sistemas de dosimetría externa ni los programas de control de calidad, sin los cuales los aceleradores no pueden aplicarse a pacientes; el diario estimó el faltante en unos US$ 500.000. El 14 de marzo de 2023 el mismo medio informó que los equipos seguían sin la autorización de funcionamiento de la Autoridad Reguladora Nacional en Radioprotección, que el Pereira Rossell no tenía construido el búnker —por lo que el equipo permaneció meses en cajas— y que en Tacuarembó el director pidió una revisión por una pérdida de gas, con la garantía ya vencida. El 12 de julio de 2023 El Observador consignó que la negociación del mantenimiento preventivo con Tera Ingenieros, proveedor único de ese servicio en el país, llevó más de cuatro años: la empresa pedía entre 12% y 15% anual del valor de los equipos —más de US$ 1 millón por año— y se cerró en torno al 8,3%, unos US$ 600.000 anuales. El presidente de ASSE, Leonardo Cipriani, describió el proceso: «Fue un parto de nalgas, realmente acalambrante». Las fuentes consultadas recogen la explicación de ASSE, pero no incluyen una respuesta de Tera Ingenieros.',
      statusNote: 'El 23 de noviembre de 2023, según Presidencia, ASSE presentó el nuevo equipo de radioterapia del INCA e informó que «la inversión para dejar operativo este equipo fue de 1.336.000 dólares»; agregó que otro equipo se ubicaría en el Pereira Rossell y estaría operativo en diciembre, y que el de Tacuarembó ya estaba en funcionamiento. Montevideo Portal informó que el equipo de Tacuarembó costó unos US$ 1.300.000 y que, con el búnker construido a tal fin, la infraestructura totaliza más de US$ 2 millones de inversión. Al cierre de esta ficha (agosto de 2026) no constan, en las fuentes consultadas, novedades posteriores a noviembre de 2023 sobre eventuales responsabilidades administrativas por la omisión del pliego.',
      porQueImporta: 'Entre 2018 y 2023 los pacientes de ASSE que necesitaban radioterapia siguieron tratándose con aparatos de dos décadas o más mientras equipos nuevos, ya pagados, esperaban. En radioterapia el tiempo no es neutro: cada mes de demora es un mes de tratamientos aplicados con tecnología menos precisa sobre el tejido sano que rodea al tumor.',
      caveat: 'El cruce con datos abiertos puede mostrar la compra de 2018 y los contratos de mantenimiento posteriores publicados en Compras Estatales, pero no la obra civil de los búnkeres ni los convenios de asistencia técnica, que pueden tramitarse por otras vías. La discrepancia de precio entre las dos notas de El Observador no está resuelta en las fuentes.',
    },
    en: {
      title: 'ASSE bought three accelerators without the software to run them',
      dek: 'The 2018 tender left out treatment-planning and dosimetry software, El Observador reported. Two of the three machines went almost five years unused.',
      contexto: 'In 2018 ASSE awarded Tera Ingenieros SRL, the Uruguayan representative of manufacturer Varian, the purchase of three linear accelerators for radiotherapy, according to El Observador. The machines were destined for the National Cancer Institute (INCA), Tacuarembó Hospital and the Pereira Rossell Hospital Centre. On the price, the paper\'s own reports do not agree: in December 2020 it gave US$3,750,000 "as shown on the state procurement website", and in March 2023 US$3,975,000. At the time the public sector was treating patients with very old machines: the Tacuarembó unit was 23 years old and INCA was using an accelerator leased since 2014 that was 15 years old. On the Pereira Rossell machine, the same 2020 report says in one passage that it was 17 years old and quotes an email from the centre\'s director, Victoria Lafluf, saying the machine in operation "has 26 years of useful life and shows habitual technical faults".',
      hallazgo: 'El Observador reported on 14 December 2020 that the tender had not included the treatment planning system (TPS), the external dosimetry systems or the quality-control programs, without which the accelerators cannot be used on patients; the paper estimated the missing items at around US$500,000. On 14 March 2023 the same outlet reported that the machines still lacked an operating authorisation from the National Radiation Protection Regulatory Authority, that Pereira Rossell had not built the bunker —so the equipment sat in crates for months— and that in Tacuarembó the director requested an inspection over a gas leak, with the warranty already expired. On 12 July 2023 El Observador reported that negotiating preventive maintenance with Tera Ingenieros, the country\'s sole supplier of that service, took more than four years: the company asked for 12% to 15% a year of the equipment\'s value —over US$1 million a year— and it closed at around 8.3%, some US$600,000 a year. The president of ASSE, Leonardo Cipriani, described the process: "It was a breech birth, truly cramping". The sources consulted carry ASSE\'s explanation but include no response from Tera Ingenieros.',
      statusNote: 'On 23 November 2023, according to Presidencia, ASSE presented INCA\'s new radiotherapy machine and reported that "the investment to make this equipment operational was 1,336,000 dollars"; it added that another unit would go to Pereira Rossell and be operational in December, and that the Tacuarembó machine was already running. Montevideo Portal reported that the Tacuarembó equipment cost around US$1,300,000 and that, with the purpose-built bunker, the infrastructure totals more than US$2 million in investment. As of this file\'s closing date (August 2026) the sources consulted record nothing after November 2023 on any administrative responsibility for the tender omission.',
      porQueImporta: 'Between 2018 and 2023, ASSE patients who needed radiotherapy kept being treated with machines two decades old or more while new, already-paid-for units waited. In radiotherapy, time is not neutral: every month of delay is a month of treatment delivered with less precise technology over the healthy tissue surrounding the tumour.',
      caveat: 'Open-data cross-referencing can show the 2018 purchase and the later maintenance contracts published on Compras Estatales, but not the civil works for the bunkers or the technical-assistance agreements, which may be processed through other channels. The price discrepancy between the two El Observador reports is not resolved in the sources.',
    },
  },
  {
    slug: 'amparos-medicamentos-alto-precio-costo-fiscal',
    emoji: '⚖️',
    theme: 'cancer',
    period: '2012-2026',
    statusKind: 'debate',
    status: 'debate',
    amountReported: 'US$ 99 millones pagados en 2023 por amparos judiciales de medicamentos de alto precio y técnicas contra el MSP (Ministerio de Economía y Finanzas, Rendición de Cuentas 2023)',
    organisms: ['Ministerio de Salud Pública', 'Fondo Nacional de Recursos'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Ministerio de Salud Pública',
      ],
      yearFrom: 2012,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Ministerio de Economía y Finanzas', title: '5.8.8 Amparos judiciales por Medicamentos de Alto Precio (MAP) y técnicas — Exposición de Motivos, Rendición de Cuentas 2023', url: 'https://www.gub.uy/ministerio-economia-finanzas/comunicacion/publicaciones/exposicion-motivos-rc-2023/58-salud/588-amparos-judiciales-medicamentos' },
      { outlet: 'OPS/OMS', title: 'Uruguay avanza en la construcción de una hoja de ruta para mejorar el acceso a medicamentos y tratamientos de alto costo con apoyo de OPS', url: 'https://www.paho.org/es/noticias/9-7-2026-uruguay-avanza-construccion-hoja-ruta-para-mejorar-acceso-medicamentos', date: '2026-07-09' },
      { outlet: 'Montevideo Portal', title: 'Fondo Nacional de Recursos incorpora prestación de tratamientos para tres tipos de cáncer', url: 'https://www.montevideo.com.uy/Archivo/Fondo-Nacional-de-Recursos-incorpora-prestacion-de-tratamientos-para-tres-tipos-de-cancer-uc899778', date: '2024-09-10' },
      { outlet: '180.com.uy', title: 'Medicamentos de alto costo, entre el interés individual y el colectivo', url: 'https://www.180.com.uy/articulo/58614_lo-que-rodea-al-acceso-a-medicamentos-de-alto-costo', date: '2015-11-09' },
      { outlet: 'Fondo Nacional de Recursos', title: 'Derecho a la Salud, medicamentos y otras prestaciones de alto costo', url: 'https://www.fnr.gub.uy/noticia_slide/derecho-a-la-salud-medicamentos-y-otras-prestaciones-de-alto-costo/', date: '2013-05-07' },
    ],
    es: {
      title: 'Los amparos por medicamentos: US$ 99 millones pagados en 2023',
      dek: 'El Ministerio de Economía informó que en 2023 el Estado pagó US$ 99 millones por amparos judiciales de medicamentos de alto precio. Los juicios pasaron de 331 en 2018 a 2.219 en 2025, según la OPS.',
      contexto: 'El Fondo Nacional de Recursos financia medicamentos de alto costo desde 2005, con criterios de costo-efectividad: según su asesora letrada Leticia Gómez, la cobertura se define mirando «la relación entre el costo y el resultado que le da al paciente», en sobrevida y calidad de vida. Cuando un fármaco no integra esa lista, el paciente puede reclamarlo por acción de amparo, un proceso judicial abreviado. El debate no es nuevo: ya en 2015, 180.com.uy recogía posiciones enfrentadas entre juristas como el ex presidente de la Suprema Corte Leslie Van Rompaey y el docente Juan Ceretta, que ven en el amparo una señal legítima de la sociedad ante políticas públicas insuficientes, y la oncóloga Lucía Delgado, entonces al frente del programa nacional de control del cáncer, que defendía priorizar porque financiar todos los oncológicos de alto costo requeriría, dijo, unos US$ 2.200 millones.',
      hallazgo: 'En la Exposición de Motivos de la Rendición de Cuentas 2023, el Ministerio de Economía y Finanzas informó «un monto de US$ 99 millones por amparos judiciales contra el MSP» en 2023, frente a US$ 128 millones en 2022, sobre un gasto total en medicamentos de alto precio de $ 6.000 millones —US$ 153 millones, 0,2% del PIB 2023—, del que el 48,5% se financió mediante el FNR. El peso de los amparos dentro de ese gasto pasó de 2% en 2012 a 51% en 2019, 60% en 2021, 59% en 2022 y 52% en 2023. El MEF agregó que «el 52% del gasto en amparos judiciales por MAP se concentran en 3 laboratorios (uno de ellos absorbe el 28,4%)» y que «el 43% del total del gasto se concentró en 5 productos, de un total de 150 productos». La Organización Panamericana de la Salud informó en julio de 2026 que «los procesos de amparo pasaron de 331 en 2018 a 2.219 en 2025, y en el primer semestre de 2026 ya se habían registrado 1.328 nuevas acciones».',
      statusNote: 'El propio MEF sostuvo que el crecimiento del gasto se desaceleró en 2023 (0,7%) y lo atribuyó a las políticas de negociación de precios y a la incorporación de medicamentos a la cobertura universal. El 9 de julio de 2026, con apoyo de la OPS, el MSP encabezado por la ministra Cristina Lustemberg convocó una instancia interinstitucional para construir una hoja de ruta de acceso a medicamentos de alto costo, con representantes de la Suprema Corte de Justicia, de las comisiones de Salud del Poder Legislativo y de la Institución Nacional de Derechos Humanos, entre otros. Allí se informó que el FNR cubre 45 patologías y financia 87 medicamentos, y que en 2025 financió 14.474 tratamientos con un presupuesto anual cercano a los US$ 460 millones. Al cierre de esta ficha (agosto de 2026) no constan resoluciones posteriores.',
      porQueImporta: 'Cada peso que sale por sentencia se resta del presupuesto que financia tratamientos para todos. La ministra de Economía Azucena Arbeleche señaló en 2024 que los medicamentos que el MSP debe comprar para atender los amparos «los tiene que comprar a precios que resultan excesivos», y que el acceso por vía judicial «no es equitativo, porque lo consiguen quienes pueden hacerlo mediante un reclamo a la Justicia»: el mismo dinero alcanza para menos pacientes.',
      caveat: 'Los pagos por amparo no se ejecutan como una compra licitada: se cumplen por sentencia y en buena parte a través del FNR, una persona pública no estatal. Por eso es esperable que este gasto no aparezca, o aparezca sólo parcialmente, en el buscador de compras estatales.',
    },
    en: {
      title: 'Court-ordered drugs: US$99 million paid in 2023',
      dek: 'The Finance Ministry reported the State paid US$99 million in 2023 on court injunctions for high-priced medicines. Lawsuits rose from 331 in 2018 to 2,219 in 2025, according to PAHO.',
      contexto: 'The National Resources Fund (FNR) has financed high-cost medicines since 2005 using cost-effectiveness criteria: according to its legal adviser Leticia Gómez, coverage is set by weighing "the relationship between the cost and the result it gives the patient", in survival and quality of life. When a drug is not on that list, patients can claim it through an amparo, a fast-track court process. The debate is not new: back in 2015, 180.com.uy gathered opposing positions between jurists such as former Supreme Court president Leslie Van Rompaey and law professor Juan Ceretta, who see the amparo as a legitimate signal from society about insufficient public policy, and oncologist Lucía Delgado, then head of the national cancer control programme, who defended prioritising because funding every high-cost cancer drug would require, she said, some US$2.2 billion.',
      hallazgo: 'In the explanatory memorandum to the 2023 Rendición de Cuentas, the Ministry of Economy and Finance reported "an amount of US$99 million in court injunctions against the MSP" in 2023, against US$128 million in 2022, out of total spending on high-priced medicines of $6 billion pesos —US$153 million, 0.2% of 2023 GDP— of which 48.5% was financed through the FNR. The share of injunctions within that spending went from 2% in 2012 to 51% in 2019, 60% in 2021, 59% in 2022 and 52% in 2023. The ministry added that "52% of injunction spending on high-priced medicines is concentrated in 3 laboratories (one of which absorbs 28.4%)" and that "43% of total spending was concentrated in 5 products, out of a total of 150 products". The Pan American Health Organization reported in July 2026 that "amparo proceedings went from 331 in 2018 to 2,219 in 2025, and in the first half of 2026 a further 1,328 new actions had already been recorded".',
      statusNote: 'The Finance Ministry itself said spending growth decelerated in 2023 (0.7%) and attributed this to price-negotiation policies and to bringing medicines into universal coverage. On 9 July 2026, with PAHO support, the Health Ministry led by Minister Cristina Lustemberg convened an inter-institutional session to build a roadmap on access to high-cost medicines, with representatives of the Supreme Court, of the legislature\'s health committees and of the national human rights institution, among others. It was reported there that the FNR covers 45 conditions and finances 87 medicines, and that in 2025 it financed 14,474 treatments with an annual budget close to US$460 million. As of this file\'s closing date (August 2026) no subsequent resolutions are on record.',
      porQueImporta: 'Every peso paid out under a court ruling is subtracted from the budget that funds treatment for everyone. Economy Minister Azucena Arbeleche said in 2024 that the medicines the Health Ministry must buy to comply with injunctions "it has to buy at prices that turn out to be excessive", and that access through the courts "is not equitable, because those who obtain it are those able to bring a claim before the courts": the same money reaches fewer patients.',
      caveat: 'Injunction payments are not executed as tendered purchases: they are complied with under court order and largely through the FNR, a non-state public entity. This spending is therefore expected to be absent, or only partly present, in the state procurement search.',
    },
  },
  {
    slug: 'amparo-moratorio-opdualag-msp',
    emoji: '🧬',
    theme: 'cancer',
    period: '2026',
    statusKind: 'judicial',
    status: 'condena',
    amountReported: '«varios miles de dólares por mes» según Subrayado; FM Gente situó el valor de mercado del Opdualag en unos US$ 30.000 mensuales',
    organisms: ['Ministerio de Salud Pública', 'Fondo Nacional de Recursos'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'Subrayado', title: 'Justicia accedió al recurso de amparo que presentó Gonzalo Moratorio y ordena al MSP que le suministre la medicación', url: 'https://www.subrayado.com.uy/justicia-accedio-al-recurso-amparo-que-presento-gonzalo-moratorio-y-ordena-al-msp-que-le-suministre-la-medicacion-n1006681', date: '2026-05-04' },
      { outlet: 'Subrayado', title: 'Tribunal de Apelaciones confirmó condena al MSP por suministro de medicamento a Gonzalo Moratorio', url: 'https://www.subrayado.com.uy/tribunal-apelaciones-confirmo-condena-al-msp-suministro-medicamento-gonzalo-moratorio-n1009225', date: '2026-06-01' },
      { outlet: 'El Observador', title: 'Tribunal de Apelaciones ratificó sentencia que obliga al MSP a suministrar medicamento a Gonzalo Moratorio', url: 'https://www.elobservador.com.uy/nacional/tribunal-apelaciones-ratifico-sentencia-que-obliga-al-msp-suministrar-medicamento-gonzalo-moratorio-n6046044', date: '2026-06-02' },
      { outlet: 'FM Gente', title: 'Condenaron al MSP a suministrarle fármaco de alto costo a Gonzalo Moratorio', url: 'https://www.fmgente.com.uy/noticias/condenaron-suministrarle-farmaco-alto-costo-81253.html', date: '2026-05-04' },
    ],
    es: {
      title: 'La Justicia ordenó al MSP dar Opdualag al virólogo Gonzalo Moratorio',
      dek: 'Dos instancias condenaron al Ministerio a suministrar un fármaco sin registro en Uruguay ni lugar en el Formulario Terapéutico. El caso resume toda la disputa por los medicamentos caros.',
      contexto: 'El científico y virólogo Gonzalo Moratorio fue diagnosticado con un astrocitoma de grado 4 en el lóbulo parietal izquierdo, según informó Subrayado. El tratamiento indicado por su médico tratante, el fármaco Opdualag, no está registrado ante el Ministerio de Salud Pública ni incluido en el Formulario Terapéutico de Medicamentos. Moratorio presentó una acción de amparo contra el MSP y el Fondo Nacional de Recursos: el mismo camino que en 2025 recorrieron 2.219 personas por medicamentos y técnicas de alto precio, según la Organización Panamericana de la Salud.',
      hallazgo: 'El 4 de mayo de 2026 la jueza Lucía Granucci hizo lugar al amparo y ordenó al MSP entregar el medicamento sin costo en un plazo máximo de 24 horas continuas desde la notificación de la sentencia, informó Subrayado; la demanda contra el FNR fue desestimada por falta de legitimación pasiva, según FM Gente y El Observador. El MSP apeló: sostuvo, según El Observador, que el fármaco no está registrado en Uruguay, que no integra el Formulario Terapéutico de Medicamentos y que no existió «ilegalidad manifiesta» en su actuación. El 1º de junio de 2026 el Tribunal de Apelaciones en lo Civil de 3er Turno confirmó la sentencia: para el tribunal, «la actuación judicial en la protección del derecho constitucional a la salud no puede quedar supeditada a requisitos reglamentarios o burocráticos», y el Estado debe asegurar los medios a los «pacientes carentes de recursos suficientes». El Observador consignó que el tribunal también confirmó que el FNR no tiene legitimación pasiva para ser condenado, criterio ya adoptado en primera instancia, y que quedó acreditado que Moratorio no cuenta con recursos suficientes para afrontar el costo.',
      statusNote: 'El Observador informó el 2 de junio de 2026 que la sentencia estableció que el MSP deberá proporcionar el tratamiento indicado por el médico tratante «durante todo el tiempo que sea necesario». Subrayado situó el costo del fármaco en «varios miles de dólares por mes»; FM Gente indicó que su valor de mercado «ronda los 30.000 dólares mensuales». Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores al fallo de segunda instancia del 1º de junio de 2026.',
      porQueImporta: 'Un amparo ganado obliga al Estado a comprar un fármaco puntual, con urgencia y sin margen para negociar el precio. El caso muestra el dilema real: el mismo Estado que rechaza la cobertura por falta de registro termina pagándola por sentencia.',
      caveat: 'Una compra ordenada por sentencia se ejecuta por vía administrativa urgente y no genera necesariamente un llamado en el buscador de compras estatales. Además, el nombre del paciente nunca aparece en un contrato: el cruce sólo podría mostrar adquisiciones del fármaco por parte del MSP.',
    },
    en: {
      title: 'Court orders Health Ministry to supply Opdualag to virologist Moratorio',
      dek: 'Two instances ordered the Ministry to supply a drug that is neither registered in Uruguay nor on the National Therapeutic Formulary. The case distils the whole high-cost drug dispute.',
      contexto: 'Scientist and virologist Gonzalo Moratorio was diagnosed with a grade 4 astrocytoma in the left parietal lobe, Subrayado reported. The treatment indicated by his doctor, the drug Opdualag, is neither registered with the Ministry of Public Health nor included in the National Therapeutic Formulary. Moratorio filed an amparo action against the Ministry and the National Resources Fund: the same route taken in 2025 by 2,219 people over high-priced medicines and techniques, according to the Pan American Health Organization.',
      hallazgo: 'On 4 May 2026 judge Lucía Granucci granted the amparo and ordered the Health Ministry to deliver the medicine at no cost within a maximum of 24 continuous hours from notification of the ruling, Subrayado reported; the claim against the FNR was dismissed for lack of standing, according to FM Gente and El Observador. The Ministry appealed, arguing, according to El Observador, that the drug is not registered in Uruguay, that it is not on the Therapeutic Formulary and that there was no "manifest illegality" in its conduct. On 1 June 2026 the Third Chamber of the Civil Court of Appeals upheld the ruling: for the court, "judicial action in protection of the constitutional right to health cannot be made subject to regulatory or bureaucratic requirements", and the State must guarantee the means for "patients lacking sufficient resources". El Observador reported that the court also confirmed that the FNR has no standing to be found liable, a criterion already adopted at first instance, and that it was established that Moratorio does not have sufficient resources to meet the cost.',
      statusNote: 'El Observador reported on 2 June 2026 that the ruling established the Ministry must provide the treatment indicated by the treating physician "for as long as necessary". Subrayado put the drug\'s cost at "several thousand dollars a month"; FM Gente said its market value "is around 30,000 dollars monthly". As of this file\'s closing date (August 2026) there is nothing on record after the second-instance ruling of 1 June 2026.',
      porQueImporta: 'A won injunction forces the State to buy one specific drug, urgently and with no room to negotiate the price. The case shows the real dilemma: the same State that refuses coverage for lack of registration ends up paying for it under a court order.',
      caveat: 'A purchase ordered by a court is executed through urgent administrative channels and does not necessarily generate a tender in the state procurement search. And a patient\'s name never appears in a contract: cross-referencing could only show Ministry purchases of the drug itself.',
    },
  },
  {
    slug: 'fnr-ampliacion-tratamientos-oncologicos-2024',
    emoji: '💊',
    theme: 'cancer',
    period: '2020-2024',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'US$ 23 millones de aumento del presupuesto del FNR en el primer año (Presidencia, setiembre de 2024)',
    organisms: ['Fondo Nacional de Recursos', 'Ministerio de Salud Pública', 'Ministerio de Economía y Finanzas'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Ministerio de Salud Pública',
        'Ministerio de Economía y Finanzas',
      ],
      yearFrom: 2020,
      yearTo: 2024,
    },
    sources: [
      { outlet: 'Presidencia de la República', title: 'Gobierno anunció financiación de medicamentos contra tres tipos de cáncer', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/gobierno-anuncio-financiacion-medicamentos-contra-tres-tipos-cancer', date: '2024-09-10' },
      { outlet: 'Telenoche', title: 'FNR incorporó 16 tratamientos contra el cáncer a la cobertura gratuita; se beneficiarán 700 pacientes por año', url: 'https://www.telenoche.com.uy/nacionales/fnr-incorporo-16-tratamientos-contra-el-cancer-la-cobertura-gratuita-se-beneficiaran-700-pacientes-ano-n5373230', date: '2024-09-10' },
      { outlet: 'Ministerio de Salud Pública', title: 'Más y mejores tratamientos oncológicos en el FNR', url: 'https://www.gub.uy/ministerio-salud-publica/comunicacion/noticias/mejores-tratamientos-oncologicos-fnr', date: '2024-09-10' },
      { outlet: 'Montevideo Portal', title: 'Fondo Nacional de Recursos incorpora prestación de tratamientos para tres tipos de cáncer', url: 'https://www.montevideo.com.uy/Archivo/Fondo-Nacional-de-Recursos-incorpora-prestacion-de-tratamientos-para-tres-tipos-de-cancer-uc899778', date: '2024-09-10' },
      { outlet: 'Subrayado', title: 'Oncólogos celebran ampliación de cobertura del FNR y aseguran que cambia radicalmente acceso a medicamentos', url: 'https://www.subrayado.com.uy/oncologos-celebran-ampliacion-cobertura-del-fnr-y-aseguran-que-cambia-radicalmente-acceso-medicamentos-n956949', date: '2024-09-11' },
    ],
    es: {
      title: 'El FNR amplió la cobertura oncológica y negoció precios 50% menores',
      dek: 'En setiembre de 2024 el Gobierno incorporó cobertura para tres cánceres nuevos y actualizó otros diez tratamientos: US$ 23 millones más y unos 700 pacientes por año sin litigar.',
      contexto: 'El 10 de setiembre de 2024 el Gobierno anunció la incorporación al Fondo Nacional de Recursos de nuevos tratamientos oncológicos —Telenoche tituló que fueron 16—: cobertura nueva para los cánceres de cabeza y cuello, ovario y cuello uterino, más ampliaciones o nuevas indicaciones en diez tratamientos ya existentes que, según Montevideo Portal y el MSP, alcanzan trece patologías, entre ellas mama, pulmón, colorrectal, hígado, próstata, riñón y melanoma. El anuncio lo hicieron el ministro interino de Salud Pública José Luis Satdjian, la ministra de Economía y Finanzas Azucena Arbeleche, la directora general del FNR María Ana Porcelli y la directora del Programa Nacional de Control del Cáncer Marisa Fazzino.',
      hallazgo: 'Según Presidencia, la medida implicó un aumento de US$ 23 millones en el primer año del presupuesto del FNR y «una baja del entorno del 50% en los precios» negociados; Telenoche consignó rebajas de hasta 50% en algunos tratamientos y de 25% en los más demandados. El MSP informó que la inversión del FNR en oncológicos pasó de US$ 11 millones en 2020 a US$ 32 millones en 2023 y llegaría a US$ 57 millones con las incorporaciones, y el ministro Satdjian mencionó «una inversión de 25 millones de dólares que ya se destinaban a cubrir los juicios de amparo». Los pacientes tratados pasaron de poco más de 2.310 en 2020 a más de 3.000. Según Telenoche, unas 700 personas por año accederían sin juicio frente a las 450 que lo lograban por amparo, y la cobertura total subiría de unos 3.100 a unos 3.800 pacientes. Montevideo Portal informó que en 2023 el MSP enfrentó 451 juicios de amparo por estos medicamentos y que, según Arbeleche, el Estado destinó US$ 99 millones a juicios por este tema, comprando «a precios que resultan excesivos».',
      statusNote: 'La ministra Arbeleche admitió que cuando se accede mediante recursos de amparo «el proceso no es equitativo, porque lo consiguen quienes pueden hacerlo mediante un reclamo a la Justicia». La oncóloga María Clara Rodríguez dijo a Subrayado, el 11 de setiembre de 2024, que la cobertura «cambia radicalmente muchísimo el acceso» para tumores como los de pulmón y riñón, y advirtió sobre el desafío de mantener actualizado el catálogo ante la velocidad con que avanza la medicina. Pese a la ampliación, la OPS informó que los amparos siguieron creciendo: 2.219 en 2025 y 1.328 sólo en el primer semestre de 2026.',
      porQueImporta: 'Es el caso más claro de que negociar en bloque paga: con dinero que antes se iba en litigios que alcanzaban a unos 450 pacientes, el Estado dice atender a unos 700 sin juicio. Para un paciente significa recibir el tratamiento por indicación médica y no por sentencia, sin costo de abogado ni espera de fallo.',
      caveat: 'La compra centralizada del FNR se negocia con los laboratorios y no necesariamente se tramita como llamado en Compras Estatales; el FNR es una persona pública no estatal. El cruce puede mostrar compras de oncológicos de ASSE y del MSP, pero no el precio negociado por el Fondo. Las cifras de pacientes y de ahorro son proyecciones oficiales del anuncio, no resultados medidos.',
    },
    en: {
      title: 'FNR widened cancer coverage and negotiated prices 50% lower',
      dek: 'In September 2024 the government added coverage for three new cancers and updated ten other treatments: US$23 million more and some 700 patients a year without litigating.',
      contexto: 'On 10 September 2024 the government announced the addition of new cancer treatments to the National Resources Fund —Telenoche\'s headline put the figure at 16—: new coverage for head and neck, ovarian and cervical cancers, plus extensions or new indications in ten existing treatments which, according to Montevideo Portal and the Health Ministry, reach thirteen conditions, including breast, lung, colorectal, liver, prostate, kidney and melanoma. The announcement was made by acting Health Minister José Luis Satdjian, Economy and Finance Minister Azucena Arbeleche, FNR general director María Ana Porcelli and National Cancer Control Programme director Marisa Fazzino.',
      hallazgo: 'According to Presidencia, the measure meant a US$23 million increase in the FNR budget in its first year and "a fall of around 50% in prices" negotiated; Telenoche reported cuts of up to 50% on some treatments and 25% on the most demanded ones. The Health Ministry reported that FNR investment in cancer drugs went from US$11 million in 2020 to US$32 million in 2023 and would reach US$57 million with the additions, and Minister Satdjian mentioned "an investment of 25 million dollars already earmarked to cover amparo lawsuits". Patients treated went from just over 2,310 in 2020 to more than 3,000. According to Telenoche, some 700 people a year would gain access without a lawsuit, against the 450 who got there through injunctions, and total coverage would rise from around 3,100 to around 3,800 patients. Montevideo Portal reported that in 2023 the Health Ministry faced 451 amparo lawsuits over these medicines and that, according to Arbeleche, the State spent US$99 million on litigation over this issue, buying "at prices that turn out to be excessive".',
      statusNote: 'Minister Arbeleche acknowledged that when access comes through amparo actions "the process is not equitable, because those who obtain it are those able to bring a claim before the courts". Oncologist María Clara Rodríguez told Subrayado on 11 September 2024 that the coverage "radically changes access a great deal" for tumours such as lung and kidney, while warning of the challenge of keeping the catalogue current given the speed of medical advances. Despite the expansion, PAHO reported that injunctions kept rising: 2,219 in 2025 and 1,328 in the first half of 2026 alone.',
      porQueImporta: 'This is the clearest case that bulk negotiation pays off: with money previously consumed by litigation that reached some 450 patients, the State says it now serves some 700 without a lawsuit. For a patient it means receiving treatment on medical indication rather than by court order, with no lawyer\'s fee and no wait for a ruling.',
      caveat: 'The FNR\'s centralised purchase is negotiated with laboratories and is not necessarily processed as a tender on Compras Estatales; the FNR is a non-state public entity. Cross-referencing can show cancer-drug purchases by ASSE and the Health Ministry, but not the price the Fund negotiated. The patient and savings figures are official projections from the announcement, not measured results.',
    },
  },
  {
    slug: 'nivolumab-pembrolizumab-cobertura-por-etapas',
    emoji: '🎯',
    theme: 'cancer',
    period: '2019-2024',
    statusKind: 'debate',
    status: 'debate',
    amountReported: '«El costo de ambas medicaciones ronda los 13 mil dólares al mes», según Teledoce en octubre de 2019, citando al diario El País',
    organisms: ['Fondo Nacional de Recursos', 'Ministerio de Salud Pública'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Ministerio de Salud Pública',
      ],
      yearFrom: 2019,
      yearTo: 2024,
    },
    sources: [
      { outlet: 'Teledoce', title: 'FNR anunció la pronta incorporación de dos medicamentos oncológicos que suelen ser los más solicitados en las demandas', url: 'https://www.teledoce.com/telemundo/nacionales/fnr-anuncio-la-pronta-incorporacion-de-dos-medicamentos-oncologicos-que-suelen-ser-los-mas-solicitados-en-las-demandas/', date: '2019-10-04' },
      { outlet: 'Presidencia de la República', title: 'Gobierno anunció financiación de medicamentos contra tres tipos de cáncer', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/gobierno-anuncio-financiacion-medicamentos-contra-tres-tipos-cancer', date: '2024-09-10' },
      { outlet: 'Montevideo Portal', title: 'Fondo Nacional de Recursos incorpora prestación de tratamientos para tres tipos de cáncer', url: 'https://www.montevideo.com.uy/Archivo/Fondo-Nacional-de-Recursos-incorpora-prestacion-de-tratamientos-para-tres-tipos-de-cancer-uc899778', date: '2024-09-10' },
      { outlet: 'Ministerio de Economía y Finanzas', title: '5.8.8 Amparos judiciales por Medicamentos de Alto Precio (MAP) y técnicas — Exposición de Motivos, Rendición de Cuentas 2023', url: 'https://www.gub.uy/ministerio-economia-finanzas/comunicacion/publicaciones/exposicion-motivos-rc-2023/58-salud/588-amparos-judiciales-medicamentos' },
      { outlet: 'OPS/OMS', title: 'Uruguay avanza en la construcción de una hoja de ruta para mejorar el acceso a medicamentos y tratamientos de alto costo con apoyo de OPS', url: 'https://www.paho.org/es/noticias/9-7-2026-uruguay-avanza-construccion-hoja-ruta-para-mejorar-acceso-medicamentos', date: '2026-07-09' },
    ],
    es: {
      title: 'Nivolumab y pembrolizumab: la cobertura que llegó por etapas',
      dek: 'El FNR anunció en 2019 que incorporaría las dos inmunoterapias más reclamadas en juicios, primero sólo para melanoma. La actualización amplia recién llegó cinco años después.',
      contexto: 'Nivolumab y pembrolizumab son dos inmunoterapias usadas en varios tipos de cáncer y, en Uruguay, fueron durante años los fármacos más solicitados en las demandas judiciales, según Teledoce. El 4 de octubre de 2019 ese canal informó —citando al diario El País— que la entonces directora general del Fondo Nacional de Recursos, Alicia Ferreira, anunció durante el foro War on Cancer de América Latina, en Ciudad de México, que Uruguay planeaba incorporar ambos medicamentos: el melanoma sería la primera patología objetivo, con posible expansión posterior al cáncer de pulmón.',
      hallazgo: 'En esa misma nota, Teledoce consignó que «el costo de ambas medicaciones ronda los 13 mil dólares al mes» y que «en los últimos dos años cerca de un centenar de juicios fueron para solicitar esta medicación». Cubrir por etapas —melanoma primero, pulmón después— fue una decisión de política sanitaria: para las indicaciones que quedaban fuera, la puerta siguió siendo el amparo. Recién el 10 de setiembre de 2024 el Gobierno anunció la actualización de los tratamientos del FNR para trece patologías oncológicas, entre ellas pulmón, riñón y melanoma, con una baja del entorno del 50% en los precios, según Presidencia y Montevideo Portal, que incluyó a nivolumab y pembrolizumab entre los fármacos de la lista. En el intervalo, el Ministerio de Economía y Finanzas informó que sólo en 2023 el Estado pagó US$ 99 millones por amparos de medicamentos de alto precio y técnicas.',
      statusNote: 'Con las incorporaciones de setiembre de 2024 el MSP informó que la inversión del FNR en oncológicos llegaría a US$ 57 millones anuales y que unas 700 personas por año accederían sin litigar. Aun así, la Organización Panamericana de la Salud informó en julio de 2026 que las acciones de amparo siguieron subiendo, hasta 2.219 en 2025 y 1.328 en el primer semestre de 2026, y que el MSP convocó una instancia interinstitucional para revisar el mecanismo. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores.',
      porQueImporta: 'Cuando el Estado cubre un fármaco sólo para una indicación, define quién recibe el tratamiento por receta y quién debe conseguirlo por juicio. Con un costo mensual del orden de los US$ 13.000 informado en 2019, esa línea es la diferencia entre un tratamiento gratuito y una demanda judicial que no todos pueden iniciar.',
      caveat: 'Los precios que efectivamente pagó el Estado por estos fármacos no surgen de las fuentes consultadas: el FNR negocia con los laboratorios y las compras por amparo se ejecutan por sentencia. El cruce con datos abiertos puede mostrar compras de oncológicos por ASSE, no el acuerdo del Fondo. La cifra de 2019 es de mercado y anterior a las rebajas negociadas en 2024.',
    },
    en: {
      title: 'Nivolumab and pembrolizumab: coverage that arrived in stages',
      dek: 'In 2019 the FNR announced it would add the two immunotherapies most demanded in lawsuits, at first only for melanoma. The broad update came five years later.',
      contexto: 'Nivolumab and pembrolizumab are two immunotherapies used in several types of cancer and, in Uruguay, were for years the drugs most requested in court claims, according to Teledoce. On 4 October 2019 that channel reported —citing the newspaper El País— that the then general director of the National Resources Fund, Alicia Ferreira, announced at the War on Cancer Latin America forum in Mexico City that Uruguay planned to add both medicines: melanoma would be the first target condition, with possible later expansion to lung cancer.',
      hallazgo: 'In that same report Teledoce noted that "the cost of both medications is around 13 thousand dollars a month" and that "in the last two years close to a hundred lawsuits were filed to request this medication". Covering them in stages —melanoma first, lung later— was a health-policy decision: for the indications left out, the door remained the amparo. Only on 10 September 2024 did the government announce the update of FNR treatments for thirteen cancer conditions, including lung, kidney and melanoma, with a fall of around 50% in prices, according to Presidencia and Montevideo Portal, which listed nivolumab and pembrolizumab among the drugs covered. In the interval, the Ministry of Economy and Finance reported that in 2023 alone the State paid US$99 million on injunctions for high-priced medicines and techniques.',
      statusNote: 'With the September 2024 additions the Health Ministry reported that FNR investment in cancer drugs would reach US$57 million a year and that some 700 people a year would gain access without litigating. Even so, the Pan American Health Organization reported in July 2026 that amparo actions kept rising, to 2,219 in 2025 and 1,328 in the first half of 2026, and that the Ministry convened an inter-institutional session to review the mechanism. As of this file\'s closing date (August 2026) there is nothing further on record.',
      porQueImporta: 'When the State covers a drug for only one indication, it defines who receives treatment on prescription and who must obtain it through a lawsuit. With a monthly cost of the order of US$13,000 reported in 2019, that line is the difference between free treatment and a court claim not everyone can start.',
      caveat: 'The prices the State actually paid for these drugs do not appear in the sources consulted: the FNR negotiates with laboratories and injunction purchases are executed under court order. Open-data cross-referencing can show ASSE cancer-drug purchases, not the Fund\'s agreement. The 2019 figure is a market price and predates the reductions negotiated in 2024.',
    },
  },
  {
    slug: 'inca-acelerador-arrendado-lista-espera',
    emoji: '🏥',
    theme: 'cancer',
    period: '2015-2025',
    statusKind: 'gestion',
    status: 'inconcluso',
    amountReported: '«El arrendamiento tiene un costo mensual próximo a los 20.000 dólares» por el acelerador lineal del INCA, contrato a diez años (Presidencia y Montevideo Portal, 2015)',
    organisms: ['Instituto Nacional del Cáncer', 'Administración de los Servicios de Salud del Estado (ASSE)'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Instituto Nacional del Cáncer',
        'NO VIGENTE Instituto Nacional del Cáncer',
        'Hospital Maciel',
        'Centro Hospitalario Pereira Rossell',
        'Hospital Pasteur',
        'Centro Departamental de Rocha',
        'Centro Departamental de Salto',
        'Centro Auxiliar de Pando',
        'Hospital Español',
        'Centro Auxiliar de Bella Unión',
        'Servicio Nacional de Ortopedia y Traumatología',
        'Centro Departamental de Flores',
        'Centro Hospitalario Maldonado-San Carlos',
        'Centro de Rehabilitación Médico Ocupacional y Sicosocial',
        'Hospital de San Carlos',
        'Centro Departamental de Paysandú',
        'Red de Atención Primaria Area Metropolitana',
        'Laboratorio Químico Industrial Francisco Dorrego',
        'Centro Departamental de Canelones',
        'Administración de Servicios de Salud del Estado',
        'Hospital Dr. Gustavo Saint Bois',
        'Centro Auxiliar de las Piedras',
        'Hospital Vilardebó',
        'Direc.Sistema de Atenciòn Integral Personas Privad. Libertad',
        'Red de Atención Primaria de Rocha',
        'Centro Auxiliar de Río Branco',
        'Red de Atención Primaria de Rivera',
        'Centro Departamental de Maldonado',
        'Centro Departamental de Durazno',
        'Instituto Nal.de Reumatalogía Prof.Dr. Moisés Mizraji',
        'Centro Auxiliar de Young',
        'Red de Atención Primaria de San José',
        'Centro Departamental de Tacuarembó',
        'Centro Departamental de Treinta y Tres',
        'Colonia Siquiátrica Dr. Bernardo Etchepare',
        'Hospital del Cerro',
        'Red de Atención Primaria de Salto',
        'Centro Departamental de San José',
        'Centro Departamental de Lavalleja',
        'Hospital -Centro Geriátrico Dr. Luis Piñeiro del Campo',
        'Centro Departamental de Florida',
        'Hospital Especializado de Ojos',
        'Centro Departamental de Cerro Largo',
        'Centro Auxiliar de San Carlos',
        'Centro Departamental de Rivera',
        'Servicio Nacional de Sangre',
        'Centro Auxiliar Chuy',
        'Red de Atención Primaria de Paysandú',
        'Centro Departamental de Soriano',
        'Red de Atención Primaria de Canelones',
        'Ctro Inf.y Ref.Nal de Red Drogas',
        'Red de Atención Primaria de Cerro Largo',
        'Centro Auxiliar de Guichón',
        'Centro Departamental de Río Negro',
        'Centro Departamental de Salud Pública de Colonia',
        'Red de Atención Primaria de Maldonado',
        'Red de Atención Primaria de Río Negro',
        'Centro Auxiliar de Paso de los Toros',
        'Red de Atención Primaria de Colonia',
        'Red de Atención Primaria de Artigas',
        'Centro Auxiliar de Carmelo',
        'Colonia Dr.Santín Carlos Rossi',
        'NO VIGENTE Centro Auxiliar Ciudad de la Costa',
        'Centro Departamental de Artigas',
        'Red de Atención Primaria de Tacuarembó',
        'Centro Auxiliar de Rosario',
        'Centro Auxiliar de Juan Lacaze',
        'Asistencia Integral',
        'Red de Atención Primaria de Treinta y Tres',
        'Red de Atención Primaria de Florida',
        'Red de Atención Primaria de Soriano',
        'Atencion de Urgencia Emergencia Prehospitalaria y Traslado.',
        'Centro Auxiliar de Dolores',
        'Centro Aux. de Cardona y Florencio Sánchez',
        'Red de Atención Primaria de Lavalleja',
        'Centro Auxiliar de Castillos',
        'Red de Atención Primaria de Flores',
        'Red de Atención Primaria de Durazno',
        'Centro Auxiliar de Nueva Helvecia',
        'Inst.Nal.Don.yTransp.Cél.Tej.Or',
        'Centro Auxiliar de Nueva Palmira',
        'NO VIGENTE - Centro Auxiliar de Nueva Helvecia',
        'NO VIGENTE Centro Auxiliar de Tala',
        'NO VIGENTE Centro Auxiliar Ciudad del Plata',
        'NO VIGENTE Centro Auxiliar de Cerro Chato',
        'NO VIGENTE Centro Auxiliar de San Ramón',
        'NO VIGENTE Centro Auxiliar de Aiguá',
        'Centro Auxiliar de Sarandí del Yi',
      ],
      search: 'acelerador lineal',
      yearFrom: 2015,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'ASSE', title: 'Instituto Nacional del Cáncer inauguró Acelerador Lineal', url: 'https://www.asse.com.uy/contenido/Instituto-Nacional-del-Cancer-inauguro-Acelerador-Lineal-7908', date: '2015-06-22' },
      { outlet: 'Montevideo Portal', title: 'Tecnología de punta en radioterapia lleva a cero la lista de espera', url: 'https://www.montevideo.com.uy/Archivo/Tecnologia-de-punta-en-radioterapia-lleva-a-cero-la-lista-de-espera-uc275292', date: '2015-06-22' },
      { outlet: 'Presidencia de la República', title: 'Uruguay dispone de tecnología de punta en radioterapia que lleva a cero la lista de espera', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/uruguay-dispone-tecnologia-punta-radioterapia-lleva-cero-lista-espera', date: '2015-06-22' },
      { outlet: 'El Observador', title: 'Dos equipos de radioterapia para cáncer estuvieron casi cinco años sin ser usados por ASSE: ¿qué pasó?', url: 'https://www.elobservador.com.uy/nota/dos-equipos-de-radioterapia-para-cancer-estuvieron-casi-cinco-anos-sin-ser-usados-por-asse-que-paso--202371118510', date: '2023-07-12' },
      { outlet: 'El Explorador', title: 'El Instituto Nacional del Cáncer frente a una nueva etapa', url: 'https://elexplorador.com.uy/el-instituto-nacional-del-cancer-frente-a-una-nueva-etapa/', date: '2025-10-23' },
      { outlet: 'Presidencia de la República', title: 'ASSE incorporó equipamiento que incrementa calidad de tratamientos radioterapéuticos', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/asse-incorporo-equipamiento-incrementa-calidad-tratamientos-radioterapeuticos', date: '2023-11-23' },
    ],
    es: {
      title: 'El INCA alquiló un acelerador y se anunció el fin de la lista de espera',
      dek: 'En 2015 ASSE arrendó por diez años el segundo acelerador del país y anunció que ya no habría cola. En 2023 el instituto tenía entre 20 y 25 pacientes en lista de espera.',
      contexto: 'El 22 de junio de 2015 ASSE inauguró en el Instituto Nacional del Cáncer (INCA) el segundo acelerador lineal de radioterapia del país —el primero estaba en el Hospital de Clínicas—, con radioterapia de intensidad modulada y colimadores de 120 láminas. No fue una compra: se adjudicó por licitación pública un arrendamiento a diez años que, según ASSE, incluía mantenimiento preventivo y correctivo «full risk, con repuestos y mano de obra incluidos», puesta a punto tecnológica a los cinco años y una garantía de funcionamiento del 97% del tiempo de uso, con sanciones por incumplimiento. Presidencia y Montevideo Portal informaron que «el arrendamiento tiene un costo mensual próximo a los 20.000 dólares».',
      hallazgo: 'La presidenta del directorio de ASSE, Susana Muñiz, definió el contrato como «una forma innovadora de contratación que, además, sigue las recomendaciones de los organismos internacionales en cuanto a seguridad de energía atómica», y el director del INCA, Álvaro Luongo, señaló que con el equipamiento el país «se iguala a los países del primer mundo». Presidencia tituló que la tecnología «lleva a cero la lista de espera» y Montevideo Portal consignó que, al contar con dos aceleradores, «ASSE asegura que ya no habrá lista de espera para este tipo de tratamientos». Ocho años después, el 12 de julio de 2023, El Observador informó que el INCA mantenía «una lista de espera de entre 20 y 25 personas para recibir este tipo de radioterapia». El 23 de octubre de 2025 el actual director del instituto, Mauricio Cuello, dijo a El Explorador: «Tenemos un porcentaje importante de la plantilla vacante», y describió déficit de especialistas en anatomía patológica y radioterapia, la necesidad de físicos médicos como problema nacional y años de equipamiento quirúrgico sin actualizar.',
      statusNote: 'El 23 de noviembre de 2023 ASSE presentó en el INCA un acelerador lineal propio, con una inversión informada de US$ 1.336.000 para dejarlo operativo, según Presidencia. En octubre de 2025 Cuello informó a El Explorador que había una licitación en curso para incorporar radioterapia de última generación y que el nodo de información mamográfica procesa «entre 1.400 y 1.500 estudios al mes». Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a octubre de 2025 sobre esa licitación.',
      porQueImporta: 'El INCA es el centro oncológico de referencia del sistema público. Que un contrato de diez años se presentara como el fin de las listas de espera y que ocho años después siguiera habiendo cola, con cargos vacantes y falta de físicos médicos, sugiere que el problema no se resuelve sólo comprando o alquilando máquinas.',
      caveat: 'El arrendamiento de 2015 se adjudicó por licitación pública y debería ser rastreable en compras estatales, igual que los mantenimientos posteriores. Las vacantes de cargos y la falta de físicos médicos no se ven en datos de compras: son presupuesto de personal. Las fuentes no permiten reconstruir la evolución de la lista de espera entre 2015 y 2023.',
    },
    en: {
      title: 'INCA leased an accelerator and the end of the waiting list was announced',
      dek: 'In 2015 ASSE leased the country\'s second accelerator for ten years and announced there would be no more queue. In 2023 the institute had 20 to 25 patients waiting.',
      contexto: 'On 22 June 2015 ASSE inaugurated at the National Cancer Institute (INCA) the country\'s second linear accelerator for radiotherapy —the first was at the Hospital de Clínicas— with intensity-modulated radiotherapy and 120-leaf collimators. It was not a purchase: a ten-year lease was awarded through public tender which, according to ASSE, included preventive and corrective maintenance "full risk, with spare parts and labour included", a technological upgrade after five years and a guarantee of operation for 97% of use time, with penalties for non-compliance. Presidencia and Montevideo Portal reported that "the lease has a monthly cost close to 20,000 dollars".',
      hallazgo: 'The president of ASSE\'s board, Susana Muñiz, described the contract as "an innovative form of contracting that also follows the recommendations of international bodies on atomic energy safety", and INCA director Álvaro Luongo said that with the equipment the country "matches first-world countries". Presidencia\'s headline said the technology "brings the waiting list to zero" and Montevideo Portal reported that, with two accelerators, "ASSE assures there will no longer be a waiting list for this type of treatment". Eight years later, on 12 July 2023, El Observador reported that INCA maintained "a waiting list of between 20 and 25 people to receive this type of radiotherapy". On 23 October 2025 the institute\'s current director, Mauricio Cuello, told El Explorador: "We have a significant share of vacant posts", and described a deficit of specialists in pathology and radiotherapy, the need for medical physicists as a national problem, and years of surgical equipment left un-updated.',
      statusNote: 'On 23 November 2023 ASSE presented an owned linear accelerator at INCA, with a reported investment of US$1,336,000 to make it operational, according to Presidencia. In October 2025 Cuello told El Explorador there was a tender under way to add latest-generation radiotherapy and that the mammography information node processes "between 1,400 and 1,500 studies a month". As of this file\'s closing date (August 2026) there is nothing on record after October 2025 about that tender.',
      porQueImporta: 'INCA is the public system\'s reference cancer centre. That a ten-year contract was presented as the end of waiting lists and that eight years later there was still a queue, with vacant posts and a shortage of medical physicists, suggests the problem is not solved by buying or leasing machines alone.',
      caveat: 'The 2015 lease was awarded through public tender and should be traceable in state procurement data, as should the later maintenance contracts. Vacant posts and the shortage of medical physicists do not show up in procurement data: they are staffing budget. The sources do not allow the waiting list to be reconstructed between 2015 and 2023.',
    },
  },
  {
    slug: 'comision-honoraria-cancer-mamografos',
    emoji: '🎗️',
    theme: 'cancer',
    period: '2018-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'US$ 16 millones invertidos en mamógrafos y capacitación de recursos humanos, cifra acumulada informada en noviembre de 2018',
    organisms: ['Comisión Honoraria de Lucha contra el Cáncer', 'Ministerio de Salud Pública'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Ministerio de Salud Pública',
      ],
      yearFrom: 2018,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Presidencia de la República', title: 'Comisión de Lucha contra el Cáncer invirtió 16 millones de dólares en mamógrafos y capacitación', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/comision-lucha-contra-cancer-invirtio-16-millones-dolares-mamografos', date: '2018-11-12' },
      { outlet: 'Ministerio de Salud Pública', title: 'Comisión Honoraria de Lucha contra el Cáncer — Compromisos de gestión institucionales', url: 'https://www.gub.uy/ministerio-salud-publica/institucional/informacion-gestion/compromisos-gestion-institucionales/comision-honoraria-lucha' },
      { outlet: 'En Perspectiva', title: 'Informe de evaluación de las capacidades y necesidades de control del cáncer (misión imPACT: OIEA, OPS/OMS y CIIC), presentado al Ministerio de Salud Pública', url: 'https://enperspectiva.uy/wp-content/uploads/2025/02/informe-IMPACT.pdf', date: '2022-09' },
      { outlet: 'Comisión Honoraria de Lucha contra el Cáncer', title: 'Comisión Honoraria de Lucha contra el Cáncer — sitio institucional', url: 'https://www.comisioncancer.org.uy/home' },
    ],
    es: {
      title: 'La Comisión del Cáncer y los US$ 16 millones en mamógrafos',
      dek: 'Creada por ley y financiada con fondos públicos, compra equipamiento y custodia el registro de cáncer. El propio MSP le pidió demostrar eficacia, eficiencia y resultados.',
      contexto: 'La Comisión Honoraria de Lucha contra el Cáncer fue creada por la Ley N° 16.097: recibe fondos públicos, compra equipamiento y capacita personal, y rinde cuentas ante el Ministerio de Salud Pública. Además de sus campañas, gestiona el Registro Nacional de Cáncer —del que surge el VII Atlas de Mortalidad por Cáncer en el Uruguay 2019-2023— y la Historia Clínica Electrónica Oncológica. Es decir: es a la vez compradora de tecnología de diagnóstico y custodia de la estadística oficial con la que se mide el problema.',
      hallazgo: 'El 12 de noviembre de 2018, en el acto por el 30º aniversario de la Comisión, Presidencia informó que el organismo había invertido 16 millones de dólares en mamógrafos y en capacitación de recursos humanos. Su entonces presidente, Álvaro Luongo, señaló que «hace 30 años había tres o cuatro mamógrafos» y que tras la inversión los equipos se multiplicaron en todo el país. En el mismo acto, el ministro de Salud Pública Jorge Basso subrayó que, por tratarse de dineros públicos, la Comisión debe «transparentarlo, demostrar eficacia, eficiencia y resultados», y mencionó un presupuesto anual de más de 2,5 millones de dólares del que debe rendir cuentas. Ninguna de las fuentes consultadas precisa cuántos mamógrafos se compraron con esos 16 millones, a qué proveedores ni por qué mecanismo de contratación. La evaluación internacional imPACT presentada al MSP en 2022 aportó un dato sobre la calidad de ese parque instalado: «Los servicios de mamografía no se someten a procesos de garantía de la calidad», y recomendó implantar programas de control de calidad en las mamografías bajo supervisión de profesionales de física médica.',
      statusNote: 'Los compromisos de gestión institucionales fueron creados por el artículo 752 de la Ley N° 18.719, de 27 de diciembre de 2010, para organismos que perciban subsidios o subvenciones con cargo al Presupuesto Nacional superiores a $ 20.000.000. Según la ficha institucional del MSP, en 2025 el Ministerio suscribió compromisos de gestión con seis instituciones, entre ellas la Comisión Honoraria de Lucha contra el Cáncer, y publica el documento correspondiente. Al cierre de esta ficha (agosto de 2026) no constan, en las fuentes consultadas, observaciones públicas sobre estas compras.',
      porQueImporta: 'Los mamógrafos determinan cuántas mujeres pueden hacerse a tiempo el estudio que detecta el cáncer de mama, y en qué departamento. Saber cuánto costó cada equipo, quién lo vendió, dónde quedó instalado y bajo qué control de calidad opera es la diferencia entre una campaña de octubre y una política verificable.',
      caveat: 'La cifra de US$ 16 millones es acumulada y no está desagregada por año ni por equipo en las fuentes; corresponde a lo informado en 2018 y no a un gasto anual. Parte de las compras de la Comisión puede tramitarse fuera del régimen general y no aparecer en el buscador de compras estatales.',
    },
    en: {
      title: 'The Cancer Commission and the US$16 million in mammographs',
      dek: 'Created by law and funded with public money, it buys equipment and keeps the cancer registry. The Health Ministry itself asked it to demonstrate efficacy, efficiency and results.',
      contexto: 'The Honorary Commission for the Fight Against Cancer was created by Law No. 16,097: it receives public funds, buys equipment and trains staff, and reports to the Ministry of Public Health. Beyond its campaigns, it runs the National Cancer Registry —source of the 7th Atlas of Cancer Mortality in Uruguay 2019-2023— and the Oncological Electronic Medical Record. In other words: it is at once a buyer of diagnostic technology and the custodian of the official statistics used to measure the problem.',
      hallazgo: 'On 12 November 2018, at the event marking the Commission\'s 30th anniversary, Presidencia reported that the body had invested 16 million dollars in mammographs and in staff training. Its then president, Álvaro Luongo, said that "thirty years ago there were three or four mammographs" and that after the investment the equipment multiplied across the country. At the same event, Health Minister Jorge Basso stressed that, as public money is involved, the Commission must "make it transparent, demonstrate efficacy, efficiency and results", and mentioned an annual budget of more than 2.5 million dollars for which it must account. None of the sources consulted specifies how many mammographs were bought with those 16 million, from which suppliers, or through what contracting mechanism. The international imPACT assessment presented to the Health Ministry in 2022 added a finding on the quality of that installed base: "Mammography services are not subject to quality assurance processes", and it recommended implementing quality-control programmes for mammography under the supervision of medical physics professionals.',
      statusNote: 'Institutional management agreements were created by article 752 of Law No. 18,719 of 27 December 2010, for bodies receiving subsidies or grants from the National Budget above $20,000,000 pesos. According to the Health Ministry\'s institutional page, in 2025 the Ministry signed management agreements with six institutions, among them the Honorary Commission for the Fight Against Cancer, and publishes the corresponding document. As of this file\'s closing date (August 2026), the sources consulted record no public observations about these purchases.',
      porQueImporta: 'Mammographs determine how many women can get, in time, the test that detects breast cancer, and in which department of the country. Knowing what each machine cost, who sold it, where it was installed and under what quality control it operates is the difference between an October campaign and a verifiable policy.',
      caveat: 'The US$16 million figure is cumulative and is not broken down by year or by machine in the sources; it corresponds to what was reported in 2018, not to annual spending. Part of the Commission\'s purchasing may be processed outside the general regime and may not appear in the state procurement search.',
    },
  },
  {
    slug: 'tamizaje-cancer-mama-prestaciones-estado',
    emoji: '🩷',
    theme: 'cancer',
    period: '2022-2025',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    organisms: ['Ministerio de Salud Pública', 'Fondo Nacional de Recursos', 'Administración de los Servicios de Salud del Estado (ASSE)'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Ministerio de Salud Pública',
        'Hospital Maciel',
        'Centro Hospitalario Pereira Rossell',
        'Hospital Pasteur',
        'Centro Departamental de Rocha',
        'Centro Departamental de Salto',
        'Centro Auxiliar de Pando',
        'Hospital Español',
        'Centro Auxiliar de Bella Unión',
        'Servicio Nacional de Ortopedia y Traumatología',
        'Centro Departamental de Flores',
        'Centro Hospitalario Maldonado-San Carlos',
        'Centro de Rehabilitación Médico Ocupacional y Sicosocial',
        'Hospital de San Carlos',
        'Centro Departamental de Paysandú',
        'Red de Atención Primaria Area Metropolitana',
        'Laboratorio Químico Industrial Francisco Dorrego',
        'Centro Departamental de Canelones',
        'Administración de Servicios de Salud del Estado',
        'Hospital Dr. Gustavo Saint Bois',
        'Centro Auxiliar de las Piedras',
        'Hospital Vilardebó',
        'Direc.Sistema de Atenciòn Integral Personas Privad. Libertad',
        'Red de Atención Primaria de Rocha',
        'Centro Auxiliar de Río Branco',
        'Red de Atención Primaria de Rivera',
        'Instituto Nacional del Cáncer',
        'Centro Departamental de Maldonado',
        'Centro Departamental de Durazno',
        'Instituto Nal.de Reumatalogía Prof.Dr. Moisés Mizraji',
        'Centro Auxiliar de Young',
        'Red de Atención Primaria de San José',
        'Centro Departamental de Tacuarembó',
        'Centro Departamental de Treinta y Tres',
        'Colonia Siquiátrica Dr. Bernardo Etchepare',
        'Hospital del Cerro',
        'Red de Atención Primaria de Salto',
        'Centro Departamental de San José',
        'Centro Departamental de Lavalleja',
        'Hospital -Centro Geriátrico Dr. Luis Piñeiro del Campo',
        'Centro Departamental de Florida',
        'Hospital Especializado de Ojos',
        'Centro Departamental de Cerro Largo',
        'Centro Auxiliar de San Carlos',
        'Centro Departamental de Rivera',
        'Servicio Nacional de Sangre',
        'Centro Auxiliar Chuy',
        'Red de Atención Primaria de Paysandú',
        'Centro Departamental de Soriano',
        'Red de Atención Primaria de Canelones',
        'Ctro Inf.y Ref.Nal de Red Drogas',
        'Red de Atención Primaria de Cerro Largo',
        'Centro Auxiliar de Guichón',
        'Centro Departamental de Río Negro',
        'Centro Departamental de Salud Pública de Colonia',
        'Red de Atención Primaria de Maldonado',
        'Red de Atención Primaria de Río Negro',
        'Centro Auxiliar de Paso de los Toros',
        'Red de Atención Primaria de Colonia',
        'Red de Atención Primaria de Artigas',
        'Centro Auxiliar de Carmelo',
        'Colonia Dr.Santín Carlos Rossi',
        'NO VIGENTE Centro Auxiliar Ciudad de la Costa',
        'Centro Departamental de Artigas',
        'Red de Atención Primaria de Tacuarembó',
        'Centro Auxiliar de Rosario',
        'Centro Auxiliar de Juan Lacaze',
        'Asistencia Integral',
        'Red de Atención Primaria de Treinta y Tres',
        'Red de Atención Primaria de Florida',
        'Red de Atención Primaria de Soriano',
        'Atencion de Urgencia Emergencia Prehospitalaria y Traslado.',
        'Centro Auxiliar de Dolores',
        'Centro Aux. de Cardona y Florencio Sánchez',
        'Red de Atención Primaria de Lavalleja',
        'Centro Auxiliar de Castillos',
        'Red de Atención Primaria de Flores',
        'Red de Atención Primaria de Durazno',
        'Centro Auxiliar de Nueva Helvecia',
        'Inst.Nal.Don.yTransp.Cél.Tej.Or',
        'Centro Auxiliar de Nueva Palmira',
        'NO VIGENTE - Centro Auxiliar de Nueva Helvecia',
        'NO VIGENTE Centro Auxiliar de Tala',
        'NO VIGENTE Centro Auxiliar Ciudad del Plata',
        'NO VIGENTE Centro Auxiliar de Cerro Chato',
        'NO VIGENTE Centro Auxiliar de San Ramón',
        'NO VIGENTE Centro Auxiliar de Aiguá',
        'Centro Auxiliar de Sarandí del Yi',
      ],
      search: 'resonancia',
      yearFrom: 2022,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'Ministerio de Salud Pública', title: 'Datos importantes sobre el cáncer de mama — Día Mundial de Lucha contra el Cáncer de Mama 2024', url: 'https://www.gub.uy/ministerio-salud-publica/comunicacion/noticias/dia-mundial-de-lucha-contra-cancer-mama-2024', date: '2024-10-18' },
      { outlet: 'El Observador', title: 'Uruguay y la lucha contra el cáncer de mama: cifras y herramientas para pacientes', url: 'https://www.elobservador.com.uy/nacional/uruguay-y-la-lucha-contra-el-cancer-mama-cifras-y-herramientas-pacientes-n5966243', date: '2024-10-19' },
      { outlet: 'Presidencia de la República', title: 'Pacientes con alto riesgo de padecer cáncer de mama accederán a resonancia para diagnóstico', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/pacientes-alto-riesgo-padecer-cancer-mama-accederan-resonancia-para', date: '2023-10-19' },
      { outlet: 'Academia Nacional de Medicina', title: 'Mes del cáncer de mama: acciones y avances en Uruguay', url: 'https://anm.org.uy/mes-del-cancer-de-mama-acciones-y-avances-en-uruguay/', date: '2025-10-25' },
      { outlet: 'En Perspectiva', title: 'Informe de evaluación de las capacidades y necesidades de control del cáncer (misión imPACT: OIEA, OPS/OMS y CIIC), presentado al Ministerio de Salud Pública', url: 'https://enperspectiva.uy/wp-content/uploads/2025/02/informe-IMPACT.pdf', date: '2022-09' },
    ],
    es: {
      title: 'Cáncer de mama: 2.000 casos y 700 muertes por año en Uruguay',
      dek: 'El Estado sumó resonancia, prótesis y cuatro fármacos entre 2022 y 2024. La Academia Nacional de Medicina advierte que crecen los casos en menores de 50 años.',
      contexto: 'El cáncer de mama es el tipo de cáncer más frecuente en las mujeres uruguayas, según la evaluación imPACT presentada al MSP. El Ministerio de Salud Pública informó en octubre de 2024 que se diagnostican alrededor de 2.000 casos nuevos por año —cinco por día— y que mueren unas 700 mujeres al año, dos por día; una de cada once mujeres podría desarrollarlo. El 78% de los casos se diagnostica después de los 50 años y el 17% entre los 40 y los 49. El tamizaje recomendado es una mamografía cada dos años entre los 50 y los 69 años, con exoneración de la tasa moderadora en esa franja y un día de licencia especial remunerada para realizarse el estudio.',
      hallazgo: 'Entre 2022 y 2024 el Estado incorporó varias prestaciones. El Decreto 236/022, de julio de 2022, cubrió las prótesis mamarias sin costo; la Ordenanza 932 sumó la linfocentellografía para el estudio del ganglio centinela; y desde enero de 2024 rige la resonancia magnética mamaria gratuita para mujeres de alto riesgo —«alteraciones genéticas, con mamas densas o que haya recibido radioterapia previa en el tórax»—, anunciada el 19 de octubre de 2023 por la entonces ministra Karina Rando y la directora del Programa Nacional de Control del Cáncer, Marisa Fazzino, con alcance a usuarias de ASSE, Sanidad Policial y Militar y la mayoría de los prestadores privados. El Observador consignó además que el FNR incorporó ribociclib en 2022 y que en 2023 se sumaron trastuzumab y pertuzumab en fase prequirúrgica y TDM-1 en la posquirúrgica. Más del 50% de las mujeres se diagnostica en estadios I y II y alrededor del 9% cuando el cáncer ya está avanzado o metastásico. La evaluación imPACT, en paralelo, señaló que la mamografía «se ofrece de forma oportunista» y que «los servicios de mamografía no se someten a procesos de garantía de la calidad».',
      statusNote: 'El 25 de octubre de 2025 la Academia Nacional de Medicina advirtió que «una preocupación actual en nuestro país es el aumento de casos de cáncer de mama en mujeres menores de 50 años», la franja que queda fuera del tamizaje sistemático, y señaló que la cobertura del test de VPH —prueba central para el cáncer de cuello uterino— «es del 70% de las mujeres, con el objetivo de alcanzar el 90%». Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a octubre de 2025 sobre cambios en el esquema de tamizaje.',
      porQueImporta: 'Que el tamizaje sistemático empiece a los 50 y que el 17% de los casos aparezca entre los 40 y los 49 define quién se detecta a tiempo y quién no. Cada prestación que entra a la cobertura —una resonancia, una prótesis, un fármaco— deja de pagarse del bolsillo o de reclamarse en un juicio.',
      caveat: 'El cruce con datos abiertos puede mostrar compras de mamógrafos, insumos y servicios de imagenología por ASSE y otros organismos, pero no la cobertura del tamizaje ni los fármacos que financia el FNR, que se negocian por fuera del régimen general de compras estatales. Las constataciones sobre control de calidad corresponden a la evaluación de 2022 y las fuentes no informan si fueron corregidas.',
    },
    en: {
      title: 'Breast cancer: 2,000 cases and 700 deaths a year in Uruguay',
      dek: 'The State added MRI, prostheses and four drugs between 2022 and 2024. The National Academy of Medicine warns that cases are rising among women under 50.',
      contexto: 'Breast cancer is the most frequent type of cancer among Uruguayan women, according to the imPACT assessment presented to the Health Ministry. The Ministry reported in October 2024 that around 2,000 new cases are diagnosed each year —five a day— and that some 700 women die annually, two a day; one in eleven women could develop it. Some 78% of cases are diagnosed after age 50 and 17% between 40 and 49. The recommended screening is a mammogram every two years between ages 50 and 69, with the co-payment waived in that bracket and one day of special paid leave to have the test.',
      hallazgo: 'Between 2022 and 2024 the State added several benefits. Decree 236/022, of July 2022, covered breast prostheses at no cost; Ordinance 932 added lymphoscintigraphy for sentinel node study; and since January 2024 free breast MRI applies to high-risk women —"genetic alterations, dense breasts, or who have received prior chest radiotherapy"— announced on 19 October 2023 by then Minister Karina Rando and National Cancer Control Programme director Marisa Fazzino, covering users of ASSE, Police and Military Health and most private providers. El Observador also reported that the FNR added ribociclib in 2022 and that in 2023 trastuzumab and pertuzumab were added in the pre-surgical phase and TDM-1 in the post-surgical phase. More than 50% of women are diagnosed at stages I and II and around 9% when the cancer is already advanced or metastatic. The imPACT assessment, in parallel, noted that mammography "is offered opportunistically" and that "mammography services are not subject to quality assurance processes".',
      statusNote: 'On 25 October 2025 the National Academy of Medicine warned that "a current concern in our country is the rise in breast cancer cases among women under 50", the bracket outside systematic screening, and noted that HPV test coverage —the central test for cervical cancer— "is 70% of women, with the objective of reaching 90%". As of this file\'s closing date (August 2026) there is nothing on record after October 2025 about changes to the screening scheme.',
      porQueImporta: 'That systematic screening starts at 50 while 17% of cases appear between 40 and 49 defines who is detected in time and who is not. Every benefit that enters coverage —an MRI, a prosthesis, a drug— stops being paid out of pocket or claimed through a lawsuit.',
      caveat: 'Open-data cross-referencing can show purchases of mammographs, supplies and imaging services by ASSE and other bodies, but not screening coverage or the drugs financed by the FNR, which are negotiated outside the general state procurement regime. The quality-control findings correspond to the 2022 assessment and the sources do not report whether they were corrected.',
    },
  },
  {
    slug: 'pet-ct-cudim-unico-centro-pais',
    emoji: '🧲',
    theme: 'cancer',
    period: '2010-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    organisms: ['Fondo Nacional de Recursos'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'Fondo Nacional de Recursos', title: 'Procedimiento financiado PET-SCAN', url: 'https://www.fnr.gub.uy/procedimiento-financiado-pet-scan/' },
      { outlet: 'Montevideo Portal', title: 'Cudim incrementó un 80% los estudios PET-CT en la última década', url: 'https://www.montevideo.com.uy/Archivo/Cudim-incremento-un-80-los-estudios-PET-CT-en-la-ultima-decada-uc952006', date: '2026-02-03' },
      { outlet: 'IMPO — Revista Importa que lo sepas', title: 'CUDIM: el Centro Uruguayo de Imagenología Molecular', url: 'https://www.impo.com.uy/revista/cudim/' },
    ],
    es: {
      title: 'Todo el PET-CT del país se hace en un solo centro',
      dek: 'El FNR financia el estudio que decide si un tratamiento oncológico sigue o cambia, pero sólo hay un centro que lo realiza en Uruguay: el CUDIM, con más de 7.000 estudios al año.',
      contexto: 'El PET-CT permite ver la actividad metabólica de un tumor y ayuda a decidir si un tratamiento continúa, cambia o se suspende. El Fondo Nacional de Recursos lo financia para pacientes oncológicos cuyo estado general permita tolerar el tratamiento específico y con expectativa de vida mayor a 3 meses, y también en epilepsia refractaria y síndrome febril prolongado, con plazos definidos: 4 semanas de terminada la quimioterapia, 12 semanas de la última sesión de radioterapia y 8 semanas de un procedimiento quirúrgico en el sitio a estudiar. El propio FNR establece que «el PET se realiza en el único centro existente en nuestro país que es el Centro Uruguayo de Imagenología Molecular (CUDIM)».',
      hallazgo: 'Montevideo Portal informó el 3 de febrero de 2026 que «la cantidad de estudios PET-CT aumentó un 80%, al pasar de unos 4.000 procedimientos en 2015 a más de 7.000 en la actualidad», la mayoría vinculados a patologías oncológicas, y que «los estudios oncológicos contemplados dentro de la cobertura del Fondo Nacional de Recursos (FNR) se realizan sin costo ni para los pacientes ni para las instituciones». La revista de IMPO consigna que el CUDIM realizó el primer estudio PET/CT del país en junio de 2010, que acumula más de 16.000 estudios, que allí trabajan cerca de 70 personas entre médicos, químicos, técnicos y personal administrativo y de servicios, y que «un convenio entre CUDIM y el Fondo Nacional de Recursos (FNR) permite que la casi totalidad de los estudios sean gratuitos para el paciente». Es decir: toda la capacidad nacional de una técnica diagnóstica financiada con fondos públicos se concentra en un único prestador, vinculado al Fondo por un convenio.',
      statusNote: 'El esquema sigue vigente: el FNR mantiene publicada la normativa del procedimiento financiado y la referencia al CUDIM como único centro del país, y Montevideo Portal informó en febrero de 2026 el crecimiento sostenido de la demanda. Al cierre de esta ficha (agosto de 2026) no constan, en las fuentes consultadas, novedades posteriores a febrero de 2026 ni anuncios de habilitación de un segundo centro PET-CT. Ninguna de las fuentes consultadas plantea observaciones sobre el desempeño del centro.',
      porQueImporta: 'Si el único centro del país se detiene o se satura, no hay adónde derivar: el PET-CT ayuda a definir si un tratamiento oncológico sigue, cambia o se suspende. Que el estudio sea gratuito para el paciente no elimina la pregunta de cuánto paga el Estado por cada uno y bajo qué convenio.',
      caveat: 'El financiamiento del PET-CT se canaliza por un convenio entre el FNR —persona pública no estatal— y el CUDIM, no por un llamado abierto, por lo que difícilmente aparezca en el buscador de compras estatales. Las fuentes consultadas no informan el precio por estudio que paga el Fondo. La cifra de «más de 16.000 estudios» de IMPO es acumulada y su página no está fechada.',
    },
    en: {
      title: 'All of the country\'s PET-CT is done at a single centre',
      dek: 'The FNR funds the scan that helps decide whether a cancer treatment continues or changes, but only one centre performs it in Uruguay: CUDIM, with more than 7,000 scans a year.',
      contexto: 'PET-CT shows a tumour\'s metabolic activity and helps determine whether a treatment continues, changes or stops. The National Resources Fund finances it for cancer patients whose general condition allows them to tolerate the specific treatment and with a life expectancy over 3 months, and also in refractory epilepsy and prolonged fever syndrome, with set intervals: 4 weeks after chemotherapy ends, 12 weeks from the last radiotherapy session and 8 weeks from a surgical procedure at the site to be studied. The Fund itself states that "PET is performed at the only existing centre in our country, the Uruguayan Centre for Molecular Imaging (CUDIM)".',
      hallazgo: 'Montevideo Portal reported on 3 February 2026 that "the number of PET-CT scans rose 80%, going from some 4,000 procedures in 2015 to more than 7,000 today", most linked to cancer conditions, and that "cancer scans covered by the National Resources Fund (FNR) are performed at no cost to patients or institutions". IMPO\'s magazine notes that CUDIM performed the country\'s first PET/CT scan in June 2010, that it has accumulated more than 16,000 studies, that close to 70 people work there among physicians, chemists, technicians and administrative and service staff, and that "an agreement between CUDIM and the National Resources Fund (FNR) makes almost all studies free for the patient". In short: the entire national capacity for a publicly funded diagnostic technique is concentrated in a single provider, tied to the Fund by an agreement.',
      statusNote: 'The arrangement remains in force: the FNR keeps published the rules for the financed procedure and the reference to CUDIM as the country\'s only centre, and Montevideo Portal reported in February 2026 the sustained growth in demand. As of this file\'s closing date (August 2026), the sources consulted record nothing after February 2026 and no announcement of a second PET-CT centre. None of the sources consulted raises any observation about the centre\'s performance.',
      porQueImporta: 'If the country\'s only centre halts or saturates, there is nowhere to refer patients: PET-CT helps define whether a cancer treatment continues, changes or stops. That the scan is free for the patient does not remove the question of how much the State pays for each one, and under what agreement.',
      caveat: 'PET-CT funding is channelled through an agreement between the FNR —a non-state public entity— and CUDIM, not through an open tender, so it is unlikely to appear in the state procurement search. The sources consulted do not report the per-scan price the Fund pays. IMPO\'s "more than 16,000 studies" figure is cumulative and its page is undated.',
    },
  },
  {
    slug: 'registro-cancer-mision-impact-oiea',
    emoji: '📊',
    theme: 'cancer',
    period: '2020-2026',
    statusKind: 'auditoria',
    status: 'auditoria',
    organisms: ['Ministerio de Salud Pública', 'Comisión Honoraria de Lucha contra el Cáncer'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Ministerio de Salud Pública',
      ],
      yearFrom: 2020,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'En Perspectiva', title: 'Informe de evaluación de las capacidades y necesidades de control del cáncer (misión imPACT: OIEA, OPS/OMS y CIIC), presentado al Ministerio de Salud Pública', url: 'https://enperspectiva.uy/wp-content/uploads/2025/02/informe-IMPACT.pdf', date: '2022-09' },
      { outlet: 'Ministerio de Industria, Energía y Minería', title: 'Misión imPACT para evaluar las capacidades y necesidades del control integral del cáncer en Uruguay', url: 'https://www.gub.uy/ministerio-industria-energia-mineria/comunicacion/noticias/mision-impact-para-evaluar-capacidades-necesidades-del-control-integral-del', date: '2021-08-11' },
      { outlet: 'Ministerio de Salud Pública', title: 'Uruguay implementó en cinco años historia clínica electrónica y registro de datos de prestadores para combatir el cáncer', url: 'https://www.gub.uy/ministerio-salud-publica/comunicacion/noticias/uruguay-implemento-cinco-anos-historia-clinica-electronica-registro-datos', date: '2020-02-07' },
      { outlet: 'Comisión Honoraria de Lucha contra el Cáncer', title: 'Comisión Honoraria de Lucha contra el Cáncer — Registro Nacional de Cáncer', url: 'https://www.comisioncancer.org.uy/home' },
    ],
    es: {
      title: 'La evaluación internacional del control del cáncer que Uruguay pidió',
      dek: 'A pedido del MSP, expertos del OIEA, la OPS/OMS y el CIIC recorrieron el sistema oncológico en diciembre de 2021. El informe está en línea y su seguimiento no es público.',
      contexto: 'La misión imPACT es el instrumento de evaluación integral del control del cáncer que el Organismo Internacional de Energía Atómica (OIEA) desarrolla junto con la Organización Panamericana de la Salud, la Organización Mundial de la Salud y el Centro Internacional de Investigaciones sobre el Cáncer (CIIC). Evalúa las capacidades nacionales en planificación, registro, prevención, detección precoz, diagnóstico, tratamiento y cuidados paliativos, y también la infraestructura reguladora de seguridad radiológica. El 11 de agosto de 2021 el Ministerio de Industria, Energía y Minería informó que, mediante nota verbal del director general del OIEA, Rafael Mariano Grossi, se confirmó la misión, solicitada por el ministro de Salud Pública; el punto focal designado fue la doctora Marisa Fazzino, directora del Programa Nacional de Control del Cáncer, y el informe se dirigiría al entonces ministro Daniel Salinas.',
      hallazgo: 'Según el propio informe, tras un análisis en formato virtual la misión técnica en el país se desarrolló en Montevideo del 6 al 10 de diciembre de 2021, con visitas al INCA, al Hospital Pereira Rossell, al Hospital Pediátrico, al FNR y a prestadores privados. El documento fue presentado al Ministerio de Salud Pública en setiembre de 2022 y actualizado en febrero de 2023 con ajustes del propio Ministerio. Entre sus recomendaciones prioritarias figuran elaborar y coordinar un plan nacional de prevención y control del cáncer «a fin de optimizar los esfuerzos y fomentar la transparencia y la rendición de cuentas»; reforzar las funciones reguladoras del MSP para controlar de forma independiente la calidad de los servicios, «por ejemplo, en relación con los tiempos de espera, los retrasos en materia de anatomía patológica y el tratamiento oportuno»; «revisar la asignación de recursos para medicamentos oncológicos de alto costo, de manera que sea coherente con los medicamentos más recetados»; y «asignar los recursos necesarios para garantizar el funcionamiento de los equipos de aceleradores lineales (LINAC) y braquiterapia en los prestadores públicos del sistema sanitario comprando repuestos y garantizando el mantenimiento y la asistencia técnica para que los servicios se presten de forma ininterrumpida». Sobre el registro, el informe destaca que el Registro Nacional de Cáncer es de base poblacional, cubre todo el país y tiene personal permanente y calificado, pero que la transición a un formato electrónico «plantea el desafío más importante» y exigirá más recursos financieros.',
      statusNote: 'El registro descansa en dos piezas: la Historia Clínica Electrónica Oncológica —el MSP informó el 7 de febrero de 2020, por boca de la responsable de su programa de control del cáncer, Lucía Delgado, que en cinco años se desarrolló y se completó su implantación en todos los prestadores integrales del país— y el Registro Nacional de Cáncer, que gestiona la Comisión Honoraria de Lucha contra el Cáncer y del que surge el VII Atlas de Mortalidad por Cáncer en el Uruguay 2019-2023. El informe de la evaluación está disponible en línea, alojado en el sitio del programa En Perspectiva. Las fuentes oficiales consultadas para esta ficha no detallan cuáles de sus recomendaciones se implementaron ni constan comunicaciones oficiales posteriores sobre el seguimiento de la misión.',
      porQueImporta: 'Sin registro no hay política: la decisión de comprar un acelerador, contratar oncólogos o cubrir un fármaco se toma sobre esos datos. Existe una evaluación internacional ya realizada, con recomendaciones concretas sobre mantenimiento de aceleradores, tiempos de espera y asignación de recursos para medicamentos de alto costo; que su seguimiento no sea público le quita al contribuyente la posibilidad de saber si se corrigió lo que se detectó.',
      caveat: 'Ni el registro de cáncer ni la evaluación internacional son compras: no dejan rastro en el buscador de compras estatales. Sí pueden aparecer los sistemas informáticos y los servicios de soporte contratados para sostener la historia clínica oncológica. El informe describe la situación relevada en 2021-2022 y puede haber cambiado.',
    },
    en: {
      title: 'The international review of cancer control that Uruguay requested',
      dek: 'At the Health Ministry\'s request, experts from the IAEA, PAHO/WHO and IARC toured the cancer system in December 2021. The report is online and its follow-up is not public.',
      contexto: 'The imPACT mission is the comprehensive cancer-control assessment instrument that the International Atomic Energy Agency (IAEA) runs together with the Pan American Health Organization, the World Health Organization and the International Agency for Research on Cancer (IARC). It evaluates national capacities in planning, registration, prevention, early detection, diagnosis, treatment and palliative care, as well as the regulatory infrastructure for radiation safety. On 11 August 2021 the Ministry of Industry, Energy and Mining reported that, through a note verbale from IAEA director general Rafael Mariano Grossi, the mission was confirmed at the request of the Minister of Public Health; the designated focal point was Dr Marisa Fazzino, director of the National Cancer Control Programme, and the report would be addressed to then Minister Daniel Salinas.',
      hallazgo: 'According to the report itself, after a virtual analysis the in-country technical mission took place in Montevideo from 6 to 10 December 2021, with visits to INCA, the Pereira Rossell Hospital, the Paediatric Hospital, the FNR and private providers. The document was presented to the Ministry of Public Health in September 2022 and updated in February 2023 with adjustments by the Ministry itself. Its priority recommendations include drawing up and coordinating a national cancer prevention and control plan "in order to optimise efforts and promote transparency and accountability"; strengthening the Ministry\'s regulatory functions to independently monitor service quality, "for example, in relation to waiting times, delays in pathology and timely treatment"; "reviewing the allocation of resources for high-cost cancer medicines so that it is consistent with the most prescribed medicines"; and "allocating the resources needed to guarantee the operation of linear accelerator (LINAC) and brachytherapy equipment in the health system\'s public providers by buying spare parts and guaranteeing maintenance and technical assistance so that services are delivered without interruption". On registration, the report highlights that the National Cancer Registry is population-based, covers the whole country and has permanent, qualified staff, but that the transition to an electronic format "poses the most important challenge" and will require more financial resources.',
      statusNote: 'Registration rests on two pieces: the Oncological Electronic Medical Record —the Health Ministry reported on 7 February 2020, through the head of its cancer control programme, Lucía Delgado, that in five years it was developed and its rollout completed across every comprehensive provider in the country— and the National Cancer Registry, run by the Honorary Commission for the Fight Against Cancer and the source of the 7th Atlas of Cancer Mortality in Uruguay 2019-2023. The assessment report is available online, hosted on the site of the En Perspectiva programme. The official sources consulted for this file do not specify which of its recommendations were implemented, nor is there any later official communication on record about follow-up to the mission.',
      porQueImporta: 'Without a registry there is no policy: the decision to buy an accelerator, hire oncologists or cover a drug is made on that data. An international assessment has already been carried out, with concrete recommendations on accelerator maintenance, waiting times and resource allocation for high-cost medicines; that its follow-up is not public deprives taxpayers of any way to know whether what was found was corrected.',
      caveat: 'Neither the cancer registry nor the international assessment is a purchase: they leave no trace in the state procurement search. What may appear are the IT systems and support services contracted to sustain the oncological medical record. The report describes the situation surveyed in 2021-2022 and it may have changed.',
    },
  },
]
