import type { CasoDef } from '../types'

/**
 * defensa — 10 dossiers, 7 of them with a live cross-reference.
 *
 * Every source URL was fetched and every query was resolved against the live
 * collection before this file was committed (scripts/verify-casos.ts re-checks
 * both). A caso with no `query` is not a gap in the research: its money does
 * not travel through the Compras Estatales feed at all, which `feedCoverage`
 * records and the page states outright.
 */
export const CASOS_DEFENSA: CasoDef[] = [
  {
    slug: 'cardama-patrullas-oceanicas-rescision',
    emoji: '🚢',
    theme: 'defensa',
    period: '2023-2026',
    statusKind: 'judicial',
    status: 'investigacion',
    amountReported: '82 millones de euros el contrato; 28.794.500 euros pagados; más de US$ 35 millones reclamados en la demanda civil',
    organisms: ['Ministerio de Defensa Nacional', 'Armada Nacional'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'Presidencia de la República', title: 'Gobierno rescindirá contrato con empresa Cardama por compra de patrullas oceánicas', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/gobierno-rescindira-contrato-empresa-cardama-compra-patrullas-oceanicas', date: '2025-10-22' },
      { outlet: 'Infobae', title: 'Paso a paso: cómo Uruguay rescindió el contrato con el astillero español Cardama por dos patrulleras oceánicas', url: 'https://www.infobae.com/america/america-latina/2026/02/16/paso-a-paso-como-uruguay-rescindio-el-contrato-con-el-astillero-espanol-cardama-por-dos-patrulleras-oceanicas/', date: '2026-02-16' },
      { outlet: 'MercoPress', title: 'Uruguay reclamará daños tras no apelar Cardama la rescisión del contrato por patrullas oceánicas', url: 'https://es.mercopress.com/2026/03/19/uruguay-reclamara-danos-tras-no-apelar-cardama-la-rescision-del-contrato-por-patrullas-oceanicas', date: '2026-03-19' },
      { outlet: 'Infodefensa', title: 'Uruguay rescinde el contrato de los patrulleros con Cardama por "incumplimientos graves" y anuncia acciones legales', url: 'https://www.infodefensa.com/texto-diario/mostrar/5772475/uruguay-rescinde-contrato-patrulleros-cardama-incumplimentos-graves-anuncia-acciones-legales', date: '2026-02-14' },
      { outlet: 'Caras y Caretas', title: 'Gobierno demanda a Cardama y reclama cifras millonarias por perjuicios al Estado', url: 'https://www.carasycaretas.com.uy/politica/gobierno-demanda-cardama-y-reclama-cifras-millonarias-perjuicios-al-estado-n98098', date: '2026-08' },
      { outlet: 'Infodefensa', title: 'Uruguay redobla su ofensiva legal contra Cardama con una demanda de 35 millones de dólares', url: 'https://www.infodefensa.com/texto-diario/mostrar/5978002/gobierno-uruguay-redobla-apuesta-contra-cardama-demanda-uruguay-35-millones-dolares', date: '2026-08-07' },
      { outlet: 'Infodefensa', title: 'Cardama presenta una denuncia penal contra Eurocommerce mientras la oposición uruguaya interpela a la ministra de Defensa', url: 'https://www.infodefensa.com/texto-diario/mostrar/5699961/cardama-presenta-denuncia-penal-contra-eurocommerce-mientras-oposicion-uruguaya-interpela-ministra-defensa', date: '2025-12' },
    ],
    es: {
      title: 'Cardama: el contrato de las patrullas oceánicas terminó rescindido',
      dek: 'Uruguay contrató dos patrulleros por 82 millones de euros, pagó casi 29 millones y rescindió el contrato: la garantía presentada resultó, según el Estado, falsa. La empresa lo niega.',
      contexto: 'En diciembre de 2023, bajo la presidencia de Luis Lacalle Pou y con Javier García al frente del Ministerio de Defensa Nacional, Uruguay firmó con el astillero español Cardama la construcción de dos patrullas oceánicas (OPV) para la Armada por 82 millones de euros, según Infodefensa e Infobae. El contrato exigía una garantía de fiel cumplimiento equivalente al 5% del monto. Uruguay fue pagando contra avance de obra: 28.794.500 euros, según la demanda civil que el Estado presentó en agosto de 2026 y reseñó Caras y Caretas.',
      hallazgo: 'El 22 de octubre de 2025 Presidencia informó que el gobierno de Yamandú Orsi rescindiría el contrato y anunció denuncias penales por "fuertes indicios" de fraude o estafa contra el Estado. Según ese comunicado, la empresa demoró once meses solo en constituir las garantías, y la garantía —que debía cubrir 42 meses— alcanzó apenas un año; el prosecretario de Presidencia, Jorge Díaz, describió a la avalista Eurocommerce como "una empresa de papel" y dijo que en su domicilio funcionaba una inmobiliaria de un ciudadano ruso. La rescisión quedó firme en febrero de 2026 y Cardama no la recurrió, según MercoPress, que citó a Díaz: "El acto administrativo de la rescisión del contrato no fue recurrido por el astillero, la rescisión es definitiva". En agosto de 2026 el Estado presentó una demanda civil: reclama los 28.794.500 euros pagados, 18.099.400 euros por la privación de vigilancia naval durante dos años y gastos legales y periciales, según Caras y Caretas; Infodefensa cifró el reclamo en más de US$ 35 millones. El empresario Mario Cardama sostuvo que compró la garantía de buena fe y que, si el emisor no responde, "el fraude es contra su empresa y no contra Uruguay"; denunció penalmente a Eurocommerce —disuelta por el gobierno británico en noviembre de 2025— y, según Infodefensa, el diputado Gabriel Gianoli difundió documentación del Colegio Notarial de Valencia que avalaba la firma que el Estado considera falsa.',
      statusNote: 'Al cierre de esta ficha (agosto de 2026) hay tres frentes abiertos y ninguno con fallo. La denuncia penal del Poder Ejecutivo, que según Infodefensa alcanza a los exministros Javier García y Armando Castaingdebat, al exdirector de Secretaría Fabián Martínez y al exresponsable de Recursos Financieros Damián Galó: ninguno tiene imputación ni condena. La demanda civil por más de US$ 35 millones, presentada a comienzos de agosto de 2026 y radicada, según Caras y Caretas, en el Juzgado Civil de 9.º Turno a cargo del juez Alejandro Recarey. Y un arbitraje internacional que Cardama promovió ante la Cámara de Comercio Internacional, en París.',
      porQueImporta: 'Son casi 29 millones de euros ya pagados por dos buques que nunca llegaron, más el costo de volver a comprar patrulleros desde cero. Cada año de demora es un año sin control efectivo sobre la pesca ilegal y el contrabando en la zona económica exclusiva, y la factura la paga Rentas Generales.',
      caveat: 'El contrato se ejecutó como compra internacional en euros a un astillero extranjero, por fuera del circuito habitual de Compras Estatales, así que difícilmente aparezca completo en el feed de datos abiertos. Lo que sí puede rastrearse ahí son los gastos conexos del Ministerio de Defensa Nacional.',
    },
    en: {
      title: 'Cardama: the ocean patrol ship contract ended in termination',
      dek: 'Uruguay contracted two patrol vessels for €82 million, paid almost €29 million and terminated the deal: the guarantee submitted was, according to the State, fake. The company denies it.',
      contexto: 'In December 2023, under President Luis Lacalle Pou and with Javier García heading the Ministry of National Defence, Uruguay signed a contract with Spanish shipyard Cardama to build two ocean patrol vessels (OPVs) for the Navy for €82 million, according to Infodefensa and Infobae. The contract required a performance guarantee equal to 5% of the amount. Uruguay paid against construction milestones: €28,794,500, according to the civil suit the State filed in August 2026 and reported by Caras y Caretas.',
      hallazgo: 'On 22 October 2025 the Presidency announced that Yamandú Orsi\'s government would terminate the contract and file criminal complaints over "strong indications" of fraud or swindle against the State. According to that statement, the company took eleven months just to lodge the guarantees, and the guarantee — which was meant to cover 42 months — ran for barely a year; Presidency deputy secretary Jorge Díaz described the guarantor Eurocommerce as "a paper company" and said its registered address housed a real-estate business belonging to a Russian citizen. The termination became final in February 2026 and Cardama did not challenge it, according to MercoPress, which quoted Díaz: "The administrative act of terminating the contract was not appealed by the shipyard; the termination is final." In August 2026 the State filed a civil suit: it claims back the €28,794,500 paid, €18,099,400 for two years of lost naval surveillance, and legal and expert costs, according to Caras y Caretas; Infodefensa put the claim at more than US$35 million. Businessman Mario Cardama said he bought the guarantee in good faith and that, if the issuer does not respond, "the fraud is against his company and not against Uruguay"; he filed a criminal complaint against Eurocommerce — dissolved by the UK government in November 2025 — and, according to Infodefensa, MP Gabriel Gianoli circulated documentation from the Valencia Notarial College backing the signature the State considers forged.',
      statusNote: 'As this file closes (August 2026) three fronts are open and none has a ruling. The Executive\'s criminal complaint, which according to Infodefensa names former ministers Javier García and Armando Castaingdebat, former secretariat director Fabián Martínez and former financial resources head Damián Galó: none has been charged or convicted. The civil suit for more than US$35 million, filed in early August 2026 and assigned, according to Caras y Caretas, to the 9th Civil Court under judge Alejandro Recarey. And an international arbitration that Cardama brought before the International Chamber of Commerce in Paris.',
      porQueImporta: 'That is almost €29 million already paid for two ships that never arrived, plus the cost of buying patrol vessels all over again. Every year of delay is a year without effective control over illegal fishing and smuggling in the exclusive economic zone, and the bill is paid out of general revenue.',
      caveat: 'The contract ran as an international purchase in euros from a foreign shipyard, outside the usual Compras Estatales channel, so it is unlikely to appear in full in the open-data feed. What can be traced there are the Ministry of National Defence\'s related expenses.',
    },
  },
  {
    slug: 'patrulleras-usadas-royal-navy-oferta',
    emoji: '⚓',
    theme: 'defensa',
    period: '2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: '60 millones de euros por tres OPV clase River usadas, unos 20 millones cada una',
    organisms: ['Ministerio de Defensa Nacional', 'Armada Nacional'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Comando General de la Armada',
        'Dirección Nacional Aviación Civil e Infraestructura Aeronáut',
        'Dirección Nacional de Sanidad de las Fuerzas Armadas',
        'Comando General del Ejército',
        'Dirección General de Secretaría de Estado',
        'Comando General de la Fuerza Aérea',
        'Dirección Nacional de Meteorología',
        'Dirección General de los Servicios',
        'Estado Mayor de la Defensa',
        'Servicio de Retiros y Pensiones de las Fuerzas Armadas',
        'Ex-Dirección General Infraestructura Aeronáutica',
        'Ex-Dirección Nacional Aviación Civil e Infraestr. Aeronau.',
        'Ex-Dirección General de Aviación Civil',
      ],
      yearFrom: 2026,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Infobae', title: 'Uruguay recibe al menos cinco ofertas para comprar patrulleras oceánicas tras rescindir contrato con española Cardama', url: 'https://www.infobae.com/america/america-latina/2026/02/24/uruguay-recibe-al-menos-cinco-ofertas-para-comprar-patrulleras-oceanicas-tras-rescindir-contrato-con-espanola-cardama/', date: '2026-02-24' },
      { outlet: 'Ámbito', title: 'Reino Unido ofrece tres patrullas oceánicas, pero la Armada advierte que no cumplen sus requisitos mínimos', url: 'https://www.ambito.com/uruguay/reino-unido-ofrece-tres-patrullas-oceanicas-pero-la-armada-advierte-que-no-cumplen-sus-requisitos-minimos-n6261959', date: '2026-03-31' },
      { outlet: 'MercoPress', title: 'Uruguay presenta una oferta de 60 millones de euros para adquirir tres patrulleras usadas de la Royal Navy', url: 'https://es.mercopress.com/2026/06/01/uruguay-presenta-una-oferta-de-60-millones-de-euros-para-adquirir-tres-patrulleras-usadas-de-la-royal-navy', date: '2026-06-01' },
    ],
    es: {
      title: 'Tras Cardama: 60 millones de euros por tres patrulleras usadas',
      dek: 'Sin buques nuevos y con casi 29 millones de euros pagados a un astillero que no entregó, el gobierno ofreció 60 millones de euros por tres patrulleras británicas construidas entre 2001 y 2003.',
      contexto: 'Rescindido el contrato con Cardama, el gobierno abrió la búsqueda de reemplazos. El 24 de febrero de 2026 el presidente Yamandú Orsi dijo que ya habían llegado "por lo menos" cinco propuestas y que la meta es tener los buques antes del cierre de la administración, en 2030, según Infobae. La opción que más avanzó fue la británica: tres patrulleras oceánicas clase River Batch 1 —HMS Tyne, HMS Mersey y HMS Severn—, construidas entre 2001 y 2003 y que quedarían disponibles en 2028. El 1 de junio de 2026 el prosecretario de Presidencia, Jorge Díaz, confirmó a Teledoce que Uruguay presentaría esa semana una nota formal ante la embajada británica ofreciendo 60 millones de euros, unos 20 millones por unidad, según MercoPress.',
      hallazgo: 'El propio gobierno reconoce que la opción barata tiene un costo técnico. Según Ámbito (31 de marzo de 2026), la Armada advirtió que las tres River Batch 1 no tienen hangar ni cubierta de vuelo para operar helicópteros embarcados, una capacidad que consideraba "requisito excluyente", y que sin helicóptero los buques no pueden cumplir su rol de vigilancia de la zona económica exclusiva. Son unidades de 1.770 toneladas, 79,5 metros de eslora, 20 nudos de velocidad máxima y un cañón de 20 mm. Díaz sostuvo que les queda una vida útil de entre 20 y 25 años, según MercoPress. Orsi, al anunciar las ofertas, marcó el límite: el precio es un criterio entre varios y no se pueden repetir errores por comprar barato, según Infobae, que agregó que el Parlamento formó una comisión investigadora sobre todo el proceso de compra anterior.',
      statusNote: 'Al cierre de esta ficha (agosto de 2026) la compra no está cerrada. La última novedad verificada es el anuncio de la nota formal ante la embajada del Reino Unido, informado el 1 de junio de 2026 por MercoPress; los buques recién quedarían libres en 2028 y siguen en evaluación otras propuestas, entre ellas construcciones nuevas. No constan novedades posteriores a esa fecha.',
      porQueImporta: 'Es la segunda vez en tres años que Uruguay intenta dotar de patrulleros a su Armada, y esta vez la discusión es entre pagar más por buques nuevos o menos por buques de más de dos décadas que, según la propia Armada, no cumplen el requisito que ella misma había declarado excluyente. Mientras tanto, según Ámbito, la flota se reduce a dos ex barreminas de los años sesenta. De esa decisión depende cómo se controla la pesca en aguas uruguayas durante los próximos veinte años.',
      caveat: 'Una compra de buques a un Estado extranjero se tramita por acuerdo intergubernamental, no por licitación en Compras Estatales, así que no debería verse en el feed de datos abiertos. Sí aparecerán, más adelante, repuestos, combustible y mantenimiento asociados.',
    },
    en: {
      title: 'After Cardama: €60 million for three second-hand patrol ships',
      dek: 'With no new vessels and almost €29 million paid to a shipyard that never delivered, the government offered €60 million for three British patrol ships built between 2001 and 2003.',
      contexto: 'With the Cardama contract terminated, the government opened a search for replacements. On 24 February 2026 President Yamandú Orsi said "at least" five proposals had already arrived and that the goal is to have the vessels before the administration ends in 2030, according to Infobae. The British option advanced furthest: three River Batch 1 ocean patrol vessels — HMS Tyne, HMS Mersey and HMS Severn — built between 2001 and 2003 and becoming available in 2028. On 1 June 2026 Presidency deputy secretary Jorge Díaz confirmed to Teledoce that Uruguay would submit a formal note to the British embassy that week offering €60 million, about €20 million per unit, according to MercoPress.',
      hallazgo: 'The government itself acknowledges the cheap option carries a technical cost. According to Ámbito (31 March 2026), the Navy warned that the three River Batch 1 vessels have no hangar or flight deck to operate embarked helicopters, a capability it regarded as an "excluding requirement", and that without a helicopter the ships cannot fulfil their role of patrolling the exclusive economic zone. They are 1,770-tonne units, 79.5 metres long, with a top speed of 20 knots and a 20 mm gun. Díaz said they have 20 to 25 years of useful life left, according to MercoPress. Announcing the offers, Orsi set the limit: price is one criterion among several and past mistakes cannot be repeated by buying cheap, according to Infobae, which added that Parliament set up an investigative committee into the whole earlier procurement.',
      statusNote: 'As this file closes (August 2026) the purchase is not settled. The last verified development is the announcement of the formal note to the British embassy, reported on 1 June 2026 by MercoPress; the vessels would only be free in 2028 and other proposals, including new builds, remain under evaluation. No later developments are on record.',
      porQueImporta: 'This is the second time in three years Uruguay has tried to equip its Navy with patrol vessels, and this time the argument is between paying more for new ships or less for ships over two decades old that, by the Navy\'s own account, fail the requirement it had itself declared excluding. Meanwhile, according to Ámbito, the fleet is down to two 1960s ex-minesweepers. How fishing in Uruguayan waters is policed for the next twenty years depends on that call.',
      caveat: 'Buying ships from a foreign State is handled through an intergovernmental agreement, not a tender in Compras Estatales, so it should not show up in the open-data feed. Related spare parts, fuel and maintenance will appear there later.',
    },
  },
  {
    slug: 'vehiculos-agrale-marrua-sin-circular',
    emoji: '🚙',
    theme: 'defensa',
    period: '2025-2026',
    statusKind: 'gestion',
    status: 'terminado',
    amountReported: 'más de US$ 9 millones a valores de 2024 por 84 todoterrenos y 5 ambulancias',
    organisms: ['Ministerio de Defensa Nacional', 'Ejército Nacional'],
    feedCoverage: 'likely',
    sources: [
      { outlet: 'El Observador', title: 'Ejército compró pero no puede utilizar 89 vehículos todoterreno porque contravienen decreto sobre calidad del aire', url: 'https://www.elobservador.com.uy/nacional/ejercito-compro-pero-no-puede-utilizar-89-vehiculos-todoterreno-porque-contravienen-decreto-calidad-del-aire-n6041793' },
      { outlet: 'Caras y Caretas', title: 'Cambio de rumbo: liberan los 89 vehículos todoterreno del Ejército que no podían circular', url: 'https://www.carasycaretas.com.uy/cambio-rumbo-liberan-los-89-vehiculos-todoterreno-del-ejercito-que-no-podian-circular-n95963' },
      { outlet: 'El Eco Digital', title: 'Gobierno gastó US$ 9 millones en vehículos militares que no se pueden usar', url: 'https://elecodigital.com.uy/politica/gobierno-gasto-us-9-millones-en-vehiculos-militares-que-no-se-pueden-usar/', date: '2026-04-27' },
      { outlet: 'Infodefensa', title: 'El Gobierno de Uruguay modifica legislación de emisiones para permitir la entrada de los Agrale Marruá del Ejército', url: 'https://www.infodefensa.com/texto-diario/mostrar/5902068/gobierno-uruguay-modifica-legislacion-emisiones-permitir-entrada-agrale-marrua-ejercito', date: '2026-06-02' },
    ],
    es: {
      title: '89 vehículos militares de US$ 9 millones que no podían circular',
      dek: 'El Ejército compró 84 todoterrenos y 5 ambulancias en 2025; quedaron retenidos en la frontera porque sus motores no cumplían el decreto de calidad del aire de 2021.',
      contexto: 'En febrero de 2025 el Ejército Nacional llamó a licitación pública para renovar su parque de vehículos tácticos livianos. Se adjudicaron 89 unidades del modelo brasileño Agrale Marruá —84 todoterrenos y cinco ambulancias tácticas— por más de US$ 9 millones a valores de 2024, según El Observador. La resolución de compra fue firmada por el entonces ministro de Defensa Nacional, Armando Castaingdebat, y el entonces presidente Luis Lacalle Pou. Según El Eco Digital, la adjudicataria fue LUTRUCKS S.A.S., que ganó el llamado luego de que la china NORINCO fuera rechazada por no cumplir requisitos técnicos. Infodefensa señaló que la compra venía a cubrir un vacío: el Ejército había rematado sus Land Rover Defender y se había quedado sin medios livianos tácticos operativos.',
      hallazgo: 'Los vehículos llegaron y no pudieron usarse. Según El Observador, quedaron retenidos en una aduana de frontera —el caso lo dio a conocer TV Ciudad— porque contravienen el decreto de mayo de 2021 sobre calidad del aire, que no prevé una excepción para vehículos militares; el diario citó el artículo 44 de esa norma, que sí contempla excepciones para importaciones temporarias, y Caras y Caretas, el artículo 41 del Decreto 135/021. Infodefensa precisó que las emisiones de los Marruá son EURO3, por debajo del mínimo exigido. León Lev, presidente de la Comisión de Defensa del Frente Amplio, informó que el Ministerio de Industria ya los había homologado y que faltaba la habilitación ambiental. La salida fue normativa: el ministro de Ambiente, Edgardo Ortuño, firmó un decreto que agrega a las excepciones los "vehículos tácticos de empleo militar", con la condición de que sean desmotorizados una vez desafectados de su uso militar, según Caras y Caretas.',
      statusNote: 'El decreto de excepción fue reportado por Infodefensa el 2 de junio de 2026 y por Caras y Caretas, con lo que los 89 vehículos quedaron habilitados a circular; Caras y Caretas señaló además que algunas unidades ya habían participado del desfile militar del 18 de mayo, y que la medida se adelantó a un proyecto de ley del senador Javier García (Partido Nacional) que proponía autorizarlos para patrullar fronteras. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a junio de 2026.',
      porQueImporta: 'Son más de US$ 9 millones de dinero público inmovilizados durante más de un año por un choque entre dos normas del propio Estado: el pliego de una licitación militar y un decreto ambiental que nadie cruzó antes de adjudicar. No hay denuncia de ilícito en este caso; lo que muestra es el costo concreto de comprar sin verificar que lo comprado pueda usarse.',
      caveat: 'Es una licitación pública común del Ejército Nacional, así que el llamado y la adjudicación deberían aparecer en el feed de compras públicas. Lo que el feed no muestra es la retención aduanera ni el tiempo que los vehículos estuvieron sin poder usarse.',
    },
    en: {
      title: '89 military vehicles worth US$9 million that could not be driven',
      dek: 'The Army bought 84 off-roaders and 5 ambulances in 2025; they were held at the border because their engines breached the 2021 air-quality decree.',
      contexto: 'In February 2025 the National Army issued a public tender to renew its light tactical vehicle fleet. It awarded 89 units of the Brazilian Agrale Marruá — 84 off-road vehicles and five tactical ambulances — for more than US$9 million at 2024 values, according to El Observador. The purchase resolution was signed by then Defence Minister Armando Castaingdebat and then President Luis Lacalle Pou. According to El Eco Digital, the winner was LUTRUCKS S.A.S., which took the tender after China\'s NORINCO was rejected for failing technical requirements. Infodefensa noted the purchase filled a gap: the Army had auctioned off its Land Rover Defenders and was left with no serviceable light tactical vehicles.',
      hallazgo: 'The vehicles arrived and could not be used. According to El Observador, they were held at a border customs post — the case was first reported by TV Ciudad — because they breach the May 2021 air-quality decree, which provides no exception for military vehicles; the paper cited article 44 of that rule, which does allow exceptions for temporary imports, while Caras y Caretas cited article 41 of Decree 135/021. Infodefensa specified that the Marruá\'s emissions are EURO3, below the required minimum. León Lev, chair of the Frente Amplio\'s Defence Committee, reported that the Ministry of Industry had already type-approved them and only environmental clearance was missing. The way out was regulatory: Environment Minister Edgardo Ortuño signed a decree adding "tactical vehicles for military use" to the exceptions, on condition that they be stripped of their engines once withdrawn from military use, according to Caras y Caretas.',
      statusNote: 'The exception decree was reported by Infodefensa on 2 June 2026 and by Caras y Caretas, clearing the 89 vehicles to circulate; Caras y Caretas also noted that some units had already taken part in the 18 May military parade, and that the measure pre-empted a bill by Senator Javier García (Partido Nacional) proposing to authorise them for border patrols. As this file closes (August 2026) no developments after June 2026 are on record.',
      porQueImporta: 'More than US$9 million of public money sat idle for over a year because of a clash between two of the State\'s own rules: a military tender\'s specifications and an environmental decree nobody cross-checked before awarding. There is no allegation of wrongdoing here; what the case shows is the concrete cost of buying without verifying that what is bought can actually be used.',
      caveat: 'This is an ordinary public tender by the National Army, so the call and the award should appear in the public-procurement feed. What the feed does not show is the customs hold or the time the vehicles spent unusable.',
    },
  },
  {
    slug: 'caja-militar-deficit-rentas-generales',
    emoji: '🎖️',
    theme: 'defensa',
    period: '2015-2026',
    statusKind: 'debate',
    status: 'debate',
    amountReported: 'US$ 583,6 millones de asistencia financiera del Estado en 2025 (unos $ 24.239 millones)',
    organisms: ['Ministerio de Defensa Nacional', 'Servicio de Retiros y Pensiones de las Fuerzas Armadas'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Comando General de la Armada',
        'Dirección Nacional Aviación Civil e Infraestructura Aeronáut',
        'Dirección Nacional de Sanidad de las Fuerzas Armadas',
        'Comando General del Ejército',
        'Dirección General de Secretaría de Estado',
        'Comando General de la Fuerza Aérea',
        'Dirección Nacional de Meteorología',
        'Dirección General de los Servicios',
        'Estado Mayor de la Defensa',
        'Servicio de Retiros y Pensiones de las Fuerzas Armadas',
        'Ex-Dirección General Infraestructura Aeronáutica',
        'Ex-Dirección Nacional Aviación Civil e Infraestr. Aeronau.',
        'Ex-Dirección General de Aviación Civil',
      ],
      search: 'retiros',
      yearFrom: 2015,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Presidencia de la República', title: 'Asistencia financiera a Caja Militar se multiplicó por 10 en los últimos 15 años', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/asistencia-financiera-caja-militar-se-multiplico-10-ultimos-15-anos', date: '2018-09-29' },
      { outlet: 'El Observador', title: 'Caja militar tiene déficit de US$ 450 millones y sus proyecciones no están incluidas en el borrador de la reforma jubilatoria', url: 'https://www.elobservador.com.uy/nota/caja-militar-tiene-un-deficit-de-us-450-millones-y-cada-dos-pasivos-hay-un-activo-202121613160', date: '2021-02-17' },
      { outlet: 'la diaria', title: 'Gobierno destinó 452 millones de dólares como asistencia financiera para la Caja Militar', url: 'https://ladiaria.com.uy/economia/articulo/2022/4/gobierno-destino-452-millones-de-dolares-como-asistencia-financiera-para-la-caja-militar/', date: '2022-04-27' },
      { outlet: 'Ámbito', title: 'El gobierno inyectó u$s 584M para asistir financieramente a la Caja Militar', url: 'https://www.ambito.com/uruguay/el-gobierno-inyecto-us-584m-asistir-financieramente-la-caja-militar-n6153586', date: '2025-06-06' },
    ],
    es: {
      title: 'La Caja Militar: US$ 583 millones al año de Rentas Generales',
      dek: 'El sistema de retiros de las Fuerzas Armadas no se paga con sus aportes: en 2025 el Estado le transfirió US$ 583,6 millones, tras US$ 374 millones en 2021.',
      contexto: 'El Servicio de Retiros y Pensiones de las Fuerzas Armadas, conocido como Caja Militar, paga los retiros y pensiones del personal militar. Sus ingresos por aportes no alcanzan y la diferencia la cubre Rentas Generales, es decir, el resto de los contribuyentes. El 29 de setiembre de 2018, en la Comisión de Presupuesto donde se discutía la reforma del régimen previsional militar, el entonces ministro de Trabajo, Ernesto Murro, afirmó que "la asistencia financiera a la Caja Militar se multiplicó por 10 en los últimos 15 años": de unos US$ 65 millones en 2005 a cerca de US$ 700 millones proyectados para 2020, según Presidencia. En la misma sesión, el entonces ministro de Economía Pablo Ferreri señaló que el Servicio cubría con recursos propios apenas el 15% de sus egresos y que Rentas Generales financiaba el 85% restante, la menor cobertura propia de todo el sistema previsional.',
      hallazgo: 'Las cifras oficiales muestran un desequilibrio estructural, no coyuntural. Según El Observador, en 2019 la Caja Militar tuvo ingresos por US$ 216,1 millones y egresos por US$ 666,5 millones, con 27.133 cotizantes activos y una relación activo/pasivo de 0,53: cada dos pasivos hay un activo. El déficit creció de US$ 362 millones en 2015 a US$ 450,5 millones. La asistencia anual siguió aumentando: US$ 374 millones en 2021, US$ 452 millones en 2022 —cifra que la diaria atribuyó al presupuesto del ejercicio 2022, equivalente a $ 19.374 millones—, US$ 546 millones en 2023, US$ 550 millones en 2024 y US$ 583,6 millones en 2025, según Ámbito. En 2021 El Observador consignó además que las proyecciones de la Caja Militar no estaban incluidas en el borrador de la reforma jubilatoria general, algo que el PIT-CNT objetó.',
      statusNote: 'El último dato verificado es la asistencia financiera de 2025 por unos $ 24.239 millones (US$ 583,6 millones), reportada por Ámbito el 6 de junio de 2025, en una operación en la que intervinieron el presidente Yamandú Orsi, el ministro de Economía Gabriel Oddone y la ministra de Defensa Sandra Lazo. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a esa fecha sobre una nueva reforma del régimen previsional militar.',
      porQueImporta: 'Cada peso que Rentas Generales pone en la Caja Militar es un peso que no va a salud, educación o vivienda. La asistencia de 2025 —US$ 583,6 millones— equivale a un gasto anual permanente decidido fuera de cualquier licitación y sin contrapartida de servicio.',
      caveat: 'Es una transferencia presupuestal, no una compra: no aparece como contrato en el feed de compras públicas. Lo que sí puede rastrearse son las compras del Ministerio de Defensa Nacional y del propio Servicio de Retiros y Pensiones.',
    },
    en: {
      title: 'The Military Pension Fund: US$583 million a year from general revenue',
      dek: 'The armed forces\' retirement system is not paid for by its own contributions: in 2025 the State transferred US$583.6 million to it, after US$374 million in 2021.',
      contexto: 'The Armed Forces Retirement and Pensions Service, known as the Caja Militar, pays military retirements and pensions. Its contribution income falls short and the gap is covered by general revenue — that is, by every other taxpayer. On 29 September 2018, at the Budget Committee session discussing reform of the military pension regime, then Labour Minister Ernesto Murro stated that "financial assistance to the Caja Militar has multiplied tenfold over the last 15 years": from about US$65 million in 2005 to some US$700 million projected for 2020, according to the Presidency. At the same session, then Economy Minister Pablo Ferreri noted that the Service covered barely 15% of its outlays from its own resources and that general revenue financed the remaining 85%, the lowest self-coverage in the whole pension system.',
      hallazgo: 'Official figures show a structural, not a passing, imbalance. According to El Observador, in 2019 the Caja Militar had income of US$216.1 million against outlays of US$666.5 million, with 27,133 active contributors and an active-to-retiree ratio of 0.53: one active member for every two retirees. The deficit grew from US$362 million in 2015 to US$450.5 million. Annual assistance kept rising: US$374 million in 2021, US$452 million in 2022 — a figure la diaria attributed to the 2022 budget year, equal to $19.374 billion pesos — US$546 million in 2023, US$550 million in 2024 and US$583.6 million in 2025, according to Ámbito. In 2021 El Observador also noted that the Caja Militar\'s projections were not included in the draft of the general pension reform, which the PIT-CNT union federation objected to.',
      statusNote: 'The latest verified figure is the 2025 financial assistance of about $24.239 billion pesos (US$583.6 million), reported by Ámbito on 6 June 2025, in an operation involving President Yamandú Orsi, Economy Minister Gabriel Oddone and Defence Minister Sandra Lazo. As this file closes (August 2026) no developments after that date are on record regarding a new reform of the military pension regime.',
      porQueImporta: 'Every peso general revenue puts into the Caja Militar is a peso that does not go to health, education or housing. The 2025 assistance — US$583.6 million — is permanent annual spending decided outside any tender and with no service in return.',
      caveat: 'This is a budget transfer, not a purchase: it does not appear as a contract in the public-procurement feed. What can be traced there are the purchases of the Ministry of National Defence and of the Retirement and Pensions Service itself.',
    },
  },
  {
    slug: 'auditoria-vivienda-social-defensa',
    emoji: '🏠',
    theme: 'defensa',
    period: '2023-2025',
    statusKind: 'auditoria',
    status: 'auditoria',
    amountReported: '$ 9.436.052 obligados en 2023, $ 5.547.934 en 2024 y $ 8.987.247 en 2025; canastas de materiales de hasta $ 430.000',
    organisms: ['Ministerio de Defensa Nacional', 'Dirección General de los Servicios Sociales del Ministerio de Defensa Nacional'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Comando General de la Armada',
        'Dirección Nacional Aviación Civil e Infraestructura Aeronáut',
        'Dirección Nacional de Sanidad de las Fuerzas Armadas',
        'Comando General del Ejército',
        'Dirección General de Secretaría de Estado',
        'Comando General de la Fuerza Aérea',
        'Dirección Nacional de Meteorología',
        'Dirección General de los Servicios',
        'Estado Mayor de la Defensa',
        'Servicio de Retiros y Pensiones de las Fuerzas Armadas',
        'Ex-Dirección General Infraestructura Aeronáutica',
        'Ex-Dirección Nacional Aviación Civil e Infraestr. Aeronau.',
        'Ex-Dirección General de Aviación Civil',
      ],
      search: 'portland',
      yearFrom: 2023,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'Auditoría Interna de la Nación (MEF)', title: 'Ministerio de Defensa Nacional (MDN) - Dirección General de los Servicios Sociales - Informe de auditoría del Programa de Vivienda Social', url: 'https://www.gub.uy/ministerio-economia-finanzas/sites/ministerio-economia-finanzas/files/documentos/publicaciones/2026_MinisterioDeDefensaNacional-DireccionGeneraldeSecretar%C3%ADa.pdf', date: '2026-04' },
      { outlet: 'Ministerio de Defensa Nacional', title: 'Programa de Vivienda Social', url: 'https://www.gub.uy/ministerio-defensa-nacional/politicas-y-gestion/programa-vivienda-social' },
      { outlet: 'El País', title: 'Programa de vivienda de Defensa: detectan irregularidades y riesgo de subsidiar a quienes no cumplen requisitos', url: 'https://www.elpais.com.uy/informacion/politica/programa-de-vivienda-de-defensa-detectan-irregularidades-y-riesgo-de-subsidiar-a-quienes-no-cumplen-requisitos', date: '2026-05-24' },
    ],
    es: {
      title: 'Auditoría a Defensa: materiales entregados sin remitos válidos',
      dek: 'La Auditoría Interna de la Nación revisó el plan de vivienda del Ministerio de Defensa y anotó entregas sin comprobantes válidos y riesgo de pagar materiales no entregados.',
      contexto: 'El Programa de Vivienda Social del Ministerio de Defensa Nacional surgió en 2011 como plan piloto de "Vivienda Adecuada" y lo ejecuta la Dirección General de los Servicios Sociales. Entrega una canasta de materiales de construcción no retributiva a funcionarios del inciso —personal subalterno escalafón K y personal civil— con carencias edilicias, para que autoconstruyan. Según el informe de auditoría, la canasta se estima en hasta $ 240.000 y excepcionalmente puede alcanzar los $ 430.000, para un módulo básico de baño y un ambiente de 16 m². Entre enero de 2023 y diciembre de 2025 se otorgaron 186 subsidios. Los materiales se compran a través de la Unidad Centralizada de Adquisiciones para la Defensa (U.C.AA.D.) mediante licitaciones públicas y abreviadas, concursos de precios y compras directas: $ 9.436.052 obligados en 2023, $ 5.547.934 en 2024 y $ 8.987.247 en 2025.',
      hallazgo: 'La Auditoría Interna de la Nación, en un informe fechado en abril de 2026 sobre el período enero 2024–diciembre 2025, reportó cuatro hallazgos. En el primero constató notas del director certificando que los recursos se destinaron al programa "dejando constancia de la no existencia de los remitos correspondientes", remitos sin firma del receptor de los materiales y documentación que "no reviste carácter de remito válido conforme a la normativa vigente". Entre los riesgos anotó, textualmente, "Pago de materiales no entregados o no utilizados en obra" y "Colusión", ambos clasificados como fraude. En el segundo hallazgo constató ausencias de informes jurídicos entre 2024 y 2025 sobre la relación jurídica del beneficiario con el inmueble —requisito obligatorio—, resoluciones que no siempre incluyen el detalle del proveedor ni el monto total del beneficio, la falta de un monto máximo formalizado y un caso de 2024 en el que la resolución de entrega de materiales se emitió cinco meses después del cese del beneficiario en el Ministerio y se efectivizó igual. El seguimiento de obras fuera del área metropolitana, agrega, se basa "principalmente en llamadas telefónicas y/o mensajes".',
      statusNote: 'El informe está fechado en Montevideo, abril de 2026, y publicado por el Ministerio de Economía y Finanzas. La propia auditoría señala que la debilidad en el control de la documentación de entregas y en el seguimiento de obras es una "situación ya advertida por la Auditoría Interna de la Nación en la Actuación del 2017". Al cierre de esta ficha (agosto de 2026) no consta una respuesta pública del Ministerio de Defensa Nacional a las recomendaciones.',
      porQueImporta: 'El programa reparte materiales de construcción a los funcionarios peor pagos del Ministerio. Que no haya remitos válidos no prueba que falten materiales, pero significa que el Estado no puede demostrar que lo que pagó llegó a quien debía. Y si no llega, el perjudicado es el soldado que espera un baño y un cuarto.',
      caveat: 'Las compras de materiales sí pasan por Compras Estatales —licitaciones, concursos de precios y compras directas de la U.C.AA.D.—, así que el gasto es rastreable en el feed. Lo que el feed no puede mostrar es si el material llegó al beneficiario: eso es justamente lo que la auditoría dice que no pudo verificarse.',
    },
    en: {
      title: 'Audit at Defence: materials handed over without valid receipts',
      dek: 'The National Internal Audit Office reviewed the Defence Ministry\'s housing plan and recorded deliveries without valid documentation and a risk of paying for materials never delivered.',
      contexto: 'The Ministry of National Defence\'s Social Housing Programme began in 2011 as an "Adequate Housing" pilot and is run by the General Directorate of Social Services. It hands out a non-salary basket of building materials to ministry staff — junior K-scale and civilian personnel — living in substandard housing, so they can build for themselves. According to the audit report, the basket is estimated at up to $240,000 pesos and exceptionally up to $430,000, for a basic 16 m² module with a bathroom and one room. Between January 2023 and December 2025, 186 subsidies were granted. Materials are bought through the Centralised Defence Procurement Unit (U.C.AA.D.) via public and abbreviated tenders, price competitions and direct purchases: $9,436,052 committed in 2023, $5,547,934 in 2024 and $8,987,247 in 2025.',
      hallazgo: 'The National Internal Audit Office, in a report dated April 2026 covering January 2024 to December 2025, reported four findings. In the first it found notes from the director certifying that funds went to the programme "placing on record the non-existence of the corresponding delivery notes", delivery notes without the signature of the person receiving the materials, and documentation that "does not constitute a valid delivery note under the applicable rules". Among the risks it listed, verbatim, "Payment for materials not delivered or not used in the works" and "Collusion", both classified as fraud. In the second finding it noted the absence of legal reports between 2024 and 2025 on the beneficiary\'s legal relationship to the property — a mandatory requirement — resolutions that do not always include the supplier detail or the total benefit amount, the lack of a formalised maximum amount, and a 2024 case in which the materials-delivery resolution was issued five months after the beneficiary had left the Ministry and was carried out anyway. Monitoring of works outside the metropolitan area, it adds, relies "mainly on phone calls and/or messages".',
      statusNote: 'The report is dated Montevideo, April 2026, and published by the Ministry of Economy and Finance. The audit itself states that the weakness in controlling delivery documentation and in monitoring works is a "situation already flagged by the National Internal Audit Office in the 2017 engagement". As this file closes (August 2026) there is no public response from the Ministry of National Defence to the recommendations on record.',
      porQueImporta: 'The programme distributes building materials to the Ministry\'s lowest-paid staff. The absence of valid delivery notes does not prove materials are missing, but it means the State cannot demonstrate that what it paid for reached the intended recipient. And if it does not, the one who loses out is the soldier waiting for a bathroom and a room.',
      caveat: 'Material purchases do go through Compras Estatales — tenders, price competitions and direct purchases by the U.C.AA.D. — so the spending is traceable in the feed. What the feed cannot show is whether the material reached the beneficiary: that is precisely what the audit says could not be verified.',
    },
  },
  {
    slug: 'super-tucano-compra-fuerza-aerea',
    emoji: '✈️',
    theme: 'defensa',
    period: '2022-2026',
    statusKind: 'debate',
    status: 'en-ejecucion',
    amountReported: 'más de US$ 100 millones por seis A-29 Super Tucano y un simulador, según Presidencia',
    organisms: ['Ministerio de Defensa Nacional', 'Fuerza Aérea Uruguaya'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Comando General de la Armada',
        'Dirección Nacional Aviación Civil e Infraestructura Aeronáut',
        'Dirección Nacional de Sanidad de las Fuerzas Armadas',
        'Comando General del Ejército',
        'Dirección General de Secretaría de Estado',
        'Comando General de la Fuerza Aérea',
        'Dirección Nacional de Meteorología',
        'Dirección General de los Servicios',
        'Estado Mayor de la Defensa',
        'Servicio de Retiros y Pensiones de las Fuerzas Armadas',
        'Ex-Dirección General Infraestructura Aeronáutica',
        'Ex-Dirección Nacional Aviación Civil e Infraestr. Aeronau.',
        'Ex-Dirección General de Aviación Civil',
      ],
      search: 'aeronave',
      yearFrom: 2022,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Presidencia de la República', title: 'Fuerza Aérea adquirió aeronaves militares para control del espacio aéreo y protección fronteriza', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/fuerza-aerea-adquirio-aeronaves-militares-para-control-del-espacio-aereo', date: '2026-02-24' },
      { outlet: 'Infobae', title: 'Uruguay renueva su Fuerza Aérea: por qué eligió los Super Tucano para reemplazar a sus históricos aviones', url: 'https://www.infobae.com/america/mundo/2026/07/22/uruguay-renueva-su-fuerza-aerea-por-que-eligio-los-super-tucano-para-reemplazar-a-sus-historicos-aviones/', date: '2026-07-22' },
      { outlet: 'Infodefensa', title: 'Super Tucanos: una decisión política oportuna pero un acta de defunción para la aviación de caza uruguaya', url: 'https://www.infodefensa.com/texto-diario/mostrar/4932111', date: '2024-07-19' },
      { outlet: 'Infodefensa', title: 'Uruguay negocia con Brasil la compra de 12 aviones Super Tucano por 40 millones de dólares', url: 'https://www.infodefensa.com/texto-diario/mostrar/3742743', date: '2022-05-09' },
    ],
    es: {
      title: 'Seis Super Tucano por US$ 100 millones: la mayor compra aérea',
      dek: 'Uruguay compró seis aviones nuevos a Embraer al final del gobierno de Lacalle Pou; dos años antes negociaba doce usados por US$ 40 millones.',
      contexto: 'En 2021 y 2022 Uruguay negociaba con Brasil la transferencia de doce A-29 Super Tucano de las reservas de la Fuerza Aérea Brasileña, con células y motores a cero horas y soporte de mantenimiento y entrenamiento, por unos US$ 40 millones —3,5 millones por unidad—, según Infodefensa. En julio de 2024 el gobierno de Luis Lacalle Pou, con Armando Castaingdebat como ministro de Defensa Nacional, confirmó en cambio la compra de A-29 nuevos por unos US$ 100 millones. Las dos primeras aeronaves de un total de seis fueron presentadas el 24 de febrero de 2026 en el Escuadrón Aéreo n.º 2 de Durazno, con la presencia del presidente Yamandú Orsi, el comandante en jefe de la Fuerza Aérea Fernando Colina y el expresidente Lacalle Pou.',
      hallazgo: 'Presidencia informó que la inversión "supera los 100 millones de dólares" e incluye seis aviones más un simulador, y que el plan agrega naves interceptoras y tres radares de alta movilidad, además de modernizar dos radares transportables; la ministra Sandra Lazo la definió como "una modernización fundamental y necesaria". Un análisis firmado por Gabriel Porfilio en Infodefensa el 19 de julio de 2024 cuestionó la decisión: la calificó como "más una decisión política que técnica", sostuvo que dejaba de lado la recomendación técnica de la Fuerza Aérea de aviones a reacción con radar a bordo y advirtió que el momento elegido —antes de las elecciones— volvía muy riesgoso para un nuevo gobierno cancelar un contrato tan caro, asegurando su continuidad. El título de ese análisis habla de "un acta de defunción para la aviación de caza uruguaya". Infobae señaló, a favor, que la hora de vuelo del A-29 ronda los US$ 2.000 frente a unos US$ 10.000 de un F-16, y que reemplaza a los IA-58 Pucará —retirados en 2017— y a los A-37 Dragonfly.',
      statusNote: 'Las dos primeras aeronaves fueron entregadas y presentadas el 24 de febrero de 2026, según Presidencia; el resto del lote, el simulador y el paquete logístico seguían pendientes de entrega. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores al artículo de Infobae del 22 de julio de 2026 ni resoluciones parlamentarias o judiciales sobre la compra.',
      porQueImporta: 'Es la mayor inversión aeronáutica militar de Uruguay en décadas y compromete presupuesto por años. La comparación entre las dos opciones que el Estado evaluó —doce usados por US$ 40 millones o seis nuevos por más de US$ 100 millones— no es directa, porque cambian el estado del material y lo que incluye cada paquete (Infobae señala que el contrato cubre aviones, simulador, entrenamiento, repuestos y soporte logístico), pero muestra cuánto puede variar el precio de una misma capacidad según cómo se decida comprarla.',
      caveat: 'Es un contrato internacional con un fabricante extranjero, negociado de gobierno a empresa, por lo que probablemente no figure como llamado en Compras Estatales. Sí deberían aparecer en el feed los gastos conexos: obras de hangaraje, combustible de aviación y repuestos de la Fuerza Aérea Uruguaya.',
    },
    en: {
      title: 'Six Super Tucanos for US$100 million: the biggest air purchase',
      dek: 'Uruguay bought six new Embraer aircraft at the end of the Lacalle Pou government; two years earlier it was negotiating twelve used ones for US$40 million.',
      contexto: 'In 2021 and 2022 Uruguay was negotiating with Brazil the transfer of twelve A-29 Super Tucanos from Brazilian Air Force reserves, with airframes and engines at zero hours plus maintenance and training support, for about US$40 million — US$3.5 million per unit — according to Infodefensa. In July 2024 Luis Lacalle Pou\'s government, with Armando Castaingdebat as Defence Minister, instead confirmed the purchase of new A-29s for about US$100 million. The first two of six aircraft were presented on 24 February 2026 at Air Squadron No. 2 in Durazno, with President Yamandú Orsi, Air Force commander-in-chief Fernando Colina and former president Lacalle Pou present.',
      hallazgo: 'The Presidency reported that the investment "exceeds 100 million dollars" and covers six aircraft plus a simulator, and that the plan adds interceptor craft and three high-mobility radars, as well as modernising two transportable radars; Minister Sandra Lazo called it "a fundamental and necessary modernisation". An analysis by Gabriel Porfilio in Infodefensa on 19 July 2024 questioned the decision: it called it "more a political than a technical decision", argued it set aside the Air Force\'s technical recommendation for jet aircraft with onboard radar, and warned that the timing — before the elections — made cancelling such an expensive contract very risky for a new government, thereby securing its continuity. The headline of that analysis speaks of "a death certificate for Uruguayan fighter aviation". Infobae noted, in favour, that the A-29\'s flight hour runs at around US$2,000 against roughly US$10,000 for an F-16, and that it replaces the IA-58 Pucará — retired in 2017 — and the A-37 Dragonfly.',
      statusNote: 'The first two aircraft were delivered and presented on 24 February 2026, according to the Presidency; the rest of the batch, the simulator and the logistics package were still pending delivery. As this file closes (August 2026) there are no developments after Infobae\'s article of 22 July 2026, and no parliamentary or judicial rulings on the purchase.',
      porQueImporta: 'This is Uruguay\'s largest military aviation investment in decades and commits budget for years. The comparison between the two options the State weighed — twelve used aircraft for US$40 million or six new ones for over US$100 million — is not like for like, since the condition of the aircraft and the contents of each package differ (Infobae notes the contract covers aircraft, simulator, training, spare parts and logistical support), but it shows how much the price of the same capability can vary depending on how the purchase is structured.',
      caveat: 'This is an international contract with a foreign manufacturer, negotiated government-to-company, so it probably does not appear as a tender in Compras Estatales. Related spending should show up in the feed: hangar works, aviation fuel and Uruguayan Air Force spare parts.',
    },
  },
  {
    slug: 'gasto-militar-uruguay-lidera-region',
    emoji: '📊',
    theme: 'defensa',
    period: '2020-2026',
    statusKind: 'debate',
    status: 'debate',
    amountReported: 'US$ 577 por habitante y US$ 1.954,3 millones en total en 2025 según Ámbito citando a SIPRI; MercoPress publicó US$ 577,2 millones como total del país',
    organisms: ['Ministerio de Defensa Nacional', 'Servicio de Retiros y Pensiones de las Fuerzas Armadas'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Comando General de la Armada',
        'Dirección Nacional Aviación Civil e Infraestructura Aeronáut',
        'Dirección Nacional de Sanidad de las Fuerzas Armadas',
        'Comando General del Ejército',
        'Dirección General de Secretaría de Estado',
        'Comando General de la Fuerza Aérea',
        'Dirección Nacional de Meteorología',
        'Dirección General de los Servicios',
        'Estado Mayor de la Defensa',
        'Servicio de Retiros y Pensiones de las Fuerzas Armadas',
        'Ex-Dirección General Infraestructura Aeronáutica',
        'Ex-Dirección Nacional Aviación Civil e Infraestr. Aeronau.',
        'Ex-Dirección General de Aviación Civil',
      ],
      search: 'uniforme militar',
      yearFrom: 2020,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Ámbito', title: 'Uruguay lidera en la región en gasto militar per cápita con el mayor aumento en los últimos cinco años', url: 'https://www.ambito.com/uruguay/lidera-la-region-gasto-militar-per-capita-el-mayor-aumento-los-ultimos-cinco-anos-n6278761', date: '2026-05-18' },
      { outlet: 'MercoPress', title: 'Brasil lidera el gasto militar de Sudamérica y Uruguay registra uno de los mayores aumentos relativos', url: 'https://es.mercopress.com/2026/05/17/brasil-lidera-el-gasto-militar-de-sudamerica-y-uruguay-registra-uno-de-los-mayores-aumentos-relativos', date: '2026-05-17' },
      { outlet: 'SIPRI', title: 'Cuestionario de gasto militar del SIPRI (definición de gasto militar)', url: 'https://www.sipri.org/sites/default/files/SIPRI%20Q_electronic_spa.pdf' },
      { outlet: 'Asociación Española de Ciencia Regional (AECR)', title: 'El gasto militar en América', url: 'https://aecr.org/en/el-gasto-militar-en-america/', date: '2025-05-28' },
      { outlet: 'Infodefensa', title: 'La Rendición de Cuentas de Uruguay recorta más de 3,3 millones de dólares al Ministerio de Defensa', url: 'https://www.infodefensa.com/texto-diario/mostrar/5955268/rendicion-cuentas-anual-gobierno-uruguay-quita-33-millones-dolares-ministerio-defensa', date: '2026-07-16' },
    ],
    es: {
      title: 'Uruguay lidera el gasto militar por habitante de Sudamérica',
      dek: 'Según SIPRI citado por Ámbito, Uruguay gastó más de US$ 577 por habitante en defensa en 2025, casi el doble que el segundo de la región; casi la mitad del presupuesto va a retiros militares.',
      contexto: 'El Instituto Internacional de Estocolmo para la Investigación de la Paz (SIPRI) divulgó el 17 de mayo de 2026 su informe anual de gasto militar. Ámbito, al día siguiente, publicó los datos de Uruguay: "más de 577 dólares por habitante" en 2025 —contra US$ 297,1 de Guyana, US$ 272,8 de Colombia, US$ 268,9 de Chile, US$ 112,7 de Brasil y US$ 84,7 de Argentina—, un total de US$ 1.954,3 millones, 2,28% del Producto Interno Bruto y alrededor del 7,09% del gasto público, el segundo porcentaje más alto de la región detrás de Colombia (9,29%). Ámbito ubica el punto de partida en 2020, cuando el gasto era de US$ 320,90 por habitante: un aumento de 79,87% en cinco años.',
      hallazgo: 'La cifra que ubica a Uruguay a la cabeza de la región no mide sobre todo armamento. El propio cuestionario con el que SIPRI recoge los datos establece que "las pensiones militares deben ser incluidas de acuerdo a la definición de gasto militar del SIPRI" y pide a cada país una estimación si no están computadas. Y un análisis del economista Ronny Correa-Quezada (Universidad Técnica Particular de Loja), publicado el 28 de mayo de 2025 por la Asociación Española de Ciencia Regional, señala que en Uruguay "en el presupuesto de defensa, se destina casi un 50% al Servicio de Retiro y Pensiones" de las Fuerzas Armadas. Corresponde además marcar una discrepancia entre las fuentes que informaron el mismo dato de SIPRI: Ámbito reporta 577 y 320,90 dólares como gasto por habitante y US$ 1.954,3 millones como total del país, mientras MercoPress publica 577,2 y 320,9 millones de dólares como el gasto total de Uruguay en 2025 y 2020, con un incremento "cercano al 80%". Esta ficha publica ambas lecturas.',
      statusNote: 'En sentido contrario al aumento, la Rendición de Cuentas presentada en 2026 recorta más de US$ 3,3 millones al Ministerio de Defensa Nacional: unos US$ 1,4 millones previstos para aumentos de remuneraciones del personal militar y otros US$ 1,9 millones de gastos de funcionamiento —combustible, operativos e insumos sanitarios—, según Infodefensa el 16 de julio de 2026. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores.',
      porQueImporta: 'Si casi la mitad de lo que Uruguay declara como gasto de defensa son retiros y pensiones, el país puede aparecer primero en la región y a la vez tener buques de los años sesenta y recortes en combustible e insumos sanitarios. La discusión que abre el dato no es cuánto se gasta, sino en qué: la comparación internacional puede leerse mal si no se descuenta la parte previsional.',
      caveat: 'El gasto de defensa que mide SIPRI incluye pensiones y remuneraciones, que no son compras y no aparecen en el feed de contrataciones. En Compras Estatales solo se ve la porción de bienes y servicios: combustible, uniformes, alimentos, mantenimiento y obras.',
    },
    en: {
      title: 'Uruguay leads South America in military spending per capita',
      dek: 'According to SIPRI cited by Ámbito, Uruguay spent more than US$577 per inhabitant on defence in 2025, almost double the region\'s runner-up; nearly half the budget goes to military pensions.',
      contexto: 'The Stockholm International Peace Research Institute (SIPRI) released its annual military spending report on 17 May 2026. The next day, Ámbito published Uruguay\'s figures: "more than 577 dollars per inhabitant" in 2025 — against US$297.1 for Guyana, US$272.8 for Colombia, US$268.9 for Chile, US$112.7 for Brazil and US$84.7 for Argentina — a total of US$1,954.3 million, 2.28% of GDP and around 7.09% of public spending, the second-highest share in the region behind Colombia (9.29%). Ámbito puts the starting point in 2020, when spending was US$320.90 per inhabitant: a 79.87% rise in five years.',
      hallazgo: 'The figure that puts Uruguay at the top of the region is not mainly a measure of weapons. SIPRI\'s own data questionnaire states that "military pensions must be included in accordance with SIPRI\'s definition of military expenditure" and asks each country for an estimate if they are not counted. And an analysis by economist Ronny Correa-Quezada (Universidad Técnica Particular de Loja), published on 28 May 2025 by the Spanish Regional Science Association, notes that in Uruguay "almost 50% of the defence budget goes to the Retirement and Pensions Service" of the armed forces. A discrepancy between the outlets reporting the same SIPRI data should also be flagged: Ámbito reports 577 and 320.90 dollars as spending per inhabitant and US$1,954.3 million as the country total, while MercoPress publishes 577.2 and 320.9 million dollars as Uruguay\'s total spending in 2025 and 2020, with an increase "close to 80%". This file publishes both readings.',
      statusNote: 'Running against the increase, the 2026 Rendición de Cuentas cuts more than US$3.3 million from the Ministry of National Defence: about US$1.4 million earmarked for military pay rises and another US$1.9 million in operating costs — fuel, operations and health supplies — according to Infodefensa on 16 July 2026. As this file closes (August 2026) no later developments are on record.',
      porQueImporta: 'If nearly half of what Uruguay reports as defence spending is retirements and pensions, the country can rank first in the region while still sailing 1960s ships and cutting fuel and medical supplies. The question the figure opens is not how much is spent, but on what: international comparisons can mislead unless the pension share is stripped out.',
      caveat: 'The defence spending SIPRI measures includes pensions and salaries, which are not purchases and do not appear in the procurement feed. Compras Estatales only shows the goods-and-services share: fuel, uniforms, food, maintenance and works.',
    },
  },
  {
    slug: 'militares-seguridad-interna-blindados-mamba',
    emoji: '🛡️',
    theme: 'defensa',
    period: '2026',
    statusKind: 'debate',
    status: 'debate',
    organisms: ['Ministerio de Defensa Nacional', 'Ejército Nacional', 'Ministerio del Interior'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'Infodefensa', title: 'El Gobierno de Uruguay busca utilizar medios militares en la lucha contra el delito interno', url: 'https://www.infodefensa.com/texto-diario/mostrar/5931367/gobierno-uruguay-busca-utilizar-medios-militares-lucha-contra-delito-interno', date: '2026-06-25' },
      { outlet: 'Caras y Caretas', title: 'La Mamba que envenenó al Gobierno', url: 'https://www.carasycaretas.com.uy/politica/la-mamba-que-enveneno-al-gobierno-n96852', date: '2026-06-26' },
      { outlet: 'Subrayado', title: 'Interior presentó primer blindado Cóndor del Ejército que participará en patrullaje; espera respuesta de EE.UU. por los Mamba', url: 'https://www.subrayado.com.uy/interior-presento-primer-blindado-condor-del-ejercito-que-participara-patrullaje-espera-respuesta-eeuu-los-mamba-n1013667', date: '2026-07-24' },
      { outlet: 'Ejército Nacional', title: 'El Ejército Nacional incrementa su compromiso en la custodia de fronteras', url: 'https://www.ejercito.mil.uy/index.php/2026/06/24/el-ejercito-nacional-incrementa-su-compromiso-en-la-custodia-de-fronteras/', date: '2026-06-18' },
      { outlet: 'Prensa Mercosur', title: 'Consejo de Ministros analiza el marco jurídico y operativo para incorporar vehículos militares al patrullaje', url: 'https://prensamercosur.org/2026/06/26/consejo-de-ministros-analiza-el-marco-juridico-y-operativo-para-incorporar-vehiculos-militares-al-patrullaje-id199135/', date: '2026-06-26' },
    ],
    es: {
      title: 'Blindados militares en las calles: los Mamba donados por EE.UU.',
      dek: 'El gobierno quiso usar blindados donados por Estados Unidos para patrullar Montevideo, pero el convenio de donación los reserva para misiones de paz.',
      contexto: 'En junio de 2026, ante el aumento de la violencia en Montevideo, el gobierno de Yamandú Orsi evaluó desplegar vehículos blindados del Ejército Nacional en operativos policiales. El 18 de junio el ministro del Interior, Carlos Negro, anunció un acuerdo con Defensa; Búsqueda lo publicó el 22 y el tema estalló políticamente, según Caras y Caretas, que señaló que el anuncio se hizo cinco días antes del aniversario del golpe de Estado y sin informar previamente a la bancada oficialista. A fines de junio el Consejo de Ministros analizó el marco jurídico: se trataba de unos doce vehículos para barrios con presencia de crimen organizado, bajo mando policial, en los operativos Dominio y Atenea. Orsi admitió: "Todavía no tenemos claro cuál será la forma jurídica". Los antecedentes legales son la ley 19.677, para fronteras, y la 18.717, para la custodia perimetral de cárceles, según Prensa Mercosur.',
      hallazgo: 'El obstáculo apareció en el origen del material. Los blindados Osprea Mamba Mk7 fueron donados por Estados Unidos con fondos de la Global Peace Operations Initiative (GPOI), destinados a misiones de paz. El embajador estadounidense Louis Rinaldi advirtió que "de acuerdo al convenio firmado entre ambos países, no pueden ser empleados con otros destinos", según Caras y Caretas. Infodefensa agregó el 25 de junio que los Mamba están vetados para seguridad interna por las condiciones de la donación, que Estados Unidos podría reclamar la devolución del material y que las Fuerzas Armadas no cuentan con el marco legal, la formación ni la preparación operativa para ese tipo de misiones. En el debate interno, la ministra de Defensa, Sandra Lazo, aclaró que "no son los militares en la calle", sino la cesión de vehículos; el ministro de Trabajo, Juan Castillo, calificó la imagen de "shockeante" y Cabildo Abierto pidió informes sobre base legal, cadena de mando, remuneración y porte de armas, según Prensa Mercosur.',
      statusNote: 'El 24 de julio de 2026 el Ministerio del Interior presentó el primer blindado Cóndor del Ejército —de cuatro— operado por 19 policías capacitados en el Batallón de Infantería Mecanizada n.º 15 de Florida, mientras Orsi enviaba una carta al gobierno de Estados Unidos pidiendo autorización para usar los Mamba; la respuesta seguía pendiente y, según el ministro Negro, los tres Cóndor restantes estarían patrullando en el correr de agosto de 2026, según Subrayado. En paralelo, el Ejército Nacional informó el 18 de junio de 2026 que desde mayo incrementó su despliegue en frontera con bases de patrullas, puestos de control de rutas y puestos de observación.',
      porQueImporta: 'Que un blindado donado no pueda salir a la calle define en qué se puede y en qué no se puede gastar plata pública, y qué queda inmovilizado. Además, cada vez que las Fuerzas Armadas asumen tareas civiles —fronteras, cárceles, patrullaje— el costo operativo sale del presupuesto de Defensa, que ya viene con recortes en combustible e insumos.',
      caveat: 'Los blindados llegaron por donación bilateral, no por licitación, así que no figuran como compra en el feed de datos abiertos. Sí deberían verse ahí los gastos que genera ponerlos a rodar: repuestos, neumáticos, combustible y mantenimiento del Ejército Nacional.',
    },
    en: {
      title: 'Armoured vehicles on the streets: the US-donated Mambas',
      dek: 'The government wanted to use US-donated armoured vehicles to patrol Montevideo, but the donation agreement reserves them for peacekeeping missions.',
      contexto: 'In June 2026, facing rising violence in Montevideo, Yamandú Orsi\'s government considered deploying National Army armoured vehicles in police operations. On 18 June, Interior Minister Carlos Negro announced an agreement with Defence; Búsqueda published it on the 22nd and the issue blew up politically, according to Caras y Caretas, which noted the announcement came five days before the anniversary of the 1973 coup and without prior notice to the governing bloc. In late June the Council of Ministers examined the legal framework: around a dozen vehicles for neighbourhoods with organised crime, under police command, in the Dominio and Atenea operations. Orsi admitted: "We still do not know what the legal form will be." The legal precedents are Law 19,677 for borders and Law 18,717 for prison perimeter guard duty, according to Prensa Mercosur.',
      hallazgo: 'The obstacle lay in where the equipment came from. The Osprea Mamba Mk7 armoured vehicles were donated by the United States with Global Peace Operations Initiative (GPOI) funds earmarked for peacekeeping missions. US Ambassador Louis Rinaldi warned that "under the agreement signed between the two countries, they cannot be used for other purposes", according to Caras y Caretas. Infodefensa added on 25 June that the Mambas are barred from internal security by the terms of the donation, that the United States could demand the equipment back, and that the Armed Forces have neither the legal framework nor the training or operational preparation for such missions. In the internal debate, Defence Minister Sandra Lazo clarified that "this is not soldiers on the street", but the loan of vehicles; Labour Minister Juan Castillo called the image "shocking" and Cabildo Abierto requested reports on the legal basis, chain of command, pay and carrying of weapons, according to Prensa Mercosur.',
      statusNote: 'On 24 July 2026 the Interior Ministry presented the first of four Army Cóndor armoured vehicles, operated by 19 police officers trained at Mechanised Infantry Battalion No. 15 in Florida, while Orsi sent a letter to the US government requesting authorisation to use the Mambas; the reply was still pending and, according to Minister Negro, the remaining three Cóndors would be patrolling during August 2026, according to Subrayado. In parallel, the National Army reported on 18 June 2026 that since May it had stepped up its border deployment with patrol bases, road checkpoints and observation posts.',
      porQueImporta: 'Whether a donated armoured vehicle can go out on the street determines what public money can and cannot be spent on, and what sits idle. Moreover, every time the Armed Forces take on civilian tasks — borders, prisons, patrolling — the operating cost comes out of the Defence budget, which is already being cut on fuel and supplies.',
      caveat: 'The armoured vehicles arrived through a bilateral donation, not a tender, so they do not appear as a purchase in the open-data feed. What should show up there is the spending needed to keep them running: spare parts, tyres, fuel and National Army maintenance.',
    },
  },
  {
    slug: 'misiones-de-paz-onu-ingresos-tropas',
    emoji: '🕊️',
    theme: 'defensa',
    period: '2005-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'algo más de US$ 600 millones recibidos de la ONU entre 2005 y 2016; no menos de US$ 10 millones anuales por equipamiento en el Congo',
    organisms: ['Ministerio de Defensa Nacional', 'Ejército Nacional'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Comando General de la Armada',
        'Dirección Nacional Aviación Civil e Infraestructura Aeronáut',
        'Dirección Nacional de Sanidad de las Fuerzas Armadas',
        'Comando General del Ejército',
        'Dirección General de Secretaría de Estado',
        'Comando General de la Fuerza Aérea',
        'Dirección Nacional de Meteorología',
        'Dirección General de los Servicios',
        'Estado Mayor de la Defensa',
        'Servicio de Retiros y Pensiones de las Fuerzas Armadas',
        'Ex-Dirección General Infraestructura Aeronáutica',
        'Ex-Dirección Nacional Aviación Civil e Infraestr. Aeronau.',
        'Ex-Dirección General de Aviación Civil',
      ],
      search: 'individual',
      yearFrom: 2005,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'El Observador', title: 'El Ejército perderá millones por fin de la misión de paz en Haití', url: 'https://www.elobservador.com.uy/nota/el-ejercito-perdera-millones-por-fin-de-la-mision-de-paz-en-haiti-20161229500', date: '2016-12-29' },
      { outlet: 'Radiomundo En Perspectiva', title: 'Misión de paz en el Congo: ¿De qué le sirven a Uruguay estos despliegues? ¿Deben continuar?', url: 'https://enperspectiva.uy/en-perspectiva-programa/la-mesa/mision-de-paz-en-el-congo-de-que-le-sirven-a-uruguay-estos-despliegues-deben-continuar/', date: '2024-10-25' },
      { outlet: 'Infobae', title: 'Uruguay hizo el relevo de sus cascos azules cinco meses después de lo previsto y tras presiones a la ONU', url: 'https://www.infobae.com/america/america-latina/2025/07/07/uruguay-hizo-el-relevo-de-sus-cascos-azules-cinco-meses-despues-de-lo-previsto-y-tras-presiones-a-la-onu/', date: '2025-07-07' },
      { outlet: 'Ejército Nacional', title: 'Destacado accionar militar en MONUSCO 2025', url: 'https://www.ejercito.mil.uy/index.php/2026/06/08/destacado-accionar-militar-en-monusco-2025/', date: '2026-06-08' },
    ],
    es: {
      title: 'Misiones de paz: lo que la ONU paga y lo que Uruguay pone',
      dek: 'Uruguay recibió algo más de US$ 600 millones de la ONU entre 2005 y 2016 por sus cascos azules; hoy el despliegue es menor y el relevo del Congo llegó cinco meses tarde.',
      contexto: 'Uruguay es históricamente uno de los mayores aportantes de tropas por habitante a las misiones de paz de Naciones Unidas. La ONU paga a los países contribuyentes por el personal desplegado y por el uso y desgaste del equipamiento. En Haití, cuando Uruguay tenía unos 1.100 efectivos en 2011, esos pagos llegaron a US$ 14,5 millones para salarios y otros US$ 8,2 millones por reembolso de los equipos; en 2016, con el contingente reducido, bajaron a US$ 3,7 millones, según El Observador, que consignó además que entre 2005 y 2016 Uruguay recibió "algo más de US$ 600 millones" por pagos de la ONU. En el Congo, según el entonces ministro Armando Castaingdebat citado por En Perspectiva, entraban "no menos de 10 millones de dólares" anuales por contrapartida de equipamiento.',
      hallazgo: 'El dinero explica parte de la política, y también su fragilidad. El Observador reportó que un soldado en Haití cobraba de la ONU unos US$ 1.100 mensuales por encima de un sueldo militar de alrededor de $ 16.000, y que los oficiales sumaban entre US$ 20.000 y US$ 30.000 por misión; En Perspectiva citó viáticos de la ONU de entre US$ 1.280 y US$ 4.000 mensuales según el grado, y a Castaingdebat definiendo la misión como "un pequeño colchón" para funcionarios que están entre "los peor pagos" del Estado. La contracara la mostró el relevo de 2025: unos 200 militares volvieron del Congo el 7 de julio, cinco meses después de lo previsto, y Uruguay debió presionar a Naciones Unidas —con un viaje del canciller Mario Lubetkin a Nueva York—; la ministra Sandra Lazo advirtió que, si la ONU no los traía, el país tomaría medidas y los traería igual, según Infobae. Dos militares uruguayos murieron durante esa misión.',
      statusNote: 'El Ejército Nacional informó el 8 de junio de 2026 que, en una ceremonia del 5 de junio, el secretario general de la ONU, António Guterres, entregó la Medalla del Capitán Mbaye Diagne al Valor Excepcional al sargento Matías Facundo Reyes Peñaloza, del Batallón "Uruguay IV", por evacuar a doce heridos bajo fuego en la República Democrática del Congo —apenas la cuarta entrega de esa distinción desde 2014—, y que se entregaron póstumamente medallas Dag Hammarskjöld al soldado 1.ª Rodolfo Cipriano Álvarez Suárez (fallecido el 25 de enero de 2025) y al cabo 1.ª Julio César Álvarez Cáceres (fallecido el 16 de abril de 2025). Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a esa publicación.',
      porQueImporta: 'Las misiones de paz son de las pocas actividades del Estado uruguayo que generan ingresos en dólares y financian el recambio de material militar. Pero ese ingreso depende de decisiones que Uruguay no controla —el calendario y la caja de la ONU— y descansa en soldados que van al Congo porque su sueldo local no alcanza.',
      caveat: 'Lo que la ONU reembolsa entra como ingreso presupuestal, no como contrato, así que no se ve en el feed de compras. Sí puede rastrearse el gasto previo que Uruguay hace para desplegar: raciones, uniformes, equipo individual y mantenimiento del material que después se factura a Naciones Unidas.',
    },
    en: {
      title: 'Peacekeeping: what the UN pays and what Uruguay puts in',
      dek: 'Uruguay received a little over US$600 million from the UN between 2005 and 2016 for its blue helmets; today the deployment is smaller and the Congo rotation ran five months late.',
      contexto: 'Uruguay is historically one of the largest per-capita troop contributors to United Nations peacekeeping. The UN pays contributing countries for deployed personnel and for the use and wear of equipment. In Haiti, when Uruguay had some 1,100 troops in 2011, those payments reached US$14.5 million for salaries and another US$8.2 million in equipment reimbursement; by 2016, with a reduced contingent, they fell to US$3.7 million, according to El Observador, which also reported that between 2005 and 2016 Uruguay received "a little over US$600 million" in UN payments. In Congo, according to then-minister Armando Castaingdebat quoted by En Perspectiva, "no less than 10 million dollars" a year came in as equipment reimbursement.',
      hallazgo: 'The money explains part of the policy, and also its fragility. El Observador reported that a soldier in Haiti received about US$1,100 a month from the UN on top of a military salary of around $16,000 pesos, and that officers earned between US$20,000 and US$30,000 per mission; En Perspectiva cited UN allowances of between US$1,280 and US$4,000 a month depending on rank, and quoted Castaingdebat calling the mission "a small cushion" for staff who are among the State\'s "worst paid". The flip side showed in the 2025 rotation: around 200 troops returned from Congo on 7 July, five months later than scheduled, and Uruguay had to press the United Nations — including a trip by Foreign Minister Mario Lubetkin to New York; Defence Minister Sandra Lazo warned that if the UN did not bring them home, the country would take measures and bring them back anyway, according to Infobae. Two Uruguayan soldiers died during that mission.',
      statusNote: 'The National Army reported on 8 June 2026 that, at a 5 June ceremony, UN Secretary-General António Guterres awarded the Captain Mbaye Diagne Medal for Exceptional Courage to Sergeant Matías Facundo Reyes Peñaloza, of the "Uruguay IV" Battalion, for evacuating twelve wounded under fire in the Democratic Republic of the Congo — only the fourth time the distinction has been awarded since 2014 — and that Dag Hammarskjöld medals were awarded posthumously to Private 1st Class Rodolfo Cipriano Álvarez Suárez (died 25 January 2025) and Corporal 1st Class Julio César Álvarez Cáceres (died 16 April 2025). As this file closes (August 2026) no developments after that publication are on record.',
      porQueImporta: 'Peacekeeping is one of the few Uruguayan state activities that earns dollars and funds the replacement of military equipment. But that income depends on decisions Uruguay does not control — the UN\'s calendar and its cash position — and rests on soldiers who go to Congo because their local pay is not enough.',
      caveat: 'What the UN reimburses comes in as budget revenue, not as a contract, so it does not show in the procurement feed. What can be traced is the spending Uruguay does beforehand to deploy: rations, uniforms, individual kit and maintenance of the equipment later billed to the United Nations.',
    },
  },
  {
    slug: 'sanidad-militar-control-medicamentos',
    emoji: '💊',
    theme: 'defensa',
    period: '2021-2026',
    statusKind: 'auditoria',
    status: 'auditoria',
    organisms: ['Dirección Nacional de Sanidad de las Fuerzas Armadas', 'Ministerio de Defensa Nacional'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Comando General de la Armada',
        'Dirección Nacional Aviación Civil e Infraestructura Aeronáut',
        'Dirección Nacional de Sanidad de las Fuerzas Armadas',
        'Comando General del Ejército',
        'Dirección General de Secretaría de Estado',
        'Comando General de la Fuerza Aérea',
        'Dirección Nacional de Meteorología',
        'Dirección General de los Servicios',
        'Estado Mayor de la Defensa',
        'Servicio de Retiros y Pensiones de las Fuerzas Armadas',
        'Ex-Dirección General Infraestructura Aeronáutica',
        'Ex-Dirección Nacional Aviación Civil e Infraestr. Aeronau.',
        'Ex-Dirección General de Aviación Civil',
      ],
      search: 'medicamentos',
      yearFrom: 2021,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Auditoría Interna de la Nación (MEF)', title: 'Ministerio de Defensa Nacional - Dirección Nacional Sanidad de las Fuerzas Armadas (Actuación de Seguimiento)', url: 'https://www.gub.uy/ministerio-economia-finanzas/sites/ministerio-economia-finanzas/files/documentos/publicaciones/2026_MinisterioDeDefensaNacional-DireccionNacionalDeSanidadDeLasFuerzasArmadas-DNSFFAA.pdf', date: '2026-04' },
      { outlet: 'El Observador', title: 'Auditoría en Sanidad Militar detectó falta de controles en la gestión de medicamentos', url: 'https://www.elobservador.com.uy/nota/auditoria-en-sanidad-militar-detecto-falta-de-controles-en-la-gestion-de-medicamentos-2022122518320', date: '2022-12-25' },
      { outlet: 'Ministerio de Economía y Finanzas', title: 'Publicación del informe de actuación de la AIN sobre la DNSFFAA', url: 'https://www.gub.uy/ministerio-economia-finanzas/comunicacion/publicaciones/2026-ministerio-defensa-nacional-direccion-nacional-sanidad-fuerzas', date: '2026-05-08' },
      { outlet: 'El País', title: 'Riesgos en Sanidad Militar: robos de fármacos, pérdidas por mal estado y recetas por parte de personal no autorizado', url: 'https://www.elpais.com.uy/informacion/salud/riesgos-en-sanidad-militar-robos-de-farmacos-perdidas-por-mal-estado-y-recetas-por-parte-de-personal-no-autorizado', date: '2026-05-18' },
    ],
    es: {
      title: 'Sanidad Militar: cuatro años después, los controles siguen flojos',
      dek: 'Una auditoría de 2022 halló ocho fallas en el control de medicamentos de las FF.AA.; el seguimiento de 2026 constató que solo una fue implementada del todo.',
      contexto: 'La Dirección Nacional de Sanidad de las Fuerzas Armadas atiende a unas 130.000 personas —78.000 militares en actividad y el resto familiares—, con un Hospital Central, 15 Centros de Atención Periféricos y 106 unidades militares, según El Observador. Por resolución del 2 de diciembre de 2022 la Auditoría Interna de la Nación aprobó un informe sobre la gestión de medicamentos en las etapas de recepción, custodia, distribución, dispensación y registro, para el período 1 de enero de 2021 a 31 de agosto de 2022. Concluyó que los controles en la farmacia del Hospital Central y la División Abastecimiento eran suficientes, pero que la descentralización de la gestión —los Centros de Atención Periféricos y las unidades militares— presentaba debilidades.',
      hallazgo: 'Los hallazgos de 2022 fueron concretos: en 6 de los 9 centros periféricos visitados entre enero y agosto de 2022 no se realizaron controles de stock; en la visita del 25 de julio de 2022 al CAP n.º 3, de una muestra de 43 medicamentos recontados el 91% presentaba diferencias, con saldos negativos cuyo stock físico superaba las 100 unidades y faltantes de más de 50; ninguna de las 15 farmacias de los centros periféricos estaba habilitada por el MSP —un solo químico farmacéutico tenía a cargo la dirección técnica de todas, por encima del máximo legal— y las 106 unidades militares usaban sistemas propios no comunicados ni integrados con los de la Dirección. El informe de seguimiento de la Auditoría Interna de la Nación, fechado en abril de 2026 y referido al período 1 de mayo al 30 de noviembre de 2025, concluyó que de los 8 hallazgos "1 fue implementado, 3 parcialmente implementado, 3 se encuentran en proceso y 1 no fue implementado". El que no se implementó sigue clasificado como criticidad extrema: la información sobre la gestión de medicamentos en las unidades militares. La DNSFFAA respondió que las unidades no están bajo el alcance de su Dirección General de Atención Periférica, "desconociéndose la gestión de medicamentos realizada por cada UM". Entre los riesgos vigentes la auditoría mantiene la "sustracción de medicamentos".',
      statusNote: 'El informe de seguimiento fue publicado por el Ministerio de Economía y Finanzas el 8 de mayo de 2026. La auditoría reconoce avances —controles mensuales de inventario en las farmacias de cada centro, inspecciones aleatorias y sorpresivas de la DGAP, y cambios en el sistema informático que permitirían la trazabilidad de cada medicamento— y señala que la incorporación de químicos farmacéuticos depende de artículos agregados a la Ley de Presupuesto Nacional 2025-2029, cuyos efectos, de concretarse, serían a futuro. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores.',
      porQueImporta: 'Son medicamentos comprados con dinero público para 130.000 usuarios: militares, jubilados, cónyuges e hijos. Sin control de stock no se sabe cuánto se pierde por vencimiento, cuánto se desvía y cuánto se compra de más. La auditoría no afirma que haya robo; anota que el riesgo de sustracción sigue vigente y que el sistema no permitiría detectarlo.',
      caveat: 'Las compras de medicamentos e insumos de la DNSFFAA sí se tramitan por Compras Estatales, así que los llamados y adjudicaciones son rastreables en el feed. Lo que el feed no muestra es qué pasó con el remedio después de comprado: eso es justamente lo que la auditoría dice que no se puede seguir.',
    },
    en: {
      title: 'Military Health: four years on, the controls are still weak',
      dek: 'A 2022 audit found eight failings in the armed forces\' medicine controls; the 2026 follow-up found only one had been fully implemented.',
      contexto: 'The National Health Directorate of the Armed Forces serves around 130,000 people — 78,000 serving military personnel and the rest dependants — with a Central Hospital, 15 Peripheral Care Centres and 106 military units, according to El Observador. By resolution of 2 December 2022 the National Internal Audit Office approved a report on medicine management across receipt, custody, distribution, dispensing and recording, for the period 1 January 2021 to 31 August 2022. It concluded that controls at the Central Hospital pharmacy and the Supply Division were adequate, but that decentralised management — the Peripheral Care Centres and the military units — showed weaknesses.',
      hallazgo: 'The 2022 findings were concrete: in 6 of the 9 peripheral centres visited between January and August 2022 no stock checks were carried out; at the 25 July 2022 visit to Centre No. 3, of a sample of 43 medicines recounted, 91% showed discrepancies, with negative balances whose physical stock exceeded 100 units and shortfalls of more than 50; none of the 15 peripheral-centre pharmacies was licensed by the Health Ministry — a single pharmacist held technical charge of all of them, above the legal maximum — and the 106 military units used their own systems, not connected or integrated with the Directorate\'s. The National Internal Audit Office\'s follow-up report, dated April 2026 and covering 1 May to 30 November 2025, concluded that of the 8 findings "1 was implemented, 3 partially implemented, 3 are in progress and 1 was not implemented". The one not implemented remains classified as extreme criticality: information on medicine management in the military units. The Directorate replied that the units fall outside the remit of its General Directorate of Peripheral Care, so "the medicine management carried out by each unit is unknown". Among the standing risks the audit still lists "theft of medicines".',
      statusNote: 'The follow-up report was published by the Ministry of Economy and Finance on 8 May 2026. The audit acknowledges progress — monthly inventory checks at each centre\'s pharmacy, random surprise inspections by the DGAP, and changes to the IT system that would allow traceability of each medicine — and notes that hiring pharmacists depends on articles added to the 2025-2029 National Budget Act, whose effects, if they materialise, would be in the future. As this file closes (August 2026) no later developments are on record.',
      porQueImporta: 'These are medicines bought with public money for 130,000 users: serving personnel, retirees, spouses and children. Without stock control there is no way to know how much is lost to expiry, how much goes astray and how much is over-ordered. The audit does not claim there is theft; it records that the risk of theft is still live and that the system would not be able to detect it.',
      caveat: 'The Directorate\'s purchases of medicines and supplies do go through Compras Estatales, so tenders and awards are traceable in the feed. What the feed does not show is what happened to the medicine after it was bought: that is exactly what the audit says cannot be tracked.',
    },
  },
]
