import type { CasoDef } from '../types'

/**
 * deporte-y-cultura — 9 dossiers, 6 of them with a live cross-reference.
 *
 * Every source URL was fetched and every query was resolved against the live
 * collection before this file was committed (scripts/verify-casos.ts re-checks
 * both). A caso with no `query` is not a gap in the research: its money does
 * not travel through the Compras Estatales feed at all, which `feedCoverage`
 * records and the page states outright.
 */
export const CASOS_DEPORTE_Y_CULTURA: CasoDef[] = [
  {
    slug: 'reforma-estadio-centenario-mundial-2030',
    emoji: '🏟️',
    theme: 'deporte-y-cultura',
    period: '2024-2026',
    statusKind: 'gestion',
    status: 'inconcluso',
    amountReported: 'US$ 120 a 180 millones (estimaciones sucesivas del costo de la obra publicadas entre enero de 2025 y julio de 2026)',
    organisms: ['Intendencia de Montevideo', 'Secretaría Nacional del Deporte'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Intendencia de Montevideo',
        'Secretaría Nacional del Deporte',
      ],
      search: 'centenario',
      yearFrom: 2024,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Búsqueda', title: 'El Estadio Centenario para 2030: US$ 160 millones y la posibilidad de que lleve el nombre de una empresa', url: 'https://www.busqueda.com.uy/deportes/el-estadio-centenario-2030-us-160-millones-y-la-posibilidad-que-lleve-el-nombre-una-empresa-n5395179', date: '2025-01-02' },
      { outlet: 'Búsqueda', title: 'La reforma del Estadio Centenario, quieta: el gobierno y la AUF, incomunicados y pendientes de la FIFA', url: 'https://www.busqueda.com.uy/deportes/la-reforma-del-estadio-centenario-quieta-el-gobierno-y-la-auf-incomunicados-y-pendientes-la-fifa-n5409003', date: '2026-01-18' },
      { outlet: 'Infobae', title: 'Mundial 2030: la reforma del Estadio Centenario costará USD 120 millones y Orsi busca inversores para financiarla', url: 'https://www.infobae.com/america/america-latina/2026/06/09/mundial-2030-la-reforma-del-estadio-centenario-costara-usd-120-millones-y-orsi-busca-inversores-para-financiarla/', date: '2026-06-09' },
      { outlet: 'Búsqueda', title: 'Mundial 2030: la mayor productora de eventos del mundo analiza participar en la reforma del Estadio Centenario', url: 'https://www.busqueda.com.uy/deportes/mundial-2030-la-mayor-productora-eventos-del-mundo-analiza-participar-la-reforma-del-estadio-centenario-n5415552', date: '2026-07-27' },
    ],
    es: {
      title: 'El Centenario para 2030: sin licitación ni financiamiento definido',
      dek: 'La obra que Uruguay debe encarar para el Mundial 2030 fue estimada entre US$ 120 y US$ 180 millones según el momento; a agosto de 2026 no hay pliego ni fuente de fondos cerrada.',
      contexto: 'El Estadio Centenario es gestionado por la Comisión Administradora del Field Oficial (CAFO), cuyo directorio de seis delegados se reparte en partes iguales entre la Intendencia de Montevideo y la Asociación Uruguaya de Fútbol (AUF), tres representantes cada una, según informó Búsqueda en enero de 2025. Uruguay albergará allí un partido del Mundial 2030, lo que obliga a adecuar el estadio: el mismo semanario informó que el aforo pasaría de 60.000 a 63.000 espectadores. Las cifras manejadas para la obra se fueron moviendo entre enero de 2025 y julio de 2026 sin que ninguna quedara firme.',
      hallazgo: 'Lo cuestionado aquí no es un contrato sino su ausencia. Búsqueda informó en enero de 2025 que la licitación estaba prevista para la segunda mitad de ese año, junto con la posibilidad de vender los derechos de nombre del estadio y de que un privado administrara parte de los servicios; el llamado no se concretó. En enero de 2026 el semanario publicó que la reforma estaba «quieta», que el último contacto entre el presidente Yamandú Orsi y el presidente de la AUF, Ignacio Alonso, había sido en setiembre de 2025 en Nueva York, y que el costo se estimaba en US$ 180 millones; el canciller Mario Lubetkin sostuvo allí que «un solo partido de fútbol no puede financiar en absoluto un emprendimiento de este tipo». En junio de 2026, según Infobae, la obra se estimaba en US$ 120 millones, Orsi citó la posición del presidente de la FIFA —«es impensable que un país ponga todo el dinero para hacer un estadio»— y el gobierno sostuvo que no gastará «un peso», buscando inversores privados y de otros países. En julio de 2026 Búsqueda informó que la inversión volvía a estimarse en US$ 160 millones, que «un porcentaje muy menor de los recursos» provendría de FIFA y Conmebol, y que se exploraban privados —entre ellos la productora Live Nation Entertainment— además de un acuerdo de cooperación deportiva firmado con Arabia Saudita en junio de 2026.',
      statusNote: 'A agosto de 2026 no consta pliego publicado ni financiamiento cerrado. Según Infobae (9 de junio de 2026), Orsi creó una comisión con representantes de la AUF, la Intendencia de Montevideo y el gobierno nacional para supervisar la obra y su financiamiento. La información más reciente entre las fuentes de esta ficha es de Búsqueda del 27 de julio de 2026, que mantiene la estimación en US$ 160 millones sin definición de quién paga. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a esa fecha.',
      porQueImporta: 'El estadio lo cogestiona la Intendencia de Montevideo: todo aporte público saldría de la comuna o del Presupuesto Nacional. Cuanto más tarde en definirse el esquema, menos margen queda para licitar con competencia real y más riesgo hay de contratar contra reloj, que es cuando los precios suben y los controles se relajan.',
      caveat: 'Mientras no haya licitación no existen contratos de obra en el sistema de compras estatales para cruzar. Lo que sí puede rastrearse son las compras corrientes de mantenimiento del estadio y las consultorías y estudios previos contratados por la Intendencia de Montevideo.',
    },
    en: {
      title: 'The Centenario for 2030: no tender, no financing in place',
      dek: 'The refit Uruguay must undertake for the 2030 World Cup has been estimated at between US$120m and US$180m depending on the moment; as of August 2026 there is no tender and no confirmed source of funds.',
      contexto: 'The Estadio Centenario is run by CAFO (Comisión Administradora del Field Oficial), whose six-delegate board is split evenly between the Municipality of Montevideo and the Uruguayan Football Association (AUF), three representatives each, as Búsqueda reported in January 2025. Uruguay will host a 2030 World Cup match there, which forces an upgrade: the same weekly reported capacity would go from 60,000 to 63,000. The figures quoted for the work kept shifting between January 2025 and July 2026 without any becoming firm.',
      hallazgo: 'What is questioned here is not a contract but its absence. Búsqueda reported in January 2025 that the tender was planned for the second half of that year, alongside the option of selling the stadium\'s naming rights and letting a private party run part of its services; the call never happened. In January 2026 the weekly reported the project was "stalled", that the last contact between President Yamandú Orsi and AUF president Ignacio Alonso had been in September 2025 in New York, and that the cost was estimated at US$180m; foreign minister Mario Lubetkin said there that "a single football match cannot possibly finance an undertaking of this kind". In June 2026, according to Infobae, the work was estimated at US$120m, Orsi cited the FIFA president\'s position — "it is unthinkable for a country to put up all the money to build a stadium" — and the government said it would not spend "a peso", seeking private investors and other countries instead. In July 2026 Búsqueda reported the investment was again estimated at US$160m, that "a very minor percentage of the resources" would come from FIFA and Conmebol, and that private parties were being explored — among them the promoter Live Nation Entertainment — plus a sports cooperation agreement signed with Saudi Arabia in June 2026.',
      statusNote: 'As of August 2026 there is no published tender document and no closed financing. According to Infobae (9 June 2026), Orsi created a commission with representatives from the AUF, the Municipality of Montevideo and the national government to oversee the work and its funding. The most recent information among this file\'s sources is Búsqueda\'s of 27 July 2026, which keeps the estimate at US$160m with no decision on who pays. As of this file\'s closing (August 2026) there are no developments after that date.',
      porQueImporta: 'The stadium is co-managed by the Municipality of Montevideo: any public contribution would come out of the city or the National Budget. The later the funding scheme is defined, the less room there is to tender with real competition, and the greater the risk of contracting against the clock — which is when prices rise and controls loosen.',
      caveat: 'With no tender there are no works contracts in the state procurement system to cross-reference. What can be traced are the stadium\'s routine maintenance purchases and the preliminary studies and consultancies contracted by the Municipality of Montevideo.',
    },
  },
  {
    slug: 'garantias-fiscales-fifa-mundial-2030',
    emoji: '🧾',
    theme: 'deporte-y-cultura',
    period: '2024-2026',
    statusKind: 'debate',
    status: 'debate',
    amountReported: 'US$ 180 millones (costo estimado de la reforma del Centenario sobre la que la AUF pidió exonerar el IVA, enero de 2026)',
    organisms: ['Intendencia de Montevideo', 'Secretaría Nacional del Deporte'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'Infobae', title: 'Luis Lacalle Pou acelera la aprobación de las garantías exigidas por FIFA para el Mundial 2030', url: 'https://www.infobae.com/america/america-latina/2024/07/10/luis-lacalle-pou-acelera-la-aprobacion-de-las-garantias-exigidas-por-fifa-para-el-mundial-2030/', date: '2024-07-10' },
      { outlet: 'Búsqueda', title: 'Mundial 2030: la FIFA aprobará las garantías que presentó Uruguay y anunciará las sedes el 11 de diciembre', url: 'https://www.busqueda.com.uy/deportes/mundial-2030-la-fifa-aprobara-las-garantias-que-presento-uruguay-y-anunciara-las-sedes-el-11-diciembre-n5394605', date: '2024-11-27' },
      { outlet: 'Búsqueda', title: 'Yamandú Orsi recibió a Alonso y Ache, que le pidieron exoneraciones impositivas a la reforma del Centenario', url: 'https://www.busqueda.com.uy/deportes/yamandu-orsi-recibio-alonso-y-ache-que-le-pidieron-exoneraciones-impositivas-la-reforma-del-centenario-n5409486', date: '2026-01-30' },
    ],
    es: {
      title: 'Las garantías que Uruguay firmó para ser sede del Mundial 2030',
      dek: 'Catorce ministerios firmaron declaraciones fiscales, laborales y comerciales ante la FIFA, y la Intendencia de Montevideo se comprometió a no cobrarle ningún tributo.',
      contexto: 'Para que la FIFA confirmara a Uruguay como sede de un partido del Mundial 2030, el país debió entregar un paquete de garantías estatales. Infobae informó el 10 de julio de 2024 que el entonces presidente Luis Lacalle Pou pidió acelerar la firma de documentos que comprometen al Estado a cumplir reglas administrativas, financieras y legales fijadas por la FIFA, con declaraciones de los 14 ministerios en «asuntos fiscales, laborales, de infraestructura, inmigración, comerciales y de propiedad intelectual, de seguridad y ambientales». Según ese mismo artículo, Lacalle Pou se comprometió además a que «el Poder Ejecutivo impulsará las leyes que sean necesarias» para cumplir con esas exigencias, y toda la documentación debía completarse dentro de julio de 2024.',
      hallazgo: 'Según Búsqueda (27 de noviembre de 2024), entre esas garantías la Intendencia de Montevideo se comprometió a que «no le cobrará a la FIFA ningún tipo de impuesto, derecho o gravamen», y la exoneración alcanza a todas las actividades directa o indirectamente vinculadas a la organización del torneo, además de la formalización, ejecución o rescisión del propio acuerdo. La comuna aportó esa garantía por ser quien administra el Estadio Centenario, donde Uruguay jugará su único partido el 8 de junio de 2030. Los documentos de candidatura fueron entregados en julio de 2024 al presidente de la FIFA, Gianni Infantino, por el presidente de la AUF, Ignacio Alonso, y el secretario nacional del Deporte, Sebastián Bauzá. El pedido de beneficios fiscales siguió creciendo: Búsqueda informó el 30 de enero de 2026 que Alonso y el dirigente Eduardo Ache pidieron al presidente Yamandú Orsi declarar de interés nacional la reforma del Centenario —proyectada en US$ 180 millones—, exonerar el IVA de los materiales de construcción y compensar los aportes a la seguridad social con certificados de crédito fiscal.',
      statusNote: 'Las garantías fueron presentadas y, según Búsqueda (27 de noviembre de 2024), la FIFA se aprestaba a aprobarlas y a anunciar las sedes el 11 de diciembre de 2024. Sobre el pedido de exoneraciones para la obra del Centenario, la misma publicación informó el 30 de enero de 2026 que Orsi «escuchó los argumentos, pero no ofreció una respuesta», y que la AUF planeaba insistir ante el ministro de Economía, Gabriel Oddone. No consta una estimación oficial publicada de cuánta recaudación resigna el Estado uruguayo por estos compromisos. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a enero de 2026.',
      porQueImporta: 'Una exoneración no aparece como gasto en ningún presupuesto, pero es plata que el Estado deja de cobrar: menos IVA, menos tributos departamentales, menos aportes. Ese hueco lo cubren el resto de los contribuyentes. Conocer el monto resignado es la única forma de saber cuánto cuesta realmente ser sede.',
      caveat: 'Las exoneraciones tributarias y las garantías soberanas no pasan por el sistema de compras estatales: no hay contrato ni orden de compra que las registre. Sólo el gasto operativo asociado a la organización sería visible en los datos abiertos.',
    },
    en: {
      title: 'The guarantees Uruguay signed to host the 2030 World Cup',
      dek: 'Fourteen ministries signed fiscal, labour and commercial declarations to FIFA, and the Municipality of Montevideo undertook not to charge it any tax at all.',
      contexto: 'For FIFA to confirm Uruguay as host of a 2030 World Cup match, the country had to hand over a package of state guarantees. Infobae reported on 10 July 2024 that then-president Luis Lacalle Pou asked for the signing to be sped up on documents committing the State to comply with administrative, financial and legal rules set by FIFA, with declarations from all 14 ministries on "fiscal, labour, infrastructure, immigration, commercial and intellectual property, security and environmental matters". According to that same article, Lacalle Pou also committed that "the Executive will promote whatever laws are necessary" to meet those demands, and all the paperwork had to be completed within July 2024.',
      hallazgo: 'According to Búsqueda (27 November 2024), among those guarantees the Municipality of Montevideo undertook that it "will not charge FIFA any kind of tax, duty or levy", with the exemption covering all activities directly or indirectly linked to organising the tournament, plus the formalisation, execution or termination of the agreement itself. The city provided that guarantee because it administers the Estadio Centenario, where Uruguay will play its single match on 8 June 2030. The candidacy documents were delivered in July 2024 to FIFA president Gianni Infantino by AUF president Ignacio Alonso and National Sports Secretary Sebastián Bauzá. The requests for tax breaks kept growing: Búsqueda reported on 30 January 2026 that Alonso and board member Eduardo Ache asked President Yamandú Orsi to declare the Centenario refit — projected at US$180m — a matter of national interest, to exempt VAT on construction materials, and to offset social security contributions with tax credit certificates.',
      statusNote: 'The guarantees were submitted and, according to Búsqueda (27 November 2024), FIFA was set to approve them and announce the host venues on 11 December 2024. On the request for exemptions for the Centenario works, the same outlet reported on 30 January 2026 that Orsi "listened to the arguments but offered no response", and that the AUF planned to press the case with Economy Minister Gabriel Oddone. No official published estimate exists of how much revenue the Uruguayan State forgoes through these commitments. As of this file\'s closing (August 2026) there are no developments after January 2026.',
      porQueImporta: 'An exemption never shows up as spending in any budget, but it is money the State stops collecting: less VAT, fewer departmental taxes, fewer contributions. That gap is covered by everyone else who pays tax. Knowing the forgone amount is the only way to know what hosting really costs.',
      caveat: 'Tax exemptions and sovereign guarantees do not pass through the state procurement system: no contract or purchase order records them. Only the operating spend associated with organising the event would be visible in open data.',
    },
  },
  {
    slug: 'antel-arena-gestion-itc-observada',
    emoji: '🎤',
    theme: 'deporte-y-cultura',
    period: '2025-2026',
    statusKind: 'auditoria',
    status: 'auditoria',
    amountReported: 'US$ 96.000 anuales más IVA (precio base del contrato de gestión con ITC, según Búsqueda)',
    organisms: ['Administración Nacional de Telecomunicaciones (ANTEL)'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Administración Nacional de Telecomunicaciones',
      ],
      yearFrom: 2025,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'la diaria', title: 'Antel Arena pasará a ser gestionado por una subsidiaria de la empresa estatal y estiman un ahorro de cerca de 500.000 dólares anuales', url: 'https://ladiaria.com.uy/politica/articulo/2025/10/antel-arena-pasara-a-ser-gestionado-por-una-subsidiaria-de-la-empresa-estatal-y-estiman-un-ahorro-de-cerca-de-500000-dolares-anuales/', date: '2025-10-13' },
      { outlet: 'El Observador', title: 'Gestión del Antel Arena pasará a manos de una subsidiaria estatal: para Raffo es una decisión «muy temeraria»', url: 'https://www.elobservador.com.uy/nacional/gestion-del-antel-arena-pasara-manos-una-subsidiaria-estatal-raffo-es-una-decision-muy-temeraria-n6020623', date: '2025-10-13' },
      { outlet: 'Radio Monte Carlo', title: 'El Tribunal de Cuentas observó al contrato con ITC, para que empiece a gestionar el Antel Arena', url: 'https://www.radiomontecarlo.com.uy/2025/11/17/nacionales/el-tribunal-de-cuentas-observo-al-contrato-con-itc-para-que-empiece-a-gestionar-el-antel-arena/', date: '2025-11-17' },
      { outlet: 'Búsqueda', title: 'El contrato del Antel Arena con ITC activa un debate parlamentario sobre gestión y costos', url: 'https://www.busqueda.com.uy/informacion/el-contrato-del-antel-arena-itc-activa-un-debate-parlamentario-gestion-y-costos-n5408021', date: '2025-12-18' },
    ],
    es: {
      title: 'El Tribunal de Cuentas observó el nuevo gestor del Antel Arena',
      dek: 'Antel pasó la operación del estadio a su propia subsidiaria ITC por US$ 96.000 anuales más IVA; el Tribunal de Cuentas observó el contrato y el directorio reiteró el gasto igual.',
      contexto: 'El Antel Arena es el principal recinto de espectáculos de Montevideo y pertenece a Antel, la empresa estatal de telecomunicaciones. Hasta el 31 de diciembre de 2025 lo operó AEG Facilities Uruguay, integrada al grupo internacional ASM Global. En octubre de 2025 el directorio de Antel resolvió, por mayoría, entregar la gestión a ITC, una de sus tres subsidiarias, una vez vencido ese contrato. Según la diaria, se estimó un ahorro cercano a los US$ 500.000 anuales.',
      hallazgo: 'Según Búsqueda (18 de diciembre de 2025), el contrato con ITC fija un precio base de US$ 96.000 anuales más IVA, con un sistema de incentivos y penalidades que puede moverlo hasta un 25% según indicadores de desempeño, por dos años con prórrogas anuales de hasta tres más —un vínculo de hasta cinco años— y prevé que los 17 trabajadores que estaban bajo AEG pasen a ITC. El 5 de noviembre de 2025, informó el mismo semanario, el Tribunal de Cuentas observó el contrato por «vulneración del principio de especialidad»: puso en duda que gestionar un estadio de espectáculos se ajuste a los cometidos de un servicio descentralizado como Antel. El directorio del ente decidió reiterar el gasto, informó Radio Monte Carlo el 17 de noviembre. Búsqueda publicó además los números del recinto: una pérdida de US$ 3.725.527 en 2024 y una proyección de US$ 4.674.948 para 2025. El diputado nacionalista Álvaro Dastugue cuestionó que «una subsidiaria sin trayectoria en la administración de grandes arenas» pueda rendir más que un operador internacional especializado.',
      statusNote: 'La decisión se tomó por mayoría del directorio: la directora opositora Laura Raffo votó en contra, calificó la resolución de «muy temeraria», dijo que presenta «riesgos absolutamente innecesarios» y criticó que no se hiciera un llamado competitivo, según El Observador y la diaria. El vicepresidente de Antel, Pablo Álvarez, respondió que la decisión no afecta las operaciones centrales del ente y puede habilitar propuestas culturales de menor costo. La observación del Tribunal de Cuentas no anula el contrato: el organismo controla y observa, y el ente puede reiterar el gasto, como hizo. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a diciembre de 2025 entre las fuentes verificadas.',
      porQueImporta: 'El Antel Arena arrastra pérdidas millonarias y las cubre una empresa pública: en última instancia, la tarifa de telefonía e internet que pagan los uruguayos. Quién lo gestiona, con qué contrato y con qué controles define si esa pérdida se reduce o se agranda, y si el ente estatal está haciendo algo para lo que fue creado.',
      caveat: 'El contrato es entre Antel y una subsidiaria propia, por lo que puede no aparecer como una adjudicación común en el sistema de compras estatales. Lo que sí es rastreable es el gasto corriente del Antel Arena en servicios, producción y mantenimiento.',
    },
    en: {
      title: 'The Court of Accounts flagged Antel Arena\'s new operator',
      dek: 'Antel handed the venue\'s operation to its own subsidiary ITC for US$96,000 a year plus VAT; the Court of Accounts objected and the board reiterated the spending anyway.',
      contexto: 'Antel Arena is Montevideo\'s main entertainment venue and belongs to Antel, the state telecoms company. Until 31 December 2025 it was run by AEG Facilities Uruguay, part of the international group ASM Global. In October 2025 Antel\'s board resolved by majority to hand management to ITC, one of its three subsidiaries, once that contract expired. According to la diaria, savings of close to US$500,000 a year were estimated.',
      hallazgo: 'According to Búsqueda (18 December 2025), the ITC contract sets a base price of US$96,000 a year plus VAT, with a system of incentives and penalties that can move it by up to 25% against performance indicators, running two years with annual extensions of up to three more — a relationship of up to five years — and provides for the 17 staff who worked under AEG to move to ITC. On 5 November 2025, the same weekly reported, the Court of Accounts objected to the contract for "breach of the principle of speciality": it questioned whether running an entertainment venue fits the remit of a decentralised service such as Antel. The board decided to reiterate the spending, Radio Monte Carlo reported on 17 November. Búsqueda also published the venue\'s figures: a loss of US$3,725,527 in 2024 and a projected US$4,674,948 for 2025. National Party MP Álvaro Dastugue questioned whether "a subsidiary with no track record in running large arenas" could outperform a specialised international operator.',
      statusNote: 'The decision was taken by a board majority: opposition director Laura Raffo voted against, called the resolution "very reckless", said it carries "absolutely unnecessary risks" and criticised the absence of a competitive tender, according to El Observador and la diaria. Antel vice-president Pablo Álvarez replied that the decision does not affect the company\'s core operations and could enable lower-cost cultural programming. The Court of Accounts\' objection does not void the contract: the body audits and objects, and the entity may reiterate the spending, as it did. As of this file\'s closing (August 2026) there are no developments after December 2025 among the verified sources.',
      porQueImporta: 'Antel Arena carries losses in the millions and a state-owned company absorbs them — ultimately through the phone and internet bills Uruguayans pay. Who runs it, under what contract and with what oversight determines whether that loss shrinks or grows, and whether the state company is doing something it was created for.',
      caveat: 'The contract is between Antel and its own subsidiary, so it may not appear as an ordinary award in the state procurement system. What is traceable is the Antel Arena\'s running spend on services, production and maintenance.',
    },
  },
  {
    slug: 'caches-artistas-intendencia-montevideo',
    emoji: '🎫',
    theme: 'deporte-y-cultura',
    period: '2022-2023',
    statusKind: 'debate',
    status: 'debate',
    amountReported: 'US$ 256.478 a Lali Espósito y US$ 62.387 a Daniela Mercury (festival Acá estamos, marzo de 2023): US$ 318.865 en total',
    organisms: ['Intendencia de Montevideo'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Intendencia de Montevideo',
      ],
      search: 'espectaculo',
      yearFrom: 2022,
      yearTo: 2023,
    },
    investigationPath: '/investigaciones/intendencia-montevideo',
    sources: [
      { outlet: 'El Observador', title: 'Montevideo Late: cuánto dinero pagó la Intendencia de Montevideo a No Te Va Gustar, La Vela Puerca y El Kuelgue', url: 'https://www.elobservador.com.uy/nota/montevideo-late-cuanto-dinero-pago-la-intendencia-de-montevideo-a-no-te-va-gustar-la-vela-puerca-y-el-kuelgue-2022122016363', date: '2022-12-20' },
      { outlet: 'El Observador', title: 'Lali y Daniela Mercury en Uruguay: la Intendencia de Montevideo pagará más de US$ 300 mil por las artistas para el festival Acá Estamos', url: 'https://www.elobservador.com.uy/nota/cuanto-pago-la-intendencia-de-montevideo-por-traer-a-lali-esposito-y-a-daniela-mercury--202331416493', date: '2023-03-15' },
      { outlet: 'Infobae', title: 'Críticas a la intendenta de Montevideo por contratar a Lali Espósito por más de 250 mil dólares', url: 'https://www.infobae.com/america/america-latina/2023/03/15/criticas-a-la-intendenta-de-montevideo-por-contratar-a-lali-esposito-por-mas-de-250-mil-dolares/', date: '2023-03-15' },
      { outlet: 'La Nación', title: 'Revuelo y críticas en Uruguay: revelan cuánto le pagará la intendencia de Montevideo a Lali Espósito', url: 'https://www.lanacion.com.ar/el-mundo/revuelo-y-criticas-en-uruguay-revelan-cuanto-le-pagara-la-intendencia-de-montevideo-a-lali-esposito-nid14032023/', date: '2023-03-14' },
    ],
    es: {
      title: 'Los cachés que la Intendencia de Montevideo paga por sus festivales',
      dek: 'US$ 256.478 a Lali Espósito y US$ 62.387 a Daniela Mercury para el festival «Acá estamos»; la propia comuna admitió que la resolución no consignaba el gasto total.',
      contexto: 'La Intendencia de Montevideo organiza festivales masivos y contrata artistas nacionales e internacionales con presupuesto departamental. En diciembre de 2022 realizó «Montevideo Late», que según El Observador convocó a más de 140.000 personas a lo largo del fin de semana. En marzo de 2023, bajo la intendenta Carolina Cosse, organizó el festival «Acá estamos» en la rambla de Punta Carretas, en el marco del Mes de la Mujer, con Lali Espósito y Daniela Mercury como cabezas de cartel y entradas a 400 pesos vendidas por Tickantel, según La Nación y El Observador.',
      hallazgo: 'El Observador informó el 15 de marzo de 2023 que la Intendencia pagó US$ 256.478 a Lali Espósito y US$ 62.387 a Daniela Mercury, US$ 318.865 en total. Sobre la publicación de los contratos, la propia comuna señaló que «en la parte resolutiva se omitió consignar a cuánto asciende el gasto total de la contratación». Infobae y La Nación replicaron el caso los días 14 y 15 de marzo. Para Montevideo Late, El Observador había informado el 20 de diciembre de 2022 pagos de US$ 65.000 a No Te Va Gustar, US$ 40.000 a La Vela Puerca y US$ 12.000 a El Kuelgue, además del compromiso de exonerar el 100% del impuesto a los espectáculos públicos a La Vela Puerca por su show del 19 de noviembre de 2022 en el Velódromo. El edil nacionalista Javier Barrios Bove habló de «pan y circo» y el edil Diego Rodríguez preguntó qué le aporta ese gasto a Montevideo; críticos citados por Infobae señalaron que la ciudad «se inunda cuando llueve, está muy sucia, tiene calles rotas».',
      statusNote: 'La Intendencia justificó el gasto: dijo que buscaba «romper los paradigmas tradicionales y promover la representatividad, el liderazgo y la igualdad de oportunidades en la cultura», y fundamentó la elección de Espósito en su proyección internacional y su defensa de la igualdad de género, y la de Mercury en su trabajo filantrópico y su activismo feminista y LGBT, según El Observador e Infobae. No consta, entre las fuentes verificadas, denuncia penal ni observación del Tribunal de Cuentas sobre estos contratos: el cuestionamiento fue político y de transparencia. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a la cobertura de marzo de 2023.',
      porQueImporta: 'Estos festivales los financia el contribuyente montevideano con la contribución inmobiliaria y los tributos departamentales: aun con entradas a 400 pesos, el grueso del costo es presupuesto público. Saber cuánto cobra cada artista, y saberlo antes del show y no después, es lo que permite discutir si esa plata está bien puesta frente a saneamiento, alumbrado o calles.',
      caveat: 'Los cachés se contratan de forma directa por la naturaleza del servicio artístico y pueden figurar en compras estatales a nombre de la productora y no del artista. El impuesto a los espectáculos públicos exonerado no aparece como gasto en ningún registro de compras.',
    },
    en: {
      title: 'What Montevideo\'s city hall pays performers at its festivals',
      dek: 'US$256,478 to Lali Espósito and US$62,387 to Daniela Mercury for the "Acá estamos" festival; the city itself admitted the resolution left out the total cost.',
      contexto: 'The Municipality of Montevideo stages mass festivals and contracts local and international performers using departmental budget. In December 2022 it held "Montevideo Late", which according to El Observador drew more than 140,000 people across the weekend. In March 2023, under mayor Carolina Cosse, it staged the "Acá estamos" festival on the Punta Carretas waterfront as part of Women\'s Month, headlined by Lali Espósito and Daniela Mercury, with tickets at 400 pesos sold through Tickantel, according to La Nación and El Observador.',
      hallazgo: 'El Observador reported on 15 March 2023 that the municipality paid US$256,478 to Lali Espósito and US$62,387 to Daniela Mercury, US$318,865 in total. On the publication of the contracts, the city itself noted that "the operative section failed to state the total cost of the contract". Infobae and La Nación picked up the story on 14 and 15 March. For Montevideo Late, El Observador had reported on 20 December 2022 payments of US$65,000 to No Te Va Gustar, US$40,000 to La Vela Puerca and US$12,000 to El Kuelgue, plus a commitment to waive 100% of the public entertainment tax for La Vela Puerca\'s 19 November 2022 show at the Velodrome. National Party councillor Javier Barrios Bove called it "bread and circuses" and councillor Diego Rodríguez asked what the spending brings Montevideo; critics quoted by Infobae noted the city "floods when it rains, is very dirty, has ruined streets".',
      statusNote: 'The municipality defended the spending: it said the aim was to "break traditional paradigms and promote representation, leadership and equal opportunity in culture", and grounded the choice of Espósito in her international standing and advocacy for gender equality, and that of Mercury in her philanthropic work and feminist and LGBT activism, according to El Observador and Infobae. Among the verified sources there is no record of a criminal complaint or a Court of Accounts objection over these contracts: the challenge was political and about transparency. As of this file\'s closing (August 2026) there are no developments after the March 2023 coverage.',
      porQueImporta: 'These festivals are financed by Montevideo\'s taxpayers through property and departmental taxes: even with 400-peso tickets, the bulk of the cost is public budget. Knowing what each performer charges — and knowing it before the show, not after — is what makes it possible to debate whether that money is well spent against sewerage, street lighting or road repairs.',
      caveat: 'Performer fees are contracted directly because of the artistic nature of the service, and may appear in procurement data under the promoter\'s name rather than the artist\'s. The waived public entertainment tax appears as spending in no purchasing record at all.',
    },
  },
  {
    slug: 'publicidad-turismo-cardoso-kirma',
    emoji: '📺',
    theme: 'deporte-y-cultura',
    period: '2020-2024',
    statusKind: 'judicial',
    status: 'archivo',
    amountReported: 'US$ 280.000 (oferta de Kirma que la empresa terminó retirando; el contrato nunca se concretó)',
    organisms: ['Ministerio de Turismo'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Dirección Nacional de Turismo',
      ],
      search: 'publicidad',
      yearFrom: 2020,
      yearTo: 2024,
    },
    investigationPath: '/pauta',
    sources: [
      { outlet: 'Teledoce', title: 'Young & Rubicam afirma que oferta de la empresa Kirma llegó a través de dos asesores del exministro Cardoso', url: 'https://www.teledoce.com/telemundo/nacionales/young-rubicam-afirma-que-oferta-de-la-empresa-kirma-llego-a-traves-de-dos-asesores-del-exministro-cardoso/', date: '2021-10-04' },
      { outlet: 'la diaria', title: 'Young & Rubicam: «A Kirma no la conocíamos; se incluyó en la propuesta a pedido del ministerio»', url: 'https://ladiaria.com.uy/politica/articulo/2021/11/young-amp-rubicam-a-kirma-no-la-conociamos-se-incluyo-en-la-propuesta-a-pedido-del-ministerio-de-turismo/', date: '2021-11-09' },
      { outlet: 'El Observador', title: 'Fiscalía archivó la denuncia contra exministro Cardoso pero mantiene la causa Kirma', url: 'https://www.elobservador.com.uy/nota/fiscalia-archivo-la-denuncia-contra-exministro-cardoso-pero-mantiene-la-causa-kirma-2022125123431', date: '2022-12-05' },
      { outlet: 'Montevideo Portal', title: 'Fiscal archivó investigación sobre Kirma y exasesor de Germán Cardoso en Turismo', url: 'https://www.montevideo.com.uy/Noticias/Fiscal-archivo-investigacion-sobre-Kirma-y-exasesor-de-German-Cardoso-en-Turismo-uc896259', date: '2024-08-05' },
    ],
    es: {
      title: 'La publicidad del Ministerio de Turismo y la empresa de Estonia',
      dek: 'Una comisión investigadora y la Fiscalía revisaron cómo entró una empresa estonia en la pauta digital del ministerio; ambas causas terminaron archivadas, la última en agosto de 2024.',
      contexto: 'Bajo el ministro Germán Cardoso (Partido Colorado), el Ministerio de Turismo contrataba publicidad digital para promocionar el destino Uruguay a través de la agencia Young & Rubicam como intermediaria. En 2021 la Cámara de Diputados creó una comisión investigadora sobre las compras y gastos del ministerio. Uno de los principales denunciantes fue Martín Pérez Banchero, exdirector nacional de Turismo desvinculado por Cardoso tras negarse a autorizar determinadas compras, según El Observador. Cardoso dejó el ministerio en 2021 y hoy es diputado.',
      hallazgo: 'El foco fue cómo llegó Kirma Services, una empresa constituida en Estonia, a la propuesta de pauta digital. Teledoce informó el 4 de octubre de 2021 que Young & Rubicam declaró que «Kirma fue incluida a pedido de Elbio Rodríguez y Daniel Reta», ambos asesores de Cardoso, y que tenía documentación que lo respaldaba; en noviembre la agencia dijo a la diaria que «a Kirma no la conocíamos; se incluyó en la propuesta a pedido del ministerio». Existe una versión contraria: el diputado colorado Conrado Rodríguez sostuvo que fue la propia agencia la que presentó a Kirma ante el ministerio, según Teledoce. La empresa terminó retirando su oferta de US$ 280.000 para trabajar para el Estado uruguayo. El 5 de diciembre de 2022 El Observador publicó que el fiscal de Delitos Económicos Gilberto Rodríguez archivó la denuncia contra Cardoso porque, «si bien puede haber irregularidades administrativas», no halló responsabilidad penal del exministro, y mantuvo abierta la causa Kirma; en esa nota, Pérez Banchero declaró ante la Fiscalía que las irregularidades rondaban el millón de dólares.',
      statusNote: 'Montevideo Portal informó el 5 de agosto de 2024 que el mismo fiscal archivó también la investigación sobre Elbio Rodríguez y Kirma, tras constatar que «la empresa constituida en Estonia ya existía y tiene actividad comercial» y no había sido creada para ejecutar la campaña; la propuesta de Kirma era por $ 12.040.000 con IVA incluido, unos US$ 300.000 al cambio de 2021, y el contrato nunca llegó a concretarse por dificultades de pago. Archivo no equivale a inexistencia de irregularidades administrativas: el propio fiscal señaló que podían existir. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a agosto de 2024.',
      porQueImporta: 'La promoción turística se paga con impuestos y su resultado es difícil de medir, lo que la vuelve un rubro especialmente sensible. Que una propuesta de US$ 280.000 en medios digitales llegara —según la agencia intermediaria— a través de asesores del ministro muestra por qué importa saber quién elige al proveedor y con cuánta competencia, incluso cuando la contratación no termina firmándose.',
      caveat: 'Buena parte de la pauta publicitaria estatal se contrata a través de agencias intermediarias: en compras estatales aparece la agencia adjudicataria, no necesariamente los medios ni las empresas subcontratadas que ejecutan el gasto.',
    },
    en: {
      title: 'The Tourism Ministry\'s ad buys and the Estonian company',
      dek: 'A parliamentary inquiry and prosecutors examined how an Estonian company entered the ministry\'s digital media plan; both cases were closed, the last in August 2024.',
      contexto: 'Under minister Germán Cardoso (Colorado Party), the Ministry of Tourism contracted digital advertising to promote Uruguay as a destination, using the agency Young & Rubicam as intermediary. In 2021 the Chamber of Deputies created an investigative committee into the ministry\'s purchases and spending. One of the main complainants was Martín Pérez Banchero, the former national tourism director removed by Cardoso after refusing to authorise certain purchases, according to El Observador. Cardoso left the ministry in 2021 and is now an MP.',
      hallazgo: 'The focus was how Kirma Services, a company incorporated in Estonia, ended up in the digital media proposal. Teledoce reported on 4 October 2021 that Young & Rubicam stated "Kirma was included at the request of Elbio Rodríguez and Daniel Reta", both advisers to Cardoso, and that it held documents backing this; in November the agency told la diaria that "we didn\'t know Kirma; it was included in the proposal at the ministry\'s request". There is a competing account: Colorado Party MP Conrado Rodríguez maintained it was the agency itself that introduced Kirma to the ministry, per Teledoce. The company ended up withdrawing its US$280,000 offer to work for the Uruguayan State. On 5 December 2022 El Observador reported that Economic Crimes prosecutor Gilberto Rodríguez closed the complaint against Cardoso because, "while there may be administrative irregularities", he found no criminal liability on the former minister\'s part, while keeping the Kirma case open; in that report, Pérez Banchero told prosecutors the irregularities came to close to a million dollars.',
      statusNote: 'Montevideo Portal reported on 5 August 2024 that the same prosecutor also closed the investigation into Elbio Rodríguez and Kirma, after establishing that "the company incorporated in Estonia already existed and has commercial activity" and had not been created to run the campaign; Kirma\'s proposal was for $12,040,000 including VAT, around US$300,000 at 2021 exchange rates, and the contract was never finalised because of payment difficulties. Closure is not the same as a finding that no administrative irregularities occurred: the prosecutor himself said they might exist. As of this file\'s closing (August 2026) there are no developments after August 2024.',
      porQueImporta: 'Tourism promotion is paid for with taxes and its results are hard to measure, which makes it an especially sensitive line of spending. That a US$280,000 digital media proposal arrived — according to the intermediary agency — via the minister\'s advisers shows why it matters who picks the supplier, and with how much competition, even when the contract is never signed.',
      caveat: 'Much state advertising is contracted through intermediary agencies: procurement data shows the winning agency, not necessarily the media outlets or subcontractors that actually execute the spending.',
    },
  },
  {
    slug: 'aerosillas-piriapolis-adjudicacion-revocada',
    emoji: '🚡',
    theme: 'deporte-y-cultura',
    period: '2016-2024',
    statusKind: 'auditoria',
    status: 'rescision',
    amountReported: 'más de $ 12 millones adeudados por el exconcesionario y US$ 1.200.000 de inversión requerida al nuevo adjudicatario',
    organisms: ['Intendencia de Maldonado'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'El Observador', title: 'Aerosillas de Piriápolis: exconcesionario debe $12 millones y la Intendencia de Maldonado inicia acciones legales', url: 'https://www.elobservador.com.uy/nacional/aerosillas-piriapolis-exconcesionario-debe-12-millones-y-la-intendencia-maldonado-inicia-acciones-legales-n5955931', date: '2024-08-13' },
      { outlet: 'El Observador', title: 'Intendencia de Maldonado revocó adjudicación de aerosillas de Piriápolis tras observaciones de Tribunal de Cuentas', url: 'https://www.elobservador.com.uy/nacional/intendencia-maldonado-revoco-adjudicacion-aerosillas-piriapolis-observaciones-tribunal-cuentas-n5973771', date: '2024-12-05' },
      { outlet: 'Montevideo Portal', title: 'Otra temporada sin aerosillas en Piriápolis: qué prevé hacer la Intendencia de Maldonado', url: 'https://www.montevideo.com.uy/Noticias/Otra-temporada-sin-aerosillas-en-Piriapolis-que-preve-hacer-la-Intendencia-de-Maldonado-uc908782', date: '2024-12-06' },
      { outlet: 'Subrayado', title: 'Piriápolis no contará este verano con el servicio de aerosillas: ¿qué prevé la Intendencia de Maldonado?', url: 'https://www.subrayado.com.uy/piriapolis-no-contara-este-verano-el-servicio-aerosillas-que-preve-la-intendencia-maldonado-n963998', date: '2024-12-06' },
      { outlet: 'InfoNegocios', title: 'Revocaron la adjudicación de las aerosillas de Piriápolis: ¿qué pasó tras el anuncio de su reactivación?', url: 'https://infonegocios.biz/nota-principal/revocaron-la-adjudicacion-de-las-aerosillas-de-piriapolis-que-paso-tras-el-anuncio-de-su-reactivacion', date: '2024-12-06' },
    ],
    es: {
      title: 'Las aerosillas de Piriápolis: adjudicación revocada tras el TCR',
      dek: 'La Intendencia de Maldonado revocó la concesión del clásico paseo tras observaciones del Tribunal de Cuentas, y el balneario pasó otra temporada sin servicio.',
      contexto: 'Las aerosillas del cerro San Antonio son uno de los atractivos turísticos históricos de Piriápolis y están en la órbita de la Intendencia de Maldonado, que las concesiona junto con dos bares, uno en la cima y otro en la base. El Observador informó el 13 de agosto de 2024 que el exconcesionario, que había ganado la licitación en 2016, adeudaba más de $ 12 millones por canon impago del período 2016-2021 y que la comuna había iniciado acciones legales. Ese año la Intendencia, encabezada por Enrique Antía, volvió a licitar la concesión por diez años y la adjudicó a Reyna Picún SRL, del empresario local Manuel Reyna, dirigente del Partido Nacional.',
      hallazgo: 'El Tribunal de Cuentas formuló observaciones al procedimiento y la Intendencia decidió revocar la adjudicación. Según InfoNegocios, el organismo de control señaló falta de criterios objetivos de evaluación, trato desigual entre oferentes y plazos de modificación que favorecían a la empresa adjudicada; las observaciones apuntaron al procedimiento del llamado, no a una conducta de la empresa. El Observador informó el 5 de diciembre de 2024 que la comuna estaba «analizando un nuevo pliego y las observaciones que ha realizado el tribunal». El director de Turismo departamental, Martín Laventure, dijo a Montevideo Portal el 6 de diciembre: «Se decidió, lamentablemente, revocar la licitación y culminar este proceso», y anunció un nuevo llamado que incorporaría lo observado. A Subrayado, el mismo día, Laventure sostuvo que «las observaciones del Tribunal de Cuentas no eran las esperadas» y que la comuna acepta algunas y discrepa con otras. InfoNegocios informó que el intendente Antía confirmó que la Intendencia aceptó las observaciones y por eso revocó el llamado, y que la reactivación del servicio exigía una inversión de US$ 1.200.000 a cargo del adjudicatario.',
      statusNote: 'Laventure previó a fines de 2024 un nuevo llamado y que las aerosillas volvieran a funcionar a mediados o fines de 2025, con una concesión a diez años. Las cuatro coberturas de diciembre de 2024 coinciden en que la adjudicación cayó y en que Piriápolis pasaría el verano sin el servicio. Al cierre de esta ficha (agosto de 2026) no constan, entre las fuentes verificadas, novedades posteriores a diciembre de 2024 sobre la reapertura efectiva.',
      porQueImporta: 'Piriápolis vive del turismo y su paseo más conocido lleva años cerrado. Cuando un llamado se cae por observaciones del control, la pérdida no es sólo administrativa: son temporadas sin servicio, sin canon para la comuna y sin la actividad que ese atractivo arrastra en comercios y hotelería.',
      caveat: 'Es una concesión, no una compra: el privado invierte y paga canon, así que puede no aparecer como gasto en el sistema de compras estatales. Lo rastreable son los llamados y adjudicaciones publicados por la Intendencia de Maldonado y el gasto de mantenimiento mientras el servicio estuvo cerrado.',
    },
    en: {
      title: 'Piriápolis chairlift: award revoked after audit objections',
      dek: 'The Maldonado municipality revoked the concession for the resort\'s landmark chairlift after Court of Accounts objections, leaving another summer without the service.',
      contexto: 'The San Antonio hill chairlift is one of Piriápolis\'s historic tourist attractions and sits under the Maldonado municipality, which concessions it out together with two bars, one at the summit and one at the base. El Observador reported on 13 August 2024 that the former concessionaire, which had won the tender in 2016, owed more than $12 million in unpaid fees for the 2016-2021 period, and that the municipality had begun legal action. That year the municipality, led by Enrique Antía, tendered the concession again for ten years and awarded it to Reyna Picún SRL, of local businessman Manuel Reyna, a National Party figure.',
      hallazgo: 'The Court of Accounts raised objections to the procedure and the municipality decided to revoke the award. According to InfoNegocios, the audit body pointed to a lack of objective evaluation criteria, unequal treatment between bidders and amendment timelines that favoured the winning company; the objections targeted the tender procedure, not any conduct by the firm. El Observador reported on 5 December 2024 that the municipality was "analysing new tender documents and the objections raised by the court". The departmental tourism director, Martín Laventure, told Montevideo Portal on 6 December: "It was decided, regrettably, to revoke the tender and end this process", announcing a fresh call that would incorporate the objections. Speaking to Subrayado the same day, Laventure said "the Court of Accounts\' objections were not the ones expected" and that the municipality accepts some and disputes others. InfoNegocios reported that intendente Antía confirmed the municipality accepted the objections and revoked the call on that basis, and that restarting the service required US$1,200,000 of investment from the winning bidder.',
      statusNote: 'In late 2024 Laventure expected a new tender and the chairlift running again by mid or late 2025, on a ten-year concession. The four December 2024 reports agree the award fell through and that Piriápolis would spend the summer without the service. As of this file\'s closing (August 2026) there are, among the verified sources, no developments after December 2024 on the service actually reopening.',
      porQueImporta: 'Piriápolis lives on tourism and its best-known attraction has been shut for years. When a tender collapses over audit objections, the loss is not merely administrative: it means seasons without the service, without concession income for the municipality, and without the trade the attraction brings to shops and hotels.',
      caveat: 'This is a concession, not a purchase: the private party invests and pays a fee, so it may not show up as spending in the state procurement system. What is traceable are the tenders and awards published by the Maldonado municipality and the maintenance spend while the service was closed.',
    },
  },
  {
    slug: 'deuda-clubes-futbol-bps',
    emoji: '⚽',
    theme: 'deporte-y-cultura',
    period: '2019-2026',
    statusKind: 'gestion',
    status: 'sin-resolver',
    amountReported: 'cerca de US$ 50 millones de deuda de los clubes con el BPS (Subrayado, febrero de 2021)',
    organisms: ['Banco de Previsión Social', 'Secretaría Nacional del Deporte'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Banco de Previsión Social',
        'Secretaría Nacional del Deporte',
      ],
      search: 'deportivo',
      yearFrom: 2019,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Subrayado', title: 'Diez clubes de fútbol de primera y segunda división deben US$ 50 millones al BPS', url: 'https://www.subrayado.com.uy/diez-clubes-futbol-primera-y-segunda-division-deben-us-50-millones-al-bps-n717822', date: '2021-02-11' },
      { outlet: 'Subrayado', title: 'Hubo acuerdo con el BPS por millonaria deuda de clubes y hay fútbol el fin de semana', url: 'https://www.subrayado.com.uy/hubo-acuerdo-el-bps-millonaria-deuda-clubes-y-hay-futbol-el-fin-semana-n718073', date: '2021-02-12' },
      { outlet: 'Subrayado', title: 'Nueve equipos del fútbol deben más de 50 millones de dólares al Banco de Previsión Social', url: 'https://www.subrayado.com.uy/nueve-equipos-del-futbol-deben-mas-50-millones-dolares-al-banco-prevision-social-n540356', date: '2019-08-01' },
      { outlet: 'Búsqueda', title: '«Fair play» financiero en el fútbol uruguayo: a partir de 2026 buscarán controlar sueldos, impuestos y aportes', url: 'https://www.busqueda.com.uy/deportes/fair-play-financiero-el-futbol-uruguayo-partir-2026-buscaran-controlar-sueldos-impuestos-y-aportes-n5397816', date: '2025-04-10' },
    ],
    es: {
      title: 'Los clubes de fútbol le deben decenas de millones al BPS',
      dek: 'Diez clubes acumulaban una deuda cercana a US$ 50 millones con la seguridad social; el conflicto de 2021 se destrabó con declaraciones juradas, no con pagos.',
      contexto: 'Los clubes del fútbol profesional uruguayo son empleadores: deben retener y verter al Banco de Previsión Social (BPS) los aportes a la seguridad social de sus futbolistas. Subrayado informó el 1° de agosto de 2019 que nueve equipos debían más de US$ 50 millones al BPS —y que un relevamiento de la AUF identificaba 25 clubes con deuda, cifra que según fuentes citadas podía acercarse a los US$ 100 millones—, con casos como Nacional (unos US$ 9,3 millones por aportes impagos entre 1996 y 2003), Peñarol (unos US$ 6,3 millones del mismo período) y Rentistas (unos US$ 16,6 millones). En febrero de 2021 el problema estalló: unos 200 futbolistas no pudieron cobrar el seguro de paro por irregularidades en sus aportes y la Mutual de Futbolistas advirtió que pararía la fecha del Torneo Clausura.',
      hallazgo: 'Subrayado informó el 11 de febrero de 2021 que diez clubes de primera y segunda división mantenían una deuda de US$ 50 millones con el BPS, y citó al vicepresidente del organismo, Daniel Graffigna, señalando que los clubes en falta «no pagaban a la institución los aportes a la seguridad social que hacen los futbolistas». Al día siguiente, el 12 de febrero, el mismo medio informó el acuerdo: diez de los once clubes con deuda firmaron una declaración jurada reconociéndola y con eso el BPS mantuvo el acceso de los jugadores al seguro de paro y a la cobertura de salud, con la AUF como garante por dos meses; Cerro no firmó y su caso pasó a la Dirección Nacional de Trabajo. Es decir, el conflicto se destrabó reconociendo la deuda, no cancelándola.',
      statusNote: 'Búsqueda informó el 10 de abril de 2025 que la AUF proyecta un reglamento de «fair play» financiero a partir de 2026, coordinado con el nuevo contrato de televisión, para verificar el «cumplimiento estricto mensual» de sueldos, impuestos a la DGI y aportes al BPS, en palabras del presidente de la AUF, Ignacio Alonso; toma como referencia el modelo chileno —que limita al 70% el gasto en plantel sobre los ingresos promedio de tres años— y no incluye topes salariales al estilo europeo. No consta una cifra oficial actualizada de la deuda del conjunto de los clubes con el BPS. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a abril de 2025.',
      porQueImporta: 'Los aportes impagos no son un problema interno del fútbol: son plata que financia jubilaciones y seguro de paro de todos. Cuando un club retiene el aporte del futbolista y no lo vierte, el trabajador queda sin cobertura y el agujero lo termina cubriendo el resto de los contribuyentes.',
      caveat: 'Esta es una deuda tributaria y de seguridad social, no una compra pública: no aparece en el sistema de compras estatales ni tiene un organismo comprador asociado. Lo que sí puede cruzarse son los pagos que organismos públicos e intendencias hacen a clubes por patrocinios, convenios y uso de instalaciones.',
    },
    en: {
      title: 'Football clubs owe tens of millions to social security',
      dek: 'Ten clubs had built up close to US$50m in debt to social security; the 2021 standoff was resolved with sworn statements, not payments.',
      contexto: 'Uruguay\'s professional football clubs are employers: they must withhold and remit their players\' social security contributions to the BPS (Banco de Previsión Social). Subrayado reported on 1 August 2019 that nine clubs owed more than US$50m to the BPS — and that an AUF survey identified 25 clubs with arrears, a figure sources put closer to US$100m — with cases such as Nacional (about US$9.3m for contributions unpaid between 1996 and 2003), Peñarol (about US$6.3m from the same period) and Rentistas (about US$16.6m). In February 2021 the problem came to a head: some 200 players could not collect unemployment insurance because of irregularities in their contributions, and the players\' union warned it would halt the Clausura tournament round.',
      hallazgo: 'Subrayado reported on 11 February 2021 that ten first- and second-division clubs carried US$50m of debt with the BPS, quoting the agency\'s vice-president, Daniel Graffigna, saying the clubs in default "were not paying the institution the social security contributions made by the players". The next day, 12 February, the same outlet reported the deal: ten of the eleven indebted clubs signed a sworn statement acknowledging the debt, and on that basis the BPS maintained players\' access to unemployment insurance and health cover, with the AUF as guarantor for two months; Cerro did not sign and its case went to the National Labour Directorate. In other words, the standoff was resolved by acknowledging the debt, not by paying it.',
      statusNote: 'Búsqueda reported on 10 April 2025 that the AUF plans a financial "fair play" rulebook from 2026, coordinated with the new television contract, to verify "strict monthly compliance" on wages, tax payments to the DGI and BPS contributions, in the words of AUF president Ignacio Alonso; it is modelled on Chile\'s framework — which caps squad spending at 70% of average revenue over three years — and does not include European-style salary caps. There is no updated official figure for the clubs\' aggregate debt to the BPS. As of this file\'s closing (August 2026) there are no developments after April 2025.',
      porQueImporta: 'Unpaid contributions are not football\'s internal problem: they are money that funds everyone\'s pensions and unemployment insurance. When a club withholds a player\'s contribution and does not remit it, the worker loses cover and the shortfall is ultimately covered by every other taxpayer.',
      caveat: 'This is tax and social security debt, not a public purchase: it does not appear in the state procurement system and has no associated buying agency. What can be cross-referenced are the payments public bodies and municipalities make to clubs for sponsorship, agreements and use of facilities.',
    },
  },
  {
    slug: 'cambio-marca-pais-uruguay-sorprende',
    emoji: '🏷️',
    theme: 'deporte-y-cultura',
    period: '2025-2026',
    statusKind: 'debate',
    status: 'debate',
    organisms: ['Ministerio de Turismo'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Dirección Nacional de Turismo',
      ],
      yearFrom: 2025,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Ministerio de Turismo (gub.uy)', title: 'Uruguay, destino turístico 2026: estrategias para el éxito', url: 'https://www.gub.uy/ministerio-turismo/comunicacion/noticias/uruguay-destino-turistico-2026-estrategias-para-exito', date: '2025-09-30' },
      { outlet: 'Caras y Caretas', title: '«Uruguay Sorprende»: el Ministerio de Turismo lanza la temporada 2025/2026', url: 'https://www.carasycaretas.com.uy/politica/uruguay-sorprende-el-ministerio-turismo-lanza-la-temporada-20252026-n90420', date: '2025-11-28' },
      { outlet: 'El Observador', title: '¿Uruguay Natural o Uruguay Sorprende?: el cambio de marca que genera polémica en el sector turístico', url: 'https://www.elobservador.com.uy/cafe-y-negocios/uruguay-natural-o-uruguay-sorprende-el-cambio-marca-que-genera-polemica-el-sector-turistico-n6051953', date: '2026-07-25' },
    ],
    es: {
      title: 'Adiós a Uruguay Natural: el cambio de marca que resiste el sector',
      dek: 'El Ministerio de Turismo se movió de «Uruguay Natural» a «Uruguay Sorprende»; operadores y publicistas cuestionan la decisión y no hay cifra pública de lo que cuesta.',
      contexto: '«Uruguay Natural» es la marca con la que el país se promociona en el exterior desde hace décadas. El 30 de setiembre de 2025, en un almuerzo de trabajo de la Asociación de Dirigentes de Marketing (ADM) al que asistieron la vicepresidenta Carolina Cosse y tres intendentes, el ministro de Turismo Pablo Menoni presentó «Uruguay Sorprende» y sostuvo que los turistas se van del país sorprendidos por la calidez de su gente y sus libertades individuales, según la comunicación oficial del propio ministerio. La temporada 2025/2026 se lanzó el 28 de noviembre de 2025 en el Espacio Dínamo de Atlántida bajo ese lema, con el ministro, la subsecretaria Ana Claudia Caram, el director nacional de Turismo Cristian Pos y el intendente de Canelones, Francisco Legniani, según Caras y Caretas.',
      hallazgo: 'El Observador informó el 25 de julio de 2026 que fuentes del sector y del propio ministerio confirmaron que la marca turística está migrando a «Uruguay Sorprende», pese a que en octubre la subsecretaria Caram había afirmado que Uruguay Natural no había cambiado. El publicista Álvaro Moré, presidente de VML y WPP Production, sostuvo que «un cambio de marca solo se justifica cuando existe un cambio de propietario o un problema de reputación». Fernando Tapia, presidente de la Cámara Uruguaya de Turismo, dijo: «No estuvimos nunca de acuerdo con que se abandonara Uruguay Natural», aunque agregó que «vamos a acompañar el camino». El exsubsecretario de Turismo Benjamín Liberoff advirtió que «la discusión excede el cambio de un eslogan» porque «cambiar una marca no es una decisión estética». La nota no consigna cuánto cuesta el recambio.',
      statusNote: '«Uruguay Sorprende» está en uso en la comunicación oficial del Ministerio de Turismo desde setiembre de 2025. No consta una cifra oficial publicada del costo del recambio de identidad visual ni del monto de la pauta asociada: El Observador no informa ninguna. La discusión con el sector privado seguía abierta al 25 de julio de 2026. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a esa fecha.',
      porQueImporta: 'La marca país es el envase con el que Uruguay se vende afuera y se paga con impuestos: campañas, ferias, cartelería, producción audiovisual. Cambiarla obliga a rehacer material que ya estaba pago y a reconstruir un reconocimiento que llevó años. Si el cambio no rinde en más turistas, ese gasto se pierde, y hoy no hay una cifra pública para medirlo.',
      caveat: 'El costo del cambio de marca se dispersa en muchas compras chicas —diseño, cartelería, producción, pauta— y puede involucrar a más de un organismo. No hay una única línea presupuestal que lo agrupe, así que el total sólo puede estimarse sumando contratos.',
    },
    en: {
      title: 'Goodbye Uruguay Natural: a rebrand the sector resists',
      dek: 'The Tourism Ministry has moved from "Uruguay Natural" to "Uruguay Sorprende"; operators and admen question the decision, and no public figure exists for what it costs.',
      contexto: '"Uruguay Natural" is the brand the country has used to market itself abroad for decades. On 30 September 2025, at a working lunch of the Marketing Executives Association (ADM) attended by Vice President Carolina Cosse and three departmental intendentes, Tourism Minister Pablo Menoni presented "Uruguay Sorprende" and said tourists leave the country surprised by the warmth of its people and its individual freedoms, according to the ministry\'s own official communication. The 2025/2026 season was launched on 28 November 2025 at Espacio Dínamo in Atlántida under that slogan, with the minister, deputy minister Ana Claudia Caram, national tourism director Cristian Pos and Canelones intendente Francisco Legniani, according to Caras y Caretas.',
      hallazgo: 'El Observador reported on 25 July 2026 that sources in the sector and in the ministry itself confirmed the tourism brand is migrating to "Uruguay Sorprende", even though in October deputy minister Caram had said Uruguay Natural had not changed. Adman Álvaro Moré, president of VML and WPP Production, argued that "a rebrand is only justified when there is a change of ownership or a reputational problem". Fernando Tapia, president of the Uruguayan Chamber of Tourism, said: "We never agreed with abandoning Uruguay Natural", while adding that "we will go along with the path". Former deputy tourism minister Benjamín Liberoff warned that "the discussion goes beyond changing a slogan" because "changing a brand is not an aesthetic decision". The report gives no figure for what the switch costs.',
      statusNote: '"Uruguay Sorprende" is in use in the Tourism Ministry\'s official communications from September 2025. No official published figure exists for the cost of the visual identity switch or the associated media spend: El Observador reports none. The dispute with the private sector was still open as of 25 July 2026. As of this file\'s closing (August 2026) there are no developments after that date.',
      porQueImporta: 'The country brand is the packaging Uruguay sells itself in abroad, and it is paid for with taxes: campaigns, trade fairs, signage, audiovisual production. Changing it forces the remaking of material already paid for and the rebuilding of recognition that took years. If the change does not deliver more tourists, that spending is lost — and today there is no public figure to measure it.',
      caveat: 'The rebrand\'s cost is scattered across many small purchases — design, signage, production, media buying — and may involve more than one body. No single budget line groups it, so the total can only be estimated by adding up contracts.',
    },
  },
  {
    slug: 'tax-rebate-audiovisual-producciones-extranjeras',
    emoji: '🎬',
    theme: 'deporte-y-cultura',
    period: '2019-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'US$ 12 millones en la línea del Programa Uruguay Audiovisual (ACAU, noviembre de 2025) y un crédito fiscal del 30% de los gastos admitidos (decreto 153/026)',
    organisms: ['Agencia del Cine y el Audiovisual del Uruguay (ACAU)', 'Agencia Nacional de Desarrollo (ANDE)', 'Ministerio de Industria, Energía y Minería', 'Ministerio de Educación y Cultura'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'MIEM (gub.uy)', title: 'Nueva edición de PUA en sus líneas de producciones audiovisuales nacionales y publicitaria internacional en Uruguay', url: 'https://www.gub.uy/ministerio-industria-energia-mineria/comunicacion/noticias/nueva-edicion-pua-sus-lineas-producciones-audiovisuales-nacionales', date: '2022-09-02' },
      { outlet: 'InfoNegocios', title: 'Luz, cámara… dólares (la industria audiovisual crece a pasos agigantados y las semanas de rodaje aumentaron en un 340%)', url: 'https://infonegocios.biz/nota-principal/luz-camara-dolares-la-industria-audiovisual-crece-a-pasos-agigantados-y-las-semanas-de-rodaje-aumentaron-en-un-340', date: '2025-11-20' },
      { outlet: 'Montevideo Portal', title: 'Uruguay creó un nuevo incentivo para atraer grandes producciones de cine: de qué se trata', url: 'https://www.montevideo.com.uy/Noticias/Uruguay-creo-un-nuevo-incentivo-para-atraer-grandes-producciones-de-cine-de-que-se-trata-uc967236', date: '2026-07-04' },
      { outlet: 'IMPO', title: 'Decreto N° 153/026', url: 'https://www.impo.com.uy/bases/decretos/153-2026', date: '2026-07-17' },
    ],
    es: {
      title: 'El Estado devuelve hasta 30% de lo que gastan las filmaciones',
      dek: 'Uruguay reembolsa parte del gasto de las producciones audiovisuales; un decreto de julio de 2026 sumó además un crédito fiscal del 30% de los gastos admitidos.',
      contexto: 'El Programa Uruguay Audiovisual (PUA) reembolsa parte de lo que las producciones audiovisuales gastan en el país. En su edición de 2022, según el MIEM, lo coordinaban la Dinatel, la Agencia Nacional de Desarrollo (ANDE), el entonces Instituto del Cine y Audiovisual (INCAU, hoy Agencia del Cine y el Audiovisual del Uruguay, ACAU) y Uruguay XXI, con una línea publicitaria que devolvía hasta 20% del proyecto con tope de US$ 100.000 y líneas nacionales de entre 20% y 80%. Montevideo Portal describe hoy ese esquema de cash rebate en un rango de 20% a 25% y señala que las semanas de rodaje anuales se cuadruplicaron desde 2019. Según InfoNegocios (20 de noviembre de 2025), la presidenta de ACAU, Gisella Previtali, indicó que el PUA cuenta con una línea de US$ 12 millones, además de $ 54 millones del Fondo de Fomento Cinematográfico.',
      hallazgo: 'Montevideo Portal informó el 4 de julio de 2026 que un nuevo decreto crea un crédito fiscal equivalente al 30% de los gastos admitidos realizados en territorio uruguayo. El texto, publicado en IMPO como decreto N° 153/026 —promulgado el 3 de julio y publicado el 17 de julio de 2026, reglamentario del artículo 686 de la ley N° 20.446—, instrumenta el beneficio en certificados de crédito en el régimen de exportadores, con validez de 36 meses y transferibles a bancos, entes autónomos y aseguradoras, y exige gastos elegibles por un mínimo de UI 1.200.000. Lo firmaron el presidente Yamandú Orsi junto a los ministros Gabriel Oddone (Economía), Fernanda Cardona (Industria) y José Carlos Mahía (Educación y Cultura). El debate es sobre el retorno de esa plata: Previtali afirmó a InfoNegocios que «por cada dólar invertido por el Estado a través de PUA, 1,7 vuelve al sector público», que la inversión pública se multiplica por 7,2 en gasto privado en servicios de producción y que las semanas de rodaje crecieron 340% en cinco años (104 semanas en 2024). Esos cálculos provienen de la propia agencia que administra el programa; no consta una evaluación independiente publicada.',
      statusNote: 'El decreto 153/026 rige desde julio de 2026 y el Ministerio de Economía se reservó la potestad de fijar un tope anual al beneficio cuando lo entienda pertinente. La ACAU debe presentar al Poder Ejecutivo informes anuales de ejecución, según informó Montevideo Portal. Al cierre de esta ficha (agosto de 2026) no constan, entre las fuentes verificadas, cuestionamientos formales del Tribunal de Cuentas ni evaluaciones externas publicadas sobre el retorno del programa.',
      porQueImporta: 'Es plata pública que vuelve a empresas privadas, muchas extranjeras, por gastar en Uruguay. Puede ser buen negocio —trabajo para técnicos, hoteles, catering, transporte— o una transferencia por rodajes que se habrían hecho igual. La diferencia depende de números que hoy publica el mismo organismo que administra el beneficio.',
      caveat: 'Los reembolsos del PUA y los créditos fiscales no son compras del Estado: no generan una adjudicación en el sistema de compras estatales. Se rastrean por los fallos de las convocatorias de ACAU y por los certificados de la DGI, no por el buscador de contratos.',
    },
    en: {
      title: 'The State refunds up to 30% of what film shoots spend',
      dek: 'Uruguay reimburses part of what audiovisual productions spend; a July 2026 decree added a 30% tax credit on eligible expenses on top.',
      contexto: 'The Uruguay Audiovisual Programme (PUA) refunds part of what audiovisual productions spend in the country. In its 2022 edition, according to MIEM, it was coordinated by Dinatel, the National Development Agency (ANDE), the then film institute INCAU (now the Uruguayan Film and Audiovisual Agency, ACAU) and Uruguay XXI, with an advertising line returning up to 20% of a project capped at US$100,000 and national lines of between 20% and 80%. Montevideo Portal now describes that cash rebate scheme as running at 20-25% and notes annual filming weeks have quadrupled since 2019. According to InfoNegocios (20 November 2025), ACAU president Gisella Previtali said PUA has a US$12m line, plus $54m from the Film Promotion Fund.',
      hallazgo: 'Montevideo Portal reported on 4 July 2026 that a new decree creates a tax credit equal to 30% of eligible expenses incurred in Uruguayan territory. The text, published on IMPO as decree N° 153/026 — enacted on 3 July and published on 17 July 2026, implementing article 686 of law N° 20.446 — delivers the benefit as credit certificates under the exporters\' regime, valid for 36 months and transferable to banks, autonomous entities and insurers, and requires eligible spending of at least UI 1,200,000. It was signed by President Yamandú Orsi alongside ministers Gabriel Oddone (Economy), Fernanda Cardona (Industry) and José Carlos Mahía (Education and Culture). The debate is over the return on that money: Previtali told InfoNegocios that "for every dollar the State invests through PUA, 1.7 comes back to the public sector", that public investment multiplies 7.2 times in private production-services spending, and that filming weeks grew 340% in five years (104 weeks in 2024). Those calculations come from the very agency that runs the programme; no independent published evaluation is on record.',
      statusNote: 'Decree 153/026 has been in force since July 2026 and the Economy Ministry reserved the power to set an annual cap on the benefit when it sees fit. ACAU must submit annual execution reports to the Executive, according to Montevideo Portal. As of this file\'s closing (August 2026) there are, among the verified sources, no formal Court of Accounts objections nor published external evaluations of the programme\'s return.',
      porQueImporta: 'This is public money going back to private companies, many of them foreign, for spending in Uruguay. It may be a good deal — work for crews, hotels, catering, transport — or a transfer for shoots that would have happened anyway. The difference rests on figures currently published by the same body that administers the benefit.',
      caveat: 'PUA refunds and tax credits are not state purchases: they generate no award in the procurement system. They are traced through ACAU\'s call results and DGI certificates, not through the contracts search.',
    },
  },
]
