import type { CasoDef } from '../types'

/**
 * estado-y-fondos — 11 dossiers, 10 of them with a live cross-reference.
 *
 * Every source URL was fetched and every query was resolved against the live
 * collection before this file was committed (scripts/verify-casos.ts re-checks
 * both). A caso with no `query` is not a gap in the research: its money does
 * not travel through the Compras Estatales feed at all, which `feedCoverage`
 * records and the page states outright.
 */
export const CASOS_ESTADO_Y_FONDOS: CasoDef[] = [
  {
    slug: 'publicidad-oficial-sin-marco-legal',
    emoji: '📺',
    theme: 'estado-y-fondos',
    period: '2015-2025',
    statusKind: 'debate',
    status: 'debate',
    amountReported: 'Más de $ 4.500 millones (unos US$ 110 millones) en publicidad oficial entre 2020 y 2024, según Observacom citado por Caras y Caretas',
    organisms: ['Presidencia de la República', 'Ministerio de Turismo', 'Administración Nacional de Telecomunicaciones (ANTEL)', 'Banco de la República Oriental del Uruguay', 'Administración Nacional de Usinas y Trasmisiones Eléctricas (UTE)', 'Banco de Seguros del Estado'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Presidencia de la República y Oficinas Dependientes',
        'Presidencia de la República',
        'Oficina Nacional del Servicio Civil',
        'Secretaría Nacional del Deporte',
        'Oficina de Planeamiento y Presupuesto',
        'Unidad Reguladora de Servic.de Comunicaciones-URSEC',
        'Casa Militar',
        'Instituto Nacional de Estadística',
        'AGESIC',
        'Unidad Reguladora de Serv. de Energía y Agua-URSEA',
        'Presidencia de la República y Unidades Dependientes',
        'NO VIGENTE - Dirección de Proyectos de Desarrollo',
        'Secretaría Nacional del Deporte',
        'Instituto Nacional de EstadÍstica',
        'Agen.p/Des.del Gob.de Gest.Electr.y Soc.Inform.y del Conoc.',
        'Dirección Nacional de Turismo',
        'Administración Nacional de Telecomunicaciones',
        'Administración Nacional de Usinas y Trasmisiones Eléctricas',
        'Banco de Seguros del Estado',
      ],
      search: 'publicidad',
      yearFrom: 2015,
      yearTo: 2025,
    },
    investigationPath: '/pauta',
    sources: [
      { outlet: 'Caras y Caretas', title: 'Publicidad oficial en cifras: Lacalle Pou gastó más que Tabaré Vázquez', url: 'https://www.carasycaretas.com.uy/politica/publicidad-oficial-cifras-lacalle-pou-gasto-mas-que-tabare-vazquez-n85143', date: '2025-06-11' },
      { outlet: 'Caras y Caretas', title: 'Informe sobre gastos en publicidad oficial', url: 'https://www.carasycaretas.com.uy/sociedad/informe-gastos-publicidad-oficial-n85475', date: '2025-06-23' },
      { outlet: 'Presidencia de la República', title: 'Proyecto de ley otorga 30 % de publicidad oficial a medios y producciones del interior', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/proyecto-ley-otorga-30-publicidad-oficial-medios-producciones-del-interior', date: '2015-08-10' },
      { outlet: 'la diaria', title: 'Diputados del FA presentaron un proyecto sobre publicidad oficial que dispone mediciones de audiencia y de lectoría', url: 'https://ladiaria.com.uy/politica/articulo/2025/12/diputados-del-fa-presentaron-un-proyecto-sobre-publicidad-oficial-que-dispone-mediciones-de-audiencia-y-de-lectoria/', date: '2025-12-25' },
      { outlet: 'Montevideo Portal', title: 'Proyecto sobre publicidad oficial: FA plantea medir audiencias y 30% a medios del interior', url: 'https://www.montevideo.com.uy/Noticias/Proyecto-sobre-publicidad-oficial-FA-plantea-medir-audiencias-y-30-a-medios-del-interior-uc947663', date: '2025-12-26' },
    ],
    es: {
      title: 'Publicidad oficial: US$ 110 millones sin una ley que fije criterios',
      dek: 'El Estado y sus empresas gastaron más de $ 4.500 millones en pauta entre 2020 y 2024, según Observacom, y Uruguay sigue sin una ley que regule cómo se reparte.',
      contexto: 'La publicidad oficial es el dinero público que ministerios, entes y empresas estatales destinan a pautar en medios de comunicación. En Uruguay no existe una ley que fije criterios de asignación: cada organismo decide con qué medios contrata y por cuánto. En agosto de 2015, representantes de todos los partidos con representación parlamentaria junto al Centro de Archivos y Acceso a la Información Pública (CAinfo) presentaron en Diputados un proyecto para regular la producción, planificación, contratación y distribución de la pauta oficial y reservar al menos 30% del presupuesto a medios y producciones del interior, según informó Presidencia. Ese proyecto no llegó a aprobarse. En diciembre de 2025 diputados del Frente Amplio presentaron una nueva versión.',
      hallazgo: 'Según un análisis de Observacom, dirigido por Gustavo Gómez, con datos pedidos por acceso a la información a la Oficina de Planeamiento y Presupuesto (OPP) y publicado por Caras y Caretas el 11 de junio de 2025, entre 2020 y 2024 el Estado gastó más de $ 4.500 millones (unos US$ 110 millones) en publicidad oficial: 80% lo ejecutaron las empresas públicas —BROU, Antel, UTE y el Banco de Seguros del Estado— y el 20% restante se repartió entre organismos estatales como Presidencia, ministerios, el Poder Judicial y la Universidad de la República. El Ministerio de Turismo fue el mayor anunciante entre los organismos estatales, con campañas internacionales incluidas. Cerca del 95% de la pauta quedó en Montevideo y 5% en el interior. En una segunda entrega, del 23 de junio de 2025, el mismo medio informó que las empresas públicas gastaron 54% más en 2024 que en 2019 (US$ 22,7 millones frente a US$ 14,8 millones) —Antel +50%, UTE +72%, BROU +76%— y que cinco anunciantes (BROU, Antel, Turismo, UTE y BSE) concentraron cerca del 84% del total del período.',
      statusNote: 'El 25 de diciembre de 2025 diputados del Frente Amplio, con Javier Umpiérrez como principal autor, presentaron un proyecto que obliga a medir audiencias antes de repartir la pauta, reserva al menos 30% de la publicidad oficial de alcance nacional para medios con producción radicada en el interior, destina 3% anual a estudios de audiencia y lectoría y crea un fondo de promoción financiado con 1% del presupuesto de publicidad oficial, según la diaria y Montevideo Portal. Fabián Werner, de CAinfo, recordó que la discusión lleva casi 20 años. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores al 26 de diciembre de 2025 sobre su tratamiento parlamentario.',
      porQueImporta: 'Sin criterios legales, la decisión de a qué medio se le paga y cuánto queda a discreción de cada jerarca, con dinero de tarifas y de impuestos. Además de la transparencia del gasto, está en juego la independencia de los medios que informan sobre el mismo Estado que los financia.',
      caveat: 'Las cifras publicadas surgen de pedidos de acceso a la información a la OPP y no de un registro único. Buena parte de la pauta se contrata mediante agencias de medios y convenios, por lo que puede no aparecer identificada como publicidad en el buscador de compras estatales.',
    },
    en: {
      title: 'Official advertising: US$110 million with no law setting criteria',
      dek: 'The State and its companies spent over $4.5 billion pesos on advertising between 2020 and 2024, per Observacom, and Uruguay still has no law governing how it is distributed.',
      contexto: 'Official advertising is the public money that ministries, agencies and state-owned companies spend on placements in the media. Uruguay has no law setting allocation criteria: each agency decides which outlets it contracts and for how much. In August 2015, representatives of every party with parliamentary representation, together with the Centre for Archives and Access to Public Information (CAinfo), submitted a bill to the Chamber of Deputies to regulate the production, planning, contracting and distribution of official advertising and to reserve at least 30% of the budget for media and productions from the interior, as Presidencia reported. That bill was never passed. In December 2025 Frente Amplio deputies filed a new version.',
      hallazgo: 'According to an analysis by Observacom, led by Gustavo Gómez, based on freedom-of-information requests to the Office of Planning and Budget (OPP) and published by Caras y Caretas on 11 June 2025, between 2020 and 2024 the State spent more than $4.5 billion pesos (some US$110 million) on official advertising: 80% was executed by state-owned companies —BROU, Antel, UTE and the state insurance bank BSE— and the remaining 20% was split among state bodies such as Presidencia, ministries, the Judiciary and the University of the Republic. The Ministry of Tourism was the largest advertiser among state bodies, international campaigns included. Around 95% of the spending stayed in Montevideo and 5% went to the interior. In a second instalment, on 23 June 2025, the same outlet reported that state companies spent 54% more in 2024 than in 2019 (US$22.7 million versus US$14.8 million) —Antel +50%, UTE +72%, BROU +76%— and that five advertisers (BROU, Antel, Tourism, UTE and BSE) accounted for about 84% of the period\'s total.',
      statusNote: 'On 25 December 2025 Frente Amplio deputies, with Javier Umpiérrez as lead author, filed a bill requiring audience measurement before advertising is allocated, reserving at least 30% of nationally scoped official advertising for media with production based in the interior, earmarking 3% a year for audience and readership studies and creating a promotion fund financed with 1% of official advertising budgets, according to la diaria and Montevideo Portal. Fabián Werner, of CAinfo, noted the debate has been running for almost 20 years. As of this file\'s closing (August 2026) there is no record of developments after 26 December 2025 on its parliamentary treatment.',
      porQueImporta: 'With no legal criteria, the decision of which outlet gets paid and how much rests on each official\'s discretion, using money from utility bills and taxes. Beyond spending transparency, what is at stake is the independence of the media that report on the very State funding them.',
      caveat: 'The published figures come from freedom-of-information requests to the OPP, not from a single register. Much of the advertising is contracted through media agencies and framework agreements, so it may not appear labelled as advertising in the state procurement search.',
    },
  },
  {
    slug: 'pases-en-comision-poder-legislativo',
    emoji: '🔀',
    theme: 'estado-y-fondos',
    period: '2025-2026',
    statusKind: 'debate',
    status: 'sin-resolver',
    organisms: ['Poder Legislativo', 'Cámara de Representantes', 'Cámara de Senadores', 'Banco de Previsión Social', 'Administración Nacional de Educación Pública', 'Administración Nacional de Telecomunicaciones (ANTEL)'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Comisión Administrativa del Poder Legislativo',
        'Cámara de Representantes',
        'Cámara de Senadores',
        'Banco de Previsión Social',
        'Administración Nacional de Telecomunicaciones',
      ],
      search: 'comisión',
      yearFrom: 2025,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'UyPress', title: 'Diputados y senadores acumulan centenares de pases en comisión: vea todos los nombres', url: 'https://www.uypress.net/auc.aspx?149602=', date: '2026-01-13' },
      { outlet: 'La Mañana', title: 'Pases en comisión llegan a 428 en el Poder Legislativo y hay 161 en trámite', url: 'https://www.lamañana.uy/actualidad/pases-en-comision-llegan-a-428-en-el-poder-legislativo-y-hay-161-en-tramite/', date: '2025-10-01' },
      { outlet: 'la diaria', title: 'Los pases en comisión de funcionarios públicos al Parlamento presentan opacidad y falta de rendición de cuentas y de contralor, según especialistas', url: 'https://ladiaria.com.uy/politica/articulo/2026/2/los-pases-en-comision-de-funcionarios-publicos-al-parlamento-presentan-opacidad-y-falta-de-rendicion-de-cuentas-y-de-contralor-segun-especialistas/', date: '2026-02-07' },
      { outlet: 'Oficina Nacional del Servicio Civil', title: 'Pases en Comisión - Datos a Diciembre 2025', url: 'https://www.gub.uy/oficina-nacional-servicio-civil/institucional/recursos-humanos/pases-comision/pases-comision-datos-diciembre-2025', date: '2026-02-20' },
    ],
    es: {
      title: 'Pases en comisión: 591 funcionarios pedidos por legisladores',
      dek: 'Cada legislador puede pedir hasta cinco funcionarios públicos que siguen cobrando en su organismo de origen; especialistas advierten que casi no hay contralor sobre lo que hacen.',
      contexto: 'El pase en comisión permite que un funcionario público pase a trabajar para un legislador manteniendo su vínculo y su sueldo en el organismo de origen: lo paga el BPS, ANEP o Antel, pero cumple tareas en el Parlamento. Cada legislador puede pedir hasta cinco funcionarios para tareas de asistencia directa. El Parlamento publica las nóminas en su sitio y la Oficina Nacional del Servicio Civil difunde datos periódicos por organismo de destino —su publicación con datos a diciembre de 2025 está fechada el 20 de febrero de 2026—, pero no se publica cuánto cuesta el régimen ni qué tareas cumple cada persona.',
      hallazgo: 'Un relevamiento publicado por UyPress el 13 de enero de 2026 contabilizó 591 pases en comisión en el Poder Legislativo: 419 en Diputados (296 autorizados y 123 en trámite) y 172 en el Senado (132 autorizados y 40 en trámite). La vicepresidenta Carolina Cosse encabezaba la lista del Senado con ocho —siete autorizados y uno en trámite—, con funcionarios provenientes de la Intendencia de Montevideo, Ancap, el Ministerio del Interior y el BPS; entre los diputados figuraba primero el nacionalista Pablo Abdala, con cinco. La Mañana había informado el 1º de octubre de 2025 que los autorizados eran 428 (292 en Diputados, 136 en el Senado) y otros 161 estaban en trámite, con el BPS (25), ANEP (23) y Antel (12) como principales organismos cedentes hacia Diputados. El 7 de febrero de 2026 la diaria consultó a especialistas: el profesor de Derecho Administrativo de la Udelar Federico Baz describió el sistema como un régimen de ficción por la falta de contralor sobre horarios y tareas, y desde el Observatorio Ciudadano de Corrupción señalaron que queda la sensación de que pasan cosas que no se pueden probar pero se pueden ver.',
      statusNote: 'El régimen sigue vigente y las nóminas se actualizan en el sitio del Parlamento. La Mañana informó que, de completarse los pases en trámite, la legislatura llegaría a 589, cinco más que la anterior, y recogió el planteo de la Fiscal de Corte, Mónica Ferrero, quien dijo a los legisladores durante el tratamiento del Presupuesto que siete funcionarios habían salido en comisión tras su asunción, en una dependencia con carencia de personal. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores al 7 de febrero de 2026 ni normas aprobadas que obliguen a publicar el costo del régimen.',
      porQueImporta: 'El sueldo lo sigue pagando el organismo de origen: si un funcionario del BPS o de ANEP atiende a un legislador, ese puesto puede quedar sin cubrir en la ventanilla o en el aula mientras el gasto se mantiene. Sin publicación del costo ni control de tareas, el contribuyente no puede saber cuánto paga por este régimen.',
      caveat: 'Los pases en comisión son gasto salarial, no compras: no tienen contrapartida en el buscador de contratos de este sitio. Las cifras provienen de nóminas parlamentarias relevadas por la prensa, incluyen pases autorizados y en trámite, y varían semana a semana según los expedientes en curso.',
    },
    en: {
      title: 'Secondments: 591 public employees requested by legislators',
      dek: 'Each legislator may request up to five public employees who keep drawing their salary from their home agency; specialists warn there is almost no oversight of what they do.',
      contexto: 'A \'pase en comisión\' (secondment) lets a public employee go to work for a legislator while keeping their post and salary at their home agency: the BPS, ANEP or Antel pays them, but they work in Parliament. Each legislator may request up to five employees for direct assistance duties. Parliament publishes the rosters on its website and the National Civil Service Office releases periodic data by receiving agency —its release with data as of December 2025 is dated 20 February 2026— but neither the cost of the scheme nor the duties performed by each person is published.',
      hallazgo: 'A survey published by UyPress on 13 January 2026 counted 591 secondments in the Legislative Branch: 419 in the Chamber of Deputies (296 authorised, 123 pending) and 172 in the Senate (132 authorised, 40 pending). Vice President Carolina Cosse topped the Senate list with eight —seven authorised and one pending— with staff from the Montevideo city government, Ancap, the Interior Ministry and the BPS; among deputies, the National Party\'s Pablo Abdala came first, with five. La Mañana had reported on 1 October 2025 that 428 were authorised (292 in the Chamber of Deputies, 136 in the Senate) and another 161 pending, with BPS (25), ANEP (23) and Antel (12) as the main sending agencies to the Chamber of Deputies. On 7 February 2026 la diaria consulted specialists: University of the Republic administrative law professor Federico Baz described the system as a regime of fiction because of the lack of oversight over hours and duties, and the Citizen Corruption Observatory said one is left with the sense that things happen that cannot be proven but can be seen.',
      statusNote: 'The scheme remains in force and the rosters are updated on Parliament\'s website. La Mañana reported that, if the pending secondments are completed, the legislature would reach 589, five more than the previous one, and reported the statement of Chief Prosecutor Mónica Ferrero, who told legislators during the budget debate that seven staff had been seconded out after she took office, at an agency short of personnel. As of this file\'s closing (August 2026) there is no record of developments after 7 February 2026, nor of any rule requiring the scheme\'s cost to be published.',
      porQueImporta: 'The salary is still paid by the home agency: if a BPS or ANEP employee serves a legislator, that post may go unstaffed at the counter or in the classroom while the spending continues. With no published cost and no oversight of duties, taxpayers cannot know what this scheme costs them.',
      caveat: 'Secondments are payroll spending, not procurement: they have no counterpart in this site\'s contract search. The figures come from parliamentary rosters compiled by the press, include both authorised and pending secondments, and shift week to week depending on pending paperwork.',
    },
  },
  {
    slug: 'fondo-coronavirus-ejecucion-y-control',
    emoji: '🦠',
    theme: 'estado-y-fondos',
    period: '2020-2022',
    statusKind: 'gestion',
    status: 'terminado',
    amountReported: 'US$ 2.200 millones canalizados por el Fondo Coronavirus entre el 13 de marzo de 2020 y agosto de 2022, según El Observador',
    organisms: ['Ministerio de Economía y Finanzas', 'Ministerio de Salud Pública', 'Ministerio de Desarrollo Social', 'Banco de Previsión Social', 'Administración de los Servicios de Salud del Estado'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Ministerio de Economía y Finanzas',
        'Ministerio de Salud Pública',
        'Ex-Adm.Gral- Dir. General Secret.',
        'Dirección de Desarrollo Social',
        'Instituto Nacional de Alimentación',
        'Direc. General de Secretaría.',
        'Dirección Nacional de Protección Social',
        'Instituto Nacional de la Juventud',
        'Banco de Previsión Social',
      ],
      search: 'emergencia',
      yearFrom: 2020,
      yearTo: 2022,
    },
    sources: [
      { outlet: 'Ministerio de Economía y Finanzas', title: 'Fondo Coronavirus', url: 'https://www.gub.uy/ministerio-economia-finanzas/fondocovid' },
      { outlet: 'Montevideo Portal', title: 'Uruguay gastó 1.217 millones de dólares en la pandemia, un 2.3% del PBI', url: 'https://www.montevideo.com.uy/Noticias/Uruguay-gasto-1-217-millones-de-dolares-en-la-pandemia-un-2-3-del-DPBI-uc777648', date: '2021-02-08' },
      { outlet: 'Montevideo Portal', title: '¿En qué se gastó el dinero del Fondo Coronavirus?', url: 'https://www.montevideo.com.uy/Noticias/-En-que-se-gasto-del-dinero-del-Fondo-Coronavirus--uc777958', date: '2021-02-11' },
      { outlet: 'El Observador', title: 'MEF avanza en "desmonte" de Fondo Covid pero asegura que la plata "no va a faltar"', url: 'https://www.elobservador.com.uy/nota/mef-avanza-en-desmonte-de-fondo-covid-pero-asegura-que-la-plata-no-va-a-faltar--2022875018', date: '2022-08-07' },
    ],
    es: {
      title: 'Fondo Coronavirus: US$ 2.200 millones por fuera del presupuesto',
      dek: 'El fondo creado por la Ley 19.874 concentró el gasto de la pandemia en un carril propio; la oposición cuestionó que terminara financiando programas permanentes.',
      contexto: 'El Fondo Solidario COVID-19, creado por la Ley 19.874, concentró fuera del presupuesto ordinario el gasto de la emergencia sanitaria: seguro de paro, transferencias del Mides, compras de salud, vacunas y pérdida de recaudación del BPS. El Ministerio de Economía y Finanzas publica en su sitio los informes de gasto de 2020 y 2021, la rendición de cuentas de 2022 y una visualización interactiva del fondo. A partir de 2023 el gobierno dejó de asignarle recursos y los gastos que continuaban pasaron a atenderse por los presupuestos de cada ministerio.',
      hallazgo: 'El 8 de febrero de 2021 Montevideo Portal informó, en base a la conferencia de la ministra Azucena Arbeleche, que Uruguay destinó US$ 1.217 millones a la pandemia en 2020, 2,3% del PBI, de los cuales US$ 711 millones pasaron por el Fondo Coronavirus. En una nota del 11 de febrero de 2021, el mismo medio detalló el destino: US$ 238 millones en seguro de paro, US$ 213 millones en renuncia a aportes, US$ 212,9 millones por pérdida de recaudación del BPS, US$ 144 millones en medidas del Mides —incluidas canastas de alimentos por US$ 72,9 millones— y US$ 48 millones en salud pública, entre otros rubros. El 7 de agosto de 2022 El Observador informó que por el fondo habían pasado US$ 2.200 millones desde el 13 de marzo de 2020, con US$ 1.167 millones ejecutados en 2021 (US$ 448 millones en salud, US$ 427 millones en medidas económicas y US$ 293 millones en apoyo social).',
      statusNote: 'Según El Observador, el gobierno resolvió desmontar el fondo para 2023 sin recursos presupuestados; la ministra Arbeleche afirmó que no era lo que esperaban y el subsecretario Alejandro Irastorza aseguró que no iba a ser un corte automático. En esa nota, la oposición cuestionó que con un fondo de emergencia transitorio se hubieran financiado programas permanentes, como tobilleras electrónicas para casos de violencia doméstica y la contratación de unos 1.600 trabajadores de la salud. El MEF mantiene publicados los informes de ejecución. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores al desmonte.',
      porQueImporta: 'Fue el mayor gasto extraordinario del Estado uruguayo en décadas y se ejecutó por un carril separado del presupuesto que el Parlamento vota año a año. Saber en qué se gastó, y qué de eso quedó adentro del gasto permanente, define parte de lo que hoy se paga en impuestos y en deuda.',
      caveat: 'Buena parte del fondo fueron transferencias, subsidios y renuncia a aportes: no son compras y no aparecen en el buscador de contratos. Solo las adquisiciones de bienes y servicios de salud tienen contrapartida en el sistema de compras estatales.',
    },
    en: {
      title: 'Coronavirus Fund: US$2.2 billion outside the budget',
      dek: 'The fund created by Law 19,874 channelled pandemic spending through its own track; the opposition questioned that it ended up financing permanent programmes.',
      contexto: 'The COVID-19 Solidarity Fund, created by Law 19,874, concentrated emergency spending outside the ordinary budget: unemployment insurance, Mides transfers, health purchases, vaccines and lost BPS revenue. The Ministry of Economy and Finance publishes on its website the 2020 and 2021 spending reports, the 2022 accountability report and an interactive visualisation of the fund. From 2023 the government stopped allocating resources to it and continuing expenses were absorbed by each ministry\'s budget.',
      hallazgo: 'On 8 February 2021 Montevideo Portal reported, based on a press conference by Minister Azucena Arbeleche, that Uruguay spent US$1.217 billion on the pandemic in 2020, 2.3% of GDP, of which US$711 million went through the Coronavirus Fund. In a piece on 11 February 2021 the same outlet detailed the breakdown: US$238 million on unemployment insurance, US$213 million on waived contributions, US$212.9 million for lost BPS revenue, US$144 million on Mides measures —including US$72.9 million in food baskets— and US$48 million on public health, among other items. On 7 August 2022 El Observador reported that US$2.2 billion had passed through the fund since 13 March 2020, with US$1.167 billion executed in 2021 (US$448 million on health, US$427 million on economic measures and US$293 million on social support).',
      statusNote: 'According to El Observador, the government decided to wind the fund down for 2023 with no budgeted resources; Minister Arbeleche said it was not what they had expected and Deputy Minister Alejandro Irastorza assured it would not be an automatic cut. In that report, the opposition questioned that a temporary emergency fund had financed permanent programmes, such as electronic ankle monitors for domestic violence cases and the hiring of some 1,600 health workers. The Ministry keeps the execution reports published. As of this file\'s closing (August 2026) there is no record of developments after the wind-down.',
      porQueImporta: 'It was the largest extraordinary outlay by the Uruguayan State in decades, executed on a track separate from the budget Parliament votes each year. Knowing what it was spent on, and how much of it became permanent spending, shapes part of what is paid today in taxes and debt.',
      caveat: 'Much of the fund consisted of transfers, subsidies and waived contributions: these are not purchases and do not appear in the contract search. Only the procurement of health goods and services has a counterpart in the state procurement system.',
    },
  },
  {
    slug: 'registro-inmuebles-del-estado-sin-datos-confiables',
    emoji: '🏢',
    theme: 'estado-y-fondos',
    period: '2017-2025',
    statusKind: 'auditoria',
    status: 'auditoria',
    amountReported: 'US$ 1.124.406 recaudó el Estado por la venta de 22 inmuebles entre 2023 y 2024, según El Observador',
    organisms: ['Dirección Nacional de Catastro', 'Ministerio de Economía y Finanzas', 'Contaduría General de la Nación', 'Oficina de Planeamiento y Presupuesto'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Dirección Nacional de Catastro',
        'Ministerio de Economía y Finanzas',
        'Contaduría General de la Nación',
        'Casa Militar',
      ],
      search: 'arrendamiento',
      yearFrom: 2017,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'Búsqueda', title: 'Errores, inconsistencias y fallas de control impiden un "conocimiento veraz" de cuántos inmuebles tiene el Estado', url: 'https://www.busqueda.com.uy/economia/errores-inconsistencias-y-fallas-control-impiden-un-conocimiento-veraz-cuantos-inmuebles-tiene-el-estado-n5392949', date: '2024-09-03' },
      { outlet: 'El Observador', title: '"Pusimos la rueda a funcionar": entre 2023 y 2024 el Estado vendió 22 inmuebles por más de US$ 1 millón', url: 'https://www.elobservador.com.uy/nacional/pusimos-la-rueda-funcionar-2023-y-2024-el-estado-vendio-22-inmuebles-mas-us-1-millon-n6005110', date: '2025-06-22' },
      { outlet: 'En Perspectiva', title: 'Informe: El gobierno tiene unos 2.500 inmuebles entre edificios y terrenos', url: 'https://enperspectiva.uy/home/la-opp-prepara-sistema-de-gestion-inteligente-para-inmuebles-del-estado/', date: '2017-07-25' },
    ],
    es: {
      title: 'El Estado no sabe con certeza cuántos inmuebles tiene',
      dek: 'Una auditoría de la AIN halló tres hallazgos de severidad extrema en el registro de inmuebles estatales, mientras el Estado alquila locales y mantiene padrones vacíos.',
      contexto: 'El Registro Único de Inmuebles del Estado (RUIE), a cargo de la Dirección Nacional de Catastro, debe reunir todos los bienes inmuebles de propiedad o posesión estatal. Sobre ese inventario se apoya el Programa de Racionalización del Uso de Bienes Inmuebles del Estado (Prubie), que define qué padrones son prescindibles y pueden venderse o reasignarse. La discusión no es nueva: en julio de 2017 En Perspectiva informó que la Administración Central tenía unos 2.500 inmuebles —1.700 urbanos y 800 rurales— y que el entonces subdirector de la OPP, Martín Dibarboure, admitía que el Estado mantenía edificios vacíos mientras pagaba alquiler por locales privados, con la Torre Ejecutiva y sus 35.000 metros cuadrados como ejemplo, sin que nadie centralizara la información.',
      hallazgo: 'Búsqueda informó el 3 de septiembre de 2024 sobre un informe de la Auditoría Interna de la Nación de julio de 2024, que evaluó la gestión del RUIE por parte de la Dirección Nacional de Catastro entre enero de 2023 y marzo de 2024: las actividades de control no permiten optimizar la información de los inmuebles del Estado y las autoridades no pueden alcanzar un conocimiento veraz de cuántos inmuebles son de propiedad o posesión estatal. La auditoría clasificó tres hallazgos como de severidad extrema. Detectó cifras inconsistentes según el filtro utilizado —7.738 unidades catastrales a marzo de 2024 frente a 7.772 al filtrar por inciso, diferencia de 34 unidades que Catastro no pudo justificar—, mientras un cálculo previo de 2023 identificaba unos 8.832 registros; también halló padrones informados al Prubie que no figuraban en el RUIE y que, de 114 inmuebles declarados prescindibles entre 2022 y abril de 2024, el 75,43% seguía sin trámite.',
      statusNote: 'El Observador informó el 22 de junio de 2025 que entre 2023 y 2024 el Estado vendió 22 inmuebles por US$ 1.124.406 —17 en 2023 y 5 en 2024, a precios de entre US$ 4.000 y US$ 136.000— y que la Contaduría General de la Nación contabilizaba 369 padrones vacíos en 2020. La Dirección Nacional de Catastro asumió la gestión del programa, antes en la Contaduría General de la Nación. El exdirector de Catastro Augusto Alcalde sostuvo allí que los organismos se consideran no solo dueños sino administradores del patrimonio estatal, lo que frena las ventas, y estimó que entre 70 y 100 inmuebles declarados prescindibles podrían seguir el mismo camino. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores.',
      porQueImporta: 'Cada local que el Estado alquila teniendo un inmueble propio vacío es un gasto mensual evitable, pagado con impuestos. Y sin un inventario confiable no hay forma de saber cuánto se pierde ni de decidir qué vender, qué reasignar y qué destinar a vivienda o a servicios públicos.',
      caveat: 'El arrendamiento de inmuebles sí se tramita por el sistema de compras estatales, pero se registra con objetos genéricos y sin identificación del padrón, por lo que no puede cruzarse automáticamente con el registro de inmuebles propios.',
    },
    en: {
      title: 'The State does not know for certain how many properties it owns',
      dek: 'An audit by the National Internal Audit found three extreme-severity findings in the state property register, while the State rents premises and keeps vacant plots.',
      contexto: 'The Single Register of State Property (RUIE), run by the National Cadastre Directorate, is meant to list every property owned or held by the State. That inventory underpins the Programme for Rationalising the Use of State Real Estate (Prubie), which decides which plots are dispensable and can be sold or reassigned. The debate is not new: in July 2017 En Perspectiva reported that the Central Administration held around 2,500 properties —1,700 urban and 800 rural— and that OPP deputy director Martín Dibarboure acknowledged the State kept empty buildings while paying rent for private premises, citing the Torre Ejecutiva and its 35,000 square metres, with no one centralising the information.',
      hallazgo: 'Búsqueda reported on 3 September 2024 on a July 2024 report by the National Internal Audit, which assessed the National Cadastre Directorate\'s management of the RUIE between January 2023 and March 2024: control activities do not allow the information on state property to be optimised and the authorities cannot achieve true knowledge of how many properties the State owns or holds. The audit classified three findings as of extreme severity. It found inconsistent figures depending on the filter used —7,738 cadastral units as of March 2024 against 7,772 when filtering by budget sector, a 34-unit gap the Cadastre could not justify— while an earlier 2023 calculation identified some 8,832 records; it also found plots reported to Prubie that did not appear in the RUIE, and that of 114 properties declared dispensable between 2022 and April 2024, 75.43% remained unprocessed.',
      statusNote: 'El Observador reported on 22 June 2025 that between 2023 and 2024 the State sold 22 properties for US$1,124,406 —17 in 2023 and 5 in 2024, at prices between US$4,000 and US$136,000— and that the General Accounting Office counted 369 vacant plots in 2020. The National Cadastre Directorate took over the programme from the General Accounting Office. Former cadastre director Augusto Alcalde said there that agencies consider themselves not just owners but managers of state assets, which slows sales, and estimated that between 70 and 100 properties declared dispensable could follow the same path. As of this file\'s closing (August 2026) there is no record of later developments.',
      porQueImporta: 'Every premises the State rents while owning an empty building of its own is an avoidable monthly cost paid with taxes. And without a reliable inventory there is no way to know how much is lost, or to decide what to sell, what to reassign and what to devote to housing or public services.',
      caveat: 'Property leases are processed through the state procurement system, but they are recorded with generic descriptions and no plot identifier, so they cannot be automatically cross-referenced with the register of state-owned property.',
    },
  },
  {
    slug: 'asse-gastos-sin-credito-auditoria-nacion',
    emoji: '🏥',
    theme: 'estado-y-fondos',
    period: '2024-2025',
    statusKind: 'auditoria',
    status: 'auditoria',
    amountReported: '$ 2.436 millones (US$ 58,5 millones) comprometidos sin crédito disponible al 30 de setiembre de 2024, según Búsqueda',
    organisms: ['Administración de los Servicios de Salud del Estado', 'Auditoría Interna de la Nación', 'Ministerio de Economía y Finanzas'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Auditoría Interna de la Nación',
        'Ministerio de Economía y Finanzas',
      ],
      yearFrom: 2024,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'Búsqueda', title: 'ASSE: informe de la Auditoría Interna de la Nación constató "apartamientos normativos", pagos con atraso y falta de controles', url: 'https://www.busqueda.com.uy/economia/asse-informe-la-auditoria-interna-la-nacion-constato-apartamientos-normativos-pagos-atraso-y-falta-controles-n5397253', date: '2025-03-20' },
      { outlet: 'El Observador', title: 'Auditoría detectó "apartamientos normativos" en ASSE vinculados a gastos, compras y controles', url: 'https://www.elobservador.com.uy/nacional/auditoria-detecto-apartamientos-normativos-asse-vinculados-gastos-compras-y-controles-n5990830', date: '2025-03-21' },
      { outlet: 'Telenoche', title: 'Auditoría Interna de la Nación detectó graves irregularidades en ASSE y millonarias deudas pendientes', url: 'https://www.telenoche.com.uy/nacionales/auditoria-interna-la-nacion-detecto-graves-irregularidades-asse-y-millonarias-deudas-pendientes-n5381856', date: '2025-03-21' },
      { outlet: 'Auditoría Interna de la Nación (MEF)', title: 'ASSE - Comisión de Apoyo de los Programas Asistenciales Especiales (UE 068)', url: 'https://www.gub.uy/ministerio-economia-finanzas/comunicacion/publicaciones/asse-comision-apoyo-programas-asistenciales-especiales-ue-068', date: '2025-07-22' },
    ],
    es: {
      title: 'La AIN detectó en ASSE US$ 58 millones comprometidos sin crédito',
      dek: 'La Auditoría Interna de la Nación revisó enero-setiembre de 2024 en ASSE y encontró gastos sin respaldo presupuestal y pagos con seis meses de atraso promedio.',
      contexto: 'La Administración de los Servicios de Salud del Estado (ASSE) es el mayor prestador público de salud y uno de los mayores compradores del Estado. El artículo 15 del TOCAF prohíbe comprometer gastos de funcionamiento o de inversión sin que exista crédito disponible: primero el crédito, después la orden de compra. En marzo de 2025, ya con las nuevas autoridades designadas por el gobierno de Yamandú Orsi, se conoció un informe de la Auditoría Interna de la Nación (AIN) —el órgano de control interno que funciona en la órbita del Ministerio de Economía y Finanzas— sobre la gestión de ASSE entre enero y setiembre de 2024.',
      hallazgo: 'Según Búsqueda del 20 de marzo de 2025, la AIN constató que ASSE comprometió gastos sin crédito disponible por $ 2.436.323.394 (unos US$ 58,5 millones) al 30 de setiembre de 2024, recogió una estimación de la Tesorería de un atraso promedio de pagos de seis meses hacia enero de 2025 y advirtió que la situación se reiteró a lo largo de los años: la unidad de auditoría interna registró trece actuaciones vinculadas a procesos de compra entre 2015 y 2022 que señalaban los mismos problemas de atrasos y controles insuficientes. El Observador informó el 21 de marzo de 2025 que el crédito autorizado para 2024, con refuerzos, llegó a $ 24.227 millones mientras las obligaciones asumidas alcanzaban $ 65.272 millones al 20 de enero de 2025, y consignó la misma cifra de $ 2.436 millones sin financiamiento a setiembre de 2024, que al tipo de cambio que aplicó equivalían a US$ 55,3 millones. Telenoche informó ese mismo día que la deuda acumulada pendiente rondaba los US$ 120 millones.',
      statusNote: 'El informe se conoció en marzo de 2025 a través de Búsqueda y El País, y fue replicado por Telenoche y El Observador. La AIN señaló que ASSE no presentó planes de acción para todas las observaciones realizadas. Desde ASSE se respondió, según Búsqueda, que se priorizaron los pagos a prestadores de servicios esenciales, a proveedores sensibles al flujo de caja, a empresas tercerizadas y a pequeños proveedores locales, con algunas excepciones ante amenazas de corte de servicio. El 22 de julio de 2025 la AIN publicó además una auditoría específica sobre la Comisión de Apoyo de los Programas Asistenciales Especiales de ASSE (UE 068). Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores.',
      porQueImporta: 'Cuando ASSE compra sin crédito disponible y paga con seis meses de atraso, los proveedores cargan ese riesgo al precio o directamente dejan de presentarse. Lo termina pagando el usuario del hospital público, en insumos más caros, llamados desiertos y demoras en la atención.',
      caveat: 'Las cifras en dólares difieren según la fuente (US$ 55,3 millones, US$ 58,5 millones o unos US$ 60 millones) porque dependen del tipo de cambio y de la fecha de corte, aunque todas parten del mismo monto en pesos. El informe mide compromisos asumidos sin crédito, no acredita sobreprecios ni compras irregulares.',
    },
    en: {
      title: 'The AIN found US$58 million committed at ASSE without budget',
      dek: 'The National Internal Audit reviewed January-September 2024 at ASSE and found spending with no budget backing and payments running six months late on average.',
      contexto: 'The State Health Services Administration (ASSE) is Uruguay\'s largest public health provider and one of the State\'s biggest buyers. Article 15 of the TOCAF financial code bars committing operating or investment spending without available budget credit: credit first, purchase order second. In March 2025, with new authorities appointed by the Yamandú Orsi government already in place, a report by the National Internal Audit (AIN) —the internal control body within the Ministry of Economy and Finance— on ASSE\'s management between January and September 2024 became public.',
      hallazgo: 'According to Búsqueda on 20 March 2025, the AIN found that ASSE had committed spending without available credit of $2,436,323,394 pesos (some US$58.5 million) as of 30 September 2024, reported a Treasury estimate of an average payment delay of six months towards January 2025, and warned that the situation had recurred over the years: the internal audit unit recorded thirteen actions related to procurement processes between 2015 and 2022 flagging the same problems of delays and insufficient controls. El Observador reported on 21 March 2025 that the authorised credit for 2024, including reinforcements, reached $24,227 million pesos while obligations assumed reached $65,272 million pesos as of 20 January 2025, and gave the same figure of $2,436 million pesos unfinanced as of September 2024, which at the exchange rate it applied came to US$55.3 million. Telenoche reported the same day that accumulated pending debt was around US$120 million.',
      statusNote: 'The report became public in March 2025 through Búsqueda and El País and was picked up by Telenoche and El Observador. The AIN noted that ASSE did not submit action plans for all the observations made. ASSE responded, according to Búsqueda, that it prioritised payments to essential service providers, to suppliers sensitive to cash flow, to outsourced companies and to small local suppliers, with some exceptions in the face of threats to cut services. On 22 July 2025 the AIN also published a specific audit of ASSE\'s Support Commission for Special Assistance Programmes (UE 068). As of this file\'s closing (August 2026) there is no record of later developments.',
      porQueImporta: 'When ASSE buys without available credit and pays six months late, suppliers price that risk in or simply stop bidding. Public hospital users end up paying for it, through costlier supplies, failed tenders and delays in care.',
      caveat: 'The dollar figures differ by source (US$55.3 million, US$58.5 million or around US$60 million) because they depend on the exchange rate and the cut-off date, although all start from the same peso amount. The report measures commitments made without credit; it does not establish overpricing or irregular purchases.',
    },
  },
  {
    slug: 'jutep-declaraciones-juradas-reservadas',
    emoji: '📄',
    theme: 'estado-y-fondos',
    period: '2020-2025',
    statusKind: 'debate',
    status: 'debate',
    organisms: ['Junta de Transparencia y Ética Pública', 'Poder Legislativo'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Junta de Transparencia y Etica Pública-JUTEP',
        'Junta de Transparencia y Etica Publica',
        'Comisión Administrativa del Poder Legislativo',
      ],
      search: 'transparencia',
      yearFrom: 2020,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'Búsqueda', title: 'Jutep no publicará declaraciones juradas', url: 'https://www.busqueda.com.uy/Secciones/Jutep-no-publicara-declaraciones-juradas-uc1428', date: '2020-09-10' },
      { outlet: 'El Observador', title: 'Jutep evalúa descargos de Sartori y se encamina a sancionarlo por no presentar declaración jurada de su esposa', url: 'https://www.elobservador.com.uy/nota/junta-anticorrupcion-evalua-descargos-de-sartori-y-se-encamina-a-sancionarlo-2023102019250', date: '2023-10-21' },
      { outlet: 'Subrayado', title: 'Senado rechazó por unanimidad pedido de Juan Sartori para suspender la sanción que le impuso la Jutep', url: 'https://www.subrayado.com.uy/senado-rechazo-unanimidad-pedido-juan-sartori-suspender-la-sancion-que-le-impuso-la-jutep-n945809', date: '2024-05-07' },
      { outlet: 'Junta de Transparencia y Ética Pública', title: 'Publicación de omisos 2025', url: 'https://www.gub.uy/junta-transparencia-etica-publica/comunicacion/publicaciones/publicacion-omisos-2025', date: '2025-12-31' },
    ],
    es: {
      title: 'Declaraciones juradas: reservadas y con sanción de medio sueldo',
      dek: 'La JUTEP resolvió no publicar las declaraciones patrimoniales de los legisladores en ejercicio y su única sanción por no presentarlas es retener el 50% del sueldo.',
      contexto: 'La Ley 17.060, de 1998, obliga a los funcionarios comprendidos en sus artículos 10 y 11 —presidente, ministros, legisladores, intendentes, directores de entes y miles de funcionarios más— a presentar una declaración jurada de bienes e ingresos ante la Junta de Transparencia y Ética Pública (JUTEP). Quien no cumple es declarado omiso por el organismo e incluido en una nómina que se publica en su sitio. La JUTEP no destituye ni multa: la consecuencia prevista es comunicar el incumplimiento al organismo correspondiente para que se retenga el 50% del sueldo hasta regularizar.',
      hallazgo: 'El 10 de setiembre de 2020 Búsqueda informó que la JUTEP resolvió no publicar las declaraciones juradas de senadores y diputados en ejercicio, pese a que la ley revisada —vigente desde el 1º de marzo— disponía su publicación: su presidenta, Susana Signorino, sostuvo que los legisladores habían asumido el 15 de febrero, antes de esa fecha. El diputado Daniel Caggiani (MPP) calificó esa lectura como una interpretación equivocada de la ley en la comisión parlamentaria del 8 de setiembre. Sobre el alcance real de la sanción, El Observador informó el 21 de octubre de 2023, a propósito del senador Juan Sartori —que no presentó la declaración de su esposa—, que la resolución de omiso se publica en la página de la Jutep y se notifica al Parlamento para la retención del 50% del salario. Sartori pidió el archivo alegando que se casó con la persona y no con el patrimonio, y sostuvo que había decenas de omisiones similares que no habían sido citadas.',
      statusNote: 'El 7 de mayo de 2024 Subrayado informó que el Senado rechazó por unanimidad el pedido de Sartori para suspender la sanción, al entender que solo la JUTEP puede levantarla y que el Parlamento le pagará todo el salario retenido si deja de estar omiso. La JUTEP mantiene la práctica de publicar las nóminas de omisos: la publicación correspondiente a 2025, con listas por cuatrimestre y por gobiernos departamentales, está fechada el 31 de diciembre de 2025 en su sitio oficial. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores.',
      porQueImporta: 'La declaración jurada es la principal herramienta para detectar enriquecimiento inexplicado de quien maneja dinero público. Que sea reservada, y que la única consecuencia de no presentarla sea retener medio sueldo, define cuánto puede controlar realmente un ciudadano a quien decide sobre miles de millones de pesos.',
      caveat: 'Este caso no involucra compras ni contratos: no tiene contrapartida en el buscador de este sitio. Las nóminas de omisos publicadas por la JUTEP son la única información pública sobre incumplimientos y no incluyen el contenido de las declaraciones.',
    },
    en: {
      title: 'Asset declarations: kept private, penalty is half a salary',
      dek: 'JUTEP decided not to publish sitting legislators\' asset declarations, and its only sanction for failing to file is withholding 50% of the official\'s salary.',
      contexto: 'Law 17,060, of 1998, requires the officials covered by its articles 10 and 11 —the president, ministers, legislators, departmental mayors, agency directors and thousands more staff— to file a sworn declaration of assets and income with the Public Transparency and Ethics Board (JUTEP). Anyone who fails to comply is declared \'omiso\' and added to a list published on its website. JUTEP cannot dismiss or fine: the prescribed consequence is to report the breach to the relevant body so that 50% of the salary is withheld until compliance.',
      hallazgo: 'On 10 September 2020 Búsqueda reported that JUTEP resolved not to publish the asset declarations of sitting senators and deputies, even though the revised law —in force since 1 March— provided for their publication: its president, Susana Signorino, argued that the legislators had taken office on 15 February, before that date. Deputy Daniel Caggiani (MPP) called that an incorrect reading of the law at the parliamentary committee on 8 September. On the sanction\'s real reach, El Observador reported on 21 October 2023, in the case of Senator Juan Sartori —who did not file his wife\'s declaration— that the \'omiso\' ruling is published on JUTEP\'s website and notified to Parliament so that 50% of the salary is withheld. Sartori asked for the case to be dropped, arguing he married the person and not the assets, and said there were dozens of similar omissions that had not been summoned.',
      statusNote: 'On 7 May 2024 Subrayado reported that the Senate unanimously rejected Sartori\'s request to suspend the sanction, holding that only JUTEP can lift it and that Parliament will pay him all the withheld salary if he ceases to be a non-filer. JUTEP maintains the practice of publishing the lists of non-filers: the 2025 publication, with lists by four-month period and for departmental governments, is dated 31 December 2025 on its official site. As of this file\'s closing (August 2026) there is no record of later developments.',
      porQueImporta: 'The asset declaration is the main tool for detecting unexplained enrichment by those handling public money. That it is kept private, and that the only consequence of not filing is losing half a salary, defines how much a citizen can really scrutinise someone deciding over billions of pesos.',
      caveat: 'This case involves no purchases or contracts: it has no counterpart in this site\'s search. The lists of non-filers published by JUTEP are the only public information on breaches and do not include the content of the declarations.',
    },
  },
  {
    slug: 'intendencia-montevideo-gastos-observados-tribunal',
    emoji: '🏛️',
    theme: 'estado-y-fondos',
    period: '2024-2025',
    statusKind: 'auditoria',
    status: 'auditoria',
    amountReported: 'Más de US$ 207,8 millones en 74 gastos observados por el Tribunal de Cuentas durante 2024, según Búsqueda',
    organisms: ['Intendencia de Montevideo', 'Tribunal de Cuentas'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Intendencia de Montevideo',
        'Tribunal de Cuentas',
      ],
      search: 'arrendamiento',
      yearFrom: 2024,
      yearTo: 2025,
    },
    investigationPath: '/investigaciones/intendencia-montevideo',
    sources: [
      { outlet: 'Búsqueda', title: 'Intendencia de Montevideo: en 2024 TCR observó gastos por US$ 207 millones y equipo de Lema denuncia "prioridades desordenadas"', url: 'https://www.busqueda.com.uy/informacion/intendencia-montevideo-2024-tcr-observo-gastos-us-207-millones-y-equipo-lema-denuncia-prioridades-desordenadas-n5397957', date: '2025-04-10' },
      { outlet: 'El Observador', title: 'Intendencia de Montevideo cerró 2024 con un déficit de US$ 82 millones y tiene un acumulado de US$ 497 millones', url: 'https://www.elobservador.com.uy/nacional/en-2024-la-intendencia-montevideo-tuvo-un-deficit-us-82-millones-y-tiene-un-acumulado-us-497-millones-n6007209', date: '2025-07-04' },
      { outlet: 'la diaria', title: 'La reducción del déficit de la Intendencia de Montevideo: en qué situación se encuentran las finanzas de la comuna capitalina', url: 'https://ladiaria.com.uy/verifica/articulo/2026/7/la-reduccion-del-deficit-de-la-intendencia-de-montevideo-en-que-situacion-se-encuentran-las-finanzas-de-la-comuna-capitalina/', date: '2026-06-30' },
    ],
    es: {
      title: 'El Tribunal de Cuentas observó US$ 207 millones de gastos de la IM',
      dek: 'En 2024 el órgano de control objetó 74 gastos de la Intendencia de Montevideo, en su mayoría por comprometer sin crédito disponible, y la comuna los reiteró igual.',
      contexto: 'El Tribunal de Cuentas controla la legalidad del gasto público, pero no puede impedirlo: cuando observa un gasto, el organismo puede reiterarlo bajo su responsabilidad y ejecutarlo igual. La observación queda registrada y se comunica a la Asamblea General o a la Junta Departamental, sin otra consecuencia automática. La causal más frecuente es el artículo 15 del TOCAF, que prohíbe comprometer gastos de funcionamiento o de inversión sin crédito disponible. La Intendencia de Montevideo es uno de los organismos con más gastos observados del país.',
      hallazgo: 'Búsqueda informó el 10 de abril de 2025 que en 2024 el Tribunal de Cuentas observó 74 gastos de la Intendencia de Montevideo por más de US$ 207,8 millones, en su mayoría por comprometer gastos sin crédito disponible, y que entre el 1º de enero y el 6 de marzo de 2025 ya había observado otros 12 gastos por US$ 75 millones, siete de ellos por la misma causal. La nota consigna que la comuna reiteró los gastos observados, incluido el arrendamiento de máquinas tragamonedas para el Casino Parque Hotel, objetado durante doce años seguidos y con US$ 30 millones solo en 2024, y partidas especiales a inspectores departamentales aprobadas pese a objeciones previas. El relevamiento fue difundido por Agustina Maschwitz, coordinadora técnica de Modernización y Simplificación Normativa del equipo del entonces candidato a intendente Martín Lema, que habló de prioridades desordenadas; la misma nota señala que el 94% de las compras de 2023 fueron compras directas frente a 6% por licitación.',
      statusNote: 'El Observador informó el 4 de julio de 2025 que la Intendencia cerró 2024 con un déficit de $ 3.640 millones (unos US$ 82,6 millones) —ocho veces el de 2023, de $ 439 millones— y un acumulado cercano a $ 22.000 millones (US$ 497,4 millones); la comuna lo atribuyó a adversidades económicas, menores transferencias del gobierno central y la eliminación del impuesto a las materias inflamables. El 30 de junio de 2026 la diaria verificó que bajo la administración de Mario Bergara el déficit presupuestal cayó cerca de 70%, de unos US$ 60 millones a US$ 18 millones, pasando de -7,27% de los ingresos en 2024 a -2,21% en 2025. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores.',
      porQueImporta: 'Comprometer gastos sin crédito es gastar plata que todavía no está disponible: se paga tarde, se acumula deuda y el proveedor traslada ese riesgo al precio. En Montevideo eso convive con un déficit acumulado de casi US$ 500 millones que se cubre con tributos departamentales o con menos servicios.',
      caveat: 'Las observaciones del Tribunal de Cuentas señalan incumplimientos de procedimiento presupuestal; no implican sobreprecio ni delito. El monto observado no equivale a un perjuicio: incluye gastos legítimos tramitados fuera de plazo o sin crédito disponible. El relevamiento de 2024 fue difundido por el equipo de un candidato opositor en plena campaña departamental.',
    },
    en: {
      title: 'Audit court flagged US$207 million of Montevideo city spending',
      dek: 'In 2024 the oversight body objected to 74 items of Montevideo city government spending, mostly for committing without available credit, and the city reaffirmed them anyway.',
      contexto: 'The Court of Accounts checks the legality of public spending but cannot stop it: when it flags an expense, the agency can \'reiterate\' it under its own responsibility and execute it anyway. The observation is recorded and reported to the General Assembly or the Departmental Board, with no other automatic consequence. The most frequent ground is article 15 of the TOCAF financial code, which bars committing operating or investment spending without available credit. The Montevideo city government is among the country\'s most-flagged bodies.',
      hallazgo: 'Búsqueda reported on 10 April 2025 that in 2024 the Court of Accounts flagged 74 items of Montevideo city spending worth more than US$207.8 million, mostly for committing expenses without available credit, and that between 1 January and 6 March 2025 it had already flagged another 12 items worth US$75 million, seven of them on the same ground. The report notes that the city reaffirmed the flagged spending, including the lease of slot machines for the Casino Parque Hotel, objected to for twelve consecutive years and worth US$30 million in 2024 alone, and special allowances for departmental inspectors approved despite earlier objections. The compilation was circulated by Agustina Maschwitz, technical coordinator for Modernisation and Regulatory Simplification on the team of then mayoral candidate Martín Lema, who spoke of disorderly priorities; the same report says 94% of 2023 purchases were direct awards against 6% by tender.',
      statusNote: 'El Observador reported on 4 July 2025 that the city closed 2024 with a deficit of $3,640 million pesos (some US$82.6 million) —eight times the 2023 figure of $439 million— and an accumulated shortfall of nearly $22 billion pesos (US$497.4 million); the city attributed it to economic adversity, lower central government transfers and the elimination of the flammable materials tax. On 30 June 2026 la diaria\'s fact-check found that under Mario Bergara\'s administration the budget deficit fell by around 70%, from some US$60 million to US$18 million, going from -7.27% of revenues in 2024 to -2.21% in 2025. As of this file\'s closing (August 2026) there is no record of later developments.',
      porQueImporta: 'Committing spending without credit means spending money that is not yet available: payment comes late, debt piles up and suppliers price that risk in. In Montevideo this coexists with an accumulated deficit of almost US$500 million covered by departmental taxes or by fewer services.',
      caveat: 'Observations by the Court of Accounts flag breaches of budget procedure; they do not imply overpricing or a crime. The flagged amount is not a loss: it includes legitimate spending processed late or without available credit. The 2024 compilation was circulated by an opposition candidate\'s team in the middle of the departmental campaign.',
    },
  },
  {
    slug: 'asse-circulo-catolico-convenio-observado',
    emoji: '⛪',
    theme: 'estado-y-fondos',
    period: '2020-2026',
    statusKind: 'judicial',
    status: 'investigacion',
    amountReported: '$ 2.331 millones pagados por ASSE al Círculo Católico en convenios entre 2020 y 2024, según la diaria',
    organisms: ['Administración de los Servicios de Salud del Estado', 'Ministerio de Salud Pública'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Ministerio de Salud Pública',
      ],
      yearFrom: 2020,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'la diaria', title: 'ASSE: el 70% del gasto en convenios con el Círculo Católico fue observado por el Tribunal de Cuentas entre 2020 y 2024', url: 'https://ladiaria.com.uy/politica/articulo/2026/5/asse-el-70-del-gasto-en-convenios-con-el-circulo-catolico-fue-observado-por-el-tribunal-de-cuentas-entre-2020-y-2024/', date: '2026-05-03' },
      { outlet: 'Búsqueda', title: 'MSP elevará a Fiscalía una investigación que señala irregularidades en un convenio de ASSE con el Círculo Católico', url: 'https://www.busqueda.com.uy/informacion/msp-elevara-fiscalia-una-investigacion-que-senala-irregularidades-un-convenio-asse-el-circulo-catolico-n5413168', date: '2026-05-13' },
      { outlet: 'El Observador', title: 'Jurídica del MSP sugiere "evaluar" denuncia a Satdjian ante Fiscalía por firma de 2022 para habilitar el convenio entre ASSE y el Círculo Católico', url: 'https://www.elobservador.com.uy/nacional/juridica-del-msp-sugiere-evaluar-denuncia-satdjian-fiscalia-firma-2022-habilitar-el-convenio-asse-y-el-circulo-catolico-n6043797', date: '2026-05-13' },
    ],
    es: {
      title: 'ASSE-Círculo Católico: 70% del gasto observado por el Tribunal',
      dek: 'Entre 2020 y 2024 ASSE pagó $ 2.331 millones al Círculo Católico por convenios; el Tribunal de Cuentas observó el 70% y, según la diaria, ASSE reiteró la mayoría de esos gastos.',
      contexto: 'Los convenios de complementación asistencial permiten que ASSE derive prestaciones a instituciones privadas sin licitación, invocando causales de excepción del régimen de contratación. Entre 2020 y 2024 ASSE firmó y renovó convenios de ese tipo con el Círculo Católico de Obreros del Uruguay, mutualista que compró parte del patrimonio de la liquidada Casa de Galicia por US$ 15,3 millones, según El Observador. En 2022 se tramitó la habilitación ministerial del convenio. Con el cambio de gobierno en 2025, el Ministerio de Salud Pública abrió una investigación administrativa sobre ese trámite.',
      hallazgo: 'El 3 de mayo de 2026 la diaria informó que el Tribunal de Cuentas observó el 70% del gasto de ASSE en convenios con el Círculo Católico entre 2020 y 2024, sobre un total de $ 2.331 millones, y que la mayoría de esos gastos observados fueron reiterados por el organismo; según esa nota, el punto en discusión es el uso reiterado de mecanismos de excepción y el diseño de convenios por precio unitario y plazos indefinidos con prórroga automática, que dificulta al control determinar los montos comprometidos. El 13 de mayo de 2026 Búsqueda informó que la investigación administrativa del MSP concluyó que el entonces subsecretario José Luis Satdjian firmó la habilitación el 9 de setiembre de 2022 sin que existiera impedimento de hecho ni de derecho para que la firmara el ministro Daniel Salinas —que ese día estaba en funciones y firmó otras dos resoluciones ministeriales— y que el trámite del convenio con el Círculo demoró 42 días frente a 61 de uno comparable con CASMU, sin justificación técnica en el expediente. Según esa nota, los pagos de ASSE al Círculo crecieron 170% entre 2020 y 2024.',
      statusNote: 'El Observador informó el 13 de mayo de 2026 que la Dirección de Servicios Jurídicos del MSP concluyó que la firma de Satdjian no se ajustó a derecho y que su director, Martín Esposto, sugirió evaluar el traslado de los hechos a la Fiscalía, ya que Satdjian no mantiene vínculo funcional con el MSP que habilite una sanción administrativa. Satdjian defendió su actuación: en declaraciones a Radio Montecarlo de noviembre de 2025 recogidas por esa nota sostuvo que, para evitar suspicacias por su vínculo previo con el Círculo, Salinas había firmado una resolución delegándole todos los trámites vinculados a la mutualista, y agregó que su firma no está solo en la aprobación del convenio sino también en las multas, en la habilitación de los tomógrafos y en todos los trámites de esos cinco años. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores al 13 de mayo de 2026.',
      porQueImporta: 'Cuando el prestador público compra servicios de salud por excepción y no por licitación, no hay competencia que discipline el precio: ASSE paga lo que se pacta. Son consultas, cirugías y camas para usuarios del sistema público, financiadas con impuestos y aportes de todos.',
      caveat: 'Los $ 2.331 millones son lo facturado por el Círculo Católico a ASSE en convenios durante cinco años, no el monto cuestionado. Una observación del Tribunal de Cuentas señala un apartamiento de procedimiento; no acredita sobreprecio ni delito. No hay imputados: al cierre de esta ficha lo que consta es una investigación administrativa concluida y una sugerencia de elevar los hechos a la Fiscalía.',
    },
    en: {
      title: 'ASSE-Círculo Católico: 70% of the spending flagged by auditors',
      dek: 'Between 2020 and 2024 ASSE paid $2,331 million pesos to Círculo Católico under agreements; the Court of Accounts flagged 70% and, per la diaria, ASSE reaffirmed most of that spending.',
      contexto: 'Complementary care agreements let ASSE outsource services to private institutions without a tender, invoking exception grounds in the procurement rules. Between 2020 and 2024 ASSE signed and renewed such agreements with the Círculo Católico de Obreros del Uruguay, a health provider that bought part of the assets of the liquidated Casa de Galicia for US$15.3 million, according to El Observador. In 2022 the ministerial authorisation of the agreement was processed. After the change of government in 2025, the Ministry of Public Health opened an administrative investigation into that process.',
      hallazgo: 'On 3 May 2026 la diaria reported that the Court of Accounts flagged 70% of ASSE\'s spending on agreements with Círculo Católico between 2020 and 2024, out of a total of $2,331 million pesos, and that most of that flagged spending was reaffirmed by the agency; according to that report, the issue in dispute is the repeated use of exception mechanisms and the design of agreements based on unit prices and open-ended terms with automatic renewal, which makes it hard for auditors to determine the amounts committed. On 13 May 2026 Búsqueda reported that the health ministry\'s administrative investigation concluded that then deputy minister José Luis Satdjian signed the authorisation on 9 September 2022 with no factual or legal impediment to Minister Daniel Salinas signing it —Salinas was on duty that day and signed two other ministerial resolutions— and that the Círculo agreement took 42 days to process against 61 days for a comparable CASMU deal, with no technical justification on file. According to that report, ASSE\'s payments to Círculo rose 170% between 2020 and 2024.',
      statusNote: 'El Observador reported on 13 May 2026 that the ministry\'s Legal Services Division concluded Satdjian\'s signature did not comply with the law and that its director, Martín Esposto, suggested evaluating referral of the facts to the Prosecution Service, since Satdjian no longer has a functional link to the ministry that would allow administrative discipline. Satdjian defended his conduct: in remarks to Radio Montecarlo in November 2025 quoted in that report, he said that to avoid any suspicion arising from his earlier link to Círculo, Salinas had signed a resolution delegating to him all procedures involving the provider, and added that his signature appears not only on the approval of the agreement but also on the fines, the licensing of the CT scanners and every procedure over those five years. As of this file\'s closing (August 2026) there is no record of developments after 13 May 2026.',
      porQueImporta: 'When the public provider buys health services by exception rather than by tender, there is no competition to discipline the price: ASSE pays what is agreed. These are consultations, surgeries and beds for public system users, financed by everyone\'s taxes and contributions.',
      caveat: 'The $2,331 million pesos is what Círculo Católico billed ASSE under agreements over five years, not the questioned amount. An observation by the Court of Accounts flags a procedural departure; it does not establish overpricing or a crime. No one has been charged: as of this file\'s closing what exists is a concluded administrative investigation and a suggestion to refer the facts to prosecutors.',
    },
  },
  {
    slug: 'flota-vehicular-del-estado-sigue-creciendo',
    emoji: '🚙',
    theme: 'estado-y-fondos',
    period: '2019-2025',
    statusKind: 'gestion',
    status: 'sin-resolver',
    organisms: ['Ministerio del Interior', 'Administración Nacional de Usinas y Trasmisiones Eléctricas (UTE)', 'Intendencia de Montevideo', 'Obras Sanitarias del Estado', 'Ministerio de Transporte y Obras Públicas', 'Administración Nacional de Combustibles, Alcohol y Portland (ANCAP)'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Secretaría del Ministerio del Interior',
        'Dir.Nac.Cárceles,Penitenciarías y Centros de Recuperación',
        'Dirección Nacional de Policía de Tránsito',
        'Jefatura de Policía de Maldonado',
        'Dirección Nacional de Sanidad Policial',
        'Jefatura de Policía de Rivera',
        'Jefatura de Policía de Montevideo',
        'Dirección Nacional de Asuntos Sociales',
        'Jefatura de Policía de Salto',
        'Jefatura de Policía de Cerro Largo',
        'Jefatura de Policía de Tacuarembó',
        'Jefatura de Policía de Paysandú',
        'Dirección Nacional de Bomberos',
        'Jefatura de Policía de Durazno',
        'Jefatura de Policía de Lavalleja',
        'Jefatura de Policía de Colonia',
        'Jefatura de Policía de Artigas',
        'Jefatura de Policía de Rocha',
        'Jefatura de Policía de Canelones',
        'Jefatura de Policía de San José',
        'Jefatura de Policía de Soriano',
        'Dirección Nacional de Identificación Civil',
        'Jefatura de Policía de Flores',
        'Jefatura de Policía de Río Negro',
        'Dirección Nacional de Migración',
        'Dirección Nacional de Policia Cientifica',
        'Escuela Nacional de Policía',
        'Instituto Nacional de Rehabilitación',
        'Jefatura de Policía de Florida',
        'Jefatura de Policía de Teinta y Tres',
        'Dirección Nacional de Asistencia Social Policial',
        'Guardia Republicana',
        'Dirección Nacional de Policía Caminera',
        'Dirección Nacional de la Seguridad Rural',
        'Dirección Nacional de Policía Científica',
        'Dirección Nacional de Asistencia y Seguridad Social Policial',
        'Dirección Nacional de Información e Inteligencia',
        'Jefatura de Policía de Treinta y Tres',
        'Dirección Nacional de Prevención Social del Delito',
        'Administración Nacional de Usinas y Trasmisiones Eléctricas',
        'Intendencia de Montevideo',
        'Administración de las Obras Sanitarias del Estado',
        'Ministerio de Transporte y Obras Públicas',
        'Administración Nacional de Combustible, Alcohol y Portland',
      ],
      search: 'vehículo',
      yearFrom: 2019,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'Búsqueda', title: 'La flota oficial volvió a crecer el año pasado y son casi 18.500 los vehículos del Estado', url: 'https://www.busqueda.com.uy/economia/la-flota-oficial-volvio-crecer-el-ano-pasado-y-son-casi-18500-los-vehiculos-del-estado-n5409896', date: '2026-02-12' },
      { outlet: 'El Observador', title: 'Pasan los gobiernos y la flota de vehículos del Estado no para de crecer: ya son 18.480', url: 'https://www.elobservador.com.uy/nacional/pasan-los-gobiernos-y-la-flota-vehiculos-del-estado-no-crecer-ya-son-18480-n6034282', date: '2026-02-12' },
      { outlet: 'UyPress', title: 'Las intendencias tienen 6.000 vehículos sobre un total de 18.500 que componen la flota del Estado', url: 'https://www.uypress.net/Actualidad/Las-intendencias-tienen-6-000-vehiculos-sobre-un-total-de-18-500-que-componen-la-flota-del-Estado-uc150390', date: '2026-02-19' },
    ],
    es: {
      title: 'La flota del Estado ya son 18.480 vehículos y sigue creciendo',
      dek: 'Pasan los gobiernos y el parque automotor estatal no para de aumentar: 332 unidades más en 2025, según datos de Ancap relevados por Búsqueda y El Observador.',
      contexto: 'El Sistema Computarizado de Contralor Vehicular (Sisconve), administrado por Ancap, registra los vehículos oficiales del Estado y el combustible que consumen. Es la única fuente consolidada sobre el tamaño de la flota estatal y sus datos se obtienen mediante pedidos de acceso a la información pública. La flota fue tema de campaña: en 2019 el entonces candidato Luis Lacalle Pou sostuvo que los vehículos oficiales habían pasado de unos 4.000 en 2004 a casi 15.000 en 2017 y prometió terminar con el manejo irresponsable de la plata de los contribuyentes.',
      hallazgo: 'El 12 de febrero de 2026 Búsqueda informó, en base a datos de Sisconve provistos por Ancap, que en 2025 había casi 18.500 vehículos oficiales, 332 más que en 2024. El Observador publicó ese mismo día la cifra de 18.480 unidades y el ranking por organismo: Ministerio del Interior 4.947, UTE 1.724, Intendencia de Montevideo 1.029, OSE 875, MTOP 721, Intendencia de Canelones 669, ASSE 545 y Presidencia 111. Ambos medios consignan que durante el gobierno de Lacalle Pou, que había prometido reducirla, la flota creció de 16.155 vehículos en 2019 a 18.148 en 2024, y que volvió a crecer en el primer año del gobierno de Yamandú Orsi. El consumo de combustible, en cambio, bajó de 57,6 millones de litros en 2024 a 54,6 millones en 2025. UyPress informó el 19 de febrero de 2026 que las intendencias concentran 5.960 vehículos, cerca de un tercio del total.',
      statusNote: 'Según Búsqueda, el ministro de Economía Gabriel Oddone reconoció que hay enormes oportunidades para aumentar la eficiencia en el funcionamiento del Estado —puso como ejemplo concentrar oficinas para reducir alquileres—, sin referirse específicamente a la flota. UyPress detalló que 17 de las 19 intendencias tienen vehículos registrados en Sisconve —San José y Cerro Largo no— y que Flores llega a 52 vehículos cada 10.000 habitantes frente a unos 8 en Montevideo. Al cierre de esta ficha (agosto de 2026) no constan medidas anunciadas para reducir el parque automotor estatal.',
      porQueImporta: 'Cada vehículo oficial cuesta compra, patente, seguro, mantenimiento, combustible y, en muchos casos, chofer, todos los años y en todos los organismos. Es uno de los pocos gastos de funcionamiento que puede medirse en unidades y compararse entre gobiernos, y por eso vuelve a discutirse en cada elección.',
      caveat: 'Sisconve registra vehículos y combustible, no el costo total de la flota: no incluye compra, seguros, mantenimiento ni choferes. Tampoco cubre a los dos gobiernos departamentales que no registran unidades. Las compras de vehículos sí aparecen en el sistema de compras estatales, pero dispersas entre decenas de organismos y llamados.',
    },
    en: {
      title: 'The State\'s fleet is now 18,480 vehicles and still growing',
      dek: 'Governments come and go and the state vehicle fleet keeps expanding: 332 more units in 2025, according to Ancap data compiled by Búsqueda and El Observador.',
      contexto: 'The Computerised Vehicle Control System (Sisconve), run by the state oil company Ancap, records the State\'s official vehicles and the fuel they consume. It is the only consolidated source on the size of the state fleet, and its data is obtained through freedom-of-information requests. The fleet has been a campaign issue: in 2019 then-candidate Luis Lacalle Pou said official vehicles had gone from around 4,000 in 2004 to almost 15,000 in 2017 and promised to end the irresponsible handling of taxpayers\' money.',
      hallazgo: 'On 12 February 2026 Búsqueda reported, based on Sisconve data provided by Ancap, that in 2025 there were almost 18,500 official vehicles, 332 more than in 2024. El Observador published the figure of 18,480 units the same day, along with the ranking by agency: Interior Ministry 4,947, UTE 1,724, Montevideo city government 1,029, OSE 875, the Transport Ministry 721, Canelones city government 669, ASSE 545 and the Presidency 111. Both outlets note that under the Lacalle Pou government, which had promised to cut it, the fleet grew from 16,155 vehicles in 2019 to 18,148 in 2024, and grew again in the first year of the Yamandú Orsi government. Fuel consumption, by contrast, fell from 57.6 million litres in 2024 to 54.6 million in 2025. UyPress reported on 19 February 2026 that departmental governments account for 5,960 vehicles, close to a third of the total.',
      statusNote: 'According to Búsqueda, Economy Minister Gabriel Oddone acknowledged there are enormous opportunities to increase efficiency in how the State operates —citing consolidating offices to cut rents as an example— without referring specifically to the fleet. UyPress detailed that 17 of the 19 departmental governments have vehicles registered in Sisconve —San José and Cerro Largo do not— and that Flores reaches 52 vehicles per 10,000 residents against around 8 in Montevideo. As of this file\'s closing (August 2026) no measures have been announced to reduce the state fleet.',
      porQueImporta: 'Every official vehicle costs purchase, registration, insurance, maintenance, fuel and, in many cases, a driver, every year and across every agency. It is one of the few operating costs that can be measured in units and compared across governments, which is why it resurfaces at every election.',
      caveat: 'Sisconve records vehicles and fuel, not the fleet\'s total cost: it excludes purchase, insurance, maintenance and drivers. Nor does it cover the two departmental governments that register no units. Vehicle purchases do appear in the state procurement system, but scattered across dozens of agencies and tenders.',
    },
  },
  {
    slug: 'antel-arena-contratos-por-excepcion',
    emoji: '🏟️',
    theme: 'estado-y-fondos',
    period: '2015-2025',
    statusKind: 'judicial',
    status: 'archivo',
    amountReported: 'US$ 85.995.517 según el Tribunal de Cuentas en 2019; US$ 119,7 millones de costo final según la JUTEP en 2021',
    organisms: ['Administración Nacional de Telecomunicaciones (ANTEL)'],
    feedCoverage: 'partial',
    sources: [
      { outlet: 'la diaria', title: 'Antel Arena costó casi 86 millones de dólares, según respuesta del Tribunal de Cuentas a Mieres', url: 'https://ladiaria.com.uy/politica/articulo/2019/3/antel-arena-costo-casi-86-millones-de-dolares-segun-respuesta-del-tribunal-de-cuentas-a-mieres/', date: '2019-03-09' },
      { outlet: 'El Observador', title: 'Jutep, sobre Antel Arena: se violentaron principios de transparencia, eficiencia y legalidad', url: 'https://www.elobservador.com.uy/nota/jutep-sobre-antel-arena-hubo-violacion-de-principios-de-transparencia-eficiencia-y-legalidad-202192118506', date: '2021-09-21' },
      { outlet: 'Telenoche', title: '¿Cuáles son las distintas cifras de la construcción del Antel Arena?', url: 'https://www.telenoche.com.uy/nacionales/cuales-son-las-distintas-cifras-la-construccion-del-antel-arena-n5363515', date: '2024-02-22' },
      { outlet: 'El Observador', title: 'Fiscalía volvió a archivar investigación sobre el Antel Arena', url: 'https://www.elobservador.com.uy/nacional/fiscalia-volvio-archivar-investigacion-del-antel-arena-n5984909', date: '2025-02-13' },
    ],
    es: {
      title: 'Antel Arena: la JUTEP vio todo por excepción y la Fiscalía archivó',
      dek: 'La JUTEP concluyó que Antel invirtió la regla y contrató la obra por excepción; la Fiscalía archivó definitivamente la causa penal en febrero de 2025.',
      contexto: 'El Antel Arena, inaugurado en noviembre de 2018 en el predio del ex Cilindro Municipal, fue el mayor emprendimiento edilicio de Antel. La estimación inicial anunciada cuando Carolina Cosse presidía el ente era de US$ 40 millones, revisada a US$ 55 millones en 2015. En marzo de 2019, ante un pedido de informes del senador Pablo Mieres (Partido Independiente), el Tribunal de Cuentas cifró el costo total en US$ 85.995.517, incluyendo el estadio, una guardería, un polideportivo y los espacios exteriores, según informó la diaria. El nuevo directorio de Antel denunció después ante la Fiscalía apartamientos y violaciones a normas y principios de la contratación administrativa.',
      hallazgo: 'El 21 de setiembre de 2021 El Observador informó que la JUTEP concluyó que Antel violó los principios de probidad, transparencia, eficiencia y legalidad. Según ese informe, el ente invirtió la regla general y contrató todo por vía de excepción en lugar de los procedimientos comunes, algo observado reiteradamente por el Tribunal de Cuentas sin consecuencias; clasificó información como confidencial por diez años sin acreditar elementos objetivos que lo justificaran; no existió un plan de negocios completo o no estuvo accesible; y hubo gastos sin disponibilidad presupuestal suficiente. La JUTEP manejó un costo final de US$ 119,7 millones y pérdidas cercanas a US$ 4 millones en los primeros 20 meses de funcionamiento. Telenoche informó el 22 de febrero de 2024 que conviven tres cifras: los US$ 40 millones estimados al anunciar la obra, los más de US$ 85 millones del Tribunal de Cuentas —la cifra que adoptó la Fiscalía— y los US$ 120 millones de una auditoría encargada por la propia Antel.',
      statusNote: 'El 13 de febrero de 2025 El Observador informó que el fiscal Enrique Rodríguez archivó definitivamente la investigación. Concluyó que los peritos contables no detectaron irregularidades en los procedimientos de compra, que la contratación directa obtuvo mejores cotizaciones en beneficio de Antel y que ninguna empresa denunció corrupción durante el proceso; entendió que no hubo desviación o irregularidad pasible de sanción penal en la conducta de los investigados. La causa ya había sido archivada por el fiscal Alejandro Machado —que no halló delito pero sí descuidos y un manejo dispendioso de recursos— y reabierta por el juez Alejandro Asteggiante a pedido del directorio de Antel. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores.',
      porQueImporta: 'Antel es una empresa estatal con caja propia: la obra se pagó con lo que factura por telefonía e internet, sin pasar por el presupuesto que vota el Parlamento. El caso muestra hasta dónde puede llegar un ente cuando contrata por excepción y el órgano de control solo puede dejar constancia.',
      caveat: 'Las cifras de costo varían entre US$ 86 y US$ 120 millones según qué se incluya: obra civil, equipamiento, exteriores u operación. La Fiscalía archivó la causa y no hubo imputados ni condenas. La JUTEP no aplica sanciones: sus conclusiones son un dictamen ético.',
    },
    en: {
      title: 'Antel Arena: JUTEP saw everything by exception, prosecutors closed it',
      dek: 'JUTEP concluded Antel inverted the rule and contracted the works by exception; prosecutors definitively closed the criminal case in February 2025.',
      contexto: 'The Antel Arena, opened in November 2018 on the site of the former Cilindro Municipal, was the largest building project by state telecoms company Antel. The initial estimate announced when Carolina Cosse chaired the company was US$40 million, revised to US$55 million in 2015. In March 2019, in response to a request for information from Senator Pablo Mieres (Partido Independiente), the Court of Accounts put the total cost at US$85,995,517, covering the arena, a nursery, a sports hall and the outdoor areas, as la diaria reported. Antel\'s new board later filed a complaint with prosecutors alleging departures from and breaches of administrative contracting rules and principles.',
      hallazgo: 'On 21 September 2021 El Observador reported that JUTEP concluded Antel had breached the principles of probity, transparency, efficiency and legality. According to that report, the company inverted the general rule and contracted everything through exception routes instead of ordinary procedures, something repeatedly flagged by the Court of Accounts without consequence; it classified information as confidential for ten years without establishing objective grounds for doing so; there was no complete business plan, or it was not accessible; and there was spending without sufficient budget availability. JUTEP used a final cost figure of US$119.7 million and losses of nearly US$4 million in the first 20 months of operation. Telenoche reported on 22 February 2024 that three figures coexist: the US$40 million estimated when the project was announced, the more than US$85 million from the Court of Accounts —the figure prosecutors adopted— and the US$120 million from an audit commissioned by Antel itself.',
      statusNote: 'On 13 February 2025 El Observador reported that prosecutor Enrique Rodríguez definitively closed the investigation. He concluded that accounting experts found no irregularities in the procurement procedures, that direct contracting obtained better quotes to Antel\'s benefit and that no company reported corruption during the process; he found no deviation or irregularity in the conduct of those investigated that was subject to criminal sanction. The case had already been closed by prosecutor Alejandro Machado —who found no crime but did note carelessness and wasteful handling of resources— and reopened by judge Alejandro Asteggiante at the request of Antel\'s board. As of this file\'s closing (August 2026) there is no record of later developments.',
      porQueImporta: 'Antel is a state company with its own revenues: the works were paid for with what it bills for telephony and internet, without passing through the budget Parliament votes. The case shows how far a state company can go when it contracts by exception and the oversight body can only place its objection on record.',
      caveat: 'Cost figures range between US$86 million and US$120 million depending on what is included: civil works, equipment, outdoor areas or operations. Prosecutors closed the case and no one was charged or convicted. JUTEP imposes no sanctions: its conclusions are an ethics opinion.',
    },
  },
  {
    slug: 'horas-extra-intendencia-montevideo-auditoria',
    emoji: '⏰',
    theme: 'estado-y-fondos',
    period: '2020-2026',
    statusKind: 'auditoria',
    status: 'auditoria',
    amountReported: '$ 407.407.451 pagados por 882.061 horas extra en 2023, según El Observador',
    organisms: ['Intendencia de Montevideo', 'Tribunal de Cuentas'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Intendencia de Montevideo',
        'Tribunal de Cuentas',
      ],
      search: 'horas extra',
      yearFrom: 2020,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Telenoche', title: 'El Tribunal de Cuentas auditará a la Intendencia de Montevideo por pago de horas extra', url: 'https://www.telenoche.com.uy/nacionales/el-tribunal-cuentas-auditara-la-intendencia-montevideo-pago-horas-extra-n5388431', date: '2025-08-18' },
      { outlet: 'Teledoce', title: 'Tribunal de Cuentas hará auditoría a la Intendencia de Montevideo, con foco en las horas extra de funcionarios durante el período anterior', url: 'https://www.teledoce.com/telemundo/nacionales/tribunal-de-cuentas-hara-auditoria-a-la-intendencia-de-montevideo-con-foco-en-las-horas-extra-de-funcionarios-durante-el-periodo-anterior/', date: '2025-08-19' },
      { outlet: 'El Observador', title: 'IM reducirá la cantidad de horas extra, que serán 150 mil menos en 2026: a qué áreas se destinarán más', url: 'https://www.elobservador.com.uy/nacional/im-reducira-la-cantidad-horas-extra-que-seran-200-mil-menos-2026-que-areas-se-destinaran-mas-n6034148', date: '2026-02-12' },
    ],
    es: {
      title: 'Horas extra en Montevideo: 719.000 por año bajo auditoría',
      dek: 'La Junta Departamental pidió al Tribunal de Cuentas auditar las horas extra de la Intendencia entre 2020 y 2025; la comuna anunció un recorte para 2026.',
      contexto: 'Las horas extra son un componente estructural del gasto salarial de la Intendencia de Montevideo, sobre todo en limpieza, guardavidas, policlínicas y desarrollo social. La normativa fija un tope mensual de 40 horas por funcionario. En 2025, catorce ediles de la oposición en la Junta Departamental reunieron el tercio de votos que exige la Constitución para pedir al Tribunal de Cuentas una auditoría específica sobre cómo se autorizaron y pagaron esas horas durante la administración anterior. El pedido fue aprobado el 31 de julio de 2025 y el período auditado va del 26 de noviembre de 2020 al 9 de julio de 2025.',
      hallazgo: 'Según informó Telenoche el 18 de agosto de 2025, entre 2020 y 2024 la Intendencia autorizó un promedio de 719.000 horas extra por año, 3.595.727 en total, y solo en 2023 aprobó 888.558 horas extra, estimadas en unos US$ 9,7 millones. Teledoce informó el 19 de agosto de 2025 que, según un relevamiento previo, 1.435 funcionarios —34% de quienes hicieron horas extra en 2023— superaron el tope de 40 horas mensuales autorizado y que algunas aprobaciones carecían de justificación sobre la necesidad del trabajo extraordinario. Entre los cuestionamientos que recogió Telenoche figuran autorizaciones consecutivas a los mismos cargos y trabajo extraordinario durante la pandemia, cuando centros como los casinos estaban cerrados.',
      statusNote: 'El presidente del Tribunal de Cuentas, Francisco Gallinal, dijo que la auditoría puede llevar varios meses. El exintendente Mauricio Zunino defendió el régimen: según Telenoche, sostuvo que las horas extra representan solo el 2,17% del presupuesto municipal y son necesarias para tareas esenciales como limpieza, guardavidas, policlínicas y desarrollo social; ante la Junta Departamental acusó a la oposición de intentar generar desconfianza. El 12 de febrero de 2026 El Observador informó que el intendente Mario Bergara firmó una resolución que recorta 150.000 horas extra en 2026 sobre las 674.350 proyectadas para 2025, tras una reducción de 40% dispuesta desde octubre de 2025 que en diciembre se reportaba cumplida en 41%. Al cierre de esta ficha (agosto de 2026) no constan resultados publicados de la auditoría.',
      porQueImporta: 'Las horas extra se pagan con recargo y no generan un cargo nuevo, por lo que suelen ser la vía más rápida —y más cara— de cubrir servicios permanentes. En 2023 la Intendencia pagó $ 407 millones por 882.061 horas extra: es dinero de tributos departamentales que no se discute en una licitación ni en un concurso.',
      caveat: 'Las horas extra son gasto salarial y no aparecen en el buscador de contratos. Las cifras de 2023 difieren según la fuente (888.558 horas según Telenoche, 882.061 según El Observador) porque cambian el criterio de corte y las unidades incluidas. La auditoría fue pedida por ediles de la oposición y a agosto de 2026 no tiene resultados publicados.',
    },
    en: {
      title: 'Overtime in Montevideo: 719,000 hours a year under audit',
      dek: 'The Departmental Board asked the Court of Accounts to audit the city government\'s overtime between 2020 and 2025; the city has announced a cut for 2026.',
      contexto: 'Overtime is a structural component of the Montevideo city government\'s payroll, above all in street cleaning, lifeguarding, health clinics and social development. The rules set a monthly cap of 40 hours per employee. In 2025, fourteen opposition councillors on the Departmental Board gathered the one-third of votes the Constitution requires to ask the Court of Accounts for a specific audit of how those hours were authorised and paid during the previous administration. The request was approved on 31 July 2025 and the audited period runs from 26 November 2020 to 9 July 2025.',
      hallazgo: 'As Telenoche reported on 18 August 2025, between 2020 and 2024 the city authorised an average of 719,000 overtime hours a year, 3,595,727 in total, and in 2023 alone approved 888,558 overtime hours, estimated at around US$9.7 million. Teledoce reported on 19 August 2025 that, according to an earlier survey, 1,435 employees —34% of those working overtime in 2023— exceeded the authorised cap of 40 hours a month, and that some approvals lacked justification of the need for the extra work. Among the objections reported by Telenoche are consecutive authorisations to the same posts and extraordinary work during the pandemic, when venues such as the casinos were closed.',
      statusNote: 'The president of the Court of Accounts, Francisco Gallinal, said the audit could take several months. Former mayor Mauricio Zunino defended the arrangement: according to Telenoche, he argued overtime represents only 2.17% of the municipal budget and is necessary for essential tasks such as street cleaning, lifeguarding, health clinics and social development; before the Departmental Board he accused the opposition of trying to generate distrust. On 12 February 2026 El Observador reported that Mayor Mario Bergara signed a resolution cutting 150,000 overtime hours in 2026 from the 674,350 projected for 2025, after a 40% reduction ordered from October 2025 that by December was reported as 41% achieved. As of this file\'s closing (August 2026) no audit results have been published.',
      porQueImporta: 'Overtime is paid at a premium and creates no new post, so it tends to be the fastest —and most expensive— way to staff permanent services. In 2023 the city paid $407 million pesos for 882,061 overtime hours: money from departmental taxes that is never debated in a tender or a competitive hiring process.',
      caveat: 'Overtime is payroll spending and does not appear in the contract search. The 2023 figures differ by source (888,558 hours per Telenoche, 882,061 per El Observador) because the cut-off criteria and the units included vary. The audit was requested by opposition councillors and as of August 2026 has no published results.',
    },
  },
]
