import type { CasoDef } from '../types'

/**
 * seguridad — 10 dossiers, 4 of them with a live cross-reference.
 *
 * Every source URL was fetched and every query was resolved against the live
 * collection before this file was committed (scripts/verify-casos.ts re-checks
 * both). A caso with no `query` is not a gap in the research: its money does
 * not travel through the Compras Estatales feed at all, which `feedCoverage`
 * records and the page states outright.
 */
export const CASOS_SEGURIDAD: CasoDef[] = [
  {
    slug: 'carcel-ppp-punta-de-rieles-canon',
    emoji: '🏗️',
    theme: 'seguridad',
    period: '2014-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'US$ 97 millones según Presidencia (2014), US$ 93 millones según Revista Construcción y US$ 100 millones según Montevideo Portal (2018); canon anual de unos US$ 20 millones según Búsqueda (2020)',
    organisms: ['Ministerio del Interior', 'Instituto Nacional de Rehabilitación'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'Presidencia de la República', title: 'Gobierno adjudicó primera obra bajo el régimen de participación público privada', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/gobierno-adjudico-primera-obra-bajo-regimen-participacion-publico-privada', date: '2014-06-06' },
      { outlet: 'Montevideo Portal', title: 'OPP visitó nueva cárcel de Punta Rieles, que costó 100 millones de dólares', url: 'https://www.montevideo.com.uy/Noticias/OPP-visito-nueva-carcel-de-Punta-Rieles-que-costo-100-millones-de-dolares-uc679475', date: '2018-04-05' },
      { outlet: 'Búsqueda', title: 'El gobierno reitera sus críticas a la cárcel de Punta de Rieles, con quejas por el vandalismo y un costo económico mayor al previsto', url: 'https://www.busqueda.com.uy/Secciones/El-gobierno-reitera-sus-criticas-a-la-carcel-de-Punta-de-Rieles-con-quejas-por-el-vandalismo-y-un-costo-economico-mayor-al-previsto-uc1192', date: '2020-08-26' },
      { outlet: 'Revista Construcción', title: 'PPP en la mira', url: 'https://www.revistaconstruccion.uy/infraestructura/ppp-en-la-mira/', date: '2020-08-31' },
    ],
    es: {
      title: 'Punta de Rieles: la cárcel PPP que se paga por décadas',
      dek: 'El Estado adjudicó en 2014 su primera cárcel bajo Participación Público-Privada. Seis años después, según Búsqueda, el propio gobierno dijo que costaba más de lo previsto.',
      contexto: 'En junio de 2014 el gobierno de José Mujica adjudicó la primera obra bajo el régimen de Participación Público-Privada: la Unidad Nº 1 de Punta de Rieles. Según Presidencia, el contrato cubría US$ 97 millones de diseño, obra, suministros y equipamiento de seguridad y estándar para 1.860 plazas más 100 en el centro de ingreso y clasificación, por 27 años, con un pago diario de 196 unidades indexadas por plaza disponible. En ese mismo comunicado, el privado presta además la enfermería, la hotelería y la alimentación, mientras que el Estado se encarga del tratamiento médico, la seguridad y la rehabilitación. Revista Construcción identificó al consorcio adjudicatario como Consorcio Unidad Punta de Rieles S.A., integrado por Abengoa Uruguay, Instalaciones Inabensa y Goddard Catering. La cárcel opera desde enero de 2018.',
      hallazgo: 'Las cifras difieren según la fuente. Presidencia habló de US$ 97 millones en 2014; Revista Construcción, de una inversión privada de US$ 93 millones y de pagos por disponibilidad de unos 165 millones de unidades indexadas por año durante 25 años, con el primer pago en abril de 2018; y Montevideo Portal, tras una visita de la OPP en 2018, de US$ 100 millones para una capacidad de 1.960 personas en 50.000 metros cuadrados. En agosto de 2020 Búsqueda informó que el gobierno de Luis Lacalle Pou reiteró sus críticas al contrato: el entonces ministro del Interior, Jorge Larrañaga, sostuvo que el penal se construyó como de baja seguridad pero recibe internos de baja, media y alta; que el vandalismo sobre las cerraduras electrónicas derivó en compras directas por excepción de unos US$ 450.000 en 2019, que según el contrato corren por cuenta del Estado; y que se paga el canon por la capacidad contratada de 1.960 plazas aunque entonces alojaba unos 1.560 internos por sectores clausurados. Según esa nota, Larrañaga situó el canon anual en unos US$ 20 millones, indexado en unidades reajustables. El entonces director de la OPP, Álvaro García, había defendido el modelo ante Montevideo Portal como "una primera experiencia muy interesante" que permite al país concretar inversiones que de otro modo no se harían.',
      statusNote: 'El contrato sigue vigente y el consorcio continúa operando la Unidad Nº 1; al momento de la nota de Revista Construcción era el único proyecto PPP terminado del país. El modelo se replicó: en agosto de 2024 el Ministerio del Interior firmó un segundo contrato PPP por tres unidades en el predio del ex Penal de Libertad, y en julio de 2026 el Estado trasladó unas 800 mujeres a una nueva cárcel levantada en el predio de Punta de Rieles. Al cierre de esta ficha (agosto de 2026) no encontramos novedades públicas sobre el contrato de 2014 posteriores a la cobertura de Búsqueda de agosto de 2020.',
      porQueImporta: 'Es el compromiso penitenciario más largo del país: un canon que Larrañaga situó en unos US$ 20 millones anuales ata presupuesto durante décadas. Si el pago se calcula sobre plazas contratadas y no sobre plazas usadas, cada celda clausurada se sigue cobrando. Saber cuánto cuesta una plaza es el punto de partida para discutir si conviene construir más o encarcelar menos.',
      caveat: 'El canon de un contrato PPP se ejecuta como pago por disponibilidad y no necesariamente aparece como compra en el feed de compras estatales. Lo rastreable son las compras satélite del Ministerio del Interior asociadas a la unidad: reparaciones, insumos y servicios. Las fuentes tampoco coinciden en el plazo de los pagos: Presidencia habla de 27 años y Revista Construcción de 25.',
    },
    en: {
      title: 'Punta de Rieles: the PPP prison paid for over decades',
      dek: 'In 2014 the State awarded its first prison under a Public-Private Partnership. Six years later, according to Búsqueda, the government itself said it cost more than expected.',
      contexto: 'In June 2014 José Mujica\'s government awarded the country\'s first project under the Public-Private Partnership regime: Unit No. 1 at Punta de Rieles. According to the Presidency, the contract covered US$ 97 million in design, construction, supplies and security and standard equipment for 1,860 places plus 100 at the intake and classification centre, over 27 years, with a daily payment of 196 indexed units per available place. In that same release, the private party also provides the infirmary, hotel and food services, while the State handles medical treatment, security and rehabilitation. Revista Construcción identified the winning consortium as Consorcio Unidad Punta de Rieles S.A., made up of Abengoa Uruguay, Instalaciones Inabensa and Goddard Catering. The prison has been operating since January 2018.',
      hallazgo: 'Figures differ by source. The Presidency cited US$ 97 million in 2014; Revista Construcción reported a private investment of US$ 93 million and availability payments of around 165 million indexed units a year over 25 years, with the first payment in April 2018; and Montevideo Portal, after an OPP visit in 2018, reported US$ 100 million for a capacity of 1,960 people across 50,000 square metres. In August 2020 Búsqueda reported that Luis Lacalle Pou\'s government repeated its criticism of the contract: then Interior Minister Jorge Larrañaga argued the prison was built as low-security but takes in low, medium and high-security inmates; that vandalism of the electronic locks led to direct purchases by exception worth about US$ 450,000 in 2019, which under the contract fall to the State; and that the fee is paid on the contracted capacity of 1,960 places even though it then held around 1,560 inmates because of closed sectors. According to that report, Larrañaga put the annual fee at around US$ 20 million, indexed in adjustable units. The then head of the OPP, Álvaro García, had defended the model to Montevideo Portal as "a first very interesting experience" that lets the country make investments that otherwise would not happen.',
      statusNote: 'The contract remains in force and the consortium still operates Unit No. 1; at the time of the Revista Construcción piece it was the country\'s only completed PPP project. The model was repeated: in August 2024 the Interior Ministry signed a second PPP contract for three units on the grounds of the former Penal de Libertad, and in July 2026 the State moved some 800 women to a new prison built on the Punta de Rieles site. As this file closes (August 2026) we found no public developments on the 2014 contract later than Búsqueda\'s August 2020 coverage.',
      porQueImporta: 'It is the country\'s longest prison commitment: a fee Larrañaga put at around US$ 20 million a year ties up budget for decades. If payment is calculated on contracted places rather than used places, every closed cell is still billed. Knowing what a prison place costs is the starting point for debating whether to build more or imprison fewer people.',
      caveat: 'A PPP availability fee is not executed as an ordinary purchase and may not appear in the state procurement feed. What can be traced are the Interior Ministry\'s satellite purchases tied to the unit: repairs, supplies and services. The sources also disagree on the payment term: the Presidency says 27 years and Revista Construcción 25.',
    },
  },
  {
    slug: 'nuevas-carceles-ppp-penal-libertad',
    emoji: '🧱',
    theme: 'seguridad',
    period: '2024-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'US$ 75 millones de inversión anunciada y hasta US$ 1,7 millones por mes durante 15 años de operación (Búsqueda, 2024); sobre ese máximo, unos US$ 306 millones según nuestro propio cálculo',
    organisms: ['Ministerio del Interior', 'Instituto Nacional de Rehabilitación'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'Búsqueda', title: 'El gobierno pagará U$S 1,7 millones al mes por la operación de tres cárceles nuevas en el predio del penal de Libertad', url: 'https://www.busqueda.com.uy/informacion/el-gobierno-pagara-us-17-millones-al-mes-la-operacion-tres-carceles-nuevas-el-predio-del-penal-libertad-n5392346', date: '2024-08-01' },
      { outlet: 'El Observador', title: 'Construirán tres nuevas unidades en el Penal de Libertad e Interior busca "aliviar el hacinamiento"', url: 'https://www.elobservador.com.uy/nacional/construiran-tres-nuevas-unidades-el-penal-libertad-e-interior-busca-aliviar-el-hacinamiento-n5958299', date: '2024-08-28' },
      { outlet: 'Presidencia de la República', title: 'Nuevas unidades aumentarán en 1.700 plazas la capacidad del penal de Libertad', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/nuevas-unidades-aumentaran-1700-plazas-capacidad-del-penal-libertad', date: '2024-10-08' },
      { outlet: 'InfoNegocios', title: 'Tres nuevas unidades penitenciarias en Libertad (de la mano de TEYMA, Saceem y Ciemsa)', url: 'https://infonegocios.biz/y-ademas/tres-nuevas-unidades-penitenciarias-en-libertad-de-la-mano-de-teyma-saceem-y-ciemsa', date: '2024-08-30' },
      { outlet: 'Caras y Caretas', title: 'Los problemas endémicos del sistema penitenciario uruguayo y las medidas adoptadas para solucionarlos', url: 'https://www.carasycaretas.com.uy/sociedad/los-problemas-endemicos-del-sistema-penitenciario-uruguayo-y-las-medidas-adoptadas-solucionarlos-n95472', date: '2026-05-15' },
    ],
    es: {
      title: 'Tres cárceles nuevas por PPP: US$ 1,7 millones por mes',
      dek: 'El Estado pagará durante 15 años la operación de tres unidades en el ex Penal de Libertad. El máximo mensual que informó Búsqueda, proyectado al plazo completo, cuadruplica el costo de la obra.',
      contexto: 'El 28 de agosto de 2024 el Ministerio del Interior firmó el segundo contrato de Participación Público-Privada del sistema carcelario uruguayo, según El Observador. El consorcio adjudicatario es UIPPL Libertad S.A., integrado por Ciemsa, Mefren, Saceem y Teyma según Búsqueda; El Observador e InfoNegocios lo presentaron como el consorcio de Teyma, Saceem y Ciemsa, y Presidencia lo llamó "Consorcio Libertad". Construirá tres unidades —la 27, la 28 y la 29— en el predio del ex Penal de Libertad, en San José. La inversión anunciada fue de US$ 75 millones, con 18 meses de obra seguidos de 15 años de operación. El contrato incluye equipamiento, mantenimiento de infraestructura, alimentación, suministros, aseo, disposición de residuos y control de plagas. El entonces ministro Nicolás Martinelli fijó como meta el "hacinamiento cero".',
      hallazgo: 'Búsqueda informó el 1º de agosto de 2024 que el Estado pagará hasta US$ 1,7 millones por mes por la operación de las tres unidades, con ese máximo atado al 100% de ocupación y por un plazo de 15 años. Proyectado sobre esos 15 años —cálculo nuestro, no de la fuente— el tope acumulado ronda los US$ 306 millones, más de cuatro veces la inversión anunciada de US$ 75 millones. La capacidad declarada también varía según la fuente: Búsqueda informó hasta 460 plazas por unidad y 1.380 en total, InfoNegocios habló de 460 por unidad y 1.430 en total, y un comunicado de Presidencia del 8 de octubre de 2024 tituló que las nuevas unidades aumentarían la capacidad del penal en 1.700 plazas. El comisionado parlamentario penitenciario Juan Miguel Petit dijo a Búsqueda que las unidades "pueden ayudar a que se cierre ese lugar esperpéntico", pero describió la situación del sistema como extrema, volátil, explosiva y desalentadora, y reclamó priorizar rehabilitación, tratamiento de adicciones y medidas alternativas a la privación de libertad por encima de la construcción.',
      statusNote: 'Las obras avanzaron y en mayo de 2026 comenzaron los traslados. Caras y Caretas informó el 15 de mayo de 2026, sobre la base de un informe parlamentario de la directora del INR, Ana Juanche, que la Unidad 27 se inauguraba con 460 camas destinadas a personas condenadas por delitos sexuales de alto riesgo y que los traslados desde el Módulo 1 de Santiago Vázquez comenzaban esa misma semana, con envíos quincenales posteriores. Al cierre de esta ficha (agosto de 2026) no encontramos auditorías publicadas ni observaciones del Tribunal de Cuentas sobre este contrato.',
      porQueImporta: 'Es plata comprometida por 15 años y decidida en 2024: un tope de operación que, proyectado al plazo completo, ronda los US$ 306 millones frente a US$ 75 millones de obra. Para el contribuyente la pregunta concreta es cuánto cuesta cada plaza por mes y cómo se compara ese precio con lo que cuesta operar una unidad penitenciaria estatal equivalente.',
      caveat: 'El pago por disponibilidad de un contrato PPP no se ejecuta como una compra común, así que puede no aparecer en el feed de compras estatales. Sí pueden rastrearse las compras del Ministerio del Interior y del INR ligadas a la puesta en marcha de las unidades 27, 28 y 29. El total de US$ 306 millones es una proyección aritmética del tope mensual publicado, no una cifra contractual confirmada.',
    },
    en: {
      title: 'Three new PPP prisons: US$ 1.7 million a month',
      dek: 'The State will pay for 15 years to operate three units at the former Penal de Libertad. The monthly maximum Búsqueda reported, projected over the full term, is four times the construction cost.',
      contexto: 'On 28 August 2024 the Interior Ministry signed the second Public-Private Partnership contract in Uruguay\'s prison system, according to El Observador. The winning consortium is UIPPL Libertad S.A., made up of Ciemsa, Mefren, Saceem and Teyma according to Búsqueda; El Observador and InfoNegocios presented it as the Teyma, Saceem and Ciemsa consortium, and the Presidency called it "Consorcio Libertad". It will build three units — 27, 28 and 29 — on the grounds of the former Penal de Libertad in San José. The announced investment was US$ 75 million, with 18 months of construction followed by 15 years of operation. The contract covers equipment, infrastructure maintenance, food service, supplies, cleaning, waste disposal and pest control. Then Minister Nicolás Martinelli set a target of "zero overcrowding".',
      hallazgo: 'Búsqueda reported on 1 August 2024 that the State will pay up to US$ 1.7 million a month to operate the three units, with that maximum tied to 100% occupancy over a 15-year term. Projected across those 15 years — our arithmetic, not the source\'s — the accumulated ceiling comes to roughly US$ 306 million, more than four times the announced US$ 75 million investment. Declared capacity also varies by source: Búsqueda reported up to 460 places per unit and 1,380 in total, InfoNegocios cited 460 per unit and 1,430 in total, and a Presidency release of 8 October 2024 was headlined that the new units would add 1,700 places to the prison. Parliamentary prison commissioner Juan Miguel Petit told Búsqueda the units "can help close that grotesque place", but described the system\'s situation as extreme, volatile, explosive and disheartening, and called for prioritising rehabilitation, addiction treatment and alternatives to imprisonment over construction.',
      statusNote: 'Construction advanced and transfers began in May 2026. Caras y Caretas reported on 15 May 2026, drawing on a parliamentary report by INR director Ana Juanche, that Unit 27 was opening with 460 beds for people convicted of high-risk sexual offences and that transfers from Module 1 at Santiago Vázquez began that same week, with further groups every two weeks. As this file closes (August 2026) we found no published audits or Tribunal de Cuentas observations on this contract.',
      porQueImporta: 'This is money committed for 15 years and decided in 2024: an operating ceiling that, projected over the full term, comes to roughly US$ 306 million against US$ 75 million in construction. For the taxpayer the concrete question is what each place costs per month and how that price compares with running an equivalent State-operated prison unit.',
      caveat: 'A PPP availability payment is not executed as an ordinary purchase, so it may not appear in the state procurement feed. What can be traced are the Interior Ministry and INR purchases tied to bringing units 27, 28 and 29 into service. The US$ 306 million total is an arithmetic projection of the published monthly ceiling, not a confirmed contractual figure.',
    },
  },
  {
    slug: 'el-guardian-escuchas-compra-secreta',
    emoji: '🎧',
    theme: 'seguridad',
    period: '2013-2024',
    statusKind: 'judicial',
    status: 'investigacion',
    amountReported: 'US$ 1.098.060 la ampliación autorizada en 2022 (Montevideo Portal); unos US$ 2 millones el sistema original y cerca de US$ 200.000 anuales de mantenimiento (El Observador)',
    organisms: ['Ministerio del Interior'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'El Observador', title: 'Ministerio del Interior afirma que pondrá en marcha los controles de El Guardián', url: 'https://www.elobservador.com.uy/nota/ministerio-del-interior-afirma-que-pondra-en-marcha-los-controles-de-el-guardian-201978212954', date: '2019-07-09' },
      { outlet: 'Montevideo Portal', title: 'Tribunal de Cuentas autorizó compra secreta de nuevas funcionalidades de El Guardián', url: 'https://www.montevideo.com.uy/Noticias/Tribunal-de-Cuentas-autorizo-compra-secreta-de-nuevas-funcionalidades-de-El-Guardian-uc838118', date: '2022-11-14' },
      { outlet: 'la diaria', title: 'Policía que ingresó a El Guardián para acceder a escuchas de la causa del vino envenenado es hijo del exjefe de Inteligencia', url: 'https://ladiaria.com.uy/justicia/articulo/2023/10/policia-que-ingreso-a-el-guardian-para-acceder-a-escuchas-de-la-causa-del-vino-envenenado-es-hijo-del-exjefe-de-inteligencia/', date: '2023-10-18' },
    ],
    es: {
      title: 'El Guardián: el sistema de escuchas comprado en secreto',
      dek: 'El Ministerio del Interior amplió por US$ 1,1 millones su sistema de interceptación mediante una compra declarada secreta. Después se reportaron accesos irregulares.',
      contexto: 'El Guardián es el sistema de interceptación legal de comunicaciones que usa la Policía uruguaya, con software de la empresa brasileña Digitro. Según El Observador, costó cerca de US$ 2 millones, con un mantenimiento y servicio técnico anual de cerca de US$ 200.000, y permite monitorear simultáneamente 800 celulares y 200 teléfonos fijos, crear hasta 100 casillas de correo espejo y vigilar hasta tres redes sociales. Según Montevideo Portal, su compra original en 2013, con Eduardo Bonomi como ministro del Interior, se tramitó también como compra secreta, un mecanismo que el TOCAF habilita cuando las circunstancias exigen mantener la operación reservada. En diciembre de 2015 la Suprema Corte de Justicia, el Ministerio del Interior y la Fiscalía acordaron un régimen de control.',
      hallazgo: 'El Observador informó el 9 de julio de 2019 que los informes trimestrales de escuchas comprometidos en ese acuerdo, que debían empezar en mayo de 2017, nunca se enviaron, y que tampoco se concretó el protocolo para que las empresas de telecomunicaciones informaran las interceptaciones al Poder Judicial; agregó que el Tribunal de Cuentas había hecho observaciones sobre el funcionamiento del sistema cuyo detalle el ministerio mantuvo reservado. El senador Javier García describió entonces al sistema como "un gran agujero negro" sin controles verificables. Montevideo Portal informó el 14 de noviembre de 2022 que el Tribunal de Cuentas autorizó una compra directa de US$ 1.098.060 a Digitro Tecnología Ltda para incorporar mejoras a la plataforma de interceptación legal, tramitada como compra secreta por el artículo 33 del TOCAF y catalogada como secreta por el entonces director general de Secretaría, Luis Calabria, el 28 de junio de 2022; un pedido de informes presentado en mayo de 2022 por el senador Charles Carrera seguía sin respuesta a la fecha de esa nota. En octubre de 2023 la diaria informó que dos policías de la Dirección Nacional de Información e Inteligencia accedieron de forma irregular a escuchas del sistema.',
      statusNote: 'Según la diaria, los dos policías involucrados fueron sumariados en la semana previa a esa publicación. El medio informó que uno de ellos, hijo del fallecido excomisario Silcar Lara Borges —exjefe de la DNII—, obtuvo credenciales de acceso a través del subcomisario John Giménez para ver escuchas de policías y militares investigados en la causa del vino envenenado, y que la fiscal Silvia Porteiro investiga los vínculos entre los involucrados. El único imputado en esa causa, según la nota, es Ricardo Zabala, expolicía que trabajó en la DNII. Al cierre de esta ficha (agosto de 2026) no encontramos fallos ni imputaciones publicadas por el uso indebido del sistema posteriores a esa investigación. Las personas mencionadas no tienen condena por estos hechos.',
      porQueImporta: 'Es dinero público gastado bajo un régimen que impide el control ciudadano: la compra es secreta, las características técnicas también, y los informes de uso comprometidos nunca llegaron, según El Observador. El sistema escucha teléfonos de personas en Uruguay; que su compra y su control queden fuera del escrutinio afecta a cualquiera, no sólo a quienes están siendo investigados.',
      caveat: 'Una compra tramitada como secreta bajo el artículo 33 del TOCAF no se publica en el portal de compras estatales, así que estos contratos no aparecen en nuestros datos. Lo que sí puede rastrearse son otras compras de tecnología del Ministerio del Interior en el mismo período.',
    },
    en: {
      title: 'El Guardián: the wiretap system bought in secret',
      dek: 'The Interior Ministry expanded its interception system by US$ 1.1 million through a purchase declared secret. Irregular access to wiretaps was later reported.',
      contexto: 'El Guardián is the lawful communications interception system used by Uruguay\'s police, running software from the Brazilian firm Digitro. According to El Observador it cost close to US$ 2 million, with annual maintenance and technical service of nearly US$ 200,000, and it can simultaneously monitor 800 mobile phones and 200 landlines, create up to 100 mirrored email accounts and watch up to three social networks. According to Montevideo Portal, its original purchase in 2013, with Eduardo Bonomi as Interior Minister, was also processed as a secret purchase, a mechanism the TOCAF procurement law allows when circumstances require the operation to be kept confidential. In December 2015 the Supreme Court, the Interior Ministry and the Prosecutor\'s Office agreed an oversight arrangement.',
      hallazgo: 'El Observador reported on 9 July 2019 that the quarterly wiretap reports committed under that agreement, due to begin in May 2017, were never sent, and that the protocol for telecom companies to report interceptions to the Judiciary was never completed either; it added that the Tribunal de Cuentas had made observations about how the system worked whose details the ministry kept confidential. Senator Javier García then described the system as "a big black hole" with no verifiable controls. Montevideo Portal reported on 14 November 2022 that the Tribunal de Cuentas authorised a direct purchase of US$ 1,098,060 from Digitro Tecnología Ltda to add improvements to the lawful interception platform, processed as a secret purchase under article 33 of the TOCAF and classified as secret by then Secretariat director general Luis Calabria on 28 June 2022; an information request filed in May 2022 by Senator Charles Carrera was still unanswered as of that report. In October 2023 la diaria reported that two officers of the National Directorate of Police Information and Intelligence irregularly accessed wiretaps from the system.',
      statusNote: 'According to la diaria, the two officers involved were placed under disciplinary proceedings the week before that report. The outlet reported that one of them, son of the late former commissioner Silcar Lara Borges — a former head of the DNII — obtained access credentials through subcommissioner John Giménez to view wiretaps of police and military personnel under investigation in the poisoned wine case, and that prosecutor Silvia Porteiro is investigating the links between those involved. The only person charged in that case, according to the report, is Ricardo Zabala, a former police officer who worked at the DNII. As this file closes (August 2026) we found no published rulings or charges over misuse of the system after that investigation. None of the people named has been convicted over these events.',
      porQueImporta: 'This is public money spent under a regime that blocks citizen oversight: the purchase is secret, so are the technical specifications, and the committed usage reports never arrived, according to El Observador. The system listens to phones in Uruguay; keeping its purchase and its controls out of scrutiny affects everyone, not only those under investigation.',
      caveat: 'A purchase processed as secret under article 33 of the TOCAF is not published in the state procurement portal, so these contracts do not appear in our data. What can be traced are other Interior Ministry technology purchases from the same period.',
    },
  },
  {
    slug: 'chalecos-antibala-licitacion-suspendida',
    emoji: '🦺',
    theme: 'seguridad',
    period: '2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'US$ 7.080.840 la adjudicación, sobre una compra plurianual de hasta 27.000 chalecos (Búsqueda e Infodefensa, 2026)',
    organisms: ['Ministerio del Interior'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Secretaría del Ministerio del Interior',
        'Dir.Nac.Cárceles,Penitenciarías y Centros de Recuperación',
        'Dirección Nacional de Policía de Tránsito',
        'Jefatura de Policía de Maldonado',
        'Dirección Nacional de Sanidad Policial',
        'Jefatura de Policía de Rivera',
        'Jefatura de Policía de Montevideo',
        'Dirección Nacional de Asuntos Sociales',
        'Jefatura de Policía de Salto',
        'Jefatura de Policía de Cerro Largo',
        'Jefatura de Policía de Tacuarembó',
        'Jefatura de Policía de Paysandú',
        'Dirección Nacional de Bomberos',
        'Jefatura de Policía de Durazno',
        'Jefatura de Policía de Lavalleja',
        'Jefatura de Policía de Colonia',
        'Jefatura de Policía de Artigas',
        'Jefatura de Policía de Rocha',
        'Jefatura de Policía de Canelones',
        'Jefatura de Policía de San José',
        'Jefatura de Policía de Soriano',
        'Dirección Nacional de Identificación Civil',
        'Jefatura de Policía de Flores',
        'Jefatura de Policía de Río Negro',
        'Dirección Nacional de Migración',
        'Dirección Nacional de Policia Cientifica',
        'Escuela Nacional de Policía',
        'Instituto Nacional de Rehabilitación',
        'Jefatura de Policía de Florida',
        'Jefatura de Policía de Teinta y Tres',
        'Dirección Nacional de Asistencia Social Policial',
        'Guardia Republicana',
        'Dirección Nacional de Policía Caminera',
        'Dirección Nacional de la Seguridad Rural',
        'Dirección Nacional de Policía Científica',
        'Dirección Nacional de Asistencia y Seguridad Social Policial',
        'Dirección Nacional de Información e Inteligencia',
        'Jefatura de Policía de Treinta y Tres',
        'Dirección Nacional de Prevención Social del Delito',
      ],
      search: 'policial',
      yearFrom: 2026,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Infodefensa', title: 'El Ministerio del Interior de Uruguay suspende licitación para la compra de chalecos antibala', url: 'https://www.infodefensa.com/texto-diario/mostrar/5770846/suspendida-multimillonaria-compra-chalecos-antibala-policia-uruguay-observaciones-proceso', date: '2026-02-18' },
      { outlet: 'Búsqueda', title: 'Con la intervención de Orsi, Interior adjudicó una discutida compra millonaria de chalecos antibalas', url: 'https://www.busqueda.com.uy/informacion/con-la-intervencion-orsi-interior-adjudico-una-discutida-compra-millonaria-chalecos-antibalas-n5410673', date: '2026-03-05' },
      { outlet: 'Presidencia de la República', title: 'Ministerio del Interior adquirió 9.500 chalecos antibala diseñado para mujeres', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/ministerio-del-interior-adquirio-9500-chalecos-antibala-disenado-para-mujeres', date: '2026-03-19' },
    ],
    es: {
      title: 'Chalecos antibala: US$ 7 millones, suspendidos y adjudicados',
      dek: 'Tres empresas impugnaron la compra de chalecos para la Policía. Según Búsqueda, el presidente Orsi levantó la suspensión por resolución y el contrato se adjudicó igual.',
      contexto: 'A comienzos de 2026 el Ministerio del Interior tramitó una compra plurianual de chalecos antibala para la Policía Nacional por unos US$ 7 millones. Según Infodefensa, el llamado abarcaba hasta 27.000 chalecos. El sindicato de la Guardia Republicana venía pidiendo información desde principios de febrero sobre los chalecos balísticos en uso, señalando que había funcionarios trabajando con equipo vencido y advirtiendo por el riesgo de las armas de alto calibre incautadas en procedimientos, incluidos fusiles AR-15. El proceso quedó suspendido en febrero de 2026 tras las objeciones de empresas competidoras.',
      hallazgo: 'Búsqueda informó el 5 de marzo de 2026 que la compra, por US$ 7.080.840, fue adjudicada a la importadora uruguaya Silvercat, con chalecos de la marca colombiana Miguel Caballero, y que tres competidoras —Iberfix, MKU y Mars Armor— impugnaron el fallo. Cuestionaron la supuesta insuficiencia de la protección lateral del torso en el modelo elegido, un cambio de material exterior de Cordura 500D a poliéster sin justificación técnica documentada, y la ausencia de informes técnicos comparativos en el expediente. Según la misma nota, el presidente Yamandú Orsi habilitó el levantamiento de la suspensión mediante una resolución del 18 de febrero de 2026, con el argumento de que la adquisición es "imprescindible e impostergable" para garantizar "condiciones mínimas de seguridad en el servicio policial". Infodefensa informó ese mismo 18 de febrero que el ministerio respondió a los policías que habían pedido información con procedimientos disciplinarios que incluyeron retención de salario y separación del cargo por seis meses.',
      statusNote: 'La compra siguió adelante. El 19 de marzo de 2026 Presidencia informó que el Ministerio del Interior adquirió 9.500 chalecos diseñados específicamente para mujeres, que son el 33% del personal del ministerio, y que los primeros 500 llegarían en abril de 2026; la directora de políticas de género, July Zabaleta, dijo que "no es una cuestión de estética, es una cuestión de salud y de seguridad", porque los chalecos unisex dejan partes del cuerpo sin proteger. Al cierre de esta ficha (agosto de 2026) no encontramos resoluciones del Tribunal de Cuentas ni fallos judiciales publicados sobre las impugnaciones, ni información sobre el desenlace de los procedimientos disciplinarios a los funcionarios policiales.',
      porQueImporta: 'Son US$ 7 millones en el equipo que separa a un policía de una bala. Que tres empresas cuestionen la protección lateral no prueba que los chalecos sean deficientes —son planteos de competidoras que perdieron el llamado—, pero deja el pliego y su evaluación en discusión. Y sancionar a funcionarios que pidieron información sobre su propio equipo desalienta el control desde adentro.',
      caveat: 'El llamado y la adjudicación deberían figurar en el portal de compras estatales bajo el Ministerio del Interior. Las impugnaciones, los recursos y los procedimientos disciplinarios, en cambio, no dejan rastro en los datos abiertos de compras.',
    },
    en: {
      title: 'Body armour: US$ 7 million, suspended then awarded',
      dek: 'Three firms challenged the police body armour purchase. According to Búsqueda, President Orsi lifted the suspension by resolution and the contract was awarded anyway.',
      contexto: 'In early 2026 the Interior Ministry ran a multi-year purchase of bulletproof vests for the National Police worth around US$ 7 million. According to Infodefensa, the tender covered up to 27,000 vests. The Republican Guard police union had been requesting information since early February about the ballistic vests in use, noting that officers were working with expired equipment and warning about the risk of the high-calibre weapons seized in police operations, including AR-15 rifles. The process was suspended in February 2026 after objections from competing companies.',
      hallazgo: 'Búsqueda reported on 5 March 2026 that the purchase, worth US$ 7,080,840, was awarded to Uruguayan importer Silvercat, supplying vests of the Colombian brand Miguel Caballero, and that three competitors — Iberfix, MKU and Mars Armor — challenged the award. They questioned the allegedly insufficient lateral torso protection of the chosen model, a change of outer material from Cordura 500D to polyester without documented technical justification, and the absence of comparative technical reports from the file. According to the same report, President Yamandú Orsi enabled the lifting of the suspension through a resolution dated 18 February 2026, arguing the acquisition is "essential and unpostponable" to guarantee "minimum safety conditions in police service". Infodefensa reported the same 18 February that the ministry responded to the officers who had requested information with disciplinary proceedings that included salary withholding and six-month separation from duty.',
      statusNote: 'The purchase went ahead. On 19 March 2026 the Presidency reported that the Interior Ministry acquired 9,500 vests designed specifically for women, who make up 33% of the ministry\'s staff, and that the first 500 would arrive in April 2026; gender policy director July Zabaleta said "it\'s not a matter of aesthetics, it\'s a matter of health and safety", because unisex vests leave parts of the body unprotected. As this file closes (August 2026) we found no published Tribunal de Cuentas resolutions or court rulings on the challenges, nor information on the outcome of the disciplinary proceedings against the officers.',
      porQueImporta: 'This is US$ 7 million on the equipment that stands between an officer and a bullet. Three firms questioning lateral protection does not prove the vests are deficient — these are claims by competitors that lost the tender — but it does leave the specification and its evaluation in dispute. And disciplining officers who asked about their own equipment discourages oversight from within.',
      caveat: 'The tender and the award should appear in the state procurement portal under the Interior Ministry. The challenges, appeals and internal disciplinary proceedings, however, leave no trace in open procurement data.',
    },
  },
  {
    slug: 'servicio-222-deuda-organismos-publicos',
    emoji: '🚔',
    theme: 'seguridad',
    period: '2022-2025',
    statusKind: 'gestion',
    status: 'sin-resolver',
    amountReported: 'US$ 13 millones adeudados por ASSE (Subrayado, 2025) y $ 9.845.446 por la Intendencia de Rivera (El Observador, 2025)',
    organisms: ['Ministerio del Interior', 'Administración de los Servicios de Salud del Estado', 'Intendencia de Rivera', 'Instituto Nacional de Inclusión Social Adolescente'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Secretaría del Ministerio del Interior',
        'Dir.Nac.Cárceles,Penitenciarías y Centros de Recuperación',
        'Dirección Nacional de Policía de Tránsito',
        'Jefatura de Policía de Maldonado',
        'Dirección Nacional de Sanidad Policial',
        'Jefatura de Policía de Rivera',
        'Jefatura de Policía de Montevideo',
        'Dirección Nacional de Asuntos Sociales',
        'Jefatura de Policía de Salto',
        'Jefatura de Policía de Cerro Largo',
        'Jefatura de Policía de Tacuarembó',
        'Jefatura de Policía de Paysandú',
        'Dirección Nacional de Bomberos',
        'Jefatura de Policía de Durazno',
        'Jefatura de Policía de Lavalleja',
        'Jefatura de Policía de Colonia',
        'Jefatura de Policía de Artigas',
        'Jefatura de Policía de Rocha',
        'Jefatura de Policía de Canelones',
        'Jefatura de Policía de San José',
        'Jefatura de Policía de Soriano',
        'Dirección Nacional de Identificación Civil',
        'Jefatura de Policía de Flores',
        'Jefatura de Policía de Río Negro',
        'Dirección Nacional de Migración',
        'Dirección Nacional de Policia Cientifica',
        'Escuela Nacional de Policía',
        'Instituto Nacional de Rehabilitación',
        'Jefatura de Policía de Florida',
        'Jefatura de Policía de Teinta y Tres',
        'Dirección Nacional de Asistencia Social Policial',
        'Guardia Republicana',
        'Dirección Nacional de Policía Caminera',
        'Dirección Nacional de la Seguridad Rural',
        'Dirección Nacional de Policía Científica',
        'Dirección Nacional de Asistencia y Seguridad Social Policial',
        'Dirección Nacional de Información e Inteligencia',
        'Jefatura de Policía de Treinta y Tres',
        'Dirección Nacional de Prevención Social del Delito',
        'Intendencia de Rivera',
        'Instituto Nacional de Inclusion Social Adolescente',
      ],
      search: 'vigilancia',
      yearFrom: 2022,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'Subrayado', title: 'Ministerio del Interior entregó dinero a Jefatura de Montevideo para pagar servicio 222 a policías', url: 'https://www.subrayado.com.uy/ministerio-del-interior-entrego-dinero-jefatura-montevideo-pagar-servicio222-policias-n967822', date: '2025-01-26' },
      { outlet: 'El Observador', title: 'Jefatura de Rivera anunció que no brindará el servicio 222 de la Policía desde octubre por deuda de casi $ 10 millones de la Intendencia', url: 'https://www.elobservador.com.uy/nacional/jefatura-rivera-anuncio-que-no-brindara-el-servicio-222-la-policia-octubre-deuda-casi-10-millones-la-intendencia-n6017576', date: '2025-09-18' },
      { outlet: 'Tribunal de Cuentas de la República', title: 'Resoluciones 38575 a 38581: reiteración del gasto por facturas del servicio de vigilancia del artículo 222 emitidas por Jefaturas de Policía', url: 'https://www.tcr.gub.uy/resultado_busqueda.php?p=51', date: '2022-04-06' },
    ],
    es: {
      title: 'Servicio 222: el Estado le debe a su propia Policía',
      dek: 'Organismos públicos contratan custodia policial y no pagan a tiempo. El atraso llega al bolsillo del policía y obliga al ministerio a adelantar fondos.',
      contexto: 'El "servicio 222", por el artículo 222 de la ley 13.318, es el mecanismo por el cual organismos públicos y empresas privadas contratan policías fuera de su horario para custodiar instalaciones, valores o dar seguridad en eventos. El contratante paga a la Jefatura de Policía correspondiente y ésta liquida a los funcionarios. Es una porción relevante del ingreso de miles de policías y, del lado del Estado, una compra de servicios que muchas veces ocurre entre organismos públicos. Cuando el contratante no paga, la Jefatura no puede liquidar y el atraso termina recayendo sobre el salario del funcionario que ya cumplió el turno.',
      hallazgo: 'Subrayado informó el 26 de enero de 2025 que los policías de Montevideo cobraron el 222 con diez días de atraso, atribuido a que los contratantes no giraron los fondos a la Jefatura, y que el Ministerio del Interior transfirió dinero para destrabar el pago; la AUF había abonado ese viernes $ 1,7 millones a cuenta de su deuda y ASSE adeudaba en total unos US$ 13 millones. El dirigente sindical Ricardo González dijo a ese medio que hay mala gestión y que el problema es que no se cobra a tiempo, no el desempeño de los funcionarios. El Observador informó el 18 de septiembre de 2025 que la Jefatura de Rivera anunció que desde octubre dejaría de prestar el 222 a la Intendencia por una deuda de $ 9.845.446 —el servicio cubría la Terminal Turística, la Terminal de Ómnibus y la Cantera— y que, según el jefe de Policía Germán Suárez, una trasposición de fondos del ministerio permitió pagar agosto y setiembre. El propio Tribunal de Cuentas registra reiteraciones del gasto por facturas del servicio 222 emitidas por las Jefaturas de Montevideo y Canelones a INISA.',
      statusNote: 'El circuito se repite. El 6 de abril de 2022 el Tribunal de Cuentas dictó las resoluciones 38575 a 38581, sucesivas reiteraciones del gasto por convalidación de facturas del servicio 222 entre INISA y las Jefaturas de Montevideo y Canelones, por servicios prestados entre setiembre de 2021 y enero de 2022. En enero de 2025 el conflicto llegó a poner en duda la cobertura policial del clásico Nacional-Peñarol en el Centenario, que se cubrió con unos 450 efectivos tras el pago de la AUF. En setiembre de 2025 una Jefatura anunció que cortaba el servicio a una intendencia. Al cierre de esta ficha (agosto de 2026) no encontramos información pública sobre la cancelación de la deuda de ASSE ni novedades posteriores a setiembre de 2025.',
      porQueImporta: 'Es plata pública que va de un organismo del Estado a otro y que, cuando se atrasa, la termina pagando el policía que ya hizo el turno. Además encarece la operación: hospitales, intendencias y entes contratan custodia policial en vez de resolver la seguridad por otra vía, y esa factura no siempre se discute en el presupuesto.',
      caveat: 'Parte del 222 se factura entre organismos públicos y puede no aparecer como compra en el feed de compras estatales. El rastro más firme está en las resoluciones de reiteración del gasto del Tribunal de Cuentas y en los rubros de vigilancia de cada organismo comprador.',
    },
    en: {
      title: 'Service 222: the State owes money to its own police',
      dek: 'Public bodies hire police guard duty and pay late. The delay lands on the officer\'s payslip and forces the ministry to advance the funds.',
      contexto: '"Service 222", under article 222 of law 13,318, is the mechanism by which public bodies and private companies hire police officers off-duty to guard facilities and valuables or provide security at events. The client pays the relevant Police Headquarters, which then pays the officers. It is a significant share of thousands of officers\' income and, on the State\'s side, a service purchase that often happens between public bodies. When the client does not pay, headquarters cannot settle, and the delay ends up hitting the wage of the officer who already worked the shift.',
      hallazgo: 'Subrayado reported on 26 January 2025 that Montevideo officers were paid their 222 wages ten days late, attributed to clients failing to remit funds to headquarters, and that the Interior Ministry transferred money to unblock the payment; the AUF football association had paid $ 1.7 million that Friday against its debt, and ASSE owed around US$ 13 million in total. Union leader Ricardo González told the outlet there is poor management and that the problem is failure to collect on time, not officers\' performance. El Observador reported on 18 September 2025 that Rivera police headquarters announced it would stop providing service 222 to the municipal government from October over a debt of $ 9,845,446 — the service covered the Tourist Terminal, the Bus Terminal and the Quarry — and that, according to police chief Germán Suárez, a transfer of funds from the ministry allowed August and September to be paid. The Tribunal de Cuentas itself records reiterated spending over service 222 invoices issued by the Montevideo and Canelones headquarters to INISA.',
      statusNote: 'The pattern repeats. On 6 April 2022 the Tribunal de Cuentas issued resolutions 38575 to 38581, successive reiterations of spending over the validation of service 222 invoices between INISA and the Montevideo and Canelones police headquarters, for services provided between September 2021 and January 2022. In January 2025 the dispute put police coverage of the Nacional-Peñarol derby at the Centenario in doubt; it was staffed with around 450 officers after the AUF\'s payment. In September 2025 a headquarters announced it was cutting the service to a municipal government. As this file closes (August 2026) we found no public information on ASSE\'s debt being settled, nor developments after September 2025.',
      porQueImporta: 'This is public money moving from one State body to another, and when it is late the officer who already worked the shift pays for it. It also raises costs: hospitals, municipal governments and state enterprises buy police guard duty instead of solving security another way, and that bill is not always debated in the budget.',
      caveat: 'Part of service 222 is invoiced between public bodies and may not appear as a purchase in the state procurement feed. The firmest trail is in the Tribunal de Cuentas\' reiterated-spending resolutions and in each buying body\'s security line items.',
    },
  },
  {
    slug: 'hacinamiento-carcelario-muertes-custodia',
    emoji: '⛓️',
    theme: 'seguridad',
    period: '2023-2026',
    statusKind: 'auditoria',
    status: 'auditoria',
    organisms: ['Ministerio del Interior', 'Instituto Nacional de Rehabilitación'],
    feedCoverage: 'likely',
    sources: [
      { outlet: 'Subrayado', title: 'Hay casi 15.000 reclusos y la mayoría de las cárceles tienen hacinamiento crítico, dice informe del Comisionado Parlamentario', url: 'https://www.subrayado.com.uy/hay-casi-15000-reclusos-y-la-mayoria-las-carceles-tienen-hacinamiento-critico-dice-informe-del-comisionado-n956260', date: '2024-09-04' },
      { outlet: 'UyPress', title: 'Uruguay aumentó su tasa de reclusión y hubo 57 muertes bajo custodia del Estado, según informe del comisionado', url: 'https://www.uypress.net/Actualidad/Uruguay-aumento-su-tasa-de-reclusion-y-hubo-57-muertes-bajo-custodia-del-Estado-segun-informe-del-comisionado-uc146979', date: '2025-09-13' },
      { outlet: 'Brecha', title: 'Hasta las manos', url: 'https://brecha.com.uy/hasta-las-manos-2/', date: '2025-09-19' },
      { outlet: 'Caras y Caretas', title: 'Los problemas endémicos del sistema penitenciario uruguayo y las medidas adoptadas para solucionarlos', url: 'https://www.carasycaretas.com.uy/sociedad/los-problemas-endemicos-del-sistema-penitenciario-uruguayo-y-las-medidas-adoptadas-solucionarlos-n95472', date: '2026-05-15' },
    ],
    es: {
      title: 'Cárceles por encima del 120%: 57 muertes bajo custodia en 2024',
      dek: 'El Comisionado Parlamentario documentó hacinamiento crítico, muertes con fallas de asistencia y hasta camas vacías por mala distribución, mientras el sistema sigue creciendo.',
      contexto: 'El Comisionado Parlamentario Penitenciario, cargo creado por el Parlamento para vigilar el sistema carcelario, publica un informe anual sobre el estado de las unidades. El cargo lo ocupó Juan Miguel Petit, que presentó su último informe anual en setiembre de 2025. El sistema depende del Instituto Nacional de Rehabilitación, órgano desconcentrado del Ministerio del Interior, que compra alimentos, insumos, mantenimiento y servicios para todas las unidades del país. La población privada de libertad crece de forma sostenida y Uruguay tiene la tasa de encarcelamiento más alta de Sudamérica.',
      hallazgo: 'Subrayado informó en setiembre de 2024 que el informe del comisionado contabilizaba 14.968 personas presas a fines de 2023, con el sistema por encima del 120% de densidad, la mayoría de los establecimientos en hacinamiento crítico y 51 muertes bajo custodia en el año (17 homicidios, 13 suicidios, 2 accidentales y 19 no violentas), sobre una tasa de 435 presos cada 100.000 habitantes. En setiembre de 2025, según UyPress, el informe siguiente registró 57 muertes bajo custodia en 2024 —el segundo año con más muertes del registro, detrás de las 86 de 2021—, de las cuales 36 fueron violentas: 18 homicidios, 15 suicidios, dos accidentales por intoxicación y una por caída de altura; la tasa de 2024 fue de 456 presos cada 100.000 habitantes y a mediados de 2025 llegó a 477. Brecha detalló ese mismo informe: negligencias asistenciales o fallas institucionales del Estado en 27 de las muertes (el 47%), densidad de 147% en las cárceles de mujeres, un 46% de las unidades con "tratos crueles, inhumanos o degradantes" y cerca de 1.500 plazas sin utilizar en 2024 por fallas de distribución, 500 de ellas en un solo centro. Petit propuso crear una fiscalía penitenciaria especializada porque, dijo, en las cárceles ocurren delitos que el sistema judicial no atiende.',
      statusNote: 'La población siguió creciendo. Caras y Caretas informó el 15 de mayo de 2026, sobre la base del informe parlamentario de la directora del INR, Ana Juanche, que había 16.789 personas privadas de libertad y una tasa de 480 cada 100.000 habitantes, la más alta de Sudamérica y la octava del mundo, con Colonia y Rocha por encima del 200% de ocupación y Durazno por encima del 180%. Juanche afirmó que el 74% vuelve a delinquir dentro de los tres años de la salida. El mismo medio consignó que se crearon 1.000 cargos nuevos —500 operadores penitenciarios y 500 policías— distribuidos hasta 2029, que en marzo de 2026 egresó el primer grupo de 195 agentes, y que la participación en trabajo o estudio pasó del 37% al 53% entre noviembre de 2025 y marzo de 2026.',
      porQueImporta: 'Cada plaza carcelaria se paga con impuestos y cada muerte bajo custodia ocurre bajo responsabilidad del Estado. Con cerca de 1.500 plazas sin usar por problemas de distribución, según el informe del comisionado, parte del hacinamiento no es falta de plata sino de gestión. Y con el 74% de reincidencia a tres años que reportó la dirección del INR, el gasto no está comprando el resultado que promete.',
      caveat: 'El informe del comisionado no publica precios de compra. Lo que sí puede cruzarse con datos abiertos es el gasto del INR y del Ministerio del Interior en alimentación, colchones, higiene y mantenimiento por unidad, para ver si acompañó el crecimiento de la población.',
    },
    en: {
      title: 'Prisons above 120%: 57 deaths in custody in 2024',
      dek: 'The Parliamentary Commissioner documented critical overcrowding, deaths with care failures and even empty beds from poor distribution, while the system keeps growing.',
      contexto: 'The Parliamentary Prison Commissioner, an office created by Parliament to oversee the prison system, publishes an annual report on the state of the units. The post was held by Juan Miguel Petit, who presented his final annual report in September 2025. The system depends on the National Rehabilitation Institute, a decentralised body of the Interior Ministry that buys food, supplies, maintenance and services for every unit in the country. The prison population has grown steadily and Uruguay has the highest incarceration rate in South America.',
      hallazgo: 'Subrayado reported in September 2024 that the commissioner\'s report counted 14,968 people imprisoned at the end of 2023, with the system above 120% density, most facilities in critical overcrowding and 51 deaths in custody that year (17 homicides, 13 suicides, 2 accidental and 19 non-violent), against a rate of 435 prisoners per 100,000 inhabitants. In September 2025, according to UyPress, the next report recorded 57 deaths in custody during 2024 — the second-highest year on record, behind the 86 of 2021 — of which 36 were violent: 18 homicides, 15 suicides, two accidental by intoxication and one by fall from height; the 2024 rate was 456 prisoners per 100,000 inhabitants and reached 477 by mid-2025. Brecha detailed the same report: care negligence or State institutional failures in 27 of the deaths (47%), 147% density in women\'s prisons, 46% of units with "cruel, inhuman or degrading treatment", and around 1,500 places unused in 2024 because of distribution failures, 500 of them in a single facility. Petit proposed creating a specialised prison prosecutor\'s office because, he said, crimes occur in prisons that the justice system does not address.',
      statusNote: 'The population kept growing. Caras y Caretas reported on 15 May 2026, drawing on the parliamentary report by INR director Ana Juanche, that there were 16,789 people deprived of liberty and a rate of 480 per 100,000 inhabitants, the highest in South America and the eighth in the world, with Colonia and Rocha above 200% occupancy and Durazno above 180%. Juanche stated that 74% reoffend within three years of release. The same outlet noted that 1,000 new posts were created — 500 prison officers and 500 police — distributed through 2029, that the first group of 195 agents graduated in March 2026, and that participation in work or study rose from 37% to 53% between November 2025 and March 2026.',
      porQueImporta: 'Every prison place is paid for with taxes, and every death in custody happens under the State\'s responsibility. With around 1,500 places unused because of distribution problems, according to the commissioner\'s report, part of the overcrowding is not a lack of money but of management. And with the 74% three-year reoffending rate reported by the INR\'s leadership, the spending is not buying the result it promises.',
      caveat: 'The commissioner\'s report does not publish purchase prices. What can be cross-checked against open data is INR and Interior Ministry spending on food, mattresses, hygiene and maintenance per unit, to see whether it kept pace with population growth.',
    },
  },
  {
    slug: 'camaras-videovigilancia-reconocimiento-facial',
    emoji: '📹',
    theme: 'seguridad',
    period: '2019-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'US$ 638.913 el software de reconocimiento facial más US$ 238.178 por tres años de mantenimiento (El Observador, 2020); más de US$ 100 millones de inversión tecnológica anunciada por el ministerio en 2026',
    organisms: ['Ministerio del Interior'],
    feedCoverage: 'likely',
    sources: [
      { outlet: 'El Observador', title: 'Licitación por cámaras de seguridad: Interior apretó el acelerador y negó prórroga a oferentes', url: 'https://www.elobservador.com.uy/nota/licitacion-por-camaras-interior-apreto-el-acelerador-y-nego-prorroga-a-oferentes-2019315221136', date: '2019-03-16' },
      { outlet: 'El Observador', title: 'Reconocimiento facial en la mira: así funciona el sistema comprado por la Policía', url: 'https://www.elobservador.com.uy/nota/reconocimiento-facial-en-la-mira-asi-funciona-el-sistema-comprado-por-la-policia-2020111916510', date: '2020-11-20' },
      { outlet: 'Telenoche', title: 'Ministerio del Interior planea cerrar el período con 14 mil cámaras: les integrarán inteligencia artificial', url: 'https://www.telenoche.com.uy/nacionales/ministerio-del-interior-planea-cerrar-periodo-14-mil-camaras-les-integraran-inteligencia-artificial-n5367119', date: '2024-05-03' },
      { outlet: 'Ministerio del Interior', title: 'Ministerio del Interior fortalece la seguridad pública con una inversión histórica', url: 'https://www.gub.uy/ministerio-interior/comunicacion/noticias/ministerio-del-interior-fortalece-seguridad-publica-inversion-historica', date: '2026-04-01' },
    ],
    es: {
      title: 'Cámaras y reconocimiento facial: quién gana esas licitaciones',
      dek: 'El Ministerio del Interior pasó de menos de 6.000 a más de 20.000 cámaras. En una licitación clave, un requisito de certificación dejó sólo dos oferentes en carrera.',
      contexto: 'La videovigilancia es la principal apuesta tecnológica del Ministerio del Interior. Telenoche informó en mayo de 2024 que el sistema había pasado de menos de 6.000 cámaras al inicio del período a 12.000, con una meta de 14.000 y software de inteligencia artificial para generar alertas automáticas; según el entonces comisario general Gabriel Lima, el software apunta a detectar movimientos como el de una persona que va a disparar o que pide ayuda con señas frente a una cámara. En abril de 2026 el propio ministerio comunicó una inversión superior a US$ 100 millones y más de 20.000 cámaras instaladas, junto con pórticos lectores de matrículas, drones térmicos y unidades móviles. A esa red se sumó, desde 2020, un software de reconocimiento facial comprado por licitación pública.',
      hallazgo: 'El Observador informó el 16 de marzo de 2019 que, en la licitación para instalar 1.000 cámaras donadas por China en Artigas, Rivera, Cerro Largo y Rocha, el Ministerio del Interior rechazó las prórrogas que dos empresas pidieron para conseguir una carta de Huawei que las acreditara como distribuidoras o integradoras autorizadas, requisito excluyente del pliego; alegó razones de servicio y la urgencia de instalar las cámaras, y sostuvo que al ser un requisito excluyente no podía presentarse después de la apertura de ofertas. Cabo Norte, Servinfo y Sonda desistieron al conocer la exigencia y quedaron sólo dos ofertas: DDBA e Ingeniería en Seguridad. El mismo diario informó el 20 de noviembre de 2020 que el software de reconocimiento facial se adjudicó por licitación pública, en febrero de 2020, a DDBA, representante de la española Herta, por US$ 638.913 más US$ 238.178 por tres años de mantenimiento, para al menos 3.000 dispositivos móviles y al menos 300 puestos policiales. Veintidós organizaciones sociales y académicas enviaron una carta a los legisladores advirtiendo por los sesgos de estos sistemas; Patricia Díaz, de Datysoc, sostuvo que tienen sesgos significativos y mayores tasas de error en mujeres, personas mayores y personas de piel oscura.',
      statusNote: 'La red siguió creciendo. El 1º de abril de 2026 el Ministerio del Interior informó una inversión superior a US$ 100 millones, más de 20.000 cámaras —un crecimiento del 21%—, la instalación del quinto pórtico lector de matrículas en el área metropolitana con una meta de 28 a fin de año y más de 50 en total, y drones con cámara térmica operados desde el Centro de Comando Unificado. El director de ese centro, el comisario general Víctor Torres, dijo que las tecnologías fueron analizadas y desarrolladas junto a los equipos de innovación del ministerio. Al cierre de esta ficha (agosto de 2026) no encontramos auditorías publicadas sobre el uso del reconocimiento facial ni una respuesta oficial al planteo de las organizaciones de 2020.',
      porQueImporta: 'Es la inversión tecnológica más grande del ministerio y lo que está en juego es quién puede competir por ella. Cuando un requisito técnico deja sólo dos oferentes, el precio lo termina fijando un mercado de dos. Y el reconocimiento facial se aplica sobre gente que camina por la calle: su margen de error tiene consecuencias concretas.',
      caveat: 'Las licitaciones de cámaras y software sí figuran en el portal de compras estatales, pero los montos anunciados en comunicados y conferencias agregan obra, equipamiento y servicios de varios llamados y no coinciden uno a uno con los expedientes.',
    },
    en: {
      title: 'Cameras and facial recognition: who wins those tenders',
      dek: 'The Interior Ministry went from under 6,000 to more than 20,000 cameras. In one key tender, a certification requirement left only two bidders in the race.',
      contexto: 'Video surveillance is the Interior Ministry\'s main technology bet. Telenoche reported in May 2024 that the system had gone from under 6,000 cameras at the start of the term to 12,000, with a target of 14,000 and artificial intelligence software to generate automatic alerts; according to then General Commissioner Gabriel Lima, the software aims to detect movements such as a person about to fire a shot or signalling for help in front of a camera. In April 2026 the ministry itself announced an investment of more than US$ 100 million and over 20,000 cameras installed, alongside licence-plate reading gantries, thermal drones and mobile units. Since 2020 that network has also included facial recognition software bought through a public tender.',
      hallazgo: 'El Observador reported on 16 March 2019 that, in the tender to install 1,000 cameras donated by China in Artigas, Rivera, Cerro Largo and Rocha, the Interior Ministry rejected the extensions two firms requested to obtain a letter from Huawei accrediting them as authorised distributors or integrators, a disqualifying requirement of the specification; it cited service reasons and the urgency of installing the cameras, and held that as a disqualifying requirement it could not be submitted after bids were opened. Cabo Norte, Servinfo and Sonda withdrew once they learned of the requirement, and only two bids remained: DDBA and Ingeniería en Seguridad. The same paper reported on 20 November 2020 that facial recognition software was awarded through a public tender, in February 2020, to DDBA, the local representative of Spain\'s Herta, for US$ 638,913 plus US$ 238,178 for three years of maintenance, covering at least 3,000 mobile devices and at least 300 police workstations. Twenty-two social and academic organisations sent a letter to legislators warning about the biases of these systems; Patricia Díaz, of Datysoc, argued they carry significant biases and higher error rates for women, older people and people with darker skin.',
      statusNote: 'The network kept growing. On 1 April 2026 the Interior Ministry announced an investment of more than US$ 100 million, over 20,000 cameras — 21% growth — the installation of the fifth licence-plate reading gantry in the metropolitan area with a target of 28 by year\'s end and more than 50 in total, and thermal-camera drones operated from the Unified Command Centre. The centre\'s director, General Commissioner Víctor Torres, said the technologies had been analysed and developed alongside the ministry\'s innovation teams. As this file closes (August 2026) we found no published audits of facial recognition use, nor an official reply to the organisations\' 2020 warning.',
      porQueImporta: 'This is the ministry\'s largest technology investment, and what is at stake is who gets to compete for it. When a technical requirement leaves only two bidders, the price ends up set by a market of two. And facial recognition is applied to people walking down the street: its margin of error has concrete consequences.',
      caveat: 'Camera and software tenders do appear in the state procurement portal, but the amounts announced in releases and press conferences bundle works, equipment and services from several tenders and do not map one-to-one onto individual procurement files.',
    },
  },
  {
    slug: 'comunicaciones-policiales-tecnologia-china',
    emoji: '📻',
    theme: 'seguridad',
    period: '2024-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'US$ 1.251.900 la ampliación adjudicada por compra directa (Búsqueda, 2026)',
    organisms: ['Ministerio del Interior'],
    feedCoverage: 'likely',
    sources: [
      { outlet: 'Búsqueda', title: 'La Policía amplió por U$S 1,2 millones un nuevo sistema de comunicación interna, que utiliza tecnología china', url: 'https://www.busqueda.com.uy/informacion/la-policia-amplio-us-12-millones-un-nuevo-sistema-comunicacion-interna-que-utiliza-tecnologia-china-n5409234', date: '2026-01-22' },
      { outlet: 'Presidencia de la República', title: 'Policía Nacional incorporó equipos de alta tecnología en comunicación', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/policia-nacional-incorporo-equipos-alta-tecnologia-comunicacion', date: '2024-11-01' },
      { outlet: 'El Observador', title: 'Un golpe a la crónica roja', url: 'https://www.elobservador.com.uy/nota/un-golpe-a-la-cronica-roja-20161812100', date: '2016-01-08' },
    ],
    es: {
      title: 'La radio de la Policía: US$ 1,25 millones por compra directa',
      dek: 'Interior amplió sin licitación el sistema con tecnología Huawei que había probado en Rivera. El proveedor es el mismo que le vende cámaras y software a la Policía.',
      contexto: 'La Policía uruguaya cambió su radio abierta analógica por el sistema digital cifrado TETRA a fines de 2010. El Observador informó en enero de 2016 que la inversión inicial fue de 37 millones de pesos y que había unas 4.500 terminales de origen británico a unos 600 euros cada una, que reportan su posición cada dos minutos o cada doscientos metros, con cobertura en Montevideo, Las Piedras, Pando y Canelones mientras en el resto del interior seguía el viejo sistema analógico y abierto. En noviembre de 2024 el ministerio presentó un sistema nuevo: 170 equipos para Rivera, con radiobase exclusiva, transmisión en tiempo real de imagen y audio, comunicaciones cifradas y migración automática a LTE fuera del área de cobertura. Presidencia informó que en la presentación participaron representantes de Huawei y DDBA.',
      hallazgo: 'Búsqueda informó el 22 de enero de 2026 que el Ministerio del Interior amplió ese sistema por US$ 1.251.900 mediante una compra directa, como extensión del piloto de 170 equipos que había funcionado en Rivera entre 2024 y 2025. El adjudicatario es HO Tecnología (DDBA LTDA.) y la tecnología es Huawei LTE MCCS, una red privada cifrada de voz, video y datos con radiobase dedicada de hasta 12 kilómetros. Según la nota, el Centro de Comando Unificado determinó la necesidad de continuar con el servicio a partir del resultado del piloto en esa zona de frontera, y Gabriel Lima —entonces director de ese centro y hoy jefe de Policía de Durazno— sostuvo que el equipamiento es clave para operaciones de vigilancia en áreas amplias y permite trabajar con mayor protección ante posibles interferencias y conectividad asegurada en todo momento. La misma nota consigna que HO Tecnología también provee software y cámaras de videovigilancia a la Policía Nacional en varios departamentos y en escenarios como el Campeón del Siglo, el Estadio Centenario y el Gran Parque Central. Búsqueda no registró en esa nota objeciones de otras empresas ni reparos oficiales por el origen chino de la tecnología.',
      statusNote: 'El sistema está en despliegue tras el piloto de Rivera. En abril de 2026 el ministerio incluyó las comunicaciones seguras dentro del paquete tecnológico que anunció como inversión histórica, junto con cámaras, pórticos y drones. Al cierre de esta ficha (agosto de 2026) no encontramos impugnaciones publicadas, resoluciones del Tribunal de Cuentas ni pedidos de informes parlamentarios sobre esta ampliación posteriores a la nota de Búsqueda del 22 de enero de 2026.',
      porQueImporta: 'Una compra directa de US$ 1,25 millones no compite por precio: se adjudica sin llamado abierto. Y cuando el mismo proveedor concentra radios, cámaras y software policial, el Estado queda atado a una sola empresa para tres sistemas críticos, lo que encarece cualquier cambio de proveedor más adelante.',
      caveat: 'Las compras directas figuran en el portal de compras estatales, pero suelen describirse con objetos genéricos como "equipos de comunicación", lo que dificulta agruparlas. Para dimensionar la relación conviene sumar todas las adjudicaciones al mismo RUT y no sólo las que mencionan la marca.',
    },
    en: {
      title: 'Police radio: US$ 1.25 million by direct purchase',
      dek: 'Interior expanded the Huawei-technology system it had piloted in Rivera without a tender. The supplier is the same firm that sells the police cameras and software.',
      contexto: 'Uruguay\'s police replaced its open analogue radio with the encrypted digital TETRA system in late 2010. El Observador reported in January 2016 that the initial investment was 37 million pesos and that there were around 4,500 British-made terminals at roughly €600 each, reporting their position every two minutes or every two hundred metres, covering Montevideo, Las Piedras, Pando and Canelones while the rest of the interior kept the old open analogue system. In November 2024 the ministry presented a new system: 170 devices for Rivera, with a dedicated radio base, real-time transmission of image and audio, encrypted communications and automatic migration to LTE outside the coverage area. The Presidency reported that representatives of Huawei and DDBA took part in the presentation.',
      hallazgo: 'Búsqueda reported on 22 January 2026 that the Interior Ministry expanded that system by US$ 1,251,900 through a direct purchase, as an extension of the 170-device pilot that ran in Rivera between 2024 and 2025. The awardee is HO Tecnología (DDBA LTDA.) and the technology is Huawei LTE MCCS, an encrypted private network for voice, video and data with a dedicated radio base reaching up to 12 kilometres. According to the report, the Unified Command Centre determined the need to continue the service based on the pilot\'s results in that border area, and Gabriel Lima — then director of that centre and now Durazno police chief — argued the equipment is crucial for surveillance operations across wide areas and lets officers work with greater protection against possible interference and assured connectivity at all times. The same report notes that HO Tecnología also supplies software and surveillance cameras to the National Police in several departments and at venues such as Campeón del Siglo, Estadio Centenario and Gran Parque Central. Búsqueda recorded no objections from other firms nor official concerns about the Chinese origin of the technology.',
      statusNote: 'The system is being rolled out after the Rivera pilot. In April 2026 the ministry included secure communications in the technology package it announced as a historic investment, alongside cameras, gantries and drones. As this file closes (August 2026) we found no published challenges, Tribunal de Cuentas resolutions or parliamentary information requests about this expansion later than Búsqueda\'s 22 January 2026 report.',
      porQueImporta: 'A US$ 1.25 million direct purchase does not compete on price: it is awarded without an open tender. And when a single supplier holds radios, cameras and police software, the State is locked into one company for three critical systems, which makes switching suppliers later far more expensive.',
      caveat: 'Direct purchases do appear in the state procurement portal, but they are often described with generic objects such as "communications equipment", which makes grouping them hard. To size the relationship it is better to add up every award to the same tax ID, not only those naming the brand.',
    },
  },
  {
    slug: 'carcel-mujeres-fallo-judicial-incumplido',
    emoji: '🚺',
    theme: 'seguridad',
    period: '2023-2026',
    statusKind: 'judicial',
    status: 'condena',
    amountReported: 'US$ 46 millones la obra del nuevo Centro de Rehabilitación Femenino de Punta de Rieles (Presidencia, 2024)',
    organisms: ['Ministerio del Interior', 'Instituto Nacional de Rehabilitación'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Secretaría del Ministerio del Interior',
        'Dir.Nac.Cárceles,Penitenciarías y Centros de Recuperación',
        'Dirección Nacional de Policía de Tránsito',
        'Jefatura de Policía de Maldonado',
        'Dirección Nacional de Sanidad Policial',
        'Jefatura de Policía de Rivera',
        'Jefatura de Policía de Montevideo',
        'Dirección Nacional de Asuntos Sociales',
        'Jefatura de Policía de Salto',
        'Jefatura de Policía de Cerro Largo',
        'Jefatura de Policía de Tacuarembó',
        'Jefatura de Policía de Paysandú',
        'Dirección Nacional de Bomberos',
        'Jefatura de Policía de Durazno',
        'Jefatura de Policía de Lavalleja',
        'Jefatura de Policía de Colonia',
        'Jefatura de Policía de Artigas',
        'Jefatura de Policía de Rocha',
        'Jefatura de Policía de Canelones',
        'Jefatura de Policía de San José',
        'Jefatura de Policía de Soriano',
        'Dirección Nacional de Identificación Civil',
        'Jefatura de Policía de Flores',
        'Jefatura de Policía de Río Negro',
        'Dirección Nacional de Migración',
        'Dirección Nacional de Policia Cientifica',
        'Escuela Nacional de Policía',
        'Instituto Nacional de Rehabilitación',
        'Jefatura de Policía de Florida',
        'Jefatura de Policía de Teinta y Tres',
        'Dirección Nacional de Asistencia Social Policial',
        'Guardia Republicana',
        'Dirección Nacional de Policía Caminera',
        'Dirección Nacional de la Seguridad Rural',
        'Dirección Nacional de Policía Científica',
        'Dirección Nacional de Asistencia y Seguridad Social Policial',
        'Dirección Nacional de Información e Inteligencia',
        'Jefatura de Policía de Treinta y Tres',
        'Dirección Nacional de Prevención Social del Delito',
      ],
      search: 'rehabilitación',
      yearFrom: 2023,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Búsqueda', title: 'Funcionarios de la cárcel de mujeres denuncian ante la Comisión Interamericana un hacinamiento en condiciones infrahumanas', url: 'https://www.busqueda.com.uy/informacion/funcionarios-la-carcel-mujeres-denuncian-la-comision-interamericana-un-hacinamiento-condiciones-infrahumanas-n5393654', date: '2024-10-10' },
      { outlet: 'Búsqueda', title: 'Ministerio del Interior muda en mayo la cárcel de mujeres: un cambio sustantivo en condiciones, pero no en el modelo', url: 'https://www.busqueda.com.uy/informacion/ministerio-del-interior-muda-mayo-la-carcel-mujeres-un-cambio-sustantivo-condiciones-pero-no-modelo-n5411322', date: '2026-03-19' },
      { outlet: 'Presidencia de la República', title: 'Interior construirá nueva cárcel para mujeres, de 800 plazas', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/interior-construira-nueva-carcel-para-mujeres-800-plazas', date: '2024-11-20' },
      { outlet: 'Subrayado', title: 'Trasladan 800 presas a la cárcel de mujeres nueva en Punta de Rieles', url: 'https://www.subrayado.com.uy/trasladan-800-presas-la-carcel-mujeres-la-nueva-punta-rieles-n1014073', date: '2026-07-30' },
    ],
    es: {
      title: 'Cárcel de mujeres: dos años y medio de fallo incumplido',
      dek: 'La Unidad 5 llegó al 200% de ocupación y su propio sindicato la denunció ante la CIDH. Una jueza multó al Ministerio del Interior antes de que abriera el edificio nuevo.',
      contexto: 'La Unidad Nº 5 de Colón fue durante años la principal cárcel de mujeres del país. En noviembre de 2024 Presidencia anunció la construcción de un nuevo Centro de Rehabilitación Femenino en Punta de Rieles, con 846 plazas ampliables a 1.015, una inversión de unos US$ 46 millones y un plazo estimado de obra de 21 meses; el entonces ministro Nicolás Martinelli lo presentó como parte de la iniciativa del gobierno de generar 3.500 nuevas plazas, de las cuales ese centro y las tres unidades de Libertad aportarían 3.000. El proyecto incluye módulos para personas trans y un sector de prelibertad, y está pensado para sustituir a la Unidad Nº 5.',
      hallazgo: 'Búsqueda informó el 10 de octubre de 2024 que el Sindicato de Trabajadores Penitenciarios (Sitrapen), representado por su presidente Germán Gutiérrez, pidió medidas cautelares a la Comisión Interamericana de Derechos Humanos por la situación de la Unidad 5: 847 mujeres en un establecimiento diseñado para 424, un 200% de hacinamiento que el gremio describió como condiciones infrahumanas que afectan los derechos a la vida, la integridad física, la salud y la dignidad; pidió frenar nuevos ingresos hasta bajar el hacinamiento al 120%. El 19 de marzo de 2026 el mismo semanario informó que un fallo del 19 de febrero de 2026, de la jueza María Sol Bellomo, determinó que el Ministerio del Interior incumplió durante dos años y medio una orden judicial de habeas corpus para mejorar la unidad, cuyas condiciones seguían siendo, según la magistrada, violatorias de la dignidad humana pese a sucesivas prórrogas, e impuso una multa de 10 unidades reajustables por cada día de incumplimiento. Según esa nota, había entonces 806 mujeres en un lugar previsto para 470 —eran 719 en 2023—, con unos 30 profesionales del área técnica para más de 820 internas y, en seguridad operativa, 74 policías y 27 operadores penitenciarios en todos los turnos.',
      statusNote: 'El traslado se concretó. Subrayado informó el 30 de julio de 2026 que unas 800 mujeres fueron trasladadas en tres ómnibus del Ministerio del Interior, en varios viajes y con custodia, desde la Unidad 5 de Colón al nuevo establecimiento de Punta de Rieles, de 846 plazas iniciales ampliables a 1.015, con 66 de prelibertad y 30 para mujeres trans; las embarazadas y las madres con hijos permanecieron en Colón. El ministro Carlos Negro describió el operativo como complejo. La directora del INR, Ana Juanche, había dicho a Búsqueda que el nuevo edificio es un cambio sustantivo en las condiciones materiales, pero que el déficit de personal se revertirá de forma gradual y dentro de las restricciones presupuestales.',
      porQueImporta: 'El Estado quedó expuesto a una multa diaria por no cumplir a tiempo un fallo sobre condiciones de encierro que él mismo administra: es dinero público comprometido por no hacer algo. Y muestra que una obra de US$ 46 millones resuelve el edificio pero no el plantel: sin técnicos ni operadores suficientes, la plaza nueva arrastra el problema viejo.',
      caveat: 'La obra se ejecutó mediante un contrato de construcción cuyo detalle no siempre aparece desagregado en el feed de compras, y las fuentes consultadas no identifican a la empresa constructora. Sí pueden rastrearse las compras de equipamiento, mobiliario, alimentación y servicios asociadas al nuevo centro y a la Unidad 5 de Colón.',
    },
    en: {
      title: 'Women\'s prison: two and a half years of an unmet ruling',
      dek: 'Unit 5 hit 200% occupancy and its own union took it to the IACHR. A judge fined the Interior Ministry shortly before the new building opened.',
      contexto: 'Unit No. 5 in Colón was for years the country\'s main women\'s prison. In November 2024 the Presidency announced construction of a new Female Rehabilitation Centre at Punta de Rieles, with 846 places expandable to 1,015, an investment of around US$ 46 million and an estimated construction period of 21 months; then Minister Nicolás Martinelli presented it as part of the government\'s initiative to create 3,500 new places, of which that centre and the three units at Libertad would provide 3,000. The project includes modules for trans people and a pre-release sector, and is designed to replace Unit No. 5.',
      hallazgo: 'Búsqueda reported on 10 October 2024 that the Prison Workers\' Union (Sitrapen), represented by its president Germán Gutiérrez, requested precautionary measures from the Inter-American Commission on Human Rights over conditions at Unit 5: 847 women in a facility designed for 424, a 200% overcrowding rate the union described as subhuman conditions affecting the rights to life, physical integrity, health and dignity; it asked to halt new admissions until overcrowding fell to 120%. On 19 March 2026 the same weekly reported that a ruling of 19 February 2026 by judge María Sol Bellomo found the Interior Ministry had failed for two and a half years to comply with a habeas corpus order to improve the unit, whose conditions remained, in the judge\'s words, in violation of human dignity despite successive extensions, and imposed a fine of 10 adjustable units for each day of non-compliance. According to that report there were then 806 women in a facility designed for 470 — there were 719 in 2023 — with around 30 technical-area professionals for more than 820 inmates and, in operational security, 74 police officers and 27 prison officers across all shifts.',
      statusNote: 'The move went ahead. Subrayado reported on 30 July 2026 that around 800 women were transferred in three Interior Ministry buses, over several trips and under escort, from Unit 5 in Colón to the new Punta de Rieles facility, with 846 initial places expandable to 1,015, including 66 pre-release and 30 for trans women; pregnant women and mothers with children stayed in Colón. Minister Carlos Negro described the operation as complex. INR director Ana Juanche had told Búsqueda that the new building is a substantive change in material conditions, but that the staffing shortfall will be reversed gradually and within budget constraints.',
      porQueImporta: 'The State was exposed to a daily fine for failing to comply on time with a ruling about detention conditions it administers itself: public money committed for not doing something. And it shows a US$ 46 million building solves the premises but not the staff: without enough technical personnel and officers, the new place carries the old problem with it.',
      caveat: 'The works were carried out through a construction contract whose detail is not always itemised in the procurement feed, and the sources consulted do not identify the building company. What can be traced are purchases of equipment, furniture, food and services tied to the new centre and to Unit 5 in Colón.',
    },
  },
  {
    slug: 'camionetas-seguridad-rural-ayax-2020',
    emoji: '🛻',
    theme: 'seguridad',
    period: '2020-2026',
    statusKind: 'debate',
    status: 'debate',
    amountReported: 'US$ 1.376.430 por 55 camionetas Toyota Hilux DX 4x4 diésel, a US$ 25.026 cada una según el portal de Compras Estatales (Licitación Pública 2/2020)',
    organisms: ['Ministerio del Interior'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Secretaría del Ministerio del Interior',
        'Dir.Nac.Cárceles,Penitenciarías y Centros de Recuperación',
        'Dirección Nacional de Policía de Tránsito',
        'Jefatura de Policía de Maldonado',
        'Dirección Nacional de Sanidad Policial',
        'Jefatura de Policía de Rivera',
        'Jefatura de Policía de Montevideo',
        'Dirección Nacional de Asuntos Sociales',
        'Jefatura de Policía de Salto',
        'Jefatura de Policía de Cerro Largo',
        'Jefatura de Policía de Tacuarembó',
        'Jefatura de Policía de Paysandú',
        'Dirección Nacional de Bomberos',
        'Jefatura de Policía de Durazno',
        'Jefatura de Policía de Lavalleja',
        'Jefatura de Policía de Colonia',
        'Jefatura de Policía de Artigas',
        'Jefatura de Policía de Rocha',
        'Jefatura de Policía de Canelones',
        'Jefatura de Policía de San José',
        'Jefatura de Policía de Soriano',
        'Dirección Nacional de Identificación Civil',
        'Jefatura de Policía de Flores',
        'Jefatura de Policía de Río Negro',
        'Dirección Nacional de Migración',
        'Dirección Nacional de Policia Cientifica',
        'Escuela Nacional de Policía',
        'Instituto Nacional de Rehabilitación',
        'Jefatura de Policía de Florida',
        'Jefatura de Policía de Teinta y Tres',
        'Dirección Nacional de Asistencia Social Policial',
        'Guardia Republicana',
        'Dirección Nacional de Policía Caminera',
        'Dirección Nacional de la Seguridad Rural',
        'Dirección Nacional de Policía Científica',
        'Dirección Nacional de Asistencia y Seguridad Social Policial',
        'Dirección Nacional de Información e Inteligencia',
        'Jefatura de Policía de Treinta y Tres',
        'Dirección Nacional de Prevención Social del Delito',
      ],
      search: 'camionetas',
      yearFrom: 2020,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Agencia Reguladora de Compras Estatales (ARCE)', title: 'Licitación Pública 2/2020 – Ministerio del Interior: adquisición de camionetas doble cabina', url: 'https://www.comprasestatales.gub.uy/consultas/detalle/id/795445', date: '2020-07-08' },
      { outlet: 'Caras y Caretas', title: 'Ministerio del Interior compró camionetas a empresa de amigo de Lacalle Pou', url: 'https://www.carasycaretas.com.uy/ministerio-del-interior-camionetas', date: '2020-08-14' },
      { outlet: 'Caras y Caretas', title: 'Camionetas Toyota y compras estatales: las adjudicaciones a AYAX durante el gobierno de Lacalle Pou', url: 'https://www.carasycaretas.com.uy/politica/camionetas-toyota-y-compras-estatales-las-adjudicaciones-ayax-el-gobierno-lacalle-pou-n95925', date: '2026-05-29' },
    ],
    es: {
      title: '55 camionetas para seguridad rural: la adjudicación a Ayax',
      dek: 'El Ministerio del Interior compró 55 Toyota Hilux por US$ 1,37 millones a la concesionaria oficial de la marca. Caras y Caretas cuestionó el procedimiento y el vínculo del titular con el presidente de entonces.',
      contexto: 'En 2020, en los primeros meses del gobierno de Luis Lacalle Pou, el Ministerio del Interior resolvió la Licitación Pública 2/2020 para adquirir hasta 60 camionetas doble cabina 4x2 y hasta 20 doble cabina 4x4. Según el registro del portal de Compras Estatales, con resolución del 8 de julio de 2020, la licitación se adjudicó parcialmente a AYAX S.A. —RUT 210383480019, concesionaria oficial de Toyota en Uruguay— por 55 camionetas Toyota Hilux DX 4x4 diésel a US$ 25.026 cada una, US$ 1.376.430 en total. También ofertaron Bloommy S.A., Darkinel S.A. y Ralitor S.A., que no resultaron adjudicadas. Los vehículos se destinaron a la Dirección Nacional de Seguridad Rural.',
      hallazgo: 'Caras y Caretas informó el 14 de agosto de 2020 que el ítem 1 —60 camionetas— no tuvo adjudicatario y que el ítem 2, de 55 unidades, se adjudicó a Ayax después de que la comisión asesora entendiera que su propuesta combinaba mejor la propuesta técnica, la garantía, la entrega y la oferta económica. El semanario situó el precio en US$ 27.528,60 por unidad, por encima de los US$ 25.026 que figuran en el portal oficial, y señaló que Ayax está presidida por Alejandro Curcio, citando una crónica de El País de marzo de 2020 que lo ubicaba entre los "amigos de años del presidente" presentes en la asunción. En mayo de 2026 el mismo medio volvió sobre el tema: sostuvo que parte del proceso derivó en una compra directa por excepción luego de que un ítem no recibiera ofertas válidas, y agregó que una compra posterior de ANEP en 2023 —19 Toyota Hilux 4x4 más mantenimiento, por más de US$ 611.000— fue observada por el Tribunal de Cuentas, que cuestionó el sistema de puntajes aplicado en la evaluación de ofertas y el cumplimiento de la eficiencia energética de la flota estatal; la comisión asesora de adjudicación defendió la elección alegando que era la única oferta válida y admisible.',
      statusNote: 'No consta una denuncia penal ni una investigación administrativa sobre la Licitación Pública 2/2020 del Ministerio del Interior, ni se ha establecido irregularidad alguna en esa compra. Ninguna de las notas recoge una respuesta de Ayax ni del ministerio, y no encontramos un descargo oficial publicado; lo más cercano en el expediente es la defensa de la comisión asesora de adjudicación. Al cierre de esta ficha (agosto de 2026) el caso sigue siendo un cuestionamiento político y periodístico, reflotado por Caras y Caretas en mayo de 2026, sin resolución de organismos de control sobre esa compra en particular.',
      porQueImporta: 'Comprar camionetas para la Policía Rural es una compra corriente y legítima; lo que se discute es el procedimiento y el precio. Con el expediente público cualquiera puede verificar cuánto pagó el Estado por unidad y compararlo con lo que pagaron otros organismos por el mismo modelo el mismo año. Ese es exactamente el control que habilitan los datos abiertos.',
      caveat: 'Este caso sí está en los datos abiertos: la Licitación Pública 2/2020 figura en el portal de Compras Estatales con montos y oferentes. La diferencia entre el precio unitario del portal (US$ 25.026) y el que publicó la prensa (US$ 27.528,60) no está explicada en las fuentes consultadas, y las observaciones del Tribunal de Cuentas que cita Caras y Caretas corresponden a una compra posterior de ANEP, no a esta licitación del Ministerio del Interior.',
    },
    en: {
      title: '55 pickups for rural security: the Ayax award',
      dek: 'The Interior Ministry bought 55 Toyota Hilux for US$ 1.37 million from the brand\'s official dealer. Caras y Caretas questioned the procedure and the owner\'s ties to the then president.',
      contexto: 'In 2020, during the first months of Luis Lacalle Pou\'s government, the Interior Ministry resolved Public Tender 2/2020 to acquire up to 60 double-cab 4x2 pickups and up to 20 double-cab 4x4s. According to the record in the state procurement portal, with a resolution dated 8 July 2020, the tender was partially awarded to AYAX S.A. — tax ID 210383480019, Toyota\'s official dealer in Uruguay — for 55 Toyota Hilux DX 4x4 diesel pickups at US$ 25,026 each, US$ 1,376,430 in total. Bloommy S.A., Darkinel S.A. and Ralitor S.A. also bid and were not awarded. The vehicles went to the National Directorate of Rural Security.',
      hallazgo: 'Caras y Caretas reported on 14 August 2020 that item 1 — 60 pickups — had no awardee and that item 2, for 55 units, was awarded to Ayax after the advisory committee found its bid best combined technical proposal, guarantee, delivery and price. The weekly put the price at US$ 27,528.60 per unit, above the US$ 25,026 recorded in the official portal, and noted that Ayax is chaired by Alejandro Curcio, citing an El País chronicle from March 2020 placing him among the president\'s "longtime friends" present at the inauguration. In May 2026 the same outlet returned to the subject: it held that part of the process ended in a direct purchase by exception after one item received no valid bids, and added that a later purchase by the education authority ANEP in 2023 — 19 Toyota Hilux 4x4 plus maintenance, for more than US$ 611,000 — was observed by the Tribunal de Cuentas, which questioned the scoring system used to evaluate bids and compliance with energy efficiency rules for the state fleet; the award advisory committee defended the choice on the grounds that it was the only valid and admissible offer.',
      statusNote: 'There is no record of a criminal complaint or administrative investigation into the Interior Ministry\'s Public Tender 2/2020, and no irregularity has been established in that purchase. None of the reports contains a response from Ayax or the ministry, and we found no published official rebuttal; the closest thing on record is the award advisory committee\'s defence. As this file closes (August 2026) the case remains a political and journalistic question, revived by Caras y Caretas in May 2026, with no ruling from oversight bodies on that particular purchase.',
      porQueImporta: 'Buying pickups for the rural police is a routine and legitimate purchase; what is in dispute is the procedure and the price. With the file public, anyone can check what the State paid per unit and compare it with what other bodies paid for the same model in the same year. That is exactly the scrutiny open data makes possible.',
      caveat: 'This case is in the open data: Public Tender 2/2020 appears in the state procurement portal with amounts and bidders. The gap between the portal\'s unit price (US$ 25,026) and the one published in the press (US$ 27,528.60) is not explained in the sources consulted, and the Tribunal de Cuentas observations cited by Caras y Caretas correspond to a later ANEP purchase, not to this Interior Ministry tender.',
    },
  },
]
