import type { CasoDef } from '../types'

/**
 * telecomunicaciones — 10 dossiers, 9 of them with a live cross-reference.
 *
 * Every source URL was fetched and every query was resolved against the live
 * collection before this file was committed (scripts/verify-casos.ts re-checks
 * both). A caso with no `query` is not a gap in the research: its money does
 * not travel through the Compras Estatales feed at all, which `feedCoverage`
 * records and the page states outright.
 */
export const CASOS_TELECOMUNICACIONES: CasoDef[] = [
  {
    slug: 'antel-arena-sobrecosto-obra',
    emoji: '🏟️',
    theme: 'telecomunicaciones',
    period: '2013-2025',
    statusKind: 'judicial',
    status: 'archivo',
    amountReported: 'US$ 119,7 millones de costo total según la auditoría que Antel contrató a ECOVIS; US$ 85,995 millones según el Tribunal de Cuentas',
    organisms: ['ANTEL'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Administración Nacional de Telecomunicaciones',
      ],
      yearFrom: 2013,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'Telenoche', title: '¿Cuáles son las distintas cifras de la construcción del Antel Arena?', url: 'https://www.telenoche.com.uy/nacionales/cuales-son-las-distintas-cifras-la-construccion-del-antel-arena-n5363515', date: '2024-02-22' },
      { outlet: 'Subrayado', title: 'Antel Arena costó más de 90 millones de dólares; 8 millones más de lo declarado por Cosse', url: 'https://www.subrayado.com.uy/antel-arena-costo-mas-90-millones-dolares-8-millones-mas-lo-declarado-cosse-n524702', date: '2019-01-24' },
      { outlet: '180.com.uy', title: 'Cosse y el Antel Arena: “cometí un error cuando anuncié el proyecto y dije el costo”', url: 'https://www.180.com.uy/articulo/79690_cosse-y-el-antel-arena-cometi-un-error-cuando-anuncie-el-proyecto-y-dije-el-costo', date: '2019-06-05' },
      { outlet: 'Teledoce', title: 'Daniel Larrosa: "El Antel Arena costó 65 millones de dólares de inversión"', url: 'https://www.teledoce.com/programas/desayunos-informales/primera-manana/daniel-larrosa-el-antel-arena-costo-65-millones-de-dolares-de-inversion/', date: '2021-12-08' },
      { outlet: 'El Observador', title: 'Fiscalía volvió a archivar investigación sobre el Antel Arena', url: 'https://www.elobservador.com.uy/nacional/fiscalia-volvio-archivar-investigacion-el-antel-arena-n5984909', date: '2025-02-13' },
      { outlet: 'Ámbito', title: 'La Fiscalía archivó definitivamente el caso del Antel Arena', url: 'https://www.ambito.com/uruguay/la-fiscalia-archivo-definitivamente-el-caso-del-antel-arena-n6113244', date: '2025-02-13' },
    ],
    es: {
      title: 'Antel Arena: del anuncio de US$ 40 millones a las cifras en disputa',
      dek: 'Antel anunció en 2013 un complejo de US$ 40 millones. El costo final tiene al menos cuatro cifras distintas —90,5, 86, 88 y 119,7 millones— según quién lo mida.',
      contexto: 'El Antel Arena se levantó sobre el predio del viejo Cilindro Municipal. Antel, entonces presidida por Carolina Cosse, anunció el proyecto en 2013 con una inversión estimada en torno a los US$ 40 millones. El complejo se inauguró el 12 de noviembre de 2018. Desde entonces el costo real fue objeto de al menos cuatro mediciones distintas: un cálculo del Tribunal de Cuentas difundido en enero de 2019 a pedido del senador Pablo Mieres, un informe del mismo organismo del 6 de marzo de 2019, la cifra que la Fiscalía tomó como oficial y una auditoría externa que la propia Antel licitó en 2020. Ninguna coincide con otra.',
      hallazgo: 'Subrayado informó el 24 de enero de 2019, sobre datos del Tribunal de Cuentas difundidos por el semanario Búsqueda a pedido del senador Pablo Mieres (Partido Independiente), que la construcción superaba los US$ 90,5 millones: unos US$ 8 millones más que los US$ 82 millones declarados por Cosse, cifra que ya se conocía antes de la inauguración del 12 de noviembre de 2018. Telenoche detalló que el informe del Tribunal de Cuentas del 6 de marzo de 2019 sumó más de US$ 85 millones —más de US$ 49 millones de obra civil, US$ 2,5 millones de ejecución del proyecto y consultoría, US$ 17 millones de equipamiento y acondicionamiento técnico y más de US$ 17 millones de espacios exteriores, guardería, parque público y deporte— y que la Fiscalía tomó como cifra oficial US$ 88 millones. La auditoría que Antel encargó a ECOVIS llevó el total a unos US$ 119,7 millones (US$ 120 millones, según Telenoche). El director Daniel Larrosa (Frente Amplio) rechazó ese número en Teledoce: dijo que «el Antel Arena, según nuestros cálculos, costó unos 65 millones de dólares de inversión» y que «no se puede sumar inversiones y gastos». Cosse admitió en 180.com.uy: «Yo cometí un error cuando anuncié el proyecto y dije cuál era el costo», y atribuyó la diferencia a modificaciones no previstas durante la obra.',
      statusNote: 'La denuncia penal la presentó el directorio de Antel presidido por Gabriel Gurméndez, que denunció «apartamientos y contravenciones a normas y principios en materia de contratación administrativa». El fiscal Alejandro Machado archivó el caso el 22 de febrero de 2024: según Ámbito, sostuvo que hubo «desprolijidades» y un manejo dispendioso de recursos, pero no delitos. A pedido de Antel, el juez Alejandro Asteggiante habilitó el reexamen en mayo de 2024 y el fiscal Enrique Rodríguez archivó la causa de forma definitiva el 13 de febrero de 2025: concluyó que no hubo «desviación o irregularidad en la conducta de los investigados, pasible de ser sancionada penalmente». Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores al 13 de febrero de 2025.',
      porQueImporta: 'El Antel Arena se pagó con recursos de la empresa de telecomunicaciones del Estado, la misma que financia la red de fibra y el 5G y que vuelca sus utilidades a Rentas Generales. Que el costo final tenga cuatro cifras distintas y ninguna sea reconocida por todas las partes muestra hasta qué punto una obra pública puede terminar sin un número verificable para el contribuyente.',
      caveat: 'Buena parte de la obra se financió por un fideicomiso administrado por Conafin Afisa, por lo que muchos contratos pueden no figurar como compras de ANTEL en el portal de Compras Estatales. Lo que se cruza aquí es sólo lo que Antel registró a su nombre. La causa penal fue archivada de forma definitiva: no hay responsabilidad penal declarada contra ninguna persona.',
    },
    en: {
      title: 'Antel Arena: from a US$40 million announcement to disputed figures',
      dek: 'Antel announced a US$40 million complex in 2013. The final cost has at least four different figures — 90.5, 86, 88 and 119.7 million — depending on who measures it.',
      contexto: 'The Antel Arena was built on the site of the old Cilindro Municipal. Antel, then chaired by Carolina Cosse, announced the project in 2013 with an estimated investment of around US$40 million. The complex opened on 12 November 2018. Since then the real cost has been measured in at least four different ways: a Court of Audit calculation released in January 2019 at senator Pablo Mieres\'s request, a report by the same body dated 6 March 2019, the figure the Prosecutor\'s Office treated as official, and an external audit Antel itself tendered in 2020. No two of them agree.',
      hallazgo: 'Subrayado reported on 24 January 2019, using Court of Audit data published by the weekly Búsqueda at senator Pablo Mieres\'s (Partido Independiente) request, that the works exceeded US$90.5 million: some US$8 million more than the US$82 million declared by Cosse, a figure already known before the 12 November 2018 opening. Telenoche detailed that the Court of Audit\'s 6 March 2019 report added up to more than US$85 million — over US$49 million in civil works, US$2.5 million in project execution and consultancy, US$17 million in equipment and technical fit-out and more than US$17 million in outdoor areas, nursery, public park and sports facilities — and that the Prosecutor\'s Office treated US$88 million as the official figure. The audit Antel commissioned from ECOVIS put the total at around US$119.7 million (US$120 million, according to Telenoche). Board member Daniel Larrosa (Frente Amplio) rejected that figure on Teledoce: he said "the Antel Arena, by our calculations, cost around 65 million dollars in investment" and that "you cannot add investment and expenses together". Cosse admitted on 180.com.uy: "I made a mistake when I announced the project and stated its cost", attributing the gap to unforeseen changes during construction.',
      statusNote: 'The criminal complaint was filed by Antel\'s board under Gabriel Gurméndez, which alleged "departures from and breaches of rules and principles of administrative contracting". Prosecutor Alejandro Machado shelved the case on 22 February 2024: according to Ámbito, he held there had been "sloppiness" and wasteful management of resources, but no crimes. At Antel\'s request, judge Alejandro Asteggiante allowed a re-examination in May 2024 and prosecutor Enrique Rodríguez shelved the case definitively on 13 February 2025, concluding there was no "deviation or irregularity in the conduct of those investigated liable to criminal sanction". As of this file\'s closing (August 2026) there are no developments after 13 February 2025.',
      porQueImporta: 'The Antel Arena was paid for with the resources of the state telecoms company — the same one that funds the fibre network and 5G and transfers its profits to the Treasury. That the final cost has four different figures, none accepted by all parties, shows how far a public work can go without leaving taxpayers a verifiable number.',
      caveat: 'Much of the work was financed through a trust managed by Conafin Afisa, so many contracts may not appear as ANTEL purchases in the state procurement portal. What is cross-referenced here is only what Antel recorded under its own name. The criminal case was definitively shelved: no criminal liability has been established against anyone.',
    },
  },
  {
    slug: 'antel-arena-informacion-reservada-diez-anos',
    emoji: '🔒',
    theme: 'telecomunicaciones',
    period: '2015-2021',
    statusKind: 'auditoria',
    status: 'auditoria',
    amountReported: 'US$ 119,7 millones de costo total según la auditoría contratada por Antel, frente a US$ 40 millones anunciados en 2013 y US$ 56,5 millones del plan de negocios de 2015',
    organisms: ['ANTEL'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Administración Nacional de Telecomunicaciones',
      ],
      yearFrom: 2015,
      yearTo: 2021,
    },
    sources: [
      { outlet: '180.com.uy', title: 'Jutep, en base a auditoría contratada por Antel: el Antel Arena violó los principios de buena administración', url: 'https://www.180.com.uy/articulo/85252_jutep-en-base-a-auditoria-contratada-por-antel-el-antel-arena-violo-los-principios-de-buena-administracion', date: '2021-09-22' },
      { outlet: 'Subrayado', title: 'ANTEL publicó dictamen de la junta anticorrupción sobre construcción del Antel Arena', url: 'https://www.subrayado.com.uy/antel-publico-dictamen-la-junta-anticorrupcion-construccion-del-antel-arena-n797566', date: '2021-09-21' },
      { outlet: 'La Mañana', title: 'Múltiples repercusiones tras informe de Jutep sobre Antel Arena', url: 'https://www.xn--lamaana-7za.uy/politica/multiples-repercusiones-tras-informe-de-jutep-sobre-antel-arena/', date: '2021-09-29' },
      { outlet: 'ANTEL (comunicado oficial)', title: 'Antel reafirma transparencia en la selección del auditor externo del proyecto Antel Arena', url: 'https://www.antel.com.uy/institucional/sala-de-prensa/comunicados/antel-reafirma-transparencia-en-la-seleccion-del-auditor-externo-del-proyecto-antel-arena', date: '2021-09-22' },
      { outlet: 'El Observador', title: 'Fiscalía volvió a archivar investigación sobre el Antel Arena', url: 'https://www.elobservador.com.uy/nacional/fiscalia-volvio-archivar-investigacion-el-antel-arena-n5984909', date: '2025-02-13' },
    ],
    es: {
      title: 'La información del Antel Arena se clasificó como reservada por diez años',
      dek: 'Antel clasificó como reservadas por diez años las contrataciones del complejo. La JUTEP dictaminó en 2021, sobre una auditoría contratada por la propia Antel, que eso violó los principios de buena administración.',
      contexto: 'Durante la construcción del Antel Arena, el directorio de Antel resolvió clasificar como reservada la información de las contrataciones del proyecto por un plazo de diez años. Según el comunicado oficial de la empresa, el 23 de julio de 2020 el directorio presidido por Gabriel Gurméndez dispuso el llamado a licitación abreviada para contratar una auditoría del proyecto —se presentaron siete ofertas y la Comisión Asesora de Adjudicaciones sugirió adjudicar a ECOVIS «fundada en el criterio del menor precio»— y el 6 de agosto de 2020 resolvió levantar la reserva y desclasificar toda la información. Con la auditoría en la mano intervino la Junta de Transparencia y Ética Pública (JUTEP).',
      hallazgo: 'Según 180.com.uy, la JUTEP identificó tres apartamientos: incumplimiento del ordenamiento jurídico en las contrataciones, falta de transparencia por haber clasificado como reservadas «la totalidad de las contrataciones» por diez años, e ineficiencia económica por un sobrecosto que va de los US$ 40 millones anunciados en 2013 —US$ 56,5 millones en el plan de negocios de 2015— a los US$ 119,7 millones que arrojó la auditoría. Subrayado publicó el dictamen difundido por la propia Antel: la junta sostuvo que «la buena administración, tanto en la gestión financiera como en el uso de procedimientos idóneos para alcanzar los fines, estuvo ausente en este proyecto» y que se constató una violación a principios y normas de conducta que «pueden configurar falta administrativa, sin perjuicio de las responsabilidades políticas, civiles y penales que puedan corresponder a los funcionarios involucrados». La JUTEP aclaró que trabajó sobre la información de la auditoría que pidió Antel, no sobre una investigación propia. Carolina Cosse calificó el informe como una «pseudoauditoría» que no aportaba nada, según La Mañana.',
      statusNote: 'El dictamen de la JUTEP se conoció el 21 de septiembre de 2021 y Antel lo publicó. Según 180.com.uy, Antel había remitido los resultados de la auditoría de ECOVIS a la JUTEP el 14 de junio de 2021 y en paralelo los envió a la Fiscalía; esa causa penal fue archivada de forma definitiva el 13 de febrero de 2025 por el fiscal Enrique Rodríguez, que concluyó que no hubo irregularidad pasible de sanción penal. La Mañana informó que el integrante de la junta Jorge Castro (Partido Comunista) renunció tras votar el informe —su partido calificó ese voto como un error— y que el senador Jorge Gandini anunció que convocaría una Comisión General del Senado para pedir explicaciones al ministro de Industria y al presidente de Antel. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores.',
      porQueImporta: 'Mientras las contrataciones estuvieron reservadas, ni el Parlamento, ni el Tribunal de Cuentas, ni la prensa, ni cualquier vecino pudieron ver a quién se le compró, por cuánto y con qué procedimiento. La reserva no encareció la obra por sí sola, pero impidió durante años el control que habría permitido discutir su precio a tiempo.',
      caveat: 'Los procedimientos declarados reservados no se publican en el portal de compras estatales mientras dura la reserva, por lo que el cruce con datos abiertos puede mostrar sólo una parte de las contrataciones del proyecto. El dictamen de la JUTEP es administrativo y no declara responsabilidad penal de nadie; la causa judicial derivada terminó archivada.',
    },
    en: {
      title: 'Antel Arena records were classified as reserved for ten years',
      dek: 'Antel classified the complex\'s contracting as reserved for ten years. In 2021 the public ethics board, working from an audit Antel itself commissioned, ruled this breached the principles of good administration.',
      contexto: 'While the Antel Arena was being built, Antel\'s board classified the project\'s contracting information as reserved for ten years. According to the company\'s official statement, on 23 July 2020 the board chaired by Gabriel Gurméndez called an abbreviated tender to hire an audit of the project — seven bids were submitted and the advisory award commission recommended ECOVIS "on the lowest-price criterion" — and on 6 August 2020 it resolved to lift the classification and declassify all the information. With the audit in hand, the Public Transparency and Ethics Board (JUTEP) stepped in.',
      hallazgo: 'According to 180.com.uy, JUTEP identified three departures: failure to comply with the legal framework in the contracting, lack of transparency for having classified "all of the contracting" as reserved for ten years, and economic inefficiency over a cost overrun running from the US$40 million announced in 2013 — US$56.5 million in the 2015 business plan — to the US$119.7 million the audit produced. Subrayado published the opinion released by Antel itself: the board held that "good administration, both in financial management and in the use of suitable procedures to achieve the ends, was absent from this project", and that a breach of principles and standards of conduct had been found which "may constitute an administrative offence, without prejudice to any political, civil and criminal liability of the officials involved". JUTEP clarified that it worked from the information in the audit Antel requested, not from its own investigation. Carolina Cosse called the report a "pseudo-audit" that contributed nothing, according to La Mañana.',
      statusNote: 'JUTEP\'s opinion became known on 21 September 2021 and Antel published it. According to 180.com.uy, Antel had sent the ECOVIS audit results to JUTEP on 14 June 2021 and at the same time sent them to the Prosecutor\'s Office; that criminal case was definitively shelved on 13 February 2025 by prosecutor Enrique Rodríguez, who concluded there was no irregularity liable to criminal sanction. La Mañana reported that board member Jorge Castro (Communist Party) resigned after voting for the report — his party called that vote a mistake — and that senator Jorge Gandini announced he would convene a General Senate Committee to ask the Industry Minister and Antel\'s president for explanations. As of this file\'s closing (August 2026) there are no later developments.',
      porQueImporta: 'While the contracts were classified, neither Parliament, nor the Court of Audit, nor the press, nor any citizen could see who was hired, for how much and under which procedure. Secrecy alone did not make the work more expensive, but for years it blocked the scrutiny that would have allowed its price to be debated in time.',
      caveat: 'Procedures declared reserved are not published in the state procurement portal while the classification lasts, so a cross-reference with open data may show only part of the project\'s contracting. JUTEP\'s opinion is administrative and declares no one criminally liable; the resulting court case ended shelved.',
    },
  },
  {
    slug: 'antel-arena-fideicomiso-conafin-afisa',
    emoji: '💰',
    theme: 'telecomunicaciones',
    period: '2015-2018',
    statusKind: 'gestion',
    status: 'terminado',
    amountReported: 'US$ 58 millones de tope de endeudamiento autorizado por el Poder Ejecutivo para el fideicomiso',
    organisms: ['ANTEL', 'Corporación Nacional para el Desarrollo'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'Presidencia de la República (gub.uy)', title: 'Poder Ejecutivo aprobó fideicomiso de 58 millones de dólares para obras del Antel', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/poder-ejecutivo-aprobo-fideicomiso-58-millones-dolares-para-obras-del-antel', date: '2015-11-10' },
      { outlet: 'Subrayado', title: 'Aprueban fideicomiso de U$S 58 millones para Antel Arena', url: 'https://www.subrayado.com.uy/aprueban-fideicomiso-us-58-millones-antel-arena-n50338', date: '2015-11-10' },
      { outlet: 'Corporación Nacional para el Desarrollo', title: 'Fideicomiso Antel Arena', url: 'https://www.cnd.org.uy/noticias/fideicomiso-antel-arena', date: '2015-11' },
      { outlet: 'Subrayado', title: 'Antel Arena costó más de 90 millones de dólares; 8 millones más de lo declarado por Cosse', url: 'https://www.subrayado.com.uy/antel-arena-costo-mas-90-millones-dolares-8-millones-mas-lo-declarado-cosse-n524702', date: '2019-01-24' },
      { outlet: 'La Mañana', title: 'Múltiples repercusiones tras informe de Jutep sobre Antel Arena', url: 'https://www.xn--lamaana-7za.uy/politica/multiples-repercusiones-tras-informe-de-jutep-sobre-antel-arena/', date: '2021-09-29' },
    ],
    es: {
      title: 'El fideicomiso de US$ 58 millones que financió el Antel Arena',
      dek: 'El Poder Ejecutivo autorizó en 2015 a Antel a endeudarse por hasta US$ 58 millones mediante un fideicomiso administrado por Conafin Afisa para terminar el complejo.',
      contexto: 'La obra del Antel Arena estuvo suspendida desde junio de 2015: según Subrayado, «la obra fue suspendida en junio por el presidente Vázquez luego que evaluara como prioritarias otras obras para mejorar la calidad del agua en la cuenca del río Santa Lucía». Para reactivarla, el Poder Ejecutivo autorizó el 10 de noviembre de 2015 a Antel a constituir un fideicomiso de administración por hasta US$ 58 millones. Según la Corporación Nacional para el Desarrollo, el 4 de noviembre de 2015 se firmó el Fideicomiso de Administración para el Financiamiento de la Obra del Complejo Multifuncional Antel Arena, con CONAFIN AFISA como fiduciario, encargado de buscar financiamiento en la plaza bancaria local y en organismos multilaterales, con la obra retomándose en enero de 2016.',
      hallazgo: 'Según la comunicación de Presidencia, el mecanismo permitía a Antel endeudarse por hasta US$ 58 millones a un plazo de hasta ocho años, con dos años de gracia y pagos de intereses a partir de fines de enero de 2018, cuando se esperaba que la obra estuviera terminada. En esa misma nota, el presidente de Antel Andrés Tolosa estimó que «la obra implicará unos 52 millones de dólares, más impuestos, impuesto al valor agregado y leyes sociales, lo que se estima en un total de 67 millones de dólares». La CND detalló que el objeto del fideicomiso era «financiar los contratos de obra para la construcción del mencionado complejo». La auditoría que Antel encargó años después, reseñada por La Mañana, computó un costo total del orden de US$ 119,7 millones y unos US$ 48 millones que restaban pagar al momento del informe.',
      statusNote: 'El complejo se inauguró el 12 de noviembre de 2018, según Subrayado. La autorización de 2015 preveía el repago del fideicomiso a lo largo de hasta ocho años desde enero de 2018. Al cierre de esta ficha (agosto de 2026) no constan comunicaciones públicas posteriores sobre la cancelación del fideicomiso.',
      porQueImporta: 'Un fideicomiso permite ejecutar una obra sin que el gasto aparezca como una compra corriente del organismo ni pase por el presupuesto discutido en el Parlamento. Es una herramienta legal y usada por varios organismos, pero cambia dónde hay que mirar para saber cuánto se gastó y a quién se le pagó.',
      caveat: 'El gasto ejecutado por fideicomisos no se publica en el buscador de compras estatales: lo administra el fiduciario. El cruce con datos abiertos sólo alcanza las compras que ANTEL registró a su propio nombre. La constitución del fideicomiso fue autorizada por el Poder Ejecutivo y no está cuestionada judicialmente.',
    },
    en: {
      title: 'The US$58 million trust that financed the Antel Arena',
      dek: 'In 2015 the Executive authorised Antel to borrow up to US$58 million through a trust managed by Conafin Afisa in order to finish the complex.',
      contexto: 'Work on the Antel Arena had been suspended since June 2015: according to Subrayado, "the work was suspended in June by president Vázquez after he judged other works to improve water quality in the Santa Lucía river basin to be a priority". To restart it, on 10 November 2015 the Executive authorised Antel to set up an administration trust of up to US$58 million. According to the National Development Corporation, the Administration Trust for the Financing of the Antel Arena Multipurpose Complex was signed on 4 November 2015, with CONAFIN AFISA as trustee, tasked with sourcing financing in the local banking market and from multilateral bodies, with construction resuming in January 2016.',
      hallazgo: 'According to the Presidency\'s statement, the mechanism let Antel borrow up to US$58 million over up to eight years, with two years\' grace and interest payments starting in late January 2018, when the work was expected to be finished. In that same piece, Antel president Andrés Tolosa estimated that "the work will involve some 52 million dollars, plus taxes, VAT and social charges, which is estimated at a total of 67 million dollars". The CND stated the trust\'s purpose was "to finance the construction contracts for the said complex". The audit Antel commissioned years later, summarised by La Mañana, put the total cost at around US$119.7 million, with some US$48 million still to be paid at the time of the report.',
      statusNote: 'The complex opened on 12 November 2018, according to Subrayado. The 2015 authorisation provided for repayment of the trust over up to eight years from January 2018. As of this file\'s closing (August 2026) there are no later public statements on the trust\'s cancellation.',
      porQueImporta: 'A trust makes it possible to build without the spending showing up as an ordinary purchase by the agency or passing through the budget debated in Parliament. It is a legal tool used by several public bodies, but it changes where you have to look to find out how much was spent and who was paid.',
      caveat: 'Spending executed through trusts is not published in the state procurement search: the trustee administers it. The cross-reference with open data only reaches purchases ANTEL recorded under its own name. The trust was authorised by the Executive and is not the subject of any court challenge.',
    },
  },
  {
    slug: 'antel-arena-gestion-itc-tribunal-cuentas',
    emoji: '🎤',
    theme: 'telecomunicaciones',
    period: '2018-2026',
    statusKind: 'auditoria',
    status: 'auditoria',
    amountReported: 'US$ 3,7 millones de resultado negativo en 2024 y una pérdida proyectada de US$ 4,67 millones para 2025; canon base de US$ 96.000 anuales para ITC',
    organisms: ['ANTEL'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Administración Nacional de Telecomunicaciones',
      ],
      yearFrom: 2018,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Radio Monte Carlo', title: 'El Tribunal de Cuentas observó al contrato con ITC, para que empiece a gestionar el Antel Arena', url: 'https://www.radiomontecarlo.com.uy/2025/11/17/nacionales/el-tribunal-de-cuentas-observo-al-contrato-con-itc-para-que-empiece-a-gestionar-el-antel-arena/', date: '2025-11-17' },
      { outlet: 'Búsqueda', title: 'El contrato del Antel Arena con ITC activa un debate parlamentario sobre gestión y costos', url: 'https://www.busqueda.com.uy/informacion/el-contrato-del-antel-arena-itc-activa-un-debate-parlamentario-gestion-y-costos-n5408021', date: '2025-12-18' },
      { outlet: 'Montevideo Portal', title: 'Antel Arena revirtió los números y dio ganancia en los primeros meses de 2026: el detalle', url: 'https://www.montevideo.com.uy/Noticias/Antel-Arena-revirtio-los-numeros-y-dio-ganancia-en-los-primeros-meses-de-2026-el-detalle-uc965816', date: '2026-06-20' },
      { outlet: 'Búsqueda', title: 'Tras años de pérdidas, los resultados operativos medirán la nueva gestión del Antel Arena', url: 'https://www.busqueda.com.uy/vida-cultural/tras-anos-perdidas-los-resultados-operativos-mediran-la-nueva-gestion-del-antel-arena-n5414770', date: '2026-07-02' },
    ],
    es: {
      title: 'Antel Arena: el Tribunal de Cuentas observó el contrato con ITC',
      dek: 'Tras años de pérdidas y la salida del operador privado, Antel pasó la gestión a su filial ITC. El Tribunal de Cuentas observó el contrato y el directorio reiteró el gasto.',
      contexto: 'Desde su inauguración en 2018, el Antel Arena fue administrado por AEG Facilities Uruguay S.A. Según Búsqueda, ASM Global, casa matriz de la filial uruguaya, notificó que dejaría la gestión del complejo al vencimiento del contrato vigente, el 31 de diciembre de 2025. El 23 de octubre de 2025 el directorio de Antel aprobó el contrato para que la gestión pasara desde el 1º de enero de 2026 a ITC S.A., una empresa filial del propio ente, en lugar de llamar a la licitación internacional que, según el diputado Álvaro Dastugue, estaba pronta desde octubre de 2024. El contrato fija un canon base de US$ 96.000 anuales más incentivos y penalidades de hasta ±25% según indicadores, con un plazo inicial de dos años y renovaciones anuales automáticas por hasta tres años más. Los resultados del complejo venían en rojo: US$ 3,7 millones negativos en 2024 y una pérdida proyectada de US$ 4,67 millones para 2025.',
      hallazgo: 'Búsqueda informó que el 5 de noviembre de 2025 el Tribunal de Cuentas observó el contrato por apartarse del «principio de especialidad», es decir, por poner en duda que administrar un estadio esté dentro de los cometidos de una empresa de telecomunicaciones. Antel siguió adelante igual. Radio Monte Carlo consignó que el directorio resolvió reiterar el gasto y que la directora del ente por la oposición, Laura Raffo, votó en contra y advirtió que muchos de estos casos «están en carácter reservado»; según Búsqueda, Raffo —directora por el Partido Nacional— calificó la decisión de «temeraria» e «irresponsable». Dastugue cuestionó que una filial sin antecedentes en la administración de grandes arenas pudiera mejorar el desempeño de un operador especializado. El presidente de Antel, Alejandro Paz, defendió el cambio: sostuvo que el «99,9% de los espectáculos que se producen en el Antel Arena son traídos por productores nacionales», lo que a su juicio vuelve innecesario el intermediario internacional.',
      statusNote: 'Los primeros datos bajo la nueva gestión, difundidos por Antel y publicados por Montevideo Portal el 20 de junio de 2026, muestran que entre enero y abril de 2026 el resultado operativo pasó de un déficit de US$ 203.080 a una ganancia de US$ 208.710, con ingresos de US$ 1.393.170 (44% más que en igual período de 2025) y un costo del proveedor de gerenciamiento que bajó de US$ 70.000 a US$ 32.000. Búsqueda dio cuenta de los mismos números el 2 de julio de 2026 y agregó que la venta de plateas premium creció 148% y que la meta es superar los 100 eventos en 2026; el vicepresidente de Antel, Pablo Álvarez, dijo que «estamos a seis meses de la nueva gestión de ITC. Entendemos que la decisión que se tomó está dando resultados positivos» y advirtió que hará falta un año completo para evaluar el cambio. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores.',
      porQueImporta: 'El déficit del Antel Arena lo cubre Antel, o sea la empresa de telecomunicaciones que además financia fibra y 5G y transfiere sus utilidades al Estado. Que el gestor haya cambiado sin licitación internacional y con observación del Tribunal de Cuentas define quién controla varios millones de dólares al año de eventos y servicios.',
      caveat: 'Se trata de un contrato entre Antel y una filial suya, y parte de los antecedentes fue declarada reservada según la directora Raffo: puede no aparecer como una compra ordinaria en el buscador de compras estatales. Una observación del Tribunal de Cuentas es un reparo de legalidad, no una condena ni una imputación.',
    },
    en: {
      title: 'Antel Arena: the Court of Audit flagged the ITC contract',
      dek: 'After years of losses and the private operator\'s exit, Antel handed management to its subsidiary ITC. The Court of Audit flagged the contract and the board reiterated the spending.',
      contexto: 'Since it opened in 2018, the Antel Arena was run by AEG Facilities Uruguay S.A. According to Búsqueda, ASM Global, the parent of the Uruguayan subsidiary, notified that it would cease managing the venue when the existing contract expired on 31 December 2025. On 23 October 2025 Antel\'s board approved the contract handing management from 1 January 2026 to ITC S.A., a subsidiary of Antel itself, instead of launching the international tender that, according to MP Álvaro Dastugue, had been ready since October 2024. The contract sets a base fee of US$96,000 a year plus incentives and penalties of up to ±25% against performance indicators, with an initial two-year term and automatic annual renewals for up to three more years. The venue\'s results were in the red: minus US$3.7 million in 2024 and a projected loss of US$4.67 million for 2025.',
      hallazgo: 'Búsqueda reported that on 5 November 2025 the Court of Audit flagged the contract for departing from the "principle of speciality" — that is, questioning whether running a stadium falls within a telecoms company\'s remit. Antel proceeded anyway. Radio Monte Carlo noted that the board resolved to reiterate the spending and that the opposition\'s board member, Laura Raffo, voted against and warned that many such cases "are classified as reserved"; according to Búsqueda, Raffo — the National Party\'s director — called the decision "reckless" and "irresponsible". Dastugue questioned whether a subsidiary with no record in managing large arenas could outperform a specialist operator. Antel president Alejandro Paz defended the change, arguing that "99.9% of the shows produced at the Antel Arena are brought in by national producers", which in his view makes the international middleman unnecessary.',
      statusNote: 'The first figures under the new management, released by Antel and published by Montevideo Portal on 20 June 2026, show that between January and April 2026 the operating result went from a US$203,080 deficit to a US$208,710 profit, with income of US$1,393,170 (44% more than in the same period of 2025) and a management-provider cost that fell from US$70,000 to US$32,000. Búsqueda reported the same figures on 2 July 2026 and added that premium seat sales grew 148% and that the target is to exceed 100 events in 2026; Antel vice-president Pablo Álvarez said "we are six months into ITC\'s new management. We understand the decision taken is producing positive results", and cautioned that a full year would be needed to assess the change. As of this file\'s closing (August 2026) there are no later developments.',
      porQueImporta: 'The Antel Arena\'s deficit is covered by Antel — the telecoms company that also funds fibre and 5G and transfers its profits to the State. That the operator changed without an international tender and over a Court of Audit objection determines who controls several million dollars a year in events and services.',
      caveat: 'This is a contract between Antel and one of its own subsidiaries, and part of the record was declared reserved according to board member Raffo: it may not appear as an ordinary purchase in the state procurement search. A Court of Audit observation is a legality objection, not a conviction or a charge.',
    },
  },
  {
    slug: 'licitaciones-fibra-optica-alerta-colusion',
    emoji: '🕸️',
    theme: 'telecomunicaciones',
    period: '2021-2024',
    statusKind: 'auditoria',
    status: 'investigacion',
    amountReported: '$ 1.797 millones pagados frente a $ 1.368 millones estimados (31,4% más), según Brecha',
    organisms: ['ANTEL'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Administración Nacional de Telecomunicaciones',
      ],
      yearFrom: 2021,
      yearTo: 2024,
    },
    sources: [
      { outlet: 'Brecha', title: 'El Tribunal de Cuentas alerta presunta colusión en licitaciones de ANTEL', url: 'https://brecha.com.uy/acuerdo-de-precios-el-tribunal-de-cuentas-alerta-presunta-colusion-en-licitaciones-de-antel/', date: '2022-05-20' },
      { outlet: 'la diaria', title: 'Autoridades de Antel analizarán presuntos “sobrecostos” en licitaciones para la instalación de fibra óptica', url: 'https://ladiaria.com.uy/politica/articulo/2021/11/autoridades-de-antel-analizaran-presuntos-sobrecostos-en-licitaciones-para-la-instalacion-de-fibra-optica/', date: '2021-11-19' },
      { outlet: 'Ministerio de Economía y Finanzas — Comisión de Promoción y Defensa de la Competencia', title: 'Resolución N° 215/024 — Asunto N° 2022-05-150-7 — Tribunal de Cuentas — ANTEL', url: 'https://www.gub.uy/ministerio-economia-finanzas/institucional/normativa/resolucion-n-215024-asunto-n-2022-05-150-7-tribunal-cuentas-antel', date: '2024-12-11' },
    ],
    es: {
      title: 'Siete licitaciones de fibra óptica y una alerta de presunta colusión',
      dek: 'El Tribunal de Cuentas advirtió que siete llamados de fibra óptica de Antel pudieron haberse repartido entre oferentes y los derivó a Defensa de la Competencia. Se pagó 31,4% más de lo estimado.',
      contexto: 'A fines de 2021 Antel adjudicó siete licitaciones públicas para la instalación, ampliación y sustitución de redes de fibra óptica al hogar en distintos puntos del país. Según Brecha, los llamados —identificados como P102378, P102379, P102390, P102391, P102392, P102393 y P102394— dividieron el trabajo en siete zonas geográficas, se publicitaron durante diez días y tuvieron el precio como único factor de evaluación, de modo que se adjudicaban a la oferta más barata recibida. La primera apertura fue el 16 de agosto de 2021. El directorio de Antel estaba presidido por Gabriel Gurméndez.',
      hallazgo: 'Brecha informó el 20 de mayo de 2022 que el Tribunal de Cuentas detectó la situación, señaló el riesgo de estar frente a una colusión —una concertación entre oferentes para repartirse los llamados— y remitió los antecedentes a la Comisión de Promoción y Defensa de la Competencia. El Tribunal apuntó a los artículos 4 y 4 bis de la ley de defensa de la competencia, que prohíben «concertar o imponer directa o indirectamente precios» y «establecer, concertar o coordinar las ofertas» en licitaciones. Según el mismo semanario, el costo estimado era de $ 1.368 millones y lo finalmente pagado fue de $ 1.797 millones, un 31,4% más; las ofertas ganadoras superaron sistemáticamente en más de 5% las estimaciones, lo que impedía pedir mejora de precios. Entre las empresas que participaron Brecha nombra a Montelecnor, Electrosistemas, Saceem, Ciemsa, CEI, SIE, Oritecno, Stiler, Gofinal, Río Golf y Clauger. Antes, el 19 de noviembre de 2021, la diaria había publicado que el director Daniel Larrosa (Frente Amplio) denunciaba «sobrecostos cercanos a los diez millones de dólares en cinco licitaciones adjudicadas recientemente para ampliar la red de fibra óptica», atribuidos a haber sustituido la subasta a la baja por la licitación. Ninguna empresa fue sancionada.',
      statusNote: 'La Comisión de Promoción y Defensa de la Competencia, del Ministerio de Economía y Finanzas, abrió una investigación de oficio por Resolución N° 71/022 del 3 de marzo de 2022 sobre la licitación pública P102394 de ANTEL, y por Resolución N° 215/024 del 11 de diciembre de 2024 resolvió «concluir la investigación de oficio dispuesta por Resolución N° 71/022». La resolución publicada no consigna sanciones contra ninguna de las empresas participantes. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores al 11 de diciembre de 2024.',
      porQueImporta: 'La fibra óptica al hogar es la red por la que hoy pasa casi todo: internet, teletrabajo, educación y salud a distancia. Cada peso pagado de más en su tendido es dinero que no se invierte en llegar a más hogares ni vuelve a Rentas Generales, y lo pone la misma empresa pública que cobra la factura mensual.',
      caveat: 'Participar en una licitación no implica infracción alguna: la investigación de la Comisión de Defensa de la Competencia se cerró sin sanciones publicadas y ninguna empresa fue sancionada. El cruce con datos abiertos muestra adjudicaciones y montos, no conductas de las empresas.',
    },
    en: {
      title: 'Seven fibre-optic tenders and an alert over suspected collusion',
      dek: 'The Court of Audit warned that seven Antel fibre-optic tenders may have been divided up among bidders and referred them to the competition authority. The amount paid was 31.4% above the estimate.',
      contexto: 'In late 2021 Antel awarded seven public tenders for the installation, extension and replacement of fibre-to-the-home networks across the country. According to Brecha, the tenders — identified as P102378, P102379, P102390, P102391, P102392, P102393 and P102394 — split the work into seven geographic zones, were advertised for ten days and used price as the sole evaluation criterion, so each went to the cheapest bid received. The first opening was on 16 August 2021. Antel\'s board was chaired by Gabriel Gurméndez.',
      hallazgo: 'Brecha reported on 20 May 2022 that the Court of Audit detected the situation, flagged the risk of collusion — an agreement among bidders to share out the tenders — and referred the file to the Competition Promotion and Defence Commission. The Court pointed to articles 4 and 4 bis of the competition law, which ban "agreeing or directly or indirectly imposing prices" and "setting, agreeing or coordinating bids" in tenders. According to the same weekly, the estimated cost was $1,368 million and the amount finally paid was $1,797 million, 31.4% more; winning bids consistently exceeded the estimates by more than 5%, which barred the agency from requesting improved prices. Among the participating firms Brecha names Montelecnor, Electrosistemas, Saceem, Ciemsa, CEI, SIE, Oritecno, Stiler, Gofinal, Río Golf and Clauger. Earlier, on 19 November 2021, la diaria had reported that board member Daniel Larrosa (Frente Amplio) alleged "cost overruns of close to ten million dollars in five tenders recently awarded to extend the fibre-optic network", which he attributed to replacing reverse auctions with ordinary tenders. No company was sanctioned.',
      statusNote: 'The Competition Promotion and Defence Commission, within the Ministry of Economy and Finance, opened an ex-officio investigation by Resolution No. 71/022 of 3 March 2022 into ANTEL\'s public tender P102394, and by Resolution No. 215/024 of 11 December 2024 resolved to "conclude the ex-officio investigation ordered by Resolution No. 71/022". The published resolution records no sanctions against any of the participating firms. As of this file\'s closing (August 2026) there are no developments after 11 December 2024.',
      porQueImporta: 'Fibre to the home is the network almost everything now runs on: internet, remote work, education and telemedicine. Every peso overpaid on laying it is money not invested in reaching more households or returned to the Treasury — and it is put up by the same public company that sends the monthly bill.',
      caveat: 'Bidding in a tender implies no wrongdoing: the competition authority\'s investigation closed with no published sanctions and no company was sanctioned. The open-data cross-reference shows awards and amounts, not company conduct.',
    },
  },
  {
    slug: 'vera-tv-inversion-no-recuperada',
    emoji: '📺',
    theme: 'telecomunicaciones',
    period: '2013-2025',
    statusKind: 'gestion',
    status: 'debate',
    amountReported: 'US$ 45,7 millones gastados entre 2013 y 2019 y US$ 19 millones recuperados entre 2015 y octubre de 2020, según datos de Antel',
    organisms: ['ANTEL'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Administración Nacional de Telecomunicaciones',
      ],
      yearFrom: 2013,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'El Observador', title: 'Antel gastó en Vera TV US$ 45 millones y recuperó US$ 19 millones desde 2013', url: 'https://www.elobservador.com.uy/nota/antel-gasto-en-vera-tv-us-45-millones-y-recupero-us-19-millones-desde-2013-202182720530', date: '2021-08-28' },
      { outlet: 'Radiomundo En Perspectiva', title: 'Antel dejará de comprar o producir contenidos para Vera TV, ya que “no es su giro” de negocio', url: 'https://enperspectiva.uy/en-perspectiva-programa/la-mesa/antel-dejara-comprar-producir-contenidos-vera-tv-ya-no-giro-negocio/', date: '2020-05-13' },
      { outlet: 'Montevideo Portal', title: 'Sindicato de Antel celebró la no renovación de contrato millonario con canales 4, 10 y 12', url: 'https://www.montevideo.com.uy/Noticias/Sindicato-de-Antel-celebro-la-no-renovacion-de-contrato-millonario-con-canales-4-10-y-12-uc926437', date: '2025-06-09' },
    ],
    es: {
      title: 'Vera TV: US$ 45,7 millones invertidos y US$ 19 millones recuperados',
      dek: 'Antel gastó US$ 45,7 millones en su plataforma de streaming y recuperó US$ 19 millones, según datos que el propio ente entregó por acceso a la información pública.',
      contexto: 'Vera TV fue la apuesta de Antel por el video bajo demanda: una plataforma con películas, series y transmisiones deportivas —entre ellas mundiales de fútbol— ofrecida a sus clientes. Según los datos que Antel entregó a El Observador, ocupó a 131 funcionarios propios y 74 contratados desde su creación. La discusión pública sobre si producir y comprar contenidos audiovisuales es parte del negocio de una empresa de telecomunicaciones acompañó al proyecto y se reactivó con cada cambio de directorio.',
      hallazgo: 'El Observador publicó el 28 de agosto de 2021, con datos que Antel entregó por un pedido de acceso a la información pública, que la empresa gastó US$ 45,7 millones en Vera TV entre 2013 y 2019 y recuperó US$ 19 millones entre 2015 y octubre de 2020, alrededor del 42% de lo invertido en el período medido. El desglose de lo recuperado: US$ 250.000 por publicidad, US$ 350.000 por venta de contenidos, US$ 2,3 millones por servicios de plataforma y US$ 16,8 millones por tráfico de datos. Antes, el 13 de mayo de 2020, el ministro de Industria Omar Paganini había anunciado en Radiomundo En Perspectiva que Antel dejaría de comprar y producir contenidos porque no es su giro: «cuando las cosas son gratis alguien las paga», dijo sobre los mundiales que se vieron sin costo en la plataforma. El PIT-CNT rechazó esa decisión y sostuvo que la producción de contenidos era el camino que debía seguir el operador; Paganini calificó esa posición de «muy discutible».',
      statusNote: 'En junio de 2025 el directorio de Antel resolvió no renovar el contrato con los canales privados que alimentaban la plataforma, vencido el 19 de mayo de 2025, según informó Montevideo Portal el 9 de junio de 2025. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores al 9 de junio de 2025 sobre el futuro de la plataforma.',
      porQueImporta: 'Los US$ 26,7 millones de diferencia entre lo gastado y lo recuperado salieron de la caja de la empresa telefónica del Estado, la misma que financia la red y transfiere utilidades a Rentas Generales. La discusión de fondo —si el Estado debe comprar películas y fútbol para ofrecerlos con el plan— sigue abierta y define en qué se usan esos recursos.',
      caveat: 'No hay auditoría con observaciones ni causa judicial sobre Vera TV: es una discusión de gestión y de giro de negocio. Además, buena parte de los contenidos se compra por contratos internacionales de derechos, que no siempre se registran como compras nacionales en el portal de compras estatales.',
    },
    en: {
      title: 'Vera TV: US$45.7 million invested, US$19 million recovered',
      dek: 'Antel spent US$45.7 million on its streaming platform and recovered US$19 million, according to figures the company itself released under a freedom-of-information request.',
      contexto: 'Vera TV was Antel\'s bet on video on demand: a platform with films, series and sports broadcasts — including football World Cups — offered to its customers. According to the data Antel gave El Observador, it employed 131 of its own staff and 74 contractors since its creation. The public argument over whether producing and buying audiovisual content belongs in a telecoms company\'s business followed the project and reignited with every change of board.',
      hallazgo: 'On 28 August 2021 El Observador published figures Antel released under a freedom-of-information request: the company spent US$45.7 million on Vera TV between 2013 and 2019 and recovered US$19 million between 2015 and October 2020, around 42% of what it invested over the measured period. The recovered amount breaks down as US$250,000 in advertising, US$350,000 in content sales, US$2.3 million in platform services and US$16.8 million in data traffic. Earlier, on 13 May 2020, Industry Minister Omar Paganini had announced on Radiomundo En Perspectiva that Antel would stop buying and producing content because it is not its line of business: "when things are free, someone pays for them", he said of the World Cups watched at no cost on the platform. The PIT-CNT union confederation rejected that decision, arguing content production was the path the operator should follow; Paganini called that position "highly debatable".',
      statusNote: 'In June 2025 Antel\'s board decided not to renew the contract with the private channels that fed the platform, which had expired on 19 May 2025, as Montevideo Portal reported on 9 June 2025. As of this file\'s closing (August 2026) there are no developments after 9 June 2025 regarding the platform\'s future.',
      porQueImporta: 'The US$26.7 million gap between what was spent and what was recovered came from the state telephone company\'s cash — the same company that funds the network and transfers profits to the Treasury. The underlying question — whether the State should buy films and football to offer with a phone plan — remains open and determines how those resources are used.',
      caveat: 'There is no audit with findings and no court case over Vera TV: this is a management and line-of-business debate. Also, much of the content is bought through international rights contracts, which are not always recorded as domestic purchases in the state procurement portal.',
    },
  },
  {
    slug: 'vera-tv-contratos-canales-privados',
    emoji: '📡',
    theme: 'telecomunicaciones',
    period: '2022-2025',
    statusKind: 'auditoria',
    status: 'terminado',
    amountReported: 'US$ 10,8 millones con IVA por tres años (US$ 9 millones sin IVA; US$ 83.334 mensuales más IVA a cada canal, unos US$ 1,2 millones anuales por señal)',
    organisms: ['ANTEL'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Administración Nacional de Telecomunicaciones',
      ],
      yearFrom: 2022,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'Montevideo Portal', title: 'Contrato de tres años de Antel y canales privados por US$ 10 millones es estudiado por TCR', url: 'https://www.montevideo.com.uy/Noticias/Contrato-de-tres-anos-de-Antel-y-canales-privados-por-US-10-millones-es-estudiado-por-TCR-uc824929', date: '2022-06-16' },
      { outlet: 'El Observador', title: 'Antel pagará más de US$ 1 millón por año a canales privados para que estén en Vera Tv', url: 'https://www.elobservador.com.uy/nota/antel-pagara-mas-de-un-millon-por-ano-a-canales-privados-para-que-esten-en-vera-tv-202261793251', date: '2022-06-17' },
      { outlet: 'Montevideo Portal', title: 'Sindicato de Antel celebró la no renovación de contrato millonario con canales 4, 10 y 12', url: 'https://www.montevideo.com.uy/Noticias/Sindicato-de-Antel-celebro-la-no-renovacion-de-contrato-millonario-con-canales-4-10-y-12-uc926437', date: '2025-06-09' },
    ],
    es: {
      title: 'Antel pagó a los canales 4, 10 y 12 para verse en Vera TV',
      dek: 'Un contrato de tres años por unos US$ 10,8 millones con IVA puso las señales de los canales privados en la plataforma de Antel, sólo en celulares, y fue declarado reservado.',
      contexto: 'El 19 de mayo de 2022 Antel firmó con Monte Carlo TV (canal 4), Saeta TV (canal 10) y Sociedad Televisora Larrañaga (Teledoce, canal 12) un contrato para incluir sus señales en vivo en su plataforma de streaming. El acuerdo, informado por Montevideo Portal y El Observador, preveía US$ 83.334 mensuales más IVA para cada canal: unos US$ 1,2 millones anuales por señal y unos US$ 10,8 millones con IVA en los tres años (US$ 9 millones sin IVA), con renovación automática salvo aviso con 20 días de anticipación. El directorio lo aprobó ad referéndum de la intervención preventiva de legalidad del Tribunal de Cuentas, y la información fue clasificada como reservada por el plazo del contrato y sus eventuales renovaciones.',
      hallazgo: 'Según Montevideo Portal (16 de junio de 2022), el Tribunal de Cuentas inició un análisis para determinar la legalidad de esos contratos. El Observador detalló al día siguiente las condiciones: Antel sólo podía transmitir las señales por celulares —«quedan expresamente excluidas los televisores, computadoras personales (PC) y laptops, así como cualquier dispositivo no autorizado (por ejemplo: Chromecast, Android TV o similares)»—; el contrato le aseguraba «el 80% de las transmisiones semanales de los canales y tres horas del prime time televisivo», con bloqueos (blackout) para los contenidos que los canales definieran no compartibles, y los canales debían aportar sin costo la señal del Mundial 2022. Incluía además una cláusula de exclusividad: los canales no podían comercializar sus señales a otros servicios de streaming en Uruguay y Antel no podía revenderlas a terceros ni permitir su descarga o almacenamiento.',
      statusNote: 'El contrato venció el 19 de mayo de 2025 y el directorio de Antel resolvió no renovarlo. Montevideo Portal informó el 9 de junio de 2025 que el Sindicato Único de Telecomunicaciones (Sutel) celebró la decisión; su presidente Gabriel Molina sostuvo que el acuerdo «desde el inicio, fue un pésimo negocio para Antel» y el sindicato señaló que beneficiaba a competidores de la empresa. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores al 9 de junio de 2025.',
      porQueImporta: 'Son unos US$ 10,8 millones de una empresa pública pagados para que canales abiertos —que ya se ven gratis con una antena— también se vieran en la app de Antel, y sólo en el celular. Es dinero de la misma caja que financia la fibra, el 5G y el aporte a Rentas Generales.',
      caveat: 'El contrato fue declarado reservado por su plazo y sus renovaciones, por lo que puede no aparecer con su detalle en el buscador de compras estatales. Las cifras citadas provienen de las notas periodísticas, no de un registro público de la compra, y no consta que el Tribunal de Cuentas haya publicado una conclusión de su análisis.',
    },
    en: {
      title: 'Antel paid channels 4, 10 and 12 to appear on Vera TV',
      dek: 'A three-year contract worth some US$10.8 million including VAT put the private channels\' signals on Antel\'s platform, on mobile phones only, and was classified as reserved.',
      contexto: 'On 19 May 2022 Antel signed a contract with Monte Carlo TV (channel 4), Saeta TV (channel 10) and Sociedad Televisora Larrañaga (Teledoce, channel 12) to carry their live signals on its streaming platform. The deal, reported by Montevideo Portal and El Observador, provided for US$83,334 a month plus VAT for each channel: some US$1.2 million a year per signal and around US$10.8 million including VAT over three years (US$9 million excluding VAT), with automatic renewal unless either party gave 20 days\' notice. The board approved it subject to the Court of Audit\'s preventive legality review, and the information was classified as reserved for the term of the contract and any renewals.',
      hallazgo: 'According to Montevideo Portal (16 June 2022), the Court of Audit opened a review to determine the legality of these contracts. El Observador detailed the terms the next day: Antel could only carry the signals on mobile phones — "televisions, personal computers (PCs) and laptops are expressly excluded, as is any unauthorised device (for example: Chromecast, Android TV or similar)"; the contract secured for Antel "80% of the channels\' weekly broadcasts and three hours of television prime time", with blackouts for content the channels deemed non-shareable, and the channels had to supply the 2022 World Cup signal at no cost. It also included an exclusivity clause: the channels could not sell their signals to other streaming services in Uruguay, and Antel could not resell them to third parties or allow downloading or storage.',
      statusNote: 'The contract expired on 19 May 2025 and Antel\'s board decided not to renew it. Montevideo Portal reported on 9 June 2025 that the telecoms union Sutel welcomed the decision; its president Gabriel Molina said the deal "was a terrible business for Antel from the start", and the union argued it benefited the company\'s competitors. As of this file\'s closing (August 2026) there are no developments after 9 June 2025.',
      porQueImporta: 'That is some US$10.8 million of public money paid so that free-to-air channels — already available with an aerial — could also be watched on Antel\'s app, and only on a phone. It comes from the same purse that funds fibre, 5G and the transfer to the Treasury.',
      caveat: 'The contract was classified as reserved for its term and renewals, so its detail may not appear in the state procurement search. The figures cited come from press reports, not from a public record of the purchase, and there is no record of the Court of Audit publishing a conclusion to its review.',
    },
  },
  {
    slug: 'publicidad-antel-gastos-y-reservas',
    emoji: '📣',
    theme: 'telecomunicaciones',
    period: '2005-2022',
    statusKind: 'debate',
    status: 'debate',
    amountReported: 'US$ 194 millones en publicidad entre 2005 y 2019, de los cuales US$ 91 millones entre 2010 y 2014',
    organisms: ['ANTEL'],
    feedCoverage: 'likely',
    query: {
      buyers: [
        'Administración Nacional de Telecomunicaciones',
      ],
      yearFrom: 2005,
      yearTo: 2022,
    },
    investigationPath: '/pauta',
    sources: [
      { outlet: 'El Observador', title: 'Cosse gastó en Antel US$ 90 millones en publicidad, casi el doble que otros gobiernos del FA', url: 'https://www.elobservador.com.uy/nota/cosse-gasto-en-antel-us-90-millones-en-publicidad-casi-el-doble-que-otros-periodos-del-fa-20209217200', date: '2020-09-03' },
      { outlet: 'Montevideo Portal', title: 'Cosse sobre gastos en publicidad y marketing: "Los montos siempre fueron públicos"', url: 'https://www.montevideo.com.uy/Noticias/Cosse-sobre-gastos-en-publicidad-y-marketing--Los-montos-siempre-fueron-publicos--uc763510', date: '2020-09-04' },
      { outlet: 'El Observador', title: 'Antel: tras decir que la transparencia es un mandato legal, Gurméndez declaró reservados gastos en publicidad', url: 'https://www.elobservador.com.uy/nota/antel-tras-decir-que-la-transparencia-es-un-mandato-legal-gurmendez-declaro-reservados-gastos-en-publicidad-2022421101220', date: '2022-04-21' },
    ],
    es: {
      title: 'US$ 194 millones en publicidad de Antel y una reserva reinstalada',
      dek: 'Antel gastó US$ 194 millones en publicidad entre 2005 y 2019, casi la mitad en el quinquenio de Carolina Cosse. En 2022 volvió a declarar reservados otros gastos.',
      contexto: 'Antel es uno de los mayores anunciantes del país: patrocina selecciones, festivales, espectáculos y campañas masivas. Durante años esos montos estuvieron clasificados como reservados. En septiembre de 2020 el directorio presidido por Gabriel Gurméndez resolvió levantar la confidencialidad de los gastos de promoción, auspicios y publicidad decretada por administraciones anteriores, y los entregó ante un pedido de acceso a la información pública. Según El Observador, las cifras fueron certificadas por PwC y convertidas a dólares con el tipo de cambio promedio de cada año.',
      hallazgo: 'El Observador publicó el 3 de septiembre de 2020 el detalle por período: US$ 48 millones entre 2005 y 2009 (presidencia de María Simon), US$ 91 millones entre 2010 y 2014 (presidencia de Carolina Cosse) y US$ 56 millones entre 2015 y 2019 (presidencia de Andrés Tolosa), un total de US$ 194 millones en quince años. Gurméndez afirmó que «se le había puesto una lápida a toda esta información y eso ha impedido un ejercicio de contralor ciudadano». Cosse respondió al día siguiente en Montevideo Portal: «Es una fake news porque lo que no están diciendo es que Antel con esa inversión en publicidad, que me extraña que lo califiquen como un gasto, generó mucho más dinero»; sostuvo que con ella Antel ganó «14 puntos de share de mercado» —cada punto, según su cálculo, unos nueve millones de dólares anuales— y que «los montos siempre fueron públicos», ya que la empresa publicaba estados contables auditados con el gasto de marketing y lo nuevo era la apertura de en qué se aplicó. En abril de 2022, según El Observador, la propia administración de Gurméndez declaró reservados la campaña por la portabilidad numérica y el contrato de patrocinio con la Asociación Uruguaya de Fútbol, alegando que difundirlos podía provocar «una pérdida de ventajas competitivas» o «dañar su proceso de producción» en un mercado en competencia.',
      statusNote: 'El levantamiento de la reserva se resolvió en 2020 y la nueva clasificación de gastos publicitarios se conoció el 21 de abril de 2022. No se trata de una causa judicial ni de una auditoría con conclusiones publicadas: es una discusión sobre cuánto y con qué visibilidad debe gastar en publicidad una empresa pública que compite con privados. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a la información del 21 de abril de 2022.',
      porQueImporta: 'US$ 194 millones equivalen a más de una obra del porte del Antel Arena, gastados en avisos, auspicios y patrocinios. Saber cuánto se paga y a quién permite discutir si esa inversión trae más clientes —como sostiene Cosse— o si es dinero que podría bajar la factura o volver a Rentas Generales.',
      caveat: 'Buena parte del gasto publicitario se canaliza por agencias y centrales de medios, de modo que el proveedor que aparece en el registro de compras no siempre es el medio o el evento que finalmente recibe el dinero. Los tramos declarados reservados no aparecen. No hay auditoría con observaciones ni causa judicial sobre este gasto.',
    },
    en: {
      title: 'US$194 million in Antel advertising and a reinstated secrecy',
      dek: 'Antel spent US$194 million on advertising between 2005 and 2019, nearly half of it during Carolina Cosse\'s five-year term. In 2022 it classified other spending again.',
      contexto: 'Antel is one of the country\'s biggest advertisers: it sponsors national teams, festivals, shows and mass campaigns. For years those amounts were classified as reserved. In September 2020 the board chaired by Gabriel Gurméndez lifted the confidentiality over promotion, sponsorship and advertising spending imposed by earlier administrations, and released the figures in response to a freedom-of-information request. According to El Observador, the figures were certified by PwC and converted to dollars at each year\'s average exchange rate.',
      hallazgo: 'On 3 September 2020 El Observador published the breakdown by period: US$48 million between 2005 and 2009 (under María Simon), US$91 million between 2010 and 2014 (under Carolina Cosse) and US$56 million between 2015 and 2019 (under Andrés Tolosa), a total of US$194 million over fifteen years. Gurméndez said "a tombstone had been placed over all this information and that has prevented any exercise of citizen oversight". Cosse replied the next day in Montevideo Portal: "This is fake news, because what they are not saying is that Antel, with that advertising investment — which I find odd they call an expense — generated far more money"; she said it won Antel "14 points of market share" — each point worth, by her calculation, some nine million dollars a year — and that "the amounts were always public", since the company published audited accounts including marketing spending and what was new was the breakdown of how it was applied. In April 2022, according to El Observador, Gurméndez\'s own administration classified as reserved the number-portability campaign and the sponsorship contract with the Uruguayan Football Association, arguing that disclosure could cause "a loss of competitive advantages" or "damage its production process" in a competitive market.',
      statusNote: 'The lifting of the classification was decided in 2020 and the new classification of advertising spending became known on 21 April 2022. This is neither a court case nor an audit with published conclusions: it is a debate over how much, and how visibly, a public company competing with private firms should spend on advertising. As of this file\'s closing (August 2026) there are no developments after the 21 April 2022 report.',
      porQueImporta: 'US$194 million is more than one Antel Arena, spent on ads, sponsorships and endorsements. Knowing how much is paid and to whom is what allows a debate over whether that investment brings in more customers — as Cosse argues — or whether it is money that could lower bills or return to the Treasury.',
      caveat: 'Much advertising spending is channelled through agencies and media buyers, so the supplier recorded in procurement data is not always the outlet or event that ultimately receives the money. The tranches declared reserved do not appear at all. There is no audit with findings and no court case over this spending.',
    },
  },
  {
    slug: 'subasta-espectro-5g-bloque-reservado-antel',
    emoji: '📶',
    theme: 'telecomunicaciones',
    period: '2023',
    statusKind: 'debate',
    status: 'debate',
    amountReported: 'US$ 28,1 millones pagó Claro y US$ 28,051 millones Movistar por un bloque de 100 MHz cada uno; Antel pagó el promedio de ambos',
    organisms: ['ANTEL'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Administración Nacional de Telecomunicaciones',
      ],
      yearFrom: 2023,
      yearTo: 2023,
    },
    sources: [
      { outlet: 'El Observador', title: 'Las advertencias de Movistar y Claro a la subasta del 5G por las “ventajas” de Antel', url: 'https://www.elobservador.com.uy/nota/las-advertencias-de-movistar-y-claro-a-la-subasta-del-5g-por-las-ventajas-de-antel-202321520560', date: '2023-02-16' },
      { outlet: 'Ámbito', title: 'Previsible subasta de la red 5G: Movistar y Claro se quedaron cada una con un bloque', url: 'https://www.ambito.com/uruguay/previsible-subasta-la-red-5g-movistar-y-claro-se-quedaron-cada-una-un-bloque-n5718401', date: '2023-05-09' },
      { outlet: 'Montevideo Portal', title: 'Movistar y Claro adquirieron bloques en la subasta del 5G por US$ 28 millones cada uno', url: 'https://www.montevideo.com.uy/Noticias/Movistar-y-Claro-adquirieron-bloques-en-la-subasta-del-5G-por-US-28-millones-cada-uno-uc853445', date: '2023-05-09' },
      { outlet: 'Ámbito', title: 'Subasta de la red 5G: las reacciones a las adquisiciones de Movistar y Claro', url: 'https://www.ambito.com/uruguay/subasta-la-red-5g-las-reacciones-las-adquisiciones-movistar-y-claro-n5718929', date: '2023-05-09' },
    ],
    es: {
      title: 'La subasta del 5G terminó sin puja y con un bloque reservado a Antel',
      dek: 'Movistar y Claro pagaron unos US$ 28 millones cada uno por sus bloques y Antel recibió el tercero al precio promedio, sin puja. Las privadas alegaron ventaja para el ente.',
      contexto: 'La Unidad Reguladora de Servicios de Comunicaciones (Ursec) subastó el 9 de mayo de 2023 tres bloques de 100 MHz en la banda de 3,5 GHz para desplegar redes 5G, con un precio base de US$ 28 millones por bloque, un máximo de un bloque por participante y una concesión de 25 años. Uno de los tres bloques estaba reservado para Antel: no competía en la puja y, según Montevideo Portal, «deberá pagar el promedio de los valores ofrecidos por las empresas privadas». Antes del llamado, Movistar, Claro y la asociación internacional GSMA presentaron observaciones al pliego.',
      hallazgo: 'El Observador informó el 16 de febrero de 2023 que Movistar, en un documento de quince páginas, calificó el lote reservado como un «privilegio discriminatorio en detrimento de los operadores privados» y pidió que la subasta fuera cerrada; Claro pidió bajar el precio base de US$ 28 a US$ 20 millones, alegó una «enorme ventaja anticompetitiva» para Antel y reclamó un plazo de despliegue de ocho meses igual para todos los operadores. La GSMA advirtió que el precio base era «elevado» para el estándar regional y que precios altos desalientan la inversión en redes. La Ursec respondió que la mayoría de las propuestas «exceden al pliego» y correspondían al decreto del Poder Ejecutivo. El resultado, según Ámbito y Montevideo Portal, fue Claro con US$ 28,1 millones por 3300-3400 MHz y Movistar con US$ 28,051 millones por 3700-3800 MHz, tras «siete rondas sin puja». El director de Ursec por el Frente Amplio Pablo Siris señaló que la subasta «terminó luego de 7 rondas sin puja» y Pedro Bordaberry la llamó «un remate sin puja».',
      statusNote: 'La subasta se cerró el 9 de mayo de 2023 tras siete rondas sin ofertas competitivas. El director nacional de Telecomunicaciones Guzmán Acosta y Lara destacó que el 5% de los US$ 56 millones recaudados de los privados va a educación, según Ámbito; la presidenta de la Ursec, Mercedes Aramendía, proyectó que el Estado recibiría en total más de US$ 84 millones. Al cierre de esta ficha (agosto de 2026) no constan resoluciones judiciales ni administrativas publicadas que hayan revertido el resultado de la subasta.',
      porQueImporta: 'El espectro es un bien público escaso: lo que el Estado cobra por él son ingresos que no salen del bolsillo del contribuyente, y lo que Antel paga sale de la caja de una empresa pública. Cómo se fija ese precio y si hay competencia real determina tanto la recaudación como el precio y la cobertura del 5G que después paga cada usuario.',
      caveat: 'El pago por el espectro es una concesión de la Ursec, no una compra estatal: no aparece en el buscador de compras. Lo que sí puede cruzarse son las compras de equipamiento y obra que Antel hace para desplegar la red. La reserva del bloque estaba prevista en el decreto del Poder Ejecutivo y no fue anulada por ninguna resolución conocida.',
    },
    en: {
      title: 'The 5G auction ended without bidding and with a block reserved for Antel',
      dek: 'Movistar and Claro paid around US$28 million each for their blocks and Antel got the third at the average price, with no bidding. The private firms alleged a state advantage.',
      contexto: 'The communications regulator Ursec auctioned three 100 MHz blocks in the 3.5 GHz band on 9 May 2023 to deploy 5G networks, at a base price of US$28 million per block, one block maximum per bidder and a 25-year concession. One of the three blocks was reserved for Antel: it did not compete in the bidding and, according to Montevideo Portal, "will have to pay the average of the prices offered by the private companies". Before the call, Movistar, Claro and the international association GSMA filed objections to the terms.',
      hallazgo: 'El Observador reported on 16 February 2023 that Movistar, in a fifteen-page document, called the reserved lot a "discriminatory privilege to the detriment of private operators" and asked for a closed auction; Claro asked to cut the base price from US$28 million to US$20 million, alleged an "enormous anti-competitive advantage" for Antel and demanded an eight-month deployment deadline applying equally to all operators. The GSMA warned that the base price was "high" by regional standards and that high prices discourage network investment. Ursec replied that most proposals "exceed the tender terms" and were matters for the Executive\'s decree. The outcome, according to Ámbito and Montevideo Portal, was Claro at US$28.1 million for 3300-3400 MHz and Movistar at US$28.051 million for 3700-3800 MHz, after "seven rounds without bidding". Ursec board member Pablo Siris (Frente Amplio) noted the auction "ended after 7 rounds with no bidding", and Pedro Bordaberry called it "an auction with no bids".',
      statusNote: 'The auction closed on 9 May 2023 after seven rounds with no competitive offers. National telecommunications director Guzmán Acosta y Lara highlighted that 5% of the US$56 million raised from the private operators goes to education, according to Ámbito; Ursec president Mercedes Aramendía projected the State would receive more than US$84 million in total. As of this file\'s closing (August 2026) there are no published court or administrative rulings that have reversed the auction\'s outcome.',
      porQueImporta: 'Spectrum is a scarce public asset: what the State charges for it is revenue that does not come out of taxpayers\' pockets, and what Antel pays comes from a public company\'s cash. How that price is set and whether there is real competition shapes both the revenue collected and the price and coverage of the 5G every user later pays for.',
      caveat: 'Payment for spectrum is a Ursec concession, not a state purchase: it does not appear in the procurement search. What can be cross-referenced are the equipment and works purchases Antel makes to deploy the network. The reserved block was provided for in the Executive\'s decree and was not annulled by any known ruling.',
    },
  },
  {
    slug: 'antel-utilidades-aporte-rentas-generales',
    emoji: '🏦',
    theme: 'telecomunicaciones',
    period: '2024-2025',
    statusKind: 'gestion',
    status: 'debate',
    amountReported: '$ 9.728,9 millones (unos US$ 249,2 millones) transferidos a Rentas Generales en 2025, sobre una utilidad de $ 9.710,5 millones (US$ 248,7 millones)',
    organisms: ['ANTEL'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Administración Nacional de Telecomunicaciones',
      ],
      yearFrom: 2024,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'El Observador', title: 'Antel registró utilidades por US$ 249 millones y volcó la totalidad de sus ganancias a la caja del Estado', url: 'https://www.elobservador.com.uy/economia-y-empresas/antel-registro-utilidades-us-249-millones-y-volco-la-totalidad-sus-ganancias-la-caja-del-estado-n6039194', date: '2026-03-31' },
      { outlet: 'Ámbito', title: 'Antel cerró 2025 con ganancias por US$ 248,7 millones y un aporte récord a Rentas Generales', url: 'https://www.ambito.com/uruguay/antel-cerro-2025-ganancias-us-2487-millones-y-un-aporte-record-rentas-generales-n6261742', date: '2026-03-31' },
      { outlet: 'la diaria', title: 'Antel recaudó 248 millones de dólares y volcó 249 a Rentas Generales en 2025', url: 'https://ladiaria.com.uy/politica/articulo/2026/3/antel-recaudo-248-millones-de-dolares-y-volco-249-a-rentas-generales-en-2025/', date: '2026-03-31' },
      { outlet: 'El Observador', title: 'Las ganancias millonarias de Antel en 2024: ¿qué dice el balance?', url: 'https://www.elobservador.com.uy/economia-y-empresas/los-ganancias-millonarias-antel-2024-que-dice-el-balance-n5994458', date: '2025-04-16' },
      { outlet: 'Montevideo Portal', title: 'Sutel: artículos de Rendición “debilitarán a Antel” y “beneficiarán a multinacionales”', url: 'https://www.montevideo.com.uy/Noticias/Sutel-articulos-de-Rendicion-debilitaran-a-Antel-y-beneficiaran-a-multinacionales--uc795251', date: '2021-08-16' },
    ],
    es: {
      title: 'Antel ganó US$ 249 millones en 2025 y los volcó enteros al Estado',
      dek: 'El ente transfirió a Rentas Generales $ 9.728,9 millones, algo más que toda su ganancia del año. El aporte récord convive con una caída de 34% en telefonía fija.',
      contexto: 'Antel es una de las empresas públicas más rentables del país y una fuente estable de recursos para el Tesoro: cada año transfiere parte de sus utilidades a Rentas Generales, el fondo con el que el Estado paga salud, educación, seguridad y vivienda. En 2024, según El Observador, ganó $ 9.676 millones (unos US$ 219,6 millones) y aportó US$ 171 millones. El balance de 2025, auditado por KPMG y publicado el 31 de marzo de 2026, mostró un cambio de escala en el aporte, en un año en que la empresa desplegaba 5G y fibra y desactivaba la vieja red de cobre.',
      hallazgo: 'El Observador, Ámbito y la diaria informaron el 31 de marzo de 2026 que Antel cerró 2025 con una utilidad de $ 9.710,5 millones (unos US$ 248,7 millones) y transfirió a Rentas Generales $ 9.728,9 millones (unos US$ 249,2 millones): algo más que la totalidad de lo ganado en el ejercicio, un aporte récord. Los ingresos operativos fueron de $ 46.482 millones, con un crecimiento nominal de 1,3%; los datos crecieron 10,5% y la telefonía móvil 2,8%, mientras la telefonía fija cayó 34% por la desactivación del cobre. El margen EBITDA fue de 33% (dos puntos más que en 2024) y la rentabilidad sobre patrimonio de 15,1%; la empresa redujo 29% su endeudamiento bancario y cerró con $ 2.784 millones en caja (unos US$ 71,3 millones). En 2021 el sindicato Sutel había advertido en Montevideo Portal que artículos de la Rendición de Cuentas «debilitarán a Antel» y «beneficiarán a multinacionales», y recordó que la empresa, «con fondos propios (que son de todos los uruguayos y aportando simultáneamente a rentas generales)», invirtió en fibra óptica, data center, cable submarino y 5G.',
      statusNote: 'El balance 2025, auditado por KPMG, se publicó el 31 de marzo de 2026. No hay auditoría con observaciones ni causa judicial asociada a este aporte: es una decisión de política presupuestal del gobierno de turno, discutida cada año en la Rendición de Cuentas. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores al 31 de marzo de 2026.',
      porQueImporta: 'Cada peso que Antel gira a Rentas Generales financia otras políticas, pero también es dinero que no queda en la empresa para invertir en red o para bajar tarifas. Transferir en un año algo más que toda la utilidad es una decisión sobre esa balanza, y quien la paga o la recibe es el mismo contribuyente que abona la factura.',
      caveat: 'Los aportes a Rentas Generales no son compras y no figuran en el buscador de compras estatales. Lo que sí puede cruzarse con datos abiertos son las compras de bienes y servicios que Antel hace para sostener la red. No hay irregularidad denunciada: la ficha documenta una decisión de política presupuestal.',
    },
    en: {
      title: 'Antel earned US$249 million in 2025 and handed it all to the State',
      dek: 'The company transferred $9,728.9 million to the Treasury, slightly more than its entire profit for the year. The record transfer sits alongside a 34% fall in fixed telephony.',
      contexto: 'Antel is one of the country\'s most profitable public companies and a steady source of funds for the Treasury: each year it transfers part of its profits to Rentas Generales, the pot the State uses to pay for health, education, security and housing. In 2024, according to El Observador, it earned $9,676 million (some US$219.6 million) and contributed US$171 million. The 2025 accounts, audited by KPMG and published on 31 March 2026, showed a step change in that transfer, in a year when the company was rolling out 5G and fibre and switching off the old copper network.',
      hallazgo: 'El Observador, Ámbito and la diaria reported on 31 March 2026 that Antel closed 2025 with a profit of $9,710.5 million (about US$248.7 million) and transferred $9,728.9 million (about US$249.2 million) to the Treasury: slightly more than everything it earned in the year, a record contribution. Operating income was $46,482 million, up 1.3% in nominal terms; data grew 10.5% and mobile telephony 2.8%, while fixed telephony fell 34% as copper was decommissioned. The EBITDA margin was 33% (two points above 2024) and return on equity 15.1%; the company cut bank debt by 29% and closed with $2,784 million in cash (some US$71.3 million). Back in 2021 the union Sutel had warned in Montevideo Portal that articles of the budget bill "will weaken Antel" and "benefit multinationals", recalling that the company, "with its own funds (which belong to all Uruguayans, while simultaneously contributing to general revenues)", invested in fibre optics, data centres, submarine cable and 5G.',
      statusNote: 'The 2025 accounts, audited by KPMG, were published on 31 March 2026. There is no audit with findings and no court case attached to this transfer: it is a budget-policy decision of the government of the day, debated each year in the Rendición de Cuentas budget bill. As of this file\'s closing (August 2026) there are no developments after 31 March 2026.',
      porQueImporta: 'Every peso Antel sends to the Treasury funds other policies, but it is also money that does not stay in the company to invest in the network or to cut tariffs. Transferring slightly more than its entire profit in one year is a decision about that trade-off, and the person paying or receiving is the same taxpayer who pays the bill.',
      caveat: 'Transfers to the Treasury are not purchases and do not appear in the state procurement search. What can be cross-referenced with open data are the goods and services Antel buys to run the network. No irregularity has been alleged: this file documents a budget-policy decision.',
    },
  },
]
