import type { CasoDef } from '../types'

/**
 * transporte — 10 dossiers, 7 of them with a live cross-reference.
 *
 * Every source URL was fetched and every query was resolved against the live
 * collection before this file was committed (scripts/verify-casos.ts re-checks
 * both). A caso with no `query` is not a gap in the research: its money does
 * not travel through the Compras Estatales feed at all, which `feedCoverage`
 * records and the page states outright.
 */
export const CASOS_TRANSPORTE: CasoDef[] = [
  {
    slug: 'fideicomiso-boleto-honorarios-fiduciaria',
    emoji: '🎫',
    theme: 'transporte',
    period: '2006-2025',
    statusKind: 'auditoria',
    status: 'auditoria',
    amountReported: 'Honorario mínimo mensual de US$ 30.500 pagado a la fiduciaria CONAFIN AFISA, según la auditoría del Tribunal de Cuentas citada por El Observador (18/2/2025); el mismo informe consigna que en ningún mes se pagó ese mínimo porque los importes siempre lo superaron',
    organisms: ['Ministerio de Transporte y Obras Públicas', 'Ministerio de Economía y Finanzas', 'Corporación Nacional para el Desarrollo'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Ministerio de Transporte y Obras Públicas',
        'Ministerio de Economía y Finanzas',
      ],
      yearFrom: 2006,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'El Observador', title: 'Fideicomiso del boleto: Conafin Afisa recibió más dinero por honorarios que lo que recibieron las empresas de transporte', url: 'https://www.elobservador.com.uy/fideicomiso-del-boleto-conafin-afisa-recibio-mas-dinero-honorarios-que-lo-que-recibieron-las-empresas-transporte-n5985552', date: '2025-02-18' },
      { outlet: 'IMPO / Poder Ejecutivo', title: 'Decreto N° 143/024 — Fideicomiso para la Movilidad Sostenible', url: 'https://www.impo.com.uy/bases/decretos/143-2024', date: '2024-05-15' },
      { outlet: 'Corporación Nacional para el Desarrollo', title: 'Fideicomiso del Boleto — sitio oficial de declaraciones y pagos', url: 'https://fb.cnd.org.uy/index.php?option=com_content&task=view&id=8&Itemid=8' },
    ],
    es: {
      title: 'El fideicomiso del boleto y los honorarios de su fiduciaria',
      dek: 'El Tribunal de Cuentas auditó el fondo que abarata el gasoil del transporte y concluyó que el 91,4% de las empresas beneficiarias recibió por año menos que la fiduciaria.',
      contexto: 'El Fideicomiso de Administración del Boleto (FAB) canaliza recursos que abaratan el gasoil de las empresas de transporte colectivo de pasajeros; el sitio oficial del propio fideicomiso remite al Decreto 347/006, de 2006, como marco del beneficio. Se financia con un sobreprecio cobrado por cada litro de gasoil vendido, y las empresas deben declarar por internet, dentro de los primeros cinco días hábiles de cada mes, su consumo y kilometraje del mes anterior; con esas declaraciones la fiduciaria ordena los pagos. Según El Observador, esa fiduciaria es CONAFIN AFISA, del grupo de la Corporación Nacional para el Desarrollo. En mayo de 2024 el Decreto 143/024 reglamentó el Fideicomiso para la Movilidad Sostenible (FiMS) —cuya creación había sido autorizada por los artículos 584 a 586 de la Ley 20.212—, dispuso que los bienes, créditos, derechos, recursos y obligaciones del FAB pasaran a su patrimonio y fijó en su artículo 12 una recaudación de $ 4,984 por litro de gasoil comercializado por ANCAP.',
      hallazgo: 'Según El Observador (18 de febrero de 2025), una auditoría del Tribunal de Cuentas sobre el FAB concluyó que el 91,4% de los beneficiarios —empresas de transporte colectivo de pasajeros— percibió un monto anual inferior al que recibió CONAFIN AFISA por honorarios de administración, y que ese importe anual la ubica en el puesto 11 entre los 129 beneficiarios del fideicomiso. El mismo informe consigna que el mínimo mensual de honorarios pagados fue de US$ 30.500, pero que "se pudo determinar que en ningún mes se pagó el mínimo", sino que "los importes siempre superaron esa cifra". El Tribunal señaló además que el FAB paga los honorarios más altos en comparación con otros fideicomisos, quedando sólo por debajo de lo que abona el del SODRE, y que la tarea consiste en realizar los pagos determinados automáticamente por el sistema informático, cargado previamente por los beneficiarios y el Ministerio de Transporte, sin verificación de los importes declarados. El Observador informó también que el sobreprecio del gasoil bajó de $ 5 a $ 3 por litro.',
      statusNote: 'El Decreto 143/024, de mayo de 2024, dispuso el traspaso de los bienes y obligaciones del FAB al Fideicomiso para la Movilidad Sostenible, que mantiene la estructura fiduciaria como administradora del subsidio al combustible. La auditoría del Tribunal de Cuentas fue difundida por El Observador el 18 de febrero de 2025; ese artículo no incluye respuesta de CONAFIN AFISA ni de la Corporación Nacional para el Desarrollo. Al cierre de esta ficha (agosto de 2026) no constan en las fuentes consultadas novedades posteriores a esa fecha sobre descargos de la fiduciaria ni sobre cambios en el esquema de honorarios.',
      porQueImporta: 'El sobreprecio del gasoil que financia el fideicomiso lo paga cualquiera que carga combustible, y su destino declarado es abaratar el boleto. Cuánto de ese dinero llega a la operación del transporte y cuánto queda en la administración del fondo es, por lo tanto, una pregunta directa sobre el precio que paga el pasajero y sobre el costo del combustible para el resto.',
      caveat: 'Los fideicomisos no se ejecutan por compras estatales licitadas, así que los honorarios de la fiduciaria no aparecen como contratos en los datos abiertos de compras públicas. El cruce sólo puede mostrar compras de los organismos involucrados, no los flujos internos del fondo.',
    },
    en: {
      title: 'The bus-fare trust and its trustee\'s fees',
      dek: 'The Court of Auditors audited the fund that lowers diesel costs for bus companies and concluded that 91.4% of the beneficiary firms received less per year than the trustee.',
      contexto: 'The Fideicomiso de Administración del Boleto (FAB) channels resources that lower the cost of diesel for public passenger transport companies; the trust\'s own official site points to Decree 347/006, of 2006, as the framework for the benefit. It is funded by a surcharge on every litre of diesel sold, and companies must declare online, within the first five working days of each month, their consumption and mileage for the previous month; the trustee orders payments on the basis of those declarations. According to El Observador, that trustee is CONAFIN AFISA, part of the Corporación Nacional para el Desarrollo group. In May 2024 Decree 143/024 set out the operating framework for the Sustainable Mobility Trust (FiMS) — whose creation had been authorised by articles 584 to 586 of Law 20.212 — provided that the FAB\'s assets, credits, rights, resources and obligations pass into its patrimony, and set in its article 12 a collection of $4.984 per litre of diesel sold by ANCAP.',
      hallazgo: 'According to El Observador (18 February 2025), a Court of Auditors audit of the FAB concluded that 91.4% of the beneficiaries — public passenger transport companies — received a lower annual amount than CONAFIN AFISA received in administration fees, and that this annual amount ranks the trustee 11th among the trust\'s 129 beneficiaries. The same report notes that the minimum monthly fee paid was US$30,500, but that "it could be determined that in no month was the minimum paid", and that "the amounts always exceeded that figure". The Court also stated that the FAB pays the highest fees compared with other trusts, second only to what the SODRE trust pays, and that the task consists of making payments determined automatically by the computer system, loaded in advance by the beneficiaries and the transport ministry, without verification of the declared amounts. El Observador also reported that the diesel surcharge fell from $5 to $3 per litre.',
      statusNote: 'Decree 143/024, of May 2024, provided for the transfer of the FAB\'s assets and obligations to the Sustainable Mobility Trust, which keeps the trustee structure as administrator of the fuel subsidy. The Court of Auditors audit was reported by El Observador on 18 February 2025; that article includes no response from CONAFIN AFISA or from the Corporación Nacional para el Desarrollo. As of this file\'s closing (August 2026), the sources consulted show no developments after that date regarding the trustee\'s reply or changes to the fee scheme.',
      porQueImporta: 'The diesel surcharge that funds the trust is paid by anyone who fills a tank, and its stated purpose is to make the bus fare cheaper. How much of that money reaches transport operations and how much stays in administering the fund is therefore a direct question about the price passengers pay and about fuel costs for everyone else.',
      caveat: 'Trusts are not executed through tendered state purchases, so the trustee\'s fees do not appear as contracts in the open procurement data. The cross-reference can only show purchases by the organisations involved, not the fund\'s internal flows.',
    },
  },
  {
    slug: 'subsidio-al-boleto-montevideo',
    emoji: '🚌',
    theme: 'transporte',
    period: '2019-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'Unos US$ 120 millones anuales en subsidios al transporte de Montevideo entre gobierno nacional e Intendencia (El Observador, 14/7/2025)',
    organisms: ['Intendencia de Montevideo', 'Ministerio de Transporte y Obras Públicas'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Intendencia de Montevideo',
        'Ministerio de Transporte y Obras Públicas',
      ],
      search: 'transporte',
      yearFrom: 2019,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'El Observador', title: 'Boleto de ómnibus en Montevideo: el subsidio "altísimo" según el exintendente y el precio que Bergara no tiene "sobre la mesa" bajar', url: 'https://www.elobservador.com.uy/nacional/el-boleto-omnibus-montevideo-subsidios-altisimos-y-un-precio-que-bergara-no-tiene-sobre-la-mesa-bajar-n6008110', date: '2025-07-14' },
      { outlet: 'El Observador', title: 'Reducción de horas extra y postergación del pago del subsidio al boleto: las ocho medidas de la IM para el "ordenamiento financiero"', url: 'https://www.elobservador.com.uy/nacional/reduccion-horas-extra-y-postergacion-del-pago-del-subsidio-al-boleto-las-ocho-medidas-la-im-del-ordenamiento-financiero-n6016874', date: '2025-09-12' },
      { outlet: 'Intendencia de Montevideo', title: 'Medidas de ordenamiento financiero y eficiencia en la gestión', url: 'https://montevideo.gub.uy/noticias/medidas-de-ordenamiento-financiero-y-eficiencia-en-la-gestion', date: '2025-09-12' },
      { outlet: 'la diaria', title: 'Empresas de la Cámara del Transporte Metropolitano esperan recibir un adelanto mientras el gobierno crea un fideicomiso financiero', url: 'https://ladiaria.com.uy/trabajo/articulo/2024/4/empresas-de-la-camara-del-transporte-metropolitano-esperan-recibir-un-adelanto-mientras-el-gobierno-crea-un-fideicomiso-financiero/', date: '2024-04-24' },
    ],
    es: {
      title: 'Cuánto subsidia el Estado cada boleto en Montevideo',
      dek: 'Entre gobierno nacional e Intendencia las empresas reciben unos US$ 120 millones al año; el subsidio pasó de cubrir 35% del sistema en 2019 a 42% en 2023.',
      contexto: 'El boleto de Montevideo no se paga sólo con el dinero del pasajero. El sistema combina lo que recauda la venta de boletos con transferencias de la Intendencia de Montevideo y del gobierno nacional, más la devolución del sobreprecio del gasoil. En julio de 2025 el boleto común costaba $ 61 en efectivo y $ 50 con tarjeta STM, y el de dos horas $ 92, según El Observador. La discusión sobre cuánto debe subsidiarse y quién lo paga volvió al centro con el cambio de administración departamental: el exintendente Mauricio Zunino calificó el nivel de subsidio de "altísimo", y el intendente Mario Bergara dijo que bajar el precio del boleto no está "sobre la mesa", aunque señaló que a mucha gente el precio le puede parecer caro.',
      hallazgo: 'Según El Observador (14 de julio de 2025), entre la Intendencia de Montevideo y el gobierno nacional las empresas de transporte reciben del orden de US$ 120 millones por año en subsidios, y la Intendencia aporta entre US$ 55 y US$ 60 millones anuales. El mismo artículo desglosa 2023: US$ 185 millones por venta de boletos, US$ 88 millones del gobierno nacional y US$ 47 millones de la Intendencia. La proporción se movió: en 2019 el boleto cubría 65% del sistema y los subsidios 35%; en 2023 el boleto cubrió 58% y los subsidios 42%. El peso de ese gasto quedó expuesto en setiembre de 2025, cuando la Intendencia anunció ocho medidas de "ordenamiento financiero" para el período de octubre de 2025 a marzo de 2026 que incluyen, según el texto oficial, la "postergación de un 10% del pago del subsidio al boleto a las empresas del transporte colectivo" y una "reducción en el entorno de un 10% de los contratos con empresas y proveedores de mayor porte", en acuerdo de partes.',
      statusNote: 'Las ocho medidas de ordenamiento financiero anunciadas por el intendente Mario Bergara el 12 de setiembre de 2025 rigen entre octubre de 2025 y marzo de 2026 e incluyen la postergación parcial del pago del subsidio al boleto a las empresas de transporte colectivo. En julio de 2025 Bergara había dicho que bajar el precio del boleto no estaba sobre la mesa. Al cierre de esta ficha (agosto de 2026) no constan en las fuentes consultadas novedades posteriores a setiembre de 2025 sobre el resultado de esas medidas ni sobre su efecto en el servicio.',
      porQueImporta: 'Cada viaje en ómnibus en Montevideo se paga dos veces: en la tarjeta y en los impuestos. Saber cuánto pone el Estado por boleto, y de qué bolsillo sale, es lo que permite discutir si el precio que se paga arriba del ómnibus es alto o bajo, y qué pasa con el servicio si ese aporte se posterga o se recorta.',
      caveat: 'Los subsidios al boleto son transferencias presupuestales, no compras licitadas: no aparecen como contratos en los datos abiertos de compras públicas. El cruce puede mostrar otras compras de la Intendencia y del MTOP vinculadas al transporte, no el monto del subsidio.',
    },
    en: {
      title: 'How much the state subsidises each bus fare in Montevideo',
      dek: 'Between the national government and the city, bus companies receive some US$120 million a year; subsidies went from covering 35% of the system in 2019 to 42% in 2023.',
      contexto: 'A Montevideo bus fare is not paid with the passenger\'s money alone. The system combines ticket revenue with transfers from the Intendencia de Montevideo and the national government, plus the diesel surcharge rebate. In July 2025 the standard fare cost $61 in cash and $50 with the STM card, and the two-hour ticket $92, according to El Observador. The debate over how much should be subsidised, and by whom, returned to the fore with the change of city administration: former mayor Mauricio Zunino called the subsidy level "very high", and mayor Mario Bergara said lowering the fare is not "on the table", though he noted the price may seem expensive to many people.',
      hallazgo: 'According to El Observador (14 July 2025), between the Intendencia de Montevideo and the national government, transport companies receive on the order of US$120 million a year in subsidies, with the city contributing between US$55 and US$60 million annually. The same article breaks down 2023: US$185 million from ticket sales, US$88 million from the national government and US$47 million from the city. The proportions shifted: in 2019 fares covered 65% of the system and subsidies 35%; in 2023 fares covered 58% and subsidies 42%. The weight of that spending became visible in September 2025, when the city announced eight "financial ordering" measures for October 2025 to March 2026 which include, per the official text, the "postponement of 10% of the fare-subsidy payment to the collective transport companies" and a "reduction of around 10% of contracts with larger firms and suppliers", by agreement of the parties.',
      statusNote: 'The eight financial-ordering measures announced by mayor Mario Bergara on 12 September 2025 run from October 2025 to March 2026 and include partially postponing the fare subsidy paid to bus companies. In July 2025 Bergara had said lowering the fare was not on the table. As of this file\'s closing (August 2026), the sources consulted show no developments after September 2025 on the outcome of those measures or their effect on service.',
      porQueImporta: 'Every bus trip in Montevideo is paid for twice: on the card and in taxes. Knowing how much the state puts in per fare, and out of which pocket, is what makes it possible to discuss whether the price paid on board is high or low, and what happens to service when that contribution is deferred or cut.',
      caveat: 'Fare subsidies are budget transfers, not tendered purchases: they do not appear as contracts in the open procurement data. The cross-reference can show other transport-related purchases by the city and the transport ministry, but not the subsidy amount itself.',
    },
  },
  {
    slug: 'ferrocarril-central-sobrecostos-acuerdo',
    emoji: '🚆',
    theme: 'transporte',
    period: '2023-2025',
    statusKind: 'gestion',
    status: 'sobrecosto',
    amountReported: 'Acuerdo por US$ 144 millones informado por la OPP el 19/5/2025; presupuesto elevado de US$ 2.300 a US$ 2.982 millones según Alfredo Asti citado por Búsqueda (6/3/2024)',
    organisms: ['Ministerio de Transporte y Obras Públicas', 'Administración de Ferrocarriles del Estado', 'Ministerio de Economía y Finanzas'],
    feedCoverage: 'partial',
    sources: [
      { outlet: 'la diaria', title: 'Ferrocarril Central: sobrecostos pueden ascender a 670 millones de dólares y desde el FA critican cambios al contrato', url: 'https://ladiaria.com.uy/politica/articulo/2024/3/ferrocarril-central-sobrecostos-pueden-ascender-a-670-millones-de-dolares-y-desde-el-fa-critican-cambios-al-contrato/', date: '2024-02-29' },
      { outlet: 'Búsqueda', title: 'Ferrocarril Central tuvo "escandalosos" costos adicionales, según jerarca del Frente Amplio', url: 'https://www.busqueda.com.uy/Secciones/Ferrocarril-Central-tuvo-escandalosos-costos-adicionales-segun-jerarca-del-Frente-Amplio-uc60283', date: '2024-03-06' },
      { outlet: 'El Observador', title: 'Demanda millonaria por el Ferrocarril Central: senador del FA arremetió contra el gobierno y no descarta auditorías del MTOP', url: 'https://www.elobservador.com.uy/nacional/demanda-millonaria-ferrocarril-central-senador-del-fa-arremetio-contra-el-gobierno-y-no-descarta-auditorias-del-mtop-n5986845', date: '2025-02-25' },
      { outlet: 'Oficina de Planeamiento y Presupuesto', title: 'Gobierno firmó acuerdo con Grupo Vía Central y evita arbitraje', url: 'https://www.opp.gub.uy/es/noticias/gobierno-firmo-acuerdo-con-grupo-central-y-evita-arbitraje', date: '2025-05-19' },
      { outlet: 'Ministerio de Economía y Finanzas', title: 'Proyecto Ferrocarril Central — contrato, adendas e informes de pago', url: 'https://www.gub.uy/ministerio-economia-finanzas/politicas-y-gestion/proyecto-ferrocarril-central-0' },
    ],
    es: {
      title: 'Ferrocarril Central: los sobrecostos y el acuerdo de US$ 144 millones',
      dek: 'La obra ferroviaria más grande del país acumuló adendas por cientos de millones y terminó en un reclamo del consorcio que el Estado saldó en 2025 para evitar un arbitraje.',
      contexto: 'El Ferrocarril Central rehabilita la vía entre Montevideo y Paso de los Toros y se contrató bajo el régimen de Participación Público-Privada entre el Ministerio de Transporte y Obras Públicas y el consorcio Grupo Vía Central, con un esquema de pago por disponibilidad: el Estado paga por tener la vía en condiciones de uso durante el plazo del contrato. Según la ficha oficial del proyecto publicada por el Ministerio de Economía y Finanzas, el acta de puesta en servicio de la infraestructura se firmó el 8 de agosto de 2024, y el contrato registra adendas firmadas el 26 de febrero de 2024 y el 17 de junio de 2025, aprobadas por resoluciones del Poder Ejecutivo del 8 de mayo de 2024 y del 23 de julio de 2025.',
      hallazgo: 'En febrero de 2024 el MTOP informó al Parlamento sobre modificaciones al contrato con Grupo Vía Central. Según la diaria (29 de febrero de 2024), la segunda adenda —entonces a estudio del Tribunal de Cuentas— implicaba US$ 331 millones de costos adicionales y los sobrecostos totales podían llegar a US$ 670 millones; el representante del Frente Amplio en la Corporación Nacional para el Desarrollo criticó que el Estado asumiera riesgos que debe asumir exclusivamente el contratista, mientras la delegación oficial sostuvo que se buscaba evitar por todos los medios que surgieran juicios contra el Estado. Los puntos en discusión incluían el atravesamiento del río Yi en la ciudad de Durazno y el ingreso del ferrocarril en Montevideo, con sus 42 pasos a nivel. Búsqueda (6 de marzo de 2024) recogió que Alfredo Asti, director de la CND por el Frente Amplio, calificó de "escandalosos" los aumentos del monto de la obra y ubicó el costo final en US$ 2.982 millones frente a US$ 2.300 millones originales, unos US$ 682 millones más; el MTOP atribuyó los problemas a una formulación deficiente de los requisitos de disponibilidad de tierras, que obligó a expropiaciones adicionales y a modificaciones en Durazno y en los accesos a Montevideo.',
      statusNote: 'En febrero de 2025 Grupo Vía Central reclamó al Estado unos US$ 160 millones por la disponibilidad de la vía desde diciembre de 2023, cuando UPM empezó a usarla para transportar celulosa al puerto de Montevideo, según El Observador (25 de febrero de 2025); el senador frenteamplista Felipe Carballo dijo entonces que no descartaba impulsar auditorías en el MTOP. El 19 de mayo de 2025 la Oficina de Planeamiento y Presupuesto informó un acuerdo con el consorcio por US$ 144 millones correspondientes al período del 23 de diciembre de 2023 al 31 de marzo de 2025, con un primer pago de US$ 56,5 millones sujeto a evaluación y reliquidación de un mediador a designar entre las partes; según la OPP, el acuerdo evita el arbitraje internacional y, en palabras del ministro de Transporte, "coloca al país en una senda de respeto de los contratos". Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a mayo de 2025.',
      porQueImporta: 'El pago por disponibilidad del Ferrocarril Central sale del presupuesto nacional todos los años, durante el plazo del contrato. Cada adenda y cada acuerdo por reclamos se suma a esa factura y compite con el resto del gasto público: los US$ 144 millones del acuerdo de 2025 equivalen a más del doble de lo que la Intendencia de Montevideo pone en un año en el subsidio al boleto.',
      caveat: 'Los contratos de Participación Público-Privada se ejecutan por un régimen distinto al de las compras habituales, así que los pagos por disponibilidad y las adendas pueden no aparecer, o aparecer sólo en parte, en los datos abiertos de compras. El cruce sirve sobre todo para ver compras conexas del MTOP y de AFE.',
    },
    en: {
      title: 'Central Railway: cost overruns and a US$144 million settlement',
      dek: 'The country\'s largest rail project piled up contract amendments worth hundreds of millions and ended in a consortium claim the state settled in 2025 to avoid arbitration.',
      contexto: 'The Central Railway rebuilds the line between Montevideo and Paso de los Toros and was contracted under the Public-Private Partnership regime between the Ministry of Transport and Public Works and the Grupo Vía Central consortium, using an availability-payment scheme: the state pays for keeping the track usable over the contract term. According to the official project page published by the Ministry of Economy and Finance, the infrastructure\'s service-commencement act was signed on 8 August 2024, and the contract records amendments signed on 26 February 2024 and 17 June 2025, approved by Executive resolutions of 8 May 2024 and 23 July 2025.',
      hallazgo: 'In February 2024 the transport ministry briefed Parliament on changes to the contract with Grupo Vía Central. According to la diaria (29 February 2024), the second amendment — then under review by the Court of Auditors — carried US$331 million in additional costs, and total overruns could reach US$670 million; the Frente Amplio\'s representative on the Corporación Nacional para el Desarrollo criticised the state for assuming risks the contractor alone should bear, while the official delegation argued it was seeking by every means to prevent lawsuits against the state. Points at issue included the Yi river crossing in the city of Durazno and the railway\'s entry into Montevideo, with its 42 level crossings. Búsqueda (6 March 2024) reported that Alfredo Asti, the Frente Amplio\'s director at the CND, called the increases in the project\'s cost "scandalous" and put the final cost at US$2.982 billion against an original US$2.3 billion, some US$682 million more; the transport ministry attributed the problems to deficient drafting of the land-availability requirements, which forced additional expropriations and changes in Durazno and on the Montevideo approaches.',
      statusNote: 'In February 2025 Grupo Vía Central claimed some US$160 million from the state for track availability since December 2023, when UPM began using it to move pulp to the port of Montevideo, according to El Observador (25 February 2025); Frente Amplio senator Felipe Carballo said at the time he did not rule out pushing for audits at the transport ministry. On 19 May 2025 the Office of Planning and Budget reported an agreement with the consortium for US$144 million covering 23 December 2023 to 31 March 2025, with a first payment of US$56.5 million subject to assessment and recalculation by a mediator to be appointed by the parties; according to the OPP the agreement avoids international arbitration and, in the transport minister\'s words, "puts the country on a path of respect for contracts". As of this file\'s closing (August 2026) there are no developments after May 2025.',
      porQueImporta: 'The Central Railway\'s availability payment comes out of the national budget every year for the length of the contract. Every amendment and every claim settlement adds to that bill and competes with the rest of public spending: the US$144 million of the 2025 agreement is more than double what the Intendencia de Montevideo puts into the bus-fare subsidy in a year.',
      caveat: 'PPP contracts run under a different regime from ordinary purchasing, so availability payments and amendments may not appear, or may appear only partly, in the open procurement data. The cross-reference mainly helps surface related purchases by the transport ministry and the state railway.',
    },
  },
  {
    slug: 'aeropuertos-interior-concesion-directa',
    emoji: '✈️',
    theme: 'transporte',
    period: '2021-2025',
    statusKind: 'debate',
    status: 'debate',
    amountReported: 'US$ 67 millones de inversión inicial y más de US$ 300 millones en treinta años comprometidos por la concesionaria (El Observador, 10/11/2021); 18.566 pasajeros acumulados en los seis aeropuertos hasta mayo de 2025 (Búsqueda, 12/6/2025)',
    organisms: ['Ministerio de Defensa Nacional', 'Dirección Nacional de Aviación Civil e Infraestructura Aeronáutica', 'Ministerio de Transporte y Obras Públicas'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Comando General de la Armada',
        'Dirección Nacional Aviación Civil e Infraestructura Aeronáut',
        'Dirección Nacional de Sanidad de las Fuerzas Armadas',
        'Comando General del Ejército',
        'Dirección General de Secretaría de Estado',
        'Comando General de la Fuerza Aérea',
        'Dirección Nacional de Meteorología',
        'Dirección General de los Servicios',
        'Estado Mayor de la Defensa',
        'Servicio de Retiros y Pensiones de las Fuerzas Armadas',
        'Ex-Dirección General Infraestructura Aeronáutica',
        'Ex-Dirección Nacional Aviación Civil e Infraestr. Aeronau.',
        'Ex-Dirección General de Aviación Civil',
        'Ministerio de Transporte y Obras Públicas',
      ],
      search: 'terminal',
      yearFrom: 2021,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'El Observador', title: 'Gobierno amplió concesión del aeropuerto de Carrasco y otorgó otros seis del interior a la misma empresa', url: 'https://www.elobservador.com.uy/nota/gobierno-amplio-concesion-del-aeropuerto-de-carrasco-y-otorgo-seis-aeropuertos-del-interior-a-la-misma-empresa-20211110103646', date: '2021-11-10' },
      { outlet: 'Búsqueda', title: 'Adjudicación de aeropuertos causó ruido en la coalición y silencio en la oposición', url: 'https://www.busqueda.com.uy/Secciones/Adjudicacion-de-aeropuertos-causo-ruido-en-la-coalicion-y-silencio-en-la-oposicion-uc50173', date: '2021-11-11' },
      { outlet: 'Telenoche (Canal 4)', title: 'García sobre aeropuertos: "Nadie se iba a presentar porque van a pérdida"', url: 'https://www.telenoche.com.uy/nacionales/garcia-sobre-aeropuertos-nadie-se-iba-a-presentar-porque-van-a-perdida', date: '2021-11-11' },
      { outlet: 'Presidencia de la República', title: 'Decreto N° 105/024 — Se amplía el objeto de la concesión otorgada a la empresa Puerta del Sur', url: 'https://www.gub.uy/presidencia/institucional/normativa/decreto-n-105024-se-amplia-objeto-concesion-otorgada-empresa-puerta-del-sur', date: '2024-04-16' },
      { outlet: 'Búsqueda', title: 'Aeropuertos concesionados del interior producen "primeros indicios alentadores" en algunos departamentos', url: 'https://www.busqueda.com.uy/economia/aeropuertos-concesionados-del-interior-producen-primeros-indicios-alentadores-algunos-departamentos-n5400727', date: '2025-06-12' },
      { outlet: 'Teledoce', title: 'Más de 10.000 personas pasaron por los nuevos seis aeropuertos del interior en el último año', url: 'https://www.teledoce.com/telemundo/nacionales/mas-de-10-000-personas-pasaron-por-los-nuevos-seis-aeropuertos-del-interior-en-el-ultimo-ano/', date: '2025-06-20' },
    ],
    es: {
      title: 'Seis aeropuertos del interior, sin licitación, a un solo operador',
      dek: 'El Ejecutivo desistió del llamado que había anunciado y amplió la concesión de Puerta del Sur hasta 2053; hasta mayo de 2025 los seis aeropuertos sumaban 18.566 pasajeros.',
      contexto: 'En mayo de 2021 el gobierno de Luis Lacalle Pou anunció que licitaría la operación de seis aeropuertos del interior. El 10 de noviembre de 2021 optó por otra vía: adjudicó de forma directa los aeropuertos de Rivera, Salto, Carmelo, Durazno, Melo y Paysandú a Puerta del Sur S.A., del grupo argentino Corporación América de Eduardo Eurnekian, que ya operaba Carrasco, y extendió la concesión de Carrasco de 2033 a 2053. Según El Observador, la empresa se obliga a una inversión de US$ 67 millones en las terminales del interior y a más de US$ 300 millones en treinta años, con US$ 15 millones para Rivera y para Salto y US$ 8 millones para Carmelo y para Durazno.',
      hallazgo: 'Búsqueda informó el 11 de noviembre de 2021 que la adjudicación fue directa pese al llamado anunciado en mayo, y que la decisión "provocó ruido y malestar en socios de la coalición, y un prudente silencio en filas de la oposición": objetaron Cabildo Abierto y el Partido Independiente, y el senador Guillermo Domenech reclamó que "este es un gobierno de la coalición y debe actuar como gobierno de coalición". El entonces ministro de Defensa, Javier García, defendió la decisión ante Telenoche (11 de noviembre de 2021): sostuvo que la ampliación "está habilitado por ley" y preguntó qué posibilidades había con seis aeropuertos del interior que nadie quería, "porque van a pérdida". Sobre el uso efectivo, Búsqueda publicó el 12 de junio de 2025 que entre enero y mayo de ese año Salto registró 415 movimientos y 2.536 pasajeros, Carmelo 652 y 1.111, Paysandú 357 y 388, Rivera 136 y 652, Melo 195 y 259 y Durazno 113 y 134, con 9.444 movimientos y 18.566 pasajeros acumulados desde la apertura de cada terminal.',
      statusNote: 'El 16 de abril de 2024 el Decreto 105/024 amplió el objeto de la concesión de Puerta del Sur incorporando el espacio físico de la antigua terminal de pasajeros de Carrasco, con vigencia hasta el 20 de noviembre de 2053. La concesionaria sostiene que los resultados son incipientes pero positivos en parte de la red: según Búsqueda (12 de junio de 2025), la empresa afirma que Salto y Carmelo superaron las expectativas, mientras actores locales dicen que Durazno prácticamente no se movió; el gerente de operaciones de Aeropuertos Uruguay, Federico Cabrera, dijo que es "muy pronto para evaluar el impacto" y que hablar de rentabilidad por terminal "sería apresurado", porque Carrasco y Punta del Este sostienen a las más chicas dentro de un modelo de sistema. Teledoce informó el 20 de junio de 2025, con registros del Ministerio de Defensa, que algo más de 10.000 personas pasaron por los seis aeropuertos en el último año. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a junio de 2025.',
      porQueImporta: 'Las terminales del interior son bienes públicos concesionados por décadas: lo que ocurra con ellas hasta 2053 quedó definido sin competencia entre oferentes. Y el tráfico real —menos de 19.000 pasajeros acumulados entre los seis hasta mayo de 2025— es el dato que permite juzgar si la inversión comprometida sirve al desarrollo de esos departamentos o queda ociosa.',
      caveat: 'Una concesión no es una compra: la operación de los aeropuertos no se ejecuta con pagos del Estado a un proveedor, así que no aparece como contrato en los datos abiertos. El cruce sí puede mostrar compras aeronáuticas de los organismos que siguen operando terminales.',
    },
    en: {
      title: 'Six interior airports handed to one operator, without a tender',
      dek: 'The Executive dropped the tender it had announced and extended Puerta del Sur\'s concession to 2053; through May 2025 the six airports had handled 18,566 passengers.',
      contexto: 'In May 2021 Luis Lacalle Pou\'s government announced it would tender the operation of six interior airports. On 10 November 2021 it chose another route: it directly awarded the airports of Rivera, Salto, Carmelo, Durazno, Melo and Paysandú to Puerta del Sur S.A., part of Eduardo Eurnekian\'s Argentine group Corporación América, which already ran Carrasco, and extended the Carrasco concession from 2033 to 2053. According to El Observador, the company is bound to invest US$67 million in the interior terminals and more than US$300 million over thirty years, with US$15 million each for Rivera and Salto and US$8 million each for Carmelo and Durazno.',
      hallazgo: 'Búsqueda reported on 11 November 2021 that the award was direct despite the tender announced in May, and that the decision "caused noise and unease among coalition partners, and a prudent silence in opposition ranks": Cabildo Abierto and the Partido Independiente objected, and senator Guillermo Domenech argued that "this is a coalition government and it must act as a coalition government". Then defence minister Javier García defended the decision on Telenoche (11 November 2021): he said the extension "is authorised by law" and asked what the options were with six interior airports nobody wanted, "because they run at a loss". On actual use, Búsqueda reported on 12 June 2025 that between January and May of that year Salto recorded 415 movements and 2,536 passengers, Carmelo 652 and 1,111, Paysandú 357 and 388, Rivera 136 and 652, Melo 195 and 259, and Durazno 113 and 134, with 9,444 movements and 18,566 passengers accumulated since each terminal opened.',
      statusNote: 'On 16 April 2024 Decree 105/024 widened Puerta del Sur\'s concession to include the physical space of the old Carrasco passenger terminal, running to 20 November 2053. The concessionaire argues the results are early but positive in part of the network: according to Búsqueda (12 June 2025), the company says Salto and Carmelo exceeded expectations, while local actors say Durazno has practically not moved; Aeropuertos Uruguay\'s operations manager, Federico Cabrera, said it is "far too soon to assess the impact" and that discussing profitability terminal by terminal "would be hasty", because Carrasco and Punta del Este sustain the smaller ones within a system-wide model. Teledoce reported on 20 June 2025, citing Defence Ministry records, that slightly more than 10,000 people passed through the six airports in the past year. As of this file\'s closing (August 2026) there are no developments after June 2025.',
      porQueImporta: 'The interior terminals are public assets conceded for decades: what happens to them until 2053 was settled without competition among bidders. And the real traffic — fewer than 19,000 accumulated passengers across all six through May 2025 — is the figure that shows whether the committed investment serves those departments\' development or sits idle.',
      caveat: 'A concession is not a purchase: airport operation is not executed through state payments to a supplier, so it does not appear as a contract in the open data. The cross-reference can show aeronautical purchases by the bodies that still operate terminals.',
    },
  },
  {
    slug: 'pluna-aval-brou-remate-aviones',
    emoji: '🛩️',
    theme: 'transporte',
    period: '2012-2017',
    statusKind: 'judicial',
    status: 'condena',
    amountReported: 'Aval por US$ 13,7 millones dentro de una operación de US$ 137 millones por los aviones (La Nación, 4/4/2014)',
    organisms: ['Banco de la República Oriental del Uruguay', 'Ministerio de Economía y Finanzas'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'La Nación (Argentina)', title: 'Uruguay: procesaron a dos funcionarios del gobierno de Pepe Mujica por el caso Pluna', url: 'https://www.lanacion.com.ar/el-mundo/uruguay-procesaron-a-dos-funcionarios-del-gobierno-de-pepe-mujica-por-el-caso-pluna-nid1678053/', date: '2014-04-04' },
      { outlet: 'Subrayado', title: 'Justicia absolvió a Lorenzo y condenó a Calloia por el aval en el caso Pluna', url: 'https://www.subrayado.com.uy/justicia-absolvio-lorenzo-y-condeno-calloia-el-aval-el-caso-pluna-n73344', date: '2017-12-18' },
      { outlet: 'El Observador', title: 'La Justicia condenó a Calloia y absolvió a Lorenzo por el caso Pluna', url: 'https://www.elobservador.com.uy/nota/la-justicia-condeno-a-calloia-y-absolvio-a-lorenzo-por-el-caso-pluna-2017121813210', date: '2017-12-18' },
    ],
    es: {
      title: 'El aval del BROU para el remate de los aviones de Pluna',
      dek: 'La justicia condenó al expresidente del Banco República por abuso de funciones tras el aval a Cosmo, único oferente del remate, y absolvió al exministro de Economía.',
      contexto: 'Pluna, la aerolínea de bandera, dejó de volar en julio de 2012 durante el gobierno de José Mujica. Para pagar deudas, el Estado remató ese año siete aviones de la empresa. Se presentó un único oferente: Cosmo, una supuesta aerolínea europea representada por Hernán Antonio Calvo Sánchez —que se presentaba como "Antonio Sánchez"— a quien La Nación describe como representante en España del grupo Buquebus. Para habilitar esa oferta el Banco de la República otorgó un aval. Según La Nación, el "comprador" no pagó ni los US$ 137 millones prometidos por los aviones ni la garantía de US$ 13,7 millones, y aclaró que no contrataría a los extrabajadores de Pluna ni abriría una aerolínea en Uruguay; acreedores postergados recurrieron la ley que había habilitado la subasta ante la Suprema Corte de Justicia y el Poder Judicial la declaró inconstitucional.',
      hallazgo: 'En abril de 2014 fueron procesados sin prisión el exministro de Economía Fernando Lorenzo y el presidente del Banco República, Fernando Calloia, por un delito de abuso de funciones vinculado al aval irregular otorgado a Cosmo, por US$ 13,7 millones dentro de una operación de US$ 137 millones, según La Nación. El 18 de diciembre de 2017 la jueza María Helena Mainard resolvió la causa: absolvió a Lorenzo y condenó a Calloia. Subrayado y El Observador informaron ese mismo día que la pena fue de 20 meses de prisión, inhabilitación especial por dos años y una multa de 1.000 unidades reajustables —del orden de un millón de pesos—, y que Calloia no iría a prisión porque el delito es excarcelable. El Observador consignó que Lorenzo fue absuelto porque, según la sentencia, "no surge probado que este hubiera actuado como garante verbal de la operación", y que la comunicación de su ministerio pidiendo al BROU que gestionara el aval no constituyó una garantía formal.',
      statusNote: 'La sentencia se dictó el 18 de diciembre de 2017: condena a Fernando Calloia por abuso de funciones y absolución de Fernando Lorenzo. Ninguna de las fuentes consultadas recoge el descargo de Calloia o de su defensa ante la condena. Al cierre de esta ficha (agosto de 2026) tampoco constan en esas fuentes novedades posteriores a diciembre de 2017 sobre instancias de apelación o casación en esta causa, por lo que no corresponde afirmar aquí que la condena haya quedado firme ni que haya sido revocada.',
      porQueImporta: 'El cierre de Pluna y el remate fallido dejaron aviones inmovilizados, deudas creciendo y una garantía estatal comprometida. Es el caso que muestra el costo de decidir rápido sobre activos públicos sin verificar quién está del otro lado del mostrador: lo que no se cobró y lo que se litigó después lo terminó absorbiendo el Estado.',
      caveat: 'Ni el remate ni el aval bancario son compras públicas: no dejan rastro en los datos abiertos de contrataciones. El cruce sólo puede mostrar compras corrientes de los organismos involucrados, no la operación que originó la causa penal.',
    },
    en: {
      title: 'The state bank guarantee behind the Pluna aircraft auction',
      dek: 'A court convicted the former head of Banco República of abuse of office over the guarantee given to Cosmo, the auction\'s sole bidder, and acquitted the former economy minister.',
      contexto: 'Pluna, the flag carrier, stopped flying in July 2012 under José Mujica\'s government. To pay debts, the state auctioned seven of the airline\'s aircraft that year. A single bidder appeared: Cosmo, a purported European airline represented by Hernán Antonio Calvo Sánchez — who went by "Antonio Sánchez" — whom La Nación describes as the Buquebus group\'s representative in Spain. To enable that bid, Banco de la República issued a guarantee. According to La Nación, the "buyer" paid neither the US$137 million promised for the aircraft nor the US$13.7 million guarantee, and stated it would neither hire Pluna\'s former workers nor open an airline in Uruguay; creditors left behind by the law that enabled the auction challenged it before the Supreme Court and the judiciary declared it unconstitutional.',
      hallazgo: 'In April 2014 former economy minister Fernando Lorenzo and Banco República president Fernando Calloia were charged without detention with abuse of office over the irregular guarantee granted to Cosmo, worth US$13.7 million within a US$137 million transaction, according to La Nación. On 18 December 2017 judge María Helena Mainard resolved the case: she acquitted Lorenzo and convicted Calloia. Subrayado and El Observador reported that same day that the sentence was 20 months in prison, a two-year special disqualification and a fine of 1,000 adjustable units — around one million pesos — and that Calloia would not serve prison time because the offence carries release. El Observador noted Lorenzo was acquitted because, per the ruling, "it is not proven that he acted as verbal guarantor of the operation", and that his ministry\'s communication asking BROU to work on the guarantee did not amount to a formal guarantee.',
      statusNote: 'The ruling was handed down on 18 December 2017: conviction of Fernando Calloia for abuse of office and acquittal of Fernando Lorenzo. None of the sources consulted carries Calloia\'s or his defence\'s response to the conviction. As of this file\'s closing (August 2026), those sources also show no developments after December 2017 on appeals or cassation in this case, so it cannot be stated here that the conviction is final or that it was overturned.',
      porQueImporta: 'Pluna\'s closure and the failed auction left aircraft grounded, debts growing and a state guarantee on the line. It is the case that shows the cost of deciding quickly about public assets without checking who is on the other side of the counter: what went uncollected and what was litigated afterwards was ultimately absorbed by the state.',
      caveat: 'Neither the auction nor the bank guarantee is a public purchase: they leave no trace in the open procurement data. The cross-reference can only show routine purchases by the bodies involved, not the transaction that triggered the criminal case.',
    },
  },
  {
    slug: 'pluna-laudo-ciadi-larah',
    emoji: '⚖️',
    theme: 'transporte',
    period: '2012-2025',
    statusKind: 'judicial',
    status: 'terminado',
    amountReported: 'US$ 30 millones más intereses, con una penalidad de US$ 500.000 por cada mes de atraso (La Nación, 14/2/2024; El Observador, 30/1/2025)',
    organisms: ['Ministerio de Economía y Finanzas', 'Presidencia de la República'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Ministerio de Economía y Finanzas',
        'Presidencia de la República y Oficinas Dependientes',
        'Presidencia de la República',
        'Oficina Nacional del Servicio Civil',
        'Secretaría Nacional del Deporte',
        'Oficina de Planeamiento y Presupuesto',
        'Unidad Reguladora de Servic.de Comunicaciones-URSEC',
        'Casa Militar',
        'Instituto Nacional de Estadística',
        'AGESIC',
        'Unidad Reguladora de Serv. de Energía y Agua-URSEA',
        'Presidencia de la República y Unidades Dependientes',
        'NO VIGENTE - Dirección de Proyectos de Desarrollo',
        'Secretaría Nacional del Deporte',
        'Instituto Nacional de EstadÍstica',
        'Agen.p/Des.del Gob.de Gest.Electr.y Soc.Inform.y del Conoc.',
      ],
      search: 'asesoramiento',
      yearFrom: 2012,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'La Nación (Argentina)', title: 'Uruguay deberá pagar 30 millones de dólares por un fallo contra el cierre de la aerolínea Pluna', url: 'https://www.lanacion.com.ar/el-mundo/uruguay-debera-pagar-30-millones-de-dolares-por-un-fallo-contra-el-cierre-de-la-aerolinea-pluna-nid14022024/', date: '2024-02-14' },
      { outlet: 'El Observador', title: 'Caso Pluna: Uruguay llega a acuerdo con Larah para pago de laudo por US$ 30 millones más intereses', url: 'https://www.elobservador.com.uy/economia-y-empresas/caso-pluna-uruguay-llega-acuerdo-larah-pago-laudo-us-30-millones-n5982481', date: '2025-01-30' },
      { outlet: 'la diaria', title: 'Díaz dijo que "molestó" que el gobierno anterior no haya informado sobre embargo de cuentas del Estado en Luxemburgo', url: 'https://ladiaria.com.uy/politica/articulo/2025/9/diaz-dijo-que-molesto-que-el-gobierno-anterior-no-haya-informado-sobre-embargo-de-cuentas-del-estado-en-luxemburgo/', date: '2025-09-08' },
    ],
    es: {
      title: 'El laudo del Ciadi por Pluna y el embargo en Luxemburgo',
      dek: 'Un tribunal del Banco Mundial condenó a Uruguay a pagar US$ 30 millones a un accionista de Pluna; el país acordó el pago tras quedar con cuentas embargadas nueve meses.',
      contexto: 'Además de la causa penal local, el cierre de Pluna en 2012 abrió un frente internacional. Latin American Regional Aviation Company Holding (Larah), firma panameña que había adquirido acciones en la casa matriz de la aerolínea, demandó a Uruguay ante el Centro Internacional de Arreglo de Diferencias relativas a Inversiones (Ciadi), del Banco Mundial, invocando el tratado bilateral de protección de inversiones con Panamá. Las cifras publicadas del reclamo difieren: El Observador consignó que en su reclamación inicial pedía alrededor de US$ 800 millones y La Nación la ubicó en US$ 860 millones. En febrero de 2024 el tribunal falló contra el Estado uruguayo por expropiación y violación de la obligación de trato justo y equitativo.',
      hallazgo: 'La Nación informó el 14 de febrero de 2024 que el Ciadi condenó a Uruguay a pagar US$ 30 millones más intereses, con una penalidad de US$ 500.000 por cada mes de atraso, y que el tribunal entendió que el gobierno "asfixió económicamente a Pluna para evitar las contingencias derivadas de la quiebra de Varig": obstaculizó la obtención de un préstamo cuando la aerolínea estaba en grave situación de iliquidez, hubo declaraciones públicas dañinas de jerarcas, presión de ANCAP para exigir el pago inmediato del combustible y beneficios fiscales a la aerolínea sucesora que antes se habían negado a los inversores privados. El Observador informó el 30 de enero de 2025 que el Estado acordó pagar los US$ 30 millones más intereses, tras negociaciones sostenidas desde mayo de 2024 que se rompieron el 14 de noviembre de ese año, y que el gobierno no aceptó la indemnidad penal que Larah pedía para los acusados por estafa en la gestión de Pluna.',
      statusNote: 'la diaria informó el 8 de setiembre de 2025 —citando a El País— que las cuentas del Estado uruguayo en Luxemburgo estuvieron embargadas entre el 22 de noviembre y el 27 de agosto por el no pago del laudo, y que el pago se concretó el 30 de mayo. El prosecretario de Presidencia, Jorge Díaz, dijo que le "molestó bastante" que el gobierno anterior no informara del embargo durante la transición. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores a setiembre de 2025.',
      porQueImporta: 'Los US$ 30 millones del laudo, más los intereses y la penalidad mensual acumulada mientras no se pagó, salieron de rentas generales: es dinero que no se decidió gastar en un servicio, sino que hubo que pagar por una decisión tomada más de una década antes. El episodio del embargo muestra además que la factura de un litigio internacional puede aparecer sin aviso.',
      caveat: 'El pago de un laudo arbitral no es una compra pública y no figura en los datos abiertos de contrataciones. Sí pueden aparecer contrataciones de asesoramiento jurídico y patrocinio internacional asociadas a la defensa del Estado, que son sólo una parte del costo.',
    },
    en: {
      title: 'The ICSID award over Pluna and the Luxembourg embargo',
      dek: 'A World Bank tribunal ordered Uruguay to pay US$30 million to a Pluna shareholder; the country settled after its accounts sat frozen for nine months.',
      contexto: 'Beyond the domestic criminal case, Pluna\'s 2012 closure opened an international front. Latin American Regional Aviation Company Holding (Larah), a Panamanian firm that had acquired shares in the airline\'s parent company, sued Uruguay before the World Bank\'s International Centre for Settlement of Investment Disputes (ICSID), invoking the bilateral investment protection treaty with Panama. Published figures for the claim differ: El Observador reported that its initial claim sought around US$800 million, while La Nación put it at US$860 million. In February 2024 the tribunal ruled against the Uruguayan state for expropriation and breach of the fair and equitable treatment obligation.',
      hallazgo: 'La Nación reported on 14 February 2024 that ICSID ordered Uruguay to pay US$30 million plus interest, with a penalty of US$500,000 for each month of delay, and that the tribunal found the government "economically asphyxiated Pluna to avoid the contingencies arising from Varig\'s bankruptcy": it obstructed a loan when the airline was in serious illiquidity, officials made damaging public statements, the state oil company ANCAP pressed for immediate fuel payment, and the successor airline was granted tax benefits previously denied to private investors. El Observador reported on 30 January 2025 that the state agreed to pay the US$30 million plus interest, after talks held since May 2024 that broke down on 14 November that year, and that the government did not accept the criminal immunity Larah sought for those accused of fraud in Pluna\'s management.',
      statusNote: 'la diaria reported on 8 September 2025 — citing El País — that Uruguayan state accounts in Luxembourg were under embargo from 22 November to 27 August over non-payment of the award, and that payment was made on 30 May. The presidential pro-secretary, Jorge Díaz, said it "bothered him quite a lot" that the previous government had not reported the embargo during the transition. As of this file\'s closing (August 2026) there are no developments after September 2025.',
      porQueImporta: 'The award\'s US$30 million, plus interest and the monthly penalty accrued while it went unpaid, came out of general revenue: money that was not chosen for a service but had to be paid over a decision taken more than a decade earlier. The embargo episode also shows that the bill for international litigation can arrive without warning.',
      caveat: 'Paying an arbitral award is not a public purchase and does not appear in the open procurement data. Contracts for legal advice and international representation tied to the state\'s defence may appear, but they are only part of the cost.',
    },
  },
  {
    slug: 'omnibus-electricos-fideicomiso-montevideo',
    emoji: '🔌',
    theme: 'transporte',
    period: '2024-2025',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: '248 millones de unidades indexadas, aproximadamente US$ 37 millones, para unos 90 ómnibus eléctricos (Intendencia de Montevideo, 15/2/2024)',
    organisms: ['Intendencia de Montevideo'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Intendencia de Montevideo',
      ],
      search: 'eléctrico',
      yearFrom: 2024,
      yearTo: 2025,
    },
    sources: [
      { outlet: 'Intendencia de Montevideo', title: 'Fideicomiso para la compra de nuevos ómnibus eléctricos', url: 'https://montevideo.gub.uy/noticias/movilidad-y-transporte/fideicomiso-para-la-compra-de-nuevos-omnibus-electricos', date: '2024-02-15' },
      { outlet: 'Telenoche (Canal 4)', title: 'La IM presentó fideicomiso para la compra de nuevos ómnibus eléctricos', url: 'https://www.telenoche.com.uy/nacionales/la-im-presento-fideicomiso-la-compra-nuevos-omnibus-electricos-n5363163', date: '2024-02-16' },
      { outlet: 'UyPress', title: 'Fideicomiso para la compra de nuevos ómnibus eléctricos', url: 'https://uypress.net/auc.aspx?134595', date: '2024-02-16' },
      { outlet: 'Intendencia de Montevideo', title: 'Medidas de ordenamiento financiero y eficiencia en la gestión', url: 'https://montevideo.gub.uy/noticias/medidas-de-ordenamiento-financiero-y-eficiencia-en-la-gestion', date: '2025-09-12' },
    ],
    es: {
      title: 'Los 90 ómnibus eléctricos que se pagan con el 1,7% del boleto',
      dek: 'La Intendencia armó un fideicomiso de unos US$ 37 millones para renovar la flota; la deuda la asumen las empresas y se repaga con parte de la recaudación de boletos y subsidios.',
      contexto: 'El 15 de febrero de 2024 la Intendencia de Montevideo presentó el fideicomiso financiero para la renovación tecnológica del transporte colectivo urbano. La suscripción de los valores se realizó los días 7 y 8 de febrero y colocó 248 millones de unidades indexadas —aproximadamente US$ 37 millones—, con una demanda que llegó a 461 millones de UI, del orden de US$ 69 millones. Financia la adquisición de aproximadamente 90 nuevos buses eléctricos, que llevarían la flota eléctrica a 121 unidades, y la sustitución de los sistemas de validación en los ómnibus de Montevideo para habilitar el pago con celular, código QR y tarjetas de crédito. La fiduciaria es EF Asset Management Administradora de Fondos de Inversión S.A. y la Intendencia administra los fondos del fideicomiso y actúa como garante.',
      hallazgo: 'Según la propia Intendencia, el fideicomiso se repaga con el 1,7% de la recaudación bruta total de la venta de boletos del transporte colectivo urbano, y esa base de cálculo incluye los subsidios que la Intendencia paga y las multas e intereses de mora del sistema; la deuda la asumen las empresas de transporte para comprar los ómnibus y los equipos, con la Intendencia como garante. Telenoche informó el 16 de febrero de 2024 que la presentación estuvo encabezada por la intendenta Carolina Cosse. UyPress consignó ese mismo día que la inversión en los títulos de deuda fue calificada por CARE Calificadora de Riesgo con la categoría AA (uy) y que la TIR promedio a pagar, 3,54% en UI, es apenas 57 puntos básicos superior a la de los títulos de deuda soberana. El repago, entonces, se apoya en un flujo que incluye dinero público: la garantía es de la Intendencia y parte de la recaudación afectada son subsidios que ella misma paga.',
      statusNote: 'La emisión se colocó en febrero de 2024 y la Intendencia informó que la flota eléctrica llegaría a 121 unidades. En setiembre de 2025 la Intendencia anunció, dentro de ocho medidas de ordenamiento financiero para el período de octubre de 2025 a marzo de 2026, la postergación de un 10% del pago del subsidio al boleto, que integra la base de recaudación afectada al repago del fideicomiso. Al cierre de esta ficha (agosto de 2026) no constan en las fuentes consultadas novedades posteriores a setiembre de 2025 sobre el cronograma de entrega de los ómnibus.',
      porQueImporta: 'Un ómnibus eléctrico gasta menos y no emite en la calle: la Intendencia estima un ahorro de unos 33.000 litros de gasoil por unidad al año y una reducción de 5.760 toneladas de CO2 anuales por las 90 unidades. Pero el 1,7% de cada boleto vendido va a pagar esa flota durante años, de modo que la renovación se financia, en parte, con lo que pone el pasajero y con lo que pone la Intendencia.',
      caveat: 'Los ómnibus los compran las empresas con el dinero del fideicomiso, no la Intendencia: esas compras no son contrataciones públicas y no aparecen en los datos abiertos. Sí pueden aparecer compras conexas de la Intendencia, como obras de infraestructura de carga o equipamiento.',
    },
    en: {
      title: 'The 90 electric buses paid for with 1.7% of every fare',
      dek: 'The city set up a roughly US$37 million trust to renew the fleet; the debt is taken on by the companies and repaid out of ticket revenue and subsidies.',
      contexto: 'On 15 February 2024 the Intendencia de Montevideo presented the financial trust for the technological renewal of urban collective transport. The securities were subscribed on 7 and 8 February, placing 248 million indexed units — roughly US$37 million — with demand reaching 461 million UI, around US$69 million. It funds the purchase of approximately 90 new electric buses, which would bring the electric fleet to 121 vehicles, and the replacement of validation systems on Montevideo\'s buses to enable payment by phone, QR code and credit cards. The trustee is EF Asset Management Administradora de Fondos de Inversión S.A., and the city administers the trust\'s funds and acts as guarantor.',
      hallazgo: 'According to the city itself, the trust is repaid with 1.7% of total gross revenue from urban collective transport ticket sales, and that base includes the subsidies the city pays plus the system\'s fines and late-payment interest; the debt is assumed by the transport companies to buy the buses and equipment, with the city as guarantor. Telenoche reported on 16 February 2024 that the presentation was led by mayor Carolina Cosse. UyPress noted the same day that the investment in the debt securities was rated AA (uy) by CARE Calificadora de Riesgo, and that the average IRR to be paid, 3.54% in UI, is barely 57 basis points above that of sovereign debt securities. Repayment therefore rests on a flow that includes public money: the guarantee is the city\'s, and part of the earmarked revenue consists of subsidies the city itself pays.',
      statusNote: 'The issue was placed in February 2024 and the city said the electric fleet would reach 121 vehicles. In September 2025 the city announced, among eight financial-ordering measures for October 2025 to March 2026, a postponement of 10% of the fare-subsidy payment, which forms part of the revenue base earmarked for repaying the trust. As of this file\'s closing (August 2026), the sources consulted show no developments after September 2025 on the bus delivery schedule.',
      porQueImporta: 'An electric bus costs less to run and emits nothing on the street: the city estimates savings of around 33,000 litres of diesel per vehicle per year and a reduction of 5,760 tonnes of CO2 annually across the 90 units. But 1.7% of every ticket sold goes to paying for that fleet for years, so the renewal is financed, in part, by what the passenger pays and what the city puts in.',
      caveat: 'The buses are bought by the companies with trust money, not by the city: those purchases are not public procurement and do not appear in the open data. Related city purchases, such as charging infrastructure works or equipment, may appear.',
    },
  },
  {
    slug: 'subsidio-aire-acondicionado-omnibus',
    emoji: '❄️',
    theme: 'transporte',
    period: '2025-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: '$ 12 millones destinados en 2025 a los dos subsidios de aire acondicionado en ómnibus urbanos, según la Intendencia de Montevideo (2/1/2026) y Subrayado (5/1/2026)',
    organisms: ['Intendencia de Montevideo'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Intendencia de Montevideo',
      ],
      search: 'aire acondicionado',
      yearFrom: 2025,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Intendencia de Montevideo', title: 'Subsidio al uso de aire acondicionado en el transporte público urbano', url: 'https://montevideo.gub.uy/noticias/subsidio-al-uso-de-aire-acondicionado-en-el-transporte-publico-urbano', date: '2026-01-02' },
      { outlet: 'Subrayado', title: 'IMM fiscaliza uso de aire acondicionado en ómnibus urbanos, desde diciembre y hasta febrero', url: 'https://www.subrayado.com.uy/imm-fiscaliza-uso-aire-acondicionado-omnibus-urbanos-diciembre-y-febrero-n996702', date: '2026-01-05' },
      { outlet: 'Montevideo Portal', title: 'Edil alerta por reclamos sobre ómnibus que circulan sin aire acondicionado en Montevideo', url: 'https://www.montevideo.com.uy/Noticias/Edil-alerta-por-reclamos-sobre-omnibus-que-circulan-sin-aire-acondicionado-en-Montevideo-uc954045', date: '2026-02-24' },
    ],
    es: {
      title: 'El subsidio para que el ómnibus prenda el aire acondicionado',
      dek: 'La Intendencia destinó $ 12 millones en 2025 a que las empresas enciendan el aire en verano; un edil advirtió que igual circulan apagados en el horario obligatorio.',
      contexto: 'Desde el 1° de diciembre y hasta el 28 de febrero, las unidades del transporte urbano de Montevideo que tienen aire acondicionado están obligadas a encenderlo entre las 9 y las 19 horas, y mientras el aire esté prendido deben mantenerse cerradas ventanas y escotillas. Según la Intendencia, Montevideo cuenta con 560 unidades de transporte con aire acondicionado. Para esto la comuna otorga dos subsidios a las empresas: uno para la compra del equipo y otro por el mayor consumo energético. El control lo hacen inspectores de la División Transporte y la Intendencia habilitó denuncias de los usuarios por WhatsApp, por teléfono y por redes sociales.',
      hallazgo: 'En su comunicación oficial del 2 de enero de 2026, la Intendencia informó que "en 2025, dichos subsidios ascendieron a 12 millones de pesos", dato que Subrayado replicó el 5 de enero junto con las 560 unidades equipadas y las condiciones de fiscalización. El 24 de febrero de 2026 Montevideo Portal informó que el edil colorado Federico Paganini presentó un pedido de informes: dijo haber recibido "una infinidad de reclamos de usuarios por ómnibus con los aires apagados, en horarios donde la resolución los obliga a tenerlos prendidos" y pidió conocer la situación al detalle, incluido cómo se está aplicando el subsidio. La obligación estacional regía hasta el 28 de febrero. Ni la comunicación oficial de la Intendencia ni las notas periodísticas consultadas difunden datos de incumplimientos detectados.',
      statusNote: 'El pedido de informes del edil Federico Paganini se presentó el 24 de febrero de 2026, cuatro días antes de que venciera la obligación estacional de encender el aire acondicionado. La nota de Montevideo Portal no incluye respuesta de la Intendencia a ese pedido. Al cierre de esta ficha (agosto de 2026) tampoco constan en las fuentes consultadas datos publicados sobre sanciones aplicadas o incumplimientos verificados durante el verano 2025-2026.',
      porQueImporta: 'Son $ 12 millones al año por un servicio que el pasajero puede verificar con sólo subirse al ómnibus en enero. Es el tipo de gasto chico y comprobable donde la diferencia entre pagar por un servicio y efectivamente recibirlo se mide en la vida cotidiana de quien viaja parado a las tres de la tarde.',
      caveat: 'El subsidio es una transferencia a las empresas, no una compra licitada, y no aparece como contrato en los datos abiertos. El cruce puede mostrar compras propias de la Intendencia vinculadas al transporte, pero no el pago del subsidio ni su control.',
    },
    en: {
      title: 'The subsidy that pays buses to switch on the air conditioning',
      dek: 'The city put $12 million into getting companies to run the AC in summer in 2025; a councillor warned buses still circulate with it off during mandatory hours.',
      contexto: 'From 1 December to 28 February, Montevideo urban buses fitted with air conditioning must run it between 9am and 7pm, and while the AC is on, windows and roof hatches must be kept closed. According to the city, Montevideo has 560 transport vehicles with air conditioning. For this the city grants companies two subsidies: one for buying the equipment and one for the higher energy consumption. Enforcement is carried out by Transport Division inspectors, and the city has opened channels for users to report violations by WhatsApp, phone and social media.',
      hallazgo: 'In its official communication of 2 January 2026, the city reported that "in 2025, those subsidies came to 12 million pesos", a figure Subrayado repeated on 5 January along with the 560 equipped vehicles and the enforcement conditions. On 24 February 2026 Montevideo Portal reported that Colorado Party councillor Federico Paganini filed a request for information: he said he had received "an endless stream of complaints from users about buses with the AC off, during hours when the resolution requires it to be on" and asked to know the situation in detail, including how the subsidy is being applied. The seasonal obligation ran until 28 February. Neither the city\'s official communication nor the news items consulted publish data on breaches detected.',
      statusNote: 'Councillor Federico Paganini\'s request for information was filed on 24 February 2026, four days before the seasonal obligation to run the air conditioning expired. The Montevideo Portal item carries no reply from the city to that request. As of this file\'s closing (August 2026), the sources consulted also show no published data on penalties applied or breaches verified during the 2025-2026 summer.',
      porQueImporta: 'It is $12 million a year for a service any passenger can verify simply by boarding a bus in January. It is the kind of small, checkable spending where the gap between paying for a service and actually receiving it is measured in the daily life of someone standing on a bus at three in the afternoon.',
      caveat: 'The subsidy is a transfer to the companies, not a tendered purchase, and does not appear as a contract in the open data. The cross-reference can show the city\'s own transport-related purchases, but not the subsidy payment or its enforcement.',
    },
  },
  {
    slug: 'terminal-pasajeros-puerto-buquebus',
    emoji: '⛴️',
    theme: 'transporte',
    period: '1995-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'US$ 65,6 millones de inversión y una concesión de 50 años según Búsqueda (11/6/2026); la misma publicación había informado el 30/4/2026 que la iniciativa involucraría una inversión del orden de los US$ 100 millones',
    organisms: ['Administración Nacional de Puertos', 'Ministerio de Transporte y Obras Públicas'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Administración Nacional de Puertos',
        'Ministerio de Transporte y Obras Públicas',
      ],
      search: 'terminal de pasajeros',
      yearFrom: 1995,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Montevideo Portal', title: 'Tribunal de Cuentas se mantiene firme (objeción a la prórroga de la concesión de Buquebus)', url: 'https://www.montevideo.com.uy/Noticias/TRIBUNAL-DE-CUENTAS-SE-MANTIENE-FIRME-uc23899', date: '2005-11-03' },
      { outlet: 'Montevideo Portal', title: 'Tribunal de lo Contencioso Administrativo rechazó recurso presentado por Buquebus', url: 'https://www.montevideo.com.uy/Noticias/Tribunal-de-lo-Contencioso-Administrativo-rechazo-recurso-presentado-por-Buquebus-uc675095', date: '2018-02-15' },
      { outlet: 'El Observador', title: 'Gobierno analiza nueva iniciativa de Buquebus para terminal en puerto de Montevideo y evalúa retomar la concesión', url: 'https://www.elobservador.com.uy/nota/gobierno-analiza-nueva-iniciativa-de-buquebus-para-terminal-en-puerto-de-montevideo-y-evalua-retomar-la-concesion--202352318530', date: '2023-05-24' },
      { outlet: 'Búsqueda', title: 'ANP dio visto bueno al proyecto de Buquebus para la concesión de la terminal de pasajeros y cruceristas', url: 'https://www.busqueda.com.uy/economia/anp-dio-visto-bueno-proyecto-buquebus-concesion-terminal-pasajeros-y-cruceristas-n5412647', date: '2026-04-30' },
      { outlet: 'Búsqueda', title: 'Buquebus plantea invertir US$ 66 millones en modernizar la terminal de Montevideo y reconstruir el muelle Maciel', url: 'https://www.busqueda.com.uy/economia/buquebus-plantea-invertir-us-66-millones-modernizar-terminal-montevideo-y-reconstruir-muelle-maciel-n5414067', date: '2026-06-11' },
    ],
    es: {
      title: 'La terminal de pasajeros del puerto y la vuelta de Buquebus',
      dek: 'El Tribunal de Cuentas objetó la prórroga en 2005 y la concesión no se renovó en 2015; en 2026 la ANP declaró de interés una iniciativa privada de la misma empresa por 50 años.',
      contexto: 'La terminal fluvio-marítima de pasajeros del puerto de Montevideo fue operada por Buquebus desde mediados de los años noventa: Montevideo Portal informó en noviembre de 2005 que la empresa había firmado el contrato por diez años en octubre de 1995, y El Observador consignó en 2023 que la concesión la ostentaba desde 1994. El último gobierno del Frente Amplio no la renovó en 2015; el dueño de la empresa, Juan Carlos López Mena, terminó llevando el caso sin éxito al Tribunal de lo Contencioso Administrativo. En 2023 la empresa presentó una iniciativa privada para volver a hacerse cargo de la terminal, y el entonces ministro de Transporte, José Luis Falero, confirmó haberla recibido: "presentaron una iniciativa más segura que incluye también una salida para los cruceristas".',
      hallazgo: 'En noviembre de 2005 el Tribunal de Cuentas mantuvo por cuatro votos contra dos su objeción a la prórroga: sostuvo que el acuerdo entre la ANP y la empresa no tenía valor legal "porque no es competencia de la ANP otorgar extensiones en concesiones", y argumentó que "la oferta inversora para estos próximos diez años es considerablemente menor a cuando se firmó el contrato" (Montevideo Portal). En febrero de 2018 el Tribunal de lo Contencioso Administrativo rechazó el recurso de la empresa contra la decisión de no renovar y llamar a nueva licitación, al entender que "no se advierte violación alguna al debido proceso". Búsqueda informó el 30 de abril de 2026 que la ANP declaró de interés la iniciativa privada de Buquebus por resolución fechada el 26 de marzo y encomendó elaborar el pliego de condiciones particulares para un llamado a licitación pública, y que el proyecto involucraría una inversión del orden de los US$ 100 millones; el 11 de junio de 2026 el mismo medio precisó que la empresa plantea una inversión de US$ 65,6 millones y un plazo de 50 años de concesión.',
      statusNote: 'Según Búsqueda, la ANP encomendó al Área Comercialización elaborar el pliego para el llamado a licitación pública de la concesión. El proyecto incluye la restauración de la terminal histórica, la reconstrucción del muelle Maciel —de 380 metros de largo, construido en 1928, con un costo estimado de US$ 25 millones y por etapas para no interrumpir la operativa— y una conexión entre el puerto y la ciudad que debería definirse entre el año cero y el año tres de la concesión, comenzar a más tardar en el año tres y terminar antes del año seis. Al cierre de esta ficha (agosto de 2026) no constan novedades posteriores al 11 de junio de 2026 ni un llamado publicado.',
      porQueImporta: 'La terminal es la puerta de entrada de quienes cruzan el Río de la Plata y de los cruceristas, y es un bien público que quedaría comprometido por medio siglo. Que el proyecto lo proponga el mismo operador que dejó la concesión en 2015 hace que las condiciones del futuro llamado —y cuánto cobra el Estado por el uso— sean lo que hay que mirar.',
      caveat: 'Una concesión de obra pública no genera pagos del Estado a un proveedor, así que no aparece como contrato en los datos abiertos. Si la ANP llega a llamar a licitación, ese llamado sí debería quedar registrado; las cifras de inversión son las declaradas por la empresa y difieren entre las dos notas de Búsqueda de 2026.',
    },
    en: {
      title: 'The port passenger terminal and Buquebus\'s return',
      dek: 'The Court of Auditors objected to the extension in 2005 and the concession was not renewed in 2015; in 2026 the ports authority declared a 50-year private initiative from the same firm to be of interest.',
      contexto: 'Montevideo port\'s river-and-sea passenger terminal was operated by Buquebus from the mid-1990s: Montevideo Portal reported in November 2005 that the company had signed the ten-year contract in October 1995, and El Observador noted in 2023 that it had held the concession since 1994. The last Frente Amplio government did not renew it in 2015; the company\'s owner, Juan Carlos López Mena, ended up taking the case unsuccessfully to the Administrative Court. In 2023 the company filed a private initiative to take the terminal back, and then transport minister José Luis Falero confirmed receiving it: "they presented a safer initiative that also includes an exit for cruise passengers".',
      hallazgo: 'In November 2005 the Court of Auditors upheld its objection to the extension by four votes to two: it held that the agreement between ANP and the company had no legal validity "because granting concession extensions is not within ANP\'s competence", and argued that "the investment offer for these next ten years is considerably lower than when the contract was signed" (Montevideo Portal). In February 2018 the Administrative Court rejected the company\'s appeal against the decision not to renew and to call a new tender, finding that "no violation of due process is apparent". Búsqueda reported on 30 April 2026 that ANP declared Buquebus\'s private initiative to be of interest by a resolution dated 26 March and instructed staff to draw up the particular conditions document for a public tender, and that the project would involve investment on the order of US$100 million; on 11 June 2026 the same outlet specified that the company proposes an investment of US$65.6 million and a 50-year concession term.',
      statusNote: 'According to Búsqueda, ANP instructed its Commercialisation Area to prepare the tender document for a public call for the concession. The project includes restoring the historic terminal, rebuilding the Maciel pier — 380 metres long, built in 1928, at an estimated US$25 million and in phases so as not to interrupt operations — and a port-to-city connection that should be defined between year zero and year three of the concession, begin no later than year three and finish before year six. As of this file\'s closing (August 2026) there are no developments after 11 June 2026 and no published tender.',
      porQueImporta: 'The terminal is the gateway for those crossing the Río de la Plata and for cruise passengers, and it is a public asset that would be committed for half a century. That the project is proposed by the same operator that left the concession in 2015 makes the terms of the future tender — and how much the state charges for the use — the thing to watch.',
      caveat: 'A public works concession does not generate state payments to a supplier, so it does not appear as a contract in the open data. If ANP does call a tender, that call should be recorded; the investment figures are those declared by the company and differ between the two 2026 Búsqueda reports.',
    },
  },
  {
    slug: 'reforma-transporte-metropolitano-brt',
    emoji: '🚏',
    theme: 'transporte',
    period: '2025-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'Línea de crédito del BID por US$ 500 millones, con una primera operación de US$ 10 millones; escenarios de obra de entre US$ 209 y US$ 254 millones sin IVA',
    organisms: ['Ministerio de Transporte y Obras Públicas', 'Intendencia de Montevideo', 'Intendencia de Canelones', 'Intendencia de San José', 'Ministerio de Economía y Finanzas'],
    feedCoverage: 'partial',
    sources: [
      { outlet: 'El Observador', title: 'BID aprueba línea de crédito de US$ 500 millones para transformar el sistema de transporte de Montevideo', url: 'https://www.elobservador.com.uy/nacional/bid-aprueba-financiamiento-us-500-millones-transformar-el-sistema-transporte-montevideo-n6026030', date: '2025-11-26' },
      { outlet: 'El Observador', title: 'Gobierno consigue los fondos para la reforma del transporte: cerró con el BID, está en trámites con la CAF y el Banco Mundial', url: 'https://www.elobservador.com.uy/nacional/gobierno-consigue-los-fondos-la-reforma-del-transporte-cerro-el-bid-esta-tramites-la-caf-y-del-banco-mundial-n6026092', date: '2025-11-27' },
      { outlet: 'Ministerio de Transporte y Obras Públicas', title: 'Primer paso hacia la transformación del transporte público metropolitano', url: 'https://www.gub.uy/ministerio-transporte-obras-publicas/comunicacion/noticias/primer-paso-hacia-transformacion-del-transporte-publico-metropolitano', date: '2025-12-01' },
      { outlet: 'Montevideo Portal', title: 'Proyecto de transporte metropolitano: los escenarios posibles, costos y sus riesgos', url: 'https://www.montevideo.com.uy/Noticias/Proyecto-de-transporte-metropolitano-los-escenarios-posibles-costos-y-sus-riesgos-uc952909', date: '2026-02-12' },
    ],
    es: {
      title: 'US$ 500 millones del BID para el ómnibus rápido de Montevideo',
      dek: 'El BID abrió una línea de crédito para un sistema de ómnibus rápidos eléctricos en 8 de Octubre y avenida Italia; los estudios manejan obras de entre US$ 209 y US$ 254 millones.',
      contexto: 'En noviembre de 2025 el Banco Interamericano de Desarrollo aprobó una Línea de Crédito Condicional para Proyectos de Inversión por US$ 500 millones para transformar el sistema de transporte de Montevideo. El proyecto es un sistema de ómnibus rápidos eléctricos sobre dos corredores troncales —avenida 8 de Octubre y avenida Italia— con estaciones modernas, carriles exclusivos segregados, pasos a desnivel en los cruces principales, un tramo subterráneo en la avenida 18 de Julio y una terminal intercambiadora en Tres Cruces. Lo impulsan el Ministerio de Transporte y Obras Públicas junto a las intendencias de Montevideo, Canelones y San José, según el propio MTOP; El Observador informó que beneficiaría directamente a 1,3 millones de habitantes de la zona.',
      hallazgo: 'Los primeros US$ 10 millones otorgados por el BID se destinan a estudios de preinversión —la red de semáforos, simulaciones del tránsito particular, análisis de frecuencias y tiempos de viaje— necesarios para preparar los pliegos, según informó el MTOP el 1° de diciembre de 2025. El Observador publicó el 27 de noviembre de 2025 que el resto de la inversión se buscará con la CAF y el Banco Mundial, con trámites ya iniciados; que una propuesta del Cinve de octubre de 2024 planteaba una inversión de US$ 528 millones, cifra no confirmada oficialmente por las autoridades; y que la ministra Lucía Etcheverry dijo que "ojalá" las licitaciones se puedan hacer "en los últimos meses" de 2026. En febrero de 2026 Montevideo Portal difundió los estudios técnicos: cuatro escenarios sin IVA —US$ 209 millones las obras básicas, US$ 218 millones con Ricaldoni, US$ 245 millones con el subterráneo de 18 de Julio entre Arenal Grande y Tres Cruces y US$ 254 millones con todas las intervenciones opcionales— más factores de incertidumbre que el propio documento admite que se afinarán en etapas posteriores: servicios "no detectados o mal registrados" que podrían exigir desvíos costosos durante la obra, condiciones climáticas "adversas" y excavaciones en zonas con edificaciones próximas.',
      statusNote: 'Según Montevideo Portal, el 6 de febrero de 2026 empezó a funcionar una Unidad Transitoria integrada por representantes del MTOP, de las intendencias de Montevideo, Canelones y San José y del Ministerio de Economía, que debe derivar en la creación de la Agencia del Sistema de Transporte Metropolitano. Los estudios técnicos con los cuatro escenarios de costo se divulgaron ese mismo mes. Al cierre de esta ficha (agosto de 2026) no constan en las fuentes consultadas un llamado a licitación publicado ni la confirmación del escenario elegido.',
      porQueImporta: 'Es la obra de transporte más grande que Montevideo tiene por delante y se va a pagar con deuda de largo plazo: quien viaja hoy y quien pague impuestos dentro de dos décadas quedan comprometidos por la misma decisión. Seguir de cerca los pliegos, el escenario elegido y los eventuales sobrecostos desde el principio es la única forma de que el costo final no se conozca recién al final.',
      caveat: 'Todavía no hay obra adjudicada: lo que puede aparecer en los datos abiertos son las consultorías y estudios de preinversión que contraten el MTOP y las intendencias. Los montos de los escenarios son estimaciones de los estudios técnicos, no precios contratados.',
    },
    en: {
      title: 'US$500 million from the IDB for Montevideo\'s rapid bus system',
      dek: 'The IDB opened a credit line for an electric bus rapid transit system on 8 de Octubre and Avenida Italia; studies put the works at between US$209 and US$254 million.',
      contexto: 'In November 2025 the Inter-American Development Bank approved a US$500 million Conditional Credit Line for Investment Projects to transform Montevideo\'s transport system. The project is an electric bus rapid transit system on two trunk corridors — Avenida 8 de Octubre and Avenida Italia — with modern stations, segregated exclusive lanes, grade separations at the main junctions, an underground stretch on Avenida 18 de Julio and an interchange terminal at Tres Cruces. It is driven by the Ministry of Transport and Public Works together with the departmental governments of Montevideo, Canelones and San José, according to the ministry itself; El Observador reported it would directly benefit 1.3 million inhabitants of the area.',
      hallazgo: 'The first US$10 million granted by the IDB goes to pre-investment studies — the traffic-light network, simulations of private traffic, analysis of service frequencies and travel times — needed to prepare the tender documents, as the transport ministry reported on 1 December 2025. El Observador reported on 27 November 2025 that the rest of the investment will be sought from CAF and the World Bank, with procedures already under way; that an October 2024 proposal by Cinve put the investment at US$528 million, a figure not officially confirmed by the authorities; and that minister Lucía Etcheverry said she hoped the tenders could be held "in the final months" of 2026. In February 2026 Montevideo Portal published the technical studies: four scenarios excluding VAT — US$209 million for the basic works, US$218 million with Ricaldoni, US$245 million with the 18 de Julio underground stretch from Arenal Grande to Tres Cruces, and US$254 million with all optional interventions — plus uncertainty factors the document itself says will be refined at later stages: utilities "undetected or badly recorded" that could force costly diversions during construction, "adverse" weather conditions, and excavation in areas with nearby buildings.',
      statusNote: 'According to Montevideo Portal, on 6 February 2026 a Transitional Unit began operating, made up of representatives of the transport ministry, the departmental governments of Montevideo, Canelones and San José, and the Ministry of Economy, which is to lead to the creation of the Metropolitan Transport System Agency. The technical studies with the four cost scenarios were released that same month. As of this file\'s closing (August 2026), the sources consulted show no published tender and no confirmation of the chosen scenario.',
      porQueImporta: 'It is the largest transport project ahead of Montevideo and it will be paid for with long-term debt: today\'s passenger and whoever pays taxes two decades from now are committed by the same decision. Tracking the tender documents, the chosen scenario and any overruns from the outset is the only way to avoid learning the final cost only at the end.',
      caveat: 'No works have been awarded yet: what may appear in the open data are the consultancies and pre-investment studies contracted by the transport ministry and the departmental governments. The scenario figures are estimates from the technical studies, not contracted prices.',
    },
  },
]
