import type { CasoDef } from '../types'

/**
 * vivienda — 10 dossiers, 7 of them with a live cross-reference.
 *
 * Every source URL was fetched and every query was resolved against the live
 * collection before this file was committed (scripts/verify-casos.ts re-checks
 * both). A caso with no `query` is not a gap in the research: its money does
 * not travel through the Compras Estatales feed at all, which `feedCoverage`
 * records and the page states outright.
 */
export const CASOS_VIVIENDA: CasoDef[] = [
  {
    slug: 'plan-juntos-auditoria-controles-fondos',
    emoji: '🏚️',
    theme: 'vivienda',
    period: '2019-2024',
    statusKind: 'auditoria',
    status: 'auditoria',
    organisms: ['Ministerio de Vivienda y Ordenamiento Territorial'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Dirección Nacional de Medio Ambiente',
        'Dirección General de Secretaría',
        'Dirección Nacional de Vivienda',
        'Dirección Nacional de Ordenamiento Territorial',
        'Dirección Nacional de Aguas y Saneamiento',
        'Dirección Nacional de Integración Social y Urbana',
      ],
      search: 'vivienda',
      yearFrom: 2019,
      yearTo: 2024,
    },
    sources: [
      { outlet: 'Montevideo Portal', title: 'Ausencia de controles y uso inadecuado de fondos: debilidades del Plan Juntos de Vivienda', url: 'https://www.montevideo.com.uy/Noticias/Ausencia-de-controles-y-uso-inadecuado-de-fondos-debilidades-del-Plan-Juntos-de-Vivienda-uc840551', date: '2022-12-14' },
      { outlet: 'la diaria', title: 'Auditoría identificó «ausencia de controles» y falta de «uso adecuado de los fondos» en el Plan Juntos', url: 'https://ladiaria.com.uy/politica/articulo/2022/12/auditoria-identifico-ausencia-de-controles-y-falta-de-uso-adecuado-de-los-fondos-en-el-plan-juntos/', date: '2022-12-15' },
      { outlet: 'la diaria', title: 'FA realizará pedido de informes por irregularidades en el Plan Juntos', url: 'https://ladiaria.com.uy/politica/articulo/2022/12/fa-realizara-pedido-de-informes-por-irregularidades-en-el-plan-juntos/', date: '2022-12-16' },
      { outlet: 'Auditoría Interna de la Nación (Ministerio de Economía y Finanzas)', title: 'Informe de auditoría (actuación de seguimiento) — MVOT, Plan Nacional de Integración Socio-Habitacional Juntos', url: 'https://www.gub.uy/ministerio-economia-finanzas/sites/ministerio-economia-finanzas/files/documentos/publicaciones/2025-MinisteriodeViviendaYOrdenamientoTerritorial_PlanNacionalDeIntegraci%C3%B3nSocioHabitacionalJuntos%20%28Plan%20Juntos%29.pdf', date: '2024-09' },
    ],
    es: {
      title: 'Plan Juntos: riesgo extremo en el manejo de fondos, según la AIN',
      dek: 'La Auditoría Interna de la Nación revisó el plan de vivienda entre 2019 y 2021 y no encontró ningún hallazgo de riesgo bajo: dos de los ocho quedaron en riesgo extremo.',
      contexto: 'El Plan Nacional de Integración Socio-Habitacional Juntos fue creado en 2011, durante el gobierno de José Mujica, para atender la emergencia socio-habitacional de familias en situación de pobreza extrema. Construye y mejora viviendas con trabajo de los propios participantes y compra de materiales. Se ejecuta bajo la órbita de la Dirección Nacional de Integración Social y Urbana (Dinisu), unidad ejecutora del Ministerio de Vivienda y Ordenamiento Territorial (MVOT), mediante un fideicomiso de administración. Es, junto con el Plan Avanzar, uno de los principales instrumentos estatales de intervención en asentamientos.',
      hallazgo: 'La Auditoría Interna de la Nación (AIN), del Ministerio de Economía y Finanzas, auditó el período enero de 2019 a diciembre de 2021 —dejando expresamente fuera del análisis la selección de los participantes y la ejecución de las obras—. Su informe se aprobó por resolución del 30 de noviembre de 2022 y se conoció en diciembre de ese año. Según la diaria, ninguno de los ocho hallazgos quedó calificado como riesgo bajo: dos fueron «extremos», tres altos y tres medios. Los dos extremos, según el propio informe, son el Registro Único de Participantes del Plan Juntos (RUPP) y la rendición de gastos. Montevideo Portal informó que el documento señaló «ausencia de controles y aprobación de actividades clave» por parte del MVOT como órgano ejecutor, el uso de cajas chicas y vales sociales transferidos a cuentas personales en lugar de institucionales, y la ausencia de actas que respalden el accionar del Comité Técnico. El informe consigna que el organismo es consciente de parte de esas debilidades y que venía realizando acciones de mejora: el desarrollo de un Sistema Integral de Información (SIIJU), la uniformización del modelo constructivo y la incorporación del sistema K2B para el registro y aprobación de las rendiciones.',
      statusNote: 'La AIN hizo una actuación de seguimiento con alcance hasta mayo de 2024, fechada en setiembre de 2024: de los ocho hallazgos originales, uno figura implementado, dos parcialmente implementados, cuatro en proceso y en uno la organización asume el riesgo. La criticidad del registro de participantes bajó de «extremo» a «alto», mientras que la rendición de gastos siguió calificada como «extremo». El SIIJU ya funcionaba para el proceso de selección de familias, pero continuaba en etapa de desarrollo, con finalización prevista para setiembre de 2024. La AIN recomendó continuar las acciones iniciadas. Al cierre de esta ficha (agosto de 2026) no constan informes posteriores de la AIN sobre el plan.',
      porQueImporta: 'El Plan Juntos maneja plata pública para construir la vivienda de las familias más pobres del país. Si los materiales se compran sin un sistema integral que permita seguir su trazabilidad y los fondos pasan por cuentas personales, no hay forma de saber cuánta casa se levantó por cada peso gastado ni de detectar sobreprecios. La auditoría no afirma que haya habido desvíos: dice que los controles no permitían asegurarlo.',
      caveat: 'El plan se ejecuta mediante un fideicomiso de administración, que contrata fuera del canal habitual de compras estatales. Lo que aparece en el buscador es lo que el MVOT compró a su nombre, no necesariamente todo el gasto del plan.',
    },
    en: {
      title: 'Plan Juntos: extreme risk in fund handling, national audit found',
      dek: 'Uruguay\'s national internal audit office reviewed the housing plan for 2019-2021 and found no low-risk item: two of the eight were rated extreme risk.',
      contexto: 'The Plan Nacional de Integración Socio-Habitacional Juntos was created in 2011, under José Mujica\'s government, to address the socio-housing emergency of families living in extreme poverty. It builds and upgrades homes using the participants\' own labour plus purchased materials. It runs under the National Directorate of Social and Urban Integration (Dinisu), an executing unit of the Ministry of Housing and Territorial Planning (MVOT), through an administration trust. Along with Plan Avanzar, it is one of the State\'s main instruments for intervening in informal settlements.',
      hallazgo: 'The Auditoría Interna de la Nación (AIN), part of the Ministry of Economy and Finance, audited the period from January 2019 to December 2021 — expressly excluding participant selection and works execution from its analysis. Its report was approved by resolution of 30 November 2022 and became known in December that year. According to la diaria, none of the eight findings was rated low risk: two were "extreme", three high and three medium. The two extreme ones, according to the report itself, are the Plan Juntos Single Participant Registry (RUPP) and expense reporting. Montevideo Portal reported that the document flagged an "absence of controls and approval of key activities" by the MVOT as executing body, the use of petty cash and social vouchers transferred to personal rather than institutional accounts, and the absence of minutes documenting the Technical Committee\'s actions. The report records that the body is aware of some of those weaknesses and had been taking corrective steps: developing an Integrated Information System (SIIJU), standardising the construction model, and adopting the K2B system for recording and approving expense reports.',
      statusNote: 'The AIN carried out a follow-up covering up to May 2024, dated September 2024: of the eight original findings, one is recorded as implemented, two partially implemented, four in process, and for one the organisation accepts the risk. The participant registry\'s rating dropped from "extreme" to "high", while expense reporting remained rated "extreme". The SIIJU was already running for the family selection process but was still under development, with completion expected in September 2024. The AIN recommended continuing the actions begun. As of this file\'s closing (August 2026) there are no later AIN reports on the plan.',
      porQueImporta: 'Plan Juntos handles public money to build homes for the country\'s poorest families. If materials are bought without an integrated system that allows their traceability to be followed, and funds pass through personal accounts, there is no way to know how much house was built per peso spent, nor to detect overpricing. The audit does not claim money was diverted: it says the controls did not allow that to be assured.',
      caveat: 'The plan is executed through an administration trust, which contracts outside the usual state procurement channel. What shows up in the search engine is what the MVOT bought in its own name, not necessarily the plan\'s full spending.',
    },
  },
  {
    slug: 'irene-moreira-adjudicaciones-directas-viviendas',
    emoji: '🔑',
    theme: 'vivienda',
    period: '2020-2026',
    statusKind: 'auditoria',
    status: 'investigacion',
    organisms: ['Ministerio de Vivienda y Ordenamiento Territorial', 'Agencia Nacional de Vivienda'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Dirección Nacional de Medio Ambiente',
        'Dirección General de Secretaría',
        'Dirección Nacional de Vivienda',
        'Dirección Nacional de Ordenamiento Territorial',
        'Dirección Nacional de Aguas y Saneamiento',
        'Dirección Nacional de Integración Social y Urbana',
        'Agencia Nacional de Vivienda',
      ],
      search: 'vivienda',
      yearFrom: 2020,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'El Observador', title: 'El Ministerio de Vivienda puso en suspenso la entrega de un apartamento a una militante de Cabildo Abierto', url: 'https://www.elobservador.com.uy/nota/el-ministerio-de-vivienda-puso-en-suspenso-la-entrega-de-un-apartamento-a-una-militante-de-cabildo-abierto-202352416289', date: '2023-05-24' },
      { outlet: 'la diaria', title: 'Plantean que la Jutep analice la conducta de Irene Moreira en adjudicación de vivienda a una militante de su partido', url: 'https://ladiaria.com.uy/politica/articulo/2023/5/plantean-que-la-jutep-analice-la-conducta-de-irene-moreira-en-adjudicacion-de-vivienda-a-una-militante-de-su-partido/', date: '2023-05-05' },
      { outlet: 'Montevideo Portal', title: 'Adjudicación directa de Irene Moreira no sería la única: existen por lo menos dos más', url: 'https://www.montevideo.com.uy/Noticias/Adjudicacion-directa-de-Irene-Moreira-no-seria-la-unica-existen-por-lo-menos-dos-mas-uc853102', date: '2023-05-05' },
      { outlet: 'la diaria', title: 'Adjudicación de viviendas: Moreira «no se ajustó a derecho ni a la ética», señala investigación administrativa del MVOT', url: 'https://ladiaria.com.uy/politica/articulo/2024/3/adjudicacion-de-viviendas-moreira-no-se-ajusto-a-derecho-ni-a-la-etica-senala-investigacion-administrativa-del-mvot/', date: '2024-03-08' },
      { outlet: 'Subrayado', title: 'Adjudicación de viviendas por Irene Moreira «no fue ilegítimo», pero hubo irregularidades, dijo Lozano', url: 'https://www.subrayado.com.uy/adjudicacion-viviendas-irene-moreira-no-fue-ilegitimo-pero-hubo-irregularidades-dijo-lozano-n939925', date: '2024-03-01' },
      { outlet: 'Telenoche', title: 'Jutep analiza informe sobre adjudicación de viviendas durante la gestión de Irene Moreira', url: 'https://www.telenoche.com.uy/nacionales/jutep-analiza-informe-adjudicacion-viviendas-la-gestion-irene-moreira-n5397520', date: '2026-03-25' },
    ],
    es: {
      title: 'Viviendas adjudicadas a dedo: la salida de la ministra Irene Moreira',
      dek: 'El Ministerio de Vivienda tramitó 12 adjudicaciones directas entre 2020 y 2023; una fue para una militante de Cabildo Abierto y le costó el cargo a la ministra.',
      contexto: 'Irene Moreira, de Cabildo Abierto, fue ministra de Vivienda y Ordenamiento Territorial entre 2020 y mayo de 2023, durante el gobierno de Luis Lacalle Pou. Las viviendas del Estado se adjudican normalmente por sorteo entre los postulantes que cumplen los requisitos, a cargo de la Agencia Nacional de Vivienda (ANV). En mayo de 2023 se conoció que la ministra había adjudicado en forma directa un apartamento del complejo de Nueva York y Yí, en Montevideo, a Mónica Píriz, militante de Cabildo Abierto, usando una reserva de cupo en lugar del sorteo que la ANV había realizado a mediados de 2022, según informó El Observador. Píriz cumplía los requisitos para participar en ese sorteo.',
      hallazgo: 'El Observador informó que la adjudicación se hizo mediante una reserva de cupo y que el ministerio puso en suspenso la entrega, prevista para el 25 de mayo de 2023, cuando estalló la polémica. Montevideo Portal informó que hubo por lo menos tres adjudicaciones directas —dos de ellas no vinculadas a militantes cabildantes— y que la comisión que Moreira mencionó como respaldo se ocupa de subsidios de alquiler ante situaciones de emergencia crítica, órgano que ni analizó el caso ni tuvo noticia de que existieran adjudicaciones directas. La investigación administrativa del propio MVOT, difundida en marzo de 2024, concluyó que la conducta de la ministra «no se ajustó a derecho ni a la ética» y que, con el trámite discrecional de 12 solicitudes de vivienda, «se vulneraron los principios de imparcialidad e igualdad de oportunidades», según la diaria. Su sucesor, Raúl Lozano, dijo a Subrayado que el mecanismo existía por una resolución de 2009 y que el acto «no fue ilegítimo», pero que ninguno de los 12 casos tramitados entre 2020 y 2023 se ajustó a los procedimientos ni a los criterios de esa norma; de esos 12, dos fueron adjudicaciones con opción a compra, cinco temporarias por 12 meses y dos se concretaron por situaciones de violencia de género.',
      statusNote: 'Lacalle Pou le pidió la renuncia a comienzos de mayo de 2023 y Moreira volvió al Senado; Raúl Lozano asumió el ministerio ese mismo mes. La Junta de Transparencia y Ética Pública (Jutep) había sido convocada a analizar el caso en mayo de 2023 por su vocal Ana Ferraris, en representación del Frente Amplio, que planteó que se podría estar «ante una conducta reñida con el régimen jurídico vigente en materia de uso indebido del poder público». Según Telenoche, en marzo de 2026 la dirección jurídica de la Jutep concluyó que hubo un apartamiento de los principios de imparcialidad, objetividad e igualdad, y el organismo quedó a la espera de los descargos de Moreira para emitir un dictamen. Al cierre de esta ficha (agosto de 2026) no consta que la Jutep haya resuelto.',
      porQueImporta: 'Cada vivienda entregada fuera del sorteo es una vivienda que no recibió alguien que esperó su turno cumpliendo los requisitos. El caso muestra que el criterio de asignación —y no solo el precio de la obra— define quién accede a un bien que pagaron todos los contribuyentes.',
      caveat: 'Lo que se cuestiona es la asignación de viviendas ya construidas, no una compra. En el buscador se pueden ver las obras y los complejos que el MVOT y la ANV contrataron, pero no a quién se le adjudicó cada unidad.',
    },
    en: {
      title: 'Homes handed out off the list: the exit of minister Irene Moreira',
      dek: 'The Housing Ministry processed 12 direct allocations between 2020 and 2023; one went to a Cabildo Abierto activist and cost the minister her job.',
      contexto: 'Irene Moreira, of Cabildo Abierto, was Minister of Housing and Territorial Planning from 2020 to May 2023, under Luis Lacalle Pou\'s government. State housing is normally allocated by lottery among applicants who meet the requirements, run by the National Housing Agency (ANV). In May 2023 it emerged that the minister had directly allocated an apartment in the Nueva York and Yí complex in Montevideo to Mónica Píriz, a Cabildo Abierto activist, using a reserved quota instead of the lottery the ANV had held in mid-2022, El Observador reported. Píriz met the requirements to take part in that lottery.',
      hallazgo: 'El Observador reported that the allocation used a reserved quota and that the ministry suspended the handover, scheduled for 25 May 2023, once the controversy broke. Montevideo Portal reported there were at least three direct allocations — two of them not linked to Cabildo Abierto activists — and that the commission Moreira cited as backing deals with rent subsidies in critical emergency situations, a body that neither reviewed the case nor was aware that direct allocations existed. The MVOT\'s own administrative investigation, made public in March 2024, concluded that the minister\'s conduct "did not conform to the law or to ethics" and that, through the discretionary handling of 12 housing requests, "the principles of impartiality and equal opportunity were violated", according to la diaria. Her successor, Raúl Lozano, told Subrayado that the mechanism existed under a 2009 resolution and that the act "was not illegitimate", but that none of the 12 cases processed between 2020 and 2023 followed that rule\'s procedures or criteria; of those 12, two were allocations with an option to buy, five were temporary for 12 months, and two went ahead on grounds of gender violence.',
      statusNote: 'Lacalle Pou asked for her resignation in early May 2023 and Moreira returned to the Senate; Raúl Lozano took over the ministry that same month. The Public Transparency and Ethics Board (Jutep) had been asked to examine the case in May 2023 by board member Ana Ferraris, representing the Frente Amplio, who argued this could amount to "conduct at odds with the legal regime on improper use of public power". According to Telenoche, in March 2026 the Jutep\'s legal division concluded there had been a departure from the principles of impartiality, objectivity and equality, and the body was awaiting Moreira\'s reply before issuing a ruling. As of this file\'s closing (August 2026) there is no record that the Jutep has ruled.',
      porQueImporta: 'Every home handed out outside the lottery is a home someone else did not get after waiting their turn and meeting the requirements. The case shows that the allocation criterion — not just the price of the works — determines who gets access to an asset paid for by all taxpayers.',
      caveat: 'What is questioned here is the allocation of already-built homes, not a purchase. The search engine shows the works and complexes contracted by the MVOT and the ANV, but not who each unit was allocated to.',
    },
  },
  {
    slug: 'mevir-auditoria-seleccion-participantes',
    emoji: '🚜',
    theme: 'vivienda',
    period: '2016-2023',
    statusKind: 'auditoria',
    status: 'auditoria',
    organisms: ['MEVIR - Dr. Alberto Gallinal Heber'],
    feedCoverage: 'partial',
    sources: [
      { outlet: 'Telenoche', title: 'Auditoría en Mevir detecta niveles críticos en gestión', url: 'https://www.telenoche.com.uy/nacionales/auditoria-mevir-detecta-niveles-criticos-gestion-n5327609', date: '2022-04-07' },
      { outlet: 'Auditoría Interna de la Nación (Ministerio de Economía y Finanzas)', title: 'Informe de auditoría — MEVIR Dr. Alberto Gallinal Heber', url: 'https://www.gub.uy/ministerio-economia-finanzas/sites/ministerio-economia-finanzas/files/documentos/publicaciones/2022_PDPNE-MEVIR-Dr.AlbertoGallinalHeber.pdf', date: '2022-03-23' },
      { outlet: 'Auditoría Interna de la Nación (Ministerio de Economía y Finanzas)', title: 'Informe de auditoría (actuación de seguimiento) — MEVIR Dr. Alberto Gallinal Heber', url: 'https://www.gub.uy/ministerio-economia-finanzas/sites/ministerio-economia-finanzas/files/documentos/noticias/2023_PDPNE-MEVIR-Dr.AlbertoGallinalHeber.pdf', date: '2023-10' },
    ],
    es: {
      title: 'Mevir: riesgo extremo en cómo se elige a quién se le da la casa',
      dek: 'La Auditoría Interna de la Nación calificó de extremo el riesgo en tres frentes de Mevir: la selección de participantes, el seguimiento posobra con la morosidad, y la concentración de funciones en la Gerencia Social.',
      contexto: 'Mevir - Dr. Alberto Gallinal Heber es una persona pública no estatal creada por el artículo 473 de la ley 13.640, del 26 de diciembre de 1967, para erradicar la vivienda insalubre rural; pasó a denominarse así por la ley 18.676 de 2010. Construye viviendas, edificaciones productivas, servicios comunitarios e infraestructura (agua, electricidad, saneamiento) en el medio rural y en pequeñas localidades, con aporte de trabajo de los propios participantes, y financia las casas con cuotas de hasta 25 años que los adjudicatarios devuelven, con una parte subsidiada. Trabaja con asalariados rurales y pequeños productores familiares de bajos recursos.',
      hallazgo: 'La Auditoría Interna de la Nación (AIN) evaluó los Programas de Vivienda Nucleada y Planta Urbana —selección de participantes, compras de materiales e insumos y seguimiento posobra— sobre los programas cuya entrega se dio entre 2016 y 2020, y firmó su informe el 23 de marzo de 2022. Calificó como riesgo «extremo» tres hallazgos: la concentración de funciones en la Gerencia Social, el proceso de selección y vinculación con los participantes, y el seguimiento posobra junto con la morosidad. Otros tres quedaron en «alto»: compras e inventario de materiales; la vinculación jerárquica de las unidades —que incluye la ausencia de una Unidad de Auditoría Interna, obligatoria según el artículo 239 de la ley 19.924—; y la toma de decisiones estratégicas. El informe concluyó que la gestión presentó debilidades de control interno que no permiten asegurar transparencia en la selección de los participantes ni en la definición de las cuotas y subsidios otorgados, coincidiendo con lo publicado por Telenoche. Sobre la morosidad, de una muestra de 189 cuentas activas, 32,80% superaba las seis cuotas impagas y 26,45% las doce —unos 3.164.960 pesos en este último caso—, y 8% del total superaba las 25 cuotas.',
      statusNote: 'En octubre de 2023 la AIN publicó la actuación de seguimiento, con alcance hasta mayo de 2023: de los seis hallazgos, cinco figuran con acciones implementadas y uno quedó como parcial —la vinculación jerárquica, con la conformación de la Unidad de Auditoría Interna todavía en proceso—, bajando su criticidad de «alto» a «medio». El informe registra que Mevir asignó la morosidad temprana a la Gerencia Contable y la morosidad crónica al área Jurídico-Notarial, que realiza las acciones judiciales, y que hubo nuevos procedimientos, cambios contractuales, instancias de transparencia en la selección de beneficiarios y digitalización de la información. Al cierre de esta ficha (agosto de 2026) no constan auditorías posteriores publicadas por el Ministerio de Economía sobre Mevir.',
      porQueImporta: 'Mevir construye la casa de familias rurales que no tienen otra opción y después les cobra la cuota. Si no se puede asegurar cómo se elige a quién entra y quién queda afuera, ni cobrar lo que se prestó, el dinero que debería volver para levantar la próxima tanda de viviendas no vuelve.',
      caveat: 'Mevir es una persona pública no estatal: parte de sus compras no se publica en el mismo canal que las de los ministerios, así que lo que aparece en el buscador puede ser solo una porción de lo que compra. La auditoría tampoco cubrió los Programas de Área Rural, los convenios ni las modalidades de refacción, saneamiento y readjudicación.',
    },
    en: {
      title: 'Mevir: extreme risk in how it picks who gets the house',
      dek: 'Uruguay\'s national internal audit office rated as extreme the risk on three fronts at Mevir: participant selection, post-construction follow-up with arrears, and the concentration of functions in its Social Management department.',
      contexto: 'Mevir - Dr. Alberto Gallinal Heber is a non-state public entity created by article 473 of law 13.640, of 26 December 1967, to eradicate substandard rural housing; it took its current name under law 18.676 of 2010. It builds homes, productive buildings, community services and infrastructure (water, electricity, sanitation) in rural areas and small towns, with labour contributed by the participants themselves, and finances the houses with instalments of up to 25 years that recipients repay, with part subsidised. It works with rural wage earners and low-income small family farmers.',
      hallazgo: 'The national internal audit office (AIN) assessed the Nucleated Housing and Urban Plot programmes — participant selection, purchasing of materials and supplies, and post-construction follow-up — covering programmes delivered between 2016 and 2020, and signed its report on 23 March 2022. It rated three findings as "extreme" risk: the concentration of functions in the Social Management department, the participant selection and contracting process, and post-construction follow-up together with arrears. Three more were rated "high": materials purchasing and inventory; the hierarchical structure of its units — which includes the absence of an Internal Audit Unit, mandatory under article 239 of law 19.924; and strategic decision-making. The report concluded that management showed internal control weaknesses that do not allow transparency to be assured in the selection of participants or in the setting of the instalments and subsidies granted, matching what Telenoche published. On arrears, out of a sample of 189 active accounts, 32.80% were more than six instalments behind and 26.45% more than twelve — some 3,164,960 pesos in the latter case — and 8% of the total were more than 25 instalments behind.',
      statusNote: 'In October 2023 the AIN published its follow-up, covering up to May 2023: of the six findings, five are recorded as having implemented actions and one remained partial — the hierarchical structure, with the Internal Audit Unit still being set up — lowering its rating from "high" to "medium". The report notes that Mevir assigned early arrears to its Accounting Management department and chronic arrears to its Legal-Notarial area, which handles court actions, and that there were new procedures, contractual changes, transparency steps in beneficiary selection and digitisation of information. As of this file\'s closing (August 2026) there are no later audits of Mevir published by the Ministry of Economy.',
      porQueImporta: 'Mevir builds homes for rural families with no other option and then charges them instalments. If there is no way to assure how it is decided who gets in and who is left out, nor to collect what was lent, the money that should come back to build the next batch of homes does not come back.',
      caveat: 'Mevir is a non-state public entity: some of its purchasing is not published through the same channel as ministries\', so what appears in the search engine may be only a portion of what it buys. The audit also did not cover the Rural Area programmes, the agreements, or the refurbishment, sanitation and reallocation schemes.',
    },
  },
  {
    slug: 'vivienda-promovida-exoneraciones-monoambientes',
    investigationPath: '/investigaciones/vivienda-promovida',
    emoji: '🏢',
    theme: 'vivienda',
    period: '2011-2026',
    statusKind: 'debate',
    status: 'debate',
    organisms: ['Ministerio de Vivienda y Ordenamiento Territorial', 'Agencia Nacional de Vivienda', 'Ministerio de Economía y Finanzas'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Dirección Nacional de Medio Ambiente',
        'Dirección General de Secretaría',
        'Dirección Nacional de Vivienda',
        'Dirección Nacional de Ordenamiento Territorial',
        'Dirección Nacional de Aguas y Saneamiento',
        'Dirección Nacional de Integración Social y Urbana',
        'Agencia Nacional de Vivienda',
        'Ministerio de Economía y Finanzas',
      ],
      search: 'vivienda',
      yearFrom: 2011,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'El Observador', title: 'Vivienda promovida: estudio cuestiona exoneraciones fiscales para la construcción de monoambientes', url: 'https://www.elobservador.com.uy/economia-y-empresas/vivienda-promovida-estudio-cuestiona-exoneraciones-fiscales-construccion-monoambientes-n6001803', date: '2025-05-30' },
      { outlet: 'la diaria', title: 'El 55,4% de los apartamentos nuevos para vivienda construidos en Montevideo en 2025 tienen menos de 40 metros cuadrados', url: 'https://ladiaria.com.uy/politica/articulo/2026/6/el-554-de-los-apartamentos-nuevos-para-vivienda-construidos-en-montevideo-en-2025-tienen-menos-de-40-metros-cuadrados/', date: '2026-06-11' },
      { outlet: 'Ministerio de Economía y Finanzas', title: 'Montos de exoneraciones fiscales en el régimen previsto en el artículo 4 de la Ley 18.795, vivienda promovida (pedido de informes)', url: 'https://www.gub.uy/ministerio-economia-finanzas/institucional/informacion-gestion/pedidos-informes/montos-exoneraciones-fiscales-regimen-previsto', date: '2026-05-14' },
      { outlet: 'la diaria', title: 'Ministerio de Vivienda aplicará parte de la Ley de Vivienda Promovida mediante el programa Entre Todos y delegará otras funciones al MEF', url: 'https://ladiaria.com.uy/politica/articulo/2025/8/ministerio-de-vivienda-aplicara-parte-de-la-ley-de-vivienda-promovida-mediante-el-programa-entre-todos-y-delegara-otras-funciones-al-mef/', date: '2025-08-14' },
    ],
    es: {
      title: 'Vivienda promovida: un estudio cuestiona la exoneración a los monoambientes',
      dek: 'La ley 18.795 exonera impuestos a promotores privados. Un estudio de la Udelar advierte que 61% de lo aprobado en Montevideo son monoambientes y unidades de un dormitorio.',
      contexto: 'La ley 18.795 creó el régimen de vivienda promovida, o de interés social: el Estado exonera impuestos a los promotores privados que construyan viviendas dentro de las condiciones que fija la normativa. Los tributos comprendidos incluyen el Impuesto a las Rentas de las Actividades Económicas (IRAE), el Impuesto al Patrimonio, el Impuesto a las Trasmisiones Patrimoniales y el Impuesto al Valor Agregado. No es un gasto directo sino renuncia fiscal: plata que el Estado deja de cobrar.',
      hallazgo: 'Las arquitectas Alina del Castillo y Graciela Lamoglie, de la Facultad de Arquitectura, Diseño y Urbanismo de la Udelar, estudiaron la producción de vivienda promovida en Montevideo y concluyeron, según El Observador, que entre abril de 2020 y diciembre de 2024 los monoambientes y las unidades de un dormitorio representaron 61% de lo aprobado: 11.674 unidades de un dormitorio (51%) y 2.268 monoambientes (10%). Sostienen que se debería regular el porcentaje de viviendas a promover según cantidad de dormitorios «para evitar que las intervenciones respondan solo a maximizar la rentabilidad del suelo», y advierten sobre una «impronta de transitoriedad» que no favorece el tejido social ni la diversidad poblacional de los barrios. la diaria informó en junio de 2026, con datos abiertos de la Dirección Nacional de Catastro procesados por la empresa uruguaya Mirando.ai, que 55,4% de los apartamentos nuevos para vivienda construidos en Montevideo en 2025 tienen menos de 40 metros cuadrados; el director nacional de Vivienda, Milton Machado, atribuyó la tendencia a un cambio cultural y estructural de las familias uruguayas y se manifestó contrario a que se prohíban por ley los monoambientes.',
      statusNote: 'El gobierno de Yamandú Orsi anunció en agosto de 2025, en la comisión de Vivienda de Diputados, que aplicará parte de la ley mediante el programa Entre Todos y delegará otras funciones en el Ministerio de Economía. El 14 de abril de 2026 el diputado Gustavo Salle Lorier presentó un pedido de informes al Ministerio de Economía por los montos exonerados entre 2012 y 2025 de IRAE, Impuesto al Patrimonio e Impuesto a las Trasmisiones Patrimoniales; en el escrito consigna que, consultado previamente, el Ministerio de Vivienda respondió que solo podía informar los montos de exoneración de IVA porque no poseía otros datos. El MEF contestó el 14 de mayo de 2026 remitiendo lo informado por la Dirección General Impositiva.',
      porQueImporta: 'Cada peso de impuesto que el Estado no cobra a un promotor es un peso que no está en el presupuesto de vivienda, salud o educación. La discusión no es si el régimen construyó —construyó decenas de miles de unidades—, sino si lo que se construyó es la vivienda que el país necesita y a qué precio fiscal. Que el propio Ministerio de Vivienda haya respondido que solo puede informar el IVA da la medida de lo difícil que es responder esa pregunta.',
      caveat: 'Esto es renuncia fiscal, no una compra del Estado: no genera contratos y por lo tanto no aparece en el buscador de compras estatales. Sí aparecen las obras de vivienda que el MVOT y la ANV contratan por su cuenta.',
    },
    en: {
      title: 'Promoted housing: a study questions the tax break for studio flats',
      dek: 'Law 18.795 grants tax exemptions to private developers. A University of the Republic study warns that 61% of what was approved in Montevideo is studios and one-bedroom flats.',
      contexto: 'Law 18.795 created the promoted (or social-interest) housing regime: the State waives taxes for private developers who build housing within the conditions the rules set. The taxes covered include corporate income tax (IRAE), wealth tax, property transfer tax and VAT. It is not direct spending but forgone revenue: money the State chooses not to collect.',
      hallazgo: 'Architects Alina del Castillo and Graciela Lamoglie, of the University of the Republic\'s Faculty of Architecture, Design and Urbanism, studied promoted housing output in Montevideo and concluded, according to El Observador, that between April 2020 and December 2024 studios and one-bedroom units made up 61% of what was approved: 11,674 one-bedroom units (51%) and 2,268 studios (10%). They argue that the share of housing promoted should be regulated by number of bedrooms "to prevent interventions from responding only to maximising land returns", and warn of a "stamp of transience" that does not favour social fabric or population diversity in neighbourhoods. la diaria reported in June 2026, using open data from the National Cadastre Directorate processed by the Uruguayan firm Mirando.ai, that 55.4% of new residential apartments built in Montevideo in 2025 are under 40 square metres; the national housing director, Milton Machado, attributed the trend to a cultural and structural change in Uruguayan families and said he was against banning studio flats by law.',
      statusNote: 'Yamandú Orsi\'s government announced in August 2025, before the Chamber of Deputies\' Housing Committee, that it will apply part of the law through the Entre Todos programme and delegate other functions to the Ministry of Economy. On 14 April 2026 deputy Gustavo Salle Lorier filed an information request with the Ministry of Economy for the amounts exempted between 2012 and 2025 under corporate income tax, wealth tax and property transfer tax; in the filing he records that, asked earlier, the Housing Ministry replied it could only report the VAT exemption amounts because it held no other data. The Ministry of Economy answered on 14 May 2026, forwarding what the tax office (DGI) had reported.',
      porQueImporta: 'Every peso of tax the State does not collect from a developer is a peso missing from the housing, health or education budget. The debate is not whether the regime built — it built tens of thousands of units — but whether what was built is the housing the country needs, and at what fiscal price. That the Housing Ministry itself answered it could only report VAT shows how hard that question is to answer.',
      caveat: 'This is forgone tax revenue, not a State purchase: it generates no contracts and therefore does not appear in the public procurement search engine. What does appear are the housing works the MVOT and the ANV contract directly.',
    },
  },
  {
    slug: 'entre-todos-viviendas-poblacion-objetivo',
    investigationPath: '/investigaciones/vivienda-promovida',
    emoji: '🏘️',
    theme: 'vivienda',
    period: '2022-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'US$ 90 millones de dotación inicial de la garantía SiGa Entre Todos, usada en solo 9 operaciones entre 2023 y 2025, por un promedio de US$ 233.000 (El Observador, agosto de 2025)',
    organisms: ['Ministerio de Vivienda y Ordenamiento Territorial', 'Agencia Nacional de Vivienda'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Dirección Nacional de Medio Ambiente',
        'Dirección General de Secretaría',
        'Dirección Nacional de Vivienda',
        'Dirección Nacional de Ordenamiento Territorial',
        'Dirección Nacional de Aguas y Saneamiento',
        'Dirección Nacional de Integración Social y Urbana',
        'Agencia Nacional de Vivienda',
      ],
      search: 'vivienda',
      yearFrom: 2022,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'la diaria', title: 'MVOT advierte que no todas las viviendas del programa Entre Todos fueron destinadas a la población objetivo y prepara varios cambios', url: 'https://ladiaria.com.uy/politica/articulo/2025/9/mvot-advierte-que-no-todas-las-viviendas-del-programa-entre-todos-fueron-destinadas-a-la-poblacion-objetivo-y-prepara-varios-cambios/', date: '2025-09-17' },
      { outlet: 'El Observador', title: 'Programa Entre Todos: el cambio que «apuesta» por empresas pequeñas en la construcción de viviendas', url: 'https://www.elobservador.com.uy/economia-y-empresas/programa-todos-el-cambio-apostar-empresas-pequenas-construccion-viviendas-n6013711', date: '2025-08-21' },
      { outlet: 'Ministerio de Vivienda y Ordenamiento Territorial', title: 'MVOT informa cambios en el programa Entre Todos', url: 'https://www.gub.uy/ministerio-vivienda-ordenamiento-territorial/comunicacion/noticias/mvot-informa-cambios-programa-entre-todos', date: '2026-06-24' },
      { outlet: 'la diaria', title: 'Ministerio de Vivienda aplicará parte de la Ley de Vivienda Promovida mediante el programa Entre Todos y delegará otras funciones al MEF', url: 'https://ladiaria.com.uy/politica/articulo/2025/8/ministerio-de-vivienda-aplicara-parte-de-la-ley-de-vivienda-promovida-mediante-el-programa-entre-todos-y-delegara-otras-funciones-al-mef/', date: '2025-08-14' },
    ],
    es: {
      title: 'Entre Todos: viviendas subsidiadas que no llegaron a quien debían',
      dek: 'El propio Ministerio de Vivienda advirtió que no todas las casas del programa fueron a la población objetivo: la lista de postulantes la presentaban las empresas.',
      contexto: 'El programa Entre Todos — Sueños en Obra fue creado en febrero de 2022, durante el gobierno de Lacalle Pou, para facilitar el acceso a la vivienda de sectores de ingresos medios y medios-bajos. Funciona dentro del régimen de vivienda promovida: empresas privadas presentan proyectos que reciben exoneraciones y, en algunos casos, subsidios y garantía del Estado, y luego venden o alquilan las unidades a familias que cumplen requisitos de ingreso. Lo gestionan el Ministerio de Vivienda y Ordenamiento Territorial y la Agencia Nacional de Vivienda.',
      hallazgo: 'En el Plan Quinquenal de Vivienda y Hábitat 2025-2029, el actual Ministerio de Vivienda dedicó 45 de sus 112 páginas a evaluar la gestión anterior. Según la diaria, allí advirtió que no todas las viviendas de Entre Todos fueron destinadas a la población objetivo. El punto central es el mecanismo de selección: el acceso se resolvía a partir de un listado de aspirantes que las propias empresas promotoras presentaban al ministerio, a diferencia del acceso por llamado público que se usa en los demás programas. El Observador informó, con datos del ministerio, que entre junio de 2022 y mayo de 2025 se presentaron 114 proyectos, con 380 viviendas terminadas, 795 en obra y 242 sin iniciar, y que la garantía estatal SiGa Entre Todos, con una dotación inicial de 90 millones de dólares, se concretó en solo nueve operaciones entre 2023 y 2025, por un monto promedio de 233.000 dólares.',
      statusNote: 'El 24 de junio de 2026 el MVOT comunicó los cambios aprobados: máximo de 100 viviendas por proyecto para promover la diversificación territorial, la Comisión Asesora Técnica (CETA) pasa de aprobar proyectos a asesorar al ministerio, la garantía SiGa queda limitada a proyectos de hasta 30 viviendas, la Dirección Nacional de Vivienda (Dinavi) fija los precios máximos de comercialización en lugar de la CETA, las viviendas deben ubicarse en suelo urbano o suburbano de uso habitacional con conexión obligatoria a saneamiento, y el Aporte Económico No Reembolsable se sustituye por un régimen encuadrado en la ley 13.728. El ministerio sostuvo que busca mejorar el acceso de las familias y fortalecer su propio control. En agosto de 2025 la ministra Tamara Paseyro ya había explicado que la garantía SiGa se orientaría a empresas pequeñas y a proyectos del interior, donde las dificultades para acceder al crédito son mayores.',
      porQueImporta: 'Si la lista de quién puede comprar una vivienda subsidiada la arma la empresa que la construye, el Estado pone el beneficio fiscal pero pierde el control de a quién llega. Para una familia que cumple los requisitos, eso puede ser la diferencia entre entrar o quedar afuera sin saber por qué.',
      caveat: 'Entre Todos se ejecuta con exoneraciones, subsidios y garantías a proyectos privados, no con obra contratada por el Estado: no deja contratos de compra en el buscador. Sí quedan registradas las obras que el MVOT licita directamente.',
    },
    en: {
      title: 'Entre Todos: subsidised homes that missed their target group',
      dek: 'The Housing Ministry itself warned that not all the programme\'s homes reached the target population: developers submitted the applicant lists.',
      contexto: 'The Entre Todos — Sueños en Obra programme was created in February 2022, under Lacalle Pou\'s government, to ease housing access for middle and lower-middle income groups. It operates within the promoted housing regime: private firms submit projects that receive tax exemptions and, in some cases, subsidies and a State guarantee, and then sell or rent the units to families meeting income requirements. It is managed by the Ministry of Housing and Territorial Planning and the National Housing Agency.',
      hallazgo: 'In the 2025-2029 Five-Year Housing and Habitat Plan, the current Housing Ministry devoted 45 of its 112 pages to assessing the previous administration. According to la diaria, it warned there that not all Entre Todos homes went to the target population. The central issue is the selection mechanism: access was decided from a list of applicants that the developer firms themselves submitted to the ministry, unlike the public-call access used in the other programmes. El Observador reported, using ministry data, that between June 2022 and May 2025 there were 114 projects submitted, with 380 homes completed, 795 under construction and 242 not yet started, and that the State\'s SiGa Entre Todos guarantee, with an initial endowment of US$ 90 million, went ahead in only nine operations between 2023 and 2025, for an average of US$ 233,000.',
      statusNote: 'On 24 June 2026 the MVOT announced the approved changes: a maximum of 100 homes per project to promote territorial diversification, the Technical Advisory Commission (CETA) shifting from approving projects to advising the ministry, the SiGa guarantee limited to projects of up to 30 homes, the National Housing Directorate (Dinavi) setting maximum sale prices instead of the CETA, homes required to sit on urban or suburban land zoned for residential use with mandatory connection to sanitation, and the Non-Repayable Economic Contribution replaced by a scheme framed under law 13.728. The ministry said it seeks to improve families\' access and strengthen its own oversight. In August 2025 minister Tamara Paseyro had already explained that the SiGa guarantee would be steered towards small firms and projects in the interior, where access to credit is harder.',
      porQueImporta: 'If the list of who may buy a subsidised home is drawn up by the company that builds it, the State puts up the tax break but loses control over who it reaches. For a family that meets the requirements, that can be the difference between getting in and being left out without knowing why.',
      caveat: 'Entre Todos runs on exemptions, subsidies and guarantees to private projects, not on works contracted by the State: it leaves no purchase contracts in the search engine. Works the MVOT tenders directly are recorded.',
    },
  },
  {
    slug: 'viviendas-vacias-ley-expropiacion',
    emoji: '🚪',
    theme: 'vivienda',
    period: '2018-2026',
    statusKind: 'debate',
    status: 'debate',
    organisms: ['Agencia Nacional de Vivienda', 'Ministerio de Vivienda y Ordenamiento Territorial'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'Instituto Nacional de Estadística', title: 'Censo 2023: Viviendas desocupadas', url: 'https://www.gub.uy/instituto-nacional-estadistica/comunicacion/noticias/censo-2023-viviendas-desocupadas', date: '2025-01-08' },
      { outlet: 'la diaria', title: 'Dos de cada diez viviendas están vacías en Uruguay: ¿qué hay detrás de esta situación?', url: 'https://ladiaria.com.uy/cotidiana/articulo/2025/2/dos-de-cada-diez-viviendas-estan-vacias-en-uruguay-que-hay-detras-de-esta-situacion/', date: '2025-02-25' },
      { outlet: 'IMPO (Dirección Nacional de Impresiones y Publicaciones Oficiales)', title: 'Ley N° 19.676 — Deberes relativos a la propiedad inmueble urbana (inmuebles vacíos y degradados)', url: 'https://www.impo.com.uy/bases/leyes/19676-2018', date: '2018-10-26' },
      { outlet: 'Telemundo (Teledoce)', title: 'Senado aprobó por unanimidad la expropiación de casas vacías y abandonadas: proyecto plantea dar un nuevo destino a los inmuebles', url: 'https://www.teledoce.com/telemundo/nacionales/senado-aprobo-por-unanimidad-la-expropiacion-de-casas-vacias-y-abandonadas-proyecto-plantea-dar-un-nuevo-destino-a-los-inmuebles/', date: '2025-10-15' },
      { outlet: 'la diaria', title: 'Viviendas vacías: el Parlamento aprobó la ley que agiliza la expropiación de inmuebles con deuda compensable', url: 'https://ladiaria.com.uy/politica/articulo/2026/6/viviendas-vacias-el-parlamento-aprobo-la-ley-que-agiliza-la-expropiacion-de-inmuebles-con-deuda-compensable/', date: '2026-06-03' },
    ],
    es: {
      title: '323.514 viviendas vacías y una ley para acelerar las expropiaciones',
      dek: 'El Censo 2023 contó que casi dos de cada diez viviendas del país están desocupadas; en junio de 2026 el Parlamento aprobó abreviar el trámite de expropiación.',
      contexto: 'La ley 19.676, promulgada el 26 de octubre de 2018, declaró de interés general el cumplimiento de los deberes relativos a la propiedad inmueble urbana, con el fin de evitar y revertir los procesos en que se combinan el vacío y la degradación de los inmuebles; habilitó a la Agencia Nacional de Vivienda y al ministerio a solicitar la declaración judicial de un inmueble como vacío y degradado. El Censo 2023 del Instituto Nacional de Estadística, difundido el 8 de enero de 2025, contabilizó 1.659.048 viviendas en el país, de las cuales 19,5% —unas 323.514— figuraban desocupadas, con picos de 45,2% en Maldonado, 42,1% en Rocha y 24% en Colonia, y un mínimo de 9,6% en Montevideo.',
      hallazgo: 'El dato abrió una discusión sobre cuánta de esa vivienda vacía es realmente recuperable. El jefe de comunicación de la ANV, Ignacio Ferrari, dijo a la diaria que las unidades vacías responden a múltiples factores, que el INE considera los inmuebles en obra como parte de los proyectos en construcción y que unas 11.000 están en distintas etapas de obra; Fucvam advirtió que hay viviendas financiadas con dinero público que terminan vacías y alimentan la especulación, y el sector inmobiliario sostuvo que el mercado está estable. En el Senado, el subsecretario de Vivienda Christian Di Candia manejó una cifra más acotada: unas 90.000 viviendas vacías sin otro destino, es decir, sin alquiler, sin construcción y sin un proyecto específico, según Telemundo, y sostuvo que «todo el sistema político hizo un acuerdo en la necesidad de recuperar suelo urbano».',
      statusNote: 'El Senado aprobó por unanimidad, el 15 de octubre de 2025, el proyecto que abrevia el trámite de expropiación de inmuebles vacíos y abandonados con deudas compensables y riesgos estructurales por deterioros severos. Tras pasar por Diputados con modificaciones, el Parlamento le dio aprobación definitiva el 3 de junio de 2026, en el Senado como tercera y última cámara, por unanimidad (22 en 22), según la diaria; el proyecto había sido presentado por el Frente Amplio. Al cierre de esta ficha (agosto de 2026) no constan cifras oficiales de cuántos inmuebles se recuperaron efectivamente al amparo de la ley 19.676.',
      porQueImporta: 'Hay familias en asentamientos y personas en situación de calle mientras casi una de cada cinco viviendas del país está vacía. Recuperar un inmueble abandonado con deuda suele ser más barato para el Estado que construir uno nuevo, y esa deuda —contribución y tributos— es plata que los demás vecinos sí pagaron.',
      caveat: 'La expropiación de inmuebles vacíos no genera compras públicas rastreables en el buscador. Lo que sí puede aparecer es la obra de refacción que el Estado contrate después sobre esos inmuebles. Además, las cifras del Censo sobre viviendas desocupadas están discutidas: la ANV sostiene que incluyen inmuebles en obra o en proceso de alquiler.',
    },
    en: {
      title: '323,514 empty homes and a law to speed up expropriations',
      dek: 'The 2023 census counted almost two in ten homes in the country as unoccupied; in June 2026 Parliament approved shortening the expropriation procedure.',
      contexto: 'Law 19.676, promulgated on 26 October 2018, declared it a matter of general interest that the duties attaching to urban real property be fulfilled, so as to prevent and reverse processes combining vacancy and degradation; it allowed the National Housing Agency and the ministry to request a judicial declaration that a property is vacant and degraded. The National Statistics Institute\'s 2023 census, released on 8 January 2025, counted 1,659,048 dwellings in the country, of which 19.5% — some 323,514 — were unoccupied, peaking at 45.2% in Maldonado, 42.1% in Rocha and 24% in Colonia, with a low of 9.6% in Montevideo.',
      hallazgo: 'The figure opened a debate over how much of that empty housing is actually recoverable. The ANV\'s head of communications, Ignacio Ferrari, told la diaria that vacant units respond to multiple factors, that the statistics institute counts properties under construction as part of building projects, and that some 11,000 are at various stages of works; Fucvam warned that homes financed with public money end up empty and feed speculation, and the real estate sector held that the market is stable. In the Senate, deputy housing minister Christian Di Candia used a narrower figure: some 90,000 empty homes with no other use — that is, no rental, no building work and no specific project — according to Telemundo, and argued that "the whole political system agreed on the need to recover urban land".',
      statusNote: 'The Senate unanimously approved, on 15 October 2025, the bill shortening the expropriation procedure for vacant and abandoned properties carrying compensable debt and structural risks from severe deterioration. After passing through the Chamber of Deputies with amendments, Parliament gave it final approval on 3 June 2026, with the Senate as the third and final chamber, unanimously (22 of 22), according to la diaria; the bill had been introduced by the Frente Amplio. As of this file\'s closing (August 2026) there are no official figures on how many properties were actually recovered under law 19.676.',
      porQueImporta: 'There are families in informal settlements and people sleeping rough while almost one in five homes in the country sits empty. Recovering an abandoned property that carries debt is usually cheaper for the State than building a new one, and that debt — rates and taxes — is money the other neighbours did pay.',
      caveat: 'Expropriating vacant properties does not generate public purchases traceable in the search engine. What may appear is the refurbishment work the State later contracts on those properties. The census figures on unoccupied dwellings are also disputed: the ANV holds that they include properties under construction or in the process of being rented.',
    },
  },
  {
    slug: 'deudores-bhu-anv-plan-ur',
    emoji: '💸',
    theme: 'vivienda',
    period: '2023-2026',
    statusKind: 'debate',
    status: 'debate',
    amountReported: 'unos US$ 590 millones que resigna el Estado, cifra manejada al aprobarse la ley en diciembre de 2023 (la diaria)',
    organisms: ['Banco Hipotecario del Uruguay', 'Agencia Nacional de Vivienda'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Banco Hipotecario del Uruguay',
        'Agencia Nacional de Vivienda',
      ],
      search: 'hipotecario',
      yearFrom: 2023,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'la diaria', title: 'Diputados aprobó solución para deudores del BHU y la ANV, que tendrá un costo de 590 millones de dólares para el Estado', url: 'https://ladiaria.com.uy/politica/articulo/2023/12/diputados-aprobo-solucion-para-deudores-del-bhu-y-la-anv-que-tendra-un-costo-de-590-millones-de-dolares-para-el-estado/', date: '2023-12-13' },
      { outlet: 'IMPO (Dirección Nacional de Impresiones y Publicaciones Oficiales)', title: 'Ley N° 20.237 — Normas para deudores en unidades reajustables del Banco Hipotecario del Uruguay y de la Agencia Nacional de Vivienda', url: 'https://www.impo.com.uy/bases/leyes/20237-2023', date: '2023-12-22' },
      { outlet: 'Agencia Nacional de Vivienda', title: 'Firma de reglamentación Ley N° 20.237 - Plan UR', url: 'https://www.anv.gub.uy/firma-de-reglamentacion-ley-ndeg-20237-plan-ur', date: '2024-07-03' },
    ],
    es: {
      title: 'Deudores en UR: los US$ 590 millones que el Estado resignó',
      dek: 'El Parlamento votó por unanimidad reestructurar las deudas en unidades reajustables de unas 25.000 familias del Banco Hipotecario y de la ANV.',
      contexto: 'Desde hace décadas los créditos hipotecarios del Banco Hipotecario del Uruguay (BHU) se otorgaron en unidades reajustables (UR), un valor que se ajusta por el índice medio de salarios. Cuando ese ajuste corrió por encima de la capacidad de pago de los hogares, miles de familias quedaron con saldos que después de años de pagar seguían siendo iguales o mayores que el original. Ya había habido un intento de solución en 2008, al que los legisladores volvieron a referirse en el debate de 2023.',
      hallazgo: 'La Cámara de Diputados aprobó por unanimidad, el 12 de diciembre de 2023, la ley que reestructura las deudas en UR de deudores del Banco Hipotecario y de la Agencia Nacional de Vivienda. Según la diaria, la medida alcanza a unas 25.000 familias y el Estado resigna unos 590 millones de dólares. La norma es la ley 20.237, aprobada el 22 de diciembre de 2023: alcanza a deudas asumidas con anterioridad al 1º de enero de 2009 por créditos originales que no superaran los 80.000 dólares, con tasa 0% para las anteriores al 31 de diciembre de 1993 y hasta 2,5% para las de 1994 a 2008, y crea un fideicomiso para administrar y reestructurar esos créditos y promesas de compraventa. La diputada Cecilia Cairo, del Frente Amplio, calificó la solución de justa y dijo que los cambios buscaban evitar «lo que nos pasó en 2008».',
      statusNote: 'La reglamentación, llamada Plan UR, se firmó el 3 de julio de 2024, tras la aprobación del reglamento por el directorio de la ANV y por el BHU el 2 de julio. La ANV informó que continuaba trabajando en el análisis de más de 20.000 créditos y que la información estaría disponible en octubre de ese año. La ley también prevé que se consideren extinguidas las deudas cuando hayan transcurrido cuarenta años o más desde su asunción y se cumplan condiciones acumulativas de pago (110 pagos en los últimos diez años y haber abonado al menos 35% del monto garantizado). Al cierre de esta ficha (agosto de 2026) no consta un balance oficial publicado de cuántos deudores ingresaron efectivamente al plan ni cuánto costó finalmente.',
      porQueImporta: '590 millones de dólares es plata que el Estado deja de cobrar y que sale del bolsillo de todos. A cambio, unas 25.000 familias dejan de arrastrar una deuda impagable y de arriesgar el remate de su casa. Es una decisión política legítima, votada por unanimidad, pero tiene precio y conviene saber cuál fue.',
      caveat: 'Es una condonación y reestructura de créditos, no una compra: no deja contratos rastreables en el buscador. La cifra de 590 millones de dólares es la que se manejó al aprobarse la ley, no un balance de ejecución.',
    },
    en: {
      title: 'UR debtors: the US$ 590 million the State gave up',
      dek: 'Parliament voted unanimously to restructure the adjustable-unit debts of some 25,000 families owing money to the Mortgage Bank and the ANV.',
      contexto: 'For decades, mortgage loans from the Banco Hipotecario del Uruguay (BHU) were granted in adjustable units (UR), a value indexed to the average wage index. When that indexation outran households\' capacity to pay, thousands of families were left with balances that, after years of payments, were still equal to or larger than the original. There had already been an attempted fix in 2008, which legislators referred back to in the 2023 debate.',
      hallazgo: 'The Chamber of Deputies unanimously approved, on 12 December 2023, the law restructuring the UR debts of Mortgage Bank and National Housing Agency borrowers. According to la diaria, the measure reaches some 25,000 families and the State gives up around US$ 590 million. The rule is law 20.237, passed on 22 December 2023: it covers debts assumed before 1 January 2009 on original loans not exceeding US$ 80,000, with a 0% rate for those predating 31 December 1993 and up to 2.5% for those from 1994 to 2008, and it creates a trust to administer and restructure those loans and purchase agreements. Frente Amplio deputy Cecilia Cairo called the solution fair and said the changes aimed to avoid "what happened to us in 2008".',
      statusNote: 'The implementing regulation, known as Plan UR, was signed on 3 July 2024, after the ANV\'s board and the BHU approved it on 2 July. The ANV reported that it was still working through the analysis of more than 20,000 loans and that the information would be available in October that year. The law also provides that debts be deemed extinguished once forty years or more have passed since they were assumed and cumulative payment conditions are met (110 payments in the last ten years and having paid at least 35% of the guaranteed amount). As of this file\'s closing (August 2026) there is no published official account of how many debtors actually entered the plan or what it finally cost.',
      porQueImporta: 'US$ 590 million is money the State chooses not to collect, and it comes out of everyone\'s pocket. In exchange, some 25,000 families stop carrying an unpayable debt and risking the foreclosure of their home. It is a legitimate political decision, passed unanimously, but it has a price and it is worth knowing what it was.',
      caveat: 'This is a write-off and restructuring of loans, not a purchase: it leaves no traceable contracts in the search engine. The US$ 590 million figure is the one used when the law was passed, not an execution report.',
    },
  },
  {
    slug: 'fosvoc-desvio-fondo-vivienda-construccion',
    emoji: '⚖️',
    theme: 'vivienda',
    period: '2024-2026',
    statusKind: 'judicial',
    status: 'condena',
    amountReported: 'más de US$ 1,2 millones desviados del Fosvoc, según Búsqueda (diciembre de 2025)',
    organisms: ['Ministerio de Trabajo y Seguridad Social', 'Banco de Previsión Social'],
    feedCoverage: 'unlikely',
    sources: [
      { outlet: 'Búsqueda', title: 'Investigación del Fondo de Vivienda de la Construcción probó un círculo delictivo y logró penas, pero no una reparación', url: 'https://www.busqueda.com.uy/informacion/investigacion-del-fondo-vivienda-la-construccion-proboun-circulo-delictivo-y-logro-penas-pero-no-una-reparacion-n5408472', date: '2025-12-30' },
      { outlet: 'la diaria', title: 'Cuatro personas fueron condenadas por desvío de dinero de fondo de vivienda de la construcción', url: 'https://ladiaria.com.uy/justicia/articulo/2025/12/cuatro-personas-fueron-condenadas-por-desvio-de-dinero-de-fondo-de-vivienda-de-la-construccion/', date: '2025-12-15' },
      { outlet: 'El Observador', title: 'Fondo Social del Sunca: fiscalía llegó a un acuerdo con la trabajadora que realizó 193 desvíos irregulares y será condenada en audiencia', url: 'https://www.elobservador.com.uy/nacional/fondo-social-del-sunca-fiscalia-llego-un-acuerdo-la-trabajadora-que-realizo-193-desvios-irregulares-y-sera-condenada-audiencia-n6024154', date: '2025-11-11' },
    ],
    es: {
      title: 'Ocho condenas por el desvío del fondo de vivienda de la construcción',
      dek: 'La Fiscalía probó el desvío de más de US$ 1,2 millones del fondo que financia soluciones habitacionales para obreros de la construcción; la plata no se recuperó.',
      contexto: 'El Fondo Social de Vivienda de Obreros de la Construcción (Fosvoc) administra recursos destinados a soluciones habitacionales y programas sociales para los trabajadores del sector, originados en aportes del propio sector y no en partidas del Presupuesto nacional. Según El Observador, la maniobra se descubrió cuando la funcionaria a cargo se tomó licencia y la trabajadora que la sustituyó detectó movimientos llamativos en las cuentas bancarias de la institución. La investigación quedó a cargo de la Fiscalía de Delitos Económicos y Complejos de 3er turno, con el fiscal Gilberto Rodríguez.',
      hallazgo: 'Búsqueda informó que la investigación probó un «círculo delictivo» y que el monto desviado supera 1,2 millones de dólares. El Observador informó que la fiscalía llegó a un acuerdo con la funcionaria que realizó 193 transacciones irregulares por 35.627.581 pesos y 17.500 dólares, y que el fiscal ya había obtenido antes, en una audiencia de junio, la condena de tres exsindicalistas del Sunca. El 15 de diciembre de 2025 se condenó a cuatro personas más, tres hombres y una mujer, por juicio abreviado, por reiterados delitos de apropiación indebida en calidad de coautores y un delito de asistencia a las actividades precedentes al lavado de activos, según la diaria; en las cuentas de esos cuatro condenados se habían depositado unos 400.000 dólares. Recibieron obligación de fijar domicilio, presentación semanal ante la seccional policial y diez meses de trabajo comunitario.',
      statusNote: 'Al cierre de esta ficha (agosto de 2026), Búsqueda contabilizaba ocho personas condenadas tras un año de investigación. Según ese medio, el punto pendiente es la reparación: no se ordenó restitución y el abogado del Fosvoc, Óscar López Goldaracena, señaló que «el gran debe es la reparación», por lo que el fondo analizaba iniciar acciones civiles en 2026 para recuperar el dinero. Búsqueda agrega que la Fiscalía todavía debía avanzar sobre hipótesis relativas al financiamiento del Sunca y del Partido Comunista con dinero desviado, líneas que al cierre de esta ficha no derivaron en imputaciones conocidas: la investigación sigue abierta.',
      porQueImporta: 'Es plata que los trabajadores de la construcción aportan para poder acceder a una vivienda. Cada dólar desviado es una solución habitacional que no se dio, y hasta ahora la justicia condenó a ocho personas pero no consiguió que se devolviera el dinero al fondo.',
      caveat: 'El Fosvoc no es un organismo del Estado ni se financia con el Presupuesto: sus recursos vienen de aportes del propio sector. Por eso este caso no deja contratos ni pagos rastreables en el buscador de compras estatales. Las líneas de investigación aún abiertas son hipótesis fiscales, no hechos probados.',
    },
    en: {
      title: 'Eight convictions over the construction workers\' housing fund',
      dek: 'Prosecutors proved more than US$ 1.2 million was siphoned from the fund that finances housing for construction workers; the money was never recovered.',
      contexto: 'The Fondo Social de Vivienda de Obreros de la Construcción (Fosvoc) manages resources earmarked for housing solutions and social programmes for workers in the sector, funded by the sector\'s own contributions rather than by national budget allocations. According to El Observador, the scheme was uncovered when the employee in charge took leave and the worker who replaced her spotted unusual movements in the institution\'s bank accounts. The investigation was assigned to the third-shift Economic and Complex Crimes Prosecutor\'s Office, under prosecutor Gilberto Rodríguez.',
      hallazgo: 'Búsqueda reported that the investigation proved a "criminal ring" and that the amount diverted exceeds US$ 1.2 million. El Observador reported that prosecutors reached an agreement with the employee who carried out 193 irregular transactions worth 35,627,581 pesos and US$ 17,500, and that the prosecutor had already obtained, at an earlier hearing in June, the conviction of three former Sunca union officials. On 15 December 2025 four more people — three men and one woman — were convicted through abbreviated proceedings for repeated counts of misappropriation as co-perpetrators and one count of assisting activities preceding money laundering, according to la diaria; some US$ 400,000 had been deposited into those four convicts\' accounts. They received obligations to keep a fixed address, report weekly to their local police station and perform ten months of community service.',
      statusNote: 'As of this file\'s closing (August 2026), Búsqueda counted eight people convicted after a year of investigation. According to that outlet, the outstanding issue is redress: no restitution was ordered and the Fosvoc\'s lawyer, Óscar López Goldaracena, said "the big shortfall is reparation", so the fund was considering civil actions in 2026 to recover the money. Búsqueda adds that prosecutors still had to pursue hypotheses about the financing of the Sunca union and the Communist Party with diverted money, lines that as of this file\'s closing had not led to any known charges: the investigation remains open.',
      porQueImporta: 'This is money construction workers contribute so they can access a home. Every dollar diverted is a housing solution that was not delivered, and so far the courts have convicted eight people but have not managed to get the money returned to the fund.',
      caveat: 'The Fosvoc is not a State body and is not financed by the national budget: its resources come from the sector\'s own contributions. That is why this case leaves no contracts or payments traceable in the public procurement search engine. The lines of investigation still open are prosecutors\' hypotheses, not proven facts.',
    },
  },
  {
    slug: 'modulos-emergencia-habitacional-fideicomiso',
    emoji: '📦',
    theme: 'vivienda',
    period: '2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    organisms: ['Ministerio de Vivienda y Ordenamiento Territorial', 'Corporación Nacional para el Desarrollo'],
    feedCoverage: 'unlikely',
    query: {
      buyers: [
        'Dirección Nacional de Medio Ambiente',
        'Dirección General de Secretaría',
        'Dirección Nacional de Vivienda',
        'Dirección Nacional de Ordenamiento Territorial',
        'Dirección Nacional de Aguas y Saneamiento',
        'Dirección Nacional de Integración Social y Urbana',
      ],
      search: 'emergencia',
      yearFrom: 2026,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'Presidencia de la República', title: 'Vivienda prevé módulos habitacionales como respuesta rápida a situaciones críticas', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/vivienda-llamado-mvot-modulos', date: '2026-02-11' },
      { outlet: 'Corporación Nacional para el Desarrollo', title: 'Módulos de emergencia habitacional — información general del llamado N° 03/2025', url: 'https://cnd.org.uy/sites/default/files/2026-02/Presentaci%C3%B3n%20M%C3%B3dulos%20Habitacionales.pdf', date: '2026-02-02' },
      { outlet: 'El Telégrafo', title: 'Ministerio de Vivienda lanzó llamado para comprar módulos', url: 'https://www.eltelegrafo.com/2026/02/ministerio-de-vivienda-lanzo-llamado-para-comprar-modulos/', date: '2026-02-07' },
      { outlet: 'la diaria', title: 'MVOT busca dar respuesta a la vulnerabilidad habitacional con la instalación de módulos de emergencia', url: 'https://ladiaria.com.uy/politica/articulo/2026/2/mvot-busca-dar-respuesta-a-la-vulnerabilidad-habitacional-con-la-instalacion-de-modulos-de-emergencia/', date: '2026-02-03' },
    ],
    es: {
      title: 'Hasta 300 módulos de emergencia comprados fuera del canal habitual',
      dek: 'El Ministerio de Vivienda compra módulos habitacionales para emergencias, pero el llamado lo contrata un fideicomiso cuya fiduciaria es Conafin AFISA, de la Corporación Nacional para el Desarrollo.',
      contexto: 'El Censo 2023 identificó 67.024 hogares con carencias críticas de vivienda en Uruguay: 1.447 con paredes o techos de material de desecho, 2.895 con piso de tierra, 9.447 sin baño de uso exclusivo y 9.041 sin saneamiento adecuado. En febrero de 2026, el Ministerio de Vivienda y Ordenamiento Territorial dio a conocer el llamado 03/2025 para el suministro e instalación de hasta 300 módulos habitacionales en todo el territorio nacional, destinados a atender situaciones de emergencia habitacional: módulos habitables de estar-cocina, dormitorio y baño (estándar y accesible), y un módulo integral de un dormitorio, más accesorios como conectores, escaleras, rampas accesibles y depósitos de agua residual.',
      hallazgo: 'El llamado no lo tramita el ministerio por el canal habitual de compras estatales: el contratante es el Fideicomiso de Integración Social y Urbana (FISU), cuya fiduciaria es Conafin AFISA, de la Corporación Nacional para el Desarrollo (CND), con el MVOT, el MGAP y el MEF como fideicomitentes, y se publica en el portal de llamados de la CND. La apertura de ofertas fue el 23 de febrero de 2026 a las 11:00. El pliego exige sistemas constructivos no tradicionales con DAT o CIR vigente del MVOT, una línea de crédito bancario de al menos 1.000.000 de pesos proporcional a la capacidad de producción declarada, una durabilidad de diez años y un plazo de fabricación de 30 días calendario desde el perfeccionamiento del contrato. Se adjudica a la oferta de menor costo total, con posibilidad de multiadjudicación y lotes mínimos de diez módulos. La ministra Tamara Paseyro dijo que «esta población hoy nos necesita más que ninguna otra, porque tenemos el 31% de los niños y niñas menores de seis años viviendo bajo pobreza multidimensional».',
      statusNote: 'El ministerio dio a conocer el llamado el 3 de febrero de 2026 y la recepción de ofertas cerró el 23 de febrero de 2026. La iniciativa se enmarca en el Plan Quinquenal de Vivienda y Hábitat del ministerio. Al cierre de esta ficha (agosto de 2026) no consta información pública sobre la adjudicación ni sobre el monto final del contrato.',
      porQueImporta: 'Un módulo de emergencia puede ser la diferencia entre un piso de tierra y un piso, hoy. Pero comprarlos a través de un fideicomiso implica que el precio unitario, el proveedor y la cantidad efectivamente entregada no quedan en el mismo registro público que el resto de las compras del Estado.',
      caveat: 'Esta compra la contrata el fideicomiso FISU, con Conafin AFISA (CND) como fiduciaria, y se publica en el portal de llamados de la CND, no en el sistema de compras estatales: es muy probable que no aparezca en el buscador de este sitio.',
    },
    en: {
      title: 'Up to 300 emergency modules bought outside the usual channel',
      dek: 'The Housing Ministry is buying emergency housing modules, but the tender is contracted by a trust whose trustee is Conafin AFISA, of the National Development Corporation.',
      contexto: 'The 2023 census identified 67,024 households with critical housing deficiencies in Uruguay: 1,447 with walls or roofs made of waste material, 2,895 with dirt floors, 9,447 without an exclusive bathroom and 9,041 without adequate sanitation. In February 2026 the Ministry of Housing and Territorial Planning announced call 03/2025 for the supply and installation of up to 300 housing modules across the country, intended to address housing emergencies: habitable modules comprising living-kitchen, bedroom and bathroom (standard and accessible), plus an integral one-bedroom module, along with accessories such as connectors, stairs, accessible ramps and wastewater tanks.',
      hallazgo: 'The ministry does not process this call through the usual state procurement channel: the contracting party is the Social and Urban Integration Trust (FISU), whose trustee is Conafin AFISA of the National Development Corporation (CND), with the MVOT, the Agriculture Ministry and the Ministry of Economy as settlors, and it is published on the CND\'s tender portal. Bids opened on 23 February 2026 at 11:00. The specifications require non-traditional construction systems with a current MVOT technical approval (DAT or CIR), a bank credit line of at least 1,000,000 pesos proportional to the declared production capacity, ten-year durability, and manufacture within 30 calendar days of the contract being finalised. The award goes to the lowest total-cost bid, with multiple awards possible and minimum lots of ten modules. Minister Tamara Paseyro said "this population needs us today more than any other, because 31% of children under six live in multidimensional poverty".',
      statusNote: 'The ministry announced the call on 3 February 2026 and bid reception closed on 23 February 2026. The initiative falls within the ministry\'s Five-Year Housing and Habitat Plan. As of this file\'s closing (August 2026) there is no public information on the award or the final contract amount.',
      porQueImporta: 'An emergency module can be the difference between a dirt floor and a floor, today. But buying them through a trust means the unit price, the supplier and the quantity actually delivered do not end up in the same public record as the rest of the State\'s purchases.',
      caveat: 'This purchase is contracted by the FISU trust, with Conafin AFISA (CND) as trustee, and published on the CND\'s tender portal, not in the state procurement system: it is very likely it will not appear in this site\'s search engine.',
    },
  },
  {
    slug: 'asentamientos-censo-corregido-plan-avanzar',
    emoji: '🏕️',
    theme: 'vivienda',
    period: '2024-2026',
    statusKind: 'gestion',
    status: 'en-ejecucion',
    amountReported: 'unos US$ 20 millones de inversión prevista para el realojo de Los Eucaliptus y Nueva Esperanza, en Maldonado (Presidencia, julio de 2026)',
    organisms: ['Ministerio de Vivienda y Ordenamiento Territorial'],
    feedCoverage: 'partial',
    query: {
      buyers: [
        'Dirección Nacional de Medio Ambiente',
        'Dirección General de Secretaría',
        'Dirección Nacional de Vivienda',
        'Dirección Nacional de Ordenamiento Territorial',
        'Dirección Nacional de Aguas y Saneamiento',
        'Dirección Nacional de Integración Social y Urbana',
      ],
      search: 'saneamiento',
      yearFrom: 2024,
      yearTo: 2026,
    },
    sources: [
      { outlet: 'El Observador', title: 'Corrección del Censo 2023 mostró que hay 34.000 personas más viviendo en asentamientos de las que se informó inicialmente', url: 'https://www.elobservador.com.uy/nacional/correccion-del-censo-2023-mostro-que-hay-34000-personas-mas-viviendo-asentamientos-las-que-se-informo-incialmente-n6043941', date: '2026-05-14' },
      { outlet: 'Subrayado', title: 'Datos finales del censo 2023: 350.000 personas no habían sido contabilizadas, 34.500 de ellas viven en asentamientos', url: 'https://www.subrayado.com.uy/datos-finales-del-censo-2023-350000-personas-no-habian-sido-contabilizadas-34500-ellas-viven-asentamientos-n1007760', date: '2026-05-14' },
      { outlet: 'Ministerio de Vivienda y Ordenamiento Territorial', title: '¿Qué es el Plan Avanzar?', url: 'https://www.gub.uy/ministerio-vivienda-ordenamiento-territorial/politicas-y-gestion/es-plan-avanzar', date: '2024-09-06' },
      { outlet: 'En Perspectiva', title: 'Balance de gestión del Plan Avanzar del Ministerio de Vivienda y Ordenamiento Territorial', url: 'https://enperspectiva.uy/documentos/balance-de-gestion-del-plan-avanzar-del-ministerio-de-vivienda-y-ordenamiento-territorial/', date: '2024-10-01' },
      { outlet: 'Presidencia de la República', title: 'Plan de realojo en Los Eucaliptus continúa con la mudanza de 40 familias a nuevas viviendas', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/plan-realojo-eucaliptus-nuevo-comienzo-maldonado-mvot', date: '2026-07-21' },
    ],
    es: {
      title: 'Asentamientos: 193.260 personas, 34.533 más de lo que se había dicho',
      dek: 'El INE corrigió el Censo 2023 por una omisión de 10,3% y la población en asentamientos pasó de 4,5% a 5,5% del total del país.',
      contexto: 'El Plan Avanzar es la política pública de alcance nacional del Ministerio de Vivienda para atender la situación de los asentamientos irregulares y promover su integración social y urbana, ejecutada por la Dirección Nacional de Integración Social y Urbana (Dinisu) junto con el Congreso de Intendentes. Según la ficha oficial del ministerio, actualizada en setiembre de 2024, el plan contempla acciones simultáneas en los 19 departamentos, trabajando en más de 120 asentamientos y atendiendo a más de 15.000 hogares. En agosto de 2024 el ministerio presentó un balance de gestión, publicado por En Perspectiva, en el que la entonces ministra Florencia Arbeleche mencionó 108 asentamientos intervenidos.',
      hallazgo: 'El 14 de mayo de 2026 el INE presentó los datos finales ponderados del Censo 2023 y corrigió al alza la población en asentamientos: 193.260 personas, 34.533 más que las 158.727 informadas inicialmente en febrero de 2025, según El Observador. Eso lleva la proporción de 4,5% a 5,5% de la población del país. La corrección responde a una omisión censal de 10,3% —unas 350.000 personas que no fueron entrevistadas y que el INE inicialmente había excluido del cálculo de la mayoría de las variables—, que el director del INE, Marcelo Bisogno, calificó de históricamente grande frente al 4,1% de 2011 y a promedios que no llegaron al 2% en los cinco censos anteriores, según Subrayado. La omisión no fue pareja: según El Observador, quedó sin censar 17,5% de la población de nivel socioeconómico bajo y 9,8% del medio-bajo, frente a 3,1% del alto, de modo que la base sobre la que se planificó la política de vivienda subestimaba justamente a la población objetivo.',
      statusNote: 'En Maldonado, el realojo de Los Eucaliptus y Nueva Esperanza —un proyecto integral que beneficiará a más de 870 núcleos y abarcará a unas 1.840 personas, con 174 viviendas— avanza con una inversión cercana a los 20 millones de dólares, según Presidencia; en julio de 2026, 40 familias se trasladaron a viviendas de dos, tres o cuatro dormitorios. Al cierre de esta ficha (agosto de 2026) el ministerio no publicó un balance de ejecución posterior a la corrección del censo.',
      porQueImporta: 'Si el país contó 34.533 personas menos de las que viven en asentamientos, todos los cálculos de cuántas viviendas, cuánto saneamiento y cuánta plata hacen falta quedaron cortos. La corrección no cambia la realidad de esos barrios: cambia lo que el Estado creía que tenía que resolver, y con eso el tamaño del presupuesto necesario.',
      caveat: 'El Plan Avanzar combina obra contratada por el ministerio, convenios con intendencias y ejecución vía fideicomiso: en el buscador se ve la parte que el MVOT contrató a su nombre, no el gasto total del plan.',
    },
    en: {
      title: 'Settlements: 193,260 people, 34,533 more than had been reported',
      dek: 'The statistics institute corrected the 2023 census for a 10.3% undercount, and the population living in settlements rose from 4.5% to 5.5% of the country.',
      contexto: 'Plan Avanzar is the Housing Ministry\'s nationwide public policy for addressing the situation of irregular settlements and promoting their social and urban integration, executed by the National Directorate of Social and Urban Integration (Dinisu) together with the Congress of Mayors. According to the ministry\'s official page, updated in September 2024, the plan involves simultaneous action across all 19 departments, working in more than 120 settlements and serving more than 15,000 households. In August 2024 the ministry presented a management report, published by En Perspectiva, in which the then minister Florencia Arbeleche mentioned 108 settlements intervened.',
      hallazgo: 'On 14 May 2026 the statistics institute (INE) presented the final weighted data from the 2023 census and revised the settlement population upwards: 193,260 people, 34,533 more than the 158,727 initially reported in February 2025, according to El Observador. That takes the share from 4.5% to 5.5% of the country\'s population. The correction stems from a census omission rate of 10.3% — some 350,000 people who were not interviewed and whom the INE had initially excluded from the calculation of most variables — which INE director Marcelo Bisogno described as historically large against 4.1% in 2011 and averages below 2% in the previous five censuses, according to Subrayado. The omission was not even: according to El Observador, 17.5% of the lower socioeconomic bracket and 9.8% of the lower-middle went uncounted, versus 3.1% of the upper one, meaning the baseline used to plan housing policy underestimated precisely the target population.',
      statusNote: 'In Maldonado, the relocation of Los Eucaliptus and Nueva Esperanza — an integrated project that will benefit more than 870 family units and reach some 1,840 people, with 174 homes — is proceeding with an investment close to US$ 20 million, according to the Presidency; in July 2026, 40 families moved into two-, three- or four-bedroom homes. As of this file\'s closing (August 2026) the ministry had not published an execution report subsequent to the census correction.',
      porQueImporta: 'If the country counted 34,533 fewer people than actually live in settlements, every calculation of how many homes, how much sanitation and how much money is needed fell short. The correction does not change the reality of those neighbourhoods: it changes what the State believed it had to solve, and with it the size of the budget required.',
      caveat: 'Plan Avanzar combines works contracted by the ministry, agreements with departmental governments and execution via a trust fund: the search engine shows the part the MVOT contracted in its own name, not the plan\'s total spending.',
    },
  },
]
