/**
 * Who else competed — recovering the list of bidders from an acta de adjudicación.
 *
 * PURE. No I/O, no imports, so tests/unit can drive it off real acta fixtures.
 *
 * ## Why this exists, and what it deliberately is NOT
 *
 * The site shows who WON a contract. It cannot show who else bid, because the OCDS feed has no such
 * field: `tender.tenderers` and `tender.numberOfTenderers` are populated on 0% of releases, the
 * per-record and per-release OCDS endpoints return exactly what the bulk download does, and the gov
 * HTML detail page states only "Recepción de ofertas hasta: <fecha>" — a deadline, not a list.
 *
 * The acta de adjudicación PDF sometimes states it in prose. Measured over 40 awarded competitive
 * calls (tests/unit/acta-bidders-feasibility.verify.ts): 37/37 actas carry a real text layer, 6
 * mention the offers at all, and only ~3 actually ENUMERATE them. Roughly 8%.
 *
 * That is why this produces a CONTRACT-LEVEL FACT and never an organism-level indicator. At 8%
 * coverage an "single bidding rate" per organism would absolve the opaque: a body whose actas simply
 * do not enumerate would score clean, exactly the labelling artifact already documented for the
 * "% compra directa" measure. A fact about one contract, carrying the acta it came from, is
 * checkable and does not average anything.
 *
 * ## Why the matching is done on a DESPACED string
 *
 * These PDFs are generated by RSTXPDF3 and hard-wrap mid-word. Real text from the corpus:
 *
 *     "se present\naron los siguientes oferentes"
 *     "se presentaron la s firmas:"
 *
 * So neither line-based matching nor whitespace-collapsed matching finds the phrases reliably. The
 * parser strips ALL whitespace to search, keeping an index map back into the original text so the
 * names are read from the spaced original. That is the only reliable way in.
 *
 * ## Fail closed
 *
 * Anything the parser cannot enumerate confidently returns null. It never guesses a count, and it
 * never reports "one bidder" from silence — silence means the acta did not say.
 */

export interface ActaBidders {
  /**
   * Bidder names AS WRITTEN in the acta, lightly cleaned. Empty only for an explicit sole-bidder
   * statement.
   *
   * They can carry line-wrap artifacts — the generator breaks lines mid-word without a hyphen, so
   * "ELIAS ANA BEATRIZ" can arrive as "ELIAS A NA BEATRIZ". No attempt is made to repair that:
   * "M D CERVINI S.A." is a genuine name of the same shape, and a repair heuristic would corrupt
   * real names to tidy up broken ones. The UI must therefore always show `excerpt` alongside, so a
   * reader sees the original sentence.
   */
  bidders: string[];
  /** How many offers the acta accounts for. */
  count: number;
  /** Which phrasing matched, kept for provenance. */
  marker: string;
  /** The sentence it came from, so a reader can check the claim against the PDF. */
  excerpt: string;
}

/** Strip accents and lowercase, for matching only. */
function fold(s: string): string {
  return s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();
}

/** Despaced view of the text plus an index map back into the original. */
function despace(text: string): { flat: string; map: number[] } {
  let flat = "";
  const map: number[] = [];
  for (let i = 0; i < text.length; i++) {
    const ch = text[i]!;
    if (!/\s/.test(ch)) {
      flat += fold(ch);
      map.push(i);
    }
  }
  return { flat, map };
}

/**
 * The phrasings that introduce an enumeration, despaced.
 *
 * Every one of these was observed in the corpus; nothing here is speculative. `shape` decides how
 * the segment after the marker is split.
 */
const MARKERS: ReadonlyArray<{ needle: string; label: string; shape: "list" }> = [
  { needle: "siguientesoferentes", label: "siguientes oferentes", shape: "list" },
  { needle: "sepresentaronlasfirmas", label: "se presentaron las firmas", shape: "list" },
  { needle: "sepresentaronlassiguientesfirmas", label: "se presentaron las siguientes firmas", shape: "list" },
  { needle: "ofertaspresentadas", label: "ofertas presentadas", shape: "list" },
  { needle: "firmasoferentes", label: "firmas oferentes", shape: "list" },
  { needle: "propuestaspresentadas", label: "propuestas presentadas", shape: "list" },
];

/** Explicit statements that exactly one offer arrived. These carry a count with no names. */
const SOLE_BIDDER_MARKERS: ReadonlyArray<{ needle: string; label: string }> = [
  { needle: "unicooferente", label: "único oferente" },
  { needle: "unicaoferta", label: "única oferta" },
  { needle: "ofertaunica", label: "oferta única" },
  { needle: "unaunicaoferta", label: "una única oferta" },
  { needle: "sepresentounsolooferente", label: "se presentó un solo oferente" },
];

/** How far past the marker to look for the enumeration. Beyond this the acta has moved on. */
const WINDOW_CHARS = 900;

/** A name shorter than this is punctuation noise; longer than this is a swallowed paragraph. */
const MIN_NAME = 4;
const MAX_NAME = 90;

/**
 * Words that mean the "name" is really the acta's next clause. Any candidate containing one is
 * dropped, which is what stops a missing terminator from turning half a page into a bidder.
 */
const NOT_A_NAME = [
  "que ",
  "segun consta",
  "según consta",
  "de conformidad",
  "criterio",
  "dictamen",
  "resuelve",
  "considerando",
  "atento",
  "visto",
  "articulo",
  "artículo",
  "fs.",
  "acta",
  "comision asesora",
  "comisión asesora",
  "adjudicar",
  "por un monto",
  "cumplen",
  "no cumplen",
  "descalific",
  "quedan",
  "rechaz",
  "las ofertas",
  "de las firmas",
];

/**
 * How many lowercase-initial words a candidate may contain before it is prose rather than a name.
 *
 * THE general defence, and the one that matters. The legal-form escape hatch below has to accept
 * Title Case names — real actas write "Alixpa SA", "Salomon Najson e Hijo Ltda" — and that same
 * hatch let a whole clause through on acta 1127664: "quedan descalificadas las ofertas de las
 * firmas Confir SA" ends in a legal form and would otherwise have been published as a bidder.
 * A firm name carries at most a connective or two ("e Hijo", "y Asociados"); a sentence carries
 * many. Three is the line.
 */
const MAX_LOWERCASE_WORDS = 2;

/**
 * Clauses that get glued onto the LAST item of a list, because the sentence continues past it.
 * Observed: "5) SEVICOL LIMITADA según consta en Acta obrante a fs. 319." Cutting at the clause
 * rescues the name; rejecting the whole candidate (the first cut of this parser did) silently
 * dropped the final bidder of every numbered list.
 */
const TAIL_CLAUSES = [
  "segun consta",
  "conforme",
  "obrante",
  "de acuerdo",
  "que se detalla",
  "por un monto",
  "cuyo objeto",
];

/**
 * Legal-form tokens. A candidate carrying one is a firm even if its casing is unusual.
 */
const LEGAL_FORMS = /\b(s\.?a\.?s?\.?|ltda\.?|s\.?r\.?l\.?|sociedad anonima|cooperativa|unipersonal)\b/i;

/** Trailing/leading noise around a captured name. */
function cleanName(raw: string): string | null {
  let name = raw.replace(/\s+/g, " ").trim();

  // ORDER MATTERS. The trailing clause goes first: the last item of a list carries the rest of the
  // sentence with it, and that tail can contain its own colon further along. Cutting on the colon
  // first threw away the final bidder of every numbered list — "5) SEVICOL LIMITADA según consta en
  // Acta obrante a fs. 319. … III) Que con las ofertas recibidas … DIVISA DE COMPARACION:" collapsed
  // to whatever followed that last colon.
  const foldedRaw = fold(name);
  for (const clause of TAIL_CLAUSES) {
    const at = foldedRaw.indexOf(fold(clause));
    if (at > 0) {
      name = name.slice(0, at).trim();
      break;
    }
  }

  // A connective phrase can precede the first name inside the same comma-delimited chunk:
  // "…los siguientes oferentes, tratándose de las firmas: FIGUEREDO ZEBALLOS NADIA SOLEDAD".
  // Keep only what follows that colon. Bounded to the start of the chunk, because a colon further
  // in belongs to the acta's next sentence, not to a lead-in.
  const colon = name.lastIndexOf(":");
  if (colon !== -1 && colon <= 80) name = name.slice(colon + 1).trim();

  name = name
    .replace(/^[\s·•*\-–—.,;:0-9)\]]+/, "")
    // A leading conjunction survives when the list separator was the comma and the last item reads
    // "… , y MARTINEZ FERNANDEZ HAYDEE ROXANA". Observed in the corpus.
    .replace(/^(?:y|e)\s+/i, "")
    .replace(/\s+(?:y|e)$/i, "")
    .replace(/[\s.,;:]+$/, "")
    .trim();

  if (name.length < MIN_NAME || name.length > MAX_NAME) return null;
  const folded = fold(name);
  if (NOT_A_NAME.some((w) => folded.includes(fold(w)))) return null;
  // A candidate with no letters is a page/figure reference, not a firm.
  if (!/[a-záéíóúñü]/i.test(name)) return null;

  // MOJIBAKE GUARD. Older actas embed fonts with a non-WinAnsi encoding, so the hex operands decode
  // to garbage: acta 878024 yielded "COOPERATIVA DE TEJEDORAS DE DOLORES. I\" and "IOREIRA FEDERTCO
  // ANDRES. PEÑALVA ISLAS PEL]ROALBERTO". None of these characters belongs in a firm name, and
  // publishing a mangled name next to a real contract is worse than publishing nothing.
  if (/[\\\][|{}<>^~`_]/.test(name)) return null;

  // THE discriminator. In every acta observed, bidder names are written in FULL CAPS while the
  // surrounding resolution is ordinary prose. Without this, a list split on commas happily turns
  // "rechazar la totalidad de las ofertas presentadas dejando sin efecto el presente llamado,
  // dictando el acto administrativo respectivo" into two "bidders". A lower-case candidate is
  // accepted only when it carries an explicit legal form, so an acta that writes "Grama Ltda."
  // still works while prose does not.
  const hasLowercase = /[a-záéíóúñü]/.test(name);
  if (hasLowercase && !LEGAL_FORMS.test(name)) return null;

  // …and the general prose guard, which is what actually stops a clause ending in "SA".
  const lowercaseWords = name.split(/\s+/).filter((w) => /^[a-záéíóúñü]/.test(w)).length;
  if (lowercaseWords > MAX_LOWERCASE_WORDS) return null;

  return name;
}

/**
 * Split the captured segment into candidate names.
 *
 * Three shapes appear in the corpus and all three are handled by splitting on whichever separator
 * the segment actually uses:
 *   - bullets:   "· GRAMA LTDA. · PASCUAL AMOROSO E HIJOS S.A.S."
 *   - numbered:  "1) C.I.E.M.S.A.; 2) M D CERVINI S.A.; 3) PROSEGUR ... y 5) SEVICOL LIMITADA"
 *   - commas:    "FIGUEREDO ZEBALLOS NADIA SOLEDAD, BARRETO TEJERA CARLOS HIGINIO, y PIMIENTA PEREZ..."
 */
function splitSegment(segment: string): string[] {
  if (/[·•]/.test(segment)) {
    return segment.split(/[·•]/);
  }
  if (/\d\s*\)/.test(segment)) {
    return segment.split(/\d\s*\)/);
  }
  // Comma/semicolon list, with a final " y " before the last item.
  return segment.split(/[;,]|\sy\s/);
}

/**
 * Cut the segment that should hold the enumeration: from just after the marker to the first
 * terminator that means the acta moved on.
 */
function captureSegment(text: string, from: number): string {
  const window = text.slice(from, from + WINDOW_CHARS);
  // A lettered section header ("H) CRITERIO Y DICTAMEN:") or a roman-numeral clause ends the list.
  const stop = window.search(/\n\s*[A-Z]\)\s|\b(?:I{1,3}|IV|V|VI{0,3})\)\s|-{5,}/);
  const cut = stop > 20 ? window.slice(0, stop) : window;
  // Drop a leading colon left over from the marker.
  return cut.replace(/^[\s:]+/, "");
}

/**
 * Recover the bidders an acta enumerates, or null when it does not.
 *
 * `null` is the common and correct outcome — measured at roughly 92% of actas — and must never be
 * rendered as "one bidder" or "no competition".
 */
export function parseActaBidders(rawText: string): ActaBidders | null {
  if (!rawText || rawText.length < 40) return null;
  // Control bytes leak out of the PDF text layer; they break both matching and display.
  const text = rawText.replace(/[ --]/g, "");
  const { flat, map } = despace(text);

  for (const marker of MARKERS) {
    const at = flat.indexOf(marker.needle);
    if (at === -1) continue;
    const afterFlat = at + marker.needle.length;
    if (afterFlat >= map.length) continue;
    const from = map[afterFlat]!;

    const segment = captureSegment(text, from);
    const names: string[] = [];
    for (const candidate of splitSegment(segment)) {
      const name = cleanName(candidate);
      if (name && !names.some((n) => fold(n) === fold(name))) names.push(name);
    }
    // One name is not an enumeration — it is far more likely a sentence fragment that survived
    // cleaning. Requiring two is what keeps this honest; a genuine sole bidder is reported through
    // the explicit SOLE_BIDDER_MARKERS below, where the acta says so in words.
    if (names.length >= 2) {
      return {
        bidders: names,
        count: names.length,
        marker: marker.label,
        excerpt: text.slice(Math.max(0, from - 120), from + Math.min(segment.length, 320)).replace(/\s+/g, " ").trim(),
      };
    }
  }

  for (const sole of SOLE_BIDDER_MARKERS) {
    const at = flat.indexOf(sole.needle);
    if (at === -1) continue;
    const from = map[Math.min(at, map.length - 1)]!;
    return {
      bidders: [],
      count: 1,
      marker: sole.label,
      excerpt: text.slice(Math.max(0, from - 160), from + 260).replace(/\s+/g, " ").trim(),
    };
  }

  return null;
}
