import type { IPliegoSummary } from "../types/monitor";

export type PliegoSummaryContent = Omit<
  IPliegoSummary,
  "model" | "generatedAt" | "sourceDocs" | "unreadableDocs" | "disclaimer" | "docsSignature"
>;

export interface OfficialPliegoDates {
  reception?: Date | string | undefined;
  enquiries?: Date | string | undefined;
}

export interface VerifiedPliegoFacts {
  opening?: string | undefined;
  execution?: string | undefined;
  requirements: string[];
  documents: string[];
  quotation: string[];
  guarantees: string[];
  evaluation: string[];
  observations: string[];
  noMarketReserve: boolean;
  priceOnlyEvaluation: boolean;
}

function textValue(value: unknown): string | undefined {
  if (typeof value === "string") return value.trim() || undefined;
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (!value || typeof value !== "object" || Array.isArray(value)) return undefined;
  const parts = Object.entries(value)
    .map(([key, item]) => {
      const text = textValue(item);
      if (!text) return undefined;
      const label = key.replace(/([a-z])([A-Z])/g, "$1 $2").toLocaleLowerCase("es");
      return `${label}: ${text}`;
    })
    .filter((item): item is string => Boolean(item));
  return parts.length ? parts.join("; ") : undefined;
}

function textArray(value: unknown): string[] {
  const values = Array.isArray(value) ? value : value === undefined || value === null ? [] : [value];
  return values.map(textValue).filter((item): item is string => Boolean(item));
}

/** Repairs common free-model schema drift before content reaches storage/UI. */
export function normalizeGeneratedPliegoSummary(value: unknown): PliegoSummaryContent {
  const source = value && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : {};
  const rawDeadlines = source.plazos && typeof source.plazos === "object" && !Array.isArray(source.plazos)
    ? source.plazos as Record<string, unknown>
    : {};
  const reception = textValue(rawDeadlines.recepcionOfertas);
  const opening = textValue(rawDeadlines.aperturaOfertas);
  const enquiries = textValue(rawDeadlines.consultas);
  const quotation = textValue(source.formaCotizacion);
  const execution = textValue(source.plazoEjecucion);
  const guarantees = textValue(source.garantias);
  const reference = textValue(source.montoReferencia);
  return {
    objeto: textValue(source.objeto) ?? "No se pudo determinar el objeto a partir del texto extraído.",
    requisitosClave: textArray(source.requisitosClave),
    documentacionRequerida: textArray(source.documentacionRequerida),
    plazos: {
      ...(reception ? { recepcionOfertas: reception } : {}),
      ...(opening ? { aperturaOfertas: opening } : {}),
      ...(enquiries ? { consultas: enquiries } : {}),
    },
    criteriosEvaluacion: textArray(source.criteriosEvaluacion),
    observaciones: textArray(source.observaciones),
    ...(quotation ? { formaCotizacion: quotation } : {}),
    ...(execution ? { plazoEjecucion: execution } : {}),
    ...(guarantees ? { garantias: guarantees } : {}),
    ...(reference ? { montoReferencia: reference } : {}),
  };
}

function normalize(text: string): string {
  return text
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, " ")
    .toLocaleLowerCase("es")
    .trim();
}

function add(target: string[], value: string, condition: boolean): void {
  if (condition && !target.includes(value)) target.push(value);
}

function find(text: string, pattern: RegExp): RegExpExecArray | null {
  const global = new RegExp(pattern.source, `${pattern.flags.replace(/g/g, "")}g`);
  let current: RegExpExecArray | null;
  let last: RegExpExecArray | null = null;
  while ((current = global.exec(text)) !== null) last = current;
  return last;
}

export function formatOfficialPliegoDate(value: Date | string | undefined): string | undefined {
  if (!value) return undefined;
  const date = value instanceof Date ? value : new Date(value);
  if (!Number.isFinite(date.getTime())) return undefined;
  const parts = new Intl.DateTimeFormat("es-UY", {
    // The Compras Estatales projection stores Uruguay's wall-clock value in a
    // BSON Date without an offset (10:00 official arrives as 10:00Z). Preserve
    // those clock fields; converting to America/Montevideo would subtract 3h.
    timeZone: "UTC",
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hourCycle: "h23",
  }).formatToParts(date);
  const part = (type: Intl.DateTimeFormatPartTypes): string => parts.find(item => item.type === type)?.value ?? "";
  return `${part("day")}/${part("month")}/${part("year")} ${part("hour")}:${part("minute")}`;
}

/**
 * Extracts only high-confidence facts whose wording is sufficiently explicit to
 * verify without another model call. It complements, rather than replaces, the
 * semantic summary generated by the free provider.
 */
export function extractVerifiedPliegoFacts(texts: string[]): VerifiedPliegoFacts {
  const text = normalize(texts.join("\n"));
  const requirements: string[] = [];
  const documents: string[] = [];
  const quotation: string[] = [];
  const guarantees: string[] = [];
  const evaluation: string[] = [];
  const observations: string[] = [];

  const openingMatch = find(text, /fecha\s+de\s+apertura\s*:?\s*(\d{1,2}\/\d{1,2}\/\d{4}).{0,40}?hora\s*:?\s*(\d{1,2}:\d{2})/i);
  const opening = openingMatch ? `${openingMatch[1]} ${openingMatch[2]}` : undefined;

  const executionMatch = find(text, /plazo\s+(?:total\s+)?(?:del\s+contrato|de\s+ejecucion)[\s\S]{0,160}?(\d+)\s+mes(?:es)?[\s\S]{0,300}?(?:prorroga|prorrogable)[\s\S]{0,80}?(\d+)\s+dias/i)
    ?? find(text, /duracion\s+(?:del\s+contrato)?[\s\S]{0,120}?(\d+)\s+mes(?:es)?[\s\S]{0,300}?(?:prorroga|prorrogable)[\s\S]{0,80}?(\d+)\s+dias/i);
  const execution = executionMatch
    ? `${executionMatch[1]} meses, con prórroga de hasta ${executionMatch[2]} días`
    : undefined;

  add(requirements, "Inscripción en RUPE en estado Ingreso o Activo; quien firma debe estar autorizado", /rupe.{0,90}(?:ingreso|activo)/i.test(text));
  add(requirements, "Seguro de accidentes de trabajo conforme a la Ley 16.074", /seguro.{0,80}(?:accidentes\s+de\s+trabajo|ley\s+16\.?074)/i.test(text));
  const staff = find(text, /(?:minimo(?:\s+de)?|no\s+menor\s+a)\s+(\d+)\s+(?:operarios|personas|funcionarios|trabajadores)/i);
  if (staff) add(requirements, `Disponer de al menos ${staff[1]} integrantes para el servicio`, true);
  add(requirements, "Contar con representante técnico permanente", /representante\s+tecnico.{0,50}(?:permanente|durante)/i.test(text));
  add(requirements, "Realizar la visita obligatoria; su constancia es requisito de admisibilidad", /visita.{0,100}(?:obligatoria|excluyente|admisibilidad)/i.test(text));

  add(documents, "Formulario de oferta correspondiente", /(?:formulario|anexo)\s+(?:de\s+)?oferta|oferta.{0,40}anexo\s+[ivx]+/i.test(text));
  add(documents, "Carta poder, cuando quien presenta la oferta no esté autorizado en RUPE", /carta\s+poder/i.test(text));
  add(documents, "Constancia de visita", /constancia.{0,35}visita|visita.{0,35}constancia/i.test(text));
  add(documents, "Nómina del personal propuesto", /(?:nomina|listado).{0,45}personal|anexo\s+vi.{0,60}personal/i.test(text));
  add(documents, "Listado de equipos, materiales y marcas ofrecidas", /listado.{0,80}(?:equipos|materiales)|(?:equipos|materiales).{0,80}marcas/i.test(text));
  add(documents, "Fichas técnicas y de seguridad de los productos", /fichas?\s+(?:tecnicas?|de\s+seguridad)/i.test(text));

  add(quotation, "Cotización en pesos uruguayos", /(?:cotizar|cotizacion|precios?).{0,80}(?:pesos\s+uruguayos|\buyu\b)/i.test(text));
  add(quotation, "IVA discriminado en la oferta", /iva.{0,60}discrimin|discrimin.{0,60}iva/i.test(text));
  add(quotation, "Un único lote; no se admiten ofertas parciales", /(?:unico|1)\s+lote.{0,100}no.{0,30}(?:ofertas?\s+)?parcial|no\s+se\s+admiten\s+ofertas?\s+parciales/i.test(text));
  const maintenance = find(text, /mantenimiento\s+de\s+(?:la\s+)?oferta[^.;]{0,80}?(\d+)\s+dias/i);
  if (maintenance) add(quotation, `Mantenimiento de oferta: ${maintenance[1]} días`, true);
  add(quotation, "Ajuste paramétrico: 80% salarios y 20% IPC", /80\s*%.{0,50}(?:salario|laudo).{0,100}20\s*%.{0,30}ipc/i.test(text));
  add(quotation, "Pago a 30 días", /pago.{0,50}30\s+dias/i.test(text));

  const noMaintenance = /garantia\s+de\s+mantenimiento\s+de\s+(?:la\s+)?oferta.{0,100}no.{0,25}(?:obligatoria|exigida)|no.{0,25}(?:obligatoria|exigida).{0,100}garantia\s+de\s+mantenimiento/i.test(text);
  add(guarantees, "La garantía de mantenimiento de oferta no es obligatoria", noMaintenance);
  add(guarantees, "Retirar la oferta durante su vigencia puede generar una multa del 5%", noMaintenance && /retiro.{0,130}5\s*%/i.test(text));
  add(guarantees, "Garantía de fiel cumplimiento: 5% del monto adjudicado, cuando corresponda", /garantia.{0,40}(?:fiel|cumplimiento).{0,100}5\s*%/i.test(text));
  add(guarantees, "Garantía por obligaciones laborales de tercerizaciones: 5%", /garantia.{0,100}(?:terceriz|laboral).{0,100}5\s*%/i.test(text));

  const priceOnlyEvaluation = /(?:unico|solo)\s+factor.{0,30}precio|evaluacion.{0,60}exclusivamente.{0,30}precio/i.test(text);
  add(evaluation, "Evaluación por precio entre las ofertas admisibles", priceOnlyEvaluation);
  add(evaluation, "Preferencia a la industria nacional, cuando corresponda", /preferencia.{0,50}(?:industria|producto|servicio)\s+nacional/i.test(text));
  const noMarketReserve = /(?:reserva\s+de\s+mercado.{0,80}no\s+(?:aplica|corresponde)|no\s+(?:aplica|corresponde).{0,80}reserva\s+de\s+mercado)/i.test(text);
  add(evaluation, "No aplica el mecanismo de reserva de mercado", noMarketReserve);

  add(observations, "Multa de 0,5 UR por inasistencias, según las condiciones del pliego", /0[,.]5\s*ur.{0,80}(?:inasistencia|ausencia)|(?:inasistencia|ausencia).{0,80}0[,.]5\s*ur/i.test(text));
  add(observations, "Cinco o más incumplimientos pueden incrementar las multas en 10%", /(?:cinco|5).{0,40}incumplimientos?.{0,100}10\s*%/i.test(text));
  add(observations, "Un incumplimiento puede generar una multa del 10% sobre el precio mensual", /incumplimiento.{0,180}multa.{0,30}10\s*%.{0,50}precio\s+mensual|multa.{0,30}10\s*%.{0,50}precio\s+mensual/i.test(text));
  add(observations, "Multas acumuladas superiores al 30% mensual pueden causar rescisión", /multa.{0,300}30\s*%[\s\S]{0,180}rescision/i.test(text));
  add(observations, "OSE no admite ofertas en línea para este procedimiento", /no.{0,30}(?:admite|permite).{0,40}ofertas?.{0,20}(?:en\s+linea|online)/i.test(text));

  return {
    opening,
    execution,
    requirements,
    documents,
    quotation,
    guarantees,
    evaluation,
    observations,
    noMarketReserve,
    priceOnlyEvaluation,
  };
}

function merge(primary: string[], secondary: string[], limit = 12): string[] {
  const result: string[] = [];
  for (const item of [...primary, ...secondary]) {
    const value = item?.trim();
    if (!value || result.some(existing => normalize(existing) === normalize(value))) continue;
    result.push(value);
    if (result.length >= limit) break;
  }
  return result;
}

/** Makes official dates and explicit clauses authoritative over model guesses. */
export function applyVerifiedPliegoFacts(
  generated: PliegoSummaryContent,
  facts: VerifiedPliegoFacts,
  officialDates: OfficialPliegoDates = {},
): PliegoSummaryContent {
  const verifiedRequirements = normalize(facts.requirements.join(" "));
  const maintenanceNotRequired = facts.guarantees.some(item => normalize(item).includes("no es obligatoria"));
  const requirements = generated.requisitosClave.filter(item => {
    const value = normalize(item);
    if (verifiedRequirements.includes("rupe") && value.includes("rupe")) return false;
    if (verifiedRequirements.includes("visita obligatoria") && value.includes("visita")) return false;
    if (/\bal menos \d+ integrantes\b/.test(verifiedRequirements) && /(?:operarios|personas|funcionarios|trabajadores)/.test(value)) return false;
    if (maintenanceNotRequired && /garantia.{0,40}mantenimiento.{0,20}oferta/.test(value)) return false;
    return true;
  });
  const criteria = generated.criteriosEvaluacion.filter(item => {
    const value = normalize(item);
    if (facts.noMarketReserve && value.includes("reserva de mercado")) return false;
    if (facts.priceOnlyEvaluation && /(puntaje|calificacion|antecedente|experiencia)/.test(value)) return false;
    return true;
  });
  const reception = formatOfficialPliegoDate(officialDates.reception);
  const enquiries = formatOfficialPliegoDate(officialDates.enquiries);

  return {
    ...generated,
    requisitosClave: merge(facts.requirements, requirements),
    documentacionRequerida: merge(facts.documents, generated.documentacionRequerida),
    formaCotizacion: facts.quotation.length
      ? merge(facts.quotation, generated.formaCotizacion ? [generated.formaCotizacion] : [], 8).join("; ")
      : generated.formaCotizacion,
    plazos: {
      ...generated.plazos,
      ...(reception ? { recepcionOfertas: reception } : {}),
      ...(facts.opening ? { aperturaOfertas: facts.opening } : {}),
      ...(enquiries ? { consultas: enquiries } : {}),
    },
    plazoEjecucion: facts.execution ?? generated.plazoEjecucion,
    garantias: facts.guarantees.length ? facts.guarantees.join("; ") : generated.garantias,
    criteriosEvaluacion: merge(facts.evaluation, criteria, 10),
    observaciones: merge(facts.observations, generated.observaciones),
  };
}
